goharbor/harbor

src/registryctl/api/registry/manifest/manifest.go
Return not found error if gets the driver PathNotFound.
=> handle path not found when to delete manifest

src/chartserver/client.go
In some perspectives to reduce the too many charts performence issue
=> Enhance: Prolong the timeout of chartclient

src/controller/event/handler/internal/artifact.go
fixes #12574
let the tag ID as 0 when tags array is empty when to update pull time
=> fix update pull time issue

src/common/utils/ldap/ldap.go, src/common/utils/ldap/ldap_test.go, src/core/auth/ldap/ldap.go, tests/ldap_test.ldif
Search ldap group name with default ldap group attribute name
fixes #10940
=> Set LDAP groupname when PopulateGroup

src/controller/p2p/preheat/enforcer.go, src/pkg/p2p/preheat/job.go, src/pkg/p2p/preheat/job_test.go
- add job stop check points in preheat job
- add missing digest property for the preheat request sent to the provider
=> fix(preheat):enhance preheat job

src/jobservice/job/impl/gc/garbage_collection.go, src/jobservice/job/impl/gc/garbage_collection_test.go
To handle the orphan blobs that created in the quota exceeding case deletion, remove the limition of artifact remove.
=> remove limitation of artifact in the GC job

src/server/middleware/security/oidc_cli.go, src/server/middleware/security/oidc_cli_test.go
This commit makes OIDC CLI secret filter allow more URLs so that the
OIDC CLI secret can be used for replication
=> Refine request checking for OIDC CLI secret

api/v2.0/swagger.yaml, src/server/v2.0/handler/auditlog.go, src/server/v2.0/handler/project.go
use the format: date-time as the format of audit op_time, then it could be rendered by FF and Chrome.
=> update time format of audit log

tests/robot-cases/Group0-Util/notary-remove-image-signature.expect
Instead of explicitly defining the expect path to /usr/local/bin/expect,
use the env command, so the expect executable is searched for and launched
from wherever it is first found.
Signed-off-by: Flávio Ramalho <framalho@suse.com>
=> Make notary-remove-image-signature more flexible

src/replication/adapter/aliacr/adapter.go
fix #12621
Aliyun replication adapter can't filter specific repo name, like 'abcde/busybox', it will replicate all images under namespace abcde
=> fix[replicatioin] aliyun acr pull with repo filter

src/jobservice/job/impl/gc/garbage_collection.go, src/jobservice/job/impl/gc/garbage_collection_test.go
Remove the artifact trash record after manifest delete success.
Don't use the flush method is because that when all of records are removed, only GC job knows these informations, and they are in the memory. Once the jobservice is crashed and restarted at GC job execution phase, the trash records are lost, then these manifest are become orphan manifests, cannot be removed any more.
=> update GC job

api/v2.0/swagger.yaml
When we use harbor swagger generate client,  when api return error, it will return json unmarshal to models.Errors,  after check the swagger yaml, the definition in swagger is not same as api result.
=> fix(swagger): fix the definition of errors

make/photon/chartserver/Dockerfile.base, make/photon/clair-adapter/Dockerfile.base, make/photon/clair/Dockerfile.base, make/photon/core/Dockerfile.base, make/photon/jobservice/Dockerfile.base, make/photon/nginx/Dockerfile.base, make/photon/notary-server/Dockerfile.base, make/photon/notary-signer/Dockerfile.base, make/photon/portal/Dockerfile.base, make/photon/redis/Dockerfile.base, make/photon/registry/Dockerfile.base, make/photon/registryctl/Dockerfile.base, make/photon/trivy-adapter/Dockerfile.base
Notably missing is the "log" image, which still uses sudo.
Relatedly, it might be useful to include `security_opt: [ 'no-new-privileges' ]` in the generated `docker-compose.yml` to avoid the ability of a setuid binary to elevate privileges in the containers.
=> Remove unused "sudo" package from most images

src/controller/proxy/controller.go, src/controller/proxy/controller_test.go, src/controller/proxy/local.go, src/controller/proxy/local_test.go, src/controller/proxy/remote.go, src/server/middleware/repoproxy/proxy.go
Change method UseLocalManifest to avoid pull manifest from remote repo frequently
=> Fix #12487: Proxy cache create duplicated operation log

make/photon/clair-adapter/Dockerfile.base, make/photon/core/Dockerfile.base, make/photon/jobservice/Dockerfile.base, make/photon/nginx/Dockerfile.base, make/photon/notary-server/Dockerfile.base, make/photon/notary-signer/Dockerfile.base, make/photon/portal/Dockerfile.base, make/photon/registry/Dockerfile.base, make/photon/registryctl/Dockerfile.base, make/photon/trivy-adapter/Dockerfile.base
The latest `photon:2.0` does not include `groupadd` and `useradd`
we need to install `shadow` package which includes these commands.
=> chore(images): install shadow package in base images

src/pkg/blob/models/blob.go
fixes #12720
The GC job doesn't remove the manifest of scheme1.MediaTypeSignedManifest as it's recognized by GC job.
=> fix gc remove manifest issue

api/v2.0/legacy_swagger.yaml
According to the spec of swagger, https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types, the integer type support int64, so we will only format the value of ResourceList as int64 to fix this issue.
Closes #12482
=> fix(swagger): format the value of ResourceList as int64

make/prepare
Mount `/` dir in container require privilege
And this change will make `z` label useless. So remove them
=> Fix: Add privileged for prepare command

make/migrations/postgresql/0040_2.1.0_schema.up.sql, src/migration/artifact.go, src/migration/migration.go
Use a separated database table to store the data version.
Fixes #12747
=> Use a separated database table to store the data version

src/controller/event/metadata/artifact.go, src/controller/event/metadata/artifact_test.go, src/controller/proxy/controller.go, src/controller/proxy/local.go, src/server/registry/manifest.go
Fixes #12741: error sql: transaction has already been committed or rolled back
=> Use orm.Context instead request context in background go routing

src/portal/src/app/sign-in/sign-in.component.html
As mentioned in #10712 forgot password should be removed. The
dialog was left in place.
See #12745
=> remove reset password dialog from sign-in component

src/core/service/token/authutils.go
This commit updates the way token service handles invalid resource, for
example a resource without projectname.
It will clear the requested access instead of returning 500 error.
=> Token service handling invalid resource

api/v2.0/swagger.yaml, src/server/v2.0/handler/artifact.go
Disable the tag creation for the artifact under a proxy cache project
Fixes #12713
=> Disable the tag creation for the artifact under a proxy cache project

.github/workflows/CI.yml
Add 1 hour(60 minutes) as the timeout of gitactions.
=> add timeout for CI

src/core/api/admin_job.go
Return 409 on triggering a GC job when there is a job ongoing.
=> fix gc job submit issue

src/server/middleware/csrf/csrf.go, src/server/middleware/csrf/csrf_test.go
The current approach will prevent the effectiveness of `Cache-Control`
header and gorilla's library add `Vary:Cookie` header in all responses.
We will set the token in a header of response so the response can be
cached when needed.
=> Store csrf token in the header of response instead of cookie

make/migrations/postgresql/0040_2.1.0_schema.up.sql, src/pkg/task/dao/execution.go, src/pkg/task/dao/execution_test.go, src/pkg/task/dao/model.go, src/pkg/task/execution.go, src/pkg/task/execution_test.go, src/pkg/task/hook.go, src/pkg/task/hook_test.go, src/pkg/task/mock_execution_dao_test.go, src/pkg/task/model.go, src/server/handler/job_status_hook.go
Refresh the status of execution for every status changing of task to support filtering executions by status directly
=> Refresh the status of execution for every status changing of task

src/portal/src/app/services/intercept-http.service.spec.ts, src/portal/src/app/services/intercept-http.service.ts, src/portal/src/lib/utils/shared/shared.module.ts, src/server/middleware/csrf/csrf.go, src/server/middleware/csrf/csrf_test.go
The current approach will prevent the effectiveness of `Cache-Control`
header and gorilla's library add `Vary:Cookie` header in all responses.
This PR sets the token in a header of response so the response can be
cached when needed.  It involves code change in both UI and backend middleware.
=> CSRF token cookie -> header 

.github/workflows/CI.yml, .github/workflows/conformance_test.yml, CONTRIBUTING.md
In the previous change #12809 I missed a few places. This
should be complete now.
=> Update all references of Golang to 1.14.7

make/migrations/postgresql/0040_2.1.0_schema.up.sql, src/pkg/blob/dao/dao.go, src/pkg/blob/dao/dao_test.go, src/pkg/blob/models/blob.go
fixes #12849
1, gives a default value to blob status in the migration script, and use none to replace the empty as the StatusNone
2, makes StatusDelete can be marked as StatusDelete as GC jobs marks all of blobs as StatusDelete in the mark phase, but if encounter any
failure in the sweep phase, user wants to execute the GC again. But it will fail if theStatusDelete can be marked as StatusDelete again.
=> fix upgrade issue

make/photon/prepare/templates/registry/config.yml.jinja
fix #12733
registry doesn't set any timeout when connect redis
=> fix(jobservice) redis sentinel failover hang

make/migrations/postgresql/0031_2.0.3_schema.up.sql
fixes #12827
After user migrates Harbor from v2.0.2, user got 404 when to pull specific images, and no work after push the same images again.
Fix:
1, If the issue is caused by missing repository data, this fix can revert the missing repository data and all things should be fine.
2, If the issue is caused by missing blob data, this fix can revert the missing repository data and still left the media type of artifact
as 'UNKNOWN', which leads the meta data and build history of the image cannot be shown in UI. User can delete and push the image again to
resolve it.
=> fix db migration issue

src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.spec.ts, src/portal/src/lib/components/endpoint/endpoint.component.spec.ts, src/replication/adapter/awsecr/adapter.go, src/replication/adapter/awsecr/adapter_test.go
Add aws China regions ECR support, both of cn-north-1 and cn-northwest-1 endpoints.
Copy origin PR from https://github.com/goharbor/harbor/pull/12264
=> Add aws China regions ECR support

make/migrations/postgresql/0031_2.0.3_schema.up.sql
fixes #12889
Before the migration script to fix the nativate repo_id issue, is has to remove the duplicate tags
from the tag table, which may caused by user in v2.0.2 to retag & repush the missing image.
=> fix migration issue

.github/workflows/CI.yml, tests/ci/api_common_install.sh, tests/robot-cases/Group0-BAT/API_DB.robot
1. Python API test can't import packages from swagger maker, the reason is that python install packages to site-packages instead of dist-packages,
so the current solution is to copy pakages from site back to dist, I will try to find a way of using ENV variable to fix this;
2. Remove a python library no longer be used.
=> Fix issue of missing swagger package for python API test

src/core/main.go
RemoveImmutableScanners may delete the default scanner, so move it
before the EnsureScanners.
Closes #12938
=> fix(scanner): move RemoveImmutableScanners before EnsureScanners

src/server/middleware/contenttrust/contenttrust.go
This commit ensures that when CLI is pulling a tag, the content trust middleware check the data in notary to ensure the particular tag is signed, not only the digest.
=> Check the tag in isArtifactSigned func

src/server/middleware/contenttrust/contenttrust.go
This commit ensures that when CLI is pulling a tag, the content trust middleware check the data in notary to ensure the particular tag is signed, not only the digest.
=> Check the tag in isArtifactSigned func -- cherrypick to 2.1

src/core/api/base.go, src/server/middleware/security/auth_proxy_test.go, src/server/middleware/security/basic_auth_test.go, src/server/middleware/security/security_test.go, src/server/middleware/security/session.go, src/server/middleware/security/session_test.go
This commit makes a change so that the user id will be stored in sessoin
after user login instead of user model to avoid data inconsistency when
user model changes.
Fixes #12934
=>  [CherryPick - 2.1] Store User ID in session instead of the whole user model

src/common/models/project.go, src/server/middleware/repoproxy/proxy.go, src/server/middleware/repoproxy/proxy_test.go, src/server/v2.0/handler/artifact.go, src/server/v2.0/handler/project.go
Ignore enable_content_trust metadata for proxy cache project, see
https://github.com/goharbor/harbor/issues/12940 to get more info
=> feat(project): ignore enable_content_trust for proxy project

src/core/api/base.go, src/server/middleware/security/auth_proxy_test.go, src/server/middleware/security/basic_auth_test.go, src/server/middleware/security/security_test.go, src/server/middleware/security/session.go, src/server/middleware/security/session_test.go
This commit makes a change so that the user id will be stored in sessoin
after user login instead of user model to avoid data inconsistency when
user model changes.
Fixes #12934
=> Store User ID in session instead of the whole user model

src/core/main.go
RemoveImmutableScanners may delete the default scanner, so move it
before the EnsureScanners.
Closes #12938
=> [Cherry pick]fix(scanner): move RemoveImmutableScanners before EnsureScanners

src/common/models/project.go, src/server/middleware/repoproxy/proxy.go, src/server/middleware/repoproxy/proxy_test.go, src/server/v2.0/handler/artifact.go, src/server/v2.0/handler/project.go
Ignore enable_content_trust metadata for proxy cache project, see
https://github.com/goharbor/harbor/issues/12940 to get more info
=> [Cherry pick]feat(project): ignore enable_content_trust for proxy project

src/common/models/project.go, src/lib/orm/query.go, src/pkg/project/dao/dao_test.go, src/server/v2.0/handler/project.go
We know the user id when query projects by member, so use the user id
as entity_id directly in project_member, no need to join harbor_user
table.
Closes #12968
=> fix(project): change to use user id to query projects of member

src/common/models/project.go, src/lib/orm/query.go, src/pkg/project/dao/dao_test.go, src/server/v2.0/handler/project.go
We know the user id when query projects by member, so use the user id
as entity_id directly in project_member, no need to join harbor_user
table.
Closes #12968
=> [Cherry pick]fix(project): change to use user id to query projects of member

src/common/utils/ldap/filter.go, src/common/utils/ldap/filter_test.go, src/common/utils/ldap/ldap.go, src/common/utils/ldap/ldap_test.go, tests/ldap_test.ldif
Correct ldap search filter is enclosed with '(' and ')'
Search ldap group with the ldap group base DN instead of group DN
Fixes #12613 LDAP Group Filter and Group Base DN have no affect
=> (cherry-pick for 2.1 )Add ldap filter syntax validation when create search filter

src/common/utils/ldap/ldap.go, src/common/utils/ldap/ldap_test.go, src/core/auth/ldap/ldap.go, tests/ldap_test.ldif
Search ldap group name with default ldap group attribute name
fixes #10940
=> (cherry-pick for 2.0) Set LDAP groupname when PopulateGroup

src/common/utils/ldap/filter.go, src/common/utils/ldap/filter_test.go, src/common/utils/ldap/ldap.go, src/common/utils/ldap/ldap_test.go, src/go.mod, tests/ldap_test.ldif
Correct ldap search filter is enclosed with '(' and ')'
Search ldap group with the ldap group base DN instead of group DN
Fixes #12613 LDAP Group Filter and Group Base DN have no affect
=> (cherry-pick for 2.0 ) Add ldap filter syntax validation when create search filter

src/common/utils/ldap/filter.go, src/common/utils/ldap/filter_test.go, src/common/utils/ldap/ldap.go, src/common/utils/ldap/ldap_test.go, tests/ldap_test.ldif
Correct ldap search filter is enclosed with '(' and ')'
Fixes #12613 LDAP Group Filter and Group Base DN have no affect
=> Add ldap filter syntax validation when create search filter

tests/apitests/python/library/project.py, tests/apitests/python/library/user.py, tests/apitests/python/test_assign_role_to_ldap_group.py, tests/apitests/python/test_ldap_admin_role.py, tests/robot-cases/Group3-Upgrade/feature_map.json, tests/robot-cases/Group3-Upgrade/prepare.py
LDAP group has different role, user in group has the same role, as groups with different roles were added in project
member list, user should act like in different roles. for admin and dev role, there should be checkpoints to verify priviledges of each own.
Fixed issue: #12773
=> Add checkpoint for LDAP group py-test

src/replication/adapter/awsecr/adapter.go, src/replication/adapter/awsecr/adapter_test.go, src/replication/adapter/awsecr/auth.go
In order to support using IAM roles for Amazon EC2 Instances, that user can create a ecr replication adapter without input credentials.
some reference doc: 
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html
https://www.youtube.com/watch?v=C4AyfV3Z3xs
note: you should at least add AmazonEC2ContainerRegistryReadOnly policy to do pull-based replication and AmazonEC2ContainerRegistryFullAccess to do push-based replication.
fix https://github.com/goharbor/harbor/issues/12553
=> feature(replication) enable role based auth for AWS ECR

api/v2.0/legacy_swagger.yaml
* Add the Location Header to POST responses that use the common response
Without the header, you cannot know which object you just created.
=> fix: Location Header in swagger api common response

src/controller/artifact/processor/base/manifest.go, src/controller/artifact/processor/base/manifest_test.go, src/controller/artifact/processor/chart/chart.go, src/controller/artifact/processor/chart/chart_test.go, src/controller/artifact/processor/image/index.go, src/controller/artifact/processor/image/index_test.go, src/controller/artifact/processor/image/manifest_v2.go, src/controller/artifact/processor/image/manifest_v2_test.go
1. Abstract the "config" property(which contains labels) of config layer into the extra attributes for images
2. Try to get the author information from the "maintainer" label
fixes 12066
fixes 12734
=> Abstract more info into the extra attributes for images

src/common/config/store/driver/db.go
Solves issues like #12777 by providing an error if something fails.
=> Add error log in case encryption on config save fails

make/migrations/postgresql/0050_2.2.0_schema.up.sql, src/controller/p2p/preheat/controller.go, src/controller/p2p/preheat/controllor_test.go, src/pkg/retention/controller.go, src/pkg/retention/controller_test.go, src/pkg/scheduler/dao.go, src/pkg/scheduler/scheduler.go, src/pkg/scheduler/scheduler_test.go, src/testing/pkg/scheduler/scheduler.go
There is requirement that show the cron type(daily, weekly, etc.) on the UI, this commit adds the support for storing the cron type in the schedule model
=> Support store the cron type in the schedule

src/common/utils/oidc/helper.go
Fixes a panic in case oidc is used, and the UI is not called before a docker command is sent via /v2 api
Panic:
```
2020/09/21 08:38:52.203  [HTTP] http: panic serving 10.253.45.1:52494: interface conversion: interface {} is nil, not models.OIDCSetting
goroutine 251 [running]:
net/http.(*conn).serve.func1(0xc001080640)
/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x1d80c40, 0xc001588870)
/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/goharbor/harbor/src/common/utils/oidc.UserInfoFromToken(0x250eb40, 0xc001588570, 0xc00047a1c0, 0x1e2bc00, 0xc00047a1c0, 0x0)
/harbor/src/common/utils/oidc/helper.go:244 +0x693
github.com/goharbor/harbor/src/common/utils/oidc.(*defaultManager).VerifySecret(0x369bff0, 0x250eb40, 0xc001588570, 0xc00171e230, 0x22, 0xc00171e253, 0x20, …
```
=> fix #10913: initialize oidc provider before calling Load

codecov.yml
Referring https://docs.codecov.io/docs/fixing-paths , this commit fixes
the path to make sure the coverage changes can be viewed on codecov's
dashboard.
=> Fix path in code cov

src/controller/proxy/controller.go, src/controller/proxy/controller_test.go, src/controller/proxy/remote.go, src/server/middleware/repoproxy/proxy.go
Compare the local digest and the remote digest when pull by tag
Use HEAD request (ManifestExist) instead of GET request (GetManifest)
to avoid been throttled
For manifest list, it can avoid GET request because cached manifest list maybe
differerent with the original manifest list
Make RemoteInterface public
Fixes #13112
=> Change the condition of LocalManifest

make/photon/common/install_cert.sh, src/core/service/token/authutils.go, src/core/service/token/token_test.go, src/pkg/token/claims/v2/claims.go, src/pkg/token/claims/v2/claims_test.go, src/pkg/token/option_test.go, src/pkg/token/options.go, src/server/middleware/security/v2_token.go
This commit refactors the approach to encode a token in handler of /service/token,
by reusing pkg/token to avoid inconsistency.
=> Use pkg/token to generate JWT token

src/controller/proxy/controller.go, src/controller/proxy/controller_test.go, src/controller/proxy/remote.go, src/server/middleware/repoproxy/proxy.go
Compare the local digest and the remote digest when pull by tag
Use HEAD request (ManifestExist) instead of GET request (GetManifest) to avoid been throttled
For manifest list, it can avoid GET request because cached manifest list maybe different with the original manifest list
Make RemoteInterface public
Fixes #13112
=> (cherry-pick) Use HEAD instead of GET for dockerhub rate limit

src/server/v2.0/handler/project.go
Fixes #13303. Return the location header when creating proxy cache project
=> Return the location header when creating proxy cache project

src/common/utils/ldap/ldap.go
Avoid generate redunant info in the filter
=> Remove dup call to createGroupSearchFilter in searchGroup

src/common/config/metadata/metadatalist.go, src/common/const.go, src/common/models/config.go, src/common/utils/oidc/helper.go, src/common/utils/oidc/helper_test.go, src/common/utils/oidc/secret.go, src/common/utils/oidc/testutils.go, src/core/config/config.go, src/core/controllers/oidc.go, src/server/middleware/security/idtoken.go
Add oidc_admin_group to configuration, and make sure a token with the
group name in group claim has the admin authority.
=> Add admin group support to OIDC auth mode

tests/apitests/python/library/artifact.py, tests/apitests/python/library/containerd.py, tests/apitests/python/library/project.py, tests/apitests/python/library/registry.py, tests/apitests/python/test_proxy_cache.py, tests/ci/api_run.sh, tests/e2e-image/Dockerfile, tests/e2e-image/containerd_config.toml, tests/e2e-image/dockerd-entrypoint.sh, tests/resources/Docker-Util.robot, tests/resources/Nightly-Util.robot, tests/resources/Util.robot, tests/robot-cases/Group0-BAT/API_DB.robot
Containerd in e2e image was using native one in ubuntu, it should be updated to the latest release.
And add proxy cache py-tests including pull image/manifest list by docker and ctr CLI.
Fixed issues: #13078
=> Upgrade containerd in e2e image

.github/workflows/CI.yml
The `add-path` and `set-env` commands are deprecated and will be
disabled soon so update the CI.yml to use the new methods for these
commands.
For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> ci: update env and path commands in github actions

src/core/api/repository.go
fix https://github.com/goharbor/harbor/issues/13098
add a thread pool size for tags list, in case it takes up too much resources
=> feature(tag) add a thread pool size for tags list

src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json, src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.html, src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.scss, src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.ts, src/portal/src/lib/components/endpoint/endpoint.component.html, src/portal/src/lib/components/endpoint/endpoint.component.scss, src/portal/src/lib/components/endpoint/endpoint.component.ts, src/portal/src/lib/components/list-replication-rule/list-replication-rule.component.html, src/portal/src/lib/components/list-replication-rule/list-replication-rule.component.scss, src/portal/src/lib/components/list-replication-rule/list-replication-rule.component.ts, src/portal/src/lib/services/endpoint.service.ts
UI changes for #13244
1. hide Helm Hub option when creating registry:
2. Add deprecated mark to existed Helm Hub registry
=> Add deprecated mark to Helm Hub

api/v2.0/legacy_swagger.yaml, tests/apitests/python/library/artifact.py, tests/apitests/python/library/base.py, tests/apitests/python/library/docker_api.py, tests/apitests/python/library/repository.py, tests/apitests/python/library/tag_immutability.py, tests/apitests/python/test_assign_role_to_ldap_group.py, tests/apitests/python/test_copy_artifact_outside_project.py, tests/apitests/python/test_project_level_policy_content_trust.py, tests/apitests/python/test_proxy_cache.py, tests/apitests/python/test_push_chart_by_helm3_chart_cli.py, tests/apitests/python/test_push_cnab_bundle.py, tests/apitests/python/test_push_files_by_oras.py, tests/apitests/python/test_push_image_with_special_name.py, tests/apitests/python/test_push_index_by_docker_manifest.py, tests/apitests/python/test_push_sif_by_singularity.py, tests/apitests/python/test_retention.py, tests/apitests/python/test_scan_image_artifact.py, tests/apitests/python/test_sign_image.py, tests/apitests/python/test_tag_crud.py, tests/apitests/python/test_tag_immutability.py, tests/resources/Util.robot, tests/robot-cases/Group0-BAT/API_DB.robot
1. Add 7 API python test scripts for tag immutability;
2. Swagger file has object struct defination issue on imuutability policy rule, because
this policy is in shared with retention rule, therefore, they should be unified to
the same  type of rule;
3. Fixed a timeout issue of action keyword, waiting for a long period;
4. Add API test scripts for scan signed image.
Fixed issues: #13280, #13390
=> Add API test scripts for tag immutability and scan signed image

src/core/api/harborapi_test.go, src/core/middlewares/middlewares.go, src/server/middleware/security/security.go
The ping endpoint will be blocked when DB conns reach the max open conns
of the sql.DB which will make ping request timeout,
so skip the middlewares which will require DB conn.
=> feat: skip middlewares require db for ping

make/photon/portal/Dockerfile
This allows Trivy and other vulnerability scanners to correctly
determine the embedded dependencies in minified harbor-portal image.
Also simplify build process by reducing the number of layers in the
final stage container image
Signed-off-by: Dirk Mueller <dirk@dmllr.de>
Related to : https://github.com/goharbor/harbor/issues/13492
=> Include package.json/package-lock.json in portal image

tests/integration.sh
Due to docker hub access limitation, add docker login with credential
before building harbor package
=> Add docker login with credential before building harbor package

src/pkg/artifact/dao/dao.go
Don't escape the name when doing the exact matching for tag
Fixes #13106
=> Don't escape the name when doing the exact matching for tag

src/server/middleware/blob/put_manifest.go, src/server/middleware/middleware.go
Remove nop close body in the BeforeRequest helper function.
Middleware must make the request body re-readable itself when it wants
read the body in the middleware.
Closes #13556
=> fix: remove auto re-readable body in BeforeRequest

src/server/middleware/blob/put_manifest.go, src/server/middleware/middleware.go
Remove nop close body in the BeforeRequest helper function.
Middleware must make the request body re-readable itself when it wants
read the body in the middleware.
Closes #13556
=> [Cherry pick]fix: remove auto re-readable body in BeforeRequest

make/migrations/postgresql/0050_2.2.0_schema.up.sql, src/controller/quota/controller.go
1. Clean the dirty data in quota/quota_usage.
2. Ignore the fail when getting the reference of quota.
Closes #13387
=> fix(quota): ignore the fail when getting reference of quota

make/photon/prepare/templates/core/env.jinja
Includes: azure-acr, aws-ecr, google-gcr
=> Add more registry type to proxy cache

src/common/utils/ldap/ldap.go, src/common/utils/ldap/ldap_test.go, src/core/api/harborapi_test.go, src/core/api/ldap_test.go, src/testing/apitests/apilib/ldap.go
The `searchGroup` function assumed, that the input groupDN is also the DN of the result. But in case of `searchGroupByName` which is used by the `ldap/groups/search` api endpoint, the input DN is a baseDN and won't match the result. This fix will return the DN of the result.
I also added a couple of test.
Fixes #13495
=> Fix api ldap group search by name

api/v2.0/swagger.yaml, src/controller/project/controller.go, src/controller/project/options.go, src/server/v2.0/handler/project.go
default is true and don't break any existing api, and when to set it to false, the api only return the basic project infor
without meta, CVE settings and etc of the project.
=> add with details option for list project

.github/workflows/conformance_test.yml
As title.
`set-env` has been deprecated(Ref: [GitHub Actions: Deprecating set-env and add-path commands](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/))
=> Remove deprecated set-env in GitHub Actionns

src/server/middleware/v2auth/auth.go, src/server/middleware/v2auth/auth_test.go
This commit cover the cases when the port is set in one of the Host of
request or the core URL, to make sure the comparison works as expected
when the default port (80, 443) is added in only one of them.
=> Consider the default port when comparing the hosts

api/v2.0/legacy_swagger.yaml, tests/apitests/python/library/system.py, tests/apitests/python/test_system_level_scan_all.py
1. In scan all py-test, missing a important test step for checkin scan all status,
2. which indicate the ending of scan all job.
In swagger, ongoig field is missing in stats struct.
=> Fix scan all python test script issue of missing test step

api/v2.0/legacy_swagger.yaml, tests/apitests/python/library/system.py, tests/apitests/python/test_system_level_scan_all.py
1. In scan all py-test, missing a important test step for checkin scan all status,
2. which indicate the ending of scan all job.
In swagger, ongoig field is missing in stats struct.
=> Cherry-pick 2.1.0 Fix scan all python test script issue of missing test step

api/v2.0/legacy_swagger.yaml, tests/apitests/python/library/system.py, tests/apitests/python/test_system_level_scan_all.py
1. In scan all py-test, missing a important test step for checkin scan all status,
which indicate the ending of scan all job.
2. In swagger, ongoig field is missing in stats struct.
=> Cherry-pick 2.0.0 Fix scan all python test script issue of missing test step

src/lib/patterns.go, src/lib/patterns_test.go
=> Fix the pattern to match v2 catalog URI

src/core/middlewares/middlewares.go
In v2.1 security/readonly middleware will query DB by creating new
connection.
If it is put after transaction middleware there's a bigger chance of
deadlock if the concurrent open connections are set too low (#13155)
This commit mitigates that issue.  But we still need work to lower the
connections and better handle the case when http connection is closed.
=> Move security/readonly middleware ahead of transaction middleware

.github/workflows/CI.yml, tests/apitests/python/test_scan_image_artifact.py, tests/ci/api_run.sh
CI job timeout is 60 minutes, but proxy cache case timeout is 20 minutes, once
proxy cache case is timeout, it will reach CI job timeout, then cause CI job terminated
by timeout without running rest of test steps, expecially uploading useful harbor logs,
so move this test into a new clean job for saving time and debugging.
=> Move proxy cache e2e test into a new CI job

src/common/utils/utils.go
During the harbor core initialization if the database takes longer to
be ready there is a risk of deadlock when checking for the TCP connection
with the database.
The `TestTCPConn` function uses unbuffered channels to check when the
connection succeeds/timeouts. The timeout check is executed in parallel
with the connection check (this runs in a gorountine). The deadlock happens
when the goroutine execution takes longer than the function timeout
(hence setting `cancel <- 1`) and the DialTimeout call succeeds (hence
setting `success <- 1`). At this point both threads are waiting for the
channels values to be read.
This is reproducible mostly on slow systems where initializing the
database takes longer and finishes during the 5th time of the
`DialTimeout` call where it eventually exceeds the …
=> Fix deadlock on harbor-core initialization

src/controller/quota/controller_test.go
Increase the sleep time to fix the fail in TestGetReservedResources of
quota
=> test(quota): increase sleep time to fix fail of test

src/common/config/metadata/metadatalist.go, src/common/const.go, src/common/models/config.go, src/core/auth/authproxy/auth.go, src/core/config/config.go, src/core/config/config_test.go, src/pkg/authproxy/http.go, src/pkg/authproxy/http_test.go, src/server/middleware/security/auth_proxy.go, src/server/middleware/security/auth_proxy_test.go
This commit adds admin_groups into the configuration of http_auth
settings, it's a string in the form of "group1, group2".  If the token
review result shows the user is in one of the groups in the setting he
will have the administrator role in Harbor.
=> Support admin group in http authproxy

src/replication/adapter/tencentcr/adapter.go
close #13758
for standard adapter that don't have any specific credential or endpoint, it should return null in getAdapterInfo()
although currently no impact for GUI
=> fix_tencenttcr_getAdapterInfo

api/v2.0/swagger.yaml, make/migrations/postgresql/0050_2.2.0_schema.up.sql, src/pkg/scheduler/dao.go, src/pkg/scheduler/dao_test.go, src/pkg/task/dao/execution.go, src/pkg/task/dao/model.go, src/pkg/task/execution.go, src/pkg/task/execution_test.go, src/pkg/task/model.go, src/server/route.go
1. Add update time for execution
2. Add unique constraint for schedule to avoid dup records when updating policies
3. Format replication log
4. Keep the webhook handler for legacy replication jobs to avoid jobservice resending the status change request
=> Tiny fixes for task manager

src/controller/proxy/controller.go, src/controller/proxy/controller_test.go, src/controller/proxy/local.go, src/server/middleware/repoproxy/proxy.go
Fixes #13566: Quota of dockerhub is still used in v2.1.1 after the image is cached
Cache manifest list in redis cache
=> Cache manifest list for proxy cache

Makefile
Add cleanbaseimage target in Makefile, and append it to the dependencies
of the cleanall target.
Closes #13602
=> build: add cleanbaseimage target in Makefile

src/controller/robot/controller.go
fixes #13786, do not add the removed project into the permission list of a system level robot account.
=> fixes robot account list permission issue

src/controller/gc/controller.go, src/controller/gc/controller_test.go, src/server/v2.0/handler/gc.go
It needs to use the execution ID to get task firstly and then use the required task id to query GC log
=> fix gc log not found issue

make/migrations/postgresql/0050_2.2.0_schema.up.sql, src/controller/gc/model.go
1, migrate gc and scan all schedule to schedule/task/exectuion
2, migrate gc history to task/execution
=> migration admin job data

tests/apitests/python/library/artifact.py, tests/apitests/python/test_proxy_cache.py, tests/apitests/python/test_push_cnab_bundle.py, tests/apitests/python/test_push_index_by_docker_manifest.py, tests/apitests/python/test_scan_image_artifact.py
Due to complicate logic of scan report in multi-level artifacts, should add scan tests
for into manifest list and CNAB bundle python test suit.
Fixed issue: #13764
=> Add py-test for scan manifest list and CNAB bundle

src/common/const.go, src/core/api/base.go, src/core/auth/authproxy/auth.go, src/core/controllers/authproxy_redirect.go, src/server/route.go
This commit add a handler to handle the request to
"/c/authproxy/redirect".  Harbor is configured to authenticate against
an authproxy, if a request with query string `?token=xxxx`
is sent to this URI, the handler will do tokenreview according to the
setting of authproxy and simulate a `login` workflow based on the result
of token review.
=> Add handler to handle redirect via authproxy

api/v2.0/swagger.yaml, src/server/v2.0/handler/scan_all.go
Add the trigger to the metrics of the scan all job so that the customer
can know who trigger the latest scan all job.
=> feat: add trigger to the metrics of the scan all job

make/photon/common/install_cert.sh, make/photon/core/Dockerfile, make/photon/jobservice/Dockerfile
This commit fixes #13287 to remove the usage of tilde as the $HOME is not available in some
cases.  More details see #13287
=> Replace tilde in install_cert.sh

src/common/security/v2token/context.go, src/core/service/token/authutils.go, src/core/service/token/creator.go, src/core/service/token/token_test.go
This commit directly maps the actoin permission in security context to
the scope generated by the token service in harbor-core.
=> Refine the token scope generation

tests/resources/Docker-Util.robot, tests/robot-cases/Group1-Nightly/Common.robot
Remove local image right after pushing operation, then pull operation can be triggered by docker 20. 
Fixed issue: #13877.
=> Clear local images in nightly test

api/v2.0/swagger.yaml, src/server/v2.0/handler/artifact.go, src/server/v2.0/handler/artifact_test.go, src/server/v2.0/handler/assembler/vul.go, src/server/v2.0/handler/assembler/vul_test.go, src/server/v2.0/handler/base.go, src/server/v2.0/handler/base_test.go, src/server/v2.0/handler/util.go, src/testing/server/v2.0/handler/handler.go
Add X-Accept-Vulnerabilities header to the list/get artifact and get
artifact vulnerability addition APIs, and these APIs will traverse the
mime types in this header and return the first report and summary found
from the mime type.
=> feat: return scan report and summary by header

src/common/security/v2token/context.go, src/core/service/token/authutils.go, src/core/service/token/creator.go, src/core/service/token/token_test.go
This commit directly maps the actoin permission in security context to
the scope generated by the token service in harbor-core.
=> Refine the token scope generation - cherrypick to 2.0

src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/controller/scan/callback_test.go, src/pkg/task/execution.go, src/pkg/task/execution_test.go, src/testing/pkg/task/execution_manager.go
Compute the summary info for the scan all and save it to the extra attrs
of the execution.
=> feat: save summary for the scan all execution

api/v2.0/swagger.yaml, src/common/models/cve_allowlist.go, src/pkg/scan/postprocessors/report_converters.go, src/pkg/scan/report/summary.go, src/pkg/scan/vuln/report.go, src/pkg/scan/vuln/report_test.go, src/pkg/scan/vuln/summary.go, src/pkg/scan/vuln/summary_test.go
1. Remove the duplicate CVE records in the report/summary for the image
index.
2. Add scanner field in the scan overview for the API.
Closes #13913
=> feat: remove duplicate CVE in scan report and summary

make/migrations/postgresql/0050_2.2.0_schema.up.sql
The report in previous scan_report records not work well the
vulnerabilities stored in the schema table, so delete the scan_report
records.
=> chore: delete records of scan_report

src/lib/patterns.go, src/lib/patterns_test.go, src/server/middleware/v2auth/access.go, src/server/middleware/v2auth/auth.go
A more strict check is applied such that all requests to
/v2/_catalog/...  will be verified.
=> Update the reg-exp to match v2/catalog api -- Cherry pick to 2.1

src/lib/patterns.go, src/lib/patterns_test.go, src/server/middleware/v2auth/access.go, src/server/middleware/v2auth/auth.go
A more strict check is applied such that all requests to
/v2/_catalog/...  will be verified.
=> Update the reg-exp to match v2/catalog api

src/core/service/token/authutils.go, src/core/service/token/creator.go, src/core/service/token/token_test.go, src/pkg/scan/api/scan/base_controller.go, src/pkg/scan/api/scan/base_controller_test.go
This commit directly maps the actoin permission in security context to
the scope generated by the token service in harbor-core.
=> Refine the token scope generation -- cherrypick to 1.10

src/controller/retention/controller.go, src/controller/retention/controller_test.go
fix #13987
fix retention execution status not update when there's zero repo to run
=> fix(retention) execution status for zero repo

src/pkg/authproxy/http.go
The server to handle token-review may have a limitation for the size of
the header.  When the token is huge the token review may fail.
This commit remove the necessary header to harden the flow.
=> Remove raw token from header in token review reuqest - 1.10.x

src/pkg/authproxy/http.go
The server to handle token-review may have a limitation for the size of
the header.  When the token is huge the token review may fail.
This commit remove the necessary header to harden the flow.
=> Remove raw token from header in token review reuqest

src/pkg/authproxy/http.go
The server to handle token-review may have a limitation for the size of
the header.  When the token is huge the token review may fail.
This commit remove the necessary header to harden the flow.
=> Remove raw token from header in token review reuqest - 2.1.x

src/controller/replication/controller.go, src/pkg/task/execution.go
Query executions with both vendor type and ID when sweep the execution records
Fixes #13996
=> Query executions with both vendor type and ID when sweep the execution records

src/controller/scan/callback.go
1. Register task status change function for the scan job triggered by
scan all.
2. Always to delete the robot account for the scan job after the job is
finished because the job does not retry again when it's failed.
Closes #14000
=> fix: always remove the robot after scan job finished

src/controller/replication/controller.go, src/controller/replication/controller_test.go, src/jobservice/common/rds/scripts.go, src/pkg/task/task.go, src/server/handler/job_status_hook.go
Don't ignore the NotFoundErr when handling the status hook of tasks to avoid the status out of sync
Fixes #14016
=> Don't ignore the NotFoundErr when handling the status hook of tasks to avoid the status out of sync

src/controller/event/handler/util/util.go, src/controller/event/handler/util/util_test.go, src/controller/event/handler/webhook/scan/scan.go, src/pkg/notifier/model/event.go
=> fix: ignore tag in the scan webhook when it's empty

make/migrations/postgresql/0050_2.2.0_schema.up.sql
Make sure the revision of execution isn't null during the upgrade
Fixes #14075
=> Make sure the revision of execution isn't null during the upgrade

tests/ci/api_common_install.sh
The original python packaged: in git action host is V2, it should be upgraded to
V3.
=> [Cherry-pick 2.1.0] Upgrade python to v3 in git action CI host

tests/ci/api_common_install.sh
The original python packaged: in git action host is V2, it should be upgraded to
V3.
=> Upgrade python to v3 in git action CI host

src/pkg/authproxy/http.go
The server to handle token-review may have a limitation for the size of
the header.  When the token is huge the token review may fail.
This commit remove the necessary header to harden the flow.
=> Remove raw token from header in token review request -- 2.0.x 

src/server/middleware/security/idtoken.go, src/server/middleware/security/idtoken_test.go
If the request does not have bearer token in the header, do not decode
the empty string.
Fixes #12261
=> Reduce warning logs in OIDC middleware

src/jobservice/runtime/bootstrap.go
Signed-off-by: shaobo <shaobo@caicloud.io>
fix improper spelling of `jobContextInitializer`
=> fix improper spelling

src/controller/gc/controller.go, src/controller/p2p/preheat/enforcer.go, src/controller/replication/controller.go, src/controller/retention/controller.go, src/pkg/task/execution.go, src/pkg/task/execution_test.go
1. Remove the default execution sweeper count for execution vendor.
2. Set the execution sweeper count for gc, preheat, replication,
retention to 50.
3. Keep the executions for the scan job.
=> fix: remove default execution sweeper count

src/lib/orm/error.go, src/lib/orm/orm.go, src/lib/orm/orm_test.go, src/pkg/scan/dao/scan/model.go, src/pkg/scan/dao/scan/vulnerability.go, src/pkg/scan/dao/scan/vulnerability_test.go
Make the creating of the ReportVulnerabilityRecord in transaction to
avoid parallel problem
Closes #14171
=> fix: wrap report vuls record creating in transaction

src/controller/gc/controller.go, src/controller/p2p/preheat/enforcer.go, src/controller/replication/controller.go, src/controller/retention/controller.go, src/pkg/task/execution.go, src/pkg/task/execution_test.go
1. Remove the default execution sweeper count for execution vendor.
2. Set the execution sweeper count for gc, preheat, replication,
retention to 50.
3. Disable sweep for the executions of the scan job.
=> [Cherry pick]fix: remove default execution sweeper count

src/lib/orm/error.go, src/lib/orm/orm.go, src/lib/orm/orm_test.go, src/pkg/scan/dao/scan/model.go, src/pkg/scan/dao/scan/vulnerability.go, src/pkg/scan/dao/scan/vulnerability_test.go
Make the creating of the ReportVulnerabilityRecord in transaction to
avoid parallel problem
Closes #14171
=> [Cherry pick]fix: wrap report vuls record creating in transaction

tests/e2e-image/Dockerfile
See https://github.com/deislabs/oras/security/advisories/GHSA-g5v4-5x39-vwhx
for details
=> Update oras to 0.9.0 to fix "zip slip" vulnerability

src/jobservice/logger/base.go, src/jobservice/logger/known_loggers.go, src/jobservice/logger/known_loggers_test.go
- use separate std logger for job, not shared with jobservice std logger
- merge and remove useless functions
fix #14079
=> fix(jobservice):wrong depth of job logging

src/core/controllers/base.go
This commit updates the controller for sending reset pwd Email,
to make it use the Email from DB query result.
=> [CP - v2.2]: Use the Email address from DB instead of request

src/core/controllers/base.go
This commit updates the controller for sending reset pwd Email,
to make it use the Email from DB query result.
=> Use the Email address from DB instead of request

src/common/utils/oidc/helper.go
Add support for http proxy in OIDC authentication with "Verify Certificate" option disabled.
=> Add support for http proxy in oidc insecureTransport

make/photon/prepare/templates/nginx/nginx.http.conf.jinja, make/photon/prepare/templates/nginx/nginx.https.conf.jinja
Refine the way to set the header so user won't need to comment it if
Harbor is sitting behind a reverse proxy.
=> Refine the way to set X-Forwarded-Proto in nginx

src/core/service/token/creator.go, src/core/service/token/token_test.go
The "*" is used by notary server for permission checking:
https://github.com/theupdateframework/notary/blob/84287fd8df4f172c9a8289641cdfa355fc86989d/server/server.go#L200
Hence, we need to add this into the JWT token such that actions like key
rotation can be executed.
=> Add "*" to the claim set in the token for /v2 apis

src/core/service/token/creator.go, src/core/service/token/token_test.go
The "*" is used by notary server for permission checking:
https://github.com/theupdateframework/notary/blob/84287fd8df4f172c9a8289641cdfa355fc86989d/server/server.go#L200
Hence, we need to add this into the JWT token such that actions like key
rotation can be executed.
=> [Cherry Pick - 2.1] Add "*" to the claim set in the token for /v2 apis

src/pkg/blob/dao/dao.go
=> [cherry-pick]add sorting for list blobs

tests/ci/api_common_install.sh
Git action work node OS had python3.8 deployed already, so won't necessary to install python3.7 in CI.
=> Remove python3.7 deployment in CI installtion phase.

make/photon/registry/builder
Fixes #12850
This patch can fix the GC failure in the NFS v3 env, see https://github.com/distribution/distribution/pull/3309#issuecomment-783606968
=> [cherry-pick]patch upstream fix for io reader

tests/ci/api_common_install.sh
Git action work node OS had python3.8 deployed already, so won't necessary to install python3.7 in CI.
=> [cherry-pick 2.1.0] Remove python3.7 deployment in CI installtion phase.

tests/ci/api_common_install.sh
Git action work node OS had python3.8 deployed already, so won't necessary to install python3.7 in CI.
=> [cherry-pick 2.0.0] Remove python3.7 deployment in CI installtion phase

.github/workflows/CI.yml, tests/ci/api_common_install.sh
Remove python packges, and install python 3.6  to  replace python 3.7.
=> [cherry-pick 2.2.0] Replace python3.7 by 3.6 in CI installtion phase

tests/ci/api_common_install.sh
Docker v20 is the default version for git action, dns should be set manually.
Python v3.8 is the default version for git action, so remove deployment for python v3.6.
=> [Cherry-pick 2.0.0] Remove deploytment of python3.6 and set dns for docker

tests/ci/api_common_install.sh
Docker v20 is the default version for git action, dns should be set manually.
Python v3.8 is the default version for git action, so remove deployment for python v3.6.
=> [Cherry-pick 2.2.0] Remove python3.6 and set dns for docker

src/core/service/token/creator.go, src/core/service/token/token_test.go
The "*" is used by notary server for permission checking:
https://github.com/theupdateframework/notary/blob/84287fd8df4f172c9a8289641cdfa355fc86989d/server/server.go#L200
Hence, we need to add this into the JWT token such that actions like key
rotation can be executed.
=> [ CherryPick 2.2 ] Add "*" to the claim set in the token for /v2 apis

tests/apitests/python/library/artifact.py, tests/apitests/python/library/base.py, tests/apitests/python/library/gc.py, tests/apitests/python/library/preheat.py, tests/apitests/python/library/project.py, tests/apitests/python/library/projectV2.py, tests/apitests/python/library/replication_v2.py, tests/apitests/python/library/retention.py, tests/apitests/python/library/robot.py, tests/apitests/python/library/scan.py, tests/apitests/python/library/scan_all.py, tests/apitests/python/library/system_cve_allowlist.py, tests/apitests/python/library/tag_immutability.py, tests/apitests/python/library/user.py
After debugging for issue of missing some http message logs, we found out that swagger client configuration will be re-initiated by calling models in swagger client, so in API python tests, definition for models must be in front of swagger client definition.
=> Fix API python tests log missing issue

src/pkg/task/dao/task.go
Add order by ID when listing tasks to avoid duplicated records
=> Add order by ID when listing tasks to avoid duplicated records

src/replication/adapter/gitlab/adapter.go
registry enabled.
closes #14328 
closes #13353
Signed-off-by: Vadim Bauer <vb@container-registry.com>
=> Before fetching the GitLab repository check if the project has container registry enabled to avoid 403 error

make/photon/chartserver/Dockerfile.base, make/photon/core/Dockerfile.base, make/photon/db/Dockerfile.base, make/photon/exporter/Dockerfile.base, make/photon/jobservice/Dockerfile.base, make/photon/log/Dockerfile.base, make/photon/nginx/Dockerfile.base, make/photon/notary-server/Dockerfile.base, make/photon/notary-signer/Dockerfile.base, make/photon/portal/Dockerfile.base, make/photon/prepare/Dockerfile.base, make/photon/redis/Dockerfile.base, make/photon/registry/Dockerfile.base, make/photon/registryctl/Dockerfile.base, make/photon/trivy-adapter/Dockerfile.base
=> [WIP]bump up photon to 4.0

make/photon/prepare/templates/core/env.jinja
Add proxy cache for docker registry type
Fixes #14477, #14547
=> Support proxy cache for docker-registry type

make/photon/prepare/migrations/version_2_0_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_1_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_2_0/harbor.yml.jinja
Hello,
Trying to update Harbor from v2.1.2 to 2.2.0, we faced an issue due to how jinja2 template is made.
We are using redis+sentinel and we were unable to make the migration works.
Navigating to the jinja2 template you made, it allowed me to see a field "{{ external_redis.port }}" was used but removed since v1.10.0 (version since when you're supporting redis and redis+sentinel).
Anyway, removing this field allowed me to migrate my harbor.yml file.
I don't know if there are side-effects for such a modification but don't hesitate to tell me if there is something more to change.
Alexis
_(I made a PR few minutes ago but she wasn't following your contribution requirements)_
=> Remove external_redis.port from migration script since not used since v1.10.0

src/core/service/token/creator.go, src/core/service/token/token_test.go
The "*" is used by notary server for permission checking:
https://github.com/theupdateframework/notary/blob/84287fd8df4f172c9a8289641cdfa355fc86989d/server/server.go#L200
Hence, we need to add this into the JWT token such that actions like key
rotation can be executed.
=> [Cherrypick - 1.10] Add "*" to the claim set in the token for /v2 apis

src/common/config/metadata/metadatalist.go, src/common/const.go, src/common/models/config.go, src/core/auth/authproxy/auth.go, src/core/config/config.go, src/core/config/config_test.go, src/pkg/authproxy/http.go, src/pkg/authproxy/http_test.go, src/server/middleware/security/auth_proxy.go, src/server/middleware/security/auth_proxy_test.go
This commit adds the attribute "http_authproxy_admin_usernames", which
is string that contains usernames separated by comma, when a user logs
in and the username in the tokenreview status matches the setting of
this attribute, the user will have administrator permission.
=> Add attribute admin username for authproxy

.github/workflows/codeql-analysis.yml
The autobuild doesn't support golang, remove it.
=> remove the autobuild step

make/photon/Makefile
This ensures latest security fixes are pulled from base image and package managers in case the cache is not clean on builder machines
=> Add --no-cache and --pull flag to image builds

make/photon/prepare/templates/core/env.jinja
Add proxy cache for docker registry type
Fixes #14477, #14547
(cherry picked from commit ccd9ee8c560ce99182559ab9bf99e220e51ab81a)
=> (cherry-pick) Support proxy cache for docker-registry type

src/controller/member/controller.go
Handle the NotFoundError in userManager.GetUserByName()
=> Fix nightly issue: can not add user that never logged in projectmember api

src/controller/user/controller.go, src/server/v2.0/handler/user.go
This commit skips getting OIDC meta info for admin user.
It fixes the issue that admin user cannot login to portal, which was
introduced in refactor.
=> Do not get OIDC info for admin user

Makefile, api/v2.0/swagger.yaml, src/server/v2.0/handler/handler.go, src/server/v2.0/handler/model/user.go, src/server/v2.0/handler/user.go, src/server/v2.0/handler/user_test.go, tests/apitests/python/library/base.py, tests/apitests/python/library/user.py
Use singular as the tag for user APIs to align with other APIs.
=> refactor: use singular as the tag for user APIs

.github/PR_TEMPLATE.md
Signed-off-by: Abigail McCarthy <mabigail@vmware.com>
Opening this PR as a Draft to start a discussion on adding a PR template to the repo. I'm not sure if this has come up before, but I think these templates can be very helpful to make sure folks fill in some basic info about what the PR is for and remind folks to do the required steps to get the PR merged that can get missed, like the DCO.
I'd also like to make sure we call out updating docs now that the docs are kept in a separate repo.
Is there anything else we should call out here? Like for creating release notes or how to run/pass tests?
=> add PR template to repo

make/photon/db/docker-healthcheck.sh
hostname -i will malfunction in some cases like the `nsswitch.conf` file does'nt exist
=> Fix: Use local host on db's healthcheck

src/core/api/projectmember.go, src/core/api/projectmember_test.go, src/core/auth/authenticator.go
If authenticator does not support searching user/group, wraps it as a
not found error, such that the API will return 404 rather than confusing
500.
=> Refine the "not support" error when searching user

.github/workflows/build-package.yml, Makefile, tests/ci/ut_install.sh, tests/robot-cases/Group1-Nightly/Setup_Nightly.robot
1. Add buid base step to UT test in CI, base image used by UI test
should be built before buiding harbor image;
2. In build package workflow, trigger build base image step in condition of changing both in
Dockerfile.base and VERSION
3. Add tag for setup nightly test
=> [ 2.1.0 ] Add build base step to UT test in CI

.github/workflows/build-package.yml, Makefile, tests/ci/ut_install.sh
1. Add build base image step in build package git action workflow;
2. Add build base step to UT test in CI, base image used by UI test should be built before building harbor image in the same runtime;
3. In build package workflow, trigger build base image step in condition of changing both in
Dockerfile.base and VERSION;
4. Add tag for setup nightly test.
=> Fix build base related issues

.github/workflows/build-package.yml, .gitignore, Makefile, make/pushimage.sh, tests/ci/ut_install.sh, tests/robot-cases/Group1-Nightly/Setup_Nightly.robot
Build base image step should be in build package workflow, and local base images build by new step should be removed since images have been pushed to docker hub.
1. Add build base image step in build package git action workflow;
2. Add build base step to UT test in CI, base image used by UI test should be built before building harbor image in the same runtime;
3. In build package workflow, trigger build base image step in condition of changing both in
Dockerfile.base and VERSION;
4. Add tag for setup nightly test.
=> [ Cherry-pick 2.2.0 ] Add build base image step in build package git action workflow

src/pkg/task/hook.go
Read upstream job ID as ID when it isn't null to fix the job not found error
=> Read upstream job ID as ID when it isn't null

src/server/middleware/v2auth/auth.go, src/server/middleware/v2auth/auth_test.go
This commits make sure when the request does not carry authorization
headers, the HEAD and GET will get the same response code.  This change
should be made due to #14711
=> Return 401 for GET request to /v2 API for public artifacts.

src/core/auth/ldap/ldap.go, src/lib/config/config.go, src/pkg/config/manager.go, src/pkg/config/validate/ldapgroup.go, src/pkg/config/validate/test/ldapgroup_test.go, src/pkg/config/validate/validate.go
Add AssignByTag function to lib/config
When ldap_group_search_filter is set, check other required fields
When ldap_group_search_filter is empty, skip to attach group
=> Add the ldap group config validation

src/common/dao/dao_test.go, src/common/dao/oidc_user.go, src/common/dao/oidc_user_test.go, src/common/dao/user.go, src/common/models/user.go, src/common/utils/test/database.go, src/controller/user/controller.go, src/core/api/internal.go, src/core/auth/authenticator.go, src/core/auth/db/db.go, src/core/auth/ldap/ldap.go, src/core/auth/uaa/uaa.go, src/core/controllers/base.go, src/core/controllers/controllers_test.go, src/core/controllers/oidc.go, src/core/main.go, src/pkg/oidc/metamanager.go, src/pkg/user/dao/dao_test.go, src/pkg/user/manager.go, src/server/middleware/security/idtoken.go, src/testing/controller/user/controller.go, src/testing/pkg/user/manager.go
This commit moves more user related funcs, such as ChangePassword,
Login, ChangeUserProfile from common/dao to rely on /pkg/user and
pkg/oidc.
It also removes the code for resetting user's password as it's disabled.
=> Move user related funcs from common/dao

src/common/config/metadata/metadatalist.go, src/common/const.go, src/common/models/config.go, src/core/auth/authproxy/auth.go, src/core/config/config.go, src/core/config/config_test.go, src/pkg/authproxy/http.go, src/pkg/authproxy/http_test.go, src/server/middleware/security/auth_proxy.go, src/server/middleware/security/auth_proxy_test.go
This commit adds the attribute "http_authproxy_admin_usernames", which
is string that contains usernames separated by comma, when a user logs
in and the username in the tokenreview status matches the setting of
this attribute, the user will have administrator permission.
=> [Cherrypick to v2.2]: Add attribute admin username for authproxy

make/migrations/postgresql/0052_2.2.2_schema.up.sql, src/controller/scan/callback.go, src/controller/scan/callback_test.go, src/pkg/retention/callback.go, src/pkg/scheduler/callback.go, src/pkg/scheduler/dao.go, src/pkg/scheduler/mock_dao_test.go, src/pkg/task/hook.go, src/pkg/task/hook_test.go, src/pkg/task/registry.go
When the core service cannot response the checkin request in time, duplicated execution records may be created, this commit introduces the revision column to make sure there is only one record for one schedule trigger
=> Fix duplicate execution record issue

make/migrations/postgresql/0052_2.2.2_schema.up.sql, src/controller/scan/callback.go, src/controller/scan/callback_test.go, src/pkg/retention/callback.go, src/pkg/scheduler/callback.go, src/pkg/scheduler/dao.go, src/pkg/scheduler/mock_dao_test.go, src/pkg/task/hook.go, src/pkg/task/hook_test.go, src/pkg/task/registry.go
When the core service cannot response the checkin request in time, duplicated execution records may be created, this commit introduces the revision column to make sure there is only one record for one schedule trigger
=> [cherry-pick]Fix duplicate execution record issue

src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go
DB transaction failure may break the loop query of the artifacts, the
result is that not all artifacts are scanned in one scan all job. Using
a new DB connection to call the Scan method of the controller to avoid
this problem.
=> fix: using new ctx to scan artifact when scanAll

contrib/grafana-dashborad/metrics-example.json
=> Add grafana example for metrics

src/controller/scanner/base_controller.go, src/lib/cache/cache.go, src/lib/cache/memory/memory.go, src/lib/cache/redis/redis.go, src/pkg/scan/rest/v1/client.go, src/pkg/scan/rest/v1/models.go
1. Cache the metadata of scanner 30s.
2. Change the scanner client request timeout to 5s.
=> perf: cache the metadata of the scanner

src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go
DB transaction failure may break the loop query of the artifacts, the
result is that not all artifacts are scanned in one scan all job. Using
a new DB connection to call the Scan method of the controller to avoid
this problem.
=> [Cherry pick]fix: using new ctx to scan artifact when scanAll

src/controller/scanner/base_controller.go, src/lib/cache/cache.go, src/lib/cache/memory/memory.go, src/lib/cache/redis/redis.go, src/pkg/scan/rest/v1/client.go, src/pkg/scan/rest/v1/models.go
1. Cache the metadata of scanner 30s.
2. Change the scanner client request timeout to 5s.
=> [Cherry pick]perf: cache the metadata of the scanner

src/pkg/permission/evaluator/rbac/casbin.go
This change displays missing RBAC permissions in the log when the debug mode is enabled. 
The functionality well help the normal user to craft permissions for robot accounts. This is especially useful if you want to perform API operations with robot accounts.
Signed-off-by: Vadim Bauer <vb@container-registry.com>
=> Provide detailed output about missing RBAC permissions in debug mode.

.github/workflows/CI.yml, src/controller/user/controller.go
This commit fix a potential nil pointer issue when trying to read User
ID from security context
=> Check user in security context before getting the ID

api/v2.0/swagger.yaml, src/lib/truncate.go, src/lib/truncate_test.go, src/pkg/project/dao/dao.go, src/pkg/user/manager.go
Truncate the string when deletinng the resources when the length exceeds the limit
=> Truncate the string when deletinng the resources when the length exceeds the limit

src/common/rbac/const.go, src/common/rbac/system/policies.go, src/server/v2.0/handler/oidc.go, src/server/v2.0/handler/sys_cve_allowlist.go
This commit uses system configuration resource for permission check
against API to ping OIDC and update systen CVE allowlist.
Fixes #14386
=> Use system configuration resource for permission checking

Makefile, make/photon/db/Dockerfile, make/photon/db/Dockerfile.base, make/photon/db/docker-entrypoint.sh, make/photon/db/initdb.sh, make/photon/db/postgres.spec, make/photon/db/rpm_builder.sh, make/photon/db/upgrade.sh
1, use the pg source and photon spec to build postgres 9.6
2, install 9.6 on the photon 4.0
3, then leverage pg_upgrade to handle the pg major version migration
=> support pg upgrade

src/pkg/robot/dao/dao.go
QuerySeter.Delete will call two queies in the orm of beego. First it
will query all primary keys of the model by the QuerySeter, and then the
orm will delete the models using the IN statement of these primary keys.
This will be failed in the postgres when the records more than 65535.
This commit changes to use the raw query to delete the robots of the
project.
Closes #14678
=> fix: delete robots by project id using raw sql

src/server/middleware/repoproxy/proxy.go
Fixes #14822
When the upstream registry not working, but status might stay healthy because the health check interval is 5 minutes, if a pull request comes before registry status turns to unhealthy, the proxy cache middleware might proxy the request to the upstream registry and get a 401 error and this 401 error might translate to a http 500 error to the client eventually.
To solve this issue, it fall back all error to local registry when proxying manifest except the NotFoundError from the local regist
=> Fall back to local registry when upstream registry is not working

src/core/middlewares/middlewares.go, src/server/middleware/mergeslash/mergeslash.go, src/server/middleware/mergeslash/mergeslash_test.go
There are code in the core component to conditionally execute code based
on the pattern of url path, and different ingress controller or reverse
proxy may handle the dup slashes in the url path differently.
This commit merge dup slashes in the url paths to make things more
consistent.
=> Add merge slash middleware

src/server/middleware/v2auth/auth.go, src/server/middleware/v2auth/auth_test.go
This commit enhances the v2auth middleware, such that any un-recognized
request sent to /v2/ will be blocked.
=> Make v2auth more strict

src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/controller/scan/callback.go, src/controller/scan/callback_test.go, src/controller/scan/controller.go, src/lib/set.go, src/lib/set_test.go, src/pkg/scan/dao/scan/model.go, src/pkg/scan/dao/scan/vulnerability.go, src/pkg/scan/dao/scan/vulnerability_test.go, src/pkg/scan/job.go, src/pkg/scan/job_test.go, src/pkg/scan/postprocessors/report_converters.go, src/pkg/scan/report/manager.go, src/pkg/scan/vuln/report.go, src/testing/controller/scan/controller.go
1. Refactor the process of updating the scan report. First tries to update the vulnerability records whose severity are changed, then creates the vulnerabilities which are not in the db, finally associates vulnerability records with the report.
2. Move the updating of the scan report in the scan job.
Closes #14851 #14745 #14585 #14461 #14430 
=> refactor: convert scan report in scan job

src/server/middleware/v2auth/auth.go
This commit enhances the v2auth middleware, such that any
un-recognized request sent to /v2/ will be blocked.
=> [Cherrypick v2.1] Make v2auth more strict

src/server/middleware/v2auth/auth.go, src/server/middleware/v2auth/auth_test.go
This commit enhances the v2auth middleware, such that any un-recognized
request sent to /v2/ will be blocked.
=> [Cherrypick - v2.2]: Make v2auth more strict

src/core/middlewares/middlewares.go, src/server/middleware/mergeslash/mergeslash.go, src/server/middleware/mergeslash/mergeslash_test.go
There are code in the core component to conditionally execute code based
on the pattern of url path, and different ingress controller or reverse
proxy may handle the dup slashes in the url path differently.
This commit merge dup slashes in the url paths to make things more
consistent.
=> [Cherrypick - v2.1] Add merge slash middleware

src/core/middlewares/middlewares.go, src/server/middleware/mergeslash/mergeslash.go, src/server/middleware/mergeslash/mergeslash_test.go
There are code in the core component to conditionally execute code based
on the pattern of url path, and different ingress controller or reverse
proxy may handle the dup slashes in the url path differently.
This commit merge dup slashes in the url paths to make things more
consistent.
=> [Cherrypick - 2.2]: Add merge slash middleware

src/server/middleware/security/robot.go
The robotv1 context uses the robot$ as a hardcoded prefix to identify robot account, it will raise error
for a valid robotv2 account with this prefix.
Update the log level to avoid the redundant logs for the default installation.
=> update the log level of robot v1 context

make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
Fixed #15034, as for postgres 13, the default shm size is 64MB, set to 1gb to avoid could not resize shared memory segment error.
=> set shm size of postgres

src/server/registry/route.go
As from docker v20, the containerd leverages the cache when to pull a manifest, that leads to the
client doesn't send the get manifest request if the image exists in local.
The content trust and vul checker are only valid for get manifest request, the PR is to enable the checkers on
head manifest request to handle the containerd local cache scenario.
=> enable policy checker for head manifest request

src/server/middleware/repoproxy/proxy.go
Fixes #14822
When upstream registry not working, but status might stay healthy because the health check interval is 5 minutes, if a pull request comes before registry status turns to unhealthy, the proxy cache middleware might proxy the request to the upstream registry and get a 401 error and this 401 error might translate to a http 500 error to the client eventually.
To solve this issue, it fall back all error to local registry when proxying manifest except the NotFoundError from the local registry.
=> (cherry-pick) Fall back to local registry when upstream registry is not working

src/jobservice/job/impl/gc/garbage_collection.go, src/jobservice/job/impl/gc/garbage_collection_test.go, src/pkg/blob/manager.go, src/pkg/blob/manager_test.go, src/testing/pkg/blob/manager.go
Fixes #13976 for the quota exceed case, gc will print the untagged blobs for dry-run
=> fixes 13976

.github/workflows/build-package.yml, Makefile, make/photon/Makefile, make/pushimage.sh, tests/ci/api_common_install.sh, tests/ci/ut_install.sh
Remove build base executable in Makefile by replacing it as an input parameter.
Add add more input parameters for controlling docker pull/push to make
build base process flexible for users.
Fixed issue: #14979.
=> Refind build base process in Makefile

src/controller/replication/flow/stage.go, src/controller/replication/flow/stage_test.go
Flattening repository path components excepting the last one in replication
Fixes #15072
=> Flattening repository path components excepting the last one

api/v2.0/swagger.yaml
Set "x-omitempty" as "false" for the pull count and artifact count of repository to avoid the missing of these properties in API response
=> Set "x-omitempty" as "false" for the pull count and artifact count of repository

.github/workflows/build-package.yml, Makefile, make/photon/Makefile, make/pushimage.sh, tests/ci/api_common_install.sh, tests/ci/ut_install.sh
Remove build base executable in Makefile by replacing it as an input parameter.
Add add more input parameters for controlling docker pull/push to make
build base process flexible for users.
=> [ Cherry-pick 2.2.0 ] Refind build base process in Makefile

src/controller/artifact/controller.go, src/controller/repository/controller.go
The transaction will be aborted when get errors during the execution which causes the following sqls report error.
This commit moves the re-getting artifact logic out of the second transaction to avoid the concurrent pushing issue
=> Fix the concurrent pushing the same image issue

src/controller/replication/model/model.go, src/lib/patterns.go, src/lib/patterns_test.go
Add validation for destination namespace when creating/updating replication policy
=> [cherry-pick]Add validation for destination namespace when creating/updating replication policy

src/controller/replication/model/model.go, src/lib/patterns.go, src/lib/patterns_test.go
Add validation for destination namespace when creating/updating replication policy
=> Add validation for destination namespace when creating/updating replication policy

src/controller/artifact/controller.go, src/controller/repository/controller.go
The transaction will be aborted when get errors during the execution which causes the following sqls report error.
This commit moves the re-getting artifact logic out of the second transaction to avoid the concurrent pushing issue
=> [cherry-pick]Fix the concurrent pushing the same image issue

make/harbor.yml.tmpl, make/photon/prepare/migrations/version_2_3_0/__init__.py, make/photon/prepare/migrations/version_2_3_0/harbor.yml.jinja, make/photon/prepare/templates/nginx/nginx.http.conf.jinja, make/photon/prepare/templates/nginx/nginx.https.conf.jinja, make/photon/prepare/templates/registry/config.yml.jinja
Increasing the `worker_connections` of Nginx to resolve the `Connection refused` problem.
Increasing the `max_idle_conns` in the core to resolve the `connect: cannot assign requested address` in the core component.
Add the `pool` configuration to the registry to resolve the `connect: cannot assign requested address` in the registry component.
Closes #15041
=> perf: configurations for perf improvement

src/portal/src/app/shared/units/utils.spec.ts, src/portal/src/app/shared/units/utils.ts
Should fix #15200.
Based on the same pattern that GB/KB.
In the same time, I fixed the data unit used as it's not (kilo/giga/tera)byte but kibibit, gibibit (according to unit tests expecting value).
Signed-off-by: Alexis <60alexis@gmail.com>
=> Add TiB support for display, fix unit to correct one

api/v2.0/swagger.yaml, src/server/v2.0/handler/usergroup.go
Fixes #15171
Cannot use q.Query because ldap_group_dn contains comma(,) and equal(=), which are reserved characters in q.Query
=> Add ldap_group_dn parameter to search group with ldap group dn

src/lib/config/metadata/type.go
Add parseInt function to parse the scientific notation
=> Fix invalid syntax errors when int value is convert to scientific notation

RELEASES.md
This updates support matrix to make it up to date.
It also update the upgrade path section to use 2.x as examples.
=> Update RELEASES doc

make/migrations/postgresql/0070_2.4.0_schema.up.sql, src/controller/user/controller.go, src/pkg/member/dao/dao.go, src/pkg/member/dao/dao_test.go, src/pkg/member/manager.go, src/pkg/oidc/dao/meta.go, src/pkg/oidc/dao/meta_test.go, src/pkg/oidc/metamanager.go, src/server/v2.0/handler/user.go, src/testing/pkg/oidc/dao/meta_dao.go, src/testing/pkg/oidc/meta_manager.go
The following information should cleanup before delete user:
Delete project member of this user.
Delete oidc_user when auth_mode is oidc_auth.
Fixes #8424
=> Delete users under auth_mode other than db_auth

src/pkg/oidc/dao/meta.go, src/pkg/oidc/dao/meta_test.go
Ensures that `subiss` field is fetched from the database. Otherwise this field is empty and will cause several issues when working with the user object. Eg. when writing it back to the database it resets the `subiss` in the database.
Fixes #15241
=> Fix refreshing oidc access token breaks users subiss in database

src/core/main.go, src/pkg/oidc/fix.go, src/pkg/oidc/fix_test.go, src/pkg/oidc/secret.go
This commit include 2 changes to mitigate and remediate the problem
described in #15241
1. When the token is to be updated in the "oidc_user" table, make sure
only the column "token" will be udpated.
2. Restore the subiss column for the record that has this column cleared
by mistake, by decoding the persisted token.
=> Remediate the empty subiss problem

src/core/main.go, src/pkg/oidc/dao/meta.go, src/pkg/oidc/fix.go, src/pkg/oidc/fix_test.go, src/pkg/oidc/secret.go, src/testing/pkg/oidc/dao/meta_dao.go
This commit include 2 changes to mitigate and remediate the problem
described in #15241
1. When the token is to be updated in the "oidc_user" table, make sure
only the column "token" will be udpated.
2. Restore the subiss column for the record that has this column cleared
by mistake, by decoding the persisted token.
=> [CP-v2.3]:Remediate the empty subiss problem

tests/apitests/python/library/system.py
As the admin job has already droped from v2.3, remove the request handling from router.
=> drop adminjob router

src/common/dao/pgsql.go
This should resolve https://github.com/goharbor/harbor/issues/14856 or make it very unlikely to appear.  We also did the same in the past with https://github.com/goharbor/harbor/pull/4719
related to #15048
=> Fixes the broken pipe connection error with postgres.

RELEASES.md
This updates support matrix to make it up to date.
It also update the upgrade path section to use 2.x as examples.
=> [cherrypick v2.3] Update RELEASES doc

src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
This is a minor consistency issue, but it also turns into a minor rendering issue where something is converting "backtick + a" into "à"
=> Adjust "flattening" tooltip quotes to be consistent

src/common/security/robot/context.go, src/common/security/robot/context_test.go, src/pkg/project/models/project.go, src/server/middleware/security/robot.go, src/server/v2.0/handler/project.go, src/server/v2.0/handler/repository.go
1, add permission check for API of List Project
2, use the self defined query to handle both names and public query
=> support robot to list project

src/pkg/oidc/helper.go, src/pkg/oidc/helper_test.go
Ensures that username is used from token if not present in remote. Otherwise username is always fetched from userinfo endpoint even though the configured username claim does not exist in userinfo endpoint (more details in #15290).
Fixes #15290
=> if username is not available in remote, fall back to username from token

src/controller/gc/callback.go, src/controller/member/controller.go, src/controller/usergroup/controller.go, src/core/auth/auth_test.go, src/core/auth/authenticator.go, src/core/auth/authproxy/auth.go, src/core/auth/authproxy/auth_test.go, src/core/auth/db/db.go, src/core/auth/db/db_test.go, src/core/auth/ldap/ldap.go, src/core/auth/ldap/ldap_test.go, src/core/auth/oidc/oidc.go, src/core/auth/oidc/oidc_test.go, src/core/auth/uaa/uaa.go, src/core/auth/uaa/uaa_test.go, src/core/controllers/authproxy_redirect.go, src/core/controllers/base.go, src/core/controllers/oidc.go, src/pkg/ldap/manager.go, src/server/middleware/readonly/readonly.go, src/server/middleware/repoproxy/proxy.go, src/server/middleware/security/auth_proxy.go, src/server/middleware/security/auth_proxy_test.go, src/server/middleware/security/basic_auth.go, src/server/middleware/security/basic_auth_test.go, src/server/middleware/security/security.go, src/server/middleware/security/security_test.go
1. Use ctx from http request for the readonly middleware.
2. Refactor the AuthenticateHelper to let it get orm from ctx of the http request.
3. Change to use ctx from http request for oidc and authproxy http handlers.
Closes #15474 
=> fix: use ctx from http request for middlewares

src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts, src/portal/src/app/base/project/p2p-provider/policy/policy.component.ts
=> Fix ui issue for add p2p policy component

make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
For details, please refer to #14146 (comment)
and docker/for-linux#1164.
If who encounter the issue mentioned by #6031, add the dns_search: . to the releated container.
=> deprecate dns search

src/controller/gc/callback.go, src/controller/member/controller.go, src/controller/usergroup/controller.go, src/core/auth/auth_test.go, src/core/auth/authenticator.go, src/core/auth/authproxy/auth.go, src/core/auth/authproxy/auth_test.go, src/core/auth/db/db.go, src/core/auth/db/db_test.go, src/core/auth/ldap/ldap.go, src/core/auth/ldap/ldap_test.go, src/core/auth/oidc/oidc.go, src/core/auth/oidc/oidc_test.go, src/core/auth/uaa/uaa.go, src/core/auth/uaa/uaa_test.go, src/core/controllers/authproxy_redirect.go, src/core/controllers/base.go, src/core/controllers/oidc.go, src/pkg/ldap/manager.go, src/server/middleware/readonly/readonly.go, src/server/middleware/repoproxy/proxy.go, src/server/middleware/security/auth_proxy.go, src/server/middleware/security/auth_proxy_test.go, src/server/middleware/security/basic_auth.go, src/server/middleware/security/basic_auth_test.go, src/server/middleware/security/security.go, src/server/middleware/security/security_test.go
1. Use ctx from http request for the readonly middleware.
2. Refactor the AuthenticateHelper to let it get orm from ctx of the http request.
3. Change to use ctx from http request for oidc and authproxy http handlers.
=> [Cherry pick]fix: use ctx from http request for middlewares (#15523)

make/photon/log/logrotate
Logrotate is run with sudo as the syslog user by cron.hourly
The current working directory is `/root` which is inaccessible to the syslog
user so the logrotate command fails. Currently the following stderr is being
thrown away by the cron script:
```
error: cannot open current directory: Permission denied
```
Fixes #15468
Signed-off-by: Christopher Jenkins <christj@gmail.com>
=> Logrotate fails when cwd is not accessible

src/pkg/reg/adapter/gitlab/adapter.go, src/pkg/reg/adapter/gitlab/adapter_test.go
close #15385
in gitlab replication adapter, if set name and tag filters together, the tag filter is not work
=> fix(replication) gitlab filters may not work

make/photon/chartserver/docker-entrypoint.sh, make/photon/core/entrypoint.sh, make/photon/exporter/entrypoint.sh, make/photon/jobservice/entrypoint.sh, make/photon/registry/entrypoint.sh, make/photon/trivy-adapter/entrypoint.sh
Use the exec Bash command so that the final running application becomes
the container’s PID 1. This allows the application to receive any Unix
signals sent to the container, in accordance with
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint
Currently, SIGTERM signals sent by kubernetes are not passed to the
executed binary.
Closes #14382
Signed-off-by: Xavier Duthil <xavier.duthil@ovhcloud.com>
=> Use exec in all components' entrypoints

src/controller/user/controller.go
This commit make sure when security context is not found the `Get`
function in user controller should not return error.
Because this func will be called by security middleware, at which point
of time the security context is not generated.
Additionally, checking security context is not necessary because the
permission checking is already done in the API handler layer.
fixes #15535
=> Do not check security context in Get of user controller

src/controller/user/controller.go
This commit make sure when security context is not found the `Get`
function in user controller should not return error.
Because this func will be called by security middleware, at which point
of time the security context is not generated.
Additionally, checking security context is not necessary because the
permission checking is already done in the API handler layer.
fixes #15535
=> [Cherrypick - v2.3]Do not check security context in Get of user controller

.buildbaselog, .github/workflows/build-package.yml
If build base images is needed in a unexpected situation, build base images action will be triggered by making a modification of .buildbaselog.
=> Add trigger file for building base

tests/resources/Harbor-Pages/Project.robot
Because this option is deleted in the ui page, the test case is modified synchronously
=> Fix User View Logs test case error

src/core/api/harborapi_test.go, src/core/api/internal.go, src/core/api/internal_test.go, src/server/route.go
The init design of this API is to avoid the quota error leads to system disaster.
As quota has been refineded and redis lock has been removed, the API can be deprecated safely.
And this API is only call the DB to refresh quota data, user can call the SyncQuota API to handle this.
=> remove the internal legacy API to switch quota

src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.html, src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.ts, src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html, src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.ts, src/portal/src/app/base/project/repository/repository-gridview.component.html, src/portal/src/app/base/project/repository/repository-gridview.component.ts, src/portal/src/index.html
Fixes #15893
1. Enable  right-click to open in a new tab for "project links" and "repository links" (other links have extra logic, so can not enable it)
=> Support right click to open a link in a new tab

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html, src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts, src/portal/src/app/shared/components/label/label-piece/label-piece.component.html, src/portal/src/app/shared/components/label/label-piece/label-piece.component.ts
Related issue #15973
Replace spaces with "", so users can not input any space in filters
=> Not allow space in replication rule filters

tests/resources/TestCaseBody.robot, tests/robot-cases/Group1-Nightly/Common_GC.robot
Specify the test redis mirror tag. If not specified, the default tag is latest. If the latest tag changes, it will cause false positives in the test case.
=> Specify test redis image tag

src/core/main.go, src/pkg/config/db/manager.go
previous config is not cached because it is initialized when cache is not ready
=> Enable db config cache explicitly

src/core/main.go, src/pkg/config/db/manager.go
previous config is not cached because it is initialized when cache is not ready
=> (cherry-pick) Enable db config cache explicitly

src/portal/src/app/base/left-side-nav/projects/projects.component.ts, src/portal/src/app/base/project/helm-chart/helm-chart-detail/list-chart-versions/helm-chart-versions-detail/helm-chart-version.component.ts
Filter out charts that have no version property
Fixes #16004
=> Fix null pointer exception for chart version

src/common/const.go, src/controller/event/handler/auditlog/auditlog.go, src/controller/event/handler/internal/artifact.go, src/lib/config/metadata/metadatalist.go, src/lib/config/userconfig.go
These variables are temporary solution for issue: goharbor#16039
When user disable the pull count/time/audit log, it will decrease the database access, especially in large concurrency pull scenarios.
1, PULL_TIME_UPDATE_DISABLE : The flag to indicate if pull time is disable for pull request.
2, PULL_COUNT_UPDATE_DISABLE : The flag to indicate if pull count is disable for pull request.
3, pull audit log will not create on disabling pull time.
=> add pull update control env

src/server/middleware/cosign/cosign.go, src/server/middleware/cosign/cosign_test.go, src/server/registry/route.go
The middleware is to land the cosign signature linkage with the subject artifact ID.
=> add cosign middleware

make/photon/prepare/utils/cert.py, tests/ci/api_common_install.sh
The openssl 3.0.0 using newer `PKCS#8` format.
But it's not compatitable with harbor core
So using tradictional format instead
=> Fix: using traditional `PKCS#1` format RSA key

src/jobservice/logger/service.go
=> (CHERRY-PICK) fix: resolve the codeql alerts

src/jobservice/logger/service.go
Use `src/lib/log` to replace golang standard package `log` in jobservice log service to resolve the codeql alerts.
=> fix: resolve the codeql alerts

make/photon/prepare/utils/cert.py
The openssl 3.0.0 using newer `PKCS#8` format.
But it's not compatitable with harbor core
So using tradictional format instead
=> [cherry-pick]Fix: using traditional `PKCS#1` format RSA key

src/jobservice/job/impl/gc/garbage_collection.go
=> feat: add failure-tolerance for gc

api/v2.0/swagger.yaml, src/pkg/project/models/pro_meta.go, src/pkg/project/models/project.go, src/server/middleware/contenttrust/cosign.go, src/server/middleware/contenttrust/cosign_test.go, src/server/middleware/contenttrust/notary.go, src/server/middleware/contenttrust/notary_test.go, src/server/middleware/util/util.go, src/server/middleware/vulnerable/vulnerable.go, src/server/registry/route.go, src/server/v2.0/handler/project_metadata.go
Enable policy checker for cosign, when it's enabled, user cannot pull artifact without cosign.
=> Cosign policy checker

make/migrations/postgresql/0080_2.5.0_schema.up.sql
From harbor 2.4, the trivy does not support scan report v1.0, we need to remove the old version scan reports from the DB.
Closes #16221
=> fix: Clean old version scan reports of trivy

src/pkg/task/execution.go, src/pkg/task/execution_test.go
Fixes: https://github.com/goharbor/harbor/issues/15945
=> fix: add worker pool for execution sweep to limit workers

make/migrations/postgresql/0071_2.4.2_schema.up.sql, make/migrations/postgresql/0080_2.5.0_schema.up.sql
=> Move removing old version scan reports of trivy to 2.4.2

src/pkg/oidc/helper.go, src/pkg/oidc/helper_test.go
This PR resolves #16180, which seems to come down to the username not being set properly whenever `userInfoFromRemote` fails in `UserInfoFromToken`:
https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L269
When above fails, [mergeUserInfo](https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L287) is never called, which leads to `local.Username` to remain empty (as this is handled by `mergeUserInfo`).
https://github.com/goharbor/harbor/blob/5cd5bcaee44e9f57c96ac8327009bcffb95ac7a5/src/pkg/oidc/helper.go#L273-L277
What I'd like to suggest is setting the Username if it's still empty, after setting the autoOnboardUsername, as it was prior to #15625 : …
=> Store Username in auto-onboard flow (resolves #16180)

src/controller/artifact/model.go, src/controller/artifact/model_test.go, src/pkg/accessory/model/accessory.go, src/pkg/accessory/model/accessory_test.go, src/pkg/reg/adapter/harbor/v2/client.go
For the case Harbor-to-Harbor, the accessory can be replicated from source or to target.
=> add cosign support in replication

src/controller/replication/flow/copy.go, src/controller/replication/flow/copy_test.go, src/controller/replication/flow/stage.go, src/pkg/reg/adapter/harbor/base/adapter.go, src/pkg/reg/adapter/harbor/base/adapter_test.go, src/pkg/reg/model/resource.go
Fixes: https://github.com/goharbor/harbor/issues/15155
=> fix: skip replication to proxy cache project

src/lib/config/config.go, src/lib/config/trace.go, src/pkg/config/manager.go
DB Config Manager could be registered twice if need to enable cache
Get trace config only when the trace is enabled
=> Remove noise in log

src/pkg/immutable/match/rule/match.go, src/pkg/immutable/match/rule/match_test.go
Fixes: https://github.com/goharbor/harbor/issues/16335
=> fix: ignore untagged artifact when perform immutable policy

src/server/middleware/security/basic_auth.go, src/server/middleware/security/basic_auth_test.go
=> (cherry-pick) Add IP and agent in trace for failed login

make/migrations/postgresql/0080_2.5.0_schema.up.sql
Missing index with job_id, when query task with job_id, it cause a full table scan, caused performance issue
Fixes #15271
=> Create index on task with job_id

src/jobservice/main.go, src/lib/config/config.go, src/lib/config/systemconfig.go, src/lib/config/userconfig.go
Make func defaultMgr() public
Set DefaultCfgManager to RestCfgManager and Load it in the jobservice main
config.WithNotary call DefaultMgr(), it wil get the RestCfgManager
Fixes #16418
=> The DB config manager is not init on jobservice call config.WithNotary

src/go.mod, src/go.sum, src/vendor/github.com/containerd/containerd/version/version.go, src/vendor/modules.txt
Bump up github.com/containerd/containerd to v1.5.10
=> bump up github.com/containerd/containerd to v1.5.10

src/controller/artifact/controller.go
Add transaction for artifact deletion, given API has the transaction when to call artifact controller but other object may not, for example jobservice job.
Here, force add the tx to ensure all the things can be rolled back.
=> add transaction for artifact delete

src/controller/artifact/controller.go
Add transaction for artifact deletion, given API has the transaction when to call artifact controller but other object may not, for example jobservice job.
Here, force add the tx to ensure all the things can be rolled back.
=> [cherry-pick]add transaction for artifact delete

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts, src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts, src/portal/src/app/base/project/repository/artifact/artifact.ts, src/portal/src/app/shared/components/push-image/push-image.component.ts, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
=> Update push and pull command for helm

src/lib/q/builder_test.go
This fixes a dropped test `err` variable in `lib/q`.
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
=> lib/q: fix dropped test error

tests/resources/Harbor-Pages/Project-Webhooks.robot, tests/robot-cases/Group1-Nightly/Common.robot
Synchronous modification due to UI changes
=> Update webhook testcase xpath from disable to deactivate

tests/ci/api_run.sh, tests/test-engine-image/Dockerfile.api_test
Because swagger_client adds dependency on python-dateutil module
=> Add python-dateutil module in api e2e image

tests/ci/api_run.sh, tests/test-engine-image/Dockerfile.api_test
Because swagger_client adds dependency on python-dateutil module
=> [cherry-pick]Add python-dateutil module in api e2e image

make/migrations/postgresql/0090_2.6.0_schema.up.sql
=> migrations: correct project metadata public value

api/v2.0/swagger.yaml, src/server/v2.0/handler/usergroup.go
Add group_name parameter to GET usergroups API
Related to issue #16408
UI should also switch from search api to usergroups list api
=> Update usergroups API to support search by group_name

src/server/middleware/contenttrust/cosign.go, src/server/middleware/contenttrust/cosign_test.go, src/server/middleware/contenttrust/notary.go, src/server/middleware/contenttrust/notary_test.go, src/server/middleware/util/util.go, src/server/middleware/vulnerable/vulnerable.go, src/server/middleware/vulnerable/vulnerable_test.go
When user enables the cosign policy and triggers the replication, the harbor adapter will try to  pull the cosign siguature if it has to do the further push.
In this case, it has to skip policy check.
=> skip policy check on pull cosign signature

src/server/middleware/contenttrust/cosign.go, src/server/middleware/contenttrust/cosign_test.go, src/server/middleware/contenttrust/notary.go, src/server/middleware/contenttrust/notary_test.go, src/server/middleware/util/util.go, src/server/middleware/vulnerable/vulnerable.go, src/server/middleware/vulnerable/vulnerable_test.go
When user enables the cosign policy and triggers the replication, the harbor adapter will try to  pull the cosign siguature if it has to do the further push.
In this case, it has to skip policy check.
=> [cherry-pick]skip policy check on pull cosign signature

src/portal/angular.json, src/portal/package-lock.json, src/portal/package.json
1. Upgrade swagger UI and add some packages to the "allowedCommonJsDependencies" array in angular.json file
=> Clear some UI building warnings

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.scss, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
Fixes #16655 
1. Add dotted lines between the artifacts and their accessories to make it easier for users to see the relationship between them
=> Add dotted line between the artifacts and their accessories

tests/robot-cases/Group1-Nightly/Routing.robot
Add test case that open more info page to ensure correct functionality.
Fixes #(issue)
=> Add open more info page test case

src/controller/blob/controller_test.go
This fixes a dropped `err` variable in `controller/blob`.
=> fix: controller/blob: dropped test error

src/controller/artifact/controller.go, src/controller/artifact/controller_test.go
Check tag before update pull time, there are two purposes:
1. avoid noise log in the caller.("failed to update pull time, tag 0 not found")
2. reduce the db connection because `GetTag` needs query tag from db.
=> fix: check the existence of the tag before updating pull time

tests/resources/Harbor-Pages/Vulnerability.robot, tests/robot-cases/Group1-Nightly/Routing.robot
Add a test case for opening the Image Scanners Documentation Page to ensure this function is correct
Fixes #15967
=> Add open image scanners documentation page test case

src/pkg/scan/job.go
This fixes an `err` variable that was being redeclared inside an if-block with `:=` and lost.
=> pkg/scan: fix dropped error

tests/resources/Harbor-Pages/Project.robot, tests/resources/Harbor-Pages/Replication.robot, tests/robot-cases/Group1-Nightly/Replication.robot
Add test cases for these three different scenarios to ensure that Replication functions correctly after Deployment Security Policy is enabled.
Fixes #16714
=> Add test case for Enable Deployment Security Policy replication

src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.html, src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.ts, src/portal/src/app/base/project/tag-feature-integration/immutable-tag/immutable-tag.component.html, src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.html, src/portal/src/app/shared/components/global-search/global-search.component.html, src/portal/src/app/shared/components/global-search/search.component.scss, src/portal/src/i18n/lang/zh-cn-lang.json
Fix #16683
1. Fix some CSS style issues
Fixes #(issue)
=> Fix some css style issues

make/harbor.yml.tmpl, make/photon/prepare/models.py, make/photon/prepare/templates/core/env.jinja, make/photon/prepare/utils/configs.py, src/common/const.go, src/controller/artifact/abstractor.go, src/controller/artifact/controller.go, src/controller/event/handler/internal/artifact_test.go, src/controller/icon/controller.go, src/controller/repository/controller.go, src/controller/tag/controller.go, src/lib/cache/cache.go, src/lib/cache/memory/memory.go, src/lib/cache/memory/memory_test.go, src/lib/cache/redis/redis.go, src/lib/cache/redis/redis_test.go, src/lib/config/metadata/metadatalist.go, src/lib/config/systemconfig.go, src/migration/artifact.go, src/pkg/artifact/manager.go, src/pkg/cached/artifact/redis/manager.go, src/pkg/cached/artifact/redis/manager_test.go, src/pkg/cached/manager.go, src/pkg/cached/manager_test.go, src/pkg/exporter/project_collector_test.go, src/pkg/factory.go, src/pkg/factory_test.go, src/server/middleware/cosign/cosign_test.go, src/server/middleware/immutable/pushmf_test.go, src/testing/lib/cache/cache.go
Implement cache layer for resource artifact and define common
cache manager and workflow. Also add cache related options to
configuration yaml.
Closes: https://github.com/goharbor/harbor/issues/16739
`/projects/{project_name}/repositories/{repository_name}/artifacts/{reference}`
script: `hey -c 2000 -z 1m -H "Authorization: Basic YWRtaW46SGFyYm9yMTIzNDUK" http://harbor.domain/api/v2.0/projects/library/repositories/busybox/artifacts/sha256:14d4f50961544fdb669075c442509f194bdc4c0e344bde06e35dbd55af842a38`
2.5:
```bash
Summary:
Total:	62.0148 secs
Slowest:	16.1262 secs
Fastest:	0.1568 secs
Average:	1.9981 secs
Requests/sec:	980.0083
Total data:	68736525 bytes
Size/request:	1131 bytes
Response time histogram:
0.157 [1]	|
1.754 [32982] …
```
=> feat: add cache layer for artifact

make/photon/prepare/Dockerfile.base
To get reduce of CVE from photon package httpd, replace installing `httpd` by installing htpasswd binary only from photon package
Fixes #(issue)
=> replace install httpd by installing htpasswd binary only

.github/workflows/build-package.yml, Makefile, tests/ci/api_common_install.sh, tests/ci/distro_installer.sh
Change the default behavrior of building binaries for all the third parties to true.
Fixes #(issue)
=> enable default to build bin

src/portal/src/app/app.component.ts, src/portal/src/app/shared/components/navigator/navigator.component.html, src/portal/src/app/shared/components/navigator/navigator.component.ts, src/portal/src/app/shared/entities/shared.const.ts, src/portal/src/app/shared/pipes/harbor-datetime.pipe.ts, src/portal/src/app/shared/services/session.service.ts, src/portal/src/app/shared/shared.module.ts, src/portal/src/app/shared/units/shared.utils.ts
This PR makes the following improvements:
* The language code is DRYed up by defining `supportedLangs` in terms of `LANGUAGES` (previously `languageNames`).
* The language selection dropdown code is DRYed up similarly.
* The Angular locale registration code is DRYed up similarly: the omission of a supported language is now a static type error.
The above improvements mean that it's now impossible to forget to include a supported language in any of those contexts.
Furthermore:
* The type of supported languages is replaced by a more accurate one than `string`, namely `SupportedLanguage`.
* The value acquired from localStorage will never be used unless it is in fact a supported language. (Today, the GUI breaks pretty badly and errors are spammed in the console if localStorage contains an …
=> Refactor portal language code

src/portal/src/app/base/left-side-nav/labels/labels.module.ts, src/portal/src/app/base/password-setting/password-setting.component.ts, src/portal/src/app/base/project/helm-chart/helm-chart-detail/chart-detail/chart-detail-value.component.spec.ts, src/portal/src/app/base/project/helm-chart/helm-chart-detail/helm-chart.service.ts, src/portal/src/app/base/project/helm-chart/helm-chart-list/list-charts.component.spec.ts, src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.spec.ts, src/portal/src/app/shared/components/push-image/push-image.component.spec.ts, src/portal/src/app/shared/directives/port.directive.ts
This PR fixes all lint errors reported by TSLint (`npm run lint` in `src/portal/`).
TSLint also reports multiple warnings (see #16798), but this PR doesn't fix any of them.
Signed-off-by: Simon Alling <alling.simon@gmail.com>
=> Fix lint errors in portal

src/pkg/reg/adapter/dockerhub/adapter.go
It has to close the http response on deleting manifest
Fixes #(issue)
=> fix close response missing

.github/release.yml, .github/workflows/label_check.yaml
Use github autogeneration release notes and add action to check if the PR has labels
Complete and more readable relase notes
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
Fixes #(issue)
=> [cherry-pick]Add release.yml to automate release notes

src/pkg/reg/adapter/dockerhub/adapter.go
It has to close the http response on deleting manifest
Fixes #(issue)
=> [cherry-pick]fix close response missing

tests/resources/Harbor-Pages/Project-Repository.robot, tests/resources/Harbor-Pages/Project-Repository_Elements.robot, tests/resources/Imgpkg-Util.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot, tests/robot-cases/Group1-Nightly/Replication.robot
Add this test case to make sure imgpkg copy to Harbor works.
Fixes #16758
=> Add imgpkg copy test case

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
Fixes #16809
1. Improve CSS for tags column to enable resizing
Fixes #(issue)
=> Improve css for tags column

src/controller/immutable/controller_test.go, src/controller/member/controller.go, src/controller/project/controller.go, src/controller/quota/driver/project/util.go, src/controller/registry/controller.go, src/controller/repository/controller.go, src/controller/retention/controller.go, src/controller/robot/controller.go, src/core/auth/ldap/ldap_test.go, src/migration/artifact.go, src/pkg/cached/manager.go, src/pkg/cached/project/redis/manager.go, src/pkg/cached/project/redis/manager_test.go, src/pkg/factory.go, src/pkg/factory_test.go, src/pkg/member/dao/dao_test.go, src/pkg/project/manager.go, src/server/middleware/immutable/pushmf_test.go
Implement cached manager for resource project and migrate project.Mgr
to pkg.ProjectMgr.
Fixes #16740 
=> feat(project): introduce cache manager for project (#16740)

src/controller/gc/controller.go, src/controller/gc/model.go, src/server/v2.0/handler/gc.go
The `Update Time` in gc history records was incorrect.
Fixes #16355 
=> fix: gc history update_time

src/controller/gc/controller.go, src/controller/gc/model.go, src/server/v2.0/handler/gc.go
The `Update Time` in gc history records was incorrect.
Fixes #16355
=> [cherry-pick] fix: gc history update_time

src/controller/artifact/controller.go, src/controller/artifact/controller_test.go
The count should filter out the accessory, the result should be consistent with list method.
Signed-off-by: Wang Yan wangyan@vmware.com
Fixes #(issue)
=> fix artifact count issue

src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html, src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
Fixes #16842
1. Allow all roles to see the 'listed in CVE allowlist' column of CVE datagrid
Fixes #(issue)
=> Allow all roles to see 'listed in CVE allowlist' column

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.spec.ts, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
1. Improve css for accessories component
before:
after:
Fixes #(issue)
=> Improve css for accessories component

make/photon/registryctl/start.sh
When containers are terminated in Kubernetes, Kubernetes will send a SIGTERM to PID1, wait for terminationGracePeriodSeconds, then SIGKILL it.
But since PID1 in registryctl is `bash`, that SIGTERM signal is not automatically passed to the registryctl process, forcing Kubernetes to wait the whole terminationGracePeriodSeconds to update the registry Pod.
This PR fixes that issue by using `exec`, which makes `registryctl` itself be PID1 so that it receives the SIGTERM signal.
Wasn't able to test this locally, I think the build system needs some TLC, especially for testing individual components. Like for example, I need a local copy of `registry` to build the registryctl image which is downloaded from `https://storage.googleapis.com/harbor-builds/bin/registry/release-v2.8.0-patch-redis/registr …
=> Use exec in registryctl so signals are passed properly

src/pkg/reg/adapter/harbor/v2/client.go, src/pkg/reg/filter/artifact.go, src/pkg/reg/model/resource.go
=> [cherry-pick ] fix replication issue on signature

src/pkg/reg/adapter/harbor/v2/client.go, src/pkg/reg/filter/artifact.go, src/pkg/reg/model/resource.go
The tag/lable filter only works on the subject manifest, and if the subject manifest is mathed, all the accessories are marked as matched.
Fixes #(issue)
=> fix replcation issue on accessory

src/controller/project/controller.go, src/controller/project/metadata/controller.go, src/controller/scanner/base_controller.go, src/pkg/cached/manager.go, src/pkg/cached/project_metadata/redis/manager.go, src/pkg/cached/project_metadata/redis/manager_test.go, src/pkg/factory.go, src/pkg/factory_test.go, src/pkg/project/metadata/manager.go, src/server/v2.0/handler/project.go, src/server/v2.0/handler/retention.go
Implement cache layer for project_metadata and migrate metadata.Mgr to
pkg.ProjectMetaMgr.
Fixes #16891 
=> feat(project): introduce cache layer for project_metadata (#16891)

tests/resources/Harbor-Pages/HomePage_Elements.robot, tests/resources/Harbor-Pages/UserProfile_Elements.robot
Update it because #16796 modifies head_admin_xpath.
Fixes #16916
=> Update header user xpath

README.md
This PR fixes broken links in README.md
The links to badges are still referring to "master" branch instead of "main".
The links to swagger editor had the URL paths to the master branch which has hence been renamed. This leads to swagger editor failing to open the API links.
Fixes #(issue)
=> README.md: fix broken links to badges and Swagger editor

.github/workflows/CI.yml, .github/workflows/build-package.yml, .github/workflows/conformance_test.yml, CONTRIBUTING.md, Makefile, make/photon/chartserver/builder, make/photon/registry/Dockerfile.binary, make/photon/trivy-adapter/Dockerfile.binary, make/photon/trivy-adapter/builder.sh, src/go.mod, tests/ci/distro_installer.sh, tests/ci/ut_install.sh
=> bump up golang version to v1.18.3

src/controller/systemartifact/callback.go, src/controller/systemartifact/callback_test.go, src/controller/systemartifact/execution.go, src/controller/systemartifact/execution_test.go, src/core/main.go, src/jobservice/job/impl/systemartifact/cleanup.go, src/jobservice/job/impl/systemartifact/cleanup_test.go, src/jobservice/job/known_jobs.go, src/jobservice/runtime/bootstrap.go, src/testing/controller/controller.go
Scope of change:
* Introduce built-in job for system artifact clean-up.
* Associated tests
Closes https://github.com/goharbor/harbor/issues/16878
=> Introduce system artifact manager cleanup job

api/v2.0/swagger.yaml, src/server/v2.0/handler/artifact_test.go
The default value of swagger header X-Accept-Vulnerabilities should contains
scan report version 1.0 and 1.1.
Fixes #(issue)
=> fix(swagger): append scan report version 1.1 to swagger docs

src/pkg/reg/adapter/azurecr/adapter.go, src/pkg/reg/adapter/azurecr/adapter_test.go, src/pkg/reg/adapter/azurecr/auth.go, src/pkg/reg/adapter/azurecr/auth_test.go
Fix azurecr use ACR token failed to list tags, the root cause is the
scope action of acr token is 'metadata_read' not 'pull' when list v2
tags API.
Fixes [#(16888)](https://github.com/goharbor/harbor/issues/16888)
=> fix(replication): azurecr replication with token (#16888)

tests/resources/Harbor-Pages/Configuration.robot, tests/resources/Harbor-Pages/Configuration_Elements.robot, tests/resources/Harbor-Pages/Verify.robot, tests/resources/TestCaseBody.robot
Because this PR #16941 migrates CVE allowlist from Configuration System
Settings page to Configuration Security page.
Fixes #(issue)
=> Update CVE allowlist UI test case

src/jobservice/hook/hook_agent.go, src/jobservice/hook/hook_client.go, src/jobservice/runtime/bootstrap.go
Change the jobservice hook max retry concurrency from 512 to same with
the js worker numbers.
Fixes #(issue)
=> fix: update the jobservice hook retry concurrency

src/portal/package-lock.json, src/portal/package.json
1. Remove the style-lint package  and upgrade @angular-devkit/build-angular 
Fixes #(issue)
=> Remove style-lint package  and upgrade @angular-devkit/build-angular 

tests/test-engine-image/Dockerfile.common, tests/test-engine-image/Dockerfile.ui_test
1 Bump up cnab-to-oci version to v0.3.3
2 Bump up carvel-imgpkg version to v0.29.0
3 Bump up cosign version to v1.9.0
4 Bump up chromedriver version to 102.0.5005.61
Fixes #(issue)
=> Update harbor-e2e-engine image

SECURITY.md
Hyperlink for RELEASES.md points to https://github.com/goharbor/harbor/blob/master/RELEASES.md , which redirects to https://github.com/goharbor/harbor/blob/major/RELEASES.md , which is a 404. 
Fix with corrected link.
Fixes https://github.com/goharbor/harbor/issues/17020
=> In SECURITY.md, fix broken link to RELEASES.md

src/pkg/systemartifact/manager.go, src/pkg/systemartifact/manager_test.go, src/server/v2.0/handler/statistic.go, src/server/v2.0/handler/statistic_test.go, src/testing/pkg/systemartifact/manager.go
Project name validation to prevent system artifact reserved project names
Include system artifact size in system storage space calculation.
Fixes #(issue)
=> Project name validation to prevent system artifact reserved project names

src/.golangci.yaml
This PR is to enable structcheck/typecheck/unused for golangci-lint
Fixes #(issue)
=> fix: enable structcheck/typecheck/unused for golangci-lint

api/v2.0/swagger.yaml, src/controller/purge/controller.go, src/jobservice/job/impl/purge/purge.go, src/jobservice/job/impl/purge/purge_test.go, src/server/v2.0/handler/purge.go, src/testing/controller/purge/controller.go
=> Support stop purge audit log job

make/photon/prepare/Dockerfile.base
=> Upgrade pipenv to 2022.1.8

src/controller/retention/controller.go, src/pkg/retention/models.go, src/server/v2.0/handler/retention.go
Add not-found handling for non exist items in retention operation.
Fixes #(issue)
=> Unify retention schedule/task retrieve and update

.github/workflows/build-package.yml
No need to build package when push tag
Fixes #(issue)
=> Modify Build Package Workflow trigger condition

src/core/main.go
Scheduling of system artifact depends on the jobservice, where gorountine is used to avoid the circular dependencies between core and jobservice.
Fixes #(17008)
=> Resovle the system artifact schedule issue

src/pkg/task/dao/execution.go
It causes the execution status to be unchanged in a high concurrency situation.
This reverts commit b6e4ef5b5485677b3a676adaa510a69c7390f7c4.
Fixes #(issue)
=> Revert "Skip to refresh execution status when unchanged(#17034)"

.github/workflows/housekeeping-stale-issues-prs.yaml
- reducing the stale ime to 30 days
- adding operations-per-run to 1000 so we can clean a bit more
Fixes #(issue)
=> Making stale bot a bit more active

make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja
Generally, we don't need to migrate the harbor.yml between patch release, for example(v2.5.0 to v2.5.2)
so if we running the prepare migrate command, if would return `no need to upgrade` msg. So this would not impact the user upgrade Harbor from v2.5.0 to follwing patch release.
```
$ docker run -it --rm -v /:/hostfs goharbor/prepare:[tag] migrate -i ${path to harbor.yml}
=> Version of input harbor.yml is identical to target 2.5.0, no need to upgrade
```
Since the uploading_purging is a new config/feature in release-2.5.0, when user migrate from v2.4.x to v2.5.0,(or v2.5.1, or v2.5.2), NO uploading_purging configurations in the previous harbor.yml file, so it would generate using the default one
So, it …
=> 2.5 migration jinja correction for upload_purging

src/jobservice/runtime/bootstrap.go, src/pkg/scan/rest/v1/client_pool.go
os.Kill cannot be trapped. May refer to [SA1016](https://staticcheck.io/docs/checks#SA1016)
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
=> Remove os.Kill in signal handling

make/migrations/postgresql/0082_2.5.3_schema.up.sql, make/migrations/postgresql/0090_2.6.0_schema.up.sql
Add migrations sql to repair the execution status when it does not
consistent with task status.
Closes: #17114
Fixes #([17114](https://github.com/goharbor/harbor/issues/17114))
=> fix: repair execution status when it inconsistent

src/controller/robot/controller.go, src/controller/robot/controller_test.go, src/server/v2.0/handler/robot.go
In some cases, the robot automatically generates passwords that do not meet confidentiality requirements.
The fix adds retry for auto generating passwords, and the timeout is 1 minute.
The requirement: the secret must longer than 8 chars with at least 1 uppercase letter, 1 lowercase letter and 1 number
Fixes #(16137)
=> resolve robot authgen password format issue

src/portal/src/app/base/project/project-detail/project-detail.component.ts, src/portal/src/app/base/project/tag-feature-integration/tag-feature-guard.service.ts, src/portal/src/app/base/project/tag-feature-integration/tag-feature-integration.component.html, src/portal/src/app/base/project/tag-feature-integration/tag-feature-integration.component.scss, src/portal/src/app/base/project/tag-feature-integration/tag-feature-integration.component.spec.ts, src/portal/src/app/base/project/tag-feature-integration/tag-feature-integration.component.ts, src/portal/src/app/base/project/tag-feature-integration/tag-feature-integration.module.ts, src/portal/src/app/shared/router-guard/member-permission-guard-activate.service.ts, src/portal/src/css/common.scss, src/portal/src/css/dark-theme.scss, src/portal/src/css/light-theme.scss
1. Fixes #17100
Now, the Developer role can view tag-retention rules
Fixes #(issue)
=> Developer role should be able to view tag-retention rules

.github/workflows/housekeeping-stale-issues-prs.yaml
- 60 days grace period for stale
- exclude issues and PR with labels : never-stale, kind/requirement
Fixes #(issue)
=>  Tune stale action

tests/resources/Harbor-Pages/ToolKit.robot, tests/robot-cases/Group1-Nightly/Common.robot
Because this PR(#16236) update the delete project button xpath, so update synchronously
Fixes #(issue)
=> Update delete multi project testcase

src/.golangci.yaml, src/controller/event/handler/webhook/artifact/artifact.go, src/controller/event/handler/webhook/quota/quota.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
Just notice https://github.com/goharbor/harbor/pull/17131 in my timeline.
Use [ST1019](https://staticcheck.io/docs/checks#ST1019) will make golangci-lint auto report "importing the same package multiple times" problems, like below:
```bash
controller/event/handler/webhook/artifact/artifact.go:30:2: ST1019: package "github.com/goharbor/harbor/src/pkg/notifier/model" is being imported more than once (stylecheck)
"github.com/goharbor/harbor/src/pkg/notifier/model"
^
controller/event/handler/webhook/artifact/artifact.go:31:2: ST1019(related information): other import of "github.com/goharbor/harbor/src/pkg/notifier/model" (stylecheck)
notifyModel "github.com/goharbor/harbor/src/pkg/notifier/model"
^
``` …
=> delete duplicate import and use ST1019 in golangci-lint

src/controller/artifact/controller.go, src/controller/artifact/controller_test.go, src/pkg/artifact/dao/dao.go
Fixed #17145
1, Filter the accessory from the artifact list.
2, Disable the display func of the accessory interface, currently this will not impact any kind of accessory, like signature and nydus. If we'd like to introduce it, it needs to resolve the pagiation issue of artifact list.
Fixes #(issue)
=> Filter out accessory from list artifact results

src/common/rbac/project/rbac_role.go, src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/controller/scan/controller.go, src/core/api/chart_label.go, src/server/v2.0/handler/artifact.go, src/server/v2.0/handler/robot.go, src/server/v2.0/handler/scan.go, src/testing/controller/scan/controller.go
1, add check in label
2, check robot account update
3, validate scan log
Fixes #(issue)
=> [cherry-pick] Fix scan log mismatch issue

src/core/main.go, src/server/registry/route.go
Support of manifest list in Nydus service side is still remained to be discussed.
Harbor would hold this feature in this v2.6 release and enable it  until there's a clear plan for nydus/image-acceleration service to support manifest index / manifest list considered to a better user experience
https://github.com/goharbor/harbor/issues/17212
=> Disable Nydus middleware for v2.6

src/server/middleware/security/idtoken.go, src/server/middleware/security/idtoken_test.go
I can query the harbor API with my OIDC token, but unfortunately I cannot get a distribution token.
This PR fixes that. 
This PR enables us to build facades/proxies to harbor that act as custom PHP composer or JS npm registries over OCI Artifacts with OIDC Token support instead of CLI secrets.
=> fix: oidc token is not respected in /service/token endpoint

src/core/service/token/authutils.go, src/core/service/token/token_test.go, src/pkg/token/claims/robot/robot.go, src/pkg/token/claims/v2/claims.go, src/pkg/token/claims/v2/claims_test.go, src/pkg/token/token_test.go
StandardClaims are Deprecated and may might lead to incompatibilities with other JWT implementations. The use of this is discouraged.
Use RegisteredClaims instead for a forward-compatible way to access registered claims in a struct.
Signed-off-by: wujunwei <wjw3323@live.com>
=> feature: Use RegisteredClaims instead of deprecated staruct StandardClaims

tests/apitests/python/library/base.py, tests/apitests/python/library/purge.py, tests/apitests/python/test_log_rotation.py, tests/robot-cases/Group0-BAT/API_DB.robot
Added test cases for the following APIs:
1. PUT /system/purgeaudit/{purge_id}  Stop the specific purge audit log execution
2. GET /system/purgeaudit/{purge_id}  Get purge job status
3. GET /system/purgeaudit/{purge_id}/log  Get purge job log
4. PUT /system/purgeaudit/schedule   Update purge job's schedule
5. POST /system/purgeaudit/schedule  Create a purge job schedule
6. GET /system/purgeaudit/schedule  Get purge's schedule
7. GET /system/purgeaudit  Get purge job results.
Fixes #17174
=> Add purge audit log API test cases

tests/apitests/python/library/base.py, tests/apitests/python/library/purge.py, tests/apitests/python/test_log_rotation.py, tests/robot-cases/Group0-BAT/API_DB.robot
Added test cases for the following APIs:
1. PUT /system/purgeaudit/{purge_id}  Stop the specific purge audit log execution
2. GET /system/purgeaudit/{purge_id}  Get purge job status
3. GET /system/purgeaudit/{purge_id}/log  Get purge job log
4. PUT /system/purgeaudit/schedule   Update purge job's schedule
5. POST /system/purgeaudit/schedule  Create a purge job schedule
6. GET /system/purgeaudit/schedule  Get purge's schedule
7. GET /system/purgeaudit  Get purge job results.
Fixes #(issue)
=> [cherry-pick]Add purge audit log API test cases

src/common/utils/utils.go
change log level to debug to avoid noise
Fixes #(issue)
=> Return time.Time{} when cron string is empty

src/go.mod, src/go.sum, src/vendor/github.com/docker/distribution/.mailmap, src/vendor/github.com/docker/distribution/Dockerfile, src/vendor/github.com/docker/distribution/README.md, src/vendor/github.com/docker/distribution/docker-bake.hcl, src/vendor/github.com/docker/distribution/version/version.go, src/vendor/modules.txt
Signed-off-by: lengrongfu <1275177125@qq.com>
Upgrade distribution version from v2.8.0 to v2.8.1, because v2.8.0 tag does not match checksum.
issue: https://github.com/goharbor/harbor/issues/17295
=> fix: distribution v2.8.0 tag does not match checksum

make/migrations/postgresql/0090_2.6.0_schema.up.sql, src/controller/quota/controller.go, src/controller/quota/options.go, src/pkg/clients/core/client.go, src/pkg/retention/dep/client.go, src/pkg/retention/dep/client_test.go, src/pkg/retention/job.go, src/server/middleware/quota/quota.go, src/server/middleware/security/utils.go, src/server/middleware/security/utils_test.go
1. Add two indexes to database migrations.
2. Skip refresh quota in middleware for requests from jobservice.
3. Refresh quota by self in the end of tag retention job.
Closes: #14708
Fixes #(#14708)
=> [cherry-pick] fix: reduce the high db cpu usage for tag retention

make/migrations/postgresql/0090_2.6.0_schema.up.sql, src/controller/quota/controller.go, src/controller/quota/options.go, src/pkg/clients/core/client.go, src/pkg/retention/dep/client.go, src/pkg/retention/dep/client_test.go, src/pkg/retention/job.go, src/server/middleware/quota/quota.go, src/server/middleware/security/utils.go, src/server/middleware/security/utils_test.go
1. Add two indexes to database migrations.
2. Skip refresh quota in middleware for requests from jobservice.
3. Refresh quota by self in the end of tag retention job.
Closes: #14708
Fixes https://github.com/goharbor/harbor/issues/14708
=> fix: reduce the high db cpu usage for tag retention

src/controller/event/handler/webhook/artifact/replication.go, src/controller/event/handler/webhook/artifact/replication_test.go
Fix the replication webhook notification lost when the rule is
pull-based and src namespace different with dest.
Closes: #17298
Fixes #(#17298)
=> fix: replication webhook lost when src namespace different with dest

src/controller/event/handler/webhook/artifact/replication.go, src/controller/event/handler/webhook/artifact/replication_test.go
Fix the replication webhook notification lost when the rule is
pull-based and src namespace different with dest.
Closes: #17298
Fixes (#17298)
=> [cherry-pick] fix: replication webhook lost when src namespace different with dest

src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/pkg/scan/export/export_data_selector.go, src/pkg/scan/export/export_data_selector_test.go, src/pkg/scan/export/manager.go, src/pkg/scan/export/manager_test.go, src/pkg/scan/export/model.go
Closes: https://github.com/goharbor/harbor/issues/17189
Scope of change:
Fetched data column named `vendor_attributes` when exporting CSV data and dumping the data into the `Additional Data`  column.
Fixes #(issue)
=> Export CVE data Score column empty values

src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/server/v2.0/handler/scanexport.go, src/server/v2.0/handler/scanexport_test.go
1. Validate export cve request params in the API handler
2. Trim space for request in the scan export job
Closes: #17326
Fixes #17326
=> [cherry-pick] fix: validate export cve request params

src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.ts, src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.html, src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.scss, src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts, src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.html, src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.scss, src/portal/src/app/base/project/project-detail/project-detail.component.html, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
Fixes #17348
Fixes #17346
1. change `Storage used`  to  `Quota used` to avoid confusion
2. Improve style for value text of status  to adapt to different resolutions
Fixes #(issue)
=> Fix ui issues found in testing-day-round-2

make/install.sh
when we are installing harbor using `sudo ./install.sh --with-notary --with-chartmuseum`, there would be a deprecation warning message for notary or chartmusuem.
Fixes #(issue)
=> add deprecation msg for chartmsuem and notary

api/v2.0/swagger.yaml
Correct the description for the project parameter of export CVE API in
the swagger.
Closes: #17429
Fixes #17429 
=> fix: correct description for export cve project parameter

api/v2.0/swagger.yaml
Correct the description for the project parameter of export CVE API in
the swagger.
Closes: #17429
Fixes #17429
=> [cherry-pick] fix: correct description for export cve project parameter

make/photon/prepare/migrations/version_1_10_0/__init__.py, make/photon/prepare/migrations/version_1_9_0/__init__.py, make/photon/prepare/migrations/version_2_0_0/__init__.py, make/photon/prepare/migrations/version_2_1_0/__init__.py, make/photon/prepare/migrations/version_2_2_0/__init__.py, make/photon/prepare/migrations/version_2_3_0/__init__.py, make/photon/prepare/migrations/version_2_4_0/__init__.py, make/photon/prepare/utils/jinja.py
This resolves the bugs observed [here](https://lift.sonatype.com/result/bhamail/harbor/01FHG1B5AJ8MXCH0A05BMBNWWT?t=CustomTool%20%22Bandit%22%7Cjinja2_autoescape_false) by Sonatype Lift.
=> Add autoescape parameter to jinja environments

make/photon/nginx/Dockerfile.base, make/photon/portal/Dockerfile.base
Installing nginx 1.22 creates the nginx group and nginx user, so instead
of creating them again, modify them.
Fixes #17440 
=> Update portal-base and nginx-base Dockerfile.base

make/photon/nginx/Dockerfile.base, make/photon/portal/Dockerfile.base
Installing nginx 1.22 creates the nginx group and nginx user, so instead
of creating them again, modify them.
Fixes #17440
=> [cherry-pick]Update portal-base and nginx-base Dockerfile.base

src/portal/src/i18n/lang/zh-cn-lang.json
Fixes #17370
1. Correct i18n key in zh-cn-lang.json
Fixes #(issue)
=> Correct i18n key for zh-cn-lang.json

src/lib/cache/redis/util.go, src/lib/cache/redis/util_test.go
Handle the ParseSentinelURL to resolve an incompatible modification that does not recognize the default redis database.
Closes: #17483
Fixes #17483
=> fix: handle the break change for parse external sentinel redis url

src/lib/cache/redis/util.go, src/lib/cache/redis/util_test.go
Handle the ParseSentinelURL to resolve an incompatible modification that does not recognize the default redis database.
Closes: #17483
Fixes #17483
=> [cherry-pick] fix: handle the break change for parse external sentinel redis url

src/pkg/reg/adapter/awsecr/adapter.go
Pass in the correct endpoint to AWS ECR client config, so at the time of fetching token, the token will be valid for the target endpoint.
Fixes [#(issue)](https://github.com/goharbor/harbor/issues/15388)
Currently, when AWS ECR client is created, it defaults the endpoint to whatever AWS_ACCESS_KEY_ID belongs to and thus falls short in the cross account case. The proposed fix sets the endpoint explicitly so it works in all cases.
=> Fix cross account issue

.github/dependabot.yml
We need dependabot enabled to get higher score on the OSSF scorecard https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool and here https://clomonitor.io/projects/cncf/harbor
Fixes #(issue)
=> Add dependabot.yaml to enable PRs

src/jobservice/job/impl/gc/garbage_collection_test.go, src/jobservice/tests/utils.go
Signed-off-by: Gaius <gaius.qi@gmail.com>
- Add `GetRedisURL` to `src/jobservice/tests` pkg.
- Fix hardcoded redis url in `src/jobservice/job/impl/gc/garbage_collection_test.go`.
Fixes #(issue)
=> test: add GetRedisURL to tests redis pkg and fix hardcoded redis url

src/server/middleware/repoproxy/proxy.go
Check project is default project format in dockerhub
Redirect blob/manifest request to default url
Fixes #12719
Fixes #(issue)
=> Add default project when pulling from dockerhub without project name

.github/dependabot.yml
Add labels for github action as infra for release notes and add update for all other components
Fixes #(issue)
=> Add labeling for dependa bot PRs

src/core/controllers/oidc.go, src/portal/src/app/account/sign-in/sign-in.component.html, src/portal/src/app/oidc-onboard/oidc-onboard.component.ts
Fix redirect URL parameter `redirect_url` in case the user is redirected to sign-in screen in OIDC.
The fix is using server-side session storage to track the original URL being requested before login redirect.
Fixes #17594
=> Fix redirect url redirect_url  when OIDC auth mode is enabled

src/chartserver/utils_test.go, src/controller/robot/controller_test.go, src/jobservice/api/handler_test.go, src/jobservice/common/utils/utils_test.go, src/jobservice/config/config_test.go, src/jobservice/job/impl/gc/garbage_collection_test.go, src/jobservice/job/impl/notification/slack_job_test.go, src/jobservice/job/impl/notification/webhook_job_test.go, src/lib/config/test/userconfig_test.go, src/pkg/immutable/manager_test.go, src/pkg/joblog/managet_test.go, src/registryctl/config/config_test.go, src/server/registry/handler_test.go
A testing cleanup.
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
```go
func TestFoo(t *testing.T) {
// before
key := "ENV"
originalEnv := os.Getenv(key)
if err := os.Setenv(key, "new value"); err != nil {
t.Fatal(err)
}
defer func() {
if err := os.Setenv(key, originalEnv); err != nil {
t.Logf("failed to set env %s back to original value: %v", key, err)
}
}()
// after
t.Setenv(key, "new value")
}
```
=> test: use `T.Setenv` to set env vars in tests

src/controller/scandataexport/execution.go, src/controller/scandataexport/execution_test.go, src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/server/v2.0/handler/scanexport.go, src/server/v2.0/handler/scanexport_test.go
Add human friendly when export CVE in the condition of empty CSV file, because this file will be stored as system artifact and pushed to distribution, but it will leads to error when push empty blob to S3 storage driver.
Fixes #(issue)
=> fix: add human friendly message when export cve job failure

src/controller/scandataexport/execution.go, src/controller/scandataexport/execution_test.go, src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/server/v2.0/handler/scanexport.go, src/server/v2.0/handler/scanexport_test.go
Add human friendly when export CVE in the condition of empty CSV file, because this file will be stored as system artifact and pushed to distribution, but it will leads to error when push empty blob to S3 storage driver.
Fixes #(issue)
=> [cherry-pick] fix: add human friendly message when export cve job failure

src/server/v2.0/handler/user.go, src/server/v2.0/handler/user_test.go
give an random cli secret when client gives empty update.
Fixes #(issue)
=> add cli randomly for empty update

make/photon/prepare/templates/core/env.jinja, src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
Enables the support of JFrog Artifactory as a source for proxy-cache. I have tested this with a local build and was able to proxy images just fine.
Signed-off-by: Derrik Campau <dcampau@vmware.com>
Adds JFrog Artifactory as a permitted source registry for proxy-cache projects. 
Related PR: https://github.com/goharbor/harbor-helm/pull/1338 
=> Add JFrog Artifactory As Supported Proxy-Cache Registry Source

api/v2.0/swagger.yaml, src/common/const.go, src/lib/config/metadata/metadatalist.go, src/lib/config/models/model.go, src/lib/config/userconfig.go, src/pkg/oidc/helper.go, src/pkg/oidc/helper_test.go
Filter out the OIDC group which doesn't match the regular expression when user login
It doesn't filter the group when administrator adds the group manually in project member or user_group.
Fixes #17130
Fixes #(issue)
=> Add OIDC group filter

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.spec.ts, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-info/artifact-info.component.ts
Fixes #14138
1. Fix the permission issue for the edit button of repo info to make it consistent with the doc
Fixes #(issue)
=> Fix permission issue for edit button of repo info

tests/apitests/python/library/oras.py, tests/ci/api_run.sh, tests/resources/Harbor-Pages/Verify.robot, tests/resources/Util.robot, tests/test-engine-image/Dockerfile.api_test, tests/test-engine-image/Dockerfile.common, tests/test-engine-image/Dockerfile.ui_test, tests/test-engine-image/build.sh
1. Update ubuntu version to 20.04
2. Update containerd version to 1.6.9
3. Update docker-compose version to 2.12.2
4. Update helm version to 3.10.1
5. Update ORAS version to 0.16.0
6. Update CNAB version to 0.3.7
7. Update imgpkg version to 0.33.0
8. Update cosign version to 1.13.1
9. Remove singularity
Fixes #(issue)
=> Update e2e engine image

api/v2.0/swagger.yaml, src/common/const.go, src/core/session/session.go, src/core/session/session_test.go, src/lib/config/metadata/metadatalist.go, src/lib/config/userconfig.go
Add configuration session_timeout for API, then user can customize the timeout from system config page or API. The timeout is 60 minutes by default.
Fixes https://github.com/goharbor/harbor/issues/17474
=> feat: support customize session timeout

src/server/v2.0/handler/usergroup.go, src/server/v2.0/handler/usergroup_test.go
=> Sort group search result by most match order

src/.golangci.yaml, src/chartserver/cache.go, src/common/api/base.go, src/controller/artifact/processor/default.go, src/controller/p2p/preheat/controller.go, src/jobservice/job/impl/purge/purge.go, src/jobservice/job/impl/sample/job.go, src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/logger/base.go, src/lib/orm/metadata.go, src/lib/orm/orm.go, src/lib/orm/query.go, src/pkg/accessory/model/accessory.go, src/pkg/cached/base_manager.go, src/pkg/p2p/preheat/provider/driver.go, src/pkg/reg/adapter/googlegcr/adapter.go, src/pkg/scan/rest/v1/models.go, src/server/registry/tag.go, src/server/v2.0/handler/auditlog.go, src/server/v2.0/handler/model/gc.go, src/server/v2.0/handler/notification_job.go, src/server/v2.0/handler/notification_policy.go, src/server/v2.0/handler/preheat.go, src/server/v2.0/handler/purge.go, src/server/v2.0/handler/scan_all.go, src/server/v2.0/handler/scanexport.go, tests/ci/ut_install.sh
- deprecated linters: `varcheck`, `structcheck`, `deadcode`, deprecated since golangci-lint v1.49.0
- disabled `unused ` linter due to too many false positive check in upstream repo and  limited support for golang 1.19
https://github.com/dominikh/go-tools/issues/1282
https://github.com/dominikh/go-tools/releases/tag/v0.3.3
- fix several linter-checked files:
`gosimple`:  S1009: should omit nil check len() for ...file is defined as zero
`gofmt`
`stylecheck`
`staticcheck` : strings.Title has been deprecated since go 1.18
=> update golangci-lint for golang1.19

src/controller/scandataexport/execution.go, src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/pkg/scan/export/constants.go, src/server/v2.0/handler/scanexport.go, src/server/v2.0/handler/scanexport_test.go, tests/apitests/python/test_scan_data_export.py
1. Skip to push system artifact to the distribution when the exported CSV file is empty.
2. Add status message for cve export execution.
Fixes https://github.com/goharbor/harbor/issues/17700
=> fix: skip to push system artifact for empty CSV file

src/replication/adapter/quayio/adapter_test.go
=> fix: refine the quay adapter UT

src/controller/proxy/controller.go, src/controller/proxy/manifestcache.go
=> Fix issue related to redhat registry proxy cache

.github/workflows/build-package.yml, .github/workflows/publish_release.yml
ubuntu-latest was upgraded from ubuntu-20.04 to ubuntu-22.04, the python version of ubuntu-22.04 is 3.10, but gcloud does not support python 3.10, so ubuntu is fixed to version 20.04
Fixes #(issue)
=> Fix setup gcloud error

.github/workflows/build-package.yml, .github/workflows/publish_release.yml
ubuntu-latest was upgraded from ubuntu-20.04 to ubuntu-22.04, the python version of ubuntu-22.04 is 3.10, but gcloud does not support python 3.10, so ubuntu is fixed to version 20.04
Fixes #(issue)
=> [cherry-pick]Fix setup gcloud error

src/common/job/client.go, src/controller/jobmonitor/monitor.go, src/pkg/jobmonitor/redis.go
Convert the redis range result into struct and extract job id from it
Add more log when get redis config fails
Fixes #(issue)
=> Stop Pending Job cannot update status

.github/workflows/nightly-trivy-scan.yml
This PR adds a new workflow that scans the generated docker images for security vulnerabilities using trivy scanner. The workflow is set as nightly, since the security scanning needs to be done daily instead of just on push. This will help to know about reported CVEs proactively. 
Currently the following images are added which can be extended by adding into the workflow matrix
images: 
- harbor-core
- harbor-db
- harbor-exporter
- harbor-jobservice
- harbor-log
- harbor-portal
- harbor-registryctl
- prepare
tags: `dev`, `v2.6.2` and `1.10.14` 
NOTE: The tests will fail currently as there are a few CVEs reported in the images.
Signed-off-by: Akhil Mohan <akhilerm@gmail.com>
Fixes #17677 
=> add new workflow for nightly image scan

api/v2.0/swagger.yaml, src/pkg/jobmonitor/model.go, src/server/v2.0/handler/jobservice.go
=> Remove job parameters and schedule extra attribute 

.buildbaselog
=> Refresh base images

src/pkg/p2p/preheat/provider/dragonfly.go, src/server/middleware/repoproxy/proxy.go
=> Update the log information in proxy cache

make/migrations/postgresql/0100_2.7.0_schema.up.sql
use sql in the migration process to delete all the useless data of table artifact_blob
Fixes #(issue)
=> remove the redundant data from table artifact_blob

src/pkg/scheduler/scheduler.go, src/pkg/task/execution.go
=> (cherry-pick) Avoid internal error in the UI when reset a schedule

.buildbaselog, make/photon/nginx/Dockerfile.base, make/photon/portal/Dockerfile.base
Installing nginx 1.22 creates the nginx group and nginx user, so instead of creating them again, modify them.
Fixes #(issue)
=> [cherry-pick]Update portal-base and nginx-base Dockerfile.base (#17442)

src/lib/config/metadata/type.go, src/lib/config/metadata/type_test.go, src/lib/config/metadata/value.go
Fix the time duration type duplicated parse for config, maintaining the idempotency of set and get operations.
Fixes #(issue)
=> [cherry-pick] fix: fix the time duration type duplicated parse for config

src/jobservice/job/impl/gc/util.go
When debugging #17984, the error message of the Garbage Collector was 
````
exit with error: run error: error retrieving 'blobs::*' keys
````
This gave the wrong impression, that something was wrong with the content of redis.
Applying this fix gave
````
error retrieving 'blobs::*' keys: dial tcp: lookup harbor-redis.example.com on 127.0.0.1:53: no such host, pattern blobs::*
````
which points in a completly different direction. This fix prints the original redis error in the error message to avoid such confusion.
Relates #14922 
Relates  #17984
=> fix: Don't supress redis error messages to make debugging easier

.github/workflows/CI.yml, .github/workflows/codeql-analysis.yml
No need to do full test if internal documentations is changed! Saves resources and makes the PR test much faster!
=> Skip CI tests when *.md modifications are made

src/jobservice/job/impl/purge/purge.go
Signed-off-by: al-cheb [alk.chebotov@gmail.com](mailto:alk.chebotov@gmail.com)
Fix typo in info message:
`2022-12-23T08:11:05Z [INFO] [/jobservice/job/impl/purge/purge.go:110]: Purge operation parameter, renention_hour=168, include_operations:[create delete pull], dry_run:false`
Fixes #(issue)
=> fix purge info typo

src/pkg/reg/util/pattern_test.go
When I am configuring the replication strategy and want to match certain versions, I can simply set it like this for the time being;
```
eg: v2.[4-6].*
```
However, if you need to match certain fixed versions, it cannot be realized. I hope to support the configuration of multiple regular functions, such as: v2.0, v3.0.
Fixes #(issue)
release-note/update
=> add match many version pattern test

make/photon/jobservice/Dockerfile, make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja, make/photon/prepare/utils/jobservice.py, src/pkg/scan/export/constants.go
1. Change the Export CVE temporary file directory to /tmp.
2. Remove the scan data export volume in Dockerfile and docker-compose yaml.
Fixes: #18067
Fixes #18067
=> fix: remove the scan exports volume

src/pkg/reg/adapter/awsecr/auth.go
Harbor should not assume that if AWS Credentials are not defined that the user wants to use `ec2rolecreds`.  Rather, it should allow the AWS SDK to resolve credentials by passing `nil` Credentials:
https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials
This _should_ be backwards compatible because the defualt provider chain does look for: `4. If your application is running on an Amazon EC2 instance, IAM role for Amazon EC2.`
Fixes #15007
=> aws auth use default creds when none are supplied

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.scss, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.ts, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts, src/portal/src/app/base/project/repository/artifact/artifact.ts
1.Fixes https://github.com/goharbor/harbor/issues/18082
2.Update CSS
Fixes #(issue)
=> [Cherry-pick]Support searching artifacts by specified tag name

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.scss, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.ts, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts, src/portal/src/app/base/project/repository/artifact/artifact.ts
1.Fixes #18082
2.Update CSS
Fixes #(issue)
=> Support searching artifacts by specified tag name

src/controller/replication/execution.go, src/controller/replication/execution_test.go, src/server/v2.0/handler/replication.go
1. Check execution before stop replication execution.
2. Check execution before list replication tasks.
Fixes #(issue)
=> [cherry-pick] fix: update the replication API handler

src/controller/replication/execution.go, src/controller/replication/execution_test.go, src/server/v2.0/handler/replication.go
1. Check execution before stop replication execution.
2. Check execution before list replication tasks.
Fixes #(issue)
=> fix: update the replication API handler

src/controller/scandataexport/execution.go, src/controller/scandataexport/execution_test.go, src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/pkg/scan/export/filter_processor.go, src/pkg/scan/export/filter_processor_test.go, src/server/v2.0/handler/scanexport.go, src/testing/pkg/scan/export/filter_processor.go
Remove the project filter in the scan data export job as they have been validated by API handler, fix the oidc or ldap group users cannot export cve.
Fixes: #18112
Fixes #(issue)
=> [cherry-pick] fix: resolve the oidc or ldap group user cannot export cve

tests/apitests/python/library/base.py, tests/apitests/python/library/gc.py, tests/apitests/python/library/jobservice.py, tests/apitests/python/library/preheat.py, tests/apitests/python/library/purge.py, tests/apitests/python/library/retention.py, tests/apitests/python/library/scan_all.py, tests/apitests/python/library/schedule.py, tests/apitests/python/test_job_service_dashboard.py, tests/robot-cases/Group0-BAT/API_DB.robot
Added test cases for the following APIs:
1. GET /jobservice/pools/{pool_id}/workers Get workers
2. PUT /jobservice/jobs/{job_id} Stop running jc
3. PUT /jobservice/queues/{job_type} stop and clean, pause, resume pending jobs in the queue
4. GET /jobservice/queues list job queues
5. GET /jobservice/pools Get worker pools
6. GET /schedules List schedules
7. GET /schedules/{job_type}/paused Get scheduler paused status
Fixes #17948
=> Add JobService Dashboard API test cases

src/controller/scandataexport/execution.go, src/controller/scandataexport/execution_test.go, src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/pkg/scan/export/filter_processor.go, src/pkg/scan/export/filter_processor_test.go, src/server/v2.0/handler/scanexport.go, src/testing/pkg/scan/export/filter_processor.go
Remove the project filter in the scan data export job as they have been validated by API handler, fix the oidc or ldap group users cannot export cve.
Fixes: #18112
Fixes #18112 
=> fix: resolve the oidc or ldap group user cannot export cve

make/photon/db/Dockerfile.base
1. Update the path to postgresql.conf.sample as it has changed in postgresql 13.10
2. Remove creating symbolic link as it already exists in postgresql 13.10
Fixes #(issue)
=> [cherry-pick]Update DB Dockerfile.base

make/photon/db/Dockerfile.base
1. Update the path to postgresql.conf.sample as it has changed in postgresql 13.10
2. Remove creating symbolic link as it already exists in postgresql 13.10
Fixes #(issue)
=> Update DB Dockerfile.base

src/portal/src/app/base/left-side-nav/config/config.ts, src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html, src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
1. Related backend PR #17807
2. This PR should be merged after #17807
Fixes #(issue)
=> Add scanner_skip_update_pulltime property for system setting

src/portal/src/app/base/project/tag-feature-integration/immutable-tag/immutable-tag.component.html, src/portal/src/app/base/project/tag-feature-integration/tag-retention/retention.ts, src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.html, src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.ts
1. Add the next scheduled time UI
2. Update font style
3. Related issue #17399
Fixes #(issue)
=> Add next scheduled time for tag retention

make/migrations/postgresql/0110_2.8.0_schema.up.sql
Update replication_policy as Harbor v2.8.0 deprecates chartmuseum. Harbor deprecates chartmuseum as of v2.8.0
Epic: #17958
Discussion: #15057
Fixes #(issue)
=> Update the replication rule related to the Chartmuseum

src/controller/p2p/preheat/enforcer.go, src/controller/p2p/preheat/enforcer_test.go, src/controller/scan/base_controller.go, src/controller/scan/controller.go, src/server/middleware/vulnerable/vulnerable.go, src/testing/controller/scan/controller.go
The allowlist is applied even after the expiration time has passed.
Signed-off-by: hyeyoung-leee hyeyoung.lee@nhn.com
Fixes #18078 
- [ x ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).
=> Modified to check the expiration time of the allowlist when determining the vulnerability of an artifact

src/common/security/robot/context.go, src/common/security/robot/context_test.go
Fixes #17636, to determine permissions for the project resource, the path should be /project instead of /project/project.
Fixes #(issue)
=> fix robot account list project

src/controller/scandataexport/execution.go, src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/pkg/scan/export/manager.go
Change the JobId param type from int to string, use int will bring some problems for encode/decode type mismatch which generate the invalid repository name.
Fixes: #18380
Fixes #18380
=> [cherry-pick] fix: fix the invalid jobid for scan data export

src/controller/scandataexport/execution.go, src/jobservice/job/impl/scandataexport/scan_data_export.go, src/jobservice/job/impl/scandataexport/scan_data_export_test.go, src/pkg/scan/export/manager.go
Change the JobId param type from int to string, use int will bring some problems for encode/decode type mismatch which generate the invalid repository name.
Fixes: #18380
Fixes #18380
=> fix: fix the invalid jobid for scan data export

src/pkg/notifier/handler/notification/slack_handler.go, src/pkg/notifier/handler/notification/slack_handler_test.go
Escape the event data of slack webhook as original payload is invalid when send to slack.
Fixes: #18423
Fixes #18423
=> [cherry-pick] fix: escape the event data for slack webhook payload

src/pkg/notifier/handler/notification/slack_handler.go, src/pkg/notifier/handler/notification/slack_handler_test.go
Escape the event data of slack webhook as original payload is invalid when send to slack.
Fixes: #18423
Fixes #18423
=> fix: escape the event data for slack webhook payload

api/v2.0/swagger.yaml, make/migrations/postgresql/0110_2.8.0_schema.up.sql, src/server/v2.0/handler/webhook.go
1. Add migration SQL to handle the lost payload format for old policies.
2. Set payload format to 'Default' if not specified for http webhook in the API handler.
3. Fix the migration SQL of notification_job.
Fixes: #18401,#18453
Fixes #18401,#18453
=> fix: add default payload_format for http type webhook

src/controller/event/handler/webhook/artifact/retention.go, src/controller/event/metadata/retention.go, src/controller/event/topic.go
Fix the incorrect number of total and retained in the retention webhook payload, and completes the deleted_artifacts field.
Fixes: #18428
Fixes #18428
=> fix: correct the retention webhook payload

src/controller/systemartifact/execution.go, src/core/main.go, src/pkg/scheduler/scheduler.go, src/pkg/scheduler/scheduler_test.go
Wrap orm tx when the scheduler try to create the task because submit job maybe failure depends on the jobservice.
Fixes: #18452
Fixes #18452
=> fix: wrap schedule/exec/task creation as orm tx

src/common/const.go, src/core/main.go, src/lib/config/metadata/metadatalist.go, src/lib/config/systemconfig.go, src/lib/gtask/pool.go, src/lib/gtask/pool_test.go, src/lib/shuffle.go, src/pkg/task/dao/execution.go, src/pkg/task/dao/execution_test.go, src/pkg/task/hook.go, src/pkg/task/hook_test.go, src/pkg/task/mock_execution_dao_test.go, tests/apitests/python/test_log_rotation.py, tests/ci/api_common_install.sh
Refactor the logic for updating the status of execution when receiving the hook from jobservice, avoid the optimistic lock due to the multiple tasks update one execution by refreshing the status asynchronously. But still retain the old way by specifying the flag from ENV.
Fixes: #17584
Fixes #17584
=> refactor: refresh the execution status in async mode

src/pkg/task/dao/execution.go, src/pkg/task/dao/execution_test.go
Update the regexp of execution status outdate key to resolve the P2P_PREHEAT execution status not be refreshed.
Fixes #(issue)
=> [cherry-pick] fix: fix the regexp of execution status outdate key

src/pkg/task/dao/execution.go, src/pkg/task/dao/execution_test.go
Update the regexp of execution status outdate key to resolve the P2P_PREHEAT execution status not be refreshed.
Fixes #(issue)
=> fix: fix the regexp of execution status outdate key

src/jobservice/worker/cworker/reaper.go
Change the bitSize from 16 to 64 in the jobservice reaper, the 16 is too small when the redis cursor over the max value of int16.
Fixes: #18486
Fixes #18486
=> fix: fix error bitsize of jobservice reaper scan locks

tests/resources/Harbor-Pages/Project-Copy.robot, tests/resources/Harbor-Pages/Project-P2P-Preheat.robot, tests/resources/Harbor-Pages/Replication.robot, tests/resources/Harbor-Pages/Replication_Elements.robot, tests/robot-cases/Group1-Nightly/Common.robot
1. Update copy test case to add retries
2. Updata P2P Preheat test case to waiting
3. Update the Replication new rule button xpath
Fixes #(issue)
=> Update UI testcases

src/jobservice/worker/cworker/reaper.go
Change the bitSize from 16 to 64 in the jobservice reaper, the 16 is too small when the redis cursor over the max value of int16.
Fixes: #18486
Fixes #(issue)
=> [cherry-pick] fix: fix error bitsize of jobservice reaper scan locks

Makefile, make/photon/chartserver/Dockerfile.base, make/photon/clair-adapter/Dockerfile.base, make/photon/clair/Dockerfile.base, make/photon/core/Dockerfile.base, make/photon/db/Dockerfile, make/photon/db/Dockerfile.base, make/photon/db/docker-entrypoint.sh, make/photon/db/initdb.sh, make/photon/db/postgres.spec, make/photon/db/rpm_builder.sh, make/photon/db/upgrade.sh, make/photon/jobservice/Dockerfile.base, make/photon/log/Dockerfile.base, make/photon/nginx/Dockerfile.base, make/photon/notary-server/Dockerfile.base, make/photon/notary-signer/Dockerfile.base, make/photon/portal/Dockerfile.base, make/photon/prepare/Dockerfile.base, make/photon/prepare/utils/cert.py, make/photon/redis/Dockerfile.base, make/photon/redis/redis.conf, make/photon/registry/Dockerfile.base, make/photon/registryctl/Dockerfile.base
Bump up photon version to 4.0
Bump up redis version to 7.0
Bump up postgresql version to 13.10
Fixes #(issue)
=> Bump up photon version to 4.0 on release-1.10.0

src/pkg/task/dao/execution.go, src/pkg/task/sweep_manager.go
Delete the execution outdated status key in the redis when the execution is not found.
Fixes: #18511
Fixes #18511
=> [cherry-pick] fix: clean the redis if the execution is not found

src/pkg/task/hook.go
Update the stopped execution status immediately becasue the user experience is not good if wait long time when stop or reschedule a job.
Fixes: #18526
Fixes  #18526
=> fix: update stopped execution status immediately instead of async update

src/pkg/task/hook.go
Update the stopped execution status immediately becasue the user experience is not good if wait long time when stop or reschedule a job.
Fixes: #18526
Fixes #18526
=> [cherry-pick] fix: update stopped execution status immediately instead of async update

src/lib/trace/helper.go, src/lib/trace/helper_test.go, src/server/middleware/log/log.go, src/server/middleware/log/log_test.go
If the Trace ID is sent to the Harbor in HTTP header or the tracing is enabled (and the Trace ID is generated), the Trace ID will be added to the log lines as a new field.
Signed-off-by: Peter Gillich <pgillich@gmail.com>
Implements #18029
=> feat: log with trace ID

make/photon/prepare/utils/configs.py, make/photon/prepare/utils/registry.py
string and None type conversion
Fixes #(issue)
=> [cherry-pick]allow redis password safe special characters on release-2.7.0

CONTRIBUTING.md
The installation commands for Golint and FGT given in CONRTIBUTING.md were not working and were showing the following 
Errors. 
```
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see …
```
=> Fixed Golint & FGT installation commands in Project Setup Documentation

make/harbor.yml.tmpl
The link Github's rate limiting documentation in the template for harbor.yml file appear to be old and is redirected to root page of Github's rest api documentation.
The new link in this PR has been updated to point to the correct documentation.
=> fix: link to Github's rate limiting documentation.

src/portal/src/app/base/harbor-shell/harbor-shell.component.html, src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
1. Fixes #18601
Currently, the message prompts the mounted on the right page, if the users scroll the page to the bottom, the message will be covered.
Before:
After:
The message prompts are now fixed under the header, it is not scrollable with the page
Fixes #(issue)
=> Fix message prompt under the header

make/migrations/postgresql/0120_2.9.0_schema.up.sql, src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/pkg/task/dao/task.go, src/pkg/task/dao/task_test.go, src/pkg/task/mock_task_dao_test.go, src/pkg/task/mock_task_manager_test.go, src/pkg/task/task.go, src/pkg/task/task_test.go, src/testing/pkg/task/manager.go
1. Change the query for listing tasks of scan which can use the db index.
2. Add the gin index for task.extra_attrs.report_uuids
Fixes: #18013
The issue is that when the db has the large number of tasks(scan or other), the API of list artifacts will be quite slow when set the query parameter `with_scan_overview=true`, and also cost many db CPU resource. The root cause for the problem is that when querying scan reports, it is necessary to look up the scan tasks to obtain their status. However, the previous lookup method resulted in a full table scan of the database, which caused slow response times and increased resource utilization in cases with large amounts of data.
The data size of testing environment.
Artifacts: 100000+
Tasks: 500000+
Testing API: …
=> fix: improve the performance of list artifacts

make/photon/portal/Dockerfile
1. Use node script to convert swagger.yaml to swagger.json
Fixes #(issue)
=> Replace python script with node script for portal Dockerfile

make/migrations/postgresql/0101_2.7.3_schema.up.sql, make/migrations/postgresql/0111_2.8.1_schema.up.sql, src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/pkg/task/dao/task.go, src/pkg/task/dao/task_test.go, src/pkg/task/mock_task_dao_test.go, src/pkg/task/mock_task_manager_test.go, src/pkg/task/task.go, src/pkg/task/task_test.go, src/testing/pkg/task/manager.go
1. Change the query for listing tasks of scan which can use the db index.
2. Add the gin index for task.extra_attrs.report_uuids
Fixes: #18013
Fixes #(issue)
=> [cherry-pick] fix: improve the performance of list artifacts

.buildbaselog, Makefile, make/photon/portal/Dockerfile
1.Cherry-pick #18635
Fixes #(issue)
=> [Cherry-pick]Replace python script with node script for portal Dockerfile

api/v2.0/swagger.yaml
There are a `ß` char and some U+ff5c "｜" in the swagger.yaml. The character U+ff5c "｜" could be confused with the ASCII character U+007c "|".
Fixes #(issue)
=> fix: non-ASCII chars in swagger.yaml

make/migrations/postgresql/0120_2.9.0_schema.up.sql, src/controller/scan/base_controller.go, src/jobservice/job/known_jobs.go
1. Change the SCAN_ALL job execution retain counts from 5 to 1(per current design, only one report be stored for every artifact, so retain latest 1 is enough).
2. Enable the sweep for IMAGE_SCAN job(retain latest 1).
Fixes: #18633
Fixes #18633
=> fix: sweep executions of image scan job

make/photon/db/Dockerfile.base
=> Fix build db base image symlink error

make/migrations/postgresql/0101_2.7.3_schema.up.sql, src/core/main.go
Using code to patch the migration SQL instead of migration SQL file by go-migrate, the latter way will bring the potential upgrade issue, refer to code comments for more details.
Fixes #(issue)
=> fix: patch migration SQL by code

src/registryctl/api/registry/test/util.go, src/registryctl/main.go
Fix the channel that never receives a value.
Btw, Fix the code with the linter's recommendation by https://github.com/goharbor/harbor/blob/main/CONTRIBUTING.md#develop-build-and-test
Signed-off-by: iAklis <chenpinwei@gmail.com>
Fixes #(issue)
=> Fix the channel that never receives a value

tests/apitests/python/library/configurations.py, tests/apitests/python/test_p2p.py, tests/apitests/python/test_retain_image_last_pull_time.py, tests/robot-cases/Group0-BAT/API_DB.robot
=> [cherry-pick]Add Retain image last pull time API test case

tests/apitests/python/library/configurations.py, tests/apitests/python/test_p2p.py, tests/apitests/python/test_retain_image_last_pull_time.py, tests/robot-cases/Group0-BAT/API_DB.robot
=> Add Retain image last pull time API test case

src/jobservice/api/authenticator.go, src/registryctl/auth/secret.go
=> Use subtle.ConstantTimeCompare instead of compare directly

src/portal/src/app/base/account-settings/account-settings-modal.component.html, src/portal/src/app/base/account-settings/account-settings-modal.component.spec.ts, src/portal/src/app/base/account-settings/account-settings-modal.component.ts, src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.html, src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.spec.ts, src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.ts, src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts, src/portal/src/app/shared/components/navigator/navigator.component.ts, src/portal/src/app/shared/router-guard/auth-user-activate.service.ts, src/portal/src/app/shared/services/message-handler.service.ts
1. Fixes https://github.com/goharbor/harbor/issues/18694
2. Now non-system-admin users can also see the repo_read_only header
Fixes #(issue)
=> Improve repo_read_only header on the UI

make/photon/prepare/templates/nginx/nginx.https.conf.jinja, make/photon/prepare/templates/portal/nginx.conf.jinja
This PR enables `TLSv1.3` by default in the nginx configuration. This way the configuration follows the [linked recommendations](https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html#toc_0) and the [nginx default configuration](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_protocols).
Fixes #18358
=> Add support for TLSv1.3 in nginx configurations

src/controller/artifact/controller.go, src/controller/artifact/controller_test.go, src/controller/proxy/controller.go, src/controller/tag/controller.go, src/controller/tag/controller_test.go, src/testing/controller/tag/controller.go
fixes #18708
to set the pull time of tag for the first time cache the artifact.
Fixes #(issue)
=> set tag pull time for proxy cache

src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.html, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
1.Fixes #18692
UI change:
Fixes #(issue)
=> Add a text to explain the time window for GC

src/controller/proxy/controller.go, src/controller/proxy/controller_test.go, src/lib/errors/const.go, src/lib/http/error.go, src/pkg/registry/client.go, src/server/middleware/repoproxy/proxy.go
Add 429 too many request error in http error
Fixes #18707
Fixes #(issue)
=> Return error when proxy cache get too many request error(429)

src/lib/cache/cache.go, src/lib/cache/util.go
Fixes #(issue)
release-note/update
=> 【optimization】Use URL.Redacted method repleace redacted

src/controller/proxy/controller.go, src/controller/proxy/controller_test.go, src/lib/errors/const.go, src/lib/http/error.go, src/pkg/registry/client.go, src/server/middleware/repoproxy/proxy.go
Add 429 too many request error in http error
Fixes #18707
Fixes #(issue)
=> (cherry-pick) Return error when proxy cache get too many request error(429)

src/controller/event/handler/init.go, src/controller/event/handler/internal/artifact.go, src/controller/event/handler/internal/artifact_test.go
Cleanup the associated resources(scan executions and scan reports) after deletion of artifact.
Fixes: #18634
Fixes #18634
=> fix: clean up scan executions and reports after deleting artifact

src/controller/gc/callback.go, src/controller/gc/callback_test.go, src/jobservice/job/impl/gc/garbage_collection.go, src/jobservice/job/impl/gc/garbage_collection_test.go
Show more infors in the gc history, like the sweep size and how many blobs and manifests were removed by GC.
Fixes #(issue)
=> add more details in gc history

api/v2.0/swagger.yaml
type: boolean cannot be used with a format of int32
This for example hinders parsing of the api definition by other tools such as https://github.com/OpenAPITools/openapi-generator
=> Remove wrong format for boolean value in api definition

src/controller/quota/controller_test.go, src/pkg/quota/util.go, src/server/middleware/quota/post_initiate_blob_upload.go, src/server/middleware/quota/post_initiate_blob_upload_test.go
Create a zero-length resource when calling the `post /v2/library/ubuntu/blobs/uploads/` API to check if the quota is full.
Fixes https://github.com/goharbor/harbor/issues/17390
=> feat: Optimize quota checking when pushing images

tests/apitests/python/library/podman.py, tests/apitests/python/test_podman_pull_push.py, tests/apitests/python/test_referrers_api.py, tests/robot-cases/Group0-BAT/API_DB.robot, tests/test-engine-image/Dockerfile.api_test
=> Add podman pull & push testcase

src/portal/src/app/base/project/webhook/add-webhook-form/add-webhook-form.component.html, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
1.Fixes #18507
2.Remind the users of Slack's rate limits
Fixes #(issue)
=> Add a tooltip for slack notification

src/pkg/exporter/system_collector_test.go
add unit test for collector system info.
Fixes #(issue)
/label release-note/enhancement
=> 【UT】add unit test for collector system info

src/controller/quota/controller.go
Optimize the mechanism of quota refresh, return earlier to reduce the conflicts of optimistic lock. This is a follow-up fix to the https://github.com/goharbor/harbor/pull/17392.
Fixes #(issue)
=> fix: optimize the mechanism of quota refresh

src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html, src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.scss, src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
1. Related #18779
2. Show how many blobs and manifest have been deleted and how much space has been freed up
Fixes #(issue)
=> Add Details column for gc history

src/jobservice/job/impl/gc/garbage_collection.go, src/jobservice/job/impl/gc/util.go
Cherry pick to release 2.7 for #18662
Fixes #18381
=> [cherry-pick][2.7] fix: add retry on the caller of v2DeleteManifest instead within v2DeleteManifest

src/jobservice/job/impl/gc/garbage_collection.go, src/jobservice/job/impl/gc/util.go
Cherry pick to release 2.8 for #18662
Fixes #18381
=> [cherry-pick][2.8] fix: add retry on the caller of v2DeleteManifest instead within v2DeleteManifest

src/portal/src/app/base/left-side-nav/clearing-job/clearing-job-interfact.ts, src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.html, src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.scss, src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.ts, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
1. Related back-end PR #18855
Fixes #(issue)
=> Add worker parameter for GC

tests/resources/Harbor-Pages/Replication.robot, tests/resources/Harbor-Pages/Replication_Elements.robot, tests/robot-cases/Group1-Nightly/Replication.robot
=> [cherry-pick]Add replication by chunk testcase

tests/resources/Harbor-Pages/Replication.robot, tests/resources/Harbor-Pages/Replication_Elements.robot, tests/robot-cases/Group1-Nightly/Replication.robot
=> Add replication by chunk testcase

tests/resources/Harbor-Pages/Project-Webhooks.robot, tests/resources/Harbor-Pages/Project-Webhooks_Elements.robot, tests/resources/TestCaseBody.robot, tests/resources/Webhook-Util.robot, tests/robot-cases/Group1-Nightly/Webhook.robot
=> Add CloudEvents format webhook testcase

src/controller/robot/controller.go, src/controller/robot/controller_test.go, src/server/v2.0/handler/robot.go, src/server/v2.0/handler/user.go, src/server/v2.0/handler/user_test.go
Fixes #(issue)
Resolve task 5 in issue 18091
=> fix: add password/secret length check to be <= 128

tests/resources/Harbor-Pages/Configuration.robot, tests/resources/Harbor-Pages/Configuration_Elements.robot, tests/resources/TestCaseBody.robot, tests/robot-cases/Group1-Nightly/Trivy.robot
=> Add CVE Allowlist expires Test Cases

src/server/middleware/contenttrust/contentrust.go, src/server/middleware/contenttrust/contentrust_test.go, src/server/middleware/util/util.go, src/server/registry/route.go, tests/apitests/python/test_project_level_policy_content_trust.py, tests/robot-cases/Group1-Nightly/Common.robot
add notary v2 pull policy, when it enables, the artifact cannot be pull without the notation signature.
Fixes #(issue)
=> enable notary v2 policy checker

tests/apitests/python/test_proxy_cache.py
Fix APITEST_DB_PROXY_CACHE x509, Because cicd.harbor.vmwarecna uses a self-signed certificate.
Fixes #(issue)
=> Fix APITEST_DB_PROXY_CACHE x509

tests/apitests/python/test_proxy_cache.py
Fix APITEST_DB_PROXY_CACHE x509, Because cicd.harbor.vmwarecna uses a self-signed certificate.
Fixes #(issue)
=> [cherry-pick]Fix APITEST_DB_PROXY_CACHE x509

src/jobservice/job/impl/gc/garbage_collection.go, src/jobservice/job/impl/gc/util.go, src/jobservice/job/impl/gc/util_test.go
Refactor the clean redis logic in the GC job, replace the redigo client to the lib cache interface which can simplify operations.
Fixes #(issue)
=> refactor: replace the gc redigo client to the standard cache

make/harbor.yml.tmpl, make/photon/prepare/models.py, make/photon/prepare/templates/core/env.jinja, make/photon/prepare/utils/configs.py, src/controller/quota/controller.go
Add the related configurations for the quota update provider to the harbor.yml.
Fixes #(issue)
=> feat: add the configuration for quota update provider

src/pkg/securityhub/dao/security.go, src/pkg/securityhub/dao/security_test.go
Fix wrong scanned artifact count when there are multiple report for an artifact
Fixes #(issue)
=> Fix wrong scanned artifact count when there are multiple report for an artifact

src/server/middleware/contenttrust/contentrust.go, tests/apitests/python/test_project_level_policy_content_trust.py, tests/robot-cases/Group1-Nightly/Common.robot
Append the signer name to the error message which will be returned by the client
Fixes #(issue)
=> fix signer name

make/harbor.yml.tmpl, make/install.sh
Fixes https://github.com/goharbor/harbor/issues/19016
=> update installation hint

src/jobservice/main.go
fixes #19041
The issuse was introduced by https://github.com/goharbor/harbor/pull/17087. To move the import to main since the anonymous imports only allowed at main in go-cilint.
Fixes it:
To add the anonymous imports at the jobservice main since the gc job needs to remove accessory when to delete an artifact
Fixes #(issue)
=> fix accessory import issue

src/server/middleware/util/util.go
fixes #19043
Skip the policy checking when to pull the notation signature
Fixes #(issue)
=> fixes 19043

src/jobservice/main.go
fixes #19041
The issuse was introduced by https://github.com/goharbor/harbor/pull/17087. To move the import to main since the anonymous imports only allowed at main in go-cilint.
Fixes it:
To add the anonymous imports at the jobservice main since the gc job needs to remove accessory when to delete an artifact
Fixes #(issue)
=> [cherry-pick]fix accessory import issue

make/photon/core/Dockerfile.base, make/photon/db/Dockerfile.base, make/photon/exporter/Dockerfile.base, make/photon/jobservice/Dockerfile.base, make/photon/log/Dockerfile.base, make/photon/nginx/Dockerfile.base, make/photon/portal/Dockerfile.base, make/photon/prepare/Dockerfile.base, make/photon/redis/Dockerfile.base, make/photon/registry/Dockerfile.base, make/photon/registryctl/Dockerfile.base, make/photon/trivy-adapter/Dockerfile.base
=> Bump up photon version from 4.0 to 5.0

src/portal/src/app/services/routing-resolvers/artifact-detail-routing-resolver.service.ts, src/portal/src/app/services/routing-resolvers/project-routing-resolver.service.ts, src/portal/src/app/shared/router-guard/member-guard-activate.service.ts, src/portal/src/app/shared/services/project.service.ts
1. Fixes #19065
Fixes #(issue)
=> Remove cache for project policy updating

src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.html, src/portal/src/app/base/harbor-shell/app-level-alerts/app-level-alerts.component.scss, src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html, src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss
1.Fixes #19021
2.Fixes #19022
Fixes #(issue)
=> Update style for banner message ui

src/portal/src/app/base/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
Cherry-pick https://github.com/goharbor/harbor/pull/19080
Fixes #(issue)
=> [Cherry-pick]Convert the string "0" to number 0 

src/portal/src/app/base/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
1. Fixes #19046
Convert the string "0" to the number 0 for the tag retention rules
Fixes #(issue)
=> Convert the string "0" to number 0

src/pkg/reg/adapter/harbor/base/adapter.go
Quote the project name when listing projects in the replication, resolve the issue of pure number name of project.
Fixes https://github.com/goharbor/harbor/issues/19027
=> fix: fix replication list projects with pure numberic name

src/controller/securityhub/controller.go, src/controller/securityhub/controller_test.go, src/pkg/securityhub/dao/security.go, src/pkg/securityhub/dao/security_test.go, src/pkg/securityhub/manager.go, src/testing/pkg/securityhub/manager.go
Update sql to count artifact and scanned artifact
fixes #19009 #19020 #19013
Fixes #(issue)
=> Fix incorrect artifact and scanned artifact count issue

api/v2.0/swagger.yaml, src/pkg/securityhub/dao/security.go, src/pkg/securityhub/dao/security_test.go
=> Add artifact digest to query condition

make/migrations/postgresql/0120_2.9.0_schema.up.sql, src/pkg/securityhub/dao/security.go, src/pkg/securityhub/dao/security_test.go
Check it is referred by a scan_report
Add index to report_vulnerability_record to improve performance
Fixes #19014 #19028
Fixes #(issue)
=> Sort most dangerous vulnerabilities by score and severity level

src/controller/event/handler/internal/artifact.go, src/controller/event/handler/internal/artifact_test.go
Avoid to delete the scan reports in case the artifact deleted but still referenced by the other artifacts.
Fixes https://github.com/goharbor/harbor/issues/19105
=> fix: skip to delete scan reports if the digest still referenced

src/pkg/reg/adapter/harbor/base/adapter.go
Quote the project name when listing projects in the replication, resolve the issue of pure number name of project.
Fixes https://github.com/goharbor/harbor/issues/19027
=> [cherry-pick] fix: fix replication list projects with pure numberic name

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.ts, src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.interface.ts, src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts, src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html, src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts, src/portal/src/app/services/app-config.service.ts, src/portal/src/app/shared/components/app-level-alerts/app-level-alerts.component.html, src/portal/src/app/shared/components/app-level-alerts/app-level-alerts.component.ts
1. Add digest filter for vulnerability search, for #19023
2. Fixes #19104
Fixes #(issue)
=> Update ui to fix some issues

src/controller/quota/driver/project/project.go, src/controller/quota/driver/project/project_test.go, src/lib/quota_storage_limit.go, src/lib/quota_storage_limit_test.go, src/pkg/config/manager.go, src/pkg/quota/types/resources.go
=> fix: add storage_limit check

src/common/utils/utils.go, src/common/utils/utils_test.go, src/controller/p2p/preheat/controller.go, src/controller/p2p/preheat/controllor_test.go, src/controller/retention/controller.go, src/controller/retention/controller_test.go, src/pkg/p2p/preheat/models/policy/policy.go, src/pkg/p2p/preheat/models/policy/policy_test.go, src/pkg/retention/policy/models.go, src/pkg/retention/policy/models_test.go, src/server/v2.0/handler/gc.go, src/server/v2.0/handler/purge.go, src/server/v2.0/handler/scan_all.go
=> fix: cron string validation

src/cmd/exporter/main.go, src/core/session/session.go, src/lib/cache/redis/redis.go, src/pkg/notifier/notifier.go, src/server/registry/manifest.go
1. Change some logs level to reduce the noise.
2. Wrap the go-redis.Nil error as ErrNotFound to avoid confusing
Fixes #(issue)
=> log: change log level to reduce the noise logs

.github/workflows/CI.yml, .github/workflows/build-package.yml, .github/workflows/conformance_test.yml, CONTRIBUTING.md, Makefile, make/photon/chartserver/builder, make/photon/golang/Dockerfile, make/photon/registry/Dockerfile.binary, make/photon/trivy-adapter/Dockerfile.binary, make/photon/trivy-adapter/builder.sh, tests/ci/distro_installer.sh
=> bump go1.19.12 on release-2.7.0 base on ph4

make/harbor.yml.tmpl, make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja, make/photon/prepare/models.py
Update the incorrect otel timeout sample value in the harbor YAML configuration template.
Fixes https://github.com/goharbor/harbor/issues/19084
=> [cherry-pick] chore: fix incorrect otel timeout in harbor yaml template

make/harbor.yml.tmpl, make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja, make/photon/prepare/templates/core/env.jinja, make/photon/prepare/templates/jobservice/env.jinja, make/photon/prepare/utils/configs.py, src/core/main.go, src/jobservice/main.go, src/lib/cache/cache.go, src/pkg/cached/base_manager.go
Support to configure the customized redis db for cache layer and other misc business for core, by default the behavior is same with previous(stored in db 0).
Fixes https://github.com/goharbor/harbor/issues/19169
=> fix: support customize cache db for business

make/harbor.yml.tmpl, make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja, make/photon/prepare/models.py
Update the incorrect otel timeout sample value in the harbor YAML configuration template.
Fixes https://github.com/goharbor/harbor/issues/19084
=> chore: fix incorrect otel timeout in harbor yaml template

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
=> Update the max length for the filters

make/harbor.yml.tmpl, make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja, make/photon/prepare/templates/core/env.jinja, make/photon/prepare/templates/jobservice/env.jinja, make/photon/prepare/utils/configs.py, src/controller/quota/controller.go, src/core/main.go, src/jobservice/main.go, src/lib/cache/cache.go, src/lib/redis/client.go, src/lib/redis/client_test.go, src/pkg/cached/base_manager.go
Support to configure the customized redis db for cache layer and other misc business for core, by default the behavior is same with previous(stored in db 0).
Fixes https://github.com/goharbor/harbor/issues/19169
=> [cherry-pick] fix: support customize cache db for business

src/pkg/securityhub/dao/security.go
=> Wrong artifact scanned count

src/jobservice/job/impl/gc/garbage_collection.go
In the dry run mode, the accessories should be considered when try to simulate delete the subject manifest.
Fixes #(issue)
=> fix gc dry run issue

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html, src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
1. This tooltip explains the artifacts total count
Fixes #(issue)
=> Add a tooltip for the page title of security hub

src/server/registry/referrers.go
Fixes 
- https://github.com/goharbor/harbor/issues/19176
- https://github.com/goharbor/harbor/issues/19177
- https://github.com/goharbor/harbor/issues/19178
=> change Referrers Content-Type to application/vnd.oci.image.index.v1+json

src/lib/config/systemconfig.go
func GetRedisOfRegURL is not referenced.
Fixes #(issue)
=> Delete unused code

src/pkg/exporter/project_collector.go
Add an alias so that orm can parse the column name regardless of
the type and version of the database.
Fixes #(issue)
=> exporter: add field alias for count(*) func

.github/workflows/nightly-trivy-scan.yml
Update the image version for trivy scan as the main branch is now on `2.10-dev`
Fixes #(issue)
=> Update the image version for trivy scan

src/pkg/jobmonitor/redis.go, src/pkg/jobmonitor/redis_test.go
=> Remove job status track information from redis after stop

src/pkg/jobmonitor/redis.go, src/pkg/jobmonitor/redis_test.go
After stop in the queue:
Remove key in {harbor_job_service_namespace}:job_track:inprogress
Remove {harbor_job_service_namespace}:job_stats:<job_id>
fixes #19211
Fixes #(issue)
=> (cherry-pick) Remove job status track information from redis after stop the job in the queue

make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
Fixes https://github.com/goharbor/harbor/issues/19320
=> fix storage.redirect.disable migrate template error

src/lib/q/query.go, src/lib/q/query_test.go
Remove duplicated sort fields from order by clause
In MustClone() it will set Sorts field twice, that will generate two duplicated order by fields in the generated SQL.
For example, in the project list API, the SQL will be(formated):
```
[ORM]2023/09/12 19:26:16  -[Queries/default] - [  OK /    db.Query /     7.1ms] -
[SELECT T0.`project_id`, T0.`owner_id`, T0.`name`,
T0.`creation_time`, T0.`update_time`, T0.`deleted`, 
T0.`registry_id` 
FROM `project` T0 
WHERE T0.`deleted` = ? 
ORDER BY T0.`name` ASC, T0.`name` ASC 
LIMIT 50] - `false`
```
Fixes #(issue)
=> Remove duplicated sort fields from order by clause

src/controller/artifact/annotation/v1alpha1_test.go, src/controller/artifact/processor/default.go, src/controller/artifact/processor/default_test.go, src/server/middleware/subject/subject.go
Fixes https://github.com/goharbor/harbor/issues/19175
=> update default processor for unknwon type config

src/pkg/accessory/dao/dao.go, src/pkg/accessory/dao/dao_test.go, src/pkg/accessory/manager.go, src/pkg/accessory/manager_test.go, src/server/middleware/subject/subject.go, src/server/middleware/subject/subject_test.go, src/testing/pkg/accessory/dao/dao.go, src/testing/pkg/accessory/manager.go
In certain cases, the OCI client may push the subject artifact and accessory in either order. Therefore, it is necessary to handle situations where the client pushes the accessory ahead of the subject artifact.
Fixes https://github.com/goharbor/harbor/issues/19345
=> support accessory in either order

CONTRIBUTING.md
I was searching for documentation on how to build the project and skimmed this but missed the link to the website since it's under the 'fork repository' heading.
N/A
=> Add heading to contributing docs

src/pkg/securityhub/dao/security.go
=> Change fixed_version to package_version in query dangerous CVE sql

tests/resources/Harbor-Pages/Project.robot, tests/resources/Harbor-Pages/SecurityHub.robot, tests/resources/Harbor-Pages/SecurityHub_Elements.robot, tests/resources/Util.robot, tests/robot-cases/Group0-Util/docker_push_manifest_list.sh, tests/robot-cases/Group1-Nightly/Trivy.robot
=> Add security hub UI test case

src/pkg/jobmonitor/redis.go, src/pkg/jobmonitor/redis_test.go
=> [cherry-pick] Use batch to list the job id in the job queue to avoid crash redis

src/pkg/jobmonitor/redis.go, src/pkg/jobmonitor/redis_test.go
=> Use batch to list the job id in the job queue to avoid crash redis

tests/apitests/python/test_garbage_collection.py
=> [cherry-pick]Add GC accessory API test case

src/controller/event/handler/webhook/artifact/replication.go, src/controller/event/model/event.go, src/controller/replication/execution.go, src/controller/replication/execution_test.go, src/controller/replication/flow/copy.go, src/controller/replication/flow/deletion.go, src/controller/replication/flow/stage.go, src/controller/replication/model.go
Add the new filed 'references' to the replication webhook payload, which can help user better know the replicated artifact tags or digests. (references is the lists of the artifact tag name or digest if no tag)
Fixes https://github.com/goharbor/harbor/issues/19035
=> feat: enhance the replication webhook payload

tests/apitests/python/test_garbage_collection.py, tests/resources/Cosign_Util.robot, tests/resources/Harbor-Pages/GC.robot, tests/resources/Harbor-Pages/Project-Artifact-Elements.robot, tests/resources/Harbor-Pages/Project-Artifact.robot, tests/resources/TestCaseBody.robot, tests/robot-cases/Group1-Nightly/Common_GC.robot
=> Add GC accessory UI test case

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html, src/portal/src/app/shared/components/label/label-piece/label-piece.component.html, src/portal/src/app/shared/components/label/label-piece/label-piece.component.ts
Adds a tooltip showing the label's description on artifact-list-page. I believe it is not relevant to show it anywhere else (and from what I've tried it often result in broken UI).
Please find a video of how it looks: https://github.com/goharbor/harbor/assets/48765390/54669aaa-6324-4669-9967-80727fb49e64
Note that I'm a complete noob with Frontend/JS/Angular, therefore please let me know if you believe there is a more elegant way to do this.
=> Add label's description as tooltip

src/controller/event/handler/init.go, src/controller/event/handler/internal/artifact.go, src/controller/event/handler/internal/artifact_test.go, src/controller/event/handler/internal/project.go, src/controller/event/handler/internal/project_test.go, src/controller/immutable/controller.go, src/controller/retention/controller.go, src/pkg/retention/dao/retention.go, src/pkg/retention/dao/retention_test.go, src/pkg/retention/launcher_test.go, src/pkg/retention/manager.go, src/testing/controller/retention/controller.go
=> Delete tag retention rule and tag immutable rule when deleting project

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/security-hub.component.scss, src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss, src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.scss, src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.scss, src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/scanning.scss
Changed the label token foreground and background to comply with WCAG AA (or AAA when possible).
Before: 
After:
Using https://webaim.org/resources/contrastchecker/ as a testing tool, only `label-medium` was OK for WCAG AA for normal content.
No existing issue (I preferred to file a PR first). This could relate to #12327
I don't have any Sass skill so far and tried to apply a homogeneous patch where such labels were duplicated. Please let me know if I missed something.
`result-tip-histogram.component.scss` didn't have any issue, but I preferred to match the colors changed elsewhere.
=> fix: Accessibility - change color for WCAG AA

src/portal/package.json, src/portal/src/app/shared/components/new-user-form/new-user-form.component.html
1. Not allow comma for the user name when creating a user
Fixes #(issue)
=> Not allow comma for the user name

tests/apitests/python/library/configurations.py, tests/apitests/python/test_banner_message.py, tests/robot-cases/Group0-BAT/API_DB.robot
=> [cherry-pick]Add banner message API test case

tests/apitests/python/library/configurations.py, tests/apitests/python/test_banner_message.py, tests/robot-cases/Group0-BAT/API_DB.robot
=> Add banner message API test case

src/common/const.go, src/common/utils/utils.go, src/core/controllers/oidc.go, src/pkg/user/manager.go, src/pkg/user/manager_test.go, src/server/v2.0/handler/user.go, src/server/v2.0/handler/user_test.go
Check username when creating user by API
Replace comma with underscore in username for OnboardUser
Fixes #19356
Fixes #(issue)
=> Replace comma in username to avoid casbin issue

tests/coverage4gotest.sh
There's a path change introduced by #19508 which may impact showing the coverage on codecov.
This commit makes sure the profile.cov is referenced as absolute path in `coverage4gotest.sh`
Fixes #(issue)
=> Use absolute path for the profile.cov

src/server/v2.0/handler/user.go, src/server/v2.0/handler/user_test.go
=> Skip to validate username when update user profile

src/controller/event/handler/internal/project.go, src/controller/event/handler/internal/project_test.go, src/pkg/member/dao/dao.go, src/pkg/member/dao/dao_test.go, src/pkg/member/manager.go, src/testing/pkg/member/fake_member_manager.go
=> Delete project member when delete project

src/controller/retention/controller.go, src/controller/retention/controller_test.go
Enhance the API for triggering retention by optimizing it from synchronous to asynchronous to solve the problem of slow response in the case of a large number of tasks.
Fixes https://github.com/goharbor/harbor/issues/18504
=> perf: optimize the trigger retention API

src/core/middlewares/middlewares.go
=> [cherry-pick] Allow POST method to request service/token in readonly mode

src/portal/src/app/shared/components/label/label-piece/label-piece.component.html, src/portal/src/css/common.scss
Added css to see full label on hover
Fixes #19559 
Closes #19559 
=> 19559 cannot see full label easily

api/v2.0/swagger.yaml, src/lib/q/builder.go, src/lib/q/builder_test.go, src/pkg/quota/dao/dao_test.go, src/pkg/quota/dao/util.go, src/pkg/quota/dao/util_test.go
=> fix: sorting quota

api/v2.0/swagger.yaml, src/controller/systeminfo/controller.go, src/controller/systeminfo/controller_test.go, src/server/v2.0/handler/systeminfo.go
=> Add oidc provider name to systeminfo API

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html, src/portal/src/app/shared/components/label-selector/label-selector.component.html, src/portal/src/app/shared/components/label-selector/label-selector.component.ts
1. Fixes #19554
Fixes #(issue)
=> Avoid menu closure when filtering labels

src/portal/PACKAGE.md, src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.ts
1.Correct loop condition for replication tasks page
Fixes #(issue)
=> Correct loop condition for replication tasks

src/controller/securityhub/controller.go, src/pkg/scan/scanner/manager.go, src/server/v2.0/handler/security.go
=> Return empty result when no scanner configured

src/common/rbac/const.go, src/server/v2.0/handler/robot.go, src/server/v2.0/handler/robot_test.go, tests/apitests/python/library/robot.py, tests/apitests/python/test_robot_account.py
It is not allowed to create an new robot with the access outside the predefined scope.
Fixes #(issue)
=> add permission validation for robot creating and updating.

tests/apitests/python/test_permission.py
Add scan,volumes,jobservice,scanner,label,securityhub,catalog permission testcases
Fixes #(issue)
=> Add API(scan,volumes,jobservice,scanner,label,securityhub,catalog) permission testcases

src/server/v2.0/handler/label.go
Make sure robot can use rbac.Resource(label) to access system level label
Fixes #(issue)
=> fix system label resource

tests/apitests/python/library/user.py, tests/apitests/python/test_user_crud.py, tests/robot-cases/Group0-BAT/API_DB.robot
=> Add user API test case

api/v2.0/swagger.yaml
This is a one line change to the swagger.yaml file in order to update the description of the repositoryName parameter. As described in the linked issue, the forward slashes in the repo name parameter need to be double encoded. 
Fixes #19635
=> [release-note/docs] swagger.yaml "repositoryName" parameter description update

src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html, src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.ts, src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html, src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.ts
1. Fixes #19612
Fixes #(issue)
=> Update the name checking for the robot account

src/server/middleware/subject/subject.go
Fix the keywords when to list accessories belong to the subject manifest.
Fixes #(issue)
=> fix the landing accessory data

src/common/const.go, src/core/main.go, src/lib/config/metadata/metadatalist.go, src/lib/config/systemconfig.go
1. Increase the default beego max memory and upload size from 32GB to 128GB.
2. Support customize the two beego configs from env.
(cherry picked from commit 553c85eed04aea65db3336be45a628ce022148fb)
Fixes #(issue)
=> [cherry-pick] fix: increase beego max memory and upload size (#19578)

src/server/v2.0/handler/project_metadata.go
=> Fix project metadata validate bug

tests/robot-cases/Group1-Nightly/Replication.robot
=> [cherry-pick]Add notation replication test case

tests/robot-cases/Group1-Nightly/Replication.robot
=> [cherry-pick]Add multi-tier accessory replication test cases

README.md, make/common.sh
=> Fix docker version to 20.10.10

src/portal/src/app/base/project/scanner/scanner.component.html
=> update project-SelectScanner modal Default field css

make/photon/db/Dockerfile, make/photon/db/Dockerfile.base
=> Bump up PostgreSQL from 14 to 15

tests/apitests/python/test_system_permission.py, tests/resources/Harbor-Pages/Project_Robot_Account.robot, tests/robot-cases/Group1-Nightly/Common.robot
=> Add quota permissions testcase

src/controller/proxy/controller.go, src/controller/proxy/controller_test.go, src/controller/proxy/manifestcache.go
=> [cherry-pick] Cache image list with digest key

api/v2.0/swagger.yaml, src/controller/robot/controller.go, src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/server/v2.0/handler/model/robot.go, src/server/v2.0/handler/robot.go, src/server/v2.0/handler/robot_test.go
=> Add verification that robot account duration is not 0

src/common/rbac/project/rbac_role.go
Fixes #19709
Related to PR  https://github.com/goharbor/harbor/pull/19757
=> [Cherry pick] add repository read permission to limitedGuest

src/controller/artifact/controller.go, src/controller/artifact/controller_test.go
https://github.com/goharbor/harbor/blob/main/src/controller/artifact/controller.go#L230
conflict error will always be overwritten here if GetByDigest returns an error, making it hard to debug the conflict error. This change logs the conflict error before it gets overwritten
Fixes #19293
- [v] Well Written Title and Summary of the PR
- [v] Accepted the DCO. Commits without the DCO will delay acceptance.
=> Log ensureArtifact ConflictErr

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss, src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
=> fix label select bugs

src/go.mod, src/go.sum, src/jobservice/job/impl/replication/replication.go, src/pkg/reg/adapter/volcenginecr/adapter.go, src/pkg/reg/adapter/volcenginecr/adapter_test.go, src/pkg/reg/adapter/volcenginecr/artifact_registry.go, src/pkg/reg/adapter/volcenginecr/artifact_registry_test.go, src/pkg/reg/adapter/volcenginecr/auth.go, src/pkg/reg/adapter/volcenginecr/auth_test.go, src/pkg/reg/adapter/volcenginecr/consts.go, src/pkg/reg/adapter/volcenginecr/helper.go, src/pkg/reg/adapter/volcenginecr/helper_test.go, src/pkg/reg/adapter/volcenginecr/volccr.go, src/pkg/reg/adapter/volcenginecr/volccr_test.go, src/pkg/reg/manager.go, src/pkg/reg/model/registry.go, src/portal/src/app/shared/services/endpoint.service.ts
- Add new adapter for volcEngine registry:(https://www.volcengine.com/)
- support both pull-based and push-based
Fixes #(issue)
=> feat: volc cr adapter

src/core/middlewares/middlewares.go
Habor doesnot support POST /service/token endpoint, put this request into a transaction will consume
extra database resources and generate many logs.
Logs in core and nginx:
```
2023-09-12T10:59:47+08:00 [DEBUG] [/antregistry/src/server/middleware/log/log.go:30]: attach request id aaa37a96-ec65-40f8-821d-6267e8d5f5a6 to the logger for the request POST /service/token
[ORM]2023/09/12 10:59:47  -[Queries/default] - [  OK /  db.BeginTx /     4.3ms] - [START TRANSACTION]
2023-09-12T10:59:47+08:00 [DEBUG] [/antregistry/src/server/middleware/artifactinfo/artifact_info.go:55]: In artifact info middleware, url: /service/token
2023-09-12T10:59:47+08:00 [DEBUG] [/antregistry/src/server/middleware/security/unauthorized.go:28][requestID="aaa37a96-ec65-40f8-821d-626 …
```
=> skip transaction for POST /service/token

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss, src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
=> [cherry-pick]fix label select bugs (#19850)

src/lib/config/userconfig.go, src/pkg/accessory/dao/dao.go, src/pkg/accessory/dao/dao_test.go, src/pkg/accessory/manager.go, src/pkg/accessory/manager_test.go, src/server/middleware/subject/subject.go, src/server/middleware/subject/subject_test.go, src/testing/pkg/accessory/dao/dao.go, src/testing/pkg/accessory/manager.go
=> [cherry-pick] ] support accessory in either order

tests/resources/Harbor-Pages/Project.robot, tests/resources/Harbor-Pages/SecurityHub.robot, tests/resources/Harbor-Pages/SecurityHub_Elements.robot
=> fix: cve export label filter xpath

tests/resources/Harbor-Pages/Administration-Project-Quotas.robot, tests/resources/Harbor-Pages/Administration-Project-Quotas_Elements.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common_GC.robot
=> add UI test for project quota sorting

make/harbor.yml.tmpl, make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja, make/photon/prepare/templates/nginx/nginx.https.conf.jinja, make/photon/prepare/templates/portal/nginx.conf.jinja, make/photon/prepare/utils/configs.py, make/photon/prepare/utils/nginx.py, make/photon/prepare/utils/portal.py
https://github.com/goharbor/harbor/issues/19932
=> add ip_family config in harbor.yml on release-2.9.0

make/harbor.yml.tmpl, make/photon/prepare/migrations/version_2_10_0/harbor.yml.jinja, make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja, make/photon/prepare/templates/nginx/nginx.https.conf.jinja, make/photon/prepare/templates/portal/nginx.conf.jinja, make/photon/prepare/utils/configs.py, make/photon/prepare/utils/nginx.py, make/photon/prepare/utils/portal.py
https://github.com/goharbor/harbor/issues/19932
=> add ip_family config in harbor.yml

tests/resources/Harbor-Pages/Project.robot, tests/resources/Harbor-Pages/SecurityHub.robot, tests/resources/Harbor-Pages/SecurityHub_Elements.robot
=> [Cherry-pick] fix: cve export label filter xpath (#19931)

src/common/utils/utils.go, src/common/utils/utils_test.go, src/core/controllers/oidc.go
=> Limit url to local path

src/server/registry/referrers.go, src/server/registry/referrers_test.go
Update the referrers API according to the changeset in distribution spec 1.1, available at https://github.com/opencontainers/distribution-spec/pull/491/files.
https://github.com/goharbor/harbor/issues/20014
=> update referrers api

tools/migrate_chart/Dockerfile, tools/migrate_chart/migrate_chart.py, tools/migrate_chart/test_migrate_chart.py
The previous migration tool overwrites existing OCI artifacts with the same name and same tag 
Fixes #(issue)
=> Update migration tools

make/harbor.yml.tmpl
fix typos in make/harbor.yml.tmpl
Fixes #(issue)
=> fix: typos

api/v2.0/swagger.yaml
https://github.com/goharbor/harbor/discussions/20093
https://github.com/goharbor/harbor/commit/738fde7d3bd8f201711907a826630b3fe5d13e16
I wasn't sure if this was auto-generated. I didn't see the swagger comments on any where else except in the yaml. I added the url itself, so hopefully that is always the most recent.
=> Update swagger.yaml bad request permission: helm-chart:read

src/controller/replication/execution.go, src/controller/replication/execution_test.go, src/controller/retention/controller.go, src/controller/systemartifact/execution.go, src/controller/systemartifact/execution_test.go, src/pkg/task/dao/task.go, src/pkg/task/dao/task_test.go, src/pkg/task/execution.go, src/testing/pkg/task/execution_manager.go
=> [cherry-pick] panic due to mark retention task error

src/controller/event/handler/webhook/artifact/replication.go, src/controller/event/handler/webhook/artifact/replication_test.go
It also could be 'library/bitnami/fluentd:1.13.3-debian-10-r0' so we need to split resource to only 2 parts - possible namespace and image name which may include slashes for example - namespace: library, image: bitnami/fluentd:1.13.3-debian-10-r0
Fixes #(issue)
=> fix image name extraction

.github/workflows/CI.yml, .github/workflows/build-package.yml, .github/workflows/conformance_test.yml, CONTRIBUTING.md, Makefile, make/photon/registry/Dockerfile.binary, make/photon/trivy-adapter/Dockerfile.binary, make/photon/trivy-adapter/builder.sh, tests/ci/distro_installer.sh
=> bump golang 1.21.8 on main

src/common/utils/utils.go, src/common/utils/utils_test.go
=> [cherry-pick] Allow empty path in redirect_url

src/common/utils/utils.go, src/common/utils/utils_test.go
Fix for redirect to other sites with OIDC login and empty redirect_url parameter see  #20226
Fixes #20226
=> Allow empty path in redirect_url

src/controller/artifact/annotation/v1alpha1.go
close blob io ReadCloser
Fixes #(issue)
=> fix: close blob io ReadCloser

make/harbor.yml.tmpl
Fixes https://github.com/goharbor/harbor/issues/20219
=> feat: expose `trivy.timeout` to configure the duration to wait for scan completion

src/cmd/migrate-patch/main.go, src/core/main.go
his is just a small optimization of the convention of using channels as end signal notifications.
The end signal is usually sent by closing the channel
Fixes #(issue)
=> Sending signals by closing the channel

src/controller/event/topic.go
=> fix: update the image reference format for audit log when pulling image

api/v2.0/swagger.yaml, src/common/rbac/const.go, src/common/rbac/project/rbac_role.go, src/controller/artifact/controller.go, src/controller/artifact/processor/sbom/sbom.go, src/controller/artifact/processor/sbom/sbom_test.go, src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/controller/scanner/base_controller.go, src/core/main.go, src/jobservice/main.go, src/pkg/scan/dao/scanner/model.go, src/pkg/scan/handler.go, src/pkg/scan/job.go, src/pkg/scan/job_test.go, src/pkg/scan/rest/v1/client.go, src/pkg/scan/rest/v1/client_test.go, src/pkg/scan/rest/v1/models.go, src/pkg/scan/sbom/model/summary.go, src/pkg/scan/sbom/sbom.go, src/pkg/scan/sbom/sbom_test.go, src/pkg/scan/vulnerability/vul.go, src/pkg/scan/vulnerability/vul_test.go, src/server/v2.0/handler/model/scanner.go, src/server/v2.0/handler/project.go, src/server/v2.0/handler/project_test.go, src/server/v2.0/handler/scan.go, src/testing/pkg/scan/rest/v1/client.go
=> Add generate SBOM feature

src/server/middleware/repoproxy/proxy.go, src/server/middleware/repoproxy/proxy_test.go
=> Allow generate sbom in proxy cache project

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
The scan stop button will be disabled forever once it got clicked no matter the action is failed or successful.
Fixes #20303
=> Fixed an issue where the scan stop button can only be clicked once

src/pkg/scan/rest/v1/models.go, src/pkg/scan/rest/v1/models_test.go
=> Set default capability for old scanners

src/controller/scanner/base_controller.go, src/controller/scanner/controller.go, src/server/v2.0/handler/project.go, src/server/v2.0/handler/project_test.go, src/testing/controller/scanner/controller.go
=> Log and skip adapter ping error when retrieve adapter capability

api/v2.0/swagger.yaml, src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/pkg/scan/sbom/model/summary.go, src/pkg/scan/sbom/sbom.go, src/server/v2.0/handler/assembler/report.go
Add scan_status and report_id when scan has a failed task
Fixes #(issue)
=> Add scanner info and report_id to sbom_overview on listing artifact

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/scanning.scss
After the job of generating SBOM is done, the sbom overview status is not updated to the proper artifact item in the grid.
This PR update the latest sbom_overview and sbom_digest to the proper artifact.
Fixes #20320
=> Fix UI sbom status not updated to grid item after job done

src/controller/event/handler/webhook/scan/scan.go, src/controller/event/metadata/scan.go, src/controller/event/model/event.go, src/controller/event/topic.go, src/controller/scan/callback.go, src/pkg/notifier/model/event.go
=> Add scan type in webhook event

src/pkg/scan/job.go
https://github.com/goharbor/harbor/issues/20411
```
2024-05-10T08:31:05Z [DEBUG] [/pkg/scan/job.go:407]: scanRequest:
2024-05-10T08:31:05Z [INFO] [/pkg/scan/job.go:418]: {
"registry": {
"url": "http://core:8080",
"authorization": "[HIDDEN]"
},
"artifact": {
"namespace_id": 1,
"repository": "library/goharbor/spectral",
"tag": "test",
"digest": "sha256:501c46137740b45171a91707f1009817beb3aac21b65a4e2271734d3d86c4940",
"mime_type": "application/vnd.docker.distribution.manifest.v2+json",
"size": 321311585
},
"enabled_capabilities": [
{
"type": "sbom",
"produces_mime_types": [
"application/vnd.security.sbom.report+json; version=1.0"
],
"parameters": {
"sbom_media_types": [
"application/spdx+json"
]
}
}
]
}
```
=> Update scan job request log for enabled_capabilities

src/pkg/scan/rest/v1/models.go, src/pkg/scan/sbom/sbom.go, src/pkg/scan/sbom/sbom_test.go, src/pkg/scan/util.go
fixes #20407
It needs to specify the insecure option on parsing the reference
Fixes #(issue)
=> fix issue 20407

src/controller/artifact/controller.go, src/controller/artifact/controller_test.go, src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/controller/scan/checker.go, src/controller/scan/checker_test.go, src/testing/controller/artifact/controller.go
=> Skip scan in-toto sbom artifact

src/server/v2.0/handler/assembler/report.go
=> Initialize execution Manager in Report Assembler

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan-component.html, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.spec.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.ts, src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-bar-chart.component.ts, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/ko-kr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
Fix and Should to display Unsupported if no SBOM accessories found
Fixes #20346
=> Fix and Should to display Unsupported if no SBOM accessories found

src/portal/package-lock.json, src/portal/package.json, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
fix ui test failure
Fixes #20440
=> fix ui test failure

src/portal/package-lock.json, src/portal/package.json, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
fix ui test failure
Fixes #20440
=> Cherry-pick 20441-fix ui test failure

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.scss, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.ts
Fix Wrong sbom status displayed in UI
Fixes #20459
=> Fix-20459 Wrong sbom status displayed in UI

src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-sbom/artifact-sbom.component.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
fix sbom status and download issue
Fixes #20469
=> Fix - 20469  sbom status and download issue

src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/jobservice/job/known_jobs.go, src/pkg/scan/handler.go, src/pkg/scan/sbom/sbom.go, src/pkg/scan/vulnerability/vul.go, src/testing/pkg/scan/handler.go
Add vendor type SBOM for execution
fixes #20495
Fixes #(issue)
=> [cherry-pick] Separate the execution vendor type sbom from image_scan

src/pkg/scan/sbom/sbom.go, src/pkg/scan/sbom/sbom_test.go
fixes #20496
Harbor will reserve one SBOM accessory artifact for each subject artifact. Ensure all existing SBOMs are removed before generating the next set.
Fixes #(issue)
=> [cherry-pick] fix 20496

src/pkg/scan/sbom/sbom.go
fixes #20518
Since there is no report for the replicated artifact, update to use the artifact id to remove accessories.
Fixes #(issue)
=> [cherry-pick] fix 20518

src/pkg/scan/sbom/sbom.go, src/pkg/scan/sbom/sbom_test.go, src/pkg/task/mock_task_manager_test.go, src/pkg/task/task.go, src/testing/pkg/task/manager.go
=> Response an error message when there is incomplete sbom generate job

src/server/v2.0/handler/assembler/report.go, src/server/v2.0/handler/assembler/report_test.go
=> No sbom_overview when sbom is deleted

src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-additions.component.ts, src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
Hide SBOM tab  when the artifact is  helm package
Fixes #20537
=> Fixes-20537 SBOM tab should not exist when the artifact is  helm package

src/pkg/artifactrash/dao/dao.go
Delete duplicate error check section in the artifacttrash dao Flush method.
Fixes #(issue)
=> style: delete duplicate error check in artifacttrash dao

src/pkg/scan/sbom/sbom.go, src/pkg/scan/sbom/sbom_test.go
=> [cherry-pick] Use internal registry url to push artifact accessory

.github/workflows/CI.yml, src/pkg/scan/sbom/sbom.go, src/pkg/scan/sbom/sbom_test.go
=> Use internal registry url to push artifact accessory

src/controller/proxy/controller.go
Previous impl it calls c.local.DeleteManifest(remoteRepo, art.Tag), because the remoteRepo is incorrect repository and it always delete nothing, to keep consistency with the previous version and code clarity, remove this go routine
fixes #20596 
Fixes #(issue)
=> Remove the delete local manifest when remote doesn't exist

src/pkg/task/sweep_manager.go
Resolve the execution deletion conflict when there are tasks still referenced by the execution, remained execs can wait for next sweep cycle.
Fixes 
- https://github.com/goharbor/harbor/issues/20593
- https://github.com/goharbor/harbor/issues/19494
=> fix: update the execution sweep sql to resolve the exec deletion conflict

src/controller/task/sweep.go
Reduce the execution sweep job frequency from hourly to daily.
Fixes https://github.com/goharbor/harbor/issues/20255
=> fix: reduce the execution sweep job frequency from hourly to daily

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
Hide the scan related button when installation without scanner.
Fixes https://github.com/goharbor/harbor/issues/20615
=> fix: hide the scan related button when installation without scanner

.github/workflows/CI.yml, src/portal/src/i18n/lang/zh-cn-lang.json
add  sbom translation for zh_CN
Fixes #(issue)
=> [cherry-pick] Add translation for zh_CN

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.service.ts, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
disable the scan related button when installation without scanner or scanner deactived.
Fixes https://github.com/goharbor/harbor/issues/20643
=> fix: disable the scan related button when installation without scanner or scanner deactived

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.service.ts, src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
Disable the scan related button when installation without scanner or scanner deactived.
Fixes #(issue)
=> [cherry-pick] fix: disable the scan related button when installation without scanner or scanner deactived

src/controller/artifact/model.go, src/pkg/scan/job.go
fixes #20573
remove s from additions/sboms in the link
Fixes #(issue)
=> Change the log message when PostScan failed.

src/controller/artifact/model.go, src/pkg/scan/job.go
fixes #20573
remove s from additions/sboms in the link
Fixes #(issue)
=> [cherry-pick] Change the log message when PostScan failed.

.github/workflows/publish_release.yml
which will be failed to run the publish release github action job regarding publishImages
Fixes #(issue)
=> [cherry-pick] fix: add quote to dockerhub cred in case it contains specical characters

api/v2.0/swagger.yaml, src/controller/artifact/controller.go, src/controller/artifact/controller_test.go, src/controller/artifact/model.go, src/pkg/artifact/dao/dao.go, src/pkg/artifact/dao/dao_test.go, src/pkg/artifact/manager.go, src/pkg/artifact/manager_test.go, src/pkg/cached/artifact/redis/manager.go, src/server/v2.0/handler/artifact.go, src/server/v2.0/handler/model/artifact.go, src/server/v2.0/handler/project.go, src/testing/controller/artifact/controller.go, src/testing/pkg/artifact/manager.go
=> [cherry-pick ]Release 2.11.0 cp 20803

api/v2.0/swagger.yaml, src/controller/proxy/controller.go, src/controller/proxy/options.go, src/controller/proxy/options_test.go, src/controller/proxy/remote.go, src/controller/replication/transfer/image/transfer.go, src/lib/iothrottler.go, src/pkg/project/models/pro_meta.go, src/pkg/project/models/project.go, src/server/middleware/repoproxy/proxy.go, src/server/middleware/repoproxy/tag.go, src/server/v2.0/handler/project.go, src/server/v2.0/handler/project_metadata.go
Fixes #20589
test case 1: proxy_speed_kb = "-1"
```
"metadata": {
"proxy_speed_kb": "-1",
"public": "false",
"retention_id": "1"
},
"name": "proxy1-unlimited1",
```
test case 2: proxy_speed_kb = "100"
```
"metadata": {
"proxy_speed_kb": "100",
"public": "false",
"retention_id": "2"
},
"name": "proxy2-limited-100kb",
```
100 is in kilo bit per second, 100/8 = 12.5 kilo bytes per second
test case 3: proxy_speed_kb = "300"
```
"metadata": {
"proxy_speed_kb": "300",
"public": "false",
"retention_id": "3"
},
"name": "proxy3-limited-300kb",
```
300 is in kilo bit per second, 300/8 = 37.5 kilo bytes per second
test case 4: proxy_speed_kb = "1024"
```
"metadata": {
"proxy_speed_kb": "1024",
"public": "false", …
```
=> feat: implement bandwidth limit for proxy-cache

api/v2.0/swagger.yaml, make/photon/prepare/templates/nginx/nginx.http.conf.jinja, src/common/const.go, src/core/auth/ldap/ldap.go, src/lib/config/metadata/metadatalist.go, src/lib/config/models/model.go, src/lib/config/userconfig.go, src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html, src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.ts, src/portal/src/app/base/left-side-nav/config/config.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Add configure LDAP group attach parallel UI
Change the /c/login timeout from 60 (nginx default) to 900 seconds in nginx.conf
Fixes #(issue)
=> Parallel attach ldap group

src/controller/artifact/controller.go
=> [cherry-pick] Check create when fire the artifact event

src/jobservice/job/impl/gc/garbage_collection.go
=> fix: fix the GC job index data race

tests/test-engine-image/Dockerfile.common, tests/test-engine-image/Dockerfile.ui_test
1. bump up CONTAINERD_VERSION to 1.7.20
2. bump up docker compose version to v2.29.1
3. bump up HELM_VERSION to 3.15.3
4. bump up ORAS_VERSION to 1.2.0 
5. bump up IMGPKG_VERSION to 0.43.0
6. bump up COSIGN_VERSION to 2.4.0
7. bump up NOTATION_VERSION to 1.1.1
8. bump up DOCKER_VERSION to 27.1.1
9. Upgrade chromedriver version to 127.0.6533.99
Fixes #20613
=> fix: update e2e test engine images

api/v2.0/swagger.yaml, make/migrations/postgresql/0150_2.12.0_schema.up.sql, src/controller/robot/controller.go, src/controller/robot/controller_test.go, src/controller/scan/base_controller.go, src/controller/scan/base_controller_test.go, src/pkg/robot/dao/dao_test.go, src/pkg/robot/model/model.go, src/server/v2.0/handler/model/robot.go, src/server/v2.0/handler/robot.go
add the creator for robot creation
Fixes #(issue)
=> add creator for robot

src/portal/src/app/shared/components/global-search/search-result.component.html, src/portal/src/app/shared/components/global-search/search-result.component.ts, src/portal/src/app/shared/components/global-search/search.component.scss
Bug Report: The banner message was obscuring the search bar issue - #20608 
Resolution: The issue has been resolved by adjusting some styles and adding function  to ensure the below content does not overlap the search bar.
Details: After applying the style changes, the search bar is now fully visible even with the banner message displayed at the top of the page.
Fixes #20608 
=> Fixed the ui bug of banner coming over the search result container

src/common/api/base.go, src/common/const.go, src/common/http/tls.go, src/common/job/client.go, src/common/job/models/models.go, src/common/models/job.go, src/common/models/uaa.go, src/common/rbac/project/evaluator_test.go, src/common/secret/request.go, src/common/utils/email/mail.go, src/common/utils/email/mail_test.go, src/common/utils/encrypt.go, src/common/utils/passports.go, src/common/utils/test/config.go, src/common/utils/test/test.go, src/common/utils/utils.go, src/server/route.go
=> Fix typos in src/common

src/jobservice/job/impl/scandataexport/scan_data_export.go
Remove useless error check for scan data export job.
Fixes #(issue)
=> refactor: remove useless error check for scan data export job

.github/workflows/build-package.yml
=> Install docker-compose in build-package action

.buildbaselog
=> bump up the pacakges in base image

make/harbor.yml.tmpl
Update comments in template file of installation configurations.
Current descriptions make users a little bit confused about the 'root user'.
=> Update comments in template file of installation configurations

src/pkg/p2p/preheat/provider/client/http_client.go, src/pkg/p2p/preheat/provider/dragonfly.go, src/portal/src/app/base/left-side-nav/distribution/distribution-setup-modal/distribution-setup-modal.component.ts, src/server/v2.0/handler/preheat.go, src/server/v2.0/handler/preheat_test.go
Fix internal server error when test connection to p2p instance with credential.
Fixes #(issue)
=> fix: p2p instance test connection

make/photon/prepare/templates/core/env.jinja, src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts, src/portal/src/app/shared/services/endpoint.service.ts, src/portal/src/i18n/lang/de-de-lang.json, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/i18n/lang/zh-tw-lang.json
Fixes #19693
PR for docs [#519](https://github.com/goharbor/website/pull/519)
=> feat: support Alibaba ACR proxy cache type

src/controller/quota/controller.go
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>
Fixes [21045](https://github.com/goharbor/harbor/issues/21045)
=> fix: nil pointer dereference when failed to scan out the quota records from redis

src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.html, src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.scss, src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.spec.ts, src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts, src/portal/src/app/base/project/project-config/project-policy-config/project.ts, src/portal/src/app/shared/services/project.service.ts
Display proxy cache in project configuration page
Fixes #21021
This PR Only supports to display the values:
=> Fixes-21021 Display proxy cache in project configuration page

src/portal/src/app/app.component.ts, src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-health-check.service.ts
=> Change setHealth to setUnHealth to avoid misunderstanding

src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html, src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
- Resolved an issue where a horizontal scrollbar appeared unnecessarily due to the last table column being hidden, leaving a gap. By rearranging the columns so the last declared column is always visible, the scrollbar issue is fixed.
- This simple change ensures the table layout works as expected without any extra scrollbars by default.
Fixes Unwanted Scrollbar in Replication page.
=> Fix Default Horizontal Scrollbar in Replication Page

.github/workflows/build-package.yml
to avoid blocking the rc, let's temporary disable the gpg sign for development build since the key was expired at Oct 21. I will fix it after RC and revert the code change
Fixes #(issue)
=> temporary disable gpg sign

.github/workflows/build-package.yml
=> fix build package issue

.github/workflows/publish_release.yml
since we wil not ship the asc files since v2.12, it needs to remove the stesp to handle signatures.
Fixes #(issue)
=> fix release script

.github/workflows/nightly-trivy-scan.yml
=> Change the source of trivy-db to avoid 429 error

src/go.mod, src/go.sum
enable job service to set MAX_JOB_DURATION_SECONDS in the jobservice container to customize max job duration
fork gocraft/work to goharbor/work
Fixes #(issue)
=> Enable MAX_JOB_DURATION_SECONDS in the jobservice container

make/photon/db/Dockerfile
The initdb.sh and the upgrade.sh scripts in the postgres image were not owned by the postgres user, which made them failing with permission denied errors in some local builds.
Adding the scripts to the appropriate user and fixing the permissions resolved the issue.
[Fixes #21006
](https://github.com/goharbor/harbor/issues/21006)
=> Fix postgres script permissions

src/controller/artifact/controller.go, src/controller/artifact/controller_test.go, src/controller/artifact/model.go, src/controller/artifact/model_test.go, src/controller/event/handler/replication/replication.go, src/controller/event/metadata/artifact.go, src/controller/event/metadata/tag.go, src/controller/event/topic.go, src/server/v2.0/handler/artifact.go
Fix event-based replication deletion on remote registry not triggered when the replication policy configured the label filter.
Fixes https://github.com/goharbor/harbor/issues/21213
=> fix: event-based replication deletion not work when policy with label

src/controller/event/metadata/robot.go, src/controller/robot/controller.go, src/controller/robot/model.go, src/controller/scan/callback.go, src/controller/scan/callback_test.go, src/testing/controller/robot/controller.go
=> fix robot deletion event

src/controller/event/metadata/robot.go, src/controller/robot/controller.go, src/controller/robot/model.go, src/controller/scan/callback.go, src/controller/scan/callback_test.go, src/testing/controller/robot/controller.go
* fix robot deletion event
* resolve comments
---------
Fixes #(issue)
=> [cherry-pick] fix robot deletion event (#21234)

src/common/rbac/const.go
The export CVE permission should be included in the project scope, as the API relies on project-level judgment.
Fixes #(issue)
=> fix export cve permission issue

CONTRIBUTING.md
When I follow the document to set commit hook.sh with command `curl https://cdn.jsdelivr.net/gh/tommarshall/git-good-commit@v0.6.1/hook.sh >.git/hooks/commit-msg && chmod +x.git/hooks/commit-msg`, I found that the content in .git/hooks/commit-msg is `Moved Permanently. Redirecting to https://cdn.jsdelivr.net/gh/tommarshall/git-good-commit@v0.6.1/hook.sh`.
So I change the address to the moved address.
Fixes #(issue)
=> Change commit-msg hook.sh address to right place

src/pkg/reg/adapter/dtr/adapter.go
Previously DTR adapter Info() method returned incorrect adapter type. Now it is fixed and the correct type is returned.
Fixes #(issue)
=> Fixed the type in DTR adapter info

src/pkg/p2p/preheat/instance/manager.go, src/pkg/p2p/preheat/models/provider/instance.go, src/pkg/p2p/preheat/models/provider/instance_test.go
Abstract a common unified method to ensure that when using a manager to obtain a provider, the auth information is correctly populated.
Fixes https://github.com/goharbor/harbor/issues/21353
=> fix: unify the auth data handle to the decode method

src/pkg/oidc/dao/meta.go, src/server/middleware/security/oidc_cli.go
fixes #21041
verified in local env
Fixes #(issue)
=> Skip admin and change oidc user not found message more readable

api/v2.0/swagger.yaml, make/migrations/postgresql/0160_2.13.0_schema.up.sql, src/server/v2.0/handler/auditlog.go, src/server/v2.0/handler/project.go
=> Add swagger api and audit_log_ext table model

tests/apitests/python/test_system_permission.py, tests/resources/Harbor-Pages/Project_Robot_Account.robot, tests/resources/TestCaseBody.robot, tests/robot-cases/Group1-Nightly/Common.robot
=> Update testcase in main branch

src/controller/event/handler/auditlog/auditlog.go, src/controller/event/handler/init.go, src/controller/event/metadata/commonevent/model.go, src/controller/event/model/event.go, src/controller/event/topic.go, src/core/main.go, src/lib/config/userconfig.go, src/pkg/auditext/dao/dao_test.go, src/pkg/auditext/event/login/login.go, src/pkg/auditext/event/login/login_test.go, src/pkg/auditext/event/login/logout.go, src/pkg/auditext/event/login/logout_test.go, src/pkg/auditext/model/model.go, src/server/v2.0/handler/auditlog.go, tests/apitests/python/library/project.py, tests/apitests/python/library/projectV2.py
Add common event handler
Register login event
Update previous audit log event redirect to auditlogext table
Fixes #(issue)
=> Add user login event to audit log

api/v2.0/swagger.yaml, src/common/const.go, src/controller/purge/controller.go, src/controller/purge/model.go, src/jobservice/job/impl/purge/purge.go, src/jobservice/job/impl/purge/purge_test.go, src/pkg/auditext/dao/dao.go, src/pkg/auditext/dao/dao_test.go, src/pkg/auditext/event/basic.go, src/pkg/auditext/model/model.go, src/server/v2.0/handler/purge.go, src/server/v2.0/handler/purge_test.go, tests/apitests/python/library/purge.py, tests/apitests/python/test_log_rotation.py, tests/apitests/python/test_system_permission.py, tests/robot-cases/Group1-Nightly/Schedule.robot
=> Update purge audit to purge both audit_log_ext and audit_log

src/pkg/auditext/dao/dao_test.go, src/pkg/auditext/event/basic.go, src/pkg/auditext/event/basic_test.go, src/pkg/auditext/event/user/user.go, src/pkg/auditext/model/model.go
=> Fix issue with user create/delete/update event

src/go.mod, src/go.sum, src/lib/cache/cache.go, src/lib/cache/redis/redis.go, src/lib/cache/redis/util.go, src/lib/redis/pool.go
https://github.com/goharbor/harbor/issues/21629
=> add redis tls support for core&jobservice

make/harbor.yml.tmpl, make/photon/prepare/g.py, make/photon/prepare/templates/registry/config.yml.jinja, make/photon/prepare/utils/cert.py, make/photon/prepare/utils/configs.py, make/photon/prepare/utils/registry.py
[21632](https://github.com/goharbor/harbor/issues/21632)
=> prepare redis tls config

src/controller/artifact/processor/cnai/cnai_test.go, src/controller/artifact/processor/cnai/parser/base.go, src/controller/artifact/processor/cnai/parser/files.go, src/controller/artifact/processor/cnai/parser/files_test.go, src/go.mod, src/go.sum, src/lib/errors/const.go, src/lib/http/error.go
Limit the processable file size of CNAI model processor in order to avoid pull large blobs and read them to memory.
Fixes #(issue)
=> fix: limit the file size of the cnai model processor

src/server/middleware/security/robot.go
fix #21762
Harbor logs an informational message when a robot account performs a pull or push operation, as noted in the comments on issue https://github.com/goharbor/harbor/issues/21762.
This behavior can lead to log spamming. To reduce noise, this update changes the log level from 'info' to 'debug' for these operation.
Fixes #(issue)
=> update robot log level

src/go.mod
Format the go.mod, remove additional require section.
Fixes #(issue)
=> chore: format the go.mod

tests/resources/Harbor-Pages/SecurityHub.robot, tests/robot-cases/Group1-Nightly/Trivy.robot
=> Update robot testcase related to security hub row count to 15 by default

src/controller/p2p/preheat/enforcer.go, src/lib/strings.go, src/lib/strings_test.go, src/pkg/p2p/preheat/provider/dragonfly.go, src/pkg/p2p/preheat/provider/preheat_image.go
Preheat type should not only limit to image, cnai model artifact should be included as well in preheat target type.
Fixes #(issue)
=> fix: support preheat cnai model artifact

src/controller/p2p/preheat/enforcer.go, src/lib/strings.go, src/lib/strings_test.go, src/pkg/p2p/preheat/provider/dragonfly.go, src/pkg/p2p/preheat/provider/preheat_image.go
Preheat type should not only limit to image, cnai model artifact should be included as well in preheat target type.
Fixes #(issue)
=> [CHERRY-PICK] fix: support preheat cnai model artifact

Makefile, src/.golangci.yaml, src/common/utils/utils.go, src/jobservice/mgt/manager.go, src/lib/q/builder.go, src/lib/q/query.go, src/lib/retry/retry.go, tests/ci/ut_install.sh
This pull request includes updates to the `golangci-lint` version and significant changes to the `golangci-lint` configuration file. These changes aim to improve the linting process and ensure the codebase adheres to the latest standards.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L474-R474): Updated the `golangci-lint` installation command to use version `v2.1.2` instead of `v1.55.2`.
* [`tests/ci/ut_install.sh`](diffhunk://#diff-64312a020b777f5b0b4b2895a61fd049b6d7ef81b6b229980400e9e52e7914cdL21-R21): Updated the `golangci-lint` installation command to use version `v2.1.2` instead of `v1.61.0`.
* `src/.golangci.yaml`: 
- Removed specific linter settings and simplified the configuration.
- Enabled and disabled specific linters to …
=> chore: bump golangci-lint to v2

.github/workflows/build-package.yml, .github/workflows/publish_release.yml
Per https://github.com/actions/runner-images/issues/11101, the ububnu 20.04 is out of support. This change it up the git action machine to 22.04
Fixes #(issue)
=> upgrade the build machine to ubuntu 22

.github/workflows/build-package.yml, .github/workflows/publish_release.yml
Per https://github.com/actions/runner-images/issues/11101, the ubuntu 20.04 is out of support. Up it to the 22.04
Fixes #(issue)
=> update gitaction machine to 22.04

src/controller/replication/transfer/image/transfer.go
`copyBlobByChunk()` should like `copyBlob()`, first try to mount an exists layer, if not mounted or exist, then copy the layer monolithic or by chunks.
Fixes #(issue)
=> fix: check blob exist before copying layers samller than chunk size

src/lib/orm/query.go
the query parameter cannot contains orm.ExerSep which is key characters that used by orm. the pull request enhances the validation for query parameters.
Fixes #(issue)
=> [cherry-pick] enhance the query judgement

src/server/middleware/v2auth/auth.go, src/server/middleware/v2auth/auth_test.go
This commit update the flow to generate URL of token service, which will first try to use the Host in request.  This will help the situation when Harbor is configured to serve via a hostname but some client needs to pull artifacts from Harbor via IP due to limitations in the environment.
=> Generate URI of token service via Host in request

src/jobservice/common/list/list_test.go
Update for `src/jobservice/common/list/list_test.go` to test does list length increases when pushing `nil value`
=> Test update for adding nil value to list

.github/workflows/build-package.yml, .github/workflows/conformance_test.yml, .github/workflows/publish_release.yml, tests/ci/api_run.sh, tests/ci/build_util.sh, tests/integration.sh, tools/release/release_utils.sh
move the build storage from google storage to the CNCF S3 storage
Currently, we use the internal GCR to store all dev builds for nightly testing, development, and as candidates for RC and GA releases. However, this internal Google storage will no longer be available, this pull request it to move to the CNCF-hosted S3 storage.
Fixes #(issue)
=> udpate storage to s3

.github/workflows/build-package.yml, .github/workflows/conformance_test.yml, .github/workflows/publish_release.yml, tests/ci/api_run.sh, tests/ci/build_util.sh, tests/integration.sh, tools/release/release_utils.sh
move the build storage from google storage to the CNCF S3 storage
Currently, we use the internal GCR to store all dev builds for nightly testing, development, and as candidates for RC and GA releases. However, this internal Google storage will no longer be available, this pull request it to move to the CNCF-hosted S3 storage.
Fixes #(issue)
=> [cherry-pick] udpate storage to s3 (#21999)

.github/workflows/build-package.yml, .github/workflows/conformance_test.yml, .github/workflows/publish_release.yml, tests/ci/api_run.sh, tests/ci/build_util.sh, tests/integration.sh, tools/release/release_utils.sh
move the build storage from google storage to the CNCF S3 storage
Currently, we use the internal GCR to store all dev builds for nightly testing, development, and as candidates for RC and GA releases. However, this internal Google storage will no longer be available, this pull request it to move to the CNCF-hosted S3 storage.
Fixes #(issue)
=> udpate storage to s3 (#21999)

Makefile, make/photon/Makefile
add BUILD_INSTALLER parameter to optional build prepare and log container when only need build offline_installer
Fixes #(issue)
=> add BUILD_INSTALLER parameter for optionally build prepare and log container

tests/apitests/python/library/base.py, tests/apitests/python/library/repository.py, tests/apitests/python/testutils.py
lazy load v2_swagger_client module when running  Setup robot case before swagger file generated.
https://github.com/goharbor/harbor/issues/22123
=> lazy load v2_swagger_client module

make/migrations/postgresql/0170_2.14.0_schema.up.sql, src/pkg/scan/dao/scan/model.go, src/pkg/scan/postprocessors/report_converters.go, src/pkg/scan/vuln/report.go
This commit adds the field "status" to the struct of a vulnerability and adds column "status" to vulnerability record table.  It makes sure the statuses of CVEs returned by trivy scanner is persisted and can be returned via the vulnerabilities addition API of an artifact.
There will be a minor change in UI so the "status is shown in the vulnerability table, and it will be covered in another PR.
=> Add "status" of CVEs to artfact scan report

src/portal/README.md
This PR improves the formatting and readability of the [README.md](https://github.com/goharbor/harbor/blob/main/src/portal/README.md) file under `src/portal`.
No code or functionality is affected - this is only a documentation change.
Fixes #(issue)
None
=> Improve portal README.md formatting and clarity

src/common/rbac/project/rbac_role.go
This pull request introduces a minor update to the RBAC role definitions in the `src/common/rbac/project/rbac_role.go` file. The change adds a new permission to allow reading `NotificationPolicy` resources.
* [`src/common/rbac/project/rbac_role.go`](diffhunk://#diff-824f8f0eae511582f0ee7909fe81aa3d25a119f2f1bb510ac87e9feb81d8d78fR165): Added a new RBAC rule to grant the `ActionRead` permission for the `NotificationPolicy` resource.
Fixes https://github.com/goharbor/harbor/issues/22031
=> fix: correct the permission of project maintainer role for webhook policy

make/photon/prepare/templates/core/env.jinja
According to PR #22198, some inactive adapters have been removed from the default adapter list. This pull request updates PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE accordingly, since the list of proxy cache adapters should be a subset of the replication adapters.
Fixes #(issue)
=> update the support list of proxy cache

.github/workflows/CI.yml, tests/ci/api_run.sh
Enable upload log to github for api test, the download link can be found in the build logs.
Fixes #(issue)
=> Upload build logs to github artifact

src/pkg/repository/dao/dao.go
use exists instead of in condition
Fixes #(issue)
=> Refine the sql to query non empty repositories

tests/resources/Harbor-Pages/SecurityHub.robot, tests/resources/Harbor-Pages/Vulnerability.robot
Change column number because status column added before package column.
fixes #22286 and #22285
increase column number
Fixes #(issue)
=> Adjust the xpath to find the package column in testcase

src/server/v2.0/handler/robot.go
fixes #21406
The changes are target to fix the system robot to create a project level robots. It should not to get the creator robot with the createe robot's project id, and updates the code get the creator robot from the security context.
Fixes #(issue)
=> [cherry-pick] fix robot issue-21406

api/v2.0/swagger.yaml, src/pkg/project/models/pro_meta.go, src/pkg/project/models/project.go, src/pkg/proxy/connection/limit.go, src/pkg/proxy/connection/limit_test.go, src/server/middleware/repoproxy/proxy.go, src/server/v2.0/handler/project.go, src/server/v2.0/handler/project_metadata.go, src/server/v2.0/handler/project_metadata_test.go
Limit the proxy connection to the upstream registry
fixes #22184
Fixes #(issue)
=> Add max_upstream_conn parameter for each proxy_cache project
