goharbor/harbor

- src/pkg/p2p/preheat/job.go
> fix(preheat):handle fail case of preheat in job

- src/pkg/p2p/preheat/job.go
> [CHERRY-PICK]fix(preheat):handle fail case of preheat in job

- .github/workflows/CI.yml
- tests/ci/api_common_install.sh
- tests/robot-cases/Group0-BAT/API_DB.robot
> Fix issue of missing swagger package for python API test

- src/replication/transfer/image/transfer.go
> retry several times when failed to copy blob during the replication

- src/jobservice/job/impl/gc/garbage_collection.go
- src/pkg/artifactrash/model/model.go
Do not log redis url, just log the user input from UI.
> fix gc log issue

- src/replication/transfer/image/transfer.go
> [cherry-pick-1.10]retry several times when failed to copy blob during the replication

- src/server/middleware/v2auth/auth.go
- src/server/middleware/v2auth/auth_test.go
> Return basic auth challenge for /v2/_catalog -- cherrypick to 2.1.0 

- src/server/middleware/v2auth/auth.go
- src/server/middleware/v2auth/auth_test.go
> Return basic auth challenge for /v2/_catalog

- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
- src/server/v2.0/handler/project.go
Closes:  https://github.com/goharbor/harbor/issues/12891 
> fix(p2p): delete all preheat policies before delete project

- tests/ci/api_common_install.sh
> Fix git action CI missing python sit packages issue

- tests/ci/api_common_install.sh
> Fix git action CI python package installation

- tests/ci/api_common_install.sh
> cherry-pick to 2.0.0 fix git action CI missing python sit packages issue

- src/replication/transfer/image/transfer.go
> [cherry-pick-2.1]retry several times when failed to copy blob during the replication

- src/replication/transfer/image/transfer.go
> [cherry-pick-2.0]retry several times when failed to copy blob during the replication

- src/jobservice/job/impl/gc/garbage_collection.go
- src/pkg/artifactrash/model/model.go
1, Do not log redis url, just log the user input from UI.
2, Format the artifact trash items.
fix
> [cherry-pick]fix gc log issue

- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
- src/server/v2.0/handler/project.go
Closes:  https://github.com/goharbor/harbor/issues/12891 
> [CHERRY-PICK]fix(p2p): delete all preheat policies before delete project

- docs/install-config/run-installer-script.md
run installer script need contains the content about trivy adapter
> Add Doc for Trivy

- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/app/project/create-project/create-project.component.html
- src/portal/src/app/project/list-project/list-project.component.ts
- src/portal/src/app/project/project-config/project-config.component.html
- src/portal/src/app/project/project-config/project-config.component.ts
- src/portal/src/app/project/repository/artifact/artifact-summary.component.html
- src/portal/src/app/project/repository/artifact/artifact-summary.component.ts
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.html
- src/portal/src/global.scss
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/config/gc/gc-history/gc-history.component.html
- src/portal/src/lib/components/config/gc/gc-history/gc-history.component.ts
- src/portal/src/lib/components/project-policy-config/project-policy-config.component.html
- src/portal/src/lib/components/project-policy-config/project-policy-config.component.ts
> [Cherry-pick]Fix UI issues found on testing day

- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/app/project/create-project/create-project.component.html
- src/portal/src/app/project/list-project/list-project.component.ts
- src/portal/src/app/project/project-config/project-config.component.html
- src/portal/src/app/project/project-config/project-config.component.ts
- src/portal/src/app/project/repository/artifact/artifact-summary.component.html
- src/portal/src/app/project/repository/artifact/artifact-summary.component.ts
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.html
- src/portal/src/global.scss
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/config/gc/gc-history/gc-history.component.html
- src/portal/src/lib/components/config/gc/gc-history/gc-history.component.ts
- src/portal/src/lib/components/project-policy-config/project-policy-config.component.html
- src/portal/src/lib/components/project-policy-config/project-policy-config.component.ts
Fixes #12946 
Fixes #12940 
Fixes #12923 
Fixes #12922
Fixes #12937
Fixes #12931 
Fixes #12928 
Fixes #12926 
Fixes #12922 
> Fix UI issues found on testing day

- make/photon/prepare/migrations/version_1_10_0/harbor.yml.jinja
- make/photon/prepare/migrations/version_1_9_0/harbor.yml.jinja
- make/photon/prepare/migrations/version_2_0_0/harbor.yml.jinja
- make/photon/prepare/migrations/version_2_1_0/harbor.yml.jinja
> Fix trivy setting in upgrading script

- src/common/models/label.go
- src/common/models/repo.go
- src/controller/artifact/model.go
- src/controller/tag/model.go
- src/pkg/artifact/model.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/model/artifact.go
- src/server/v2.0/handler/model/label.go
- src/server/v2.0/handler/model/repository.go
- src/server/v2.0/handler/model/tag.go
- src/server/v2.0/handler/repository.go
1, remove the pkg dependency on v2.0/server/models
2, remove the controller dependency on v2.0/server/models
> remove the dependency on swagger models

- src/common/dao/dao_test.go
- src/common/dao/user.go
> Escape the query string in list user - Cherry pick to 2.1 branch

- src/common/dao/dao_test.go
- src/common/dao/user.go
> Escape the query string in list user

- src/jobservice/job/impl/notification/http_helper.go
- src/jobservice/job/impl/notification/http_helper_test.go
- src/jobservice/job/impl/notification/slack_job.go
- src/jobservice/job/impl/notification/webhook_job.go
Close: https://github.com/goharbor/harbor/issues/13016
> fix(webhook): fix the verify cert logic of webhook endpoint

- api/v2.0/legacy_swagger.yaml
* Add the Location Header to POST responses
Without the header, you cannot know which object you just created.
* Add the paging Headers and parameters to GET responses for lists where the code already exists
Without the header, you cannot retrieve the entire list of items.
> fix: Location and Paging support in swagger api

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> [Cherry-pick]Change EXECUTE button to uppercase

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Change EXECUTE button to uppercase

- src/jobservice/job/impl/notification/http_helper.go
- src/jobservice/job/impl/notification/http_helper_test.go
- src/jobservice/job/impl/notification/slack_job.go
- src/jobservice/job/impl/notification/webhook_job.go
> fix(webhook): fix the verify cert logic of webhook endpoint - cherrypick to 2.1 branch

- src/jobservice/job/impl/notification/http_helper.go
- src/jobservice/job/impl/notification/http_helper_test.go
- src/jobservice/job/impl/notification/slack_job.go
- src/jobservice/job/impl/notification/webhook_job.go
> fix(webhook): fix the verify cert logic of webhook endpoint -- cherrypick to 2.0 branch

- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
> Improve notary cmd on UI

- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
> [Cherry-pick]Improve notary cmd on UI

- .github/workflows/CI.yml
- tests/apitests/python/library/singularity.py
- tests/apitests/python/test_list_helm_charts.py
- tests/apitests/python/test_replication_from_dockerhub.py
- tests/apitests/python/update_docker_cfg.sh
- tests/ci/api_common_install.sh
- tests/ci/api_run.sh
- tests/e2e-image/Dockerfile
- tests/e2e-image/dockerd-entrypoint.sh
- tests/resources/Helm-Util.robot
- tests/resources/Nightly-Util.robot
> Create Dockerfile for E2E py-test

- src/common/dao/dao_test.go
- src/common/dao/user.go
> [Cherry-pick-2.0]Escape the query string in list user (#13012)

- tests/resources/Helm-Util.robot
> Remove ca parameter in helm test case

- src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.ts
> [Cherry-pick]Disable endpoint input for docker-hub and helm-hub

- src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.ts
> Disable endpoint input for docker-hub and helm-hub

- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Helm-Util.robot
- tests/resources/Nightly-Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Setup_Nightly.robot
- tests/robot-cases/Group3-Upgrade/prepare.py
> Rerun keyword of push CNAB

- make/photon/prepare/migrations/version_2_1_0/harbor.yml.jinja
internal tls config upgrade is not included in template, this pr is to add it.
> Fix internal tls config upgrade issue

- RELEASES.md
Signed-off-by: Abigail McCarthy <mabigail@vmware.com>
> update releases.md for 2.1

- tests/resources/Harbor-Pages/Verify.robot
- tests/robot-cases/Group3-Upgrade/data.json
- tests/robot-cases/Group3-Upgrade/feature_map.json
- tests/robot-cases/Group3-Upgrade/prepare.py
- tests/robot-cases/Group3-Upgrade/verify.robot
> Fix typo in upgrade prepare scritp

- tests/resources/Harbor-Pages/Verify.robot
- tests/robot-cases/Group3-Upgrade/data.json
- tests/robot-cases/Group3-Upgrade/feature_map.json
- tests/robot-cases/Group3-Upgrade/prepare.py
- tests/robot-cases/Group3-Upgrade/verify.robot
> Fix typo in upgrade prepare script

- src/portal/src/app/services/intercept-http.service.ts
> Handle 504 error from backend

- .github/workflows/build-package.yml
- tests/ci/build_util.sh
> Add harbor build in git action workflow

- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Replication.robot
> Fix nightly case for replication

- tests/apitests/python/library/configurations.py
- tests/apitests/python/test_ldap_admin_role.py
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Configuration_Elements.robot
- tests/resources/Harbor-Pages/LDAP-Mode.robot
- tests/robot-cases/Group0-BAT/API_LDAP.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/LDAP.robot
> Add UI test for LDAP admin group dn setting

- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Verify.robot
> Replication UI changes break upgrade pipeline

- src/controller/proxy/controller.go
Extract and move UpdatePullTime to util package
Fixes #13152
> Add pull time for proxy cache artifact in first pull

- .github/workflows/build-package.yml
- tests/ci/build_util.sh
> Add harbor build job in git action workflow

- src/controller/proxy/controller.go
- src/server/middleware/repoproxy/proxy.go
- src/server/registry/route.go
Fixes: #13153, containerd need to head manifest before pull image
> Add middleware to proxy HEAD request for proxy cache project

- src/common/utils/ldap/ldap.go
- src/common/utils/ldap/ldap_test.go
Search LDAP group with groupDN+filter, then match baseDN
Create a default filter when ldap group filter is empty
Fixes #13156
> Refine ldap searchGroup function 

- src/controller/proxy/controller.go
> (cherry-pick) Add pull time for proxy cache artifact in first pull

- src/common/utils/ldap/ldap.go
- src/common/utils/ldap/ldap_test.go
Search LDAP group with groupDN+filter, then match baseDN
Create a default filter when ldap group filter is empty
Fixes #13156
> (cherry-pick) Refine LDAP searchGroup function

- src/portal/src/app/global-message/message.component.html
- src/portal/src/app/global-message/message.component.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/shared/list-repository-ro/list-repository-ro.component.spec.ts
- src/portal/src/app/shared/list-repository-ro/list-repository-ro.component.ts
Fixes: #8491 
Fixes: #12594 
Temp Env: https://10.185.12.35
> Allow un-logged users to visit public repos

- src/controller/proxy/controller.go
- src/server/middleware/repoproxy/proxy.go
- src/server/registry/route.go
Fixes: #13153, containerd need to head manifest before pull image
> (cherry-pick) Add middleware to proxy HEAD request for proxy cache project

- src/replication/adapter/quay/adapter.go
- src/replication/adapter/quay/auth/apikey.go
- src/replication/adapter/quay/auth/apikey_test.go
- src/replication/adapter/quay/auth/authorizer.go
- src/replication/adapter/quay/auth/authorizer_test.go
Close: https://github.com/goharbor/harbor/issues/13200
> fix: fix quay adapter catalog api return error

- src/replication/adapter/quay/adapter.go
- src/replication/adapter/quay/auth/apikey.go
- src/replication/adapter/quay/auth/apikey_test.go
- src/replication/adapter/quay/auth/authorizer.go
- src/replication/adapter/quay/auth/authorizer_test.go
cherry-pick of merged pull request: https://github.com/goharbor/harbor/pull/13305
> [cherry-pick] fix: fix quay adapter catalog api return error

- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/config/config.ts
Releative issue #13113 
Temp Env:  https://10.185.12.35:4200
> [UI]Add admin group support to OIDC auth mode

- src/common/utils/ldap/ldap.go
> (cherry-pick) Remove dup call to createGroupSearchFilter in searchGroup

- src/portal/src/css/common.scss
> Fix a css bug of Clarity page size selection

- src/common/config/store/driver/db.go
- src/common/utils/oidc/secret.go
> Add more info in log message to help debug

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/push-image/push-image.component.html
- src/portal/src/lib/components/push-image/push-image.scss
Fixes #13328
Fixes #13227
Before:
After:
> Fix css and i18n bugs

- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.spec.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Improve vilnerability list UI

- tests/resources/Nightly-Util.robot
- tests/robot-cases/Group3-Upgrade/data.json
- tests/robot-cases/Group3-Upgrade/prepare.py
- tests/robot-cases/Group3-Upgrade/verify.robot
> Fix nightly upgrade webhook prepared data

- src/portal/src/lib/components/replication/replication.component.ts
> Fix filter bug for replication rule list

- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
> [Cherry-pick]Fix a bug for editing p2p instance

- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group3-Upgrade/prepare.py
> Optimize upgrade pipeline script of push image

- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.scss
> Fix css bug for adding p2p policy

- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
> Fix a bug for editing p2p instance

- api/v2.0/swagger.yaml
Fix: https://github.com/goharbor/harbor/issues/13369
> fix(preheat): disable preheat model bool type json omitempty option

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/preheat.go
Fix: https://github.com/goharbor/harbor/issues/13378
> fix(preheat): add location when create instance and policy

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
Fixes #13338
Temprory envirenment: https://10.185.12.35:4200
> Improve label selection for artifact list page

- src/replication/adapter/awsecr/adapter.go
fix https://github.com/goharbor/harbor/issues/13268
> feature(replication) check namespace existing first for AWS adapter

- src/replication/adapter/harbor/base/chart_registry.go
issue https://github.com/goharbor/harbor/issues/13187
> fix chart replication issue of uppercase letters

- src/portal/src/app/config/scanner/config-scanner.component.html
- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.html
- src/portal/src/app/project/p2p-provider/policy/policy.component.html
- src/portal/src/lib/components/list-replication-rule/list-replication-rule.component.html
- src/portal/src/lib/components/replication/replication-tasks/replication-tasks.component.ts
> Improve UI according to the designer's commonts

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.html
- src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.scss
- src/portal/src/lib/components/create-edit-endpoint/create-edit-endpoint.component.ts
- src/portal/src/lib/components/endpoint/endpoint.component.html
- src/portal/src/lib/components/endpoint/endpoint.component.scss
- src/portal/src/lib/components/endpoint/endpoint.component.ts
- src/portal/src/lib/components/list-replication-rule/list-replication-rule.component.html
- src/portal/src/lib/components/list-replication-rule/list-replication-rule.component.scss
- src/portal/src/lib/components/list-replication-rule/list-replication-rule.component.ts
- src/portal/src/lib/services/endpoint.service.ts
> [Cherry-pick]Add deprecated mark to Helm Hub

- src/replication/adapter/gitlab/adapter.go
fix gitlab replication task num not correct
close https://github.com/goharbor/harbor/issues/13272
> fix(replication) gitlab replication task num not correct

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/config/config.ts
- src/portal/src/lib/components/config/system/system-settings.component.html
- src/portal/src/lib/components/config/system/system-settings.component.ts
Related backend PR #13425
UI changes:
> [UI]add robot name prefix

- make/photon/log/Dockerfile
- make/photon/log/Dockerfile.base
move chage command to base image
> Fix: log container password expire

- make/migrations/postgresql/0050_2.2.0_schema.up.sql
- src/controller/artifact/abstractor.go
- src/controller/artifact/abstractor_test.go
> fix: compute artifact size from db for schema1 manifest

- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.html
> Fix tooltip bug for adding replication rule page

- make/migrations/postgresql/0050_2.2.0_schema.up.sql
> fix: ensure the role_id of role is correct

- tests/integration.sh
- tests/resources/Harbor-Util.robot
> Add login for docker-hub in package build proces

- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/resources/Harbor-Util.robot
> Add docker-hub login in build package

- src/controller/robot/controller.go
- src/controller/robot/controller_test.go
- src/controller/robot/model.go
- src/controller/robot/model_test.go
the controller is for the enhanced robot account
> add robot account version 2 controller

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/preheat.go
Fix: https://github.com/goharbor/harbor/issues/13378
> [CHERRY_PICK] fix(preheat): add location when create instance and policy

- api/v2.0/swagger.yaml
Cherry-pick of https://github.com/goharbor/harbor/pull/13380
> [CHERRY_PICK] fix(preheat): disable preheat model bool type json omitempty option

- src/server/middleware/metric/metric.go
Stauts code can't get from request. It shoud be recorded by a delegator
> Fix status code in metrics issue

- src/pkg/scan/rest/auth/api_key_auth.go
- src/pkg/scan/rest/auth/auth.go
Closes: https://github.com/goharbor/harbor/issues/13277
> fix: fix scanner apikey type match error

- tools/migrate_chart/Dockerfile
- tools/migrate_chart/Readme.md
- tools/migrate_chart/migrate_chart.py
- tools/migrate_chart/migrate_chart.sh
chartmuseum might deprecated in future. This tool is used for migrate the charts
> Add tool for migration chart v2 to oci format

- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.html
- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.scss
- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.ts
- src/portal/src/lib/components/inline-alert/inline-alert.component.scss
> Improve adding replication rule page

- src/portal/src/app/project/create-project/create-project.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Add new supported registries for proxy cache on UI

- src/common/utils/ldap/ldap.go
- src/common/utils/ldap/ldap_test.go
Fixes #13362: Unable to add LDAP group with different letter case in DN
> Lowercase the LDAP DN in UnderBaseDN

- src/portal/src/app/shared/route/auth-user-activate.service.ts
> Fix null pointer exception for auth guard

- src/chartserver/cache.go
- src/chartserver/handler_utility.go
- src/chartserver/utils.go
close #13485
fix redis sentinel for chartmuseum cache
this only impact the chart detail page
> fix(redis) redis sentinel for chart cache

- src/server/middleware/metric/metric.go
remove nested handler for instrumenting
> Fix instrumenting handler nest issue

- src/controller/quota/controller.go
> fix(quota): ignore the fail when getting reference of quota

- tests/apitests/python/library/docker_api.py
- tests/robot-cases/Group0-BAT/API_DB.robot
> fix proxy cache e2e test

- src/common/dao/pgsql.go
Set timezone as UTC for database connection
> Set timezone as UTC for database connection

- src/common/dao/pgsql.go
Set timezone as UTC for database connection
> [cherry-pick]Set timezone as UTC for database connection

- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Sychronize replication nightly test scripts with v2.0.0

- src/server/middleware/pattern_test.go
- src/server/middleware/patterns.go
> Fix the pattern to match v2 catalog URI

- api/v2.0/swagger.yaml
- make/migrations/postgresql/0050_2.2.0_schema.up.sql
- src/controller/robot/controller.go
- src/controller/robot/controller_test.go
- src/controller/scan/base_controller.go
- src/controller/scan/base_controller_test.go
- src/pkg/robot2/model/model.go
- src/server/middleware/security/robot2.go
- src/server/v2.0/handler/robot.go
- src/server/v2.0/handler/robotV1.go
- src/testing/controller/robot/controller.go
1, use SHA256 to generate and validate robot secret instread of symmetric encryption.
2, update the patch input object
> update robot secret

- .github/workflows/CI.yml
- tests/apitests/python/test_scan_image_artifact.py
- tests/ci/api_run.sh
> Move proxy cache e2e test into a new CI job

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/project/repository/artifact/artifact.ts
- src/portal/src/app/services/routing-resolvers/artifact-detail-routing-resolver.service.ts
> Add limitation to artifact tags

- src/jobservice/job/impl/replication/replication.go
- src/replication/adapter/artifacthub/adapter.go
- src/replication/adapter/artifacthub/adapter_test.go
- src/replication/adapter/artifacthub/chart_registry.go
- src/replication/adapter/artifacthub/client.go
- src/replication/adapter/artifacthub/consts.go
- src/replication/adapter/artifacthub/model.go
- src/replication/model/registry.go
- src/replication/replication.go
> Support replicate from artifact hub

- src/controller/robot/controller.go
- src/controller/robot/controller_test.go
- src/server/middleware/security/robot2.go
- src/server/middleware/security/robot2_test.go
- src/server/v2.0/handler/robot.go
add project name into project level robot account name
> fix robot name conflicate issue

- src/go.mod
- src/go.sum
- src/jobservice/job/impl/replication/replication.go
- src/replication/adapter/tencentcr/adapter.go
- src/replication/adapter/tencentcr/adapter_test.go
- src/replication/adapter/tencentcr/artifact_registry.go
- src/replication/adapter/tencentcr/artifact_registry_test.go
- src/replication/adapter/tencentcr/auth.go
- src/replication/adapter/tencentcr/chart_registry.go
- src/replication/adapter/tencentcr/sdk.go
- src/replication/adapter/tencentcr/sdk_test.go
- src/replication/model/registry.go
- src/replication/replication.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/LICENSE
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/credentials.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors/errors.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/regions/regions.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/sign.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/types.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/client.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/models.go
- src/vendor/modules.txt
1. Docker image registry.
2. Helm chart registry.
Signed-off-by: 疯魔慕薇 <kfanjian@gmail.com>
> Tecent TCR Provider

- src/go.mod
- src/go.sum
- src/jobservice/job/impl/replication/replication.go
- src/replication/adapter/tencentcr/adapter.go
- src/replication/adapter/tencentcr/adapter_test.go
- src/replication/adapter/tencentcr/artifact_registry.go
- src/replication/adapter/tencentcr/artifact_registry_test.go
- src/replication/adapter/tencentcr/auth.go
- src/replication/adapter/tencentcr/chart_registry.go
- src/replication/adapter/tencentcr/sdk.go
- src/replication/adapter/tencentcr/sdk_test.go
- src/replication/model/registry.go
- src/replication/replication.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/LICENSE
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/credentials.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors/errors.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/regions/regions.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/sign.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/types.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/client.go
- src/vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tcr/v20190924/models.go
- src/vendor/modules.txt
1. Docker image registry.
2. Helm chart registry.
Signed-off-by: 疯魔慕薇 <kfanjian@gmail.com>
> Cherry Pick: Tencent TCR Provider

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
> Fix UI UT failure

- src/jobservice/job/tracker.go
- src/jobservice/lcm/controller.go
- src/jobservice/period/basic_scheduler.go
- src/jobservice/period/basic_scheduler_test.go
- src/jobservice/period/policy_store.go
- src/jobservice/period/policy_store_test.go
- src/jobservice/runner/redis.go
- src/jobservice/worker/cworker/c_worker.go
- update StopJob() of basic worker
- update UnSchedule() of basic scheduler
- update the policy store to get more data
fix #13599 , fix #13597
> fix(api):update stop job api

- src/jobservice/job/impl/replication/replication.go
- src/replication/adapter/githubcr/adapter.go
- src/replication/adapter/githubcr/adapter_test.go
- src/replication/model/registry.go
- src/replication/replication.go
> GHCR Provider

- tests/apitests/python/library/system.py
- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/resources/TestCaseBody.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Migrate gitlab replication test to nightly

- src/portal/src/app/project/robot-account/add-robot/add-robot.component.html
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts
- src/portal/src/app/project/robot-account/robot-account.component.html
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.html
- src/portal/src/app/system-robot-accounts/view-token/view-token.component.html
- src/portal/src/app/system-robot-accounts/view-token/view-token.component.scss
- src/portal/src/app/system-robot-accounts/view-token/view-token.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Improve refresh secret page for robot account UI

- src/portal/src/lib/services/endpoint.service.ts
> Improve regitries UI to cover new registries

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/project.go
- src/server/v2.0/handler/robotV1.go
- src/server/v2.0/handler/util.go
Support project name in the path of projects and robotsV1 APIs.
Closes #13387
> feat(api): support project name in the path of apis

- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/config/config.ts
> Add admin groups parameter to http auth

- src/lib/cache/memory/memory_test.go
- src/lib/cache/redis/redis_test.go
> test(cache): increase sleep time to fix ut

- src/portal/src/app/account/account-settings/account-settings-modal.component.html
- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/app/user/change-password/change-password.component.ts
- src/portal/src/app/user/user.component.html
- src/portal/src/app/user/user.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Signed-off-by: sluetze <13255307+sluetze@users.noreply.github.com>
fixes #13568
> fixed small typos in variable names

- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/library/system.py
- tests/apitests/python/sign_image.sh
- tests/apitests/python/test_add_sys_label_to_tag.py
- tests/apitests/python/test_copy_artifact_outside_project.py
- tests/apitests/python/test_del_repo.py
- tests/apitests/python/test_garbage_collection.py
- tests/apitests/python/test_manage_project_member.py
- tests/apitests/python/test_project_level_policy_content_trust.py
- tests/apitests/python/test_push_cnab_bundle.py
- tests/apitests/python/test_push_index_by_docker_manifest.py
- tests/apitests/python/test_registry_api.py
- tests/apitests/python/test_robot_account.py
- tests/apitests/python/test_scan_image_artifact.py
- tests/apitests/python/test_scan_image_artifact_in_public_project.py
- tests/apitests/python/test_sign_image.py
- tests/apitests/python/test_system_level_scan_all.py
- tests/apitests/python/test_tag_crud.py
- tests/apitests/python/test_tag_immutability.py
- tests/apitests/python/test_user_view_logs.py
> Cherry-pick 2.0 build image sample for test in local

- src/server/v2.0/handler/gc.go
- src/server/v2.0/handler/replication.go
- tests/apitests/python/library/base.py
> add permission checking for gc operation

- src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.html
- src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.scss
- src/portal/src/app/system-robot-accounts/system-robot-util.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Add new permissions to robot account

- src/common/dao/label.go
- src/lib/orm/query.go
- src/pkg/scan/dao/scanner/registration.go
- src/replication/dao/policy.go
> Escape the values to `contains` operator in dao packages

- make/migrations/postgresql/0050_2.2.0_schema.up.sql
> Add default CVE allowlist to project library

- src/common/utils/uaa/test/server.go
- src/core/auth/authproxy/test/server.go
The fixing method is from https://codeql.github.com/codeql-query-help/go/go-reflected-xss/
> fix: fix errors detected by codeql

- api/v2.0/swagger.yaml
- src/controller/scan/base_controller.go
> fix(scan): returns 400 when artifact not support by scanner

- make/photon/prepare/templates/registry/config.yml.jinja
- make/photon/prepare/templates/registryctl/config.yml.jinja
- make/photon/prepare/utils/registry.py
- make/photon/prepare/utils/registry_ctl.py
1. fix level issue in registry.jinja
2. add log level to registryctl
> Fix log level issue in registry

- make/photon/portal/Dockerfile
- src/portal/src/app/project/robot-account/robot-account.component.html
- src/portal/src/app/project/robot-account/robot-account.component.ts
- src/portal/src/app/shared/statictics/statistics-panel.component.ts
- src/portal/src/app/shared/statictics/volumes.ts
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.ts
- src/portal/src/app/system-robot-accounts/system-robot-util.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.html
> Fix robot account UI issues

- make/migrations/postgresql/0050_2.2.0_schema.up.sql
- src/common/config/metadata/metadatalist.go
- src/core/config/config_test.go
- src/server/v2.0/handler/robot.go
- src/server/v2.0/handler/robot_test.go
enable the update method to support both v1 & v2 robot update
> fix robot account update issue

- make/photon/prepare/scripts/gencert.sh
> Add San for internal tls

- src/portal/src/app/services/routing-resolvers/replication-tasks-routing-resolver.service.spec.ts
- src/portal/src/app/services/routing-resolvers/replication-tasks-routing-resolver.service.ts
- src/portal/src/lib/components/replication/replication-tasks/replication-tasks.component.html
- src/portal/src/lib/components/replication/replication-tasks/replication-tasks.component.spec.ts
- src/portal/src/lib/components/replication/replication-tasks/replication-tasks.component.ts
> Fix filter bug for replication tasks page

- make/photon/prepare/utils/configs.py
> Fix pythom yaml load to safe_load

- src/replication/adapter/tencentcr/adapter_test.go
> Remove some TCR UT Case

- src/common/config/metadata/metadatalist.go
- src/common/config/metadata/type.go
- src/common/config/metadata/type_test.go
- src/common/const.go
- src/common/models/config.go
- src/common/utils/oidc/helper.go
- src/common/utils/oidc/helper_test.go
- src/core/config/config.go
> Add extra parms when forming redirect URI for OIDC

- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.ts
- src/portal/src/lib/components/config/config.ts
- src/portal/src/lib/components/config/system/system-settings.component.html
- src/portal/src/lib/components/config/system/system-settings.component.ts
> Fix a save button bug on system setting page

- src/pkg/scheduler/scheduler.go
Use the same transaction to remove the schedule to avoid dead lock in database
Fixes #13808
> Use the same transaction to remove the schedule to avoid dead lock in database

- src/pkg/scheduler/scheduler.go
- src/pkg/task/mock_task_manager_test.go
- src/pkg/task/task.go
- src/pkg/task/task_test.go
- src/testing/pkg/scheduler/scheduler.go
- src/testing/pkg/task/manager.go
Provide the function to update extra attributes in the task manager
> Provide the function to update extra attributes in the task manager

- src/portal/src/lib/components/config/config.ts
- src/portal/src/lib/components/config/vulnerability/scanAll.service.ts
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.html
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.scss
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.spec.ts
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.ts
> Improve scan all page

- src/controller/gc/callback.go
> fix quota cannot be updated after gc

- make/migrations/postgresql/0050_2.2.0_schema.up.sql
- src/core/api/base.go
- src/core/api/retention.go
- src/core/service/notifications/jobs/handler.go
- src/pkg/retention/callback.go
- src/pkg/retention/controller.go
- src/pkg/retention/controller_test.go
- src/pkg/retention/faked_controller.go
- src/pkg/retention/launcher.go
- src/pkg/retention/launcher_test.go
- src/pkg/retention/manager.go
- src/pkg/retention/manager_test.go
- src/pkg/retention/mocks/api_controller.go
- src/pkg/task/model.go
- src/server/route.go
refactor retention with task manager
close #13159
> feat(retention) refactor task manager

- src/common/security/local/context_test.go
- src/pkg/permission/evaluator/admin/admin.go
> Remove scanner-pull from system admin's permission

- src/portal/src/app/project/create-project/create-project.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> [UI]Support quay registry as proxy cache

- src/common/security/local/context_test.go
- src/pkg/permission/evaluator/admin/admin.go
> Remove scanner-pull from system admin's permission -- Cherrypick-2.1 branch

- src/common/security/local/context_test.go
- src/pkg/permission/evaluator/admin/admin.go
> Remove scanner-pull from system admin's permission - cherrypick to 2.0 branch

- src/controller/scan/callback.go
- src/controller/scan/callback_test.go
> test: fix the data race in the test of scan controller

- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Harbor-Pages/Robot_Account.robot
- tests/resources/Harbor-Pages/Robot_Account_Elements.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
Add GUI test for system robot account feature.
Fixed issue: #13689.
> Ad  nightly GUI test for system robot account

- make/photon/prepare/templates/core/env.jinja
> Add  quay registry to proxy cache

- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.ts
> Fix tag retention ui loading issue

- src/controller/scan/base_controller.go
- src/pkg/task/execution.go
- src/pkg/task/execution_test.go
Provide a mechanism to sweep the execution/task records in task manager
Fixes #13888
> Provide a mechanism to sweep the execution/task records in task manager

- make/photon/prepare/utils/cert.py
- make/photon/prepare/utils/notary.py
> Add san for notary cert

- src/replication/adapter/adapter.go
- src/replication/adapter/artifacthub/adapter_test.go
- src/replication/adapter/artifacthub/chart_registry.go
- src/replication/adapter/artifacthub/client.go
- src/replication/adapter/artifacthub/consts.go
- src/replication/adapter/artifacthub/model.go
- src/replication/adapter/harbor/base/chart_registry.go
- src/replication/adapter/harbor/base/chart_registry_test.go
- src/replication/adapter/helmhub/chart_registry.go
- src/replication/adapter/tencentcr/chart_registry.go
- src/replication/transfer/chart/transfer.go
- src/replication/transfer/chart/transfer_test.go
some download failed, because the content URLs are invalid. these URLs are maintained by chart provider.
> Support artifact hub replication using new API

- src/jobservice/job/status.go
- src/jobservice/period/basic_scheduler.go
- src/jobservice/worker/cworker/c_worker.go
- src/jobservice/worker/cworker/reaper.go
- src/pkg/scan/vuln/util.go
reform job status Compare method, make it human readable like go standard package time.Time
> reform job status compare method

- tests/apitests/python/library/artifact.py
- tests/apitests/python/library/base.py
- tests/apitests/python/library/chart.py
- tests/apitests/python/library/helm.py
- tests/apitests/python/library/label.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/library/robot.py
- tests/apitests/python/test_robot_account.py
- tests/apitests/python/testutils.py
- tests/resources/Harbor-Pages/Robot_Account.robot
- tests/robot-cases/Group1-Nightly/Common.robot
In this py-test, add a new system robot account, and verify all project privileges.
Fixed issue: #13875.
> Add py test for system robot account

- tests/apitests/python/library/docker_api.py
- tests/resources/Harbor-Pages/Replication.robot
> Fix issue of wrong xpath for replicaiton row selector

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- tests/resources/Harbor-Pages/Vulnerability.robot
> Fix nightly case by add id to scan button

- src/replication/transfer/chart/transfer.go
- src/replication/transfer/image/transfer.go
Check the stop error during the replication process
Fixes #13912
> Check the stop error during the replication process

- api/v2.0/legacy_swagger.yaml
- api/v2.0/swagger.yaml
- src/server/v2.0/handler/retention.go
- tests/apitests/python/library/base.py
- tests/apitests/python/library/retention.py
- tests/apitests/python/library/tag_immutability.py
- tests/robot-cases/Group0-BAT/API_DB.robot
fix #13942
retention.py
tag_immutability.py
> fix(retention) swagger test case

- src/controller/robot/controller.go
- src/controller/robot/controller_test.go
> fix robot cannot update expiresat

- make/photon/prepare/utils/cert.py
- make/photon/prepare/utils/notary.py
> Add san for notary cert - cherrypick 1.10

- .github/workflows/build-package.yml
- tests/ci/build_util.sh
> Push harbor build images to docker-hub in build workflow

- .github/workflows/build-package.yml
- tests/ci/build_util.sh
> Pass git action secret tp push image function in build workflow

- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.html
- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.ts
> Fix tag-retention nightly failure

- src/controller/robot/controller.go
> do not add prefix for the legacy robots

- api/v2.0/swagger.yaml
fix retention nightly ui case failed when retained or total is empty
> fix(retention) retained/total empty when 0

- src/server/middleware/security/robot2.go
- src/server/v2.0/handler/robot.go
- src/server/v2.0/handler/robot_test.go
fixes #13980
fixes #13981
1, add the robot prefix to the audit log
2, add duration maximum checking
> fix robot issues

- src/server/v2.0/handler/scan_all.go
Correct the completed count in the metrics of the scan all to be the sum
of success, error and stopped count.
Closes #14001
> fix: correct completed in the metrics of the scan all

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.scss
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.html
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.scss
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.html
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.scss
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.ts
- src/portal/src/app/system-robot-accounts/system-robot-accounts.component.html
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Fixes #13990 
Fixes #13984
Fixes #13983
Fixes #13982
> Fix UI issues found in testing round 1

- src/portal/src/app/project/robot-account/robot-account.component.html
> Fix developer permission issue for robot account

- src/pkg/robot/dao/dao.go
- src/pkg/robot/manager.go
fixes #13985
Add sorting for listing the robot account
> fix robot list issue

- src/portal/src/app/system-robot-accounts/system-robot-util.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- tests/resources/Harbor-Pages/Robot_Account.robot
> Modify i18n text for push permission

- tests/apitests/python/library/repository.py
- tests/apitests/python/test_add_sys_label_to_tag.py
- tests/apitests/python/test_assign_role_to_ldap_group.py
- tests/apitests/python/test_copy_artifact_outside_project.py
- tests/apitests/python/test_del_repo.py
- tests/apitests/python/test_garbage_collection.py
- tests/apitests/python/test_manage_project_member.py
- tests/apitests/python/test_project_level_policy_content_trust.py
- tests/apitests/python/test_project_quota.py
- tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
- tests/apitests/python/test_push_cnab_bundle.py
- tests/apitests/python/test_push_image_with_special_name.py
- tests/apitests/python/test_push_index_by_docker_manifest.py
- tests/apitests/python/test_registry_api.py
- tests/apitests/python/test_replication_from_dockerhub.py
- tests/apitests/python/test_retention.py
- tests/apitests/python/test_robot_account.py
- tests/apitests/python/test_scan_image_artifact.py
- tests/apitests/python/test_scan_image_artifact_in_public_project.py
- tests/apitests/python/test_sign_image.py
- tests/apitests/python/test_system_level_scan_all.py
- tests/apitests/python/test_tag_crud.py
- tests/apitests/python/test_tag_immutability.py
- tests/apitests/python/test_user_view_logs.py
Signed-off-by: Dirk Mueller <dirk@dmllr.de>
> Fix repoitory -> repository typo

- tests/apitests/python/test_verify_metrics_enabled.py
- tests/apitests/python/testutils.py
- tests/ci/api_common_install.sh
- tests/robot-cases/Group0-BAT/API_DB.robot
> Add e2e test for harbor metrics

- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/test_push_cnab_bundle.py
- tests/apitests/python/test_robot_account.py
- tests/e2e-image/Dockerfile
- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Configuration_Elements.robot
- tests/resources/Harbor-Pages/GC.robot
- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/resources/Harbor-Pages/Vulnerability_Elements.robot
- tests/resources/TestCaseBody.robot
- tests/resources/Util.robot
- tests/robot-cases/Group0-BAT/BAT.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Common_GC.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
- tests/robot-cases/Group1-Nightly/Schedule.robot
- tests/robot-cases/Group3-Upgrade/data.json
- tests/robot-cases/Group3-Upgrade/verify.robot
1. Add retry for Get Statics Text keywords make this operation robust;
2. Replace image to one with slash in name for CNAB test, to cover more conditions;
3. Add replication rule deletion verification in upgrade test;
4. Add non-admin user in pull operation for proxy cache test;
5. Add verification for quota display for upgrade test;
6. Add test for large size (4G) of image replication;
7. Add test for GC schedule job.
Fixed issue: #13147, #13308, #13433, #13391, #13715, #13717, ##13916.
> Add tests and fix nightly issues

- src/pkg/scan/rest/auth/api_key_auth_test.go
- src/pkg/scan/rest/auth/basic_auth.go
- src/pkg/scan/rest/auth/basic_auth_test.go
- src/pkg/scan/rest/auth/bearer_auth.go
- src/pkg/scan/rest/auth/bearer_auth_test.go
> fix: correct Authorize of basic and berer authorizer

- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
> Improve vulnerability list page

- src/portal/src/app/config/scanner/new-scanner-modal/new-scanner-modal.component.ts
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.ts
- src/portal/src/app/system-robot-accounts/system-robot-util.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Improve add scanner and add robot page

- src/server/v2.0/handler/handler.go
- tools/swagger/templates/server/builder.gotmpl
- tools/swagger/templates/server/configureapi.gotmpl
> feat: add BeforePrepare for operation of swagger API

- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/lib/components/replication/replication.component.html
> Fix UI issue for success rate calculation

- make/photon/exporter/Dockerfile
- make/photon/exporter/entrypoint.sh
- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
- src/pkg/exporter/system_collector.go
* inject internal ca
* remove empty system info
> Metric improvement

- make/harbor.yml.tmpl
- make/photon/prepare/commands/migrate.py
- make/photon/prepare/migrations/__init__.py
- make/photon/prepare/migrations/version_2_2_0/__init__.py
- make/photon/prepare/migrations/version_2_2_0/harbor.yml.jinja
- make/photon/prepare/utils/cert.py
- make/photon/prepare/utils/notary.py
1. if san not exists then remove that cert, prepare will regenerate one
2. Add upgrade script
> Harbor upgrading for 2.2

- src/common/utils/oidc/helper.go
This patch enabled Harbor to receive the username from the /userinfo endpoint
instead of only from the ID Token.
Closes #14037
> Username from /userinfo

- src/server/v2.0/handler/robotV1.go
For the v1 api, it will not update the description of a robot account.
> fix robot v1 api update issue

- src/common/utils/oidc/helper.go
- src/core/controllers/oidc.go
> Fix a potential nil pointer issue

- src/core/api/health.go
> feat: add health checker for trivy when it's enabled

- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.scss
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/project/repository/vulnerability-scanning/result-bar-chart-component.html
- src/portal/src/app/project/repository/vulnerability-scanning/result-bar-chart.component.ts
Fixes #14068
Fixes #14066
Fixes #14063
> Fix UI bugs found in round 2 testing

- .github/workflows/build-package.yml
- make/photon/chartserver/builder
- tests/apitests/python/library/docker_api.py
- tests/ci/api_common_install.sh
- tests/ci/distro_installer.sh
> build third parties in CI

- src/pkg/exporter/project_collector.go
- src/pkg/exporter/project_collector_test.go
> Support multiple artifact type in metric

- src/pkg/exporter/project_collector.go
- src/pkg/exporter/system_collector.go
- tests/apitests/python/test_verify_metrics_enabled.py
Original type is bool, should convert it to string
> Fix metric label related things

- make/photon/prepare/models.py
- make/photon/prepare/utils/cert.py
fali ealier when there is no san
> Add sen existed check for internal cert

- src/controller/scan/base_controller.go
> fix: make a new ctx when start scan all in async

- src/pkg/exporter/project_collector.go
- tests/apitests/python/test_verify_metrics_enabled.py
from `harbor_project_usage_byte` to `harbor_project_quota_usage_byte`
> Chagne quota usage metric name

- src/server/middleware/metric/metric.go
> Fix: unkonw metrics issue

- RELEASES.md
Signed-off-by: Abigail McCarthy <mabigail@vmware.com>
This PR updates the RELEASE.md file to include some more detailed steps around the non-code pieces of a release.
> update RELEASES.md to include release checklist

- src/replication/adapter/dockerhub/adapter.go
> update adapter log level to debug

- src/portal/src/app/project/robot-account/add-robot/add-robot.component.html
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.scss
- src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.html
- src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.scss
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.html
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.scss
- src/portal/src/app/user/user.component.html
- src/portal/src/app/user/user.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Fix UI issues with label 2.2.0

- src/portal/src/app/project/robot-account/add-robot/add-robot.component.html
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.scss
- src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.html
- src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.scss
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.html
- src/portal/src/app/system-robot-accounts/new-robot/new-robot.component.scss
- src/portal/src/app/user/user.component.html
- src/portal/src/app/user/user.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> [Cherry-pick]Fix UI issues with label 2.2.0

- src/pkg/task/execution.go
Ignore the not found error in some cases
Fixes #14154
> Ignore the not found error in some cases

- src/pkg/task/execution.go
Ignore the not found error in some cases
Fixes #14154
> [cherry-pick]Ignore the not found error in some cases

- api/v2.0/swagger.yaml
- src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.ts
- src/portal/src/app/system-robot-accounts/projects-modal/projects-modal.component.spec.ts
- src/portal/src/app/system-robot-accounts/projects-modal/projects-modal.component.ts
- src/portal/src/app/system-robot-accounts/system-robot-accounts.component.ts
- src/server/v2.0/handler/model/robot.go
- src/server/v2.0/handler/robot.go
- tests/apitests/python/library/robot.py
- tests/apitests/python/test_robot_account.py
> rename permission of robot account

- src/controller/scan/base_controller.go
> fix: 404 if report not found when updating report

- make/migrations/postgresql/0050_2.2.0_schema.up.sql
For the upgrade path v1.10 - v2.1.* - v2.2.0, if user doesn't reset the GC schdule that was created in 1.10 in the v2.1,
the job parameters will keep empty in the database. The fix gives a default value for the schedule record.
fix https://github.com/goharbor/harbor/issues/14157
> fix gc migration issue

- Makefile
- make/pushimage.sh
> [Cherry-Pick 2.0.0] Reschedule docker login policy in base image build process

- make/migrations/postgresql/0050_2.2.0_schema.up.sql
For the upgrade path v1.10 - v2.1.* - v2.2.0, if user doesn't reset the GC schdule that was created in 1.10 in the v2.1,
the job parameters will keep empty in the database. The fix gives a default value for the schedule record.
> [cherry-pick] fix gc migration issue

- src/controller/scan/base_controller.go
> [Cherry pick]fix: 404 if report not found when updating report

- src/controller/replication/controller.go
- src/replication/adapter/gitlab/adapter.go
- src/replication/adapter/gitlab/adapter_test.go
- src/replication/adapter/gitlab/client.go
Recover the panic of the process of replication adapter
Fix bug of gitlab adapter
Fixes #14153
> Recover the panic of the process of replication adapter and fix bug of gitlab adapter

- api/v2.0/swagger.yaml
- src/portal/src/app/system-robot-accounts/list-all-projects/list-all-projects.component.ts
- src/portal/src/app/system-robot-accounts/projects-modal/projects-modal.component.spec.ts
- src/portal/src/app/system-robot-accounts/projects-modal/projects-modal.component.ts
- src/portal/src/app/system-robot-accounts/system-robot-accounts.component.ts
- src/server/v2.0/handler/model/robot.go
- src/server/v2.0/handler/robot.go
- tests/apitests/python/library/robot.py
- tests/apitests/python/test_robot_account.py
* rename permission of robot account
fixes #14060
> [cherry-pick] rename permission of robot account (#14150)

- make/photon/prepare/templates/nginx/nginx.http.conf.jinja
the port shouldn't be hardcode
> Fix metrics template for http mode

- src/controller/replication/controller.go
- src/replication/adapter/gitlab/adapter.go
- src/replication/adapter/gitlab/adapter_test.go
- src/replication/adapter/gitlab/client.go
Recover the panic of the process of replication adapter
Fix bug of gitlab adapter
Fixes #14153
> [cherry-pick]Recover the panic of the process of replication adapter and fix bug of gitlab adapter

- src/core/controllers/base.go
- src/core/service/token/token.go
> Escape the service name that is passed via request

- src/lib/retry_test.go
> test: fix the TestRetryUntil

- src/lib/retry_test.go
> [Cherry pick]test: fix the TestRetryUntil

- src/core/service/token/token.go
> [CP - v2.2]: Escape the service passed via request

- src/lib/orm/orm.go
- src/pkg/artifact/dao/dao.go
- src/pkg/task/dao/execution.go
- src/pkg/task/dao/task.go
Fix sql issue for querying tasks
> Fix sql issue for querying tasks

- src/lib/orm/orm.go
- src/pkg/artifact/dao/dao.go
- src/pkg/task/dao/execution.go
- src/pkg/task/dao/task.go
Fix sql issue for querying tasks
> [cherry-pick]Fix sql issue for querying tasks

- src/pkg/quota/dao/util.go
> fix quota dao sql injection

- src/pkg/quota/dao/util.go
> [cherry-pick 2.2]fix quota dao sql injection

- src/portal/package-lock.json
- src/portal/package.json
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
- src/portal/src/app/shared/components/cron-schedule/cron-schedule.component.html
- src/portal/src/app/shared/units/utils.ts
> Modify cron regex for UI

- src/portal/package-lock.json
- src/portal/package.json
- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.html
- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.scss
- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.ts
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.html
- src/portal/src/lib/utils/utils.ts
> [Cherry-pick]Modify cron regex for UI

- src/portal/src/app/base/left-side-nav/distribution/distribution-instances/distribution-instances.component.ts
- src/portal/src/app/base/left-side-nav/replication/total-replication-page.component.ts
> Fix redirection issue for registries

- tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
> Fix nightly failure for p2p case

- Makefile
- make/pushimage.sh
> Reschedule docker login policy in base image build process

- .github/workflows/CI.yml
> enlarge the CI timeout to 100 minutes

- Makefile
- make/pushimage.sh
> [Cherry-pick 2.2.0] Reschedule docker login policy in base image build process

- src/lib/orm/orm.go
- src/pkg/artifact/dao/dao.go
> [cherry-pick-2.0]Fix sql issue in artifact dao

- Makefile
- make/pushimage.sh
- tests/apitests/python/library/base.py
- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/library/sign.py
- tests/apitests/python/testutils.py
- tests/ci/api_run.sh
- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/OIDC_Auth.robot
- tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
- tests/resources/Harbor-Pages/Project-Tag-Retention.robot
- tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
- tests/resources/Nightly-Util.robot
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
- tests/robot-cases/Group1-Nightly/OIDC.robot
> [Cherry-pick 2.1.0] Reschedule docker login policy in base image build process

- src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.ts
- src/portal/src/app/base/left-side-nav/registries/endpoint.component.html
- src/portal/src/app/base/left-side-nav/registries/endpoint.component.spec.ts
- src/portal/src/app/base/left-side-nav/registries/endpoint.component.ts
- src/portal/src/app/shared/services/endpoint.service.ts
> Remove forced ng-check for registries component

- src/pkg/blob/dao/dao.go
> add sorting for list blobs

- src/lib/orm/orm.go
- src/pkg/artifact/dao/dao.go
> [cherry-pick-2.1]Fix sql issue in artifact dao

- src/core/service/token/creator.go
> fix: handle project not found when creating token

- src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
- src/portal/src/app/base/project/p2p-provider/policy/policy.component.ts
- src/portal/src/app/base/project/tag-feature-integration/immutable-tag/add-rule/add-immutable-rule.component.ts
- src/portal/src/app/base/project/tag-feature-integration/immutable-tag/immutable-tag.component.ts
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.ts
> Improve double star validator on UI

- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.scss
- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.ts
- src/portal/src/app/base/left-side-nav/replication/replication/replication.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/replication.component.ts
> Improve stop button for replication

- make/photon/nginx/Dockerfile
- make/photon/portal/Dockerfile
> add shadow for nginx and portal

- make/photon/registry/builder
Fixes #12850
This patch can fix the GC failure in the NFS v3 env, see https://github.com/distribution/distribution/pull/3309#issuecomment-783606968
> patch upstream fix for io reader

- make/photon/registry/builder
Fixes #12850
This patch can fix the GC failure in the NFS v3 env, see https://github.com/distribution/distribution/pull/3309#issuecomment-783606968
> [cherry-pick]patch upstream fix for io reader

- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
- src/portal/src/app/project/p2p-provider/policy/policy.component.ts
- src/portal/src/app/project/tag-feature-integration/immutable-tag/add-rule/add-rule.component.ts
- src/portal/src/app/project/tag-feature-integration/immutable-tag/immutable-tag.component.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.ts
> [Cherry-pick]Improve double star validator on UI

- tests/ci/api_common_install.sh
- tests/ci/api_run.sh
> Replace pybot to robot and upgrade python to v3.6

- src/portal/src/app/shared/components/label/create-edit-label/create-edit-label.component.html
- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
> Fix label color issue

- tests/ci/api_common_install.sh
> Remove deployment of python3.6

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/project.go
> feat: add sorts support for the projects listing API

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
> Support adding label to multiple artifacts

- src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.ts
> Modify usage of LDAP ping API on UI

- make/migrations/postgresql/0041_2.1.4_schema.up.sql
- src/pkg/task/execution.go
- src/pkg/task/execution_test.go
- src/pkg/task/task.go
- src/pkg/task/task_test.go
Update the execution status of retention schedule
> Update the execution status of retention schedule

- make/migrations/postgresql/0041_2.1.4_schema.up.sql
- src/pkg/task/execution.go
- src/pkg/task/execution_test.go
- src/pkg/task/task.go
- src/pkg/task/task_test.go
1. Add upgrade sql file introduced in 2.1.4
2. Minor improvement for task/execution to cover corner cases
> Add upgrade sql file introduced in 2.1.4

- src/pkg/repository/dao/dao.go
- src/pkg/repository/dao/dao_test.go
Add distinct to the sql to avoid duplicate records be returned
> fix catalog duplicate result

- make/migrations/postgresql/0051_2.2.1_schema.up.sql
- src/pkg/task/execution.go
1. Update execution status during the upgrade
2. Refine the execution sweeper
> Fix the consume too much CPU issue

- src/pkg/repository/dao/dao.go
- src/pkg/repository/dao/dao_test.go
Add distinct to the sql to avoid duplicate records be returned
> [cherry-pick] fix catalog duplicate result

- src/core/api/search.go
> fix: search charts in the projects the user owned

- .github/stale.yml
> Update exempt labels to reflect latest releases

- src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
- src/portal/src/app/base/left-side-nav/replication/replication/replication.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/replication.component.ts
- src/portal/src/app/shared/components/new-user-form/new-user-form.component.html
> Add pagination to replication rules searching

- make/migrations/postgresql/0051_2.2.1_schema.up.sql
> Update the index name

- make/migrations/postgresql/0051_2.2.1_schema.up.sql
- src/pkg/task/execution.go
1. Update execution status during the upgrade
2. Refine the execution sweeper
> [cherry-pick]Fix the consume too much CPU issue

- api/v2.0/swagger.yaml
> update notification policy disable status in swagger

- src/portal/src/app/account/sign-in/sign-in.component.html
- src/portal/src/app/account/sign-in/sign-in.component.scss
- src/portal/src/app/account/sign-in/sign-in.component.ts
- src/portal/src/app/base/account-settings/account-settings-modal.component.html
- src/portal/src/app/base/left-side-nav/user/change-password/change-password.component.html
- src/portal/src/app/base/left-side-nav/user/change-password/change-password.component.scss
- src/portal/src/app/base/left-side-nav/user/change-password/change-password.component.ts
- src/portal/src/app/base/password-setting/password-setting.component.html
- src/portal/src/app/base/password-setting/password-setting.component.scss
- src/portal/src/app/base/password-setting/password-setting.component.spec.ts
- src/portal/src/app/base/password-setting/password-setting.component.ts
- src/portal/src/app/shared/components/new-user-form/new-user-form.component.html
- src/portal/src/app/shared/components/new-user-form/new-user-form.component.scss
- src/portal/src/app/shared/components/new-user-form/new-user-form.component.ts
- src/portal/src/app/shared/components/view-token/view-token.component.html
- src/portal/src/app/shared/components/view-token/view-token.component.scss
- src/portal/src/app/shared/components/view-token/view-token.component.ts
> Add switch button to password input

- Makefile
- make/photon/Makefile
- make/photon/exporter/Dockerfile
- make/photon/exporter/Dockerfile.base
> Add base image for exporter

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/ldap.go
Related models:
LdapFailedImportUser
LdapUser
UserGroup
> Replace some x-go-type in swagger

- make/photon/prepare/templates/jobservice/config.yml.jinja
- make/photon/prepare/templates/jobservice/env.jinja
- make/photon/prepare/templates/nginx/nginx.http.conf.jinja
- make/photon/prepare/templates/nginx/nginx.https.conf.jinja
- make/photon/prepare/utils/jobservice.py
- src/jobservice/config/config.go
- src/jobservice/core/controller_test.go
- src/jobservice/runner/redis.go
- src/jobservice/runtime/bootstrap.go
- src/jobservice/worker/cworker/c_worker.go
- src/jobservice/worker/interface.go
- src/lib/metric/jobservice.go
* Add prom server on jobservice
* Enabeld configs in templates
* Enabeld jobservice metrics in nginx
> Enabled Prometheus for Jobservice

- CONTRIBUTING.md
> Update web UI start guideline

- src/portal/src/app/account/sign-in/sign-in.component.ts
- src/portal/src/app/app.component.spec.ts
- src/portal/src/app/app.component.ts
- src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
- src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.ts
- src/portal/src/app/services/skinable-config.service.spec.ts
- src/portal/src/app/services/skinable-config.service.ts
- src/portal/src/app/services/theme.ts
- src/portal/src/app/shared/components/about-dialog/about-dialog.component.html
- src/portal/src/app/shared/components/about-dialog/about-dialog.component.spec.ts
- src/portal/src/app/shared/components/about-dialog/about-dialog.component.ts
- src/portal/src/app/shared/components/global-search/global-search.component.spec.ts
- src/portal/src/app/shared/components/global-search/global-search.component.ts
- src/portal/src/app/shared/components/navigator/navigator.component.html
- src/portal/src/app/shared/components/navigator/navigator.component.ts
- src/portal/src/setting.json
> Update customizing UI style function

- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.scss
- src/portal/src/app/base/project/p2p-provider/task-list/task-list.component.html
- src/portal/src/app/base/project/p2p-provider/task-list/task-list.component.scss
> Fix css issue for task list page

- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
- src/portal/src/app/base/left-side-nav/replication/replication/replication.component.ts
- src/portal/src/app/shared/units/utils.spec.ts
- src/portal/src/app/shared/units/utils.ts
> Improve replication page

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
- src/portal/src/app/base/left-side-nav/replication/replication.module.ts
- src/portal/src/app/base/left-side-nav/replication/total-replication-page.component.spec.ts
- src/portal/src/app/base/left-side-nav/replication/total-replication-page.component.ts
- src/portal/src/app/base/project/p2p-provider/p2p-provider.module.ts
- src/portal/src/app/base/project/p2p-provider/policy/policy.component.ts
- src/portal/src/app/harbor-routing.module.ts
- src/portal/src/app/route-reuse-strategy/harbor-route-reuse-strategy.spec.ts
- src/portal/src/app/route-reuse-strategy/harbor-route-reuse-strategy.ts
- src/portal/src/app/services/event-service/event.service.spec.ts
- src/portal/src/app/services/event-service/event.service.ts
Fix #14513
Temp Env.:  https://10.185.12.35
1.Navigate from the list page  to the detail page:
to
2. And when you go back from the detail page, the list page should stay the same
> Add ruote resue strategy

- src/portal/src/app/base/project/repository/gridview/grid-view.component.scss
- src/portal/src/app/base/project/repository/repository-gridview.component.html
- src/portal/src/app/base/project/repository/repository-gridview.component.scss
- src/portal/src/app/base/project/repository/repository-gridview.component.spec.ts
- src/portal/src/app/base/project/repository/repository-gridview.component.ts
- src/portal/src/app/shared/entities/shared.const.ts
- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
> Improve grid view for repos page

- src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> [UI] Support proxy cache for docker-registry type

- src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.ts
- src/portal/src/app/base/left-side-nav/registries/endpoint.component.html
- src/portal/src/app/base/left-side-nav/registries/endpoint.component.spec.ts
- src/portal/src/app/base/left-side-nav/registries/endpoint.component.ts
> Add server driven pagination to registries page

- src/portal/src/app/base/left-side-nav/projects/statictics/statistics-panel.component.html
- src/portal/src/app/base/left-side-nav/projects/statictics/statistics-panel.component.ts
- src/portal/src/app/base/project/repository/repository-gridview.component.ts
- src/portal/src/app/services/theme.service.ts
> Fix storage display and add build timestamp

- src/portal/src/app/account/sign-in/sign-in.service.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/shared/components/global-message/message.component.ts
- src/portal/src/app/shared/components/list-repository-ro/list-repository-ro.component.ts
- src/portal/src/app/shared/units/utils.spec.ts
- src/portal/src/app/shared/units/utils.ts
> Fix pull  command issue for unlogged users

- src/portal/src/app/global-message/message.component.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/shared/list-repository-ro/list-repository-ro.component.ts
- src/portal/src/app/shared/statictics/statistics-panel.component.html
- src/portal/src/app/shared/statictics/statistics-panel.component.ts
- src/portal/src/app/sign-in/sign-in.service.ts
- src/portal/src/lib/utils/utils.spec.ts
- src/portal/src/lib/utils/utils.ts
> [Cherry-pick]Fix pull  command issue for unlogged users

- src/core/api/admin_job.go
- src/replication/policy/scheduler/scheduler.go
Ignore the not found error when trying to delete scheduled policies
fixes #14292
fixes #14548
> Ignore the not found error when trying to delete scheduled policies

- api/v2.0/swagger.yaml
- src/common/models/repo.go
- src/controller/replication/flow/mock_adapter_test.go
- src/controller/replication/transfer/image/transfer.go
- src/controller/replication/transfer/image/transfer_test.go
- src/lib/q/query.go
- src/pkg/reg/adapter/adapter.go
- src/pkg/reg/adapter/harbor/v2/adapter.go
- src/pkg/reg/adapter/harbor/v2/client.go
- src/pkg/reg/adapter/native/adapter.go
- src/server/v2.0/handler/repository.go
Improve the performance of replication by introducing a new API to check whether the blob can be mounted directly
> Improve the performance of replication

- src/controller/retention/controller.go
- src/pkg/retention/dao/retention.go
- src/pkg/retention/dao/retention_test.go
- src/pkg/retention/launcher_test.go
- src/pkg/retention/manager.go
- src/pkg/retention/manager_test.go
refactor retention dao, use `orm.FromContext(ctx)` instead of `dao.GetOrmer()`
> refactor retention dao

- src/jobservice/core/controller.go
- src/jobservice/logger/getter/db_getter.go
- return 404 code when the job log is not found
> fix(js):job log not found issue

- src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.spec.ts
- src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.spec.ts
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.ts
Additional  PR  for  # #14581
Fixes #14600
Fixes #14561
> Fix creating replication rule issue and creating proxy cache project issue

- src/server/v2.0/handler/registry.go
Fix bug of ping registry
fixes #14610
> Fix bug of ping registry

- src/pkg/immutabletag/match/rule/match.go
> fix immutable issue

- src/pkg/immutabletag/match/rule/match.go
> [cherry-pick] fix immutable issue

- src/portal/src/app/project/create-project/create-project.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> [Cherry-pick][UI]Support proxy cache for docker-registry type 

- src/jobservice/mgt/manager.go
> fix(jobservice): value out of range

- .github/workflows/build-package.yml
- .gitignore
- tests/ci/build_util.sh
> Cherry-pick 2.1.0 add build base image step in build package git action workflow

- src/jobservice/mgt/manager.go
value out of range when job count bigger than 256
Signed-off-by: vic <985695123@qq.com>
fix #14633
> CHERRY-PICK: fix(jobservice): value out of range (#14634)

- api/v2.0/legacy_swagger.yaml
- api/v2.0/swagger.yaml
- src/controller/health/checker.go
- src/controller/health/checker_test.go
- src/controller/health/controller.go
- src/controller/health/controller_test.go
- src/controller/health/model.go
- src/core/api/base.go
- src/core/api/harborapi_test.go
- src/core/main.go
- src/server/v2.0/handler/handler.go
- src/server/v2.0/handler/health.go
- src/server/v2.0/route/legacy.go
- tests/apitests/python/library/base.py
- tests/apitests/python/test_health_check.py
> Refactor health check API

- src/portal/src/app/base/project/member/add-group/add-group.component.ts
- src/portal/src/app/base/project/member/add-member/add-member.component.ts
- src/portal/src/app/base/project/member/member.component.html
- src/portal/src/app/base/project/member/member.component.spec.ts
- src/portal/src/app/base/project/member/member.component.ts
> Add pagination support to project member list page

- src/portal/src/app/base/left-side-nav/user/change-password/change-password.component.html
- src/portal/src/app/shared/components/operation/operation.component.css
- src/portal/src/app/shared/components/operation/operation.component.spec.ts
- src/portal/src/app/shared/components/operation/operation.component.ts
> Improve event panel

- .github/workflows/build-package.yml
- make/pushimage.sh
Local images should be removed since images have been pushed to
docker hub.
> Remove local goharbor images after building

- src/pkg/registry/auth/bearer/cache.go
Fix: https://github.com/goharbor/harbor/issues/13491
> fix: add precheck when registry check token expired

- src/pkg/reg/adapter/awsecr/adapter.go
fix #14069 
aws adapter catch error in checkRepository
> fix(replication) aws adapter checkRepository

- src/pkg/reg/adapter/aliacr/adapter.go
- src/pkg/reg/adapter/awsecr/adapter.go
update aliyun and aws new regions
> update aliyun and aws region

- src/replication/adapter/awsecr/adapter.go
fix #14069
aws adapter catch error in checkRepository
> [cherry-pick] fix(replication) aws adapter checkRepository 2.2.2

- src/controller/config/controller.go
- src/controller/config/test/controller_test.go
- src/lib/config/config.go
- src/lib/config/context.go
- src/lib/config/metadata/yaml/genyaml.go
- src/pkg/config/db/dao/dao.go
- src/pkg/config/db/dao/dao_test.go
- src/server/v2.0/handler/config.go
- src/testing/controller/config/controller.go
Remove deps to common/dao
Move Manager interface to config.go
Remove duplicate code and change format of dao.go
> Refine the code of config

- make/photon/prepare/Dockerfile.base
- make/photon/prepare/Pipfile
- make/photon/prepare/Pipfile.lock
pothon version of pyyaml will solve the cve
> Fix: Move pyyaml to system package

- Makefile
- make/photon/Makefile
Fixed typo in NOTARYURL variable name.
> Fixed typo in NOTARYURL variable name

- make/photon/log/Dockerfile
- make/photon/log/Dockerfile.base
Solving the root password expiring issue when build image with early base
> Move chage to base

- .github/workflows/build-package.yml
- .gitignore
- Makefile
- make/pushimage.sh
- tests/ci/build_util.sh
- tests/ci/ut_install.sh
- tests/robot-cases/Group1-Nightly/Setup_Nightly.robot
Build base image step should be in build package workflow, and local base images build by new step should be removed since images have been pushed to docker hub.
> [ Cherry-pick 2.0.0 ]Add build base image step in build package git action workflow

- src/core/service/token/creator.go
Append pull permission to push when issue a registry token
> fix registry token issue

- src/portal/src/app/base/project/p2p-provider/policy/policy.component.html
- src/portal/src/app/base/project/p2p-provider/policy/policy.component.spec.ts
- src/portal/src/app/base/project/p2p-provider/policy/policy.component.ts
> Add pagination support to p2p policy list

- src/portal/src/app/base/project/helm-chart/helm-chart-detail/list-chart-versions/helm-chart-versions-detail/helm-chart-version.component.spec.ts
- src/portal/src/app/base/project/helm-chart/helm-chart-detail/list-chart-versions/helm-chart-versions-detail/helm-chart-version.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/shared/components/label/create-edit-label/create-edit-label.component.ts
- src/portal/src/app/shared/components/label/label-piece/label-piece.component.ts
- src/portal/src/app/shared/components/label/label.component.html
- src/portal/src/app/shared/components/label/label.component.spec.ts
- src/portal/src/app/shared/components/label/label.component.ts
> Add pagination support to label list

- src/portal/src/app/base/project/helm-chart/helm-chart-list/list-charts-detail/helm-chart.component.scss
> Remove css justify-content for helm-chart list

- src/common/dao/oidc_user.go
- src/common/dao/oidc_user_test.go
- src/controller/user/controller.go
- src/pkg/oidc/secret.go
- src/pkg/oidc/testutils.go
- src/pkg/user/manager.go
- src/server/middleware/security/oidc_cli.go
- src/server/middleware/security/oidc_cli_test.go
- src/testing/controller/user/controller.go
> Remove dependencies from pkg/oidc to common/dao

- src/controller/member/controller.go
- src/pkg/usergroup/dao/dao.go
> Return 409 instead of 500 for duplicate project member

- src/portal/src/app/base/project/tag-feature-integration/tag-feature-integration.module.ts
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/retention.ts
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention-tasks/tag-retention-tasks/tag-retention-tasks.component.css
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention-tasks/tag-retention-tasks/tag-retention-tasks.component.html
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention-tasks/tag-retention-tasks/tag-retention-tasks.component.spec.ts
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention-tasks/tag-retention-tasks/tag-retention-tasks.component.ts
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.html
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.spec.ts
- src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.ts
- tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
> Refactor tag-retention page

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/config.go
- src/server/v2.0/handler/systeminfo.go
- tests/apitests/python/library/configurations.py
Add operationId for systeminfo api
Add operationId for configure api
Fixes #14617
> Add missing operationId in swagger.yaml

- src/portal/src/app/base/project/webhook/webhook.component.html
- src/portal/src/app/base/project/webhook/webhook.component.ts
> Remove loading state for new webhook button

- src/controller/replication/transfer/chart/transfer.go
Fix the failure of event based chart replication
> Fix the failure of event based chart replication

- api/v2.0/swagger.yaml
- make/migrations/postgresql/0060_2.3.0_schema.up.sql
- src/controller/replication/flow/copy.go
- src/controller/replication/flow/deletion.go
- src/controller/replication/flow/stage.go
- src/controller/replication/flow/stage_test.go
- src/controller/replication/model/model.go
- src/controller/replication/policy.go
- src/pkg/replication/model/model.go
- src/server/v2.0/handler/registry.go
- src/server/v2.0/handler/replication.go
Support specifying what part of the repository will be replaced by the provided namespace
> Refactor the replication policy destination namespace logic

- api/v2.0/swagger.yaml
- src/controller/blob/controller.go
- src/controller/blob/controller_test.go
- src/pkg/blob/dao/dao.go
- src/pkg/blob/dao/dao_test.go
- src/pkg/blob/manager.go
- src/pkg/blob/manager_test.go
- src/server/v2.0/handler/statistic.go
- src/testing/controller/blob/controller.go
- src/testing/pkg/blob/manager.go
Return the total storage consumption in the statistic API
> add storage consumption support

- src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.spec.ts
- src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts
> Use standard query to search projects by name

- api/v2.0/legacy_swagger.yaml
> Remove CVE List related items from legacy swagger doc

- src/common/models/repo.go
- src/lib/orm/metadata.go
- src/lib/orm/metadata_test.go
- src/lib/orm/query.go
- src/pkg/artifact/dao/model.go
- src/pkg/p2p/preheat/models/policy/policy.go
- src/pkg/tag/model/tag/model.go
- src/pkg/task/dao/model.go
Support specifying multiple fields for default sorting
Fixes #14433
> Support specifying multiple fields for default sorting

- src/core/middlewares/middlewares.go
> perf: skip db tx for get, head and options api requests

- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Harbor-Util.robot
- tests/resources/Helm-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group0-Util/notary-push-image.sh
- tests/robot-cases/Group0-Util/notary-util.sh
Remove ca parameter in notary command, ca has been trust in OS.
> Fix ca import location issue and statistics test issue

- src/pkg/immutable/match/rule/match.go
> fixes immutable rule issue

- make/migrations/postgresql/0050_2.2.0_schema.up.sql
> [Cherry pick]fix: change art_size to bigint in migrations

- .github/workflows/build-package.yml
- tests/ci/build_util.sh
> Add build package workflow in git action of Harbor V1.10

- src/lib/orm/orm.go
Adds a debug environment variable to enable tracing SQL statements to aid in troubleshooting slow SQL calls
> feat: add ORM_DEBUG option to enable sql logging

- src/chartserver/cache.go
- src/chartserver/handler_proxy_traffic_test.go
- src/common/api/base.go
- src/common/dao/project.go
- src/common/utils/test/database.go
- src/common/utils/uaa/client.go
- src/common/utils/uaa/fake_client.go
- src/controller/member/controller.go
- src/core/api/chart_repository.go
- src/core/auth/authenticator.go
- src/core/auth/authproxy/auth.go
- src/core/auth/uaa/uaa.go
- src/core/main.go
- src/core/service/token/creator.go
- src/core/utils/response_handlers.go
- src/pkg/member/dao/dao.go
- src/pkg/notifier/notifier.go
- src/pkg/reg/adapter/aliacr/adapter.go
- src/pkg/reg/adapter/artifacthub/consts.go
- src/pkg/reg/adapter/awsecr/adapter.go
- src/pkg/reg/adapter/awsecr/adapter_test.go
- src/pkg/reg/adapter/dtr/adapter.go
- src/pkg/reg/adapter/githubcr/adapter.go
- src/pkg/retention/dep/client.go
- src/pkg/token/claims/robot/robot.go
- src/registryctl/client/client.go
- src/server/middleware/quota/quota_test.go
- src/server/middleware/repoproxy/proxy.go
> Error string should not be capitalized

- src/pkg/p2p/preheat/models/notification/notification.go
- src/pkg/p2p/preheat/provider/kraken.go
- src/pkg/p2p/preheat/provider/mock.go
Move the notification to preheat models
> refactor preheat model

- RELEASES.md
Signed-off-by: Abigail McCarthy <mabigail@vmware.com>
> Update support matrix to include 2.2

- src/server/v2.0/handler/project.go
> fix: requires authn for apis of project scanner

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/retention.go
close #14118
Add DELETE route for tag retention policy API
> fix(retention) add delete retention API

- src/core/api/usergroup.go
Check create/update permission on rbac.ResourceUserGroup
> Check permission for user group api

- src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.html
- src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.scss
- src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.spec.ts
- src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Support searching quota by project name

- api/v2.0/swagger.yaml
> fix: disable x-omitempty for repo_count and chart_count

- src/portal/src/app/account/sign-in/sign-in.component.spec.ts
- src/portal/src/app/account/sign-in/sign-in.component.ts
- src/portal/src/app/base/left-side-nav/projects/statictics/statistics-panel.component.ts
- src/portal/src/app/base/project/helm-chart/helm-chart-detail/chart-detail.component.html
- src/portal/src/app/base/project/helm-chart/helm-chart-detail/chart-detail.component.scss
- src/portal/src/app/base/project/helm-chart/helm-chart-detail/list-chart-versions/list-chart-versions.component.html
- src/portal/src/app/base/project/helm-chart/helm-chart-detail/list-chart-versions/list-chart-versions.component.scss
- src/portal/src/app/base/project/project-detail/project-detail.component.html
- src/portal/src/app/base/project/project-detail/project-detail.component.scss
- src/portal/src/app/base/project/project-detail/project-detail.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.html
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.scss
- src/portal/src/app/base/project/repository/artifact/artifact-summary.component.html
- src/portal/src/app/base/project/repository/artifact/artifact-summary.component.scss
- src/portal/src/app/base/project/repository/repository-gridview.component.ts
- src/portal/src/app/base/project/summary/summary.component.html
- src/portal/src/app/base/project/summary/summary.component.scss
- src/portal/src/app/base/project/summary/summary.component.spec.ts
- src/portal/src/app/base/project/summary/summary.component.ts
- src/portal/src/app/shared/entities/shared.const.ts
- src/portal/src/app/shared/services/permission.service.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Template Env: https://10.185.12.35
Changed:
UI  Design: https://www.figma.com/proto/cPY9Lh8LbIQawAJSGmi1KA/Harbor-v2.0?page-id=0%3A1&node-id=1%3A2452&viewport=4801%2C8439%2C1.0458333492279053&scaling=min-zoom
Fixes #14805
> Update project summary page

- src/core/api/chart_repository.go
Add condition to handle chartname parts is 0 and 1
> Fix webhook parse chartname panic

- src/controller/p2p/preheat/enforcer.go
- src/controller/p2p/preheat/enforcer_test.go
- src/controller/scan/base_controller.go
- src/controller/scan/controller.go
- src/pkg/scan/report/report.go
- src/pkg/scan/report/summary.go
- src/pkg/scan/report/summary_test.go
- src/pkg/scan/vuln/report.go
- src/pkg/scan/vuln/report_test.go
- src/pkg/scan/vuln/summary.go
- src/pkg/scan/vuln/summary_test.go
- src/pkg/scan/vuln/util.go
- src/pkg/scan/vuln/util_test.go
- src/server/middleware/vulnerable/vulnerable.go
- src/server/middleware/vulnerable/vulnerable_test.go
- src/server/v2.0/handler/artifact.go
- src/testing/controller/scan/controller.go
> refactor: remove allowlist in GetSummary of scan controller

- .dockerignore
- .spectral.yaml
- Makefile
- api/v2.0/swagger.yaml
- src/portal/src/app/base/left-side-nav/gc-page/gc/gc.component.ts
- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.ts
- src/portal/src/app/services/routing-resolvers/replication-tasks-routing-resolver.service.ts
- src/portal/src/app/shared/components/label/create-edit-label/create-edit-label.component.ts
- src/portal/src/app/shared/components/label/label.component.ts
- tools/spectral/Dockerfile
- tools/spectral/functions/requireRequestId.js
> ci: lint the swagger file

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/left-side-nav/projects/projects.component.scss
- src/portal/src/app/base/left-side-nav/projects/statictics/statistics-panel.component.html
- src/portal/src/app/base/left-side-nav/projects/statictics/statistics-panel.component.scss
- src/portal/src/app/base/project/project-detail/project-detail.component.html
- src/portal/src/app/base/project/tag-feature-integration/tag-feature-integration.component.html
- src/portal/src/app/base/project/tag-feature-integration/tag-feature-integration.component.scss
- src/portal/src/app/shared/components/push-image/push-image.scss
- src/portal/src/app/shared/units/utils.spec.ts
- src/portal/src/app/shared/units/utils.ts
- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
> Improve css style

- src/pkg/reg/dao/dao_test.go
- src/pkg/reg/dao/model.go
- src/pkg/reg/manager.go
Update the field name of registry mode
> Update the field name of registry model

- src/server/v2.0/handler/user.go
> Fail with 401 for GET .../users/current/permissions

- make/migrations/postgresql/0060_2.3.0_schema.up.sql
- src/pkg/artifact/dao/dao.go
Improve the performance of artifact related APIs by adding indexes and refactoring sql logic
Closes #13890 #14813 #14814
> Improve the performance of artifact related APIs

- src/pkg/repository/dao/dao.go
Close：https://github.com/goharbor/harbor/issues/14819
> fix: change sql to improve the performance of catalog api

- make/photon/db/docker-entrypoint.sh
> pg upgrade failure handling

- src/lib/orm/query.go
Set null list when or list is nil in query
> Set null list when or list is nil in query

- src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.html
- src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.ts
- src/portal/src/app/base/left-side-nav/projects/projects.component.ts
> Remove redundant sorting code for list projects

- api/v2.0/swagger.yaml
- src/lib/config/metadata/yaml/genyaml.go
- src/server/v2.0/handler/config.go
Update the genyaml to generate the configurations type
Add toCfgMap in config handler
> Change configurations in swagger.yaml make it more readable

- .github/workflows/build-package.yml
- Makefile
- tests/apitests/python/library/base.py
- tests/apitests/python/library/webhook.py
- tests/apitests/python/test_webhook_crud.py
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/robot-cases/Group3-Upgrade/feature_map.json
- tests/robot-cases/Group3-Upgrade/prepare.py
> Fix build base workflow issues

- src/server/v2.0/handler/gc.go
For reference, see https://github.com/goharbor/harbor/issues/14917.
> fix nil map assignment in gc handler

- tests/resources/Harbor-Pages/HomePage.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/WebUI.robot
> Remove customize case from common test

- make/migrations/postgresql/0060_2.3.0_schema.up.sql
Fix bug of migration sql for replication policy
> Fix bug of migration sql for replication policy

- make/harbor.yml.tmpl
- make/photon/prepare/commands/migrate.py
- make/photon/prepare/migrations/__init__.py
- make/photon/prepare/migrations/version_2_3_0/__init__.py
- make/photon/prepare/migrations/version_2_3_0/harbor.yml.jinja
no new config item added. harbor.yml keep the same as last version
> Add upgrade script for harbor 2.3

- src/controller/replication/flow/copy.go
- src/controller/replication/flow/deletion.go
- src/controller/replication/flow/deletion_test.go
- src/controller/replication/flow/stage.go
- src/controller/replication/flow/stage_test.go
- src/pkg/reg/adapter/dockerhub/adapter.go
- src/pkg/reg/adapter/dockerhub/adapter_test.go
- src/pkg/reg/adapter/harbor/base/adapter.go
- src/pkg/reg/adapter/harbor/base/adapter_test.go
- src/pkg/reg/model/registry.go
Declare the capability of supported repository path component for registries
fixes #14981
fixes #14980
> Declare the capability of supported repository path component for registries

- src/portal/src/app/base/account-settings/account-settings-modal.component.html
- src/portal/src/app/base/account-settings/account-settings-modal.component.scss
- src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
- src/portal/src/app/base/left-side-nav/config/email/config-email.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
- src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
- src/portal/src/app/base/project/project-detail/project-detail.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/base/project/repository/repository-gridview.component.ts
- src/portal/src/app/services/event-service/event.service.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Fixes: #14988
Fixes: #14978
Fixes: #14975
Fixes: #14973
Fixes: #14970
> Fix ui issues found in testing day

- src/core/api/usergroup.go
Check create/update permission on rbac.ResourceUserGroup
> (cherry-pick) Check permission for user group api

- Makefile
- make/photon/db/Dockerfile.pg96
Add parameter BUILDARCH for make file. DB base builds pg96 for x86_64 only
> add build arch parameter in Makefile

- src/pkg/repository/dao/dao.go
Closes: https://github.com/goharbor/harbor/issues/14819
> (cherry-pick)fix: change sql to improve the performance of catalog api

- make/migrations/postgresql/0053_2.2.3_schema.up.sql
> perf: add 2.2.3 schema up sql to master

- make/photon/db/docker-entrypoint.sh
fixes #15000
It needs to double confirm that old pg is stopped before migration
> fix db issue on helm upgrade

- src/portal/package-lock.json
- src/portal/package.json
> Fix critical CVEs for ui packages

- make/migrations/postgresql/0053_2.2.3_schema.up.sql
- src/pkg/artifact/dao/dao.go
Improve the performance of artifact related APIs by adding indexes and refactoring sql logic
Closes #13890 #14813 #14814
> (cherry-pick)Improve the performance of artifact related APIs

- src/pkg/p2p/preheat/provider/client/http_client.go
- src/pkg/p2p/preheat/provider/client/http_client_test.go
- src/pkg/p2p/preheat/provider/dragonfly.go
- src/pkg/p2p/preheat/provider/dragonfly_test.go
- src/pkg/p2p/preheat/provider/mock.go
Signed-off-by: yunkunrao <yunkunrao@gmail.com>
This PR fix issue #14913
> Fix dragonfly preheat error.

- make/photon/chartserver/Dockerfile
- make/photon/core/Dockerfile
- make/photon/jobservice/Dockerfile
- make/photon/nginx/Dockerfile
- make/photon/portal/Dockerfile
- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
- make/photon/registry/Dockerfile
- make/photon/registryctl/Dockerfile
- make/photon/trivy-adapter/Dockerfile
- tests/generateCerts.sh
> Add IPv6 support

- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
> Fix: Remove v6 format of harbor

- make/photon/db/docker-entrypoint.sh
> fix: listen to 5443 when clean unexpected status of db

- make/photon/db/docker-entrypoint.sh
> [Cherry pick]fix: listen to 5443 when clean unexpected status of db

- src/portal/src/app/base/account-settings/account-settings-modal.component.html
- src/portal/src/app/base/account-settings/account-settings-modal.component.scss
- src/portal/src/app/base/account-settings/account-settings-modal.component.ts
- src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/project/project-detail/project-detail.component.html
- src/portal/src/app/shared/components/global-message/message.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> [Cherry-pick]Fix UI issues found in round-2 testing day

- src/portal/src/app/base/account-settings/account-settings-modal.component.html
- src/portal/src/app/base/account-settings/account-settings-modal.component.scss
- src/portal/src/app/base/account-settings/account-settings-modal.component.ts
- src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/project/project-detail/project-detail.component.html
- src/portal/src/app/shared/components/global-message/message.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Fixes #15079
Fixes #15077
Fixes #15071
Fixes #15069
Fixes #15059
> Fix UI issues found in round-2 testing day

- src/controller/event/handler/internal/artifact.go
- src/controller/event/handler/internal/util.go
- src/controller/event/handler/internal/util_test.go
- src/controller/event/handler/webhook/scan/scan.go
- src/controller/scan/base_controller.go
- src/controller/scan/base_controller_test.go
- src/controller/scan/callback.go
- src/controller/scan/options.go
- src/server/v2.0/handler/scan.go
> fix: supply the latest tag of artifact to scan request

- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Replication_Elements.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Fix replication namespace level issue

- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
- tests/resources/Nightly-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Remove workround for docker20 adaptation

- src/controller/event/handler/internal/artifact.go
- src/controller/event/handler/internal/util.go
- src/controller/event/handler/internal/util_test.go
- src/controller/event/handler/webhook/scan/scan.go
- src/controller/scan/base_controller.go
- src/controller/scan/base_controller_test.go
- src/controller/scan/callback.go
- src/controller/scan/options.go
- src/server/v2.0/handler/scan.go
> [Cherry pick]fix: supply the latest tag of artifact to scan request

- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
- tests/resources/Nightly-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> [ Cherry pick 2.3 ]Remove workaround for docker20 adaptation

- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Replication_Elements.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
1. Fix replication namespace level issue;
2. Add UI test for replicaiton flattening.
> [ Cherry pick 2.3 ] Add UI test for replicaiton flattening

- make/harbor.yml.tmpl
- make/photon/prepare/migrations/version_2_3_0/__init__.py
- make/photon/prepare/migrations/version_2_3_0/harbor.yml.jinja
- make/photon/prepare/templates/nginx/nginx.http.conf.jinja
- make/photon/prepare/templates/nginx/nginx.https.conf.jinja
- make/photon/prepare/templates/registry/config.yml.jinja
> [Cherry pick]perf: configurations for perf improvement

- tests/ci/distro_installer.sh
- tests/resources/TestCaseBody.robot
> Increase retry times for checking replication result

- .github/workflows/CI.yml
- CONTRIBUTING.md
- src/portal/package.json
> Bump up UI version to v2.4.0

- api/swagger.yaml
- api/v2.0/legacy_swagger.yaml
- src/portal/src/app/dev-center/dev-center-base.ts
- src/portal/src/app/dev-center/dev-center.component.ts
- src/portal/src/app/services/intercept-http.service.ts
> Enhance swagger UI

- src/portal/src/app/base/left-side-nav/config/email/config-email.component.html
> Fix css bug for disabled checkbox

- .github/workflows/build-package.yml
- make/photon/chartserver/builder
- tests/ci/api_common_install.sh
- tests/ci/distro_installer.sh
> enable build bin for v1.10

- Makefile
- make/pushimage.sh
> add docker access to build base in make

- make/photon/prepare/Dockerfile.base
- make/photon/prepare/Pipfile
- make/photon/prepare/Pipfile.lock
replace some python packages to photon one
> Enhance: prepare package management issue

- .github/workflows/build-package.yml
> remove migrator from offline install

- src/portal/src/app/shared/components/operation/operate.ts
- src/portal/src/app/shared/components/operation/operation.component.spec.ts
- src/portal/src/app/shared/components/operation/operation.component.ts
> Improve event log component

- src/portal/src/app/shared/entities/shared.const.ts
- src/portal/src/app/shared/units/utils.spec.ts
- src/portal/src/app/shared/units/utils.ts
> [Cherry-pick]Change quota unit to Mebibyte

- src/portal/src/app/shared/entities/shared.const.ts
- src/portal/src/app/shared/units/utils.spec.ts
- src/portal/src/app/shared/units/utils.ts
> Change quota unit to Mebibyte

- api/v2.0/swagger.yaml
Fixes #15206
Includes:StringConfigItem, BoolConfigItem, IntegerConfigItem
> Change XXXConfigItem cannot be omitted when empty

- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/gc/util.go
Fixes #15197
To handle the blob & manifest deletion error, add 1 minute retry.
> add retry for blob & manifest deletion in GC

- src/portal/src/app/account/sign-in/sign-in.component.html
- src/portal/src/app/account/sign-in/sign-in.component.scss
- src/portal/src/app/account/sign-in/sign-in.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
new UI:
UI  design:
https://www.figma.com/proto/cPY9Lh8LbIQawAJSGmi1KA/Harbor-v2.0?page-id=0%3A1&node-id=2419%3A79553&viewport=4205%2C10144%2C1&scaling=min-zoom
Fixes #14968
> Improve login page for OIDC

- tests/resources/Harbor-Pages/HomePage.robot
- tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Common_GC.robot
- tests/robot-cases/Group1-Nightly/OIDC.robot
> Fix nightly test failures broke by UI change

- src/server/v2.0/handler/preheat.go
> fix(p2p): fix p2p create policy permission

- src/pkg/repository/model/model.go
Signed-off-by: elihe <elihe@tencent.com>
> Fix commentline typos in src/pkg/repository/model/model.go

- src/lib/patterns.go
- src/lib/patterns_test.go
- src/server/middleware/artifactinfo/artifact_info.go
- src/server/middleware/artifactinfo/artifact_info_test.go
fixes #15252
Give 404 for invalid digest when to get/head manifest
> fix conformance failure

- tests/ci/conformance_test.sh
set the cross mount namespace for conformance test, the default vaule cannot pass the reponame validation.
> fix cross mount conformance test

- .github/workflows/CI.yml
- .github/workflows/build-package.yml
- .github/workflows/conformance_test.yml
- CONTRIBUTING.md
- Makefile
- make/photon/chartserver/builder
- make/photon/registry/Dockerfile.binary
- make/photon/trivy-adapter/Dockerfile.binary
- make/photon/trivy-adapter/builder.sh
- src/go.mod
- tests/ci/distro_installer.sh
- tests/ci/ut_run.sh
- tools/mockery/Dockerfile
> bump up go version to 1.16

- src/portal/src/app/base/left-side-nav/user/user.component.html
- src/portal/src/app/base/left-side-nav/user/user.component.ts
> Update UI to support deleting OIDC users

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Fix replication test issue in nightly

- tests/robot-cases/Group1-Nightly/DB.robot
> Remove useless keyword for db auth mode test

- .buildbaselog
- .github/workflows/build-package.yml
> Add trigger file for building base

- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/gc/util.go
Fixes #15197
To handle the blob & manifest deletion error, add 1 minute retry.
> [cherry pick]add retry for blob & manifest deletion in GC

- tests/resources/Harbor-Pages/OIDC_Auth.robot
- tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot
- tests/robot-cases/Group1-Nightly/OIDC.robot
Related UI PR: #15305
Related back-end PR: #15247 
> Add a case of deleting an OIDC user

- src/portal/src/app/oidc-onboard/oidc-onboard.component.html
- src/portal/src/app/oidc-onboard/oidc-onboard.component.scss
> Fix style issue for oidc-onbord component

- src/pkg/reg/adapter/artifacthub/adapter_test.go
- src/pkg/reg/adapter/dockerhub/adapter_test.go
- src/pkg/reg/adapter/huawei/huawei_adapter_test.go
- src/pkg/reg/adapter/huawei/image_registry_test.go
- src/pkg/reg/adapter/quay/adapter_test.go
- src/pkg/reg/adapter/tencentcr/adapter.go
- src/pkg/reg/adapter/tencentcr/adapter_test.go
> fix: update adapter ut (mock http requests)

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/robot-cases/Group3-Upgrade/prepare.py
> Fix nightly ca header issue

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Common_GC.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
- tests/robot-cases/Group3-Upgrade/prepare.py
> cherry-pick 2.3 fix nightly issue caused by gui change of storage unit

- src/portal/src/app/services/event-service/event.service.spec.ts
- src/portal/src/app/services/event-service/event.service.ts
> Improve event service

- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.html
- src/portal/src/app/shared/pipes/harbor-datetime.pipe.ts
> Handle invalid date for HarborDatePipe

- .gitignore
- src/portal/docker-build/Dockerfile
- src/portal/docker-build/README.md
- src/portal/docker-build/nginx.conf.example
> Add docker build to deploy Harbor UI for testing

- .github/workflows/build-package.yml
> Modify GCP repo in build package workflow

- make/photon/portal/Dockerfile
> update node version for portal container

- src/portal/src/i18n/lang/pt-br-lang.json
Signed-off-by: Gustavo Raphael Stein <grstein.ramone@gmail.com>
> Fixes bizarre translation for CLI in pt-br.

- src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.ts
- src/portal/src/app/shared/units/utils.ts
> Improve  getChanges function for edit registries compoment

- src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.ts
- src/portal/src/app/shared/units/utils.ts
> [Cherry-pick] Improve getChanges function for edit registries compoment

- src/pkg/oidc/helper.go
- src/pkg/oidc/helper_test.go
Signed-off-by: Kevin Schu <kevin.schu@aoe.com>
> [CP-v2.3]: if username is not available in remote, fall back to username from token

- src/portal/src/app/base/project/member/member.component.html
- src/portal/src/app/base/project/member/member.component.spec.ts
- src/portal/src/app/base/project/member/member.component.ts
> Disable add group button for LDAP project admin

- api/v2.0/swagger.yaml
- src/controller/replication/model/model.go
- src/pkg/reg/adapter/aliacr/adapter.go
- src/pkg/reg/adapter/dockerhub/adapter.go
- src/pkg/reg/filter/artifact.go
- src/pkg/reg/filter/resource_test.go
- src/pkg/reg/model/policy.go
- src/pkg/reg/util/pattern_test.go
- src/server/v2.0/handler/replication.go
add exclude decoration for replication policy api to fix issue #13220
> feat(replication) add exclude decoration in policy

- src/portal/src/app/base/left-side-nav/replication/replication.ts
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
- src/portal/src/app/shared/services/interface.ts
changed point:
related back end PR : https://github.com/goharbor/harbor/pull/15344
> Support excluding rule for adding a replication rule

- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
> Improve css style for autofill input

- src/portal/src/app/base/project/helm-chart/helm-chart-detail/helm-chart.service.ts
> [Cherry-pick]Fix chart download issue

- src/portal/src/app/base/project/helm-chart/helm-chart-detail/helm-chart.service.ts
> Fix chart download issue

- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/gc/util.go
> fix gc delete manifest log issue

- .github/workflows/CI.yml
- .github/workflows/build-package.yml
- .github/workflows/conformance_test.yml
- CONTRIBUTING.md
- Makefile
- make/photon/chartserver/builder
- make/photon/registry/Dockerfile.binary
- make/photon/trivy-adapter/Dockerfile.binary
- make/photon/trivy-adapter/builder.sh
- tests/ci/distro_installer.sh
> bump up go to v1.16.7

- src/controller/proxy/controller.go
- src/controller/proxy/remote.go
- src/server/middleware/repoproxy/proxy.go
> refactor: initialize the remote helper using ctx from http request

- api/v2.0/swagger.yaml
- src/common/rbac/const.go
- src/common/rbac/project/rbac_role.go
- src/common/rbac/system/policies.go
- src/controller/event/handler/init.go
- src/controller/event/metadata/scan.go
- src/controller/event/metadata/scan_test.go
- src/controller/event/topic.go
- src/controller/scan/base_controller.go
- src/controller/scan/base_controller_test.go
- src/controller/scan/controller.go
- src/pkg/notification/notification.go
- src/pkg/scan/job.go
- src/pkg/scan/job_test.go
- src/pkg/scan/report/summary.go
- src/pkg/scan/vuln/util.go
- src/pkg/scan/vuln/util_test.go
- src/pkg/task/dao/execution.go
- src/pkg/task/dao/execution_test.go
- src/portal/src/app/base/project/webhook/webhook.service.ts
- src/server/v2.0/handler/scan.go
- src/server/v2.0/handler/scan_all.go
- src/server/v2.0/handler/scan_all_test.go
- src/server/v2.0/handler/scan_test.go
- src/testing/controller/scan/controller.go
> Add stop scan a particular artifact & stop scan all

- src/lib/errors/stack.go
Signed-off-by: Junyoung, Sung <junyoung.sung@naverlabs.com>
> Fix typo maxDeepth -> maxDepth

- src/portal/src/app/base/left-side-nav/replication/replication/replication.component.ts
- src/portal/src/app/base/project/robot-account/robot-account.component.ts
> Clear selected row after refreshing for replication task list component

- api/v2.0/swagger.yaml
- make/migrations/postgresql/0070_2.4.0_schema.up.sql
- src/controller/replication/flow/copy.go
- src/controller/replication/model/model.go
- src/controller/replication/transfer/chart/transfer.go
- src/controller/replication/transfer/chart/transfer_test.go
- src/controller/replication/transfer/image/transfer.go
- src/controller/replication/transfer/image/transfer_test.go
- src/controller/replication/transfer/iothrottler.go
- src/controller/replication/transfer/transfer.go
- src/jobservice/job/impl/replication/replication.go
- src/jobservice/job/impl/replication/replication_test.go
- src/pkg/replication/model/model.go
- src/server/v2.0/handler/replication.go
implement a simple bandwidth limiter for replication job.
refer proposal https://github.com/goharbor/community/pull/163
close https://github.com/goharbor/harbor/issues/13194
> limit replication bandwidth

- src/server/v2.0/handler/scan_all.go
- src/server/v2.0/handler/scan_all_test.go
> fix: update context to "makeCtx    func() context.Context"

- tests/resources/Harbor-Pages/Project-Helmcharts.robot
- tests/resources/Harbor-Pages/Project-Helmcharts_Elements.robot
- tests/resources/SeleniumUtil.robot
- tests/resources/TestCaseBody.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Chartmuseum.robot
- tests/test-engine-image/Dockerfile.common
- tests/test-engine-image/Dockerfile.ui_test
Signed-off-by: YangJiao <jiaoya@vmware.com>
> Add TestCase to download helmchart from UI

- src/portal/src/app/base/left-side-nav/replication/replication.ts
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.spec.ts
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
- src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.spec.ts
- src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.spec.ts
- src/portal/src/app/base/left-side-nav/replication/replication/replication.component.spec.ts
- src/portal/src/app/shared/services/interface.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Related back-end PR #15537
Changed points:
> Add bandwidth input to adding replication rule

- make/photon/trivy-adapter/Dockerfile.base
Signed-off-by: YangJiao <jiaoya@vmware.com>
> Fix file-5.30-2.ph2.x86_64 and toybox-0.7.3-6.ph2.x86_64 file conflict

- src/controller/p2p/preheat/enforcer.go
- src/controller/p2p/preheat/enforcer_test.go
> refactor: using ctx from http request for credMaker of preheat enforcer

- make/harbor.yml.tmpl
- make/photon/prepare/commands/migrate.py
- make/photon/prepare/migrations/__init__.py
- make/photon/prepare/migrations/version_2_4_0/__init__.py
- make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja
> Add migration script for harbor 2.4

- make/migrations/postgresql/0070_2.4.0_schema.up.sql
- src/controller/quota/controller.go
- src/controller/quota/controller_test.go
- src/controller/quota/util_test.go
- src/lib/orm/error.go
- src/lib/retry/retry.go
- src/lib/retry/retry_test.go
- src/pkg/quota/dao/dao.go
- src/pkg/quota/dao/dao_test.go
- src/pkg/quota/dao/model.go
- src/pkg/quota/manager.go
- src/pkg/quota/models/quota.go
- src/testing/pkg/quota/manager.go
Using optimistic lock to implement the quota.
> refactor: implement a lock free quota

- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Common.robot
Signed-off-by: YangJiao <jiaoya@vmware.com>
> Add Go To Harbor Api Page TestCase

- .buildbaselog
> Update photon2.0 to solve the urllib3 CVE

- src/portal/src/app/base/project/project-log/audit-log.component.ts
> Remove push option for project access log component

- .buildbaselog
> Refresh the Base image before release V2.3.3

- src/portal/docker-build/nginx.conf.example
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
- src/portal/src/app/shared/components/about-dialog/about-dialog.component.html
> Improve style for add replication rule component

- .buildbaselog
> Refresh base image

- src/controller/proxy/controller.go
- src/controller/proxy/remote.go
- src/server/middleware/repoproxy/proxy.go
> [Cherry pick]refactor: initialize the remote helper using ctx from http request

- src/controller/p2p/preheat/enforcer.go
- src/controller/p2p/preheat/enforcer_test.go
> [Cherry pick]refactor: using ctx from http request for credMaker of preheat enforcer

- src/pkg/oidc/helper.go
> Do not print warning message if group claim is empty

- src/go.mod
- src/go.sum
- src/jobservice/common/utils/utils.go
- src/jobservice/common/utils/utils_test.go
- src/vendor/github.com/asaskevich/govalidator/.travis.yml
- src/vendor/github.com/asaskevich/govalidator/CODE_OF_CONDUCT.md
- src/vendor/github.com/asaskevich/govalidator/LICENSE
- src/vendor/github.com/asaskevich/govalidator/README.md
- src/vendor/github.com/asaskevich/govalidator/arrays.go
- src/vendor/github.com/asaskevich/govalidator/converter.go
- src/vendor/github.com/asaskevich/govalidator/go.mod
- src/vendor/github.com/asaskevich/govalidator/numerics.go
- src/vendor/github.com/asaskevich/govalidator/patterns.go
- src/vendor/github.com/asaskevich/govalidator/types.go
- src/vendor/github.com/asaskevich/govalidator/validator.go
- src/vendor/modules.txt
Signed-off-by: yxxhero <aiopsclub@163.com>
Fixed: https://github.com/goharbor/harbor/issues/15541
I've seen many programmers use the net/url.Parse() function returning error message as the way to validate URL. However, it is NOT the right way and why you should use a better URL validator, such as govalidator package to validate a URL.
This method has many weaknesses and if you change the str value to d or wwwsocketloopcom, net/url.Parse() function will still pass the broken URL as valid. This is NOT the right way to validate URL.
> add unittest for jobservice/common/utils package and fix a issue for IsValidURL

- src/portal/src/app/base/project/project-detail/project-detail.component.html
- src/portal/src/app/base/project/project-detail/project-detail.component.scss
- src/portal/src/app/base/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/app/base/project/webhook/add-webhook-form/add-webhook-form.component.scss
- src/portal/src/app/base/project/webhook/add-webhook/add-webhook.component.scss
> Improve css style for project detail and add webhook components

- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.html
- src/portal/src/app/base/project/robot-account/robot-account.component.html
- src/portal/src/app/shared/components/filter/filter.component.html
- src/portal/src/app/shared/components/filter/filter.component.scss
- src/portal/src/app/shared/components/filter/filter.component.spec.ts
- src/portal/src/app/shared/components/filter/filter.component.ts
> Auto-focus for filter component

- src/portal/src/app/account/sign-in/sign-in.component.html
- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
- src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
- src/portal/src/app/base/left-side-nav/gc-page/gc/gc-history/gc-history.component.html
- src/portal/src/app/base/left-side-nav/interrogation-services/scanner/config-scanner.component.html
- src/portal/src/app/base/left-side-nav/registries/endpoint.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
- src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.html
- src/portal/src/app/base/project/p2p-provider/task-list/task-list.component.html
- src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-bar-chart-component.html
- src/portal/src/app/base/project/repository/repository-gridview.component.html
- src/portal/src/app/shared/components/about-dialog/about-dialog.component.html
> Improve routing links

- src/portal/src/app/base/project/robot-account/robot-account.component.html
> Fix lagecy robot edit issue

- src/server/v2.0/handler/robot.go
fixes #15690, for the legacy robot, update is denied.
> fix legacy robot edit issue

- make/migrations/postgresql/0061_2.3.4_schema.up.sql
- src/common/dao/base.go
- src/common/dao/testutils.go
- src/common/models/base.go
- src/common/models/user.go
- src/controller/project/controller_test.go
- src/controller/user/controller.go
- src/core/auth/ldap/ldap_test.go
- src/core/auth/uaa/uaa_test.go
- src/core/main.go
- src/pkg/member/dao/dao_test.go
- src/pkg/user/dao/dao.go
- src/pkg/user/dao/dao_test.go
- src/pkg/user/dao/user.go
- src/pkg/user/manager.go
- src/pkg/user/models/model.go
- src/server/v2.0/handler/model/user.go
- src/server/v2.0/handler/user.go
- src/testing/controller/user/controller.go
- src/testing/pkg/user/dao/dao.go
- src/testing/pkg/user/manager.go
Define user.Email as sql.NullString
Fixes #10400
> Allow empty email attribute for ldap/oidc user

- src/pkg/ldap/ldap.go
> Check empty ldap attributes value

- .buildbaselog
> Refresh the Base image

- tests/apitests/python/library/helm.py
- tests/apitests/python/test_push_chart_by_helm3.7_chart_cli.py
- tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
- tests/apitests/python/testutils.py
- tests/ci/api_run.sh
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/test-engine-image/Dockerfile.api_test
- tests/test-engine-image/Dockerfile.common
> Add test cases helm3.7 CLI push in python test

- tests/robot-cases/Group1-Nightly/Common.robot
- tests/test-engine-image/Dockerfile.common
- tests/test-engine-image/Dockerfile.ui_test
> Add wasm-to-oci test cases for harbor push and pull

- api/v2.0/swagger.yaml
- src/lib/config/config.go
- src/server/v2.0/handler/config.go
- src/server/v2.0/handler/model/quota.go
- src/server/v2.0/handler/model/resource_list.go
- src/server/v2.0/handler/project.go
- src/server/v2.0/handler/quota.go
- src/server/v2.0/handler/quota_test.go
> fix: remove x-go-type in swagger.yaml

- tests/test-engine-image/build_include_case.sh
> [Cherry-pick]Add e2e image include test case in 2.3

- tests/test-engine-image/build_include_case.sh
> [Cherry-pick]Add e2e image include test case in 2.4

- src/common/http/client.go
- src/pkg/reg/adapter/harbor/base/adapter.go
- src/pkg/reg/adapter/harbor/base/adapter_test.go
- src/pkg/reg/adapter/harbor/base/client.go
Fix: https://github.com/goharbor/harbor/issues/15894
> fix(replication): list projects before replicate

- src/portal/src/i18n/lang/de-de-lang.json
Signed-off-by: sluetze <13255307+sluetze@users.noreply.github.com>
> updated german translation for 2.4

- src/portal/src/app/base/project/repository/repository-gridview.component.ts
> Fix ng-change-checking error for repos component

- src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.ts
- src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.ts
- src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html
- src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.ts
- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
> Add select-all and unselect-all for robot permissions

- src/portal/src/index.html
Forgot to change base tag back in PR #15935.
Now, correct it
> Change base tag to "/" for index.html

- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group0-Util/prepare_imgpkg_test_files.sh
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/test-engine-image/Dockerfile.common
- tests/test-engine-image/Dockerfile.ui_test
> Add test case to verify imgpkg in nightly

- tests/test-engine-image/build_include_case.sh
> Add e2e image include test case

- tests/ci/api_common_install.sh
- tests/ci/api_run.sh
- tests/ci/distro_installer.sh
- tests/hostcfg.sh
> Modify ci script

- tests/resources/Harbor-Pages/Project-Repository.robot
- tests/resources/Harbor-Pages/Project-Repository_Elements.robot
- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/resources/Harbor-Pages/Vulnerability_Elements.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
> Add stop scan and stop scan all test cases

- src/pkg/project/manager.go
- src/pkg/reg/adapter/harbor/base/adapter.go
- src/pkg/reg/adapter/harbor/base/adapter_test.go
Fix: https://github.com/goharbor/harbor/issues/15973
> fix(replication): enhance the replication rule validation

- src/portal/src/app/account/sign-in/sign-in.service.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/shared/components/global-message/message.component.spec.ts
- src/portal/src/app/shared/components/global-message/message.component.ts
- src/portal/src/app/shared/components/list-repository-ro/list-repository-ro.component.ts
- src/portal/src/app/shared/router-guard/member-guard-activate.service.ts
> Redirect to sign-in page when user session timed out

- src/go.mod
- src/go.sum
- src/vendor/github.com/containerd/containerd/images/image.go
- src/vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
- src/vendor/github.com/containerd/containerd/remotes/docker/resolver.go
- src/vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
- src/vendor/github.com/containerd/containerd/version/version.go
- src/vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
- src/vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
- src/vendor/github.com/opencontainers/image-spec/specs-go/version.go
- src/vendor/modules.txt
1, upgrade containerd to v1.14.12
2. upgrade image-spec to v1.0.2
Signed-off-by: wy65701436 <wangyan@vmware.com>
> bump up dep versions

- src/portal/package-lock.json
> Audit fixing for package-lock.json

- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Replication_Elements.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Add replication testcase for exclude and bandwidth

- tests/resources/Harbor-Pages/Robot_Account.robot
- tests/resources/Harbor-Pages/Robot_Account_Elements.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Add robot account do replication test case

- tests/ci/api_common_install.sh
> Fix core private key

- make/photon/chartserver/454.patch
- make/photon/chartserver/492.patch
> Fix: chart replication dup files issue

- src/controller/proxy/controller.go
- src/controller/proxy/manifestcache.go
manifest list: application/vnd.docker.distribution.manifest.list.v2+json
image index: application/vnd.oci.image.index.v1+json
fixes #15837
> Cache content type for manifest list and image index in perspective

- .github/workflows/build-package.yml
> modify build-package branch master to main

- src/portal/src/app/base/project/repository/repository-gridview.component.ts
- src/portal/src/app/shared/components/list-repository-ro/list-repository-ro.component.ts
> Fix unescaped URL for repo links

- tests/apitests/python/test_push_index_by_docker_manifest.py
- tests/apitests/python/test_push_sif_by_singularity.py
- tests/ci/api_run.sh
- tests/test-engine-image/Dockerfile.api_test
- tests/test-engine-image/Dockerfile.common
> Modify push_index and push_sif case to be compatible arm

- src/portal/src/app/services/skinable-config.service.spec.ts
- src/portal/src/app/services/skinable-config.service.ts
> Add querry parameter for setting.json

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.spec.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list.component.spec.ts
- src/portal/src/app/base/project/repository/artifact/artifact-summary.component.spec.ts
- src/portal/src/app/base/project/repository/artifact/artifact-summary.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact.module.ts
- src/portal/src/app/base/project/repository/artifact/artifact.service.spec.ts
- src/portal/src/app/base/project/repository/artifact/artifact.service.ts
- src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-bar-chart.component.spec.ts
> Add share operator to icon observable

- src/portal/src/app/base/project/repository/repository-gridview.component.html
> Add preventDefault for action button of repo card view

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/artifact_test.go
> add scan report v1.1 to default X-Accept-Vulnerabilities

- src/portal/src/app/shared/components/list-repository-ro/list-repository-ro.component.ts
> Fix unescaped url issue

- src/portal/src/app/base/project/repository/gridview/grid-view.component.scss
- src/portal/src/app/base/project/repository/repository-gridview.component.html
- src/portal/src/app/base/project/repository/repository-gridview.component.scss
> Fix overlapping for repo cardview

- tests/ci/api_run.sh
> Temp disable test cases that rely on notary

- make/harbor.yml.tmpl
- make/photon/prepare/models.py
- make/photon/prepare/templates/registry/config.yml.jinja
- make/photon/prepare/test_purgeuploads.py
- make/photon/prepare/utils/configs.py
Enable the uploadpurging by default
Fixes #15641
> Add upload purge config to registry/config.yml

- tests/resources/Harbor-Pages/Replication.robot
> Update Artifact size cell xpath

- src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.html
- src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
- src/portal/src/app/base/project/project-config/project-policy-config/project.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/shared/services/project.service.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Add co-sign checkbox for project policy

- Makefile
- make/photon/Makefile
- make/photon/prepare/utils/cert.py
- tests/ci/api_common_install.sh
- tests/ci/ut_install.sh
> Build base images when running ci

- api/v2.0/swagger.yaml
- src/controller/systeminfo/controller.go
- src/controller/systeminfo/controller_test.go
- src/server/v2.0/handler/systeminfo.go
> feat: add current_time to the response of systeminfo api when user logged in

- tests/resources/Harbor-Pages/Project-Config.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
Update Deployment security Notary xpath due to changes in Deployment security UI 
> Update Deployment security Notary xpath

- make/photon/db/Dockerfile.pg96
- tests/ci/api_run.sh
> Specify postgresql version to 13

- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.spec.ts
- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.ts
- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
- src/portal/src/app/base/project/robot-account/robot-account.component.html
- src/portal/src/app/base/project/robot-account/robot-account.component.spec.ts
- src/portal/src/app/base/project/robot-account/robot-account.component.ts
- src/portal/src/app/shared/components/remaining-time/remaining-time.component.html
- src/portal/src/app/shared/components/remaining-time/remaining-time.component.spec.ts
- src/portal/src/app/shared/components/remaining-time/remaining-time.component.ts
- src/portal/src/app/shared/shared.module.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> Add "expires in" column for robot UI

- .buildbaselog
- make/photon/db/Dockerfile.pg96
> [cherry-pick]Specify postgresql version to 13

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
> Encode repo name for deleting accessory

- src/controller/artifact/controller.go
- src/controller/artifact/controller_test.go
- src/pkg/accessory/manager.go
- src/pkg/accessory/manager_test.go
- src/server/registry/manifest.go
- src/server/v2.0/handler/artifact.go
- src/testing/controller/artifact/controller.go
- src/testing/pkg/accessory/manager.go
> modify artifact copy api to support cosign

- src/server/middleware/cosign/cosign.go
- src/server/middleware/cosign/cosign_test.go
Cosign client will generate the same signature to the same manifest, ignore the conflict error in middleware
> fix cosign conflict error on landing data

- src/server/middleware/contenttrust/notary.go
- src/server/middleware/contenttrust/notary_test.go
- src/server/middleware/vulnerable/vulnerable.go
- src/server/middleware/vulnerable/vulnerable_test.go
Reduce the DB call on pulling artifact with policy disabled
> update pull policy code

- .github/workflows/CI.yml
- .github/workflows/build-package.yml
- .github/workflows/conformance_test.yml
- CONTRIBUTING.md
- Makefile
- make/photon/chartserver/builder
- make/photon/registry/Dockerfile.binary
- make/photon/trivy-adapter/Dockerfile.binary
- make/photon/trivy-adapter/builder.sh
- tests/ci/distro_installer.sh
Bump up go version from v1.17.2 to v1.17.6
> bump up go version to v1.17.6

- tests/resources/Cosign_Util.robot
- tests/resources/Harbor-Pages/Project-Artifact-Elements.robot
- tests/resources/Harbor-Pages/Project-Config.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
- tests/test-engine-image/Dockerfile.common
- tests/test-engine-image/Dockerfile.ui_test
> Add cosign UI test case

- src/portal/angular.json
- src/portal/package-lock.json
- src/portal/package.json
> upgrade ngx-markdown to the latest version

- tests/apitests/python/library/artifact.py
- tests/apitests/python/library/cosign.py
- tests/apitests/python/test_cosign_sign_artifact.py
- tests/ci/api_run.sh
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/test-engine-image/Dockerfile.api_test
> Add cosign Artifact API test case

- tests/resources/Docker-Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add copy accessory test case

- src/pkg/usergroup/manager.go
- src/pkg/usergroup/manager_test.go
Handle the case if there is duplicate user group name when onboard ldap user group
Continue to attach groups when it fail on one item
Fixes #16220
> Group members lose access to push or see projects on Harbor

- src/pkg/usergroup/manager.go
- src/pkg/usergroup/manager_test.go
Handle the case if there is duplicate user group name when onboard ldap user group
Continue to attach groups when it fail on one item
Fixes #16220
> (cherry-pick) Group members lose access to push or see projects on Harbor

- make/migrations/postgresql/0071_2.4.2_schema.up.sql
> Remove old version scan reports of trivy

- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
> Add delete repo permission for robot account

- src/controller/artifact/controller.go
It needs to copy tags for the accessories.
> fix accessory lost tags

- src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/shared/services/interface.ts
> Modify CVSS3 column for cve datagrid

- src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/shared/services/interface.ts
Cherry-pick #16298
Fixes  #16290
> [Cherry-pick]Modify CVSS3 column for cve datagrid

- src/portal/PACKAGE.md
- src/portal/package-lock.json
- src/portal/package.json
- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
> Add list tag permission for robot account

- tests/resources/Harbor-Pages/Robot_Account.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Add replication cosign test case

- src/go.mod
- src/go.sum
- src/vendor/github.com/containerd/containerd/images/image.go
- src/vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
- src/vendor/github.com/containerd/containerd/remotes/docker/httpreadseeker.go
- src/vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
- src/vendor/github.com/containerd/containerd/version/version.go
- src/vendor/modules.txt
> bump up containerd to 1.5.9

- make/migrations/postgresql/0080_2.5.0_schema.up.sql
Closes: https://github.com/goharbor/harbor/issues/16011
Closes: https://github.com/goharbor/harbor/issues/16146
> fix: vulnerability_record & report_vulnerability_record table "integer out of range" error

- Makefile
- make/photon/registry/builder
- tests/ci/ut_install.sh
> bump up distribution version to v2.8

- src/jobservice/job/impl/gc/garbage_collection.go
> (Cherry-pick) feat: add failure-tolerance for gc

- make/harbor.yml.tmpl
- make/photon/prepare/commands/migrate.py
- make/photon/prepare/migrations/__init__.py
- make/photon/prepare/migrations/version_2_5_0/__init__.py
- make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja
> Add Migration Script for Harbor 2.5

- .buildbaselog
> Refresh base images

- src/core/main.go
In order to separate the migrate process from core process, add parameter -mode for main function, it can be normal, migrate, skip_migrate.
> Improve the migrate process

- src/jobservice/api/handler.go
- src/jobservice/api/router.go
- src/jobservice/period/basic_scheduler.go
- src/jobservice/period/enqueuer.go
- src/jobservice/worker/cworker/c_worker.go
- src/pkg/p2p/preheat/provider/client/http_client.go
- src/pkg/reg/adapter/harbor/base/chart_registry.go
- src/pkg/reg/adapter/helmhub/chart_registry.go
- src/pkg/reg/adapter/tencentcr/chart_registry.go
> fix: fix codeql alerts

- src/cmd/exporter/main.go
> fix: correct typo in exporter cmd

- src/jobservice/api/router.go
- src/jobservice/period/basic_scheduler.go
- src/jobservice/period/enqueuer.go
- src/jobservice/worker/cworker/c_worker.go
- src/lib/strings.go
- src/lib/strings_test.go
> fix: trim linebreaks for log parameters

- src/controller/artifact/controller.go
When issue an copy, it has to copy the reference's accessory as well
> fix accessory copy for index

- src/jobservice/api/handler.go
- src/jobservice/api/router.go
- src/jobservice/period/basic_scheduler.go
- src/jobservice/period/enqueuer.go
- src/jobservice/worker/cworker/c_worker.go
- src/lib/strings.go
- src/lib/strings_test.go
- src/pkg/p2p/preheat/provider/client/http_client.go
- src/pkg/reg/adapter/harbor/base/chart_registry.go
- src/pkg/reg/adapter/helmhub/chart_registry.go
- src/pkg/reg/adapter/tencentcr/chart_registry.go
Cherry-pick of https://github.com/goharbor/harbor/pull/16374 and https://github.com/goharbor/harbor/pull/16359 to release-2.4
> [cherry-pick] fix go codeql alerts

- tests/apitests/python/library/containerd.py
- tests/apitests/python/library/docker_api.py
- tests/robot-cases/Group3-Upgrade/prepare.py
> Remove print in python test case

- src/pkg/reg/adapter/harbor/v2/client.go
> fix replicate reference accessory

- .github/workflows/CI.yml
- .github/workflows/build-package.yml
- .github/workflows/conformance_test.yml
- CONTRIBUTING.md
- Makefile
- make/photon/chartserver/builder
- make/photon/registry/Dockerfile.binary
- make/photon/trivy-adapter/Dockerfile.binary
- make/photon/trivy-adapter/builder.sh
- tests/ci/distro_installer.sh
> bump up Go version to 1.17.7

- .github/workflows/CI.yml
- .github/workflows/build-package.yml
- .github/workflows/conformance_test.yml
- CONTRIBUTING.md
- Makefile
- make/photon/chartserver/builder
- make/photon/registry/Dockerfile.binary
- make/photon/trivy-adapter/Dockerfile.binary
- make/photon/trivy-adapter/builder.sh
- tests/ci/distro_installer.sh
Bump up Go version to 1.17.7 for release-2.4.0
> Bump up Go version to 1.17.7 for release-2.4.0

- src/server/middleware/security/basic_auth.go
- src/server/middleware/security/basic_auth_test.go
> Add IP and agent in trace for failed login

- src/portal/PACKAGE.md
- src/portal/angular.json
- src/portal/package-lock.json
- src/portal/package.json
- src/portal/src/app/dev-center/dev-center.component.ts
- src/portal/src/polyfills.ts
- src/portal/tsconfig.json
> Upgrade swagger-ui to the latest version

- src/go.mod
- src/go.sum
- src/vendor/modules.txt
Replace with `github.com/distribution/distribution v2.8.0+incompatible`
> replace with github.com/distribution/distribution v2.8.0+incompatible

- src/portal/src/app/shared/components/inline-alert/inline-alert.component.html
> Fix inline alert issue

- src/pkg/reg/adapter/tencentcr/adapter.go
- src/pkg/reg/adapter/tencentcr/chart_registry.go
- src/pkg/reg/adapter/tencentcr/chart_registry_test.go
- src/pkg/reg/adapter/tencentcr/sdk.go
- src/pkg/reg/adapter/tencentcr/sdk_test.go
Fix & UT
1. Fix TCR Adapter namespcae check.
2. Add Chart UT.
Signed-off-by: 疯魔慕薇 <kfanjian@gmail.com>
> Fix: TCR Adapter namespcae check.

- tests/resources/Harbor-Pages/Project.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Add replication test cases triggered by events

- .github/workflows/conformance_test.yml
> fix: resolve conformance test failed issue

- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
> Add a new robot permission and sort permissions

- src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
> [Cherry-pick]Add a new robot permission and sort permissions

- src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/edit-project-quotas/edit-project-quotas.component.scss
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.ts
- src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html
- src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
> Improve style and correct typos

- .github/workflows/build-package.yml
> Add online latest installer package

- src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/edit-project-quotas/edit-project-quotas.component.scss
- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
- src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.ts
- src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html
- src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
> [Cherry-pick]Improve style and correct typos

- tests/robot-cases/Group1-Nightly/Replication.robot
> Add replication index testcase

- tests/robot-cases/Group1-Nightly/Replication.robot
> [cherry-pick]Add replication index testcase

- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Schedule.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
> [cherry-pick]Update trivy test case

- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Schedule.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
> Update trivy test case

- src/portal/src/i18n/lang/de-de-lang.json
Signed-off-by: sluetze <13255307+sluetze@users.noreply.github.com>
@Vad1mo
> Updated translation for 2.5

- tests/ci/conformance_test.sh
> fix: enable one skipped conformance test

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.service.ts
> Fix duplicate labels issue

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.service.ts
> [Cherry-pick]Fix duplicate labels issue

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.scss
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact.service.ts
Add cosign icon support on UI , #16513
> Add cosign icon

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.scss
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact.service.ts
> [Chrry-pick]Add cosign icon

- src/lib/endpoint.go
- src/lib/endpoint_test.go
- src/pkg/p2p/preheat/provider/dragonfly.go
- src/pkg/p2p/preheat/provider/kraken.go
- src/pkg/scan/dao/scanner/model.go
- src/pkg/scan/dao/scanner/model_test.go
> enhance health validataion

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/base/project/repository/artifact/artifact.ts
- src/portal/src/app/shared/components/push-image/push-image.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
> [Cherry-pick]Update push and pull command for helm

- src/portal/src/app/shared/components/view-token/view-token.component.ts
> [Cherry-pick]Add secret to download file when refreshing robot secret

- src/portal/src/app/shared/components/view-token/view-token.component.ts
> Add secret to download file when refreshing robot secret

- src/controller/scan/base_controller.go
- src/controller/scanner/base_controller.go
- src/core/api/internal.go
- src/core/controllers/base.go
- src/pkg/retention/launcher.go
- src/server/middleware/quota/quota.go
- src/server/middleware/security/robot.go
- src/server/middleware/vulnerable/vulnerable.go
- src/server/v2.0/handler/project.go
Use the deactive for instead in the error log
> update log with more inclusive language

- .github/workflows/build-package.yml
Adjust it because upstream made it, For more information, please see: https://github.com/google-github-actions/setup-gcloud/issues/539
> [cherry-pick]Modify setup-gcloud from master to v0

- .github/workflows/build-package.yml
Adjust it because upstream made it, For more information, please see: https://github.com/google-github-actions/setup-gcloud/issues/539
> Modify setup-gcloud from master to v0

- src/controller/proxy/controller.go
- src/core/main.go
- src/core/session/codec.go
- src/core/session/codec_test.go
- src/core/session/session.go
- src/core/session/session_test.go
- src/lib/cache/codec.go
- src/lib/cache/redis/redis.go
Closes: https://github.com/goharbor/harbor/issues/16456
Comparison: https://github.com/goharbor/harbor/pull/16546#issuecomment-1070516463
> feat: implement beego session provider

- src/portal/src/app/base/left-side-nav/gc-page/gc/gc-history/gc-history.component.html
> Remove state restrictions for gc log button

- src/server/v2.0/handler/project.go
Fixes: https://github.com/goharbor/harbor/issues/16448
> fix: validate project metadata public value

- src/server/v2.0/handler/project.go
> fix: return BAD_REQUEST when validate project metadata

- make/migrations/postgresql/0080_2.5.0_schema.up.sql
> migrations: correct project metadata public value

- src/server/v2.0/handler/project.go
> [cherry-pick] fix: validate project metadata public value

- src/portal/src/app/base/left-side-nav/group/group.component.ts
> Use list user groups API to search groups

- tests/robot-cases/Group1-Nightly/Routing.robot
> Add main menu routing test case

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/shared/components/image-name-input/image-name-input.component.html
- src/portal/src/app/shared/components/image-name-input/image-name-input.component.scss
- src/portal/src/app/shared/components/image-name-input/image-name-input.component.spec.ts
- src/portal/src/app/shared/components/image-name-input/image-name-input.component.ts
> Improve copy-artifact component

- src/portal/src/app/base/account-settings/account-settings-modal.component.html
- src/portal/src/app/base/account-settings/account-settings-modal.component.ts
- src/portal/src/app/shared/services/session.service.ts
> [Cherry-pick]Improve user setting component

- src/portal/src/app/base/account-settings/account-settings-modal.component.html
- src/portal/src/app/base/account-settings/account-settings-modal.component.ts
- src/portal/src/app/shared/services/session.service.ts
1. change "api/v2.0/internal/renameadmin" to "api/internal/renameadmin"
2. Refresh the account after updating 
3. disable submit button if no change for a user account
> Improve user setting component

- tests/robot-cases/Group1-Nightly/Routing.robot
Add this test case to make sure the project tab routing is routed correctly
> Add project tab routing test case

- tests/apitests/python/library/oras.py
- tests/resources/CNAB_Util.robot
- tests/resources/Helm-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Common.robot
Retry to solve the ecs environment s3aws Path not found issue
> Add retries to test cases

- CODEOWNERS
When we PR comes in all will be assigned as reviewers so we will not miss PR
> Add CODEOWNERS all maintainers

- tests/resources/Harbor-Pages/UserProfile.robot
- tests/resources/Harbor-Pages/UserProfile_Elements.robot
- tests/robot-cases/Group1-Nightly/Routing.robot
Add a test case for opening the license page to ensure this function is correct.
Fixes #15967
> Add open license test case

- src/portal/docker-build/README.md
- src/portal/docker-build/nginx.conf.example
Strengthen  location regex to make sure API requests are forwarded to the backend
> Update docker building for UI

- tests/robot-cases/Group1-Nightly/Routing.robot
Add a test case for opening the CVE Details Page to ensure this function is correct.
Fixes #15967
> Add open cve details page test case

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
Add test cases for these three different scenarios to ensure that Replication functions correctly after Deployment Security Policy is enabled
Fixes https://github.com/goharbor/harbor/issues/16714
> [cherry-pick]Add test case for Enable Deployment Security Policy replication

- api/v2.0/legacy_swagger.yaml
Signed-off-by: Tim Beermann <beermann@osism.tech>
Fixes #(issue)
> fixed typo in legacy_swagger.yaml file

- src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
- src/portal/src/i18n/lang/de-de-lang.json
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Fixes #16377
1. Provide more useful error info when editing a problematic replication rule
Fixes #(issue)
> Provide more useful error info

- make/photon/registry/builder
- make/photon/registry/redis.patch
> fix: registry/redis.patch & registry/builder

- make/photon/registry/builder
- make/photon/registry/redis.patch
> cherry-pick to release-2.5.0: fix registry/redis.patch & registry/builder

- src/jobservice/job/impl/gc/garbage_collection.go
> fix: improve GC log message

- src/jobservice/job/impl/gc/garbage_collection.go
> cherry-pick to release-2.5.0: improve GC log message

- Makefile
- src/.golangci.yaml
- tests/ci/ut_install.sh
Add lint tool `golangci-lint`, integrated several linters in file `.golangci.yaml`
remove `golint` in Makefile
remove `gofmt` in Makefile
remove `govet` in Makefile
Fixes #(issue)
> add lint with golangci-lint

- src/common/http/client.go
- src/controller/p2p/preheat/enforcer.go
- src/core/controllers/oidc.go
- src/jobservice/hook/hook_agent.go
- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/tracker.go
- src/jobservice/runtime/bootstrap.go
- src/lib/config/userconfig.go
- src/lib/errors/errors.go
- src/lib/redis/redisclient.go
- src/pkg/reg/adapter/aliacr/auth.go
- src/pkg/reg/adapter/quay/auth/authorizer.go
- src/pkg/reg/adapter/tencentcr/adapter.go
- src/pkg/reg/adapter/tencentcr/auth.go
- src/pkg/reg/filter/artifact.go
- src/pkg/scan/rest/v1/client_pool.go
- src/pkg/scan/vuln/severity.go
- src/server/middleware/quota/copy_artifact.go
Fix the staticcheck problems that reported by golangci-line staticcheck
Fixes #(issue)
> fix staticcheck issues

- tests/resources/Cosign_Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/test-engine-image/Dockerfile.common
- tests/test-engine-image/Dockerfile.ui_test
1 bump up cosign version to 1.8.0
2 Add cosign Verify test
Fixes #(issue)
> Update cosign test case

- src/controller/artifact/controller.go
- src/controller/event/handler/internal/artifact_test.go
- src/controller/event/handler/webhook/artifact/artifact.go
- src/controller/repository/controller.go
- src/controller/retention/controller.go
- src/migration/artifact.go
- src/pkg/cached/manager.go
- src/pkg/cached/repository/redis/manager.go
- src/pkg/cached/repository/redis/manager_test.go
- src/pkg/exporter/project_collector_test.go
- src/pkg/factory.go
- src/pkg/factory_test.go
- src/pkg/repository/manager.go
- src/server/middleware/immutable/pushmf_test.go
- src/server/registry/catalog.go
- src/server/registry/catalog_test.go
Implement cache layer for resource repository and migrate repository.Mgr
to pkg.RepositoryMgr.
Fixes #16741 
> feat(repository): introduce cache manager for repository (#16741)

- src/pkg/accessory/dao/dao.go
- src/server/v2.0/handler/artifact.go
The count api should ignore the pagination.
Fixes #(issue)
> fix accessory count issue

- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
1.  Improve accessory component
Fixes #(issue)
> Improve accessory component

- src/go.mod
- src/go.sum
- src/vendor/github.com/beego/beego/context/output.go
- src/vendor/github.com/beego/beego/tree.go
- src/vendor/modules.txt
> bump up beego from v1.12.7 to v1.12.9
