goharbor/harbor

api/base.go
service/token.go
utils/utils.go

enable basic authentication for api

---

controllers/itemdetail.go
static/resources/js/item-detail.js

fixed visiting project details issues for a admin user.

fixed visiting project details for a admin user.

---

AUTHORS
README.md

1. add AUTHORS
2. update README

AUTHORS and README

---

auth/authenticator.go
auth/ldap/ldap.go

update the logger for this go file, and delete bee import as the build failure.

update logger for autoenticator.go, passed on docker-compose build

---

service/utils/registryutils.go

This should probably fix https://github.com/vmware/harbor/issues/58 and https://github.com/vmware/harbor/issues/49

fix potential index out of range error

---

controllers/base.go
controllers/itemdetail.go
controllers/login.go
controllers/password.go
controllers/register.go

Already replaced with the new logger module and PASS the test.

Updated the new logger module for the go files in the controllers directory

---

service/token.go
service/utils/authutils.go
service/utils/registryutils.go

handle the case when docker request token for multiple scopes

---

Deploy/docker-compose.yml
Dockerfile.ui
ui/main.go
ui/router.go

So that we can build different binaries from one code base more easily.

refactor code stucture

---

docs/swagger.yaml

yaml key "/projects/{project_id}/members/" duplicated.
move get and post block in same "/projects/{project_id}/members/" key

fix swagger.yaml key duplicated

---

Deploy/prepare

Let prepare file be compatible with python3.

add python3 compatibility to prepare file

---

api/repository.go
models/repo.go
static/i18n/locale_en-US.ini
static/i18n/locale_zh-CN.ini
static/resources/js/item-detail.js
views/index.tpl

Update for index page title, image detail create time localization.

Update for index page title, image detail create time localization.

---

api/user.go
controllers/password.go
static/resources/js/change-password.js
ui/router.go

Changes an account password for Guests; old password required, and Guests can only change their own account.
PUT /api/users/:id/password 	
Passed on UI and API test.

update changepassword to /api/users/:id/password

---

docs/configure_swagger.md
docs/prepare-swagger.sh

update Swagger for http/https schemes support

update Swagger for http/https schemes support

---

views/project.tpl

Updated admin tab layout to match the width with other tabs
now there is no style change when switching between tabs

Updated admin tab layout to match the width with other tabs

---

api/base.go
api/project.go
api/user.go
dao/dao_test.go
dao/project.go
static/resources/js/register.js

Add a comment function in base to handle the post method return resource uri.
Passed on the API and UI testing.

add post return, add the URI to header location.

---

Deploy/templates/registry/config.yml

add timeout for notification in registry

---

README.md

Added German language to the Readme

Updated README to include German

---

docs/swagger.yaml

1, Add post user API.
2, Add change user password API.
3, Update post project return code to 201.

Update API doc

---

Deploy/db/registry.sql

This patch changes the email field to 128 characters from 30 characters.

email field data type size changed to 128 characters from 30 characters

---

README.md
docs/installation_guide.md

Cleaned up some of the Installation documentation to
* Improve clarity
* Emphasize key points

Cleanup some of the documentation

---

docs/prepare-swagger.sh

sed -i need explicit extention on mac, but linux is optinoal.
so for developer need a compatible request on macos

Fix: sed compatible with mac os env

---

dao/dao_test.go
dao/project.go

fix a sql bug

---

Deploy/db/registry.sql
api/jobs/replication.go
job/config/config.go
job/replication/statehandlers.go
job/statehandlers.go
job/statemachine.go
job/utils/logger.go
jobservice/router.go
utils/log/logger.go

@ywk253100 please review as I made update to utils/log.go

store log in fs, provide api for getting log of a job

---

Deploy/log/Dockerfile
Deploy/log/rsyslog.conf

1 add modified rsyslog.conf file in ./Deploy/log/
2 remove 'sed' command in ./Deploy/log/Dockerfile and add "ADD" command for copy modified rsyslog.conf

Update for using static 'rsyslog.conf' instead command 'sed' in  Dockerfile of  the log container

---

api/member.go
api/project.go
api/repository.go
api/utils.go
dao/project.go
ui/router.go

1. user can get public projects without login
2. add basic auth support for repository API
3. user can get repositories of public project without login
4. system admin can CRUD members of all projects
5. sort tags by name

Some modifications for implements of API

---

api/repository.go

bug fix: create repository client with credential when basic auth is used

bug fix: create repository client with credential when basic auth is used

---

static/resources/js/item-detail.js

fixed bug of issue #284

---

static/resources/js/item-detail.js

update for listing repo name contains dot.

update for listing repo name contains dot.

---

docs/swagger.yaml

change swagger.yml error,  change  api/project/{project_id} to api/project/{project_id}/publicity

change swagger.yml 

---

job/replication/delete.go
job/replication/transfer.go

add insecure filed to job log and pass variable insecure to base handler

add insecure filed to job log and pass variable insecure to base handler

---

static/resources/js/components/log/list-log.directive.html
static/resources/js/components/project-member/list-project-member.directive.html
static/resources/js/components/system-management/destination.directive.html
static/resources/js/components/system-management/replication.directive.html
static/resources/js/components/top-repository/top-repository.directive.html

Update list-log.directive.html
Update list-project-member.directive.html
Update destination.directive.html
Update replication.directive.html
Update top-repository.directive.html

fixed some page's fixed table title

---

static/resources/js/components/user-log/user-log.directive.html
static/resources/js/components/user/list-user.directive.html
views/project.htm

Update project.htm
Update user-log.directive.html
Update list-user.directive.html

Fixed Table Title

---

static/resources/js/components/project-member/add-project-member.directive.js
static/resources/js/components/project/add-project.directive.js

Update add-project.directive.js
Update add-project-member.directive.js

Close pop input bar after success.

---

controllers/changepassword.go
static/resources/js/harbor.module.js
static/resources/js/layout/account-setting/account-setting.controller.js
static/resources/js/layout/change-password/change-password.controller.js
static/resources/js/layout/change-password/change-password.module.js
static/resources/js/services/i18n/locale_messages_en-US.js
static/resources/js/services/i18n/locale_messages_zh-CN.js
ui/router.go
views/account-settings.htm
views/change-password.htm
views/sections/header-include.htm

controllers/changepassword.go
*static/resources/js/layout/change-password/change-password.controller.js
*static/resources/js/layout/change-password/change-password.module.js
**ui/router.go
views/change-password.htm
views/account-settings.htm
**views/sections/header-include.htm
**static/resources/js/harbor.module.js
static/resources/js/layout/account-setting/account-setting.controller.js
static/resources/js/services/i18n/locale_messages_en-US.js
static/resources/js/services/i18n/locale_messages_zh-CN.js

add new page for change password

---

static/resources/js/components/replication/list-replication.directive.html
static/resources/js/services/i18n/locale_messages_en-US.js
static/resources/js/services/i18n/locale_messages_zh-CN.js

squash 3 commit for add error icon on list

---

static/resources/js/components/details/retrieve-projects.directive.js
static/resources/js/components/replication/list-replication.directive.js
static/resources/js/layout/project/project.controller.js
static/resources/js/services/i18n/locale_messages_en-US.js
static/resources/js/services/i18n/locale_messages_zh-CN.js

Updates for toggling status of policies and publicity of projects i18n messages.

Updates for toggling status of policies and publicity of projects i18n messages.

---

views/forgot-password.htm
views/reset-password.htm
views/sign-up.htm

enable submit button before correct fulfil form

---

views/change-password.htm

add "(form.$submitted || form.$$$$)" on ng-message

Resolve the issue of not show error message without focus on form.

---

static/resources/js/components/replication/create-policy.directive.js
static/resources/js/components/system-management/create-destination.directive.js

Fixed compatibility issues when creating/editing in dialog box showing error messages.

Fixed compatibilty issues when creating/editing in dialog box showing error messages.

---

static/resources/js/components/log/list-log.directive.html
static/resources/js/components/log/list-log.directive.js
static/resources/js/components/project-member/list-project-member.directive.html
static/resources/js/components/project-member/list-project-member.directive.js
static/resources/js/components/replication/list-replication.directive.html
static/resources/js/components/replication/list-replication.directive.js
static/resources/js/components/repository/list-repository.directive.html
static/resources/js/components/repository/list-repository.directive.js
static/resources/js/components/search/search-input.directive.js
static/resources/js/components/system-management/destination.directive.html
static/resources/js/components/system-management/destination.directive.js
static/resources/js/components/system-management/replication.directive.html
static/resources/js/components/system-management/replication.directive.js
static/resources/js/components/user/list-user.directive.html
static/resources/js/components/user/list-user.directive.js
static/resources/js/layout/project/project.controller.js
views/project.htm

Update for interaction with enter key press when doing searches.

Update for interaction with enter key press when doing searches

---

docs/developer_i18n_guide.md

Add developer i18n guide.md file.

Add developer i18n guide.md file.

---

static/resources/js/components/system-management/create-destination.directive.html
static/resources/js/components/system-management/create-destination.directive.js

Update for destination interaction refinements.

Update for destination interaction refinements.

---

static/resources/js/services/i18n/locale_messages_en-US.js
static/resources/js/services/i18n/locale_messages_zh-CN.js

update i18n messages about tag deletion.

update i18n messages about tag deletion.

---

static/resources/js/components/repository/pull-command.directive.js

Update for selecting all when click the pull command text.

Update for selecting all when click the pull command text.

---

Deploy/harbor.cfg

Turn off "production" flag for tracking issues.

Turn off "production" flag for tracking issues.

---

static/resources/css/replication.css
static/resources/js/components/log/advanced-search.directive.html
static/resources/js/components/replication/list-replication.directive.html
static/resources/js/components/replication/list-replication.directive.js
static/resources/js/services/i18n/locale_messages_en-US.js
static/resources/js/services/i18n/locale_messages_zh-CN.js

Updates for replication page height, confirm messages and the position of advanced search button.

Updates for replication page height, confirm messages and the position of advanced search button.

---

static/resources/css/replication.css
static/resources/js/components/replication/list-replication.directive.html
static/resources/js/components/replication/list-replication.directive.js

Add re-sizable height of replication page.

Add re-sizable height of replication page.

---

docs/kubernetes_deployment.md

Update kubernetes_deployment.md fixing text error

---

docs/kubernetes_deployment.md
docs/prepare-swagger.sh

update prepare-swagger.sh for remove swagger.ymal show error

---

static/resources/js/components/project/add-project.directive.html

link checkbox and its label

---

static/resources/js/components/user/toggle-admin.directive.js

Fixed toggling admin user option.

Fixed toggling admin user option.

---

static/resources/js/components/user/list-user.directive.html
static/resources/js/components/user/toggle-admin.directive.js

Update for toggling admin options check.

Update for toggling admin options check.

---

contrib/sdk/harbor-py/harborclient/harborclient.py

Address from this PR https://github.com/tobegit3hub/harbor-py/pull/2

Replace simplejson with json and fix missed print statement

---

.travis.yml
Deploy/coverage4gotest.sh
README.md
api/api_test.go
api/jobs/job_test.go
auth/auth_test.go
auth/db/db_test.go
auth/ldap/ldap_test.go
controllers/controllers_test.go
job/config/config_test.go
job/job_test.go
job/replication/replication_test.go
job/utils/utils_test.go
jobservice/jobservice_test.go
models/models_test.go
service/cache/cache_test.go
service/service_test.go
service/token/token_test.go
service/utils/utils_test.go
ui/ui_test.go
utils/log/log_test.go
utils/registry/auth/auth_test.go
utils/registry/error/error_test.go
utils/utils_test.go

data form .Travis and Coveralls
add the tag on README.md

for shown go test coverage tag

---

api/base.go
api/project.go
api/replication_job.go
api/repository.go
dao/accesslog.go
dao/base.go
dao/dao_test.go
dao/replication_job.go
service/utils/utils.go
utils/utils.go
utils/utils_test.go

support pagination for listing repositories, jobs and access logs

---

.travis.yml

add pkg for support coveralls

---

Deploy/jsminify.sh

Add comments to fix sed compatibility issue between BSD and GNU versions

---

static/resources/js/components/project/publicity-button.directive.html
static/resources/js/components/user/list-user.directive.html
static/resources/js/components/user/list-user.directive.js
static/resources/js/components/user/toggle-admin.directive.html
static/resources/js/components/user/toggle-admin.directive.js

Updates for toggling project publicity and blocking user change admin role by oneself.

Updates for toggling project publicity and blocking user change admin role by oneself.

---

static/resources/css/project.css
static/resources/js/components/log/list-log.directive.html
static/resources/js/components/log/list-log.directive.js
static/resources/js/components/paginator/paginator.directive.html
static/resources/js/components/paginator/paginator.directive.js
static/resources/js/components/paginator/paginator.module.js
static/resources/js/components/project/publicity-button.directive.html
static/resources/js/components/replication/list-replication.directive.html
static/resources/js/components/replication/list-replication.directive.js
static/resources/js/components/repository/list-repository.directive.html
static/resources/js/components/repository/list-repository.directive.js
static/resources/js/components/user/list-user.directive.html
static/resources/js/components/user/list-user.directive.js
static/resources/js/components/user/toggle-admin.directive.html
static/resources/js/components/user/toggle-admin.directive.js
static/resources/js/harbor.module.js
static/resources/js/services/log/services.list-log.js
static/resources/js/services/replication-job/services.list-replication-job.js
static/resources/js/services/repository/services.list-repository.js
views/sections/script-include.htm

Add pagination to UI.

---

Deploy/db/registry.sql
api/replication_policy.go
dao/replication_job.go
migration/changelog.md
models/replication_job.go
static/resources/js/components/paginator/paginator.directive.js

1. support policy deletion 
2. bug fix: missing semicolon in js

Support policy deletion 

---

README.md

change branch from master to dev for coveralls in README.md

---

Deploy/db/registry.sql
api/internal.go
api/utils.go
dao/accesslog.go
dao/dao_test.go
dao/repository.go
models/base.go
models/repo.go
service/notification.go
ui/main.go
ui/router.go

1, update code per comments.
2, add retry to init registry client.
3, re-factor diffRepo() 
4, add testing code.

Add repo into DB, update code per comments

---

Deploy/db/registry.sql
api/project.go
api/repository.go
api/statistic.go
api/statistic_test.go
api/utils.go
dao/accesslog.go
dao/dao_test.go
dao/project.go
dao/repository.go
dao/repository_test.go

1.Fix bugs in implements of storing repositories in DB 
2.Complete project deletion 
3.Refactor logic of listing the most favorite repositories 
4.Refactor statistics

Enhancements and refactors due to storing repositories in database

---

api/harborapi_test.go
api/log_test.go
api/member_test.go
api/project_test.go
api/statistic_test.go
docs/swagger.yaml
tests/apitests/apilib/project.go
tests/apitests/apilib/project_req.go

1.Fix bug of public type of  project in swagger.yml: boolen to int.
2.Add member get API test.
3.Handle some conflict in statistics_test, log_test.go and harborapi_test.go
4.Add projectReq struct and update user struct  in swagger.yml and apilib

Update api test and swagger.yaml(updated version)

---

Deploy/db/registry.sql
api/project.go
dao/accesslog.go
dao/dao_test.go

Improve the performance of database when paginating large records for access logs, jobs and getting the top repositories

Recover lost commit: improve the performance of database when paginating large records for access logs, jobs and getting the top repositories

---

static/resources/js/components/details/retrieve-projects.directive.js
static/resources/js/components/log/list-log.directive.js
static/resources/js/layout/navigation/navigation-details.directive.js
views/repository.htm

Updates for interactions of retrieving project list in repositories.

Updates for interactions of retrieving project list in repositories.

---

static/resources/js/components/details/retrieve-projects.directive.js
static/resources/js/components/log/list-log.directive.html
static/resources/js/components/log/list-log.directive.js
static/resources/js/components/project-member/list-project-member.directive.js
static/resources/js/components/replication/list-replication.directive.js
static/resources/js/components/repository/list-repository.directive.js
static/resources/js/layout/details/details.controller.js
static/resources/js/services/i18n/locale_messages_en-US.js
static/resources/js/services/i18n/locale_messages_zh-CN.js

Update for loading requests of UI when retrieving project details.

Update for loading requests of UI when retrieving project details..

---

api/search.go
api/utils.go

1.search refactor due to storing repositories in database 
2.bug fix: filter repositories in project view

Search refactor and bug fix

---

static/resources/js/components/repository/popup-details.directive.html
static/resources/js/components/repository/popup-details.directive.js
static/resources/js/services/repository/services.list-manifest.js

Update for lazy loading of repo manifest.

Update for lazy loading of repo manifest.

---

static/resources/js/components/repository/popup-details.directive.js
static/resources/js/harbor.config.js
views/search.htm

Update for some refinements in session checking of UI.

Update for some refinements in session checking of UI.

---

api/dataprepare_test.go
api/harborapi_test.go
api/member_test.go
api/repository_test.go

1. add member and repos api test.
2. add  dataprepare_test.go(including add/delete/get user and project)

add member and repos test

---

static/resources/js/components/details/retrieve-projects.directive.js
static/resources/js/components/log/list-log.directive.js
static/resources/js/components/project-member/list-project-member.directive.js
static/resources/js/components/repository/list-repository.directive.js
static/resources/js/components/repository/list-tag.directive.js
static/resources/js/components/top-repository/top-repository.directive.html
static/resources/js/components/top-repository/top-repository.directive.js
static/resources/js/components/user-log/user-log.directive.html
static/resources/js/components/user-log/user-log.directive.js
static/resources/js/layout/details/details.controller.js
static/resources/js/layout/project/project.controller.js
views/project.htm
views/repository.htm

Refinements on toggling project publicity and rollback changes on popular repos.

Refinements on toggling project publicity and rollback changes on popular repos

---

controllers/base.go
static/resources/js/components/optional-menu/optional-menu.directive.js

Updates for showing version on UI.

Updates for showing version on UI.

---

docs/installation_guide.md

Corrected some typos in the installation guide.

Fix typos.

---

api/utils.go

Do not print successful log if error occur.

minor fix log print

---

static/resources/js/components/details/retrieve-projects.directive.js
static/resources/js/services/project/services.list-project.js
views/project.htm

Update for loading projects with pagination of UI.

Update for loading projects with pagination of UI.

---

static/resources/js/components/details/retrieve-projects.directive.js
static/resources/js/services/project/services.list-project.js
views/project.htm

Fix public project table title alignment.

Fix public project table title alignment.

---

static/resources/js/components/project-member/add-project-member.directive.html
static/resources/js/components/project-member/list-project-member.directive.html
views/project.htm

Updates for some UI styles.

---

docs/swagger.yaml

update API doc for sync registry.

---

src/ui/api/user.go
src/ui/static/resources/js/components/validator/email.validator.js
src/ui/views/account-settings.htm
src/ui/views/forgot-password.htm
src/ui/views/sections/script-include.htm
src/ui/views/sign-up.htm

Make consistent email validations with backend.

Updates for email validations.

---

src/ui/service/notification.go

Add prettyjws in pattern for signed manifest support

---

src/ui/static/resources/js/components/details/retrieve-projects.directive.js
src/ui/static/resources/js/components/project-member/edit-project-member.directive.html
src/ui/static/resources/js/components/project-member/edit-project-member.directive.js
src/ui/static/resources/js/components/project-member/list-project-member.directive.html
src/ui/static/resources/js/components/project-member/list-project-member.directive.js
src/ui/static/resources/js/components/project/publicity-button.directive.html
src/ui/static/resources/js/components/project/publicity-button.directive.js
src/ui/static/resources/js/components/repository/list-repository.directive.html
src/ui/static/resources/js/components/repository/list-repository.directive.js
src/ui/static/resources/js/components/repository/list-tag.directive.html
src/ui/static/resources/js/components/repository/list-tag.directive.js
src/ui/views/project.htm
src/ui/views/repository.htm

Updates for hiding buttons against to user role.

Updates for hiding buttons against to user role.

---

src/ui/static/resources/js/components/element-height/element-height.inspector.js
src/ui/static/resources/js/components/log/list-log.directive.js
src/ui/static/resources/js/components/project-member/add-project-member.directive.js
src/ui/static/resources/js/components/project-member/list-project-member.directive.js
src/ui/static/resources/js/components/project/add-project.directive.html
src/ui/static/resources/js/components/project/add-project.directive.js
src/ui/static/resources/js/components/replication/list-replication.directive.js
src/ui/static/resources/js/components/repository/list-repository.directive.js
src/ui/static/resources/js/components/system-management/destination.directive.js
src/ui/static/resources/js/components/system-management/replication.directive.js
src/ui/static/resources/js/components/user/list-user.directive.js
src/ui/static/resources/js/layout/project/project.controller.js
src/ui/views/project.htm

1) Extend height of the listing project page.
2) Do retrieval after clearing the search box.
3) Setting input box auto-focus when opened the tab form.

Updates for refinements of UX.

---

docs/migration_guide.md

_This PR is target dev branch since the latest migration update has not been merged to master yet._

update db migration guide to use image on docker hub

---

src/ui/static/resources/js/components/project-member/add-project-member.directive.html
src/ui/static/resources/js/components/project/add-project.directive.html
src/ui/static/resources/js/components/replication/create-policy.directive.html
src/ui/static/resources/js/components/system-management/configuration.directive.html
src/ui/static/resources/js/components/system-management/create-destination.directive.html
src/ui/views/account-settings.htm
src/ui/views/change-password.htm
src/ui/views/forgot-password.htm
src/ui/views/reset-password.htm
src/ui/views/sign-in.htm
src/ui/views/sign-up.htm

Set form autocomplete to off

---

docs/developer_guide_i18n.md

Fix filepath to app.conf

---

docs/swagger.yaml

Signed-off-by: xuxinkun <xuxinkun@gmail.com>

fix responses for /repositories/tags.

---

src/ui/static/resources/js/services/i18n/services.i18n.js

Change language name '中文' to '简体中文'.

Change Chinese language name.

---

src/common/dao/accesslog.go
src/common/dao/base.go
src/common/dao/dao_test.go
src/common/dao/project.go
src/common/dao/projectmember.go
src/common/dao/replication_job.go
src/common/dao/repository.go
src/common/dao/user.go
src/ui/api/member.go
src/ui/api/user.go

Escapse % and _ in sql

---

tools/ova/script/common.sh
tools/ova/script/config.sh
tools/ova/script/firstboot.sh
tools/ova/script/firstboot_config.sh

1.copy ca to download directory if nedded 
2.add IP to san 
3.ignore harbor admin password and database password in subsequent boot

OVA script update

---

docs/swagger.yaml
src/ui/api/systeminfo.go

Revert "Updates Swagger YAML for new added APIs."

---

src/common/utils/registry/registry.go

@reasonerjt, PTAL.
Fix https://github.com/vmware/harbor/issues/1239.

Remove http timeout option on getting catalog

---

.travis.yml
docs/compile_guide.md
make/dev/jobservice/Dockerfile
make/dev/ui/Dockerfile
make/ubuntu/jobservice/Dockerfile
make/ubuntu/ui/Dockerfile
tools/Dockerfile.golang

#1245 
golang: from 1.6.2 to 1.7.3

upgrade golang baseimage from 1.6.2 to 1.7.3

---

Makefile
docs/user_guide.md
make/dev/docker-compose.yml
make/docker-compose.tpl
src/vendor/github.com/docker/distribution/manifest/schema2/builder.go
src/vendor/github.com/docker/distribution/registry/api/errcode/register.go
src/vendor/github.com/docker/distribution/registry/api/v2/descriptors.go
src/vendor/github.com/docker/distribution/registry/client/repository.go
src/vendor/vendor.json
tests/docker-compose.test.yml

#1245
update registry: from 2.5 to 2.5.1

update registry from 2.5.0 to 2.5.1

---

tools/ova/script/config.sh

Fix certificate bundle issue.

---

contrib/registryapi/README.md
contrib/registryapi/cli.py
contrib/registryapi/registry.py

this pr add a little python api class for registry and a little tool for repo, tag, manifest operations.
more details, please see contrib/registryapi/README.md

add registry python api and cli tool

---

src/common/dao/dao_test.go
src/common/dao/repository.go
src/common/dao/repository_test.go
src/ui/api/repository.go

Recreated pull request #1279 for dev branch.

Fix filtering top repositories (#783, #1281) (recreated for dev branch)

---

src/common/utils/utils.go
src/common/utils/utils_test.go
src/ui/api/utils.go

Support multiple namespaces in repo name 

---

src/common/dao/repository.go
src/common/dao/repository_test.go

Show all non-deleted repositories for admin (without project role checking)

Fix visibility of top repos for admin (#1306)

---

harbor-app/src/app/base/harbor-shell/harbor-shell.component.html
harbor-app/src/app/core/core.module.ts

add forRoot() when importing clarity module

Fix bug: clarity service not found

---

harbor-app/src/app/project/action-project/action-project.component.html
harbor-app/src/app/project/action-project/action-project.component.ts
harbor-app/src/app/project/create-project/create-project.component.html
harbor-app/src/app/project/create-project/create-project.component.ts
harbor-app/src/app/project/filter-project/filter-project.component.html
harbor-app/src/app/project/list-project/list-project.component.html
harbor-app/src/app/project/list-project/list-project.component.ts
harbor-app/src/app/project/project.component.html
harbor-app/src/app/project/project.component.ts
harbor-app/src/app/project/project.module.ts
harbor-app/src/app/project/project.service.ts
harbor-app/src/app/project/project.ts

Add selection for deleting projects.
Add pop-up menu for actions of projects.

Updates for project actions.

---

harbor-app/src/app/base/account-settings/account-settings-modal.component.html
harbor-app/src/app/base/account-settings/account-settings-modal.component.ts
harbor-app/src/app/shared/max-length-ext.directive.ts
harbor-app/src/app/shared/session-user.ts
harbor-app/src/app/shared/session.service.ts
harbor-app/src/app/shared/shared.module.ts

Complete account settings component

Complete account settings component

---

make/common/templates/notary/server-config.json
make/common/templates/registry/config.yml
src/common/utils/test/adminserver.go
src/ui/main.go
src/ui/service/token/authutils.go
src/ui/service/token/creator.go
src/ui/service/token/token.go
src/ui/service/token/token_test.go
src/ui/service/token/validator.go

Due to the implementation in Docker client, seems it use the token for registry to access notary, I had use same token creator for both notary and registry, I will check the code of docker and discuss with them later.

Token service refactory

---

harbor-app/src/app/app.component.ts
harbor-app/src/app/base/auth-guard.service.ts
harbor-app/src/app/base/base-routing-resolver.service.ts
harbor-app/src/app/base/base-routing.module.ts
harbor-app/src/app/base/harbor-shell/harbor-shell.component.html
harbor-app/src/app/base/harbor-shell/harbor-shell.component.ts
harbor-app/src/app/base/navigator/navigator.component.html
harbor-app/src/app/base/navigator/navigator.component.ts
harbor-app/src/app/i18n/lang/en-lang.json
harbor-app/src/app/i18n/lang/zh-lang.json
harbor-app/src/app/shared/deletion-dialog/deletion-dialog.component.css
harbor-app/src/app/shared/deletion-dialog/deletion-dialog.component.html
harbor-app/src/app/shared/deletion-dialog/deletion-dialog.component.ts
harbor-app/src/app/shared/deletion-dialog/deletion-dialog.service.ts
harbor-app/src/app/shared/deletion-dialog/deletion-message.ts
harbor-app/src/app/shared/shared.module.ts
harbor-app/src/app/user/user.component.html
harbor-app/src/app/user/user.component.ts

add deltion dialog

---

harbor-app/src/app/account/account-settings/account-settings-modal.component.html
harbor-app/src/app/account/account-settings/account-settings-modal.component.ts
harbor-app/src/app/account/password/password-setting.component.html
harbor-app/src/app/account/password/password-setting.component.ts
harbor-app/src/app/account/sign-in/sign-in.component.html
harbor-app/src/app/account/sign-in/sign-in.component.ts
harbor-app/src/app/account/sign-in/sign-in.service.ts
harbor-app/src/app/base/harbor-shell/harbor-shell.component.html
harbor-app/src/app/global-message/message.component.html
harbor-app/src/app/global-message/message.component.ts
harbor-app/src/app/global-message/message.ts
harbor-app/src/app/i18n/lang/en-lang.json
harbor-app/src/app/i18n/lang/zh-lang.json
harbor-app/src/app/project/action-project/action-project.component.ts
harbor-app/src/app/project/member/member.component.ts
harbor-app/src/app/shared/deletion-dialog/deletion-dialog.component.ts
harbor-app/src/app/shared/deletion-dialog/deletion-dialog.service.ts
harbor-app/src/app/shared/deletion-dialog/deletion-message.ts
harbor-app/src/app/shared/session.service.ts
harbor-app/src/app/shared/shared.const.ts
harbor-app/src/app/shared/shared.utils.ts
harbor-app/src/app/user/new-user-form.component.html
harbor-app/src/app/user/new-user-form.component.ts
harbor-app/src/app/user/new-user-modal.component.html
harbor-app/src/app/user/new-user-modal.component.ts
harbor-app/src/app/user/user.component.ts

refine existing functionalities

refine existing functionalities

---

make/common/templates/adminserver/env
make/harbor.cfg
src/adminserver/systemcfg/systemcfg.go
src/common/utils/test/adminserver.go
src/jobservice/config/config.go
src/jobservice/config/config_test.go
src/jobservice/utils/logger.go

Read some configs from env when start up

---

harbor-app/src/app/app.module.ts
harbor-app/src/app/base/harbor-shell/harbor-shell.component.html
harbor-app/src/app/config/auth/config-auth.component.html
harbor-app/src/app/config/auth/config-auth.component.ts
harbor-app/src/app/config/config.component.html
harbor-app/src/app/config/config.component.ts
harbor-app/src/app/config/config.module.ts
harbor-app/src/app/config/config.service.ts
harbor-app/src/app/config/config.ts
harbor-app/src/app/config/email/config-email.component.html
harbor-app/src/app/config/email/config-email.component.ts
harbor-app/src/app/harbor-routing.module.ts
harbor-app/src/app/shared/deletion-dialog/deletion-dialog.component.ts
harbor-app/src/ng/i18n/lang/en-lang.json
harbor-app/src/ng/i18n/lang/zh-lang.json

implement configuration with clarity

implement configuration with clarity

---

harbor-app/src/app/replication/create-edit-destination/create-edit-destination.component.html
harbor-app/src/app/replication/create-edit-destination/create-edit-destination.component.ts
harbor-app/src/app/replication/destination/destination.component.html
harbor-app/src/app/replication/destination/destination.component.ts
harbor-app/src/app/replication/replication.module.ts
harbor-app/src/app/replication/replication.service.ts
harbor-app/src/app/replication/total-replication/total-replication.component.html
harbor-app/src/app/shared/create-edit-policy/create-edit-policy.component.ts
harbor-app/src/app/shared/list-policy/list-policy.component.ts
harbor-app/src/app/shared/shared.const.ts
harbor-app/src/ng/i18n/lang/en-lang.json
harbor-app/src/ng/i18n/lang/zh-lang.json

Add destination component of UI and updates for replication related.

Add destination component of UI and updates for replication related.

---

harbor-app/src/app/config/auth/config-auth.component.html
harbor-app/src/app/config/auth/config-auth.component.ts
harbor-app/src/app/config/config.component.html
harbor-app/src/app/config/config.component.ts
harbor-app/src/app/config/email/config-email.component.html
harbor-app/src/app/config/email/config-email.component.ts
harbor-app/src/app/shared/port.directive.ts
harbor-app/src/app/shared/shared.module.ts
harbor-app/src/ng/i18n/lang/en-lang.json
harbor-app/src/ng/i18n/lang/zh-lang.json

refine config

---

harbor-app/src/app/harbor-routing.module.ts
harbor-app/src/app/shared/not-found/not-found.component.css
harbor-app/src/app/shared/not-found/not-found.component.html
harbor-app/src/app/shared/not-found/not-found.component.ts
harbor-app/src/app/shared/shared.module.ts
harbor-app/src/ng/i18n/lang/en-lang.json
harbor-app/src/ng/i18n/lang/zh-lang.json

implement page not found

---

harbor-app/src/app/base/harbor-shell/harbor-shell.component.html
harbor-app/src/app/base/harbor-shell/harbor-shell.component.ts
harbor-app/src/app/base/modal-event.ts
harbor-app/src/app/base/modal-events.const.ts
harbor-app/src/app/base/navigator/navigator.component.html
harbor-app/src/app/base/navigator/navigator.component.ts
harbor-app/src/app/shared/about-dialog/about-dialog.component.css
harbor-app/src/app/shared/about-dialog/about-dialog.component.html
harbor-app/src/app/shared/about-dialog/about-dialog.component.ts
harbor-app/src/app/shared/shared.module.ts
harbor-app/src/ng/i18n/lang/en-lang.json
harbor-app/src/ng/i18n/lang/zh-lang.json

add about dialog for both authorized and unauthorized users

add about dialog for both authorized and unauthorized users

---

harbor-app/src/app/i18n/missing-trans.handler.ts

fix missing text key issue (cont.)

---

Makefile

to support compile clarity with make.
Usage: make install -e CLARITYIMAGE=danieljt/harbor-clarity-base:0.8.3 GOBUILDIMAGE=reg-bj.eng.vmware.com/harborrelease/harborgo:1.6.2 COMPILETAG=compile_golangimage

make support clarity

---

.travis.yml

https://travis-ci.org/reasonerjt/harbor/builds/209231170
it takes 8min25sec :)

Test accelerate

---

harbor-app/src/app/config/auth/config-auth.component.html
harbor-app/src/app/config/config.component.html
harbor-app/src/ng/i18n/lang/en-lang.json
harbor-app/src/ng/i18n/lang/zh-lang.json

add more tooltips for configurations

add more tooltips for configurations

---

Makefile
make/install.sh

Will create an new PR for install.sh script to support Nortary.

to support nortary

---

harbor-app/src/app/account/account-settings/account-settings-modal.component.ts
harbor-app/src/app/account/password/password-setting.component.ts
harbor-app/src/app/account/sign-up/sign-up.component.ts

fix some ui bugs

---

harbor-app/src/app/account/password/password-setting.service.ts
harbor-app/src/app/account/password/reset-password.component.ts
harbor-app/src/app/config/auth/config-auth.component.html
harbor-app/src/app/config/auth/config-auth.component.ts
harbor-app/src/app/config/config.component.html
harbor-app/src/app/config/config.component.ts
harbor-app/src/app/config/config.service.ts
harbor-app/src/app/config/email/config-email.component.html
harbor-app/src/app/harbor-routing.module.ts
harbor-app/src/ng/i18n/lang/en-lang.json
harbor-app/src/ng/i18n/lang/zh-lang.json

fix test mail and ldap

---

harbor-app/src/app/account/sign-in/sign-in.component.html
harbor-app/src/app/account/sign-in/sign-in.component.ts
harbor-app/src/app/app.component.ts
harbor-app/src/app/base/navigator/navigator.component.html
harbor-app/src/app/base/navigator/navigator.component.ts
harbor-app/src/app/config/config.component.ts
harbor-app/src/app/harbor-routing.module.ts
harbor-app/src/index.html

fix some integration mode issues

fix some integration mode issues

---

src/ui_ng/proxy.config.json
src/ui_ng/src/app/harbor-routing.module.ts

fix dashboard route issue

---

harbor-app/src/app/account/account.module.ts
harbor-app/src/app/account/sign-in/sign-in.component.css
harbor-app/src/app/account/sign-in/sign-in.component.html
harbor-app/src/app/base/harbor-shell/harbor-shell.component.css
harbor-app/src/app/base/harbor-shell/harbor-shell.component.html
harbor-app/src/app/base/harbor-shell/harbor-shell.component.ts
harbor-app/src/app/base/navigator/navigator.component.html
harbor-app/src/app/base/navigator/navigator.component.ts
harbor-app/src/app/harbor-routing.module.ts
harbor-app/src/app/project/list-project/list-project.component.ts
harbor-app/src/app/project/project-detail/project-detail.component.html
harbor-app/src/app/project/project-detail/project-detail.component.ts
harbor-app/src/app/repository/list-repository/list-repository.component.ts
harbor-app/src/app/repository/tag-repository/tag-repository.component.ts
harbor-app/src/app/repository/top-repo/top-repo.component.css
harbor-app/src/app/repository/top-repo/top-repo.component.html
harbor-app/src/app/repository/top-repo/top-repo.component.ts
harbor-app/src/app/shared/route/auth-user-activate.service.ts
harbor-app/src/app/shared/route/system-admin-activate.service.ts
harbor-app/src/i18n/lang/en-lang.json
harbor-app/src/i18n/lang/zh-lang.json

remove dashboard and refine sign-in

remove dashboard and refine sign-in

---

harbor-app/src/app/shared/inline-alert/inline-alert.component.html
harbor-app/src/app/shared/inline-alert/inline-alert.component.ts
harbor-app/src/i18n/lang/en-lang.json
harbor-app/src/i18n/lang/zh-lang.json

fix issue 1662

---

harbor-app/src/app/account/account-settings/account-settings-modal.component.ts
harbor-app/src/app/base/global-search/global-search.component.ts
harbor-app/src/app/base/global-search/search-result.component.css
harbor-app/src/app/base/global-search/search-result.component.html
harbor-app/src/app/base/global-search/search-result.component.ts
harbor-app/src/app/shared/new-user-form/new-user-form.component.ts
harbor-app/src/i18n/lang/en-lang.json
harbor-app/src/i18n/lang/zh-lang.json

fix issue issue 1633 and issue 1591

fix issue issue 1633 and issue 1591

---

harbor-app/src/app/app-config.service.ts
harbor-app/src/app/base/navigator/navigator.component.ts
harbor-app/src/app/global-message/message.component.ts
harbor-app/src/app/shared/route/auth-user-activate.service.ts
harbor-app/src/app/shared/shared.const.ts
harbor-app/src/app/shared/shared.utils.ts

fix issue of integration mode

---

src/adminserver/api/cfg_test.go
src/adminserver/client/auth/auth.go
src/adminserver/client/auth/auth_test.go
src/adminserver/client/client.go
src/adminserver/client/client_test.go
src/adminserver/systemcfg/systemcfg.go
src/adminserver/systemcfg/systemcfg_test.go
src/common/config/config.go
src/common/const.go
src/common/utils/ldap/ldap_test.go
src/common/utils/test/adminserver.go
src/jobservice/config/config.go
src/ui/api/config.go
src/ui/api/config_test.go
src/ui/api/systeminfo.go
src/ui/auth/ldap/ldap_test.go
src/ui/config/config.go

I move some const variable to another package to avoid package import cycle.

Abstract adminserver client into a single package

---

harbor-app/src/app/account/password/password-setting.component.html
harbor-app/src/app/account/password/password-setting.component.ts
harbor-app/src/app/base/modal-event.ts
harbor-app/src/app/base/navigator/navigator.component.html
harbor-app/src/app/base/navigator/navigator.component.ts
harbor-app/src/app/common.css
harbor-app/src/app/repository/list-repository/list-repository.component.html
harbor-app/src/app/shared/new-user-form/new-user-form.component.css
harbor-app/src/app/shared/new-user-form/new-user-form.component.html
harbor-app/src/i18n/lang/en-lang.json
harbor-app/src/i18n/lang/zh-lang.json

fix issue 1697 from harbor side and refine sign-up modal
1697 is still blocked by Clarity bug

fix issue 1697 from harbor side and refine sign-up modal

---

Makefile
make/common/templates/notary/mysql-initdb.d/initial-notaryserver.sql
make/common/templates/notary/mysql-initdb.d/initial-notarysigner.sql
make/docker-compose.notary.yml

Had to build a new package to update a configuration in my.cnf.

restrict access to notary db

---

harbor-app/src/app/log/recent-log.component.ts
harbor-app/src/app/shared/filter/filter.component.ts

fix issue #1747 and #1767

---

harbor-app/src/app/base/global-search/global-search.component.html
harbor-app/src/app/base/global-search/global-search.component.ts
harbor-app/src/app/base/global-search/search-result.component.ts
harbor-app/src/app/base/global-search/search-trigger.service.ts
harbor-app/src/app/base/harbor-shell/harbor-shell.component.html
harbor-app/src/app/base/harbor-shell/harbor-shell.component.ts
harbor-app/src/app/base/navigator/navigator.component.ts
harbor-app/src/app/project/list-project/list-project.component.ts
harbor-app/src/app/repository/list-repository/list-repository.component.ts

Fix #1739: Clear the search term when result pane closing

Fix #1739: Clear the search term when result pane closing

---

harbor-app/src/app/base/global-search/search-result.component.html
harbor-app/src/app/project/list-project/list-project.component.ts
harbor-app/src/app/repository/top-repo/top-repo.component.html
harbor-app/src/app/shared/list-project-ro/list-project-ro.component.html
harbor-app/src/app/shared/list-project-ro/list-project-ro.component.ts
harbor-app/src/app/shared/list-repository-ro/list-repository-ro.component.html
harbor-app/src/app/shared/list-repository-ro/list-repository-ro.component.ts
harbor-app/src/app/shared/route/auth-user-activate.service.ts
harbor-app/src/app/shared/shared.module.ts

fix issue #1693: create read-only datagrid for search and top repo

fix issue #1693: create read-only datagrid for search and top repo

---

harbor-app/package.json
harbor-app/src/app/config/config.component.ts

fix issue #1765

---

harbor-app/src/app/log/recent-log.component.css
harbor-app/src/app/log/recent-log.component.html
harbor-app/src/app/shared/about-dialog/about-dialog.component.css
harbor-app/src/app/shared/about-dialog/about-dialog.component.html
harbor-app/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
harbor-app/src/i18n/lang/en-lang.json
harbor-app/src/i18n/lang/zh-lang.json

fix issues: #1708 #1797 #1798 #1724 #1800

fix issues: #1708 #1797 #1798 #1724 #1800

---

make/prepare
src/common/utils/notary/helper.go

This should fix the key mismatch issues on notary after redeploy

Do not generate new alias each time prepare runs

---

harbor-app/src/app/base/navigator/navigator.component.html
harbor-app/src/app/base/navigator/navigator.component.ts
harbor-app/src/i18n/lang/en-lang.json
harbor-app/src/i18n/lang/zh-lang.json

change title when harbor is in integration mode

change title when harbor is in integration mode

---

.gitignore
src/ui_ng/src/app/account/sign-in/sign-in.component.html
src/ui_ng/src/app/account/sign-in/sign-in.component.ts
src/ui_ng/src/app/app-config.ts
src/ui_ng/src/app/base/navigator/navigator.component.html
src/ui_ng/src/app/base/navigator/navigator.component.ts
src/ui_ng/src/i18n/lang/en-lang.json
src/ui_ng/src/i18n/lang/zh-lang.json

support 'remember me' and root cert downloading

---

src/ui_ng/src/app/account/account-settings/account-settings-modal.component.ts
src/ui_ng/src/app/account/password/password-setting.component.ts
src/ui_ng/src/app/account/password/reset-password.component.ts
src/ui_ng/src/app/account/sign-up/sign-up.component.ts
src/ui_ng/src/app/base/global-search/search-result.component.ts
src/ui_ng/src/app/base/navigator/navigator.component.ts
src/ui_ng/src/app/config/config.component.ts
src/ui_ng/src/app/shared/inline-alert/inline-alert.component.ts
src/ui_ng/src/app/shared/message-handler/message-handler.service.ts
src/ui_ng/src/app/shared/session.service.ts
src/ui_ng/src/app/shared/shared.utils.ts
src/ui_ng/src/app/shared/statictics/statistics-panel.component.ts
src/ui_ng/src/i18n/lang/en-lang.json
src/ui_ng/src/i18n/lang/zh-lang.json

Fixed issue #1694, #1761, #1707
applied unique message handler and fix signin issue when code is 401

Fixed issue #1694, #1761, #1707

---

src/ui_ng/src/app/account/account-settings/account-settings-modal.component.html
src/ui_ng/src/app/account/account-settings/account-settings-modal.component.ts
src/ui_ng/src/app/account/password/password-setting.component.html
src/ui_ng/src/app/account/sign-up/sign-up.component.html
src/ui_ng/src/app/app-config.ts
src/ui_ng/src/app/shared/about-dialog/about-dialog.component.html
src/ui_ng/src/app/shared/about-dialog/about-dialog.component.ts
src/ui_ng/src/app/shared/inline-alert/inline-alert.component.css
src/ui_ng/src/app/shared/inline-alert/inline-alert.component.html
src/ui_ng/src/app/shared/inline-alert/inline-alert.component.ts
src/ui_ng/src/app/shared/statictics/statistics-panel.component.html
src/ui_ng/src/app/shared/statictics/statistics-panel.component.ts
src/ui_ng/src/app/shared/statictics/statistics.component.css
src/ui_ng/src/app/user/new-user-modal.component.html
src/ui_ng/src/app/user/user.component.html
src/ui_ng/src/app/user/user.component.ts

Fix issue 1795

---

src/ui_ng/src/app/account/account-settings/account-settings-modal.component.ts
src/ui_ng/src/app/account/password/forgot-password.component.html
src/ui_ng/src/app/account/password/forgot-password.component.ts
src/ui_ng/src/app/account/password/password-setting.component.ts
src/ui_ng/src/app/account/password/reset-password.component.html
src/ui_ng/src/app/account/password/reset-password.component.ts
src/ui_ng/src/app/account/sign-in/sign-in.component.ts
src/ui_ng/src/app/account/sign-up/sign-up.component.ts
src/ui_ng/src/app/base/navigator/navigator.component.html
src/ui_ng/src/app/base/navigator/navigator.component.ts
src/ui_ng/src/app/common.css
src/ui_ng/src/app/config/auth/config-auth.component.html
src/ui_ng/src/app/config/auth/config-auth.component.ts
src/ui_ng/src/app/config/config.component.ts
src/ui_ng/src/app/log/recent-log.component.ts
src/ui_ng/src/app/shared/new-user-form/new-user-form.component.ts
src/ui_ng/src/app/shared/route/auth-user-activate.service.ts
src/ui_ng/src/app/shared/route/sign-in-guard-activate.service.ts
src/ui_ng/src/app/user/new-user-modal.component.ts
src/ui_ng/src/app/user/user.component.html
src/ui_ng/src/i18n/lang/en-lang.json
src/ui_ng/src/i18n/lang/zh-lang.json

Fix #1831, #1833, #1837, #1840, #1844, #1842, #1843, #1841, #1810

Fix issues

---

src/ui_ng/src/app/account/account-settings/account-settings-modal.component.html
src/ui_ng/src/app/account/password/forgot-password.component.html
src/ui_ng/src/app/account/password/password-setting.component.html
src/ui_ng/src/app/account/password/reset-password.component.html
src/ui_ng/src/app/account/sign-up/sign-up.component.ts
src/ui_ng/src/app/project/member/member.component.html
src/ui_ng/src/app/project/project.component.html
src/ui_ng/src/app/replication/destination/destination.component.html
src/ui_ng/src/app/replication/replication.component.html
src/ui_ng/src/app/shared/about-dialog/about-dialog.component.html
src/ui_ng/src/app/shared/new-user-form/new-user-form.component.html
src/ui_ng/src/app/user/user.component.html

Fix issues #1685 #1638 and applied new regexp patterns for mail and password validations.

Fix UI issues

---

src/ui_ng/src/app/account/account-settings/account-settings-modal.component.html
src/ui_ng/src/app/account/password/reset-password.component.html
src/ui_ng/src/app/account/password/reset-password.component.ts
src/ui_ng/src/app/account/sign-in/sign-in.component.ts
src/ui_ng/src/app/shared/email.directive.ts
src/ui_ng/src/app/shared/new-user-form/new-user-form.component.html
src/ui_ng/src/app/shared/shared.module.ts
src/ui_ng/src/app/user/user.component.ts
src/ui_ng/src/app/user/user.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Fix issue #1860 and other minor things

Fix issue #1860 and other minor things

---

src/ui_ng/src/app/account/password/password-setting.component.ts
src/ui_ng/src/app/account/password/reset-password.component.ts
src/ui_ng/src/app/account/sign-in/sign-in.component.css
src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.css
src/ui_ng/src/app/base/navigator/navigator.component.ts
src/ui_ng/src/app/project/project.component.html
src/ui_ng/src/app/project/project.component.ts
src/ui_ng/src/app/replication/destination/destination.component.ts
src/ui_ng/src/app/replication/replication.component.ts
src/ui_ng/src/app/replication/replication.service.ts
src/ui_ng/src/app/replication/total-replication/total-replication.component.ts
src/ui_ng/src/app/shared/gauge/gauge.component.ts
src/ui_ng/src/app/shared/new-user-form/new-user-form.component.ts
src/ui_ng/src/app/shared/route/auth-user-activate.service.ts
src/ui_ng/src/app/shared/route/sign-in-guard-activate.service.ts
src/ui_ng/src/app/shared/session.service.ts
src/ui_ng/src/app/shared/shared.module.ts
src/ui_ng/src/app/shared/statictics/statistic-handler.service.ts
src/ui_ng/src/app/shared/statictics/statistics-panel.component.ts
src/ui_ng/src/app/shared/statictics/statistics.component.css
src/ui_ng/src/index.html
src/ui_ng/src/styles.css

Fix issues: #1615 #1897 #1687 #1874 #1824

Fix related UI bugs

---

src/ui_ng/src/app/project/member/member.component.css
src/ui_ng/src/app/project/project.component.html
src/ui_ng/src/app/project/project.component.ts

Related issues are #1904, #1899

Fix some UX issues.

---

src/ui_ng/angular-cli.json
src/ui_ng/src/app/shared/gauge/gauge.component.html
src/ui_ng/src/app/shared/gauge/gauge.component.ts
src/ui_ng/src/app/shared/statictics/statistics-panel.component.html

Fix issue 1915

---

src/ui/views/index.html
src/ui_ng/package.json
src/ui_ng/src/app/account/account-settings/account-settings-modal.component.html
src/ui_ng/src/app/account/password/forgot-password.component.html
src/ui_ng/src/app/account/password/password-setting.component.html
src/ui_ng/src/app/account/password/reset-password.component.html
src/ui_ng/src/app/account/password/reset-password.component.ts
src/ui_ng/src/app/account/sign-in/sign-in.component.css
src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.css
src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.html
src/ui_ng/src/app/config/config.component.html
src/ui_ng/src/app/config/config.component.ts
src/ui_ng/src/app/global-message/message.component.ts
src/ui_ng/src/app/project/project.component.html
src/ui_ng/src/app/shared/gauge/gauge.component.css
src/ui_ng/src/app/shared/new-user-form/new-user-form.component.html
src/ui_ng/src/app/shared/statictics/statistics-panel.component.html

Fix issue #1930 #1925 #1923 #1920

Fix UI/UX issues

---

src/ui_ng/src/app/account/password/forgot-password.component.html
src/ui_ng/src/app/account/password/password-setting.component.html
src/ui_ng/src/app/shared/about-dialog/about-dialog.component.html
src/ui_ng/src/app/shared/gauge/gauge.component.css
src/ui_ng/src/app/shared/new-user-form/new-user-form.component.html

adjust the size of inputbox in related forms

adjust the size of inputbox in related forms

---

src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.css
src/ui_ng/src/app/shared/gauge/gauge.component.css
src/ui_ng/src/app/shared/statictics/statistics.component.css
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

update message files

---

src/ui_ng/src/app/project/project-detail/project-detail.component.html
src/ui_ng/src/app/project/project-routing-resolver.service.ts

Make role name consistent.

---

src/ui_ng/src/app/account/sign-in/sign-in.component.html
src/ui_ng/src/app/account/sign-in/sign-in.component.ts
src/ui_ng/src/app/shared/about-dialog/about-dialog.component.html
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Translate COPYRIGHT message to zh
Refine sign-in form validation

Fix ui bugs

---

src/ui/controllers/error.go
src/ui/router.go
src/ui/views/404.tpl

customize beego 404

---

src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

amend typo in copyright declaration

amend typo in copyright declaration

---

src/ui_ng/src/app/account/sign-in/sign-in.component.ts
src/ui_ng/src/app/app.component.ts
src/ui_ng/src/app/base/global-search/global-search.component.html
src/ui_ng/src/app/base/global-search/global-search.component.ts
src/ui_ng/src/app/base/navigator/navigator.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json
src/ui_ng/src/index.html

Override page title and search placeholder when in VIC mode

Override page title and search placeholder when in VIC mode

---

tests/testcases/Group9-Content-trust/9-01-DB-user-push-signed-images.md
tests/testcases/Group9-Content-trust/9-02-DB-user-push-unsigned-images.md
tests/testcases/Group9-Content-trust/9-03-DB-user-pull-signed-images.md
tests/testcases/Group9-Content-trust/9-04-DB-user-pull-unsigned-images.md
tests/testcases/Group9-Content-trust/9-05-DB-user-delete-signed-images.md
tests/testcases/Group9-Content-trust/9-11-LDAP-user-push-signed-images.md
tests/testcases/Group9-Content-trust/9-12-LDAP-user-push-unsigned-images.md
tests/testcases/Group9-Content-trust/9-13-LDAP-user-pull-signed-images.md
tests/testcases/Group9-Content-trust/9-14-LDAP-user-pull-unsigned-images.md
tests/testcases/Group9-Content-trust/9-15-LDAP-user-delete-signed-images.md

update content trust test case

update content trust test case

---

docs/configure_https.md
docs/customize_token_service.md

fix markdown

---

Makefile
docs/compile_guide.md
make/dev/docker-compose-clarity.yml
make/dev/docker-compose.yml
make/dev/ui/Dockerfile
make/docker-compose-clarity.yml

update compile document

---

.gitignore
docs/developer_guide_i18n.md

update i18 development guide document

update i18 development guide document

---

tests/testcases/Group8-Configuration/8-01-Authentication-edit-authentication.md
tests/testcases/Group8-Configuration/8-02-Authentication-edit-project-creation-restriction.md
tests/testcases/Group8-Configuration/8-03-Authentication-edit-self-registration.md
tests/testcases/Group8-Configuration/8-04-Replication-edit-verify-remote-certificate.md
tests/testcases/Group8-Configuration/8-05-Email-edit-email-settings.md

update configuration test case

update configuration test case

---

Makefile
make/dev/nodeclarity/Dockerfile
make/dev/nodeclarity/entrypoint.sh

make refresh_clarity_builder -e REBUILDCLIATRYFLAG=true NEWCLARITYVERSION=1.1.0 REGISTRYUSER=******* REGISTRYPASSWORD=******* HTTPPROXY=http:\\/\\/*********

add clarity support

---

src/ui_ng/src/app/base/navigator/navigator.component.ts

Allow admin to change password when auth mode is 'ldap_auth'

Allow admin to change password when auth mode is 'ldap_auth'

---

src/ui_ng/src/app/account/sign-in/sign-in.component.css
src/ui_ng/src/app/account/sign-in/sign-in.component.html
src/ui_ng/src/app/base/global-search/global-search.component.ts
src/ui_ng/src/app/base/global-search/search-result.component.ts
src/ui_ng/src/app/base/global-search/search.component.css
src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.css
src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.html
src/ui_ng/src/app/base/navigator/navigator.component.css
src/ui_ng/src/app/base/navigator/navigator.component.html

Fix UX issues

---

src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.css
src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.html
src/ui_ng/src/app/global-message/message.component.css
src/ui_ng/src/app/global-message/message.component.html
src/ui_ng/src/app/global-message/message.component.ts
src/ui_ng/src/app/shared/shared.const.ts
src/ui_ng/src/styles.css

Change the alert style to global style: #1923

Change the alert style to global style

---

src/ui_ng/src/app/base/global-search/search.component.css
src/ui_ng/src/app/global-message/message.component.css

fix nav divider style issue #2137 #2138

fix nav divider style issue

---

.gitignore
src/ui_ng/lib/package.json
src/ui_ng/lib/src/harbor-library.module.ts

Enhance the module configuration of harbor ui

Enhance the module configuration of harbor ui

---

src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/rollup.config.js
src/ui_ng/lib/src/log/recent-log.component.spec.ts
src/ui_ng/lib/src/log/recent-log.template.ts

Add test spec for log component

Add test spec for log component

---

src/ui_ng/lib/package.json
src/ui_ng/lib/src/harbor-library.module.ts
src/ui_ng/lib/src/i18n/lang/en-us-lang.ts
src/ui_ng/lib/src/i18n/lang/es-es-lang.ts
src/ui_ng/lib/src/i18n/lang/zh-cn-lang.ts
src/ui_ng/lib/src/i18n/local-json.loader.ts
src/ui_ng/lib/src/i18n/translate.spec.ts
src/ui_ng/lib/src/shared/shared.module.ts

Use local json loader for ngx-translate

Use local json loader for ngx-translate

---

src/ui_ng/lib/src/service/access-log.service.ts
src/ui_ng/lib/src/service/interface.ts
src/ui_ng/lib/src/service/repository.service.spec.ts
src/ui_ng/lib/src/service/repository.service.ts
src/ui_ng/lib/src/utils.ts

Implement repository service interface

Implement repository service interface

---

src/ui_ng/lib/src/service/interface.ts
src/ui_ng/lib/src/service/tag.service.spec.ts
src/ui_ng/lib/src/service/tag.service.ts

Implement tag service interface

Implement tag service interface

---

src/ui_ng/lib/src/service/access-log.service.spec.ts
src/ui_ng/lib/src/service/interface.ts
src/ui_ng/lib/src/service/replication.service.spec.ts
src/ui_ng/lib/src/service/replication.service.ts
src/ui_ng/lib/src/service/repository.service.spec.ts
src/ui_ng/lib/src/service/tag.service.spec.ts

Implement replication service interface

Implement replication service interface

---

docs/compile_guide.md

Modify the harbor-clarity-ui-builder's version in docs/compile_guide.md.
See issue #2306.

modify the harbor-clarity-ui-builder's version in docs

---

src/ui_ng/lib/package.json
src/ui_ng/lib/src/harbor-library.module.ts
src/ui_ng/lib/src/i18n/lang/en-us-lang.ts
src/ui_ng/lib/src/i18n/lang/es-es-lang.ts
src/ui_ng/lib/src/i18n/lang/zh-cn-lang.ts
src/ui_ng/lib/src/index.ts
src/ui_ng/lib/src/log/recent-log.component.spec.ts
src/ui_ng/lib/src/polyfills.ts
src/ui_ng/lib/src/service.config.ts
src/ui_ng/lib/src/service/index.ts
src/ui_ng/lib/src/service/interface.ts
src/ui_ng/lib/src/service/scanning.service.spec.ts
src/ui_ng/lib/src/service/scanning.service.ts
src/ui_ng/lib/src/vulnerability-scanning/index.ts
src/ui_ng/lib/src/vulnerability-scanning/result-bar-chart.component.spec.ts
src/ui_ng/lib/src/vulnerability-scanning/result-bar-chart.component.ts
src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.spec.ts
src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.ts
src/ui_ng/lib/src/vulnerability-scanning/result-tip.component.spec.ts
src/ui_ng/lib/src/vulnerability-scanning/result-tip.component.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.css.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts

It is implemented based on current design, might have some changes later.

Implement vulnerability scanning components [unstable]

---

src/ui_ng/lib/README.md

Add integration guideline document for harbor UI library

Add integration guideline document for harbor UI library

---

src/ui_ng/src/app/user/user.component.html
src/ui_ng/src/app/user/user.component.ts

enable pagination for user list

enable pagination for user list

---

src/ui_ng/src/app/user/user.component.html
src/ui_ng/src/app/user/user.component.ts

fix conflicts between 1.1.0 and master

fix conflicts between 1.1.0 and master

---

src/ui_ng/src/app/user/user.component.html
src/ui_ng/src/app/user/user.component.ts

use *ngFor to replace *clrDgItems in user datagird

use *ngFor to replace *clrDgItems in user datagird

---

tests/robot-cases/Group8-Configuration/8-01-edit-authentacation.robot
tests/robot-cases/Group8-Configuration/8-02-edit-project-creat.robot
tests/robot-cases/Group8-Configuration/8-03-edit-self-registration.robot
tests/robot-cases/Group8-Configuration/8-04-edit-verify-remote-cert.robot
tests/robot-cases/Group8-Configuration/8-05-edit-email-settings.robot
tests/robot-cases/Group8-Configuration/8-06-edit-token-expire.robot

configuration case

---

src/ui_ng/src/app/user/user.component.html
src/ui_ng/src/app/user/user.component.ts

Merge fix code from 1.1.0 branch back to master

Merge fix code from 1.1.0 branch back to master

---

tests/resources/Harbor-Pages/Administration-Users.robot

update assign admin xpath

---

tests/robot-cases/Group0-BAT/BAT.robot
tests/robot-cases/Group8-Configuration/8-02-edit-project-creat.robot

[BAT]update project create step

---

.travis.yml
Makefile
docs/compile_guide.md
make/dev/nodeclarity/Dockerfile
make/dev/nodeclarity/entrypoint.sh
src/ui_ng/lib/src/repository-stackview/repository-stackview.component.css.ts
src/ui_ng/lib/src/tag/tag.component.css.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.css.ts
src/ui_ng/package.json
src/ui_ng/src/app/project/list-project/list-project.component.html
src/ui_ng/src/app/project/list-project/list-project.component.ts
src/ui_ng/src/app/project/project.component.html
src/ui_ng/src/app/project/project.component.ts
src/ui_ng/src/app/user/user.component.ts
tests/run-clarity-ut.sh

Update UI builder to 1.2.5

---

Makefile
make/common/postgresql/Dockerfile
make/common/postgresql/docker-entrypoint.sh
make/docker-compose.clair.yml

fix  https://github.com/vmware/harbor/issues/2628

Update clair postgresql to use photon os

---

.travis.yml
docs/compile_guide.md
make/dev/nodeclarity/entrypoint.sh

Upgrade UI builder to 1.2.7

---

make/common/templates/clair/postgresql-init.d/README.md
make/docker-compose.clair.yml
make/prepare

Support include offline data on clair startup

Support include offline data on clair startup

---

Makefile
make/common/nginx/Dockerfile
make/docker-compose.tpl

Move nginx to photon OS

---

src/ui_ng/lib/src/config/config.ts
src/ui_ng/lib/src/config/index.ts
src/ui_ng/lib/src/config/registry-config.component.html.ts
src/ui_ng/lib/src/config/registry-config.component.spec.ts
src/ui_ng/lib/src/config/registry-config.component.ts
src/ui_ng/lib/src/config/replication/replication-config.component.html.ts
src/ui_ng/lib/src/config/replication/replication-config.component.ts
src/ui_ng/lib/src/config/system/system-settings.component.html.ts
src/ui_ng/lib/src/config/system/system-settings.component.ts
src/ui_ng/lib/src/config/vulnerability/vulnerability-config.component.template.ts
src/ui_ng/lib/src/config/vulnerability/vulnerability-config.component.ts
src/ui_ng/lib/src/harbor-library.module.ts
src/ui_ng/lib/src/index.ts
src/ui_ng/lib/src/service.config.ts
src/ui_ng/lib/src/service/configuration.service.spec.ts
src/ui_ng/lib/src/service/configuration.service.ts
src/ui_ng/lib/src/service/index.ts
src/ui_ng/lib/src/service/scanning.service.ts
src/ui_ng/lib/src/vulnerability-scanning/result-tip.component.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts
src/ui_ng/package.json
src/ui_ng/src/app/config/auth/config-auth.component.ts
src/ui_ng/src/app/config/config.component.html
src/ui_ng/src/app/config/config.component.ts
src/ui_ng/src/app/config/config.service.ts
src/ui_ng/src/app/config/email/config-email.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Implement scan all policy configuration

Implement scan all policy configuration

---

make/common/db/registry.sql
make/common/db/registry_sqlite.sql
src/ui/api/user.go
tools/migration/db_meta.py

Some of our users can't login because their names are longer than 20 chars. This PR would fix this issue.

Allow 255 chars for Realname

---

tools/migration/changelog.md
tools/migration/migration_harbor/versions/1_2_0.py

update user realname

---

src/ui_ng/lib/src/tag/tag.component.ts

change the timeout in Tag's UI.
Because of following issue  #2703.

change tag retrive's timeout

---

src/common/const.go
src/common/dao/dao_test.go
src/common/dao/scan_job.go
src/common/models/clair.go
src/common/utils/clair/client.go
src/common/utils/clair/utils.go
src/jobservice/config/config.go
src/jobservice/scan/handlers.go
src/ui/api/config.go
src/ui/api/systeminfo.go
src/ui/config/config.go
src/ui/service/notifications/clair/handler.go

update scan overview in notification handler, and return clair vuln timestamp in system info api.
If looks OK, let's merge it for UI integration, and I will add more TC in following weeks.

clair notification handler enhancements

---

src/ui/proxy/interceptor_test.go
src/ui/proxy/interceptors.go

format error to make it readable for docker

---

src/ui_ng/lib/src/vulnerability-scanning/result-tip.component.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts
src/ui_ng/package.json
src/ui_ng/src/app/config/config.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json

Fix issue #2688 and #2686

---

make/common/templates/adminserver/env
make/harbor.cfg
make/prepare
src/adminserver/systemcfg/systemcfg.go
src/common/const.go
src/common/dao/base.go
src/ui/config/config.go
src/ui/main.go
src/ui/service/notifications/registry/handler.go

The password to access clair db can be configured in harbor.cfg, auto-scan if clair-db is not ready

The password to access clair db can be configured in harbor.cfg

---

src/common/notifier/config_watcher.go
src/common/notifier/notifier.go
src/common/scheduler/policy/alternate_policy.go
src/common/scheduler/watcher.go

Fix config change watching issue

Fix config change watching issue

---

src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/package.json

fix issue 2858

---

src/ui_ng/lib/src/vulnerability-scanning/result-tip.component.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.css.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts
src/ui_ng/package.json
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

fix issue #2832

---

src/ui_ng/lib/src/config/vulnerability/vulnerability-config.component.ts
src/ui_ng/package.json
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

fix issue #2811

---

docs/installation_guide.md

Refine installation guide to fix issue by user.

---

src/ui_ng/lib/src/config/registry-config.component.ts
src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.html.ts
src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
src/ui_ng/lib/src/endpoint/endpoint.component.ts
src/ui_ng/lib/src/tag/tag-detail.component.html.ts
src/ui_ng/lib/src/tag/tag-detail.component.spec.ts
src/ui_ng/lib/src/utils.ts
src/ui_ng/package.json
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json

fix issue #2435

---

src/ui_ng/lib/README.md
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.html.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
src/ui_ng/lib/src/replication/replication.component.html.ts
src/ui_ng/lib/src/replication/replication.component.ts
src/ui_ng/package.json

support read-ony mode for replication list view

support read-ony mode for replication list view

---

src/ui/controllers/index.go
src/ui/router.go

fix issue #2840 and #2916

---

src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.spec.ts
src/ui_ng/lib/src/replication/replication.component.html.ts
src/ui_ng/lib/src/replication/replication.component.spec.ts
src/ui_ng/lib/src/replication/replication.component.ts
src/ui_ng/lib/src/service/interface.ts
src/ui_ng/lib/src/service/replication.service.ts
src/ui_ng/lib/src/service/repository.service.ts
src/ui_ng/lib/src/vulnerability-scanning/result-tip.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/log/audit-log.component.html
src/ui_ng/src/app/log/audit-log.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Fix issue #2879

---

src/ui_ng/package.json

update ui library version to 0.3.92

update ui library version to 0.3.92

---

docs/configure_https.md

docs error

---

src/ui_ng/lib/pkg/package.json
src/ui_ng/package.json

upgrade ui lib version to 0.4.2

upgrade ui lib version to 0.4.2

---

make/common/templates/nginx/nginx.http.conf
make/common/templates/nginx/nginx.https.conf

to accelerate the speed to download image.
to mitigate the issue in #2936

Enable buffer on nginx

---

src/common/notifier/notifier.go
src/common/scheduler/policy/alternate_policy.go
src/common/scheduler/policy/alternate_policy_test.go
src/common/scheduler/policy/policy.go
src/common/scheduler/scheduler.go
src/common/scheduler/scheduler_store.go
src/common/scheduler/scheduler_store_test.go
src/common/scheduler/scheduler_test.go
src/common/scheduler/task/task_list.go
src/common/scheduler/task/task_list_test.go
src/common/scheduler/watcher.go
tests/coverage4gotest.sh

Fix issue #2762 
Fix data race issues of go sources

Fix data race issues of go sources

---

src/ui_ng/lib/package.json
src/ui_ng/package.json

update the library version

---

src/ui_ng/lib/README.md
src/ui_ng/lib/src/config/vulnerability/vulnerability-config.component.template.ts
src/ui_ng/lib/src/config/vulnerability/vulnerability-config.component.ts
src/ui_ng/lib/src/service/interface.ts
src/ui_ng/lib/src/tag/tag-detail.component.spec.ts
src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.spec.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts
src/ui_ng/package.json

add CVE link

---

Makefile
make/docker-compose.clair.yml

Update postgresql to 9.6.4

---

make/common/templates/clair/config.yaml
src/common/utils/timemarker.go

1, update the interval of clair updater to 12 hours
2, update the interval for scan all to 2 hours

Clair conf change

---

src/ui_ng/lib/src/config/system/system-settings.component.html.ts
src/ui_ng/lib/src/config/system/system-settings.component.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.html.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/base/navigator/navigator.component.html

Fix projetcId not ready and ca download link issues

---

make/common/templates/nginx/nginx.http.conf
make/common/templates/nginx/nginx.https.conf

Move the temp buffer folder for upload/download to /tmp directory.

Try to fix some wired permission error

---

tests/resources/Docker-Util.robot
tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/HomePage.robot
tests/resources/Harbor-Pages/Project-Members.robot
tests/resources/Harbor-Pages/Project-Members_Elements.robot
tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/UserProfile.robot
tests/robot-cases/Group0-BAT/BAT.robot

Refactory testcase for project member management
* Add some keyword for simplifying the case.
* Replace Test Case-Manage Project Member on `BAT.robot`
* Also put this case on file `3-03-DB-manage-project-members` in Group3-RBAC

refacotry testcase for project member manage

---

src/common/api/base.go

Correct spelling

---

make/kubernetes/adminserver/adminserver.rc.yaml
make/kubernetes/adminserver/adminserver.svc.yaml
make/kubernetes/jobservice/jobservice.rc.yaml
make/kubernetes/prepare
make/kubernetes/templates/adminserver.cm.yaml
make/kubernetes/templates/jobservice.cm.yaml
make/kubernetes/templates/ui.cm.yaml
make/kubernetes/ui/ui.rc.yaml

I use harbor on  k8s cluster.   
But current harbor repository doesn't have  adminserver's yaml file.  
I know 'k8s deployment' is now under development, but we want sample or PoC. 
see #3010

k8s deployment

---

src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/lib/src/vulnerability-scanning/result-tip.component.ts
src/ui_ng/package.json

Fix unkonwn package is 0 issue

---

docs/swagger.yaml

fix type error in swagger.yaml

---

tests/resources/Harbor-Pages/Project.robot
tests/robot-cases/Group0-BAT/BAT.robot

fix scan tag case

---

Makefile
make/common/postgresql/Dockerfile
make/docker-compose.clair.yml

1> update OSS in postgresql image
2> update postgresql to 9.6.5

Update OSS in postgresql image

---

tests/robot-cases/Group0-BAT/BAT.robot

add ldap case

---

make/photon/adminserver/Dockerfile

remove unneeded packages
move to vmware/photon images base

Update OSS packages in adminserver images

---

make/common/nginx/Dockerfile
make/common/templates/nginx/nginx.http.conf
make/common/templates/nginx/nginx.https.conf
make/common/templates/nginx/notary.server.conf

1>update nginx images OSS to latest
2>Fix nginx version issue

Update nginx images OSS to latest

---

src/ui_ng/lib/src/repository-stackview/repository-stackview.component.ts
src/ui_ng/src/app/project/list-project/list-project.component.html
src/ui_ng/src/app/project/list-project/list-project.component.ts
src/ui_ng/src/app/project/project.component.html
src/ui_ng/src/app/project/project.component.ts
src/ui_ng/src/app/shared/shared.utils.ts
tests/admiral.sh

This commit is to support the server end pagination in the project list view. It is already merged into the master branch before. As we're planning to release a new version 1.2.x, use cherry-pick to add it in 1.2.0 branch.

enable server end pagination for project list

---

.travis.yml
Makefile
make/common/mariadb/Dockerfile
make/common/mariadb/docker-entrypoint.sh
make/common/mariadb/my.cnf
make/docker-compose.notary.yml
tests/validatecontainers.sh

Also update the docker-compose template such that the notary db instance
will be provisioned via the mariadb-photon image.

Provide Dockerfile and artifacts for building mariadb on photon OS.

---

README.md

Update README, fix typo

---

make/photon/jobservice/Dockerfile

1>update OSS package in Job eservice images
2>use new photon base images

Update OSS package in Jobservice

---

make/common/rsyslog/Dockerfile
make/photon/log/Dockerfile

1> change to new photon base images
2> update OSS to latest

Update OSS in rsyslog images

---

.gitmessage
make/common/mariadb/docker-entrypoint.sh

Also removed some debug message in the entrypoint script.

Provide a template for git commit messages

---

tests/integration.sh

The tag is for CI to force upload a Harbor build into GS in pull request.

[Upload Build]Add a upload build flag in Drone CI

---

src/ui_ng/lib/src/vulnerability-scanning/result-tip.component.ts
src/ui_ng/package.json
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

fix the title of scanning bar when recognized package number is 0

fix text of bar chart title

---

make/photon/registry/Dockerfile

1>Change base image to vmware/photon
2>update oss pakcage and remove vim package.

Update registry image oss package to latest

---

make/photon/ui/Dockerfile

Update base image to photon
Remove vim from the image

Update UI image oss package to latest

---

src/ui_ng/lib/src/project-policy-config/project-policy-config.component.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/package.json
src/ui_ng/src/app/project/project-detail/project-detail.component.html
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

fix bug can't save new policies when it changed.

fix bug when save policies

---

src/common/notifier/scan_policy_notitification_handler.go
src/common/scheduler/policy/alternate_policy.go
src/common/scheduler/policy/alternate_policy_test.go
src/common/scheduler/policy/policy.go
src/common/scheduler/policy/uuid.go
src/common/scheduler/task/replication_task.go
src/common/scheduler/task/replication_task_test.go
src/common/scheduler/task/scan_all_task_test.go

Update the alternate policy and corresponding task to support by weekly besides daily

Update the alternate policy and corresponding task to support byweekly

---

Makefile
make/docker-compose.clair.yml
make/photon/clair/Dockerfile

1>update clair base iamges to vmware/photon:1.0
2>update oss packages to latest

Update Clair base images

---

src/replication/consts.go
src/replication/models/registry_models.go
src/replication/registry/adaptor.go
src/replication/registry/harbor_adaptor.go
src/replication/source/sourcer.go
src/replication/source/sourcer_test.go

Add registry adaptor interface and sourcer definitions

Add registry adaptor interface and sourcer definitions

---

tools/migration/db_meta.py
tools/migration/migration_harbor/versions/1_3_0.py

1. add table `project_meta`
2. remove `public` column from `project`
3. add `insecure` column to `replication_target` table
4. add migration file

db migration from 1.2.0 to 1.3.0

---

docs/configure_swagger.md

See https://github.com/vmware/harbor/issues/3463 for more information

ISSUE-3463: fix docker-compose command

---

make/docker-compose.clair.yml
make/photon/clair/Dockerfile
make/photon/clair/docker-entrypoint.sh

1>creat user clair
2>run clair with user clair

Run clair with limited user

---

contrib/harbor-cli/Dockerfile
contrib/harbor-cli/README.md
contrib/harbor-cli/harborclient/__init__.py
contrib/harbor-cli/harborclient/api_versions.py
contrib/harbor-cli/harborclient/base.py
contrib/harbor-cli/harborclient/client.py
contrib/harbor-cli/harborclient/exceptions.py
contrib/harbor-cli/harborclient/shell.py
contrib/harbor-cli/harborclient/utils.py
contrib/harbor-cli/harborclient/v2/__init__.py
contrib/harbor-cli/harborclient/v2/client.py
contrib/harbor-cli/harborclient/v2/configurations.py
contrib/harbor-cli/harborclient/v2/jobs.py
contrib/harbor-cli/harborclient/v2/logs.py
contrib/harbor-cli/harborclient/v2/projects.py
contrib/harbor-cli/harborclient/v2/repositories.py
contrib/harbor-cli/harborclient/v2/searcher.py
contrib/harbor-cli/harborclient/v2/shell.py
contrib/harbor-cli/harborclient/v2/statistics.py
contrib/harbor-cli/harborclient/v2/systeminfo.py
contrib/harbor-cli/harborclient/v2/targets.py
contrib/harbor-cli/harborclient/v2/users.py
contrib/harbor-cli/harborrc
contrib/harbor-cli/requirements.txt
contrib/harbor-cli/set_bash_completion.sh
contrib/harbor-cli/setup.cfg
contrib/harbor-cli/setup.py
contrib/harbor-cli/test-requirements.txt
contrib/harbor-cli/tools/pretty_tox.sh
contrib/harbor-cli/tox.ini

This patch provides a command-line tool for managing Harbor resources
like users, projects, images, etc.

Add CLI tool for Harbor

---

README.md

Update README to add Twitter account and email groups that user can join for better communication.

Update README to include Twitter and email groups of Harbor.

---

Makefile

Update clair image version in Makefile

Fix clair images version issue

---

src/common/notifier/init.go
src/common/notifier/notifier_test.go
src/replication/consts.go
src/replication/core/controller.go
src/replication/event/on_deletion_handler.go
src/replication/event/on_push_handler.go
src/replication/event/start_replication_handler.go
src/replication/event/topics.go
src/replication/models/policy.go
src/replication/models/trigger.go
src/replication/policy/manager.go
src/replication/source/sourcer.go
src/replication/trigger/cache.go
src/replication/trigger/cache_test.go
src/replication/trigger/immediate.go
src/replication/trigger/interface.go
src/replication/trigger/manager.go
src/replication/trigger/param_immediate.go
src/replication/trigger/param_schedule.go
src/replication/trigger/schedule.go
src/replication/trigger/trigger_param.go
src/replication/trigger/watch_list.go

Define the related interfaces for triggers and core controllers of replication service

Define the related interfaces for triggers and core controllers of replication service

---

tools/migration/migration_harbor/versions/1_3_0.py

fix issue when upgrade from 1.2.0rc1 to 1.3.0

---

make/docker-compose.notary.yml
make/photon/notary/server-start.sh
make/photon/notary/server.Dockerfile
make/photon/notary/signer-start.sh
make/photon/notary/signer.Dockerfile

1>Change the user from root to notary
2>Update the images.

Run notary related images with user notary

---

src/ui_ng/lib/src/config/config.ts
src/ui_ng/package.json
src/ui_ng/src/app/config/auth/config-auth.component.html
src/ui_ng/src/app/config/auth/config-auth.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json
tests/ldapprepare.sh
tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Configuration_Elements.robot
tests/resources/Harbor-Util.robot
tests/robot-cases/Group0-BAT/BAT.robot

Add ldap verfiy cert checkbox about #3513
Add test case about ldap verify cert checkbox

Add ldap verfiy cert checkbox about #3513

---

make/photon/notary/builder_public

See https://github.com/vmware/harbor/issues/3460 for more info

ISSUE-3460 - Fix link to Notary repo

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/project-policy-config/project-policy-config.component.html.ts
src/ui_ng/lib/src/project-policy-config/project-policy-config.component.spec.ts
src/ui_ng/lib/src/project-policy-config/project-policy-config.component.ts
src/ui_ng/lib/src/project-policy-config/project.ts
src/ui_ng/lib/src/service/project.service.ts
src/ui_ng/package.json

show config policy item based on installation of notary and clair

enhancement the presentation of project level policy 

---

make/photon/clair/Dockerfile
tools/migration/Dockerfile
tools/migration/run.sh

1)Fix a syntax error in clair Dockerfile
2)Fix permission issue in database migrator image.

Fix issue in Docker files

---

make/photon/clair/Dockerfile
make/photon/clair/docker-entrypoint.sh

Change config file owner to clair

Fix Clair config permission issue

---

src/ui_ng/lib/pkg/package.json
src/ui_ng/package.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

edit the chinese description of public policy

fix Chinese text of public policy

---

make/common/templates/adminserver/env
src/adminserver/systemcfg/systemcfg.go
src/adminserver/systemcfg/systemcfg_test.go
src/common/const.go
src/common/models/config.go
src/common/models/ldap.go
src/common/utils/ldap/ldap.go
src/common/utils/ldap/ldap_test.go
src/ui/api/config.go
src/ui/api/member.go
src/ui/config/config.go
src/ui_ng/lib/src/config/config.ts
src/ui_ng/src/app/config/auth/config-auth.component.html
src/ui_ng/src/app/config/auth/config-auth.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json
tests/ldapprepare.sh
tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Configuration_Elements.robot
tests/resources/Harbor-Util.robot
tests/robot-cases/Group0-BAT/BAT.robot

Fix includes:
1. Add LDAP remote certificate validation
2.Search and import ldap user when add project members
3.Trim space in ldap username, fix issue 3553

Ldap enhancement

---

docs/swagger.yaml
src/ui/api/harborapi_test.go
src/ui/api/target.go
src/ui/api/target_test.go
src/ui/router.go
src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.html.ts
src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
src/ui_ng/lib/src/service/endpoint.service.ts
src/ui_ng/lib/src/service/interface.ts

Merge ping target API by ID into ping target API

Refactor ping target API

---

tests/ldap_test.ldif
tests/resources/Docker-Util.robot
tests/resources/Harbor-Pages/Configuration.robot
tests/robot-cases/Group0-BAT/BAT.robot

Add LDAP e2e test, add filter to LDAP user, and log in with the user mike in group harbor_user

Add LDAP e2e test

---

tests/apitests/api-testing/client/docker_client.go
tests/apitests/api-testing/client/harbor_api_client.go
tests/apitests/api-testing/envs/concourse_ci.go
tests/apitests/api-testing/envs/environment.go
tests/apitests/api-testing/lib/image.go
tests/apitests/api-testing/lib/project.go
tests/apitests/api-testing/lib/report.go
tests/apitests/api-testing/lib/system.go
tests/apitests/api-testing/lib/user.go
tests/apitests/api-testing/models/endpoint.go
tests/apitests/api-testing/models/image.go
tests/apitests/api-testing/models/member.go
tests/apitests/api-testing/models/project.go
tests/apitests/api-testing/models/replication.go
tests/apitests/api-testing/models/system_info.go
tests/apitests/api-testing/models/user.go
tests/apitests/api-testing/tests/suites/suite.go
tests/apitests/api-testing/tests/suites/suite01/run_test.go
tests/apitests/api-testing/tests/suites/suite01/suite.go

Add test cases for API, tested:
=====================================
Overall: 8/12 passed , 4/12 failed
=====================================
GetSystemInfo: [PASSED]
CreateProject: [PASSED]
CreateUser: [PASSED]
AssignRole: [PASSED]
RevokeRole: [PASSED]
pullImage[2]: [PASSED]
DeleteProject: [PASSED]
DeleteUser: [PASSED]
pushImage: [FAILED] exec: "docker": executable file not found in $PATH
ScanTag: [FAILED] 500 Internal Server Error
pullImage[1]: [FAILED] exec: "docker": executable file not found in $PATH
DeleteRepo: [FAILED] 404 Not Found

[Skip CI]add api testing for harbor including image pull and push

---

docs/user_guide.md

Add link to user guide overview issue#3519

Add link to user guide overview issue#3519

---

Makefile
make/common/templates/registry/config_ha.yml
make/common/templates/ui/env
make/ha/docker-compose.tpl
make/ha/sample/active_active/keepalived_active_active.conf
make/ha/sample/active_standby/check_harbor.sh
make/ha/sample/active_standby/keepalived_active_standby.conf
make/harbor.cfg
make/install.sh
make/prepare

Add --ha options when install Harbor.

HA installation script

---

src/common/utils/ldap/ldap.go
src/common/utils/ldap/ldap_test.go
src/ui/api/ldap.go
src/ui/api/member.go
src/ui/auth/auth_test.go
src/ui/auth/authenticator.go
src/ui/auth/db/db.go
src/ui/auth/db/db_test.go
src/ui/auth/ldap/ldap.go
src/ui/auth/ldap/ldap_test.go
src/ui/auth/uaa/uaa.go

Refactor LDAP code in comm/utils/ldap/

Refactor LDAP code

---

tests/ldapprepare.sh

Retry when test ldap server load data fail

Retry when test ldap server load data fail

---

src/common/models/models_test.go
src/common/utils/ldap/ldap.go
src/common/utils/ldap/ldap_test.go
src/jobservice/api/job_test.go
src/jobservice/jobservice_test.go
src/jobservice/replication/replication_test.go
src/ui/api/ldap.go
src/ui/auth/db/db_test.go
src/ui/auth/ldap/ldap_test.go
src/ui/controllers/controllers_test.go
src/ui/service/service_test.go
src/ui/ui_test.go
src/ui/utils/utils_test.go
tests/common

Fix ldap ping issue #3653

---

src/common/dao/dao_test.go
src/common/dao/user.go
src/ui/api/user.go
src/ui/api/user_test.go
src/ui/auth/authenticator.go
src/ui/config/config.go
src/ui/controllers/base.go
src/ui/controllers/controllers_test.go
src/ui/router.go

Disable user management features when auth mode is UAA.

---

src/common/api/base.go
src/ui/router.go

Some URLs are not used on UI, so they are removed.  And the validation
code of API is removed as we use the security context approach.

Remove useless code from UI router and API

---

tests/nightly-test/buildweb_utils.py
tests/nightly-test/govc_utils.py
tests/nightly-test/launch.py
tests/nightly-test/shellscript/destroyvm.sh
tests/nightly-test/shellscript/getvmip.sh

Nightly test

---

src/ui/config/config_test.go

Add test case for validate Clair DB config

Add test case for Clair DB configuration

---

src/common/dao/dao_test.go
src/common/dao/scan_job.go
src/common/notifier/notifier.go
src/common/scheduler/policy/alternate_policy.go

Signed-off-by: Ri Xu <xuri.me@gmail.com>

Simple code and typo fixed.

---

src/common/utils/ldap/ldap.go
src/ui/auth/ldap/ldap.go

Call EscapeFilter for filter  to avoid security issue

Call EscapeFilter for filter  to avoid security issue

---

src/ui_ng/src/app/config/auth/config-auth.component.html
src/ui_ng/src/app/config/auth/config-auth.component.ts
src/ui_ng/src/app/config/config.component.css
src/ui_ng/src/app/config/config.component.html
src/ui_ng/src/app/config/config.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

It should show UAA auth configurations when select auth mode to UAA auth.

Add UI Component for UAA Auth

---

src/ui/api/ldap.go

Do not display internal error message to user to avoid security issue

Do not display internal error message to user

---

tests/ldap_test.ldif
tests/resources/Harbor-Pages/UserProfile.robot
tests/robot-cases/Group0-BAT/BAT.robot

Add ldap user to project member test

Add ldap user to project member test

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/harbor-library.module.ts
src/ui_ng/lib/src/repository/repository.component.css.ts
src/ui_ng/lib/src/repository/repository.component.html.ts
src/ui_ng/lib/src/shared/shared.module.ts
src/ui_ng/package.json
src/ui_ng/rollup-config.js

1. Fix the windows size of descrption info
2. Add markdown support

Enhancement of Metadata Descrition

---

src/common/dao/config_test.go
src/common/dao/user.go
src/common/dao/user_test.go
src/ui/auth/authenticator.go
src/ui/auth/db/db.go
src/ui/auth/ldap/ldap.go
src/ui/auth/ldap/ldap_test.go
src/ui/auth/uaa/uaa.go

Sync user email between harbor DB and LDAP #3663

Sync user email in ldap #3663

---

src/ui_ng/src/app/account/sign-in/sign-in.component.css
src/ui_ng/src/app/account/sign-in/sign-in.component.html
src/ui_ng/src/app/base/global-search/global-search.component.ts
src/ui_ng/src/app/base/navigator/navigator.component.html
src/ui_ng/src/app/shared/about-dialog/about-dialog.component.ts
src/ui_ng/src/app/skinable-config.service.ts
src/ui_ng/src/setting.json

Modify setting.json file description
Modify images path

Modify skinnable json file and modify images path about #3909 #3879

---

make/common/templates/registry/config.yml
make/common/templates/registry/config_ha.yml
make/harbor.cfg
make/prepare

Refer to https://docs.docker.com/registry/configuration/#storage
for all available configuration.

Add registry storage config in harbor.cfg

---

src/common/dao/user.go
src/common/models/config.go
src/common/utils/ldap/ldap.go
src/common/utils/ldap/ldap_test.go
src/ui/api/config.go
src/ui/api/ldap.go
src/ui/auth/auth_test.go
src/ui/auth/authenticator.go
src/ui/auth/ldap/ldap.go
src/ui/auth/ldap/ldap_test.go
src/ui/config/config.go
src/ui/config/config_test.go
src/ui_ng/src/app/config/auth/config-auth.component.html
tests/resources/Harbor-Pages/Administration-Users.robot
tests/resources/Harbor-Pages/Project-Members.robot
tests/robot-cases/Group0-BAT/BAT.robot

1) Refactor the ldap_scope related UI and API code to fix issue in #3763
2) Fix the email in LDAP is not sync to DB in OnBoardUser and add robot test case to verify it.

Ambiguous UI and internal values ldap_scope

---

docs/migration_guide.md

update migration doc to avoid issues when rollback from 1.3 to 1.2

Update doc file to avoid issues when rollback from 1.3 to 1.2

---

docs/installation_guide.md
docs/swagger.yaml
make/harbor.cfg

Change ldap scope after refactor

Change ldap scope after refactor

---

tests/resources/Docker-Util.robot
tests/resources/Harbor-Pages/HomePage.robot
tests/resources/Harbor-Pages/Project-Members.robot
tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/ToolKit.robot
tests/resources/Util.robot
tests/robot-cases/Group0-BAT/BAT.robot

Add batch delete testcase

---

src/common/const.go
src/ui/api/ldap.go

Set timeout for LDAP ping so that there no nginx gate-way timeout error

Setting timeout for ldap ping

---

src/ui_ng/lib/src/confirmation-dialog/confirmation-dialog.component.html.ts
src/ui_ng/lib/src/confirmation-dialog/confirmation-dialog.component.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.html.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
src/ui_ng/lib/src/replication/replication.component.html.ts
src/ui_ng/lib/src/replication/replication.component.ts
src/ui_ng/lib/src/repository-listview/repository-listview.component.ts
src/ui_ng/lib/src/service/replication.service.ts
src/ui_ng/lib/src/shared/shared.const.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/global-message/message.component.html
src/ui_ng/src/app/project/member/member.component.ts
src/ui_ng/src/app/replication/replication-page.component.html
src/ui_ng/src/app/replication/replication-page.component.ts
src/ui_ng/src/app/replication/replication-rule/replication-rule.component.ts
src/ui_ng/src/app/replication/replication-rule/replication-rule.css
src/ui_ng/src/app/replication/replication-rule/replication-rule.html
src/ui_ng/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
src/ui_ng/src/app/shared/confirmation-dialog/confirmation-dialog.component.ts
src/ui_ng/src/app/shared/shared.const.ts
src/ui_ng/src/app/user/user.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json
tests/robot-cases/Group0-BAT/BAT.robot

Modify replication list to batch delection mode
Add admin privilege to project replication module

Modify replication list to batch delection mode

---

make/ha/sample/active_active/check.sh
make/ha/sample/active_active/keepalived_active_active.conf

Add keepalived real server check script

Keepalived real server check script

---

tests/run-clarity-ut.sh

Using fixed version number to reduce the npm log in travis

Update package.js file

---

src/ui_ng/lib/src/confirmation-dialog/confirmation-dialog.component.ts
src/ui_ng/lib/src/repository-listview/repository-listview.component.html.ts
src/ui_ng/package.json
src/ui_ng/src/app/config/config.component.html
src/ui_ng/src/app/project/project-detail/project-detail.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Fix bugs about i18n & text

---

src/common/utils/uaa/client.go
src/common/utils/uaa/fake_client.go
src/ui/auth/authenticator.go
src/ui/auth/uaa/uaa.go
src/ui/auth/uaa/uaa_test.go

Will call the userinfo API of UAA to get user info and generage user
model based on the response.  Also this commit include a change that
whenever the UAA Client is to be used it will update the configuraiton,
this is needed as we enable user to update the configuration of UAA via
UI.

Read Email from UAA while onboarding user.

---

src/adminserver/systemcfg/systemcfg.go
src/adminserver/systemcfg/systemcfg_test.go

Add update ldapScope for migrate

Add update ldapScope for migrate

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/package.json
src/ui_ng/src/app/account/account-settings/account-settings-modal.component.html
src/ui_ng/src/app/account/account-settings/account-settings-modal.component.ts
src/ui_ng/src/app/shared/session.service.ts
src/ui_ng/src/app/user/user.service.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Add UI Element for rename admin

add admin rename ui

---

src/ui_ng/lib/src/confirmation-dialog/confirmation-dialog.component.html.ts
src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
src/ui_ng/lib/src/endpoint/endpoint.component.html.ts
src/ui_ng/lib/src/index.ts
src/ui_ng/lib/src/inline-alert/inline-alert.component.css.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.html.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
src/ui_ng/lib/src/replication/replication.component.html.ts
src/ui_ng/lib/src/replication/replication.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/replication/replication-rule/replication-rule.component.ts
src/ui_ng/src/app/replication/replication-rule/replication-rule.css
src/ui_ng/src/app/replication/replication-rule/replication-rule.html
src/ui_ng/src/app/replication/total-replication/total-replication-page.component.html
src/ui_ng/src/app/replication/total-replication/total-replication-page.component.ts
src/ui_ng/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Add add endpoint button in replication rule
Modify small issues  in replication rule

Add add endpoint button in replication rule

---

src/adminserver/systemcfg/systemcfg.go
src/adminserver/systemcfg/systemcfg_test.go

Fix bug 4073

---

make/ha/sample/active_active/keepalived_active_active.conf

Update the keepalived config file

Update keepalived config file

---

src/ui_ng/lib/src/endpoint/endpoint.component.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
src/ui_ng/package.json

Modify  endpoint delection unfreash issue
Add replication rule list first column checked default

Modify issue about endpoint delection unfreash 

---

src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/replication/replication-rule/replication-rule.html

Modify create endpoint ping icon undisappear auto
Modify create replication rule page layout

Modify create endpoint ping icon undisappear auto about #4102

---

docs/installation_guide.md

Add harbor resource requirement for Harbor installation guide

Harbor resource requirement doc

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.css.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.html.ts
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/account/account-settings/account-settings-modal.component.html

Fix description too long

---

src/ui_ng/src/app/project/member/add-member/add-member.component.ts
src/ui_ng/src/app/project/member/member.component.html
src/ui_ng/src/app/project/member/member.component.ts
src/ui_ng/src/app/replication/replication-rule/replication-rule.component.ts
src/ui_ng/src/app/replication/replication-rule/replication-rule.html
src/ui_ng/src/app/replication/replication-rule/replication-rule.service.ts

Delete username and possword in replication rule
Modify add member dialog default checked issue

Delete username and possword in replication rule

---

src/ui_ng/src/app/harbor-routing.module.ts
src/ui_ng/src/app/project/member/member.component.ts
src/ui_ng/src/app/repository/tag-repository/tag-repository.component.ts
src/ui_ng/src/app/shared/route/leaving-repository-deactivate.service.ts
src/ui_ng/src/app/shared/shared.module.ts

Fix that open confirmation dialog when leaving repo

Fix open confirmation dialog when leving repo

---

src/ui_ng/src/app/shared/new-user-form/new-user-form.component.html
src/ui_ng/src/app/shared/new-user-form/new-user-form.component.ts

Force refresh after enters new name and email when creating user.

Add force refresh to new user form

---

docs/high_availability_installation_guide.md

Update HA document.

---

src/ui_ng/src/app/project/member/add-member/add-member.component.ts

Fix wait time too long when clicking member add button.

Fix bug open add member modal time too long

---

tests/robot-cases/Group11-Nightly/Nightly.robot

Add a keyword special for bat delete tag test,will tag  different
images a same name with different tag, to make sure under the
same repo

Use two different tag in bat delete to aviod 500 error

---

docs/high_availability_installation_guide.md
make/harbor.cfg

Put harbor_db, clair_db configuration together.

Refactor DB configuration in harbor.cfg

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.css.ts
src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.html.ts
src/ui_ng/package.json

Test case break when clicking checkbox to test connection

Fix UI that break test case

---

make/photon/db/registry.sql
make/photon/db/registry_sqlite.sql
src/common/const.go
src/common/dao/base.go
src/common/dao/dao_test.go
src/common/dao/project.go
src/common/dao/project_test.go
src/common/dao/projectmember.go
src/common/dao/replication_job.go
src/common/dao/role.go
src/common/models/member.go
src/common/security/local/context.go
src/common/security/local/context_test.go
src/ui/api/api_test.go
src/ui/api/harborapi_test.go
src/ui/api/member.go
src/ui/api/replication_policy_test.go
src/ui/api/utils.go
src/ui/router.go

Refactor project member so that it can contain group member.
Changes include:
1)  Update table project_member, add id column to project_member, change user_id to entity_id, and add entity_type ('u' for user member, 'g' for group member), primary key changed.
2)  Change project member CRUD API,  add parameter entityType so that it can contain group members.

Refactor project member

---

tests/resources/Harbor-Util.robot

bump clarity builder version

---

src/adminserver/systemcfg/systemcfg.go

Reload Harbor DB,
Reload Clair DB.

Relead Harbor db and Clair db when restart Harbor

---

.gitignore
src/adminserver/api/monitor.go
src/adminserver/api/monitor_test.go
src/adminserver/handlers/handler.go
src/adminserver/handlers/handlers_test.go
src/adminserver/handlers/router.go
src/ui/api/harborapi_test.go
src/ui/api/systeminfo.go
src/ui/api/systeminfo_test.go
src/ui/router.go

1>AdminServer
2>Jobservice
3>UI

Add monitor API for Harbor components

---

tests/resources/Docker-Util.robot
tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/Replication_Elements.robot
tests/resources/Harbor-Pages/Vulnerability.robot
tests/robot-cases/Group11-Nightly/Nightly.robot
tests/robot-cases/Group11-Nightly/Replication.robot

add create rule with 0 endpoint
add test ping and cert verify
add add new endpoint
add create rule with existing endpoint

Add replication autotest

---

make/photon/db/registry.sql
make/photon/db/registry_sqlite.sql
src/common/dao/group/usergroup.go
src/common/dao/group/usergroup_test.go
src/common/dao/project/projectmember.go
src/common/dao/project/projectmember_test.go
src/common/dao/testutils.go
src/common/models/member.go
src/common/models/usergroup.go

Add DAO for user group and project member

Add DAO for user group and project member

---

src/jobservice_v2/config/config_test.go
src/jobservice_v2/config_test.yml
src/jobservice_v2/opm/redis_job_stats_mgr.go
src/jobservice_v2/pool/redis_pool.go

Fix the issue of causing config test failed

Fix the issue of causing config test failed

---

src/jobservice_v2/period/enqueuer_test.go
src/jobservice_v2/period/redis_scheduler_test.go
src/jobservice_v2/period/sweeper_test.go
src/jobservice_v2/tests/utils.go

Add UT cases for package period

Add UT cases for package period

---

make/common/templates/clair/clair_env
make/docker-compose.clair.tpl
make/harbor.cfg
make/prepare

Clair needs Internet access to download vulnerabilities data.
Fix issue https://github.com/vmware/harbor/issues/4272

Add http_proxy configuration for Clair service

---

src/jobservice_v2/api/handler_test.go
src/jobservice_v2/config/config_test.go
src/jobservice_v2/core/controller_test.go
src/jobservice_v2/logger/sweeper_test.go
src/jobservice_v2/opm/hook_client_test.go
src/jobservice_v2/opm/redis_job_stats_mgr_test.go
src/jobservice_v2/period/job_policy_test.go
src/jobservice_v2/period/redis_scheduler_test.go
src/jobservice_v2/period/sweeper_test.go
src/jobservice_v2/pool/message_server_test.go
src/jobservice_v2/pool/redis_job_wrapper.go
src/jobservice_v2/pool/redis_pool.go
src/jobservice_v2/pool/redis_pool_test.go
src/jobservice_v2/tests/utils.go

Add UT cases for package pool

---

make/photon/redis/Dockerfile
make/photon/redis/docker-entrypoint.sh
make/photon/redis/redis.conf

Add Redis docker file

---

make/photon/db/registry.sql
tools/migration/db/db_meta.py
tools/migration/db/migration_harbor/versions/1_5_0.py

Upgrade migrator to 1.5.0

---

src/ui_ng/lib/src/create-edit-label/create-edit-label.component.css.ts
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.css.ts
src/ui_ng/lib/src/label-piece/label-piece.template.ts
src/ui_ng/lib/src/label/label.component.ts
src/ui_ng/lib/src/repository-listview/repository-listview.component.ts
src/ui_ng/lib/src/tag/tag-detail.component.html.ts
src/ui_ng/lib/src/tag/tag-detail.component.spec.ts
src/ui_ng/lib/src/tag/tag-detail.component.ts
src/ui_ng/lib/src/tag/tag.component.css.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/app-config.ts
src/ui_ng/src/app/base/harbor-shell/harbor-shell.component.css
src/ui_ng/src/app/base/navigator/navigator.component.ts
src/ui_ng/src/app/config/config.component.html
src/ui_ng/src/app/config/config.component.ts
src/ui_ng/src/app/config/config.module.ts
src/ui_ng/src/app/config/repo/repo-read-only.component.ts
src/ui_ng/src/app/config/repo/repo-read-only.html
src/ui_ng/src/app/global-message/message.component.css
src/ui_ng/src/app/repository/tag-detail/tag-detail-page.component.html
src/ui_ng/src/app/repository/tag-detail/tag-detail-page.component.ts
src/ui_ng/src/app/shared/message-handler/message-handler.service.ts
src/ui_ng/src/app/shared/route/auth-user-activate.service.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json
tests/resources/Harbor-Pages/Configuration.robot

Add repo read only module
Modify label issue
Add config> label test case

Add repo read only

---

src/jobservice/job/impl/demo_job.go
src/jobservice/opm/op_commands.go
src/jobservice/opm/redis_job_stats_mgr.go
src/jobservice/opm/redis_job_stats_mgr_test.go
src/jobservice/period/redis_scheduler.go
src/jobservice/pool/message_server.go
src/jobservice/pool/message_server_test.go
src/jobservice/pool/redis_pool.go
src/jobservice/utils/utils.go
src/replication/target/target.go

improve op command by using cache
return 404 if no job found to stop

Fix issue of stopping periodic job

---

docs/user_guide.md

See https://github.com/vmware/harbor/issues/3462 for more information

[Skip CI] Add link to official docker documentation

---

src/ui_ng/lib/README.md
src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
src/ui_ng/lib/src/repository/repository.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/repository/tag-repository/tag-repository.component.html

Reduce properties `projectName` , `withNotary`, `withClair`, `withAdmiral` in hbr-repository

Reduce properties in hbr repository

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
src/ui_ng/package.json

Fix bug vulnerability notification not showing

Fix bug vulnerability notification not showing

---

make/photon/adminserver/Dockerfile
make/photon/nginx/Dockerfile
make/photon/postgresql/Dockerfile
make/photon/postgresql/docker-healthcheck.sh
make/photon/ui/Dockerfile

ui
nginx
adminserver
postgresql

Use new health check api for docker files

---

src/ui_ng/lib/README.md

Now hbr-repository-listview will output an event when repo clicked.

Abstract repo click as a output event

---

src/jobservice/config.yml
src/jobservice/job/impl/demo_job.go
src/jobservice/opm/redis_job_stats_mgr.go
src/jobservice/pool/message_server.go
src/jobservice/pool/redis_job_wrapper.go

Fix issue: failed to update the status of a job if runtime error occurred

Fix issue: failed to update the status of job if runtme error occurred

---

src/jobservice/api/authenticator.go
src/jobservice/api/handler_test.go
src/jobservice/api/router.go
src/jobservice/config/config.go
src/jobservice/errs/errors.go
src/jobservice/runtime/bootstrap.go

Get secret from 'Authorization' header of the request

Apply auth checking to all the incoming requests

---

docs/high_availability_installation_guide.md

Fix issue https://github.com/vmware/harbor/issues/4588

Fix doc bug in high_availability_installation_guide.md

---

make/common/templates/jobservice/config.yml

increase it from 10 to 50 to improve the performance

Update the worker concurrency of job service

---

make/common/templates/clair/config.yaml
make/prepare

Add dbname paramter in dburl

---

tests/resources/Docker-Util.robot
tests/robot-cases/Group11-Nightly/Nightly.robot
tests/robot-cases/Group11-Nightly/Replication.robot

Fix up keyword: push image with tag
Fix up case: Project Admin Add Labels To Repo
Fix up case: Proj Replication Jobs Log View

Fix up keyword and test case

---

docs/high_availability_installation_guide.md
make/ha/docker-compose.clair.tpl
make/ha/docker-compose.tpl

Update the docker compose template and user guide

Update HA template and User guide

---

tests/apitests/api-testing/client/harbor_api_client.go
tests/apitests/api-testing/lib/project.go
tests/apitests/api-testing/lib/report.go
tests/apitests/api-testing/models/member.go
tests/apitests/api-testing/models/project.go
tests/apitests/api-testing/tests/suites/suite01/suite.go
tests/apitests/api-testing/tests/suites/suite02/suite.go

update test case for assigning the role
update test case for revoking role

Fix the failure api test cases because API implementation changed

---

docs/swagger.yaml
src/common/dao/project/projectmember.go
src/common/dao/project/projectmember_test.go
src/ui/api/ldap.go
src/ui/api/projectmember.go
src/ui/api/projectmember_test.go

Previous implementation contains the search user by name feature. This implementation can search user and user group by name.

Add project member search by name

---

.drone.yml

Update to DNS server to make the network stable.

Fix drone fail on photon tdnf call

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/config/registry-config.component.html.ts
src/ui_ng/lib/src/config/registry-config.component.ts
src/ui_ng/lib/src/config/system/system-settings.component.html.ts
src/ui_ng/lib/src/config/system/system-settings.component.ts
src/ui_ng/package.json
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Hidden read-only mode on vic
Reword the tooltip

Fix readonly mode show in vic and rewording the tooltip

---

make/dev/nodeclarity/entrypoint.sh

add `cp ./src/setting.json ../ui/static/`

Fix the issue of missing copying the setting.json to container image

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/config/registry-config.component.html.ts
src/ui_ng/lib/src/config/registry-config.component.ts
src/ui_ng/lib/src/config/system/system-settings.component.html.ts
src/ui_ng/lib/src/config/system/system-settings.component.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.css.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/config/config.component.ts
src/ui_ng/src/app/project/member/member.component.ts
src/ui_ng/src/app/project/member/member.service.ts
src/ui_ng/src/app/repository/repository-page.component.html
src/ui_ng/src/app/repository/repository-page.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

1. Fix bug 4665 project admin cannot change the role of some user.
2. Add query string when getting members
3. ix UI/UX issues and manually refresh component when fresh
4. Fix configure save err #4698
5. Fix readonly mode show in vic and rewording the tooltip
6. Fix default view problem and styles issues

Cheery-pick bugs fix to Release 1.5.0

---

tests/resources/Harbor-Pages/Project.robot
tests/robot-cases/Group11-Nightly/Nightly.robot

Fix up card view keyword and failed test case

Fix up card view keyword

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.css.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/repository/repository-page.component.html
src/ui_ng/src/app/repository/repository-page.component.ts

Set default view of repo to cardview
Fix card title style issue that break test

Fix default view problem and styles issues

---

src/ui_ng/lib/package.json
src/ui_ng/package.json

downgrade the zone.js version to 0.8.19 and fix it

Fix the issue of causing the UI UT cases failed

---

.travis.yml
tests/resources/Harbor-Util.robot

Update UI code builder version to latest(1.4.0) to fix ui bugs.

Update ui clarity builder version to 1.4.0

---

src/ui_ng/src/app/account/sign-in/sign-in.component.html

Modify login background image position

Modify login bg image position about skinnable

---

src/ui_ng/lib/src/repository/repository.component.css.ts
src/ui_ng/lib/src/repository/repository.component.html.ts
src/ui_ng/lib/src/repository/repository.component.ts
src/ui_ng/lib/src/tag/tag-detail.component.css.ts
src/ui_ng/lib/src/tag/tag-detail.component.html.ts
src/ui_ng/lib/src/tag/tag-detail.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/account/sign-in/sign-in.component.html
src/ui_ng/src/app/repository/tag-detail/tag-detail-page.component.html
src/ui_ng/src/app/repository/tag-detail/tag-detail-page.component.ts
src/ui_ng/src/app/repository/tag-repository/tag-repository.component.css
src/ui_ng/src/app/repository/tag-repository/tag-repository.component.html
src/ui_ng/src/app/repository/tag-repository/tag-repository.component.ts

Modify bread crumb for vic only show arrow and ova show bread crumb
Modify loginBg position about skinnable

Modify bread crumb and modify loginBg position about skinnable

---

src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
src/ui_ng/lib/src/replication/replication.component.html.ts
src/ui_ng/lib/src/replication/replication.component.ts
src/ui_ng/package.json

Modify replication rule list not seleted when load first

Modify replication rule list not seleted when load first

---

src/ui_ng/src/app/replication/replication-page.component.html
src/ui_ng/src/app/replication/replication-page.component.ts

Modify click to registry link under project

Modify click to registry link under project

---

src/ui_ng/src/app/config/auth/config-auth.component.html

Modify tooltips size base on the tooltips length  in authentication

Modify tooltips size about authentication 

---

.travis.yml

Download golint source codes from mirror to work around the failure in travis ci

Workaround for golint issue in travis

---

src/ui_ng/lib/src/create-edit-label/create-edit-label.component.css.ts
src/ui_ng/lib/src/create-edit-label/create-edit-label.component.html.ts
src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/package.json

Modify color panel and add labels to imgs frequently click problem

Modify color panel and add labels to imgs frequently click problem

---

src/ui_ng/lib/src/create-edit-label/create-edit-label.component.css.ts
src/ui_ng/lib/src/create-edit-label/create-edit-label.component.html.ts
src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/config/config.component.ts

Modify color panel and add labels to imgs click problem
fix issue about read only mode warning undisappear about #4741

Cherry-pick: modify color panel and add labels to imgs click problem

---

contrib/helm/harbor/templates/registry/registry-cm.yaml
contrib/helm/harbor/templates/registry/registry-ss.yaml
contrib/helm/harbor/values.yaml

- when persistence is disabled
- when using s3 storage

[Chart] Fix registry storage config issue

---

src/jobservice/core/controller_test.go
src/jobservice/pool/interface.go
src/jobservice/pool/message_server.go
src/jobservice/pool/redis_pool.go
src/jobservice/runtime/bootstrap.go

github issue: #4712
ping redis server before pool starting
Let worker pool to restart the message server if message server exits with error (controlled by max retries)

Fix the issue of intermittent restarting of job service

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
src/ui_ng/package.json

Add additional info and Deploy event will take the url before repon ame

Add url before repo name

---

docs/migrate_ova_guide.md

Run pvscan command before power off the machine.

Change the order of power off machine and pvscan command in step 2

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.html.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
src/ui_ng/lib/src/utils.ts
src/ui_ng/package.json

1. everytime click deploy or add additional info will add a prefix before reponame
2. add constrait on button on cardview

Fix bugs infinity copy of reponame and auth

---

src/common/dao/repository.go

Remove the table join when querying repositories with project name

Cherry pick: Fix bug #4791

---

src/common/dao/repository.go

Remove the table join when querying repositories with project name

Fix bug #4791

---

src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
src/ui_ng/lib/src/tag/tag-detail.component.css.ts
src/ui_ng/lib/src/tag/tag-detail.component.html.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.spec.ts
src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.css.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts
src/ui_ng/package.json

Add sort function when filter labels in tag page
Modify tag detail page layout and add scan button
Add page freash code to verify name exist when create new label

Add sort fun when filter labels in tag page  #4617

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/harbor-library.module.ts
src/ui_ng/lib/src/service.config.ts
src/ui_ng/lib/src/service/project.service.ts
src/ui_ng/lib/src/service/tag.service.ts
src/ui_ng/package.json

In the repositories and projects service some url is hardcoded.

Fix bugs that some place hardcode url addr

---

tests/resources/Harbor-Pages/Configuration.robot

Fixup create new labels keyword to fix failed testcase

Fix up keyword add label

---

make/photon/db/registry.sql
make/photon/db/registry_sqlite.sql
src/common/dao/label_test.go
tools/migration/db/db_meta.py

Add unique constraint to column name, scope and project_id  of table harbor_label to make creating same name labels under different projects valid

Modify unique constraint of table harbor_label

---

src/ui_ng/lib/src/create-edit-label/create-edit-label.component.css.ts
src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
src/ui_ng/lib/src/tag/tag-detail.component.css.ts
src/ui_ng/lib/src/tag/tag-detail.component.html.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.spec.ts
src/ui_ng/lib/src/vulnerability-scanning/result-grid.component.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.css.ts
src/ui_ng/lib/src/vulnerability-scanning/scanning.html.ts
src/ui_ng/package.json

Add sort fun when filter label in tag page #4617
Modify images filter with label issue

Cherry pick add sort fun when filter label in tag page 

---

src/ui_ng/lib/package.json
src/ui_ng/lib/pkg/package.json
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.html.ts
src/ui_ng/lib/src/harbor-library.module.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
src/ui_ng/lib/src/service.config.ts
src/ui_ng/lib/src/service/project.service.ts
src/ui_ng/lib/src/service/tag.service.ts
src/ui_ng/lib/src/utils.ts
src/ui_ng/package.json

1. Fix bugs of infinity copy of reponame.
2. Add authentication in cardview button.
3. Fix hardcode url issues.

Cherry pick hardcode url and bug fix

---

tools/migration/db/migration_harbor/versions/1_4_0.py
tools/migration/migrator.py

Fix the bug: upgrade failed in VIC if replication policies exist

Fix bug #4840

---

src/ui_ng/lib/src/shared/shared.const.ts
src/ui_ng/lib/src/utils.ts

Modify issue about cannot switch language to franch
Modify exact filter label issue in tag filter module.

Modify issue about cannot switch language to franch

---

tests/resources/Harbor-Pages/Replication_Elements.robot
tests/robot-cases/Group11-Nightly/Nightly.robot

Fix up project level policy public
Change text to fix up pro repilcation rules add

Fix nightly failures bases on latest UI change

---

src/ui_ng/lib/src/filter/filter.component.ts
src/ui_ng/lib/src/filter/filter.template.ts
src/ui_ng/lib/src/tag/tag.component.css.ts
src/ui_ng/lib/src/tag/tag.component.html.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/package.json
tests/resources/Harbor-Pages/Project.robot

give up <clr-dropdown-menu>,use click event to open the label list

rewrite layout about filter by label and tesecase #4809

---

src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.html.ts
src/ui_ng/lib/src/log/recent-log.component.spec.ts
src/ui_ng/lib/src/log/recent-log.component.ts
src/ui_ng/lib/src/log/recent-log.template.ts
src/ui_ng/package.json

Add username,tag, operation filter options  for log。#4360
Add spin div height for unjump when testing #4359

Add multiple filter options for log #4360

---

src/jobservice/core/controller_test.go
src/jobservice/pool/interface.go
src/jobservice/pool/message_server.go
src/jobservice/pool/redis_pool.go
src/jobservice/runtime/bootstrap.go

github issue: #4712
ping redis server before pool starting
Let worker pool to restart the message server if message server exits with error (controlled by max retries)

Cherry-pick: Fix the issue of intermittent restarting of job service

---

src/jobservice/job/impl/context.go
src/jobservice/main.go
src/jobservice/runtime/bootstrap.go

Return none zero code when job service exit with an error
Add retry when getting configs from admin server failed

Cherry-pick: Improve the error handling capabilities of job service

---

tests/testcases/Group9-Content-trust/9-30-Project-level-content-trust.md

Add project level content trust testcase

Add project level content trust case

---

src/replication/consts.go
src/replication/core/controller.go
src/replication/core/controller_test.go
src/replication/models/filter.go
src/replication/policy/manager.go
src/replication/source/label_filter.go
src/replication/source/label_filter_test.go
src/replication/source/repository_filter.go
src/replication/source/tag_filter.go

Label filters are used to filter the resources according to the labels, adding the filters to the chain to enable the function.

Add label filter to filter chain

---

tests/resources/Harbor-Pages/Replication.robot

Add sleep to avoid test fail in delete replication rule case

Add sleep to avoid fail

---

src/ui/auth/ldap/ldap.go

Fix issue that returns 500 when login with a nonexisting user.

Fix error 500 with error username

---

src/ui/api/internal.go
src/ui/api/replication_job.go
src/ui/api/replication_policy.go
src/ui/api/repository.go
src/ui/api/scan_job.go
src/ui/api/target.go
src/ui/api/user.go

Record the errors which are only returned to frontend in the server side for easy debugging.

Log error message in server side

---

src/ui/api/internal.go
src/ui/api/replication_job.go
src/ui/api/replication_policy.go
src/ui/api/repository.go
src/ui/api/scan_job.go
src/ui/api/target.go
src/ui/api/user.go

Record the errors which are only returned to frontend in the server side for easy debugging.

Cherry-pick: Log error message in server side

---

src/ui_ng/src/app/shared/list-repository-ro/list-repository-ro.component.ts

Modify leftnav and tab have no hightLight about #4996

Modify leftnav and tab have no hightLight about #4996

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/ToolKit.robot
tests/robot-cases/Group11-Nightly/Nightly.robot

update muliti delete testcase for task progress

Update testcase for task progress

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Project-Members.robot
tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/ToolKit.robot
tests/robot-cases/Group11-Nightly/Replication.robot

Fix robot keywords align with UI changes 
fix replication case for new delete progress

Fix robot keywords align with UI changes

---

src/common/dao/dao_test.go
src/common/dao/user.go
src/ui/api/user.go
src/ui/api/user_test.go

Modify the changing password API to support that admin user can change the password of normal users without old password

Update change password API

---

tests/testcases/Group12-group-management/12-01-LDAP-usergroup-add.md
tests/testcases/Group12-group-management/12-02-LDAP-usergroup-update.md
tests/testcases/Group12-group-management/12-03-LDAP-usergroup-delete.md
tests/testcases/Group3-RBAC/3-07-LDAP-usergroup-manage-project-groupmembers.md
tests/testcases/Group4-logging/4-06-LDAP-usergroup-view-logs.md

Including
1. LDAP group configure settings
2. Assign role to LDAP user group.
3. Manage user group

Add testcase for assign role to LDAP group.

---

src/ui_ng/src/app/user/change-password/change-password.component.html
src/ui_ng/src/app/user/change-password/change-password.component.scss
src/ui_ng/src/app/user/change-password/change-password.component.ts
src/ui_ng/src/app/user/user.component.html
src/ui_ng/src/app/user/user.component.ts
src/ui_ng/src/app/user/user.module.ts
src/ui_ng/src/app/user/user.service.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Add function about admin reset user's password

Add function about admin reset user's password

---

contrib/helm/harbor/README.md
contrib/helm/harbor/templates/adminserver/adminserver-ss.yaml
contrib/helm/harbor/templates/clair/clair-dpl.yaml
contrib/helm/harbor/templates/jobservice/jobservice-dpl.yaml
contrib/helm/harbor/templates/mysql/mysql-ss.yaml
contrib/helm/harbor/templates/notary/notary-server.yaml
contrib/helm/harbor/templates/registry/registry-ss.yaml
contrib/helm/harbor/templates/ui/ui-dpl.yaml
contrib/helm/harbor/values.yaml

I added nodeSelector, tolerations, affinity configuration to helm chart to assign pods to nodes.

Add nodeSelector, tolerations, affinity configuration to helm chart

---

src/ui_ng/lib/src/tag/tag-detail.component.html
src/ui_ng/lib/src/tag/tag-detail.component.scss
src/ui_ng/lib/src/tag/tag.component.html
src/ui_ng/package.json

Modify if no clarity ,can't click into tag detail page, 
Modify tag detail info layout when window stretch

Modify tag detail alert when without clarity about #4999

---

tests/resources/Harbor-Util.robot
tests/robot-cases/Group11-Nightly/Nightly.robot

Add get harbor version case

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Replication.robot

Fix label test case fail for new UI change
Fix replicate manual keyword to avoid case fail

Fix label test case and replicate case

---

src/ui_ng/src/app/user/change-password/change-password.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Modify admin can't reset pwd to exist pwd

Modify admin can't reset pwd to exist pwd

---

tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/ToolKit.robot
tests/resources/Harbor-Pages/Vulnerability.robot
tests/robot-cases/Group11-Nightly/Nightly.robot

Update test case order to avoid scan on push fail
Add sleep time to avoid view scan results fail
Change keyword to wait unitl avoid delete operation fail
Change delete rule and repicate manual confirm to mouse down and up

Update test case to increase passrate

---

CONTRIBUTING.md
README.md
docs/README.md
partners.md

This PR is for issue #5079, and will add correct links for mailing lists, Slack and support email.
Signed-off-by: <jrosland@vmware.com>

Adding correct links in docs, and minor edits for spelling

---

docs/high_availability_installation_guide.md

Change harbor sql to point to 1.5.0 branch.
change keepalived configuration file and check script to 1.5.0 branch

Update HA docs to point to 1.5 branch

---

src/ui_ng/src/app/user/user.component.html

if auth_node is not db_auth, should hidden reset password button in user component .

Hidden pwd button if auth_mode is not db_auth

---

src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.html
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.scss
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.ts
src/ui_ng/package.json
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Add name validation when creat new replication rule

Add name validation when creat new replication rule #5050

---

main.bundle.js

1. Add community to doc site
2. Add demos to doc site
3. change wording contributing to contribution

Change document site

---

main.bundle.js

Small changes to the doc site based on review comments.

Update doc per comments

---

docs/swagger.yaml
src/ui/api/harborapi_test.go
src/ui/api/label.go
src/ui/api/label_test.go
src/ui/router.go

The API returns the resources that the label is referenced by. The resources contain only replication policies for now.

Provide an API to return the resources that a label is referenced by

---

src/ui_ng/src/i18n/lang/en-us-lang.json

Fixes #5152 by clarifying content trust wording.
/cc @pauldul

clarify wording: content trust policy in project setting

---

docs/swagger.yaml
src/common/utils/ldap/ldap.go
src/common/utils/ldap/ldap_test.go
src/ui/api/usergroup.go

Given an invalid DN, return 400 error
If the group DN is not found, return 404 error

Handle Invalid syntax and not found error

---

docs/registry_landscape.md

Creating a high-level overview of different projects and tols available for platform engineers / architects to leverage when attempting to deploy a container registry.
If you find any errors please don't hesitate to submit a PR.

create registry landscape table

---

contrib/helm/harbor/templates/ingress/ingress.yaml

Rewrite /v2/* to UI instead of registry to apply the filters to the requests

Update ingress rule for Harbor chart

---

docs/registry_landscape.md

Simplified and tweaked registry landscape table.
/cc @pauldul @clintkitson

Updated registry_landscape.md

---

tests/robot-cases/Group13-Upgrade/testdata.json
tests/robot-cases/Group13-Upgrade/testupgrade.py

Add upgrade test data generate script and example data

Add upgrade test scripts

---

docs/upgradetest.md

Add tips and information before and after upgrade for Harbor
upgrade test

Add upgrade test tips

---

tests/resources/Harbor-Pages/Verify.robot
tests/resources/Util.robot
tests/robot-cases/Group13-Upgrade/Verifydata.robot

Add data verify e2e case after upgrade

Add verify e2e case after upgrade

---

README.md
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.html
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.scss
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.spec.ts
src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.ts
src/ui_ng/lib/src/create-edit-rule/filter-label.component.html
src/ui_ng/lib/src/create-edit-rule/filter-label.component.scss
src/ui_ng/lib/src/create-edit-rule/filter-label.component.ts
src/ui_ng/lib/src/create-edit-rule/index.ts
src/ui_ng/lib/src/label-piece/label-piece.component.scss
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.html
src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
src/ui_ng/lib/src/replication/replication.component.html
src/ui_ng/lib/src/replication/replication.component.spec.ts
src/ui_ng/lib/src/replication/replication.component.ts
src/ui_ng/lib/src/service/label.service.ts
src/ui_ng/lib/src/tag/tag.component.ts
src/ui_ng/package.json
src/ui_ng/src/app/replication/total-replication/total-replication-page.component.html
src/ui_ng/src/app/replication/total-replication/total-replication-page.component.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Let user select the label from both system and project labels and use as a filter for the replication

Label filter UI for replication

---

src/common/models/project.go
src/ui/api/search.go
src/ui/api/search_test.go

Refactor the logic of search API to fix bug mentioned in issue #5156 and #3838

Fix bug in search API

---

main.bundle.js

Update our GitHub page(s) with the appropriate project description / wording.
/cc @pauldul @clintkitson

update project tagline

---

docs/swagger.yaml

Fix #5168 by correcting the types of properties used in ProjectMetadata

Update the swagger file

---

docs/installation_guide.md

Modify HTTS of network port 4443 to HTTPS.

Modify installation_guide.md

---

src/chartserver/base_handler.go
src/chartserver/controller.go
src/chartserver/manipulation_handler.go
src/chartserver/repo_handler.go
src/chartserver/reverse_proxy.go

support index file
support object downloading
support health checking
support related manipulating operations except getting chart version

Implement the related handler methods of the transparent operations

---

docs/swagger.yaml
src/ui/api/harborapi_test.go
src/ui/api/ldap.go
src/ui/api/ldap_test.go

It helps to validate the input LDAP group DN.
Refactor related LDAP API for unit testing.

Add REST API to search LDAP by Group DN

---

.drone.yml
tests/integration.sh

This commit enables the images publishing to Docker Hub in Drone CI. Every pull request merging will trigger this process.

Publish images to Docker Hub

---

make/docker-compose.tpl

make/docker-compose.tpl: fix wrong mount configuration(#5208)

---

make/common/templates/ui/env
src/ui/main.go

add sync env to determine whether sync registry to db
fix https://github.com/vmware/harbor/issues/5271

add sync registry env

---

src/common/job/const.go
src/jobservice/job/impl/gc/job.go
src/jobservice/runtime/bootstrap.go

This PR depends on https://github.com/vmware/harbor/pull/5265, plesae just ignore the CI failure.

Add garbage collection job implemention

---

src/adminserver/api/cfg.go
src/adminserver/systemcfg/systemcfg.go
src/adminserver/systemcfg/systemcfg_test.go
src/common/const.go
src/common/utils/utils.go
src/common/utils/utils_test.go
src/ui/api/config.go
src/ui/api/systeminfo.go
src/ui/config/config.go

Add SafeCastString, SafeCastInt, SafeCastFloat64, SafeCastBool function to check
the type matched and avoid panic in runtime
Add default value to configure settings to avoid cannot save configure
issue

Add SafeCast function and set default value for some sytem configure

---

.gitmessage
README.md

1) Remove the reference of MYSQL from README.md
2) Update commit message template to inert an empty line between title
and body.

Update README and .gitmessage

---

contrib/helm/harbor/templates/adminserver/adminserver-secrets.yaml

This commit fixes the issue mentioned int #5326

Fix the mismatch of property used in helm chart

---

src/adminserver/api/cfg.go
src/adminserver/systemcfg/systemcfg.go
src/adminserver/systemcfg/systemcfg_test.go
src/common/const.go
src/common/utils/utils.go
src/common/utils/utils_test.go
src/ui/api/config.go
src/ui/api/systeminfo.go
src/ui/config/config.go

Add SafeCastString, SafeCastInt, SafeCastFloat64, SafeCastBool function to check
the type matched and avoid panic in runtime
Add default value to configure settings to avoid cannot save configure
issue
(cherry-pick from 1.5.0)

Add SafeCast function and set default value for some system configure  -- target master

---

make/harbor.cfg

Reduce config option 'max_job_workers' from **50 to 10**

Modify the cfg option 'max_job_workers' from 50 to 10 to reduce the resource requirement

---

src/chartserver/chart_operator.go

return default empty when file is not existing

Fix the issue of returning '* file not found' error

---

src/adminserver/systemcfg/store/database/driver_db.go
src/common/dao/config.go

var name should not be `error`.

var name should not be error

---

src/ui/api/chart_repository.go

**Update content length of the request when rewriting the content**
* update content length
* check content type before rewriting content

Update content length of request when rewriting the content

---

make/photon/adminserver/Dockerfile
make/photon/clair/Dockerfile
make/photon/jobservice/Dockerfile
make/photon/log/Dockerfile
make/photon/mariadb/Dockerfile
make/photon/nginx/Dockerfile
make/photon/notary/server.Dockerfile
make/photon/notary/signer.Dockerfile
make/photon/postgresql/Dockerfile
make/photon/redis/Dockerfile
make/photon/registry/Dockerfile
make/photon/ui/Dockerfile

This commit update the base photon image from vmware/photon:1.0 to
photon:1.0 in 1.5 branch

Update photon base images -- for 1.5 branch

---

src/ui_ng/lib/src/create-edit-label/create-edit-label.component.html
src/ui_ng/lib/src/create-edit-label/create-edit-label.component.scss
src/ui_ng/lib/src/create-edit-label/create-edit-label.component.ts
src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html

Problem description:
1 label enable sometimes not correct. User input good label names, submit button still disabled.
2 Some times click submit, not working.
Fix:
1 After review the new label code. It trying to use a global variable to control the progress of validation. In the progress of validation, it will disabled the submit button.
This will cause user bad experience. Just remove this logic.
2 Backend use fuzzy matching, the frontend logic did not change before. So when user already have a user name called "abcd",and then input another name called "abc" it will report duplicated name error.
This logic still need change.
3 This is the first version of refine. Can be refine again if find some other logic not correct.

Fix configuration->label->new sometimes not enable.

---

src/ui/main.go

This commit fixes #5283 by not registering scan all policy when Harbor
is not deployed with Clair.

No scan all policy if Clair is not installed.

---

src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.html
src/ui_ng/lib/src/project-policy-config/project-policy-config.component.html
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Problem description:
when user try to new a replication rule, he need to input source project name.
In this case, if user input a project name not exist. The error message will be:"Please add a project name",
this is not accurate.
Fix:
Modify the error message to "This project is not exist".
Plus:Modify the error popup using standard tooltip component.

Replicate project error message is not correct

---

src/chartserver/chart_operator.go
src/chartserver/manipulation_handler.go

**Provide digital signature info of the related chart version**
- if the associated prov file exists, then signed will be true
- otherwise, signed will be false

Provide digital signature info of the related chart version

---

contrib/helm/harbor/templates/adminserver/adminserver-cm.yaml
contrib/helm/harbor/templates/registry/registry-cm.yaml
contrib/helm/harbor/templates/ui/ui-dpl.yaml
contrib/helm/harbor/values.yaml

1. Read value of storage driver from values.yaml for adminserver
2. Set Redis as UI cache
3. Set Redis as registry cache

Fix misc issues of Harbor chart

---

src/ui/api/api_test.go
src/ui/api/chart_repository_test.go

**Add more UT cases for chart repo API controller**
- case for testing require access
- case for testing require namespace
- case for testing multipart checking
- case for testing URL rewriting

Add more UT cases for chart repo API controller

---

contrib/helm/harbor/templates/notary/notary-server.yaml
contrib/helm/harbor/templates/registry/registry-secret.yaml
contrib/helm/harbor/templates/registry/registry-ss.yaml
contrib/helm/harbor/templates/ui/ui-dpl.yaml
contrib/helm/harbor/templates/ui/ui-secrets.yaml
contrib/helm/harbor/values.yaml

The certificate and private key used by token service, registry and notoary server will be generated automatically

Remove the hardcoded certificate and private key in value.yaml

---

make/common/templates/nginx/nginx.http.conf
make/common/templates/nginx/nginx.https.conf
src/ui/controllers/controllers_test.go
src/ui/proxy/interceptors.go
src/ui/proxy/proxy.go
src/ui/router.go

This commit redirects the request to UI directory without URL rewrite

Remove the URL rewrite for docker registry request

---

src/ui/views/index.html
src/ui_ng/src/app/app-config.service.ts
src/ui_ng/src/app/project/member/member.component.html
src/ui_ng/src/app/project/member/member.component.ts
src/ui_ng/src/index.html
src/ui_ng/src/styles.css

Disable "New group" button when user does not login with ldap

New group button should disabled when login without ldap

---

tools/migration/db/schema/registry_create_tables.pgsql

These chanes are introduced by PR 5430, please refer to the PR for details

Add default value for creation time and update time trigger

---

src/ui_ng/src/app/config/auth/config-auth.component.html
src/ui_ng/src/app/config/auth/config-auth.component.scss
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json
src/ui_ng/src/styles.css

Problem description:
currently, harbor does not support config ldap admin DN
Enhancement:
Add ldap admin dn in configuration as a optional config.

Add ldap admin DN

---

contrib/helm/harbor/templates/ingress/ingress.yaml

This commit removes the rewrite ingrss rule in Harbor chart and redirect the requests sent to registry to UI direclty

Remove the rewrite ingress rule

---

contrib/helm/harbor/templates/adminserver/adminserver-cm.yaml
contrib/helm/harbor/templates/chartmuseum/chartmuseum-cm.yaml
contrib/helm/harbor/templates/chartmuseum/chartmuseum-secret.yaml
contrib/helm/harbor/templates/chartmuseum/chartmuseum-ss.yaml
contrib/helm/harbor/templates/chartmuseum/chartmuseum-svc.yaml
contrib/helm/harbor/templates/ui/ui-dpl.yaml
contrib/helm/harbor/values.yaml

This commit integrates the chartmuseum to Harbor chart to enable the feature for storing chart in Harbor

Add chartmuseum to Harbor chart

---

src/ui_ng/src/app/project/member/member.component.scss

Fix remove button not clickable

---

src/chartserver/manipulation_handler.go
src/ui/api/chart_repository.go

**Fix issues described in #5464 and #5465**
- return unified error format by the chart repo API
- update the prov file status at anytime

Fix issues described in #5464 and #5465

---

src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html

Fix argument types of repo delete function

Fix bug of repository can not delete on card view

---

src/ui_ng/lib/src/service/interface.ts
src/ui_ng/src/app/app-config.ts
src/ui_ng/src/app/project/project-detail/project-detail.component.html
src/ui_ng/src/app/project/project-detail/project-detail.component.ts

Add parameter for receving chartmuseum installation state.
Using that to decide the presentation of helmchart tab in project.

Hide the helmcharts tab when chart museum is not installed.

---

src/chartserver/chart_operator.go
src/chartserver/utils.go

Add the error handling to fix go gas issue "Error unhandled"

Fix go gas issue for chart

---

src/ui_ng/lib/src/create-edit-rule/create-edit-rule.component.ts
src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.html
src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.ts

I Helm chart tab. If user upload a chart file. If icon for this chart is empty or not valid chart. Need to show a default logo to show.

Add onError for some logo return 404

---

src/chartserver/controller.go
src/chartserver/utility_handler.go
src/chartserver/utility_handler_test.go
src/ui/api/project.go
src/ui/api/project_test.go

**Enhance the project deletable checking logic to include helm charts checking**
- add utility handler in chart controller to support getting charts by ns
- add ut case for utility handler
- update deletable checking logic in project controller

Enhance the project deletable checking logic to include helm charts checking

---

tests/robot-cases/Group11-Nightly/LDAP.robot

Add API test to LDAP nightly test

Add API test to LDAP nightly test

---

contrib/helm/harbor/templates/adminserver/adminserver-ss.yaml

Fix helm template error

---

docs/swagger.yaml
src/adminserver/systemcfg/store/database/driver_db.go
src/ui/api/projectmember.go
src/ui/api/usergroup.go
src/ui/auth/authenticator.go
src/ui/auth/ldap/ldap.go
src/ui/auth/ldap/ldap_test.go

User groups should not have same DN
Should not import an LDAP group if there is a user group with same DN

Fix LDAP user group related issues

---

src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.html
src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.scss
src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail.component.html
src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail.component.scss

Refine the layout in chart detail page.

Fix some layout issue in chart detail page

---

tests/testcases/Group3-RBAC/3-08-LDAP-define-harbor-admin-by-dn.md

Testcase to verify the option:
LDAP Groups With Admin Privilege

Add testcase for define harbor admin by LDAP group DN

---

tests/resources/APITest-Util.robot
tests/resources/Harbor-Pages/Project-Members.robot
tests/robot-cases/Group11-Nightly/Setup.robot

Generate swagger client before all test
Add Member button change to " + USER".

Add API Test setup and fix Add Member button verify

---

tests/resources/Harbor-Pages/Configuration.robot

fix nightly test fail for project creation moved to system config

fix nightly test fail for project creation moved to system config

---

src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.html
src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.scss
src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.ts
src/ui_ng/lib/src/helm-chart/helm-chart.component.ts
src/ui_ng/src/app/project/member/add-group/add-group.component.html
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

1. Refactor Chart Summary Commands UI
2. Change UI about security table

Fix chart ui related issue

---

README.md

https://www.cncf.io/blog/2018/07/31/cncf-to-host-harbor-in-the-sandbox/
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

Add mention of CNCF in README

---

contrib/helm/harbor/README.md

This commit updates the guide of how to install Harbor with Helm chart

Update the readme of Harbor chart

---

src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.ts

Because HTML render before component initialize, so assign value on onInit

Fix repo is undefined issue on chart summary ui

---

make/common/templates/jobservice/config.yml
make/common/templates/registry/config.yml
make/common/templates/registry/config_ha.yml
make/common/templates/ui/env
make/harbor.cfg
make/prepare

this commit is to separate the redis_url into the host, port, pwd, and index for different components, and make it possible to set external Redis server.

Unify redis configuration for harbor components

---

make/install.sh

**Update the usage message to include chart repository server related info**
- add `Please set --with-chartmuseum if needs enable Chartmuseum in Harbor`

Update the usage message to include chart repository server related info

---

README.md

**Add go report badge to readme file**
- add [![Go Report Card](https://goreportcard.com/badge/github.com/goharbor/harbor)](https://goreportcard.com/report/github.com/goharbor/harbor)

Add go report badge to readme file

---

tests/resources/Harbor-Pages/HomePage.robot

This commit updates the "Sign In Harbor" robot case by adding debug information when it failed

Update robot case to debug the issue got in nightly test

---

tests/apitests/python/test_assign_role_to_ldap_group.py

Use test user to test this case

Fix testcase related to LDAP user can not see any logs

---

contrib/helm/harbor/values.yaml

This commit update the repository in helm chart from vmware namespace to goharbor
Sign-off-by: Daniel Jiang <jiangd@vmware.com>

Update repository reference in helm chart

---

src/ui/api/usergroup.go

user group name can not be empty

---

docs/installation_guide.md

**Update the installation guide doc to append chart repo server related content**

Update the installation guide doc to append chart repo server related content

---

docs/installation_guide.md

**[Cherry-pick] Update the installation guide doc to append chart repo server related content**

[Cherry-pick] Update the installation guide doc to append chart repo server related content

---

docs/user_guide.md

**Append chart repo service related sections to the agenda of user guide doc**

Append chart repo service related sections to the agenda of user guide doc

---

docs/user_guide.md

**Append chart repo service related sections to the agenda of user guide doc**

[Cherry-pick] Append chart repo service related sections to the agenda of user guide doc

---

docs/swagger.yaml

**Update the swagger.yaml file to contain the chart repo service APIs**
- Signed-off-by: Steven Zou <szou@vmware.com>

Update the swagger.yaml file to contain the chart repo service APIs

---

docs/swagger.yaml

**Update the swagger.yaml file to contain the chart repo service APIs**
- Signed-off-by: Steven Zou <szou@vmware.com>

[Cherry-pick] Update the swagger.yaml file to contain the chart repo service APIs

---

Makefile
tests/apitests/python/library/Harbor.py
tests/apitests/python/library/base.py
tests/apitests/python/library/label.py
tests/apitests/python/library/project.py
tests/apitests/python/library/registry.py
tests/apitests/python/library/replication.py
tests/apitests/python/library/repository.py
tests/resources/Docker-Util.robot
tests/robot-cases/Group11-Nightly/Replication.robot

This commit creates a new E2E API test case to verify the replication based on label
Signed-off-by: Wenkai Yin yinw@vmware.com

Add E2E API test cases for replication based on labels

---

src/ui_ng/lib/src/helm-chart/helm-chart.component.html
src/ui_ng/lib/src/helm-chart/helm-chart.component.scss
src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.html
src/ui_ng/lib/src/service/helm-chart.service.ts
src/ui_ng/lib/src/tag/tag-detail.component.html
src/ui_ng/lib/src/tag/tag-detail.component.scss
src/ui_ng/lib/src/tag/tag-detail.component.spec.ts
src/ui_ng/src/app/shared/shared.utils.ts

1 Misc issues for chart repo card view
2 Create group dialog ignores the error from backend
3 The detail page of a scanned image has overlap of text fields.

fix issue helmchart layout related issues

---

docs/swagger.yaml

**Fix the duplicated entry issue in the swagger.yaml doc**
- Signed-off-by: Steven Zou <szou@vmware.com>

Fix the duplicated entry issue in the swagger.yaml doc

---

docs/swagger.yaml

The api includes to trigger gc and add/update/delete gc schedule

Add gc api of regsistryctl to swagger file

---

src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.html
src/ui_ng/lib/src/helm-chart/helm-chart.component.html
src/ui_ng/lib/src/helm-chart/helm-chart.component.scss
src/ui_ng/lib/src/helm-chart/helm-chart.component.ts
src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.html
src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.ts
src/ui_ng/lib/src/shared/shared.const.ts
src/ui_ng/src/app/group/add-group-modal/add-group-modal.component.html
src/ui_ng/src/app/group/add-group-modal/add-group-modal.component.ts
src/ui_ng/src/app/group/group.component.html
src/ui_ng/src/app/project/chart-detail/chart-detail.component.ts
src/ui_ng/src/app/project/list-chart-versions/list-chart-versions.component.ts
src/ui_ng/src/app/project/list-charts/list-charts.component.html
src/ui_ng/src/app/project/list-charts/list-charts.component.ts
src/ui_ng/src/app/project/member/add-group/add-group.component.html
src/ui_ng/src/app/project/member/add-group/add-group.component.ts
src/ui_ng/src/app/project/project-detail/project-detail.component.ts
src/ui_ng/src/app/project/project-routing-resolver.service.ts
src/ui_ng/src/app/shared/shared.const.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

1. Fix Group related issues
2. Edit the wording of version
3. Fix chart upload related issues
4.  Fix incorrect UI views when logging in with a user in the group assigned with proper role
5. Diable delete button when user not admin
6. Remove Upload Button on Chart Version List
7. Fix i18n translate issue

Fix UI related issues

---

src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.html
src/ui_ng/lib/src/helm-chart/helm-chart.component.html
src/ui_ng/lib/src/helm-chart/helm-chart.component.scss
src/ui_ng/lib/src/helm-chart/helm-chart.component.ts
src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.html
src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.ts
src/ui_ng/lib/src/shared/shared.const.ts
src/ui_ng/src/app/group/add-group-modal/add-group-modal.component.html
src/ui_ng/src/app/group/add-group-modal/add-group-modal.component.ts
src/ui_ng/src/app/group/group.component.html
src/ui_ng/src/app/project/chart-detail/chart-detail.component.ts
src/ui_ng/src/app/project/list-chart-versions/list-chart-versions.component.ts
src/ui_ng/src/app/project/list-charts/list-charts.component.html
src/ui_ng/src/app/project/list-charts/list-charts.component.ts
src/ui_ng/src/app/project/member/add-group/add-group.component.html
src/ui_ng/src/app/project/member/add-group/add-group.component.ts
src/ui_ng/src/app/project/project-detail/project-detail.component.ts
src/ui_ng/src/app/project/project-routing-resolver.service.ts
src/ui_ng/src/app/shared/shared.const.ts
src/ui_ng/src/i18n/lang/en-us-lang.json
src/ui_ng/src/i18n/lang/es-es-lang.json
src/ui_ng/src/i18n/lang/fr-fr-lang.json
src/ui_ng/src/i18n/lang/zh-cn-lang.json

Fix Group related issues
Edit the wording of version
Fix chart upload related issues
Fix incorrect UI views when logging in with a user in the group assigned with the proper role
Diable delete button when user not admin
Remove Upload Button on Chart Version List
Fix i18n translate issue

Cherry pick ui bug fix

---

contrib/helm/harbor/README.md

Supplement of the persistence section in the Harbor helm chart document.

helm chart doc improve

---

docs/migration_guide.md

Update migratrion guide for harbor.cfg migration

---

docs/migration_guide.md

Signed-off-by: wangyan <wangyan@vmware.com>

[Cherry-pick]Update migratrion guide for harbor.cfg migration

---

src/ui_ng/lib/src/helm-chart/chart-detail/chart-detail-summary.component.scss
src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.ts

Add table style in markdown and
Fix deleted all version may cause 404

Add github flavered table in markdown

---

OWNERS.md

Signed-off-by: wangyan <wangyan@vmware.com>

Add steven zou into goharbor owner list

---

README.md

Add Codacy badge into README file

---

make/harbor.cfg

'Hostname' is a must parameter for installation and the check for it is hard-coded in install.sh,which could be optimized later.(First pr here)

add some comments to harbor.cfg

---

.github/ISSUE_TEMPLATE
.github/ISSUE_TEMPLATE/issue_template.md
.github/ISSUE_TEMPLATE/proposal_template.md

**Update the issue templates**
- update bug template
- add proposal template

Update the issue templates

---

make/docker-compose.chartmuseum.tpl
make/harbor.cfg
make/photon/chartserver/docker-entrypoint.sh
make/prepare

**Fix issues related with chart storage**
- inject custom CA bundle into chart repo
- update prepare script to inject credentials

Fix issues related with chart storage

---

src/common/models/config.go
src/common/models/project.go
src/common/scheduler/scheduler.go
src/common/utils/clair/client.go
src/common/utils/uaa/client.go
src/jobservice/env/context.go
src/jobservice/job/impl/gc/job.go
src/jobservice/period/redis_scheduler.go
src/jobservice/pool/message_server.go
src/jobservice/utils/gocarft_work.go
src/registryctl/client/client.go
src/registryctl/client/client_test.go
src/registryctl/handlers/handler.go
src/replication/core/controller.go
src/replication/trigger/interface.go
src/replication/trigger/schedule.go
src/ui/api/harborapi_test.go
src/ui/api/models/reg_gc.go
src/ui/api/project_test.go
src/ui/api/reg_gc_test.go
src/ui/api/repository_test.go
src/ui/api/systeminfo.go
src/ui/api/systeminfo_test.go
src/ui/api/user_test.go
src/ui/proxy/interceptors.go
src/ui/service/token/token.go
src/ui/utils/response_handlers.go

Fix misspell checking results

---

.travis.yml
Makefile

Revise and cleanup travis script, and misspell/gofmt to makefile

---

src/chartserver/chart_operator.go
src/chartserver/chart_operator_test.go

**Sort the chart list before returning**
- updatet the chart getting API
- update the corresponding UT case

Sort the chart list before returning

---

docs/swagger.yaml
src/chartserver/chart_operator.go
src/chartserver/client.go
src/chartserver/utility_handler.go
src/chartserver/utility_handler_test.go
src/ui/api/chart_repository.go
src/ui/router.go

**Delete all the versions of the specified chart**
- add API route
- add DELETE chart method in utility handler of chart controller
- add UT case for the newly added methods
- update swagger.yaml to refelct the new change

Delete all the versions of the specified chart

---

contrib/helm/harbor/README.md
docs/migration_guide.md

I think the 'or' should be 'and'. The migrator backups both.
Signed-off-by: silenceshell me@ieevee.com

I think the 'or' should be 'and'

---

.travis.yml
Makefile
make/migrations/postgresql/0002_update_v_length_properties.up.sql
src/ui/api/config_test.go
tests/docker-compose.test.yml
tools/migration/db/changelog.md

Extend configuration length to 1024 in DB

---

Makefile

Remove 'ha' directory reference in Makefile

---

tests/resources/Harbor-Pages/Project-Helmcharts.robot
tests/resources/Harbor-Pages/Project-Helmcharts_Elements.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common.robot

Test case of chart repo

---

.travis.yml
Makefile
make/photon/Makefile
make/photon/adminserver/Dockerfile
make/photon/chartserver/Dockerfile
make/photon/clair/Dockerfile
make/photon/db/Dockerfile
make/photon/jobservice/Dockerfile
make/photon/log/Dockerfile
make/photon/notary/server.Dockerfile
make/photon/notary/signer.Dockerfile
make/photon/redis/Dockerfile
make/photon/registry/Dockerfile
make/photon/registryctl/Dockerfile
make/photon/ui/Dockerfile
tests/resources/Harbor-Util.robot

Clean make file unused code and unify docker build method (#59)

---

open_source_license

Update OSL for Clair  -- 1.6 branch

---

src/common/utils/log/logger_test.go

Fix logger test case, add SetSkipLine func.

---

docs/swagger.yaml
src/chartserver/controller_test.go
src/chartserver/repo_handler.go
src/ui/api/search.go
src/ui/api/search_test.go

**Enhance the global search API to include chart searching result**
- add chart search interface method in utility handler
- update the search API handler
- update the search API UT case

Enhance the global search API to include chart searching result

---

open_source_license

Update OSL for Clair 2.0.5

---

README.md

**Correct the url location of the Codacy badge**
- add status report url link

Correct the url location of the Codacy badge

---

src/portal/lib/src/shared/shared.const.ts
src/portal/src/app/shared/about-dialog/about-dialog.component.html
src/portal/src/app/skinable-config.service.ts

remove static after angular 6 ugprade

---

LICENSE
open_source_license

Update LICENSE and OSL

---

make/docker-compose.tpl

Add depdends_on to portal container

---

docs/swagger.yaml

The swagger was a little misleading about the API to update user's
password.  This commit clarifies the usage of 'old_password' and 403
status code.
Other change was generated by the online editor

Update swagger.yaml for API to update password

---

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss

Signed-off-by: chengfangyuan <1309173081@qq.com>
I adjust the layout about 'Trigger Mode' to fit on one line

Make the replication dialog a little bit wider

---

src/portal/src/app/group/group.component.html

This is the error of #5495.
If no group , the delete button is enabled.
Signed-off-by: ChengFangyuan <1309173081@qq.com>

Disable delete button when there is no group

---

src/portal/lib/src/label/label.component.html
src/portal/lib/src/label/label.component.scss
src/portal/lib/src/replication/replication.component.html
src/portal/src/app/project/member/member.component.html
src/portal/src/app/project/member/member.component.scss
src/portal/src/app/project/project-label/project-label.component.html
src/portal/src/app/project/project-label/project-label.component.scss
src/portal/src/app/replication/replication-page.component.html
src/portal/src/app/repository/repository-page.component.html

fixed #5886 
Adjust the label's margin-top or top to make the space between the button and the tab part consistent
Signed-off-by: Cheng Fangyuan<1309173081@qq.com>

Make the space between the button and the tab section consistent

---

src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json

fixed #5883 
Make Tooltip prompt "repository read-only"
Signed-off-by: Cheng Fangyuan<1309173081@qq.com>

Tooltip prompts 'repository read only'

---

README.md

**Update README to reflect the related changes delivered in V1.6.0**

Update README to reflect the related changes delivered in V1.6.0

---

src/common/dao/admin_job.go
src/ui/api/models/reg_gc.go
src/ui/api/reg_gc.go
src/ui/api/reg_gc_test.go

1, Return json format of gc schedule
2, Unify capital and small letter
3, Return gc records by desc

Update gc api to fix issues found by UI implemention 

---

tests/integration.sh

This commit is to remove tests from drone CI server, and leave drone
as the build system only for harbor. Harbor system admin will remove
the webhook from harbor repo, then any pull request will not trigger
drone job.

Decrepate tests from drone ci

---

Makefile
src/chartserver/repo_handler.go
src/core/api/harborapi_test.go
src/core/api/search_test.go

Signed-off-by: 陈德 <chende@caicloud.io>
Related to: https://github.com/goharbor/harbor/pull/5827
Add comment format check to makefile and travis CI

Add comment format check to makefile and travis

---

src/portal/lib/src/config/registry-config.component.ts
src/portal/lib/src/config/system/system-settings.component.ts
src/portal/lib/tsconfig.lib.json
src/portal/package.json
src/portal/src/app/app.module.ts
src/portal/src/app/config/config.component.html
src/portal/src/app/config/config.component.ts
src/portal/src/app/config/config.module.ts
src/portal/src/app/config/gc/gc.api.repository.ts
src/portal/src/app/config/gc/gc.component.html
src/portal/src/app/config/gc/gc.component.scss
src/portal/src/app/config/gc/gc.component.spec.ts
src/portal/src/app/config/gc/gc.component.ts
src/portal/src/app/config/gc/gc.const.ts
src/portal/src/app/config/gc/gc.service.ts
src/portal/src/app/config/gc/gc.utility.ts
src/portal/src/app/config/gc/gc.viewmodel.factory.ts
src/portal/src/app/config/gc/gcLog.ts
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json

This pr contains the main logic of gc ui . 
The main functionalities are: 
1 Start a manual gc task. 
2 Start a schedule gc task. 
3 Show top 10 jobs in main view. 
4 Fix the i18n issues after upgrade to angular6

Implementation of  GC UI

---

tests/integration.sh

Fix error on packaging offline installer with Drone

---

src/portal/lib/src/create-edit-label/create-edit-label.component.html
src/portal/lib/src/create-edit-label/create-edit-label.component.scss

fixed: #5114 
Remove the trigger button and make our own button style
Signed-off-by: Cheng Fangyuan<1309173081@qq.com>

After selecting color, the color button is closed

---

src/portal/src/app/config/gc/gc.component.html
src/portal/src/app/config/gc/gc.component.scss
src/portal/src/app/config/gc/gc.component.ts
src/portal/src/app/config/gc/gc.const.ts
src/portal/src/app/config/gc/gc.viewmodel.factory.ts
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json

Fix some small issues in ui
1 Modify the edit button to small size
2 Disable the "gc now" button after click and enable it after 1 minute. 
3 show log detail when job status is finished and error.

Modify some small issues in gc ui

---

make/common/templates/nginx/nginx.http.conf
make/common/templates/nginx/nginx.https.conf
src/core/controllers/controllers_test.go
src/core/router.go
src/portal/src/app/account/password-setting/password-setting.service.ts
src/portal/src/app/account/sign-in/sign-in.service.ts
src/portal/src/app/shared/session.service.ts
tests/userlogintest.sh

1. Change backend api
2. Change frontend api
3. Change the proxy config file

Refactor backend api for authrization

---

.travis.yml
Makefile
tests/travis/distro_installer.sh

Add installer pipeline in travis

---

tests/resources/Harbor-Pages/Configuration.robot

Modified the xpath that created the label
Signed-off-by: Cheng Fangyuan     <fangyuanc@vmware.com>

Fix the error caused by deleting the button in lable

---

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss

Because it caused some errors. So restore the replitaion dialog
Signed-off-by: Cheng Fangyuan    <fangyuanc@vmware.com>

Revert replication dialog

---

src/portal/src/app/config/gc/gc.component.ts
src/portal/src/app/config/gc/gc.const.ts
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json

Refresh page after 3 seconds to fresh job status.

fresh page after job finished

---

.travis.yml
src/core/api/project.go
tests/travis/api_run.sh

Fix #5956 issue: **The APIs should not get chart information when Harbor is not installed with chart repo**

Fix #5956 issue: The APIs should not get chart information when Harbor is not installed with chart repo

---

docs/user_guide.md

I was reading through the Helm charts docs and saw a couple of places for minor improvements such as adding some extra links for future readers and fixing a typo.

Minor improvements to Helm charts documentation

---

ADOPTERS.md

Listing publicly-referenceable users in ADOPTERS.md.

Creating ADOPTERS.md

---

.github/stale.yml

Update the settings to extend the "Days until stale" and "Days untile
close".  Added other exempt labels.

Update the settings in stale.yml

---

docs/compile_guide.md
docs/installation_guide.md
docs/kubernetes_deployment.md
docs/manage_role_by_ldap_group.md
docs/migration_guide.md
docs/upgradetest.md
docs/use_notary.md
docs/user_guide.md

Updated documentation files to fix typo's

Documentation typo correction

---

tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/Vulnerability.robot
tests/robot-cases/Group1-Nightly/Common.robot

Longer the wait time to pass the nightly testing

Update automation test cases

---

CONTRIBUTING.md

Updated directory paths and URLS in contributing.md to reflect new repo

Updated github and directory paths for repo change to goharbor

---

src/portal/package-lock.json
src/portal/package.json
src/portal/src/app/shared/gauge/gauge.component.html
src/portal/src/app/shared/gauge/gauge.component.scss
src/portal/src/app/shared/gauge/gauge.component.ts

After refactor gauge component, jquery can be removed from harbor. 

refactor gauge component using angular way,remove jquery

---

src/portal/lib/src/helm-chart/helm-chart.component.html
src/portal/lib/src/helm-chart/helm-chart.component.scss
src/portal/lib/src/helm-chart/helm-chart.component.ts
src/portal/lib/src/helm-chart/versions/helm-chart-version.component.ts
src/portal/lib/src/service/helm-chart.service.ts
src/portal/lib/src/service/interface.ts
src/portal/lib/src/shared/shared.const.ts

1. Add delete chart button
2. Add download chart button

Add buttons to chart list view

---

tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/Vulnerability.robot
tests/robot-cases/Group1-Nightly/Common.robot

Update the automation test cases to pass the nightly testing

Update test cases

---

src/portal/lib/AUTHORS
src/portal/lib/package.json

modify harbor ui package structure

---

src/jobservice/job/impl/logger/job_logger.go

**Log error if failed to create logger for job**

Log error if failed to create logger for job

---

tests/travis/ut_install.sh

The golint repository is updated, this commit changes it with the latest version

Update golint repository used in travis

---

tests/robot-cases/Group1-Nightly/Common.robot

Replace image hello-world with busybox as the hello-world has been scaned in the last case

Update scan automation test case

---

tests/resources/Harbor-Pages/Project.robot

Add "Wait Until" to ensure the "Save" button is clicked

Update automation test case "Make Project Public/Private"

---

make/common/templates/jobservice/env
make/prepare
src/adminserver/client/client.go
src/adminserver/handlers/router.go
src/common/utils/test/adminserver.go
src/core/api/config.go
src/core/api/config_test.go
src/core/api/harborapi_test.go
src/core/router.go
src/jobservice/config/config.go

Refactor admin client, remove the dependency to adminserver to core server

Change admin server to core in jobservice

---

src/portal/src/app/user/user.component.html

modify delete to uppercase

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Configuration_Elements.robot
tests/robot-cases/Group1-Nightly/Common.robot

add gc e2e test case

---

tests/integration.sh

Publish images to docker hub with dev tag only for master branch changes

Update CI script run in Drone

---

src/portal/lib/src/config/registry-config.component.spec.ts
src/portal/lib/src/config/vulnerability/vulnerability-config.component.html
src/portal/lib/src/config/vulnerability/vulnerability-config.component.scss
src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
src/portal/src/app/config/config.component.ts
src/portal/src/app/config/gc/gc.component.html
src/portal/src/app/config/gc/gc.component.scss
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json

fixed #5935 
Added Edit button，Make the vulnerability configuration page consistent with the GC page behavior.
Signed-off-by: Fangyuan Cheng (c) <fangyuanc@vmware.com>

Refactoring the vulnerability UI to make it similar to GC.

---

src/portal/src/app/account/sign-in/sign-in.component.html
src/portal/src/app/account/sign-in/sign-in.component.scss
src/portal/src/app/account/sign-in/sign-in.component.ts
src/portal/src/app/app-config.ts

add a configuration file in portal/app.config.js
by default it set showPopularRepo to false.

hide the popular repositories by default

---

src/portal/lib/src/tag/tag.component.html
src/portal/lib/src/tag/tag.component.ts

fixed #3673 
Disable manual scan when vulnerability data is not ready.

Disable scan button when vulnerability data is not ready.

---

make/photon/Makefile
make/photon/adminserver/Dockerfile
make/photon/chartserver/Dockerfile
make/photon/clair/Dockerfile
make/photon/core/Dockerfile
make/photon/db/Dockerfile
make/photon/db/docker-entrypoint.sh
make/photon/jobservice/Dockerfile
make/photon/log/Dockerfile
make/photon/nginx/Dockerfile
make/photon/notary/server.Dockerfile
make/photon/notary/signer.Dockerfile
make/photon/portal/Dockerfile
make/photon/redis/Dockerfile
make/photon/registry/Dockerfile
make/photon/registryctl/Dockerfile

Build harbor images based on photon 2.0

---

.travis.yml
tests/travis/api_run.sh

Add step to upload travis logs into GCR

---

src/portal/lib/src/_mixin.scss
src/portal/lib/src/helm-chart/chart-detail/chart-detail-summary.component.html
src/portal/lib/src/helm-chart/chart-detail/chart-detail-summary.component.ts
src/portal/lib/src/helm-chart/chart-detail/chart-detail.component.html
src/portal/lib/src/helm-chart/versions/helm-chart-version.component.html
src/portal/lib/src/helm-chart/versions/helm-chart-version.component.scss
src/portal/lib/src/helm-chart/versions/helm-chart-version.component.ts
src/portal/lib/src/label/index.ts
src/portal/lib/src/label/label-marker/label-marker.component.html
src/portal/lib/src/label/label-marker/label-marker.component.scss
src/portal/lib/src/label/label-marker/label-marker.component.ts
src/portal/lib/src/label/label-signpost/label-signpost.component.html
src/portal/lib/src/label/label-signpost/label-signpost.component.scss
src/portal/lib/src/label/label-signpost/label-signpost.component.ts
src/portal/lib/src/service/helm-chart.service.ts
src/portal/lib/src/service/interface.ts
src/portal/lib/src/service/label.service.ts
src/portal/lib/src/service/resource-label.service.ts
src/portal/lib/src/shared/shared.const.ts
src/portal/lib/src/shared/shared.utils.ts
src/portal/lib/src/tag/tag.component.html
src/portal/lib/src/tag/tag.component.scss
src/portal/src/app/project/list-chart-versions/list-chart-versions.component.html
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json

1. Add label marker componet
2. Add label signpost component
3. Add label button in chartversion
4. Show labels on chart summary

Add label 2 helm chart

---

tests/resources/Harbor-Pages/ToolKit.robot

Add "Capture Page Screenshot" to help debug the case failure

Add debug info to automation test case

---

tests/resources/Harbor-Pages/Project.robot

Replace the "Sleep x seconds" with "Wait Until xxx" in the "Delete Repo" case

Update automation test case "Delete Repo"

---

src/portal/lib/src/tag/tag.component.html
src/portal/lib/src/tag/tag.component.ts

This reverts commit 2a3c1134585893cd26ce2941a9b2a08f73b65979.
Signed-off-by: Cheng Fangyuan fangyuanc@vmware.com

Revert "Disable scan button when vulnerability data is not ready."

---

src/portal/lib/src/tag/tag-detail.component.html
src/portal/lib/src/tag/tag-detail.component.ts
src/portal/lib/src/vulnerability-scanning/result-grid.component.html
src/portal/lib/src/vulnerability-scanning/result-grid.component.ts
src/portal/src/app/account/sign-in/sign-in.component.scss
src/portal/src/app/repository/tag-detail/tag-detail-page.component.html
src/portal/src/app/repository/tag-detail/tag-detail-page.component.ts

Disable scan button in tag detail page if login with normal user role

---

src/portal/lib/src/service/interface.ts
src/portal/src/app/base/global-search/search-result.component.html
src/portal/src/app/base/global-search/search-result.component.ts
src/portal/src/app/base/global-search/search-results.ts
src/portal/src/app/project/project.service.ts
src/portal/src/app/shared/list-chart-version-ro/list-chart-version-ro.component.html
src/portal/src/app/shared/list-chart-version-ro/list-chart-version-ro.component.ts
src/portal/src/app/shared/list-project-ro/list-project-ro.component.ts
src/portal/src/app/shared/shared.module.ts
src/portal/src/app/shared/shared.utils.ts
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json

Include helmchart to global search resault related to #5791

Feature: Add helmchart version result in global search result

---

src/portal/src/app/account/sign-in/sign-in.component.scss

add the default login page image by clarity.

add login page image

---

src/portal/lib/src/helm-chart/versions/helm-chart-version.component.html
src/portal/lib/src/helm-chart/versions/helm-chart-version.component.scss
src/portal/lib/src/helm-chart/versions/helm-chart-version.component.ts
src/portal/lib/src/label/index.ts
src/portal/lib/src/label/label-filter/label-filter.component.html
src/portal/lib/src/label/label-filter/label-filter.component.scss
src/portal/lib/src/label/label-filter/label-filter.component.ts
src/portal/lib/src/label/label-signpost/label-signpost.component.html
src/portal/lib/src/label/label-signpost/label-signpost.component.scss
src/portal/lib/src/shared/shared.const.ts
src/portal/lib/src/tag/tag.component.html
src/portal/src/app/base/global-search/search.component.scss
src/portal/src/app/shared/list-chart-version-ro/list-chart-version-ro.component.ts
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json

1. Add Filter to helmchart datagrid
2. Fix UI misc issues

Enhancement: Harbor Helmchart UI Label

---

src/portal/src/app/config/auth/config-auth.component.ts

UAA should editable if no uaa users in db

Fix: UAA can not edit after save

---

make/migrations/postgresql/0002_1.7.0_schema.up.sql
make/migrations/postgresql/0002_update_v_length_properties.up.sql
src/common/models/scan_job.go
src/core/config/config_test.go
src/core/main.go

Not submit scan all job when core container starts

---

src/replication/source/convertor.go
src/replication/source/default_filter_chain.go
src/replication/source/default_filter_chain_test.go
src/replication/source/filter.go
src/replication/source/label_filter.go
src/replication/source/label_filter_test.go
src/replication/source/pattern_filter.go
src/replication/source/pattern_filter_test.go
src/replication/source/repository_convertor.go
src/replication/source/repository_convertor_test.go
src/replication/source/repository_filter.go
src/replication/source/repository_filter_test.go
src/replication/source/tag_combination_filter.go
src/replication/source/tag_combination_filter_test.go
src/replication/source/tag_convertor.go
src/replication/source/tag_convertor_test.go
src/replication/source/tag_filter.go
src/replication/source/tag_filter_test.go

* s/convertor/converter
* s/Convertor/Converter
Signed-off-by: clouderati <35942204+clouderati@users.noreply.github.com>

Fix mispelling

---

src/portal/src/app/shared/new-user-form/new-user-form.component.html

Username can longer then 20 in UI (255 currently)

Extend username length

---

src/jobservice/opm/job_stats_mgr.go
src/jobservice/opm/redis_job_stats_mgr.go
src/jobservice/period/enqueuer.go

Fix the web hook mising issue for the periodic job executions

---

src/portal/src/app/config/gc/gc.component.html
tests/resources/Harbor-Pages/Replication.robot

modify test case since replication log change to popup a new page

---

src/portal/lib/src/helm-chart/versions/helm-chart-version.component.scss
src/portal/lib/src/label/label-marker/label-marker.component.html
src/portal/lib/src/label/label-marker/label-marker.component.scss
src/portal/lib/src/tag/tag-detail.component.html

Fix label centering on label
Fix icon centering on button

Fix chart label bugs

---

src/jobservice/job/impl/demo_job.go
src/jobservice/period/enqueuer.go
src/jobservice/period/enqueuer_test.go
src/jobservice/utils/keys.go

Fix the issue of duplicated periodic job scheduling

---

src/jobservice/api/handler.go
src/jobservice/errs/errors.go
src/jobservice/period/redis_scheduler.go

Return 409 conflict error in lieu of 200 with the ID of existing one when submitting the periodic job

Return 409 conflict error in liue of 200 with ID of existing one

---

src/core/service/notifications/registry/handler.go

add for supporting jib client.
test success.
step1.compile harbor and bring up
2.config new harbor IP and account password in pom.xml in jib block.
3.compile using jib plugin and jib will auto pushing image to harbor.
4.check the image in project in harbor. success.
resubmit for PR  https://github.com/goharbor/harbor/pull/5873

5178 jib supporting

---

src/portal/lib/src/datetime-picker/date-validator.directive.ts
src/portal/lib/src/datetime-picker/datetime-picker.component.html
src/portal/lib/src/datetime-picker/datetime-picker.component.scss
src/portal/lib/src/datetime-picker/datetime-picker.component.ts
src/portal/lib/src/replication/replication.component.html
src/portal/lib/src/replication/replication.component.scss
src/portal/src/app/log/audit-log.component.html
src/portal/src/app/log/audit-log.component.scss
src/portal/src/app/log/audit-log.component.ts

fixed #6073 
Change Datapicker on replication to clarity widget

Change Datapicker on replication to clarity widget

---

src/portal/lib/src/repository/repository.component.html
src/portal/lib/src/repository/repository.component.ts
src/portal/lib/src/tag/tag.component.html
src/portal/lib/src/tag/tag.component.ts
src/portal/src/app/repository/tag-repository/tag-repository.component.html
src/portal/src/app/repository/tag-repository/tag-repository.component.ts

Signed-off-by: 陈德 <chende@caicloud.io>

Allow retag in portal only for developer or above role

---

src/jobservice/api/router.go

Remove auth required constraint for the health check endpoint `/api/v1/stats` to enable free call in the HA deployment like Helm chart.

Support health check free call in job service

---

src/portal/lib/src/config/system/system-settings.component.ts
src/portal/lib/src/index.ts
src/portal/lib/src/utils.ts
src/portal/src/app/config/auth/config-auth.component.html
src/portal/src/app/config/auth/config-auth.component.ts
src/portal/src/app/config/config.component.html
src/portal/src/app/config/config.component.ts
src/portal/src/app/config/config.msg.utils.ts
src/portal/src/app/config/email/config-email.component.html
src/portal/src/app/config/email/config-email.component.ts

1 remove save and cancel button from config.component.ts
2 add save and cancel logic in authentication and email and system component. 
3 getChanges function add filter to filterout other changes in configuration.

refactor configuration

---

src/jobservice/period/enqueuer.go

Sharing the existing redis conn with the enqueuer may cause incorrect behavior of redis `set key value EX 30000 NX` command. That might be an issue from the redis client library.
Moreover, generate an identity for the enqueuer and append that identity in the log of `enqueue` loop.

Use separate redis conn for the lock mechanism in the periodic enqueuer

---

tests/integration.sh

Publish images to docker hub with dev tag only for master branch changes

Update CI script run in Drone (#6053)

---

tests/resources/Harbor-Pages/Configuration.robot

There is a typpo error in one of the test case, it lead to the variable can not find.

Fix nightly

---

src/portal/lib/src/helm-chart/versions/helm-chart-version.component.html
src/portal/lib/src/helm-chart/versions/helm-chart-version.component.ts
src/portal/lib/src/tag/tag.component.html
src/portal/src/app/project/list-chart-versions/list-chart-versions.component.html
src/portal/src/app/project/list-chart-versions/list-chart-versions.component.ts

When a ordinary user logs in, the button to add label in images will be disabled.

Ordinary user login is forbidden to add labels in images.

---

tests/apitests/python/library/base.py
tests/apitests/python/library/docker_api.py
tests/apitests/python/library/label.py
tests/apitests/python/library/project.py
tests/apitests/python/library/repository.py
tests/apitests/python/library/user.py
tests/apitests/python/test_add_member_to_private_project.py
tests/apitests/python/test_add_sys_label_to_tag.py
tests/apitests/python/test_del_repo.py
tests/apitests/python/testutils.py
tests/robot-cases/Group0-BAT/API_DB.robot

Add repository library, add API TC add-sys-label-to-tag and del-repo.

add tc add-sys-label-to-tag and del-repo

---

CHANGELOG.md

Updated change log for v1.4.0 -> v1.6.0

---

tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common.robot

Update the automation case to wait until the vul data is ready before running the scan-on-push case

Check the vul data before running scan-on-push case

---

OWNERS.md

Signed-off-by: clouderati <35942204+clouderati@users.noreply.github.com>

Updating OWNERS.md with affiliation

---

docs/configure_https.md

Rebase PR #4279
Close Issue #4258 
Refine Configure_https.md so that HTTPS can work and comply with Subject Alternative Name (SAN) and x509 v3 extension requirement. The document outline is as follows:
Getting Certificate Authority
Getting Server Certificate
Getting Client Certificate
Configuration and Installation
Troubleshooting

Refine Configure_https.md

---

src/portal/src/index.html

Fix:Vmware is appeared in ihe title of loading page

---

src/portal/lib/package.json

We need publish a rc6 version for remove registry component.

upgrade package version to rc6

---

tests/resources/Harbor-Pages/Project-Members.robot
tests/robot-cases/Group1-Nightly/Common.robot

1. Add "Wait Until ..." to "Change User Role In Project"
2. Rename case name to "Scan Image On Push"

Update automation test case

---

tests/apitests/python/library/replication.py
tests/apitests/python/library/repository.py
tests/apitests/python/library/target.py
tests/apitests/python/test_add_replication_rule.py
tests/robot-cases/Group0-BAT/API_DB.robot

Add test case of add-a-replication-rule and replication library.

add test case of add a replication rule

---

tests/resources/Harbor-Pages/Configuration_Elements.robot

when the code structure changed, xpath very easilly to break, modify the xpath will browser suggested.

modify test ldap button xpath

---

src/portal/lib/package.json
src/portal/lib/src/config/registry-config.component.html
src/portal/lib/src/config/registry-config.component.spec.ts
src/portal/lib/src/config/vulnerability/vulnerability-config.component.html

We need to modify registry component using tabs to make ui looks good after refactor configuration.

Refactor registry for admiral

---

make/photon/db/Dockerfile

Fix issue when query psql cli failed on more command not found

---

make/docker-compose.chartmuseum.tpl
make/docker-compose.clair.tpl
make/docker-compose.tpl
make/photon/chartserver/Dockerfile
make/photon/chartserver/docker-entrypoint.sh
make/photon/clair/Dockerfile
make/photon/clair/docker-entrypoint.sh
make/photon/common/install_cert.sh
make/photon/registry/Dockerfile
make/photon/registry/entrypoint.sh
make/prepare

Install custom cert for clair, registry, chartmuseum

---

tests/apitests/python/library/project.py

Modify sequence of return value in project library create project part.

Only modify lib-project for seq of return

---

tests/apitests/python/test_add_member_to_private_project.py
tests/apitests/python/test_add_replication_rule.py
tests/apitests/python/test_add_sys_label_to_tag.py
tests/apitests/python/test_del_repo.py

Modify 4 scripts which call create project function in Project.py.

Modify script call create project
