goharbor/harbor

src/portal/src/app/base/left-side-nav/config/config.service.ts

1. Fixes #16848
Remove message prompt clearing code, as the message prompt will automatically disappear in 10 seconds
Fixes #(issue)

Remove message prompt clearing

---

src/portal/src/app/shared/components/navigator/navigator.component.html
src/portal/src/app/shared/components/navigator/navigator.component.ts
src/portal/src/app/shared/pipes/harbor-datetime.pipe.ts
src/portal/src/app/shared/units/shared.utils.ts

1. Modify HarborDatetimePipe to pure pipe to improve performance
2. Remove some redundant code
Fixes #(issue)

Modify HarborDatetimePipe to pure pipe to improve performance

---

Makefile
src/.golangci.yaml
src/chartserver/reverse_proxy.go
src/chartserver/utils.go
src/common/http/tls.go
src/controller/replication/flow/mock.go
src/core/api/chart_repository.go
src/core/controllers/base.go
src/pkg/allowlist/validator.go
src/pkg/exporter/js_worker.go
src/pkg/reg/adapter/aliacr/types.go
src/pkg/reg/adapter/artifacthub/consts.go
src/pkg/reg/adapter/gitlab/client.go
src/pkg/reg/adapter/tencentcr/adapter.go
src/pkg/scan/postprocessors/report_converters.go
src/pkg/scan/report/manager.go
src/pkg/systemartifact/dao/dao.go

Enable several linters due to prior merged PR and fix several deadcode lint
enable: 
`bodyclose` (https://github.com/goharbor/harbor/pull/16820/files)
`govet` (no error)
`deadcode` (this pr)
Fixes #(issue)

fix deadcode lint & update golangci-lint.yaml

---

make/common.sh

support docker compose v2

---

make/photon/prepare/models.py

Fixes #([16949](https://github.com/goharbor/harbor/issues/16949))

fix(prepare): validate expire hours when enable cache (#16949)

---

.github/release.tpl
.github/workflows/publish_release.yml
tools/release/release_utils.sh

When release, this workflow will be triggered to complete subsequent work.
1 Push harbor images to dockerhub.
2 Upload asset to release.
3 Generate release notes using the `.github/release.yml` template.
Fixes #16935

Add Publish Release workflow

---

tests/resources/Harbor-Pages/Project-Tag-Retention.robot
tests/resources/Harbor-Pages/Project-Webhooks.robot
tests/resources/Harbor-Pages/ToolKit.robot
tests/resources/TestCaseBody.robot
tests/resources/Util.robot
tests/resources/Webhook-Util.robot
tests/robot-cases/Group1-Nightly/Common.robot
tests/robot-cases/Group1-Nightly/Webhook.robot

1.Add Webhook Tester to the test environment.
2.Create a new project and enable webhook.
3.Trigger different event types(Artifact pushed、Artifact
pulled、Artifact deleted、Scanning finished、Scanning stopped、Tag
retention finished、Replication finished、Quota near threshold、Quota exceed).
4.Verify that the message is correct in the Webhook Tester.
5.Moved Webhook CRUD test cases from Common.robot to Webhook.robot for
triage.
Fixes  #15097

Add webhook functionality test case

---

src/server/v2.0/handler/purge.go

The purge job update time is wrong

---

tests/robot-cases/Group1-Nightly/Routing.robot

Because this PR modifies the routing of the Web UI.
1 Modify harbor/gc to harbor/clearing-job/gc.
2 Added harbor/clearing-job/audit-log-purge route.
3 Added harbor/configs/security route.
Fixes #(issue)

Update Web Routing test case

---

src/portal/.stylelintrc.json
src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.html
src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.ts
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.ts
src/portal/src/app/base/left-side-nav/config/security/security.component.ts
src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.ts
src/portal/src/app/base/project/tag-feature-integration/tag-retention/tag-retention.component.ts
src/portal/src/app/shared/services/interface.ts

Fixes #16968
1.  Automatically refresh duration for retention execution
Fixes #16962
2. Correct the status for GC and Log rotation
Fixes #16924
3. Clear registry cache for creating a project
Fixes #(issue)

Fix some UI issues

---

src/common/rbac/project/rbac_util.go

Response the sign status to UI for the public project.
Fixes #16940

fixes 16940

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Configuration_Elements.robot
tests/resources/Harbor-Pages/GC.robot
tests/resources/Harbor-Pages/GC_Elements.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common_GC.robot
tests/robot-cases/Group1-Nightly/Schedule.robot

This PR #16941 modifies the GC UI, so update the test cases.
1 Update GC web element xpath.
2 Migrate GC content from Configuration.robot to GC.robot for classification.
Fixes #(issue)

Update GC UI Testcase

---

api/v2.0/swagger.yaml
src/jobservice/job/impl/gc/garbage_collection.go
src/jobservice/job/impl/gc/garbage_collection_test.go
src/server/v2.0/handler/gc.go

Support stop GC execution
Fixes 16902
Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>
Fixes #(issue)

Support stop GC execution

---

src/jobservice/hook/hook_agent.go
src/jobservice/hook/hook_client.go
src/jobservice/runtime/bootstrap.go

fix: update the jobservice hook retry concurrency

---

src/pkg/task/dao/execution.go

Skip to refresh execution status when unchanged

---

src/pkg/task/dao/execution.go

(cherry-pick) Skip to refresh execution status when unchanged

---

make/migrations/postgresql/0081_2.5.2_schema.up.sql

migrate: add db index on artifact repository name

---

src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
src/portal/src/app/shared/entities/shared.const.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Fixes #17007
1. Select any running gc executions
2. Click confirm button to stop them
Fixes #(issue)

Add stop button for GC

---

tests/resources/Harbor-Pages/Project-Webhooks.robot
tests/resources/TestCaseBody.robot
tests/robot-cases/Group1-Nightly/Webhook.robot

Increase retry to improve test case stability.
Fixes #(issue)

Enhance webhook testcase

---

make/common.sh
make/install.sh

update support for docker compose v2

---

src/.golangci.yaml
src/pkg/reg/adapter/aliacr/types.go
src/pkg/reg/adapter/tencentcr/adapter.go

This PR update code to fix varcheck of golangci-lint.
Fixes #(issue)

fix: update code for golangci-lint varcheck

---

src/server/v2.0/handler/notification_policy.go
src/server/v2.0/handler/preheat.go
src/server/v2.0/handler/robot.go

Change regular expression in robot account
Fixes #(issue)

(cherry-pick) Unify the process of jobservice execution/task retrieve and update

---

make/photon/prepare/Dockerfile.base

removing httpd on prepare base DockerFile

---

make/photon/prepare/Dockerfile.base

update install htpasswd in prepare dockerfile

---

src/server/v2.0/handler/retention.go

fix: fix the update of retention policy

---

.github/workflows/publish_release.yml

Update publish release workflow dockerhub account

---

src/core/middlewares/middlewares.go
src/server/middleware/url/parse.go
src/server/middleware/url/parse_test.go

The middleware can give a uniform url validation and raised error early.
Fixes #(issue)

[cherry-pick]add url raw query check middleware

---

src/portal/src/app/services/event-service/event.service.spec.ts
src/portal/src/app/services/event-service/event.service.ts
src/portal/src/app/shared/components/push-image/copy-input.component.ts
src/portal/src/app/shared/components/third-party/ngx-clipboard/clipboard.service.ts

Fixes #17001
1. Now only the activated copy command component will turn green
Fixes #(issue)

Improve copy command component

---

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Fixes #17043
1. Not allow "*" for the "Minutes" field
Fixes #(issue)

Improve cron validator for replication rule

---

src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.html
src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.spec.ts
src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.ts
src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.html
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.spec.ts
src/portal/src/app/shared/entities/shared.const.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Fixes #17007
1. Select any running executions
2.  Click the stop button then confirm
Fixes #(issue)

Add stop button for audit log rotation

---

src/common/rbac/project/rbac_role.go
src/controller/scan/base_controller.go
src/controller/scan/base_controller_test.go
src/controller/scan/controller.go
src/core/api/chart_label.go
src/server/v2.0/handler/artifact.go
src/server/v2.0/handler/scan.go
src/testing/controller/scan/controller.go

Add checks in label
Fixes #(issue)

Fix scan log mismatch issue

---

src/pkg/p2p/preheat/dao/instance/dao.go
src/pkg/p2p/preheat/dao/instance/dao_test.go
src/server/v2.0/handler/preheat.go

1. fix preheat dao Get method
2. update preheat tasks and getLog api
Fixes #(issue)

fix: update preheat api handler and DAO

---

make/photon/prepare/Dockerfile.base

[cherry-pick]Upgrade pipenv to 2022.1.8

---

src/common/registryctl/client.go
src/jobservice/job/impl/gc/garbage_collection.go
src/jobservice/job/impl/gc/util.go
src/jobservice/logger/entry_test.go
src/jobservice/logger/sweeper_controller.go
src/jobservice/runtime/bootstrap_test.go
src/lib/cache/memory/memory.go
src/pkg/registry/client.go
src/pkg/registry/interceptor/interceptor.go
src/pkg/registry/interceptor/readonly/interceptor.go
src/pkg/registry/interceptor/readonly/interceptor_test.go
src/registryctl/client/client.go

Enhance the read-only API to avoid deleting operations during the job running
Fixes #16901
Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>
Fixes #(issue)

Enhance the read-only API to avoid deleting operations during the job running

---

tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/Project_Elements.robot
tests/resources/TestCaseBody.robot

Added error retries to improve test stability
Fixes #(issue)

Enhancement Stop Scan Testcase

---

src/.golangci.yaml
src/controller/systemartifact/execution.go
src/core/main.go
src/core/session/session.go
src/jobservice/job/impl/gc/garbage_collection.go
src/jobservice/job/impl/gc/garbage_collection_test.go
src/lib/config/systemconfig.go
src/pkg/accessory/manager.go
src/pkg/accessory/manager_test.go
src/pkg/cached/artifact/redis/manager.go
src/pkg/cached/artifact/redis/manager_test.go
src/pkg/cached/manifest/redis/manager.go
src/pkg/cached/manifest/redis/manager_test.go
src/pkg/cached/project/redis/manager.go
src/pkg/cached/project/redis/manager_test.go
src/pkg/cached/project_metadata/redis/manager.go
src/pkg/cached/project_metadata/redis/manager_test.go
src/pkg/cached/repository/redis/manager.go
src/pkg/cached/repository/redis/manager_test.go
src/pkg/config/manager.go
src/pkg/reg/adapter/harbor/base/client.go
src/pkg/reg/adapter/tencentcr/adapter.go
src/pkg/systemartifact/manager.go
src/pkg/task/dao/execution.go
src/pkg/task/dao/execution_test.go
src/server/middleware/cosign/cosign.go
src/server/middleware/cosign/cosign_test.go
src/server/registry/route.go

refactored code in order to make it compliant with golangci-lint revive
Fixes #(issue)

fix: update code in compliance with golangci-lint revive

---

make/migrations/postgresql/0090_2.6.0_schema.up.sql

Add index to avoid full table scan
Remove some improper index
fixes #16574 
Fixes #(issue)

Create index for performance

---

src/pkg/task/dao/execution.go

This reverts commit 88b8a7ac2cfe6ce5b54de0de8097af6ebfb102f4.
Fixes #(issue)

Revert "Skip to refresh execution status when unchanged (#17023)"

---

api/v2.0/swagger.yaml

Added group_type information for type 3 OIDC group to the API description
Fixes #()

Added group_type information for type 3 OIDC group

---

src/controller/event/handler/replication/replication.go

Attach labels for replication event, list labels by artifact ID so for
event-based replication rule filter by label can work as expect.
Closes: #17014
Fixes https://github.com/goharbor/harbor/issues/17014

fix: attach labels for replication event

---

src/common/rbac/project/rbac_role.go

**Observed Bug:**
According to according to the ["User Pemission by Role" Table](https://goharbor.io/docs/2.4.0/administration/managing-users/user-permissions-by-role/) the Developer should have the right to "Create/delete tag retention rules" and "Enable/disable tag retention rules". Nevertheless the Developer cannot see the Policy tab in the Harbor Portal, so he cannot work with retention rules.
**Troubleshooting:**
While looking for the source of this difference we found that the Policy tab is shown if the [user has TagRetentionPermission](https://github.com/goharbor/harbor/blob/44f477e965e57ba619d494a7122c69a636906666/src/portal/src/app/base/project/project-detail/project-detail.component.ts#L104). This Information is provided by the backend under "GET …

Added Tag Retention Permission to Developer 

---

src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.ts

1. Hide pull command for Nydus type, corresponding back-end PR #17126
Fixes #(issue)

Hide pull command for Nydus

---

tests/resources/Harbor-Pages/Project_Elements.robot

Because this PR(#17138) update the tag immutability xpath, so update synchronously
Fixes #(issue)

Update tag immutability xpath

---

make/photon/prepare/utils/jobservice.py

See the right uid and gid for the scandata_exports in the prepare
Fixes #(issue)

resolve the cve export volumn permission

---

tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/Project_Elements.robot
tests/resources/Harbor-Pages/ToolKit.robot

Because this PR(#16236) update the delete project button xpath, so update synchronously
Fixes #(issue)

Update delete project test case

---

api/v2.0/swagger.yaml
src/controller/scandataexport/execution.go
src/pkg/scan/export/filter_processor.go
src/pkg/scan/export/filter_processor_test.go
src/portal/src/app/shared/components/operation/operation.component.ts
src/server/v2.0/handler/scanexport.go
src/server/v2.0/handler/scanexport_test.go

Closes:
* https://github.com/goharbor/harbor/issues/17152
* https://github.com/goharbor/harbor/issues/17153
Better error handling in case of task executions not found in the system
Fixes #(issue)

Improvements to Vulnerability Data Export functionality.

---

src/jobservice/job/impl/purge/purge.go

Change the log to logger in purge job

---

src/pkg/scan/export/manager.go

Closes:
* https://github.com/goharbor/harbor/issues/17167
Fixes #(issue)

Fix to CVE Data Export functionality for images pushed by `docker push`

---

src/common/api/base.go

Remove redundant if check due to condition always false
Fixes #17159

fix: remove redundant check due to always false

---

tests/resources/Harbor-Pages/HomePage_Elements.robot
tests/resources/Harbor-Pages/Vulnerability.robot
tests/resources/Harbor-Pages/Vulnerability_Elements.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Routing.robot

Add retry to improve test case stability
Fixes #(issue)

Update routing test case

---

src/pkg/audit/manager.go

Add resource type in forward audit log

---

src/common/const.go
src/jobservice/job/impl/purge/purge.go
src/server/v2.0/handler/purge.go
src/server/v2.0/handler/purge_test.go

Cap the retention hour to 240000 hour
Fixes #17198
Fixes #(issue)

Return bad request if audit log retention hour > 240000 hour

---

src/portal/src/app/shared/components/operation/operation.component.html
src/portal/src/app/shared/components/operation/operation.component.ts

Fixes #17183
1. Fix cve export UI issues found on the testing day
Fixes #(issue)

Fix cve export UI issues

---

src/jobservice/job/impl/scandataexport/scan_data_export.go
src/pkg/scan/export/manager.go
src/pkg/scan/export/manager_test.go
src/pkg/scan/export/model.go
src/server/v2.0/handler/scanexport.go
src/server/v2.0/handler/scanexport_test.go

Closes #17199
Closes #17193
Closes #17188
Closes #17184
Closes #17187
Closes:
* CVE Data Export API IDOR issue
* https://github.com/goharbor/harbor/issues/17199
* https://github.com/goharbor/harbor/issues/17193
* https://github.com/goharbor/harbor/issues/17188
* https://github.com/goharbor/harbor/issues/17184
Fixes #(issue)

Fixes for various bugs/issues logged as a part of the test day.

---

src/controller/retention/controller.go
src/pkg/retention/models.go
src/server/v2.0/handler/retention.go

Fix the update of retention policy

---

src/server/v2.0/handler/immutable.go

Add check when updating immutable tag

---

src/pkg/p2p/preheat/dao/instance/dao.go
src/pkg/p2p/preheat/dao/instance/dao_test.go
src/server/v2.0/handler/notification_job.go
src/server/v2.0/handler/notification_policy.go
src/server/v2.0/handler/preheat.go

1. Update the preheat policy API hander and DAO Get method.
2. Update the webhook policy and webhook job API handler.
Fixes #(issue)

fix: update process of webhook and preheat policy

---

src/server/v2.0/handler/robot.go

Only check the project id for the project level robot
Fixes #([17249](https://github.com/goharbor/harbor/issues/17249))

fix update robot regression

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bumpup golang version to v1.18.4

---

src/server/v2.0/handler/robot.go

Only check the project id for the project level robot
Fixes #(issue)

[cherry-pick] fix update robot regression

---

src/server/v2.0/handler/robot.go

[cherry-pick] fix robot update issue

---

api/v2.0/swagger.yaml
src/common/rbac/const.go
src/common/rbac/project/rbac_role.go
src/controller/scandataexport/execution.go
src/controller/scandataexport/execution_test.go
src/pkg/scan/export/constants.go
src/pkg/scan/export/model.go
src/server/v2.0/handler/scanexport.go
src/server/v2.0/handler/scanexport_test.go

1. Add resource permission check for API handler
2. Validate export cve params project
3. Optimize friendly human message when execution status is error
Fixes
- https://github.com/goharbor/harbor/issues/17203
- https://github.com/goharbor/harbor/issues/17196

fix: export cve adds resource check and project validation

---

src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.html
src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.scss
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.scss
src/portal/src/app/base/left-side-nav/user/user.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-summary.component.html
src/portal/src/app/base/project/repository/repository-gridview.component.scss
src/portal/src/app/route-reuse-strategy/harbor-route-reuse-strategy.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json
tests/resources/Harbor-Pages/Project-Artifact-Elements.robot

Fixes #17229
Fixes #17222
1. Fix router issues for UI
Fixes #(issue)

Fix router issues for UI

---

src/portal/src/app/base/left-side-nav/projects/list-project/export-cve/export-cve.component.html
src/portal/src/app/base/left-side-nav/projects/list-project/export-cve/export-cve.component.scss
src/portal/src/app/base/left-side-nav/projects/list-project/export-cve/export-cve.component.ts
src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.html
src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.ts
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
src/portal/src/app/services/intercept-http.service.ts
src/portal/src/app/shared/components/operation/operation.component.ts
src/portal/src/app/shared/services/label.service.ts
src/portal/src/app/shared/services/permission-static.ts
src/portal/src/css/common.scss
src/portal/src/css/dark-theme.scss
src/portal/src/css/light-theme.scss
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Fixes #17185
1. disable exporting all projects and can only export one project at one time
2. Add permission check
3. can only click the export button once in an interval of 30s
Fixes #(issue)

Add permission check to CVE export

---

src/common/rbac/project/visitor_role.go
src/core/api/chart_label.go
src/core/api/notification_job.go
src/core/api/retention.go

Add chart label check and retention policy check in 1.10

---

src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.html
src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.ts
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts

Fixes #17273
Fixes #17272
1. Fix null pointer issue for creating replication rule
2. Remove loading for export CVE button
Fixes #(issue)

Fix null pointer issue for creating reolication rule

---

src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.html
src/portal/src/app/base/left-side-nav/projects/list-project/list-project.component.ts
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts

Cherry-pick #17274
Fixes #(issue)

[Cherry-pick]Fix null pointer issue for creating reolication rule

---

src/go.mod
src/go.sum
src/vendor/github.com/beego/beego/session/session.go
src/vendor/github.com/beego/beego/tree.go
src/vendor/github.com/gocarina/gocsv/go.mod
src/vendor/modules.txt

upgrade: bump up beego to 1.12.11

---

src/.golangci.yaml

Enable staticcheck

---

src/portal/package-lock.json
src/portal/package.json

1. Upgrade the Angular dev-tool package to 13.3.9
Fixes #(issue)

Upgrade Angular dev-tool package

---

src/common/utils/utils.go

change log level to debug to avoid noise
Fixes #(issue)

(cherry-pick) Return time.Time{} when cron string is empty

---

src/controller/artifact/processor/image/manifest_v2.go

https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
https://github.com/goharbor/harbor/issues/17190

update image extra attributes author in labels

---

src/core/session/session.go

To avoid too much noise in the core log, udpate the level to debug.
Fixes #(issue)

update session log level

---

src/core/session/session.go

To avoid too much noise in the core log, udpate the level to debug.
Fixes #(issue)

[cherry-pick] update session log level

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bumpup golang to v1.18.5

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bumpup golang to v1.18.5 on release-2.6.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bumpup golang to v1.17.13

---

src/controller/artifact/controller.go
src/server/middleware/quota/copy_artifact.go

It needs to request quota for accessory on copying artifact.
Fixes #(17207)

fix copy artifact accessory quota issue

---

src/go.mod
src/go.sum
src/vendor/github.com/docker/distribution/.mailmap
src/vendor/github.com/docker/distribution/Dockerfile
src/vendor/github.com/docker/distribution/README.md
src/vendor/github.com/docker/distribution/docker-bake.hcl
src/vendor/github.com/docker/distribution/version/version.go
src/vendor/modules.txt

bump up distribution to v2.8.1+incompatible

---

make/harbor.yml.tmpl

Add helpful description for cache layer configurations in harbor.yml.tmpl
Fixes #(issue)

docs: add helpful description for cache layer configurations

---

make/harbor.yml.tmpl

Add helpful description for cache layer configurations in harbor.yml.tmpl.
Fixes #(issue)

[cherry-pick] docs: add helpful description for cache layer configurations

---

src/jobservice/job/impl/scandataexport/scan_data_export_test.go
src/pkg/scan/export/export_data_selector.go
src/pkg/scan/export/export_data_selector_test.go
src/pkg/scan/export/manager.go
src/pkg/scan/export/manager_test.go
src/pkg/scan/export/model.go

Closes: https://github.com/goharbor/harbor/issues/17189
Fixes #(issue)

[cherry-pick] Export CVE data Score column empty values (#17321)

---

make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja

_version:2.6.0 correction in migration yml jinja

---

make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja

[cherry-pick]_version:2.6.0 correction in migration yml jinja

---

api/v2.0/swagger.yaml
src/jobservice/job/impl/scandataexport/scan_data_export.go
src/jobservice/job/impl/scandataexport/scan_data_export_test.go
src/pkg/scan/export/export_data_selector_test.go
src/pkg/scan/export/filter_processor.go
src/pkg/scan/export/manager.go
src/pkg/scan/export/model.go

1. Fix export cve for image manifest list
2. Remove row_id column in csv file
3. Update cve execution swagger API description
Closes: #17331,#17330,#17335,#17334
Fixes #17331,#17330,#17335,#17334

[cherry-pick] fix: export cve for image manifest list

---

api/v2.0/swagger.yaml
src/jobservice/job/impl/scandataexport/scan_data_export.go
src/jobservice/job/impl/scandataexport/scan_data_export_test.go
src/pkg/scan/export/export_data_selector_test.go
src/pkg/scan/export/filter_processor.go
src/pkg/scan/export/manager.go
src/pkg/scan/export/model.go

1. Fix export cve for image manifest list
2. Remove row_id column in csv file
3. Update cve execution swagger API description
Closes: #17331,#17330,#17334,#17335
Fixes
- #17330 
- #17331
- #17334
- #17335

fix: export cve for image manifest list

---

src/jobservice/job/impl/scandataexport/scan_data_export.go
src/jobservice/job/impl/scandataexport/scan_data_export_test.go
src/server/v2.0/handler/scanexport.go
src/server/v2.0/handler/scanexport_test.go

1. Validate export cve request params in the API handler
2. Trim space for request in the scan export job
Closes: #17326
Fixes #17326

fix: validate export cve request params

---

src/controller/project/controller.go

https://github.com/goharbor/harbor/issues/16693

project userid not found log level into debug

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/shared/components/image-name-input/image-name-input.component.html
src/portal/src/app/shared/components/image-name-input/image-name-input.component.ts
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json

Fixes #17302
1. Improve input validator for copy-component
Fixes #(issue)

Improve input validator for copy-component

---

src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/history/purge-history.component.ts
src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.html
src/portal/src/app/base/left-side-nav/clearing-job/audit-log-purge/set-job/set-job.component.scss
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.html
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc.component.scss
src/portal/src/app/base/project/project-detail/project-detail.component.html
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Cherry-pick #17357
Fixes #(issue)

[Cherry-pick]Fix ui issues found in testing-day-round-2

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.spec.ts

Cherry-pick #17372
Fixes #(issue)

[Cherry-pick]Improve unit test for sub-accessories component

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.spec.ts

1. Improve unit test for sub-accessories component
Fixes #(issue)

Improve unit test for sub-accessories component

---

tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/Replication_Elements.robot
tests/resources/Harbor-Pages/Vulnerability.robot
tests/robot-cases/Group1-Nightly/Trivy.robot

1 Update replication filter_label_xpath because of this PR https://github.com/goharbor/harbor/pull/17267 updated xpath
2 Update the Manual Scan All test case, because Scan All will affect other testcases if it is not finished running
Signed-off-by: Yang Jiao [jiaoya@vmware.com](mailto:jiaoya@vmware.com)
Fixes #(issue)

[cherry-pick]Update replication and trivy testcases

---

tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/Replication_Elements.robot
tests/resources/Harbor-Pages/Vulnerability.robot
tests/robot-cases/Group1-Nightly/Trivy.robot

1 Update replication filter_label_xpath because of this PR #17267 updated xpath
2 Update the Manual Scan All test case, because Scan All will affect other testcases if it is not finished running
Fixes #(issue)

Update replication and trivy testcases

---

src/pkg/task/execution.go
src/pkg/task/task.go

enhancement: add error log for create task

---

src/pkg/task/execution.go
src/pkg/task/task.go

[cherry-pick] enhancement: add error log for create task

---

make/common.sh
make/install.sh

[cherry-pick]support docker compose v2

---

make/install.sh

adjust msg
adjust typo
adjust
Fixes #(issue)

[cherry-pick]add deprecation msg for chartmsuem and notary

---

Makefile

adjust golangci-lint installation hint

---

tools/systemd/harbor.service

Dependencies
1, You must have docker with compose plugin installed.
2, You must have the directory /etc/goharbor/harbor in your env.
Tested
1, ubuntu 20.04
Fixes #(issue)

add an example of harbor systemd service

---

src/server/v2.0/handler/scanexport.go
src/server/v2.0/handler/scanexport_test.go

Validate the existence of the project for export CVE API handler, return
not found error if the project is not exist.
Closes: #17430
Fixes #17430 

fix: validate the existence of project for export cve api

---

src/server/v2.0/handler/scanexport.go
src/server/v2.0/handler/scanexport_test.go

Validate the existence of the project for export CVE API handler, return
not found error if the project is not exist.
Closes: #17430
Fixes #17430

[cherry-pick] fix: validate the existence of project for export cve api

---

src/portal/src/app/base/project/repository/artifact/artifact.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1.  Add WASM filter for artifacts list
Fixes #(issue)

Add WASM filter for artifacts list

---

src/portal/src/app/base/project/repository/artifact/artifact.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Cherry-pick #17447
Fixes #(issue)

[Chrry-pick]Add WASM filter for artifacts list

---

src/portal/app-swagger-ui/README.md
src/portal/app-swagger-ui/index.html

1. Change title for Swagger UI to resolve e2e failure
Fixes #(issue)

Change title for Swagger UI

---

tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/Replication_Elements.robot

Fix 2.5 CI failed
Fixes #(issue)

Update replication filter_label xpath

---

tests/resources/Harbor-Pages/Log_Rotation.robot
tests/resources/Harbor-Pages/Log_Rotation_Elements.robot
tests/resources/Harbor-Pages/Logs.robot
tests/resources/Harbor-Pages/Logs_Elements.robot
tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/Project_Elements.robot
tests/resources/Harbor-Pages/ToolKit.robot
tests/resources/Harbor-Pages/UserProfile.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common.robot
tests/robot-cases/Group1-Nightly/Schedule.robot

1. Add audit log test case
2. Add log rotation test case
3. Add log rotation schedule test case
Fixes #17467

Add audit log and log rotation test cases

---

make/photon/prepare/migrations/version_2_5_0/__init__.py
make/photon/prepare/migrations/version_2_6_0/__init__.py

Add autoescape parameter for 2.5 & 2.6 jinja

---

src/portal/scripts/generate-build-timestamp.js
src/portal/src/index.html

Fixes  task  1  in #17462
Remove preload for theme css files
Fixes #(issue)

Remove preload for theme css files

---

.buildbaselog
tests/resources/Harbor-Pages/Log_Rotation.robot
tests/resources/Harbor-Pages/Log_Rotation_Elements.robot
tests/resources/Harbor-Pages/Logs.robot
tests/resources/Harbor-Pages/Logs_Elements.robot
tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/Project_Elements.robot
tests/resources/Harbor-Pages/ToolKit.robot
tests/resources/Harbor-Pages/UserProfile.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common.robot
tests/robot-cases/Group1-Nightly/Schedule.robot

1. Add audit log test case
2. Add log rotation test case
3. Add log rotation schedule test case
Fixes #17467

[cherry-pick]Add audit log and log rotation test cases

---

tests/apitests/python/library/base.py
tests/apitests/python/library/cnab.py
tests/apitests/python/library/containerd.py
tests/apitests/python/library/docker_api.py
tests/apitests/python/library/registry.py
tests/apitests/python/library/repository.py
tests/apitests/python/test_project_quota.py
tests/apitests/python/test_push_image_with_special_name.py
tests/resources/APITest-Util.robot
tests/resources/Docker-Util.robot
tests/resources/Harbor-Pages/Replication.robot
tests/resources/Nightly-Util.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Replication.robot

Remove logs that do not need to be printed
Fixes #(issue)

Remove the log in testcase

---

src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.html

1. Fix css issue for resource type filter of replication tasks component
Fixes #(issue)

Fix css issue for resource type filter

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/copy-artifact/copy-artifact.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/copy-artifact/copy-artifact.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/copy-artifact/copy-artifact.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/copy-digest/copy-digest.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/copy-digest/copy-digest.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/copy-digest/copy-digest.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.module.ts

1. Break down the artifact-list-tab component into smaller components
Fixes #(issue)

Refactor artifact-list-tab component

---

src/replication/adapter/huawei/huawei_adapter_test.go
src/replication/adapter/huawei/image_registry_test.go

fix: ignore huawei adapter ut error

---

src/pkg/ldap/ldap.go

Change ldap.Search to ldap.SearchWithPaging

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list-page.service.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.scss
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-filter/artifact-filter.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.module.ts
src/portal/src/app/base/project/repository/artifact/artifact.ts
src/portal/src/app/shared/components/label-selector/label-selector.component.html
src/portal/src/app/shared/components/label-selector/label-selector.component.scss
src/portal/src/app/shared/components/label-selector/label-selector.component.spec.ts
src/portal/src/app/shared/components/label-selector/label-selector.component.ts
src/portal/src/app/shared/components/label/label-piece/label-piece.component.html
src/portal/src/app/shared/components/label/label-piece/label-piece.component.scss
src/portal/src/app/shared/shared.module.ts
src/portal/src/css/common.scss

1. Break down `adding labels` and `filtering artifacts` into independent components
Fixes #(issue)

Refactor artifact-list component

---

src/controller/config/controller.go
src/controller/config/controller_test.go

Add check on the audit log forward and skip audit log database

---

src/controller/config/controller.go
src/controller/config/controller_test.go

(cherry-pick) Add check on the audit log forward and skip audit log database

---

tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/Replication.robot

Because this PR #17577 modifies the filter label
Fixes #(issue)

Update filter label xpath

---

src/portal/.eslintrc.json
src/portal/README.md
src/portal/angular.json
src/portal/server/README.md
src/portal/server/controllers/scanners.ts
src/portal/server/src/mock-api.ts

1. Simplify proxy config to reduce the number of proxy server
Fixes #(issue)

Simplify proxy config

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bumpup golang to v1.18.6 on release-2.6.0

---

Makefile

add govulncheck tools

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
src/go.mod
tests/ci/distro_installer.sh

Bump up golang version to v1.19

---

tests/apitests/python/library/audit_log.py
tests/apitests/python/library/base.py
tests/apitests/python/library/configurations.py
tests/apitests/python/test_audit_log_forward.py
tests/apitests/python/testutils.py
tests/ci/api_run.sh
tests/robot-cases/Group0-BAT/API_DB.robot

Add audit log forword API test case

---

tests/apitests/python/library/audit_log.py
tests/apitests/python/library/base.py
tests/apitests/python/library/configurations.py
tests/apitests/python/test_audit_log_forward.py
tests/apitests/python/testutils.py
tests/ci/api_run.sh
tests/robot-cases/Group0-BAT/API_DB.robot

[cherry-pick]Add audit log forword API test case

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Configuration_Elements.robot
tests/resources/Harbor-Pages/Logs.robot
tests/resources/SeleniumUtil.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common.robot

Verify that the audit log forward function is correct.
Fixes #17559

Add audit log forward UI testcase

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Configuration_Elements.robot
tests/resources/Harbor-Pages/Logs.robot
tests/resources/SeleniumUtil.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common.robot

Verify that the audit log forward function is correct.
Fixes

[cherry-pick]Add audit log forward UI testcase

---

tests/apitests/python/library/base.py
tests/apitests/python/library/cnab.py
tests/apitests/python/library/containerd.py
tests/apitests/python/library/docker_api.py
tests/apitests/python/library/registry.py
tests/apitests/python/library/repository.py
tests/apitests/python/test_project_quota.py
tests/apitests/python/test_push_image_with_special_name.py
tests/resources/APITest-Util.robot
tests/resources/Docker-Util.robot
tests/resources/Harbor-Pages/Replication.robot
tests/resources/Nightly-Util.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Replication.robot

Remove logs that do not need to be printed
Fixes #(issue)

[cherry-pick]Remove the log in testcase

---

src/portal/src/app/base/left-side-nav/config/config.component.spec.ts
src/portal/src/app/base/left-side-nav/config/config.component.ts
src/portal/src/app/base/left-side-nav/config/config.service.spec.ts
src/portal/src/app/base/left-side-nav/config/config.service.ts

Fixes #17539
1. Refresh config every time entering the configuration page
Fixes #(issue)

Refresh config every time entering the configuration page

---

src/portal/src/app/shared/router-guard/auth-user-activate.service.ts

Fixes #17594
1. Improve auth check guard service. Now, un-authed navigating will be redirected to the sign-in page, and the query param `redirect_url `  will be rightly set
Fixes #(issue)

Improve auth check guard service

---

src/portal/.eslintrc.json
src/portal/server/src/mock-api.ts
src/portal/src/app/base/left-side-nav/config/config.service.ts
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.spec.ts
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts
src/portal/src/app/base/project/repository/artifact/vulnerability-scanning/result-bar-chart.component.ts

1. Fix the message processing issue to resolve the e2e failure
2. Disable console.info() and console.log() 
Fixes #(issue)

Fix message processing issue

---

tests/apitests/python/library/base.py
tests/apitests/python/library/scan_data_export.py
tests/apitests/python/test_scan_data_export.py
tests/robot-cases/Group0-BAT/API_DB.robot

1. Add export scan data API test case
2. Add get scan data export execution list test case
3. Add get scan data export execution test case
4. Add download scan data test case
Fixes #(issue)

[cherry-pick]Add scan data export API test case

---

src/pkg/reg/adapter/awsecr/adapter.go
src/pkg/reg/adapter/awsecr/adapter_test.go
src/pkg/reg/adapter/awsecr/auth.go

Signed-off-by: Vincent Ni <kangqini@amazon.com>
The original fix (https://github.com/goharbor/harbor/pull/17533) sometimes results in unmarshalling issue of the request response. The proposed changes here allow Harbor to fetch the token for the right account and thus solves the cross account authentication issue.
Fixes [#(issue)](https://github.com/goharbor/harbor/issues/15388)

Fix cross account issue

---

tests/apitests/python/library/base.py
tests/apitests/python/library/scan_data_export.py
tests/apitests/python/test_scan_data_export.py
tests/robot-cases/Group0-BAT/API_DB.robot

1. Add export scan data API test case
2. Add get scan data export execution list test case
3. Add get scan data export execution test case
4. Add download scan data test case
Fixes #17560

Add scan data export API test case

---

src/pkg/reg/adapter/awsecr/auth.go

Signed-off-by: Vincent Ni <kangqini@amazon.com>
Fixes https://github.com/goharbor/harbor/issues/17642
GetAuthorizationTokenInput returns error in case of empty registry ids.

Fix ecr authorization token issue

---

src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html

Fixes #17652
1. Remove the validator for username claim input to make it consistent with  groupname claim
Fixes #(issue)

Remove validator for username claim input

---

src/chartserver/cache.go
src/chartserver/redis_sentinel.go

beego v2 cache refactor

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump up golang to 1.18.7

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump up golang to 1.19.2

---

src/core/main.go

Add completion message for database migrated when harbor core start up.
Fixes https://github.com/goharbor/harbor/issues/17647

feat: log completion message when database migrated

---

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.spec.ts
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Fixes #17550
1. Add copy_by-chunk checkbox for replication rule. Related back-end PR #17602
2.  Changed points:
Fixes #(issue)

Add copy_by-chunk checkbox for replication rule

---

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.spec.ts
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Cherry-pick #17617
Fixes #(issue)

[Cherry-pick]Add copy_by-chunk checkbox for replication rule

---

README.md

Add FOSSA badge and licence analysis

---

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts

1. It's a patch PR for #17617
Fixes #(issue)

Add triggers and filters check for target changing under push mode

---

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts

Cherry-pick #17731
Fixes #(issue)

[Cherry-pick]Add triggers and filters check for target changing under push mode

---

make/migrations/postgresql/0091_2.6.2_schema.up.sql

fix: cherry pick 262 sql for migrations

---

src/server/v2.0/handler/user.go
src/server/v2.0/handler/user_test.go

add cli randomly for empty update

---

.github/ISSUE_TEMPLATE/issue.md

Fix wording in harbor issue template

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump up golang to 1.18.8

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump up golang to 1.19.3

---

src/pkg/registry/client.go

Support override the registry http client timeout from env `REGISTRY_HTTP_CLIENT_TIMEOUT` (in minutes), the timeout is 30 minutes by default.
Fixes #(issue)

feat: support customize registry http client timeout

---

src/portal/src/app/base/left-side-nav/config/auth/config-auth.component.html
src/portal/src/app/base/left-side-nav/config/config.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1. Add OIDC group filter input related back-end PR #17736
Changes:
Fixes #(issue)

Add OIDC group filter input

---

src/server/v2.0/handler/base.go

Fix permission denied error for non existing projects
Fixes #17586 
- [ x] Well Written Title and Summary of the PR
- [ x] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ x] Accepted the DCO. Commits without the DCO will delay acceptance.
- [x ] Made sure tests are passing and test coverage is added if needed.
- [x ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

fix permission denied error for non existing projects (#17586)

---

.github/dependabot.yml

revise the go mod path for dependency bot and remove the monitoring on tests.
Fixes #(issue)

revise the gomod path

---

src/controller/event/handler/webhook/artifact/artifact.go

Check the notification enable before in the artifact webhook handler, avoid additional db query cost for notification_policy.
Fixes https://github.com/goharbor/harbor/issues/16930

fix: pre check notification enable for artifact webhook

---

tests/apitests/python/library/base.py
tests/apitests/python/library/statistic.py
tests/apitests/python/library/system_info.py
tests/apitests/python/test_verify_metrics_enabled.py

Add more metrics validation
Fixes #(issue)

Add metrics test case

---

src/portal/src/app/base/left-side-nav/config/config.ts
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1.  Add session timeout input.   Related back-end PR #17767
Changed:
Fixes #(issue)

Add session timeout input

---

src/portal/src/app/shared/components/operation/operation.component.ts

1. Update cve export UI to always display `status_text` 
Fixes #(issue)

Update cve export UI

---

tests/apitests/python/test_audit_log_forward.py
tests/apitests/python/testutils.py
tests/ci/api_run.sh
tests/resources/APITest-Util.robot
tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Logs.robot
tests/resources/SeleniumUtil.robot
tests/resources/Util.robot
tests/robot-cases/Group0-BAT/API_DB.robot
tests/robot-cases/Group1-Nightly/Common.robot

Modify the audit log forward test case to forward the audit log to elk
Fixes #(issue)

Modify audit log forward test case

---

src/controller/proxy/controller.go
src/controller/proxy/manifestcache.go

(cherry-pick) Fix issue related to redhat registry proxy cache

---

api/v2.0/swagger.yaml
src/server/v2.0/handler/jobservice.go

Remove create time because update time is added
Fixes #(issue)

Add Cron, CronType and Update Time for schedule

---

src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard.interface.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.ts
src/portal/src/app/shared/components/cron-schedule/cron-schedule.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1.Add Cron and Cron Type columns, related back-end PR #17844
Fixes #(issue)

Update schedule list

---

src/portal/package-lock.json
src/portal/src/app/base/left-side-nav/log/recent-log.component.spec.ts
src/portal/src/app/base/project/project-log/audit-log.component.spec.ts

1. Update test cases for AuditLogComponent and RecentLogComponent
Fixes #(issue)

Update UI-UT cases

---

src/.golangci.yaml

issue related: https://github.com/golangci/golangci-lint-action/issues/297
Fixes #(issue)

Increase golangci-lint timeout value

---

src/server/v2.0/handler/jobservice.go

Keep CheckInAt time empty when it is empty

---

src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.scss
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Fixes #17868 
Fixes #17853
1. Update i18n for group filter
2. Remove Cron Type and Extra Attribute columns for schedule list
3. Remove Job parameter
Fixes #(issue)

Update i18n for group filter and schedule list

---

src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-shared-data.service.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-shared-data.service.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard.interface.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard.module.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.scss
src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-list/pending-job-list.component.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.scss
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-card/worker-card.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-card/worker-card.component.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-card/worker-card.component.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.ts
src/portal/src/app/services/event-service/event.service.ts

1. Fixes #17855, 
2. Fixes #17874 
3. Fixes #17863
Fixes #(issue)

Update jobservice dashboard UI

---

src/controller/jobmonitor/monitor.go
src/pkg/task/dao/task.go
src/pkg/task/dao/task_test.go
src/pkg/task/mock_task_dao_test.go
src/pkg/task/mock_task_manager_test.go
src/pkg/task/task.go
src/testing/pkg/task/manager.go

Update the execution status after tasks stopped

---

src/portal/src/app/base/harbor-shell/harbor-shell.component.html
src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.scss
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts

1. Fixes #17890
2. Update the isDBAuth function for harbor-shell component
Fixes #(issue)

Change inputs type from text to number

---

src/core/main.go

fixes #17887
enhance the timeout to 5m to avoid system artifact failed to schedule in the helm base installation.
Fixes #(issue)

update system artifact schedult timeout

---

src/common/const.go
src/controller/config/controller.go
src/controller/config/controller_test.go

This is the backend change to align with fronend commit: https://github.com/goharbor/harbor/commit/5f1dff32c27555c620e6e5ec25ef49e2ae0bd9d7
Fixes #(issue)

fix: align some configuration api fields validation with frontend

---

.github/auto-assignees.yml

Bump the auto assignees to 3

---

src/controller/robot/controller.go

We don't need to create regexp variables in the `IsValidSec` every time
Fixes #(issue)

controller/robot: use global regexp vars

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump up golang 1.17.13 for release-2.4.0

---

src/pkg/retention/job.go

fix the setting of data slice length for tablewriter

---

src/jobservice/job/impl/gc/garbage_collection.go

fixes #17857
It needs to clean the artifact_blob records on artifact deletion
Fixes #(issue)

remove artifact_blob with aritfact deletion

---

src/pkg/scheduler/scheduler.go
src/pkg/task/execution.go

Avoid internal error in the UI when reset a schedule

---

src/server/middleware/repoproxy/proxy.go

(cherry-pick) Update the log information in proxy cache

---

.buildbaselog

Refresh the base images

---

src/portal/src/app/base/left-side-nav/job-service-dashboard/job-service-dashboard-shared-data.service.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/pending-job-card/pending-job-card.component.scss
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-card/schedule-card.component.scss
src/portal/src/app/base/left-side-nav/replication/replication/replication.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Cherry-pick #17964
Fixes #(issue)

[Cherry-pick]Fix some UI issues

---

.buildbaselog

Refresh the base images to fix CVEs.
Fixes #(issue)

Refresh base images on release-2.5.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

Bump up golang 1.19.4 for release 2.7.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump up golang to 1.19.4 for main

---

make/harbor.yml.tmpl

Signed-off-by: asta1992 [andreas.stalder92@bluemail.ch](mailto:andreas.stalder92@bluemail.ch)
Fixes #(issue)

Fix: Small typos in harbor.yml.tmpl

---

src/portal/src/app/base/project/member/add-group/add-group.component.ts
src/portal/src/app/base/project/member/add-member/add-member.component.spec.ts
src/portal/src/app/base/project/member/add-member/add-member.component.ts

Switch listUsers to searchUsers for adding project member

---

.buildbaselog

Refresh the base image on release-2.6.0

---

.buildbaselog

Refresh the base image on release-2.5.0

---

src/go.mod
src/go.sum
src/vendor/helm.sh/helm/v3/pkg/chartutil/create.go
src/vendor/helm.sh/helm/v3/pkg/chartutil/jsonschema.go
src/vendor/helm.sh/helm/v3/pkg/repo/index.go
src/vendor/helm.sh/helm/v3/pkg/repo/repo.go
src/vendor/modules.txt

bump up helm/v3/pkg to v3.10.3 on release-2.6.0

---

src/go.mod
src/go.sum
src/vendor/helm.sh/helm/v3/pkg/chartutil/create.go
src/vendor/helm.sh/helm/v3/pkg/chartutil/jsonschema.go
src/vendor/helm.sh/helm/v3/pkg/repo/index.go
src/vendor/helm.sh/helm/v3/pkg/repo/repo.go
src/vendor/modules.txt

bump up helm/v3/pkg to v3.10.3 on main

---

.github/workflows/nightly-trivy-scan.yml

add 2.7.0 tag to nightly trivy scan

---

.github/workflows/nightly-trivy-scan.yml

update trivy scan ci image tag to v2.7.0-dev

---

src/jobservice/job/status_test.go

add job status unit test

---

ADOPTERS.md
CONTRIBUTING.md
README.md
RELEASES.md
ROADMAP.md
SECURITY.md

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
Fixes #(issue)

docs(readme): fix syntax errors in the document

---

.github/workflows/CI.yml

1.Specify Chrome version for UI UT
Fixes #(issue)

[2.7]Update CI for UI UT

---

.github/workflows/CI.yml
tests/ci/ut_install.sh

Cherry-pick https://github.com/goharbor/harbor/pull/18166
Fixes #(issue)

[Cherry-pick]Update CI for UI UT

---

src/server/v2.0/handler/immutable.go
src/server/v2.0/handler/project.go

fix retention/immutable API issue

---

src/server/v2.0/handler/immutable.go
src/server/v2.0/handler/project.go

[Cherry-pick] fix retention/immutable API issue (#18158)

---

src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.ts

Cherry-pick #18148
Fixes #(issue)

[Cherry-pick]Correct total count for schedule list datagrid

---

src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.spec.ts
src/portal/src/app/base/left-side-nav/job-service-dashboard/schedule-list/schedule-list.component.ts

1. Fixes #18120
2. Add a ut case to cover it
Fixes #(issue)

Correct total count for schedule list datagrid

---

src/server/v2.0/handler/user.go
src/server/v2.0/handler/user_test.go

fix: reset user password

---

src/portal/src/i18n/lang/zh-cn-lang.json

Related PR #17627
1.Translate the English text into Chinese for primary auth mode tooltip
Fixes #(issue)

Translate English to Chinese for primary auth mode tooltip

---

src/server/v2.0/handler/user.go
src/server/v2.0/handler/user_test.go

[Cherry-pick] fix: reset user password

---

src/portal/src/app/shared/components/operation/operation.component.css
src/portal/src/app/shared/components/operation/operation.component.html

Cherry-pick #18226
Fixes #(issue)

[Cherry-pick]Display error message by defaul for event panel

---

src/portal/src/app/shared/components/operation/operation.component.css
src/portal/src/app/shared/components/operation/operation.component.html

1. Now, the error message will be displayed by default
Fixes #(issue)

Display error message by defaul for event panel

---

.buildbaselog

Refresh base images on release-2.6.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
.github/workflows/publish_release.yml

Remove the remove setup docker step in CI
Fix #18236
Fixes #(issue)

Fix Setup Docker error in CI

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
.github/workflows/publish_release.yml

Remove the remove setup docker step in CI
Fix #18236
Fixes #(issue)

[cherry-pick]Fix Setup Docker error in CI

---

tests/apitests/python/library/base.py
tests/apitests/python/library/gc.py
tests/apitests/python/library/jobservice.py
tests/apitests/python/library/preheat.py
tests/apitests/python/library/purge.py
tests/apitests/python/library/retention.py
tests/apitests/python/library/scan_all.py
tests/apitests/python/library/schedule.py
tests/apitests/python/test_job_service_dashboard.py
tests/robot-cases/Group0-BAT/API_DB.robot

Added test cases for the following APIs:
1. GET /jobservice/pools/{pool_id}/workers Get workers
2. PUT /jobservice/jobs/{job_id} Stop running jc
3. PUT /jobservice/queues/{job_type} stop and clean, pause, resume pending jobs in the queue
4. GET /jobservice/queues list job queues
5. GET /jobservice/pools Get worker pools
6. GET /schedules List schedules
7. GET /schedules/{job_type}/paused Get scheduler paused status
Fixes #(issue)

[Cherry-pick]Add JobService Dashboard API test cases

---

src/pkg/retention/manager.go
src/pkg/retention/policy/models.go

fix: add "next_scheduled_time"

---

.buildbaselog

Refresh the base images on release-2.6.0

---

.buildbaselog

Refresh the base images on release-2.7.0

---

api/v2.0/swagger.yaml
make/photon/prepare/templates/core/env.jinja
make/photon/prepare/utils/core.py
src/common/const.go
src/controller/event/handler/internal/artifact.go
src/controller/event/handler/internal/artifact_test.go
src/controller/scan/base_controller.go
src/controller/scan/base_controller_test.go
src/lib/config/metadata/metadatalist.go
src/lib/config/systemconfig.go
src/lib/config/userconfig.go

Skip to update pull time and pull count for scanner robot account

---

src/pkg/factory.go
src/pkg/registry/client.go

Remove noise logs when core started.
Fixes: #18126
Fixes #(issue)

fix: remove noise log when core started

---

src/portal/src/app/shared/components/operation/operation.component.ts

1.Fixes #17879
2.Add retry times to avoid endless API calls for CVE data export execution list API
Fixes #(issue)

Add retry times for calling CVE data export execution list API

---

src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.html
src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.scss
src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.ts
src/portal/src/app/base/left-side-nav/registries/endpoint.component.html
src/portal/src/app/base/left-side-nav/registries/endpoint.component.ts
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
src/portal/src/app/shared/services/endpoint.service.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1. Update edit-registry page to enable the edition for Artifact Hub
2. Update edit-replication-rule page to enable the edition for rules contain Artifact Hub
Fixes #(issue)

Update UI for the deprecation of Artifact Hub

---

src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.html
src/portal/src/app/base/left-side-nav/job-service-dashboard/worker-list/worker-list.component.ts

1. Related back-end PR #18261
2. This PR should be merged after #18261
Changes:
Fixes #(issue)

Add logs column for worker datagrid

---

src/controller/robot/controller.go

Update robot account to skip NotFoundErr

---

src/server/middleware/security/oidc_cli.go

Skip robot account for oidc_cli middleware

---

src/controller/tag/controller.go
src/controller/tag/controller_test.go

Verify tag name with OCI spec when creating tag
Fixes #18073 (issue)

Check tag name for OCI spec

---

make/migrations/postgresql/0110_2.8.0_schema.up.sql

Update robot account and notification policy as Harbor v2.8.0 deprecates chartmuseum. 
Harbor deprecates chartmuseum as of v2.8.0
Epic: goharbor#17958
Discussion: goharbor#15057
Fixes #(issue)

Migrate robot account and notification policy related to Chartmuseum

---

src/core/controllers/oidc.go
src/pkg/oidc/helper.go
src/pkg/oidc/helper_test.go

Config is cached in redis with 1 minute interval
Fixes #18189 

Remove go routine to reloadSetting

---

src/portal/src/app/base/project/webhook/add-webhook-form/add-webhook-form.component.ts
src/portal/src/app/base/project/webhook/excutions/executions.component.html
src/portal/src/app/base/project/webhook/excutions/executions.component.ts
src/portal/src/app/base/project/webhook/webhook.service.ts

1. Add text format for payload data
2. Delete payload_format for Slack
Fixes #(issue)

Improve webhook UI

---

src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.scss
src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/shared/units/utils.spec.ts
src/portal/src/app/shared/units/utils.ts

1. Fixes #17815
2. Add dynamic column support for the replication rule list  and artifact list
Changes:
Fixes #(issue)

Add dynamic column support

---

src/pkg/reg/adapter/aliacr/adapter.go
src/pkg/reg/adapter/aliacr/adapter_test.go
src/pkg/reg/adapter/aliacr/types.go
src/portal/src/app/base/left-side-nav/registries/create-edit-endpoint/create-edit-endpoint.component.spec.ts
src/portal/src/app/base/left-side-nav/registries/endpoint.component.spec.ts

Signed-off-by: Back Yu <yhfszb@gmail.com>
Fixes #17488 
Add support for vpc and internal endpoint for aliacr.

Support vpc and internal network (goharbor#17488)

---

make/migrations/postgresql/0110_2.8.0_schema.up.sql

Migrate the old webhook job to executions and tasks.
Fixes #(issue)

migration: add sql to migrate the old webhook job to new way

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.ts
src/portal/src/app/services/event-service/event.service.ts

1. Update accessory UI to support recursion(An accessory can have accessories)
Changes:
Fixes #(issue)

Support accessory recursion for artifact list

---

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts

1. Fixes #15825
2. Now, you can input labels or select them from the candidates
Changes:
Fixes #(issue)

Make label filter editable for replication rule

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
src/go.mod
src/lib/retry/retry.go
src/pkg/permission/evaluator/rbac/casbin_match.go
tests/ci/distro_installer.sh
tests/ci/ut_install.sh
tests/ci/ut_run.sh

feat: upgrade golang to 1.20.1

---

make/migrations/postgresql/0110_2.8.0_schema.up.sql

fix: fix the webhook migration sql

---

make/harbor.yml.tmpl
make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
make/photon/prepare/templates/jobservice/env.jinja
make/photon/prepare/utils/configs.py
src/jobservice/job/impl/notification/http_helper.go
src/jobservice/job/impl/notification/http_helper_test.go
src/jobservice/job/impl/notification/webhook_job.go

Support configurate the http client timeout for webhook job.
Fixes #(issue)

feat: support configurate the http client timeout for webhook job

---

src/jobservice/job/known_jobs.go

Register sweeper retain counts for purge audit log job
Fixes #(issue)

fix: register sweeper retain counts for purge audit log job

---

make/migrations/postgresql/0110_2.8.0_schema.up.sql

The sql must be idempotent
Fixes #(issue)

fix 2.8 migration issue

---

make/harbor.yml.tmpl
make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
src/jobservice/job/impl/notification/slack_job.go
src/jobservice/job/impl/notification/slack_job_test.go
src/jobservice/job/impl/notification/webhook_job.go
src/jobservice/job/impl/notification/webhook_job_test.go

fix: change the default max retry count for webhook job to 3

---

RELEASES.md

Update the support matrix

---

src/pkg/task/sweep_manager.go
src/pkg/task/sweep_manager_test.go

Fix sql error in FixDanglingStateExecution

---

src/server/registry/referrers.go
src/server/registry/referrers_test.go

1, add fitler artifactType to header when the api is called with filter 2, give an empty json body on non aritfact scenario 3, give an empty array on non accessory scenario
4, fix the artifact type filter issue
Fixes #(issue)

fix referrers api response issue

---

make/install.sh

fix: add remove chartmuseum notice message

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.scss
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
src/portal/src/app/services/event-service/event.service.ts
src/portal/src/css/common.scss

1. Fixes #18406
Change:
Fixes #(issue)

Add copy digest button for accessories

---

src/portal/src/app/base/project/webhook/excutions/executions.component.html

1. Fixes #18435
2. Remove the markdown pipe for webhook payload data, then Harbor UI can render payload data correctly
Fixes #(issue)

Remove markdown pipe for webhook payload data

---

tests/resources/Harbor-Pages/Job_Service_Dashboard.robot
tests/resources/Harbor-Pages/Project-Webhooks.robot
tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/Replication_Elements.robot

Update webhook xpath
Update replication xpath
Fixes #(issue)

Update webhook and repliation element xpath

---

src/server/middleware/blob/copy_artifact.go

To enable the middleware to save the project_blob data, make sure to set the accessories options to true when handling the artifact copy.
Fixes #(issue)

fix copy artifact issue

---

src/server/middleware/blob/copy_artifact.go

To enable the middleware to save the project_blob data, make sure to set the accessories options to true when handling the artifact copy.
Fixes #(issue)

[cherry-pick]fix copy artifact issue

---

src/server/middleware/blob/copy_artifact.go

To enable the middleware to save the project_blob data, make sure to set the accessories options to true when handling the artifact copy.
Fixes #(issue)

[cherrt-pick]fix copy artifact issue

---

src/portal/src/app/base/left-side-nav/config/system/system-settings.component.scss
src/portal/src/app/base/project/webhook/excutions/executions.component.scss
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1. extend the width for event type label
2. add quotes for Retain image last pull time to make it more understandable
Fixes #(issue)

Update styles for UI according to the designer's suggestions

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.20.2

---

src/pkg/reg/adapter/harbor/v2/client.go

Fixes #18404
Support multiple level accessories replication.
Fixes #(issue)

fix accessory replication issue

---

make/migrations/postgresql/0110_2.8.0_schema.up.sql

style: adjust the style of migration SQL

---

.buildbaselog

Refresh base images on release-2.8.0

---

tests/resources/Harbor-Pages/Project-Copy.robot
tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
tests/resources/Harbor-Pages/Replication.robot
tests/resources/Harbor-Pages/Replication_Elements.robot
tests/robot-cases/Group1-Nightly/Common.robot

1. Update copy test case to add retries
2. Updata P2P Preheat test case to waiting
3. Update the Replication new rule button xpath
Fixes #(issue)

[cherry-pick]Update UI testcases

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.20.3 on release-2.8.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.20.3 on main

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.19.8 on release-2.7.0

---

.github/workflows/nightly-trivy-scan.yml

1. Update v2.7.0-dev to v2.8.0-dev as main branch is in v2.9.0 now
Fixes #(issue)

Update nightly-trivy-scan.yml for the workflows

---

make/common.sh

Signed-off-by: Maxi_Mega <52792549+Maxi-Mega@users.noreply.github.com>
- Fix two typos in make/common.sh

Fix typos in common.sh

---

.github/workflows/CI.yml
.github/workflows/codeql-analysis.yml
.github/workflows/pass-CI.yml
.github/workflows/pass-codeql-analysis.yml

Skipping CI tests will result in PRs not being merged, as CI passes are required
Fixes #(issue)

Handling skipped but required checks

---

RELEASES.md

Update Support Matrix

---

src/portal/src/app/base/left-side-nav/distribution/distribution-instances/distribution-instances.component.html
src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-additions.component.html
src/portal/src/app/base/project/repository/artifact/artifact-additions/dependencies/dependencies.component.html
src/portal/src/app/base/project/repository/artifact/artifact-additions/summary/summary.component.html
src/portal/src/app/base/project/repository/artifact/artifact-additions/values/values.component.html
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Add missing i18n key-value for helm chart

---

src/portal/src/app/base/left-side-nav/distribution/distribution-instances/distribution-instances.component.html
src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-additions.component.html
src/portal/src/app/base/project/repository/artifact/artifact-additions/dependencies/dependencies.component.html
src/portal/src/app/base/project/repository/artifact/artifact-additions/summary/summary.component.html
src/portal/src/app/base/project/repository/artifact/artifact-additions/values/values.component.html
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Cherry-pick #18578
Fixes #(issue)

[Cherry-pick]Add missing i18n key-value for helm chart

---

.github/workflows/build-package.yml
.github/workflows/publish_release.yml

Fix this error[https://github.com/goharbor/harbor/actions/runs/4776991336/jobs/8492390908]
Fixes #(issue)

Fix setup docker error

---

.github/workflows/build-package.yml
.github/workflows/publish_release.yml

Fix this error[https://github.com/goharbor/harbor/actions/runs/4776991336/jobs/8492390908]
Fixes #(issue)

[cherry-pick]Fix setup docker error

---

make/photon/prepare/utils/configs.py
make/photon/prepare/utils/registry.py

string and None type conversion
Fixes #(issue)

[cherry-pick]allow redis password safe special characters on release-2.8.0

---

make/photon/prepare/utils/configs.py
make/photon/prepare/utils/registry.py

Fixes #https://github.com/goharbor/harbor/issues/18538

Allow redis password using safe special characters

---

CONTRIBUTING.md

Specify proper language in CONTRIBUTING.md code blocks
This will help improve the readability with syntax highlighting

Specify proper language in CONTRIBUTING.md code blocks

---

make/photon/db/Dockerfile
make/photon/db/Dockerfile.base
make/photon/db/docker-entrypoint.sh

Upgrade the internal PostgreSQL to 14 in 2.9.0

---

make/photon/portal/Dockerfile

Copy swagger.json to the dist folder

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.20.4 on release-2.8.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/chartserver/builder
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.19.9 on release-2.7.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.20.4 on main

---

.github/workflows/build-package.yml

Be able to discover photon updates in time.
Fixes #(issue)

Refresh the base images when building on main

---

src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.html
src/portal/src/app/base/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.html
src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.spec.ts
src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
src/portal/src/app/base/project/project-config/project-policy-config/project.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.html
src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
src/portal/src/app/base/project/repository/repository-gridview.component.spec.ts
src/portal/src/app/services/app-config.ts
src/portal/src/app/shared/services/interface.ts

1. remove notary from the UI
2. Remove notary-related unit test cases
Fixes #(issue)

Remove notary UI

---

.github/workflows/build-package.yml

Fix setup-gcloud fails when building package

---

.github/workflows/build-package.yml

[cherry-pick]Fix setup-gcloud fails when building package

---

tools/migrate_chart/Dockerfile
tools/migrate_chart/migrate_chart.py
tools/migrate_chart/migrate_chart.sh

Dump error to migrate_error.txt file  
Dump the total amount of errors
Fixes #(issue)

Handle error in migrate script

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Configuration_Elements.robot
tests/robot-cases/Group1-Nightly/Common.robot

[cherry-pick]Add Retain image last pull time UI test case

---

tests/resources/Harbor-Pages/Configuration.robot
tests/resources/Harbor-Pages/Configuration_Elements.robot
tests/robot-cases/Group1-Nightly/Common.robot

Add Retain image last pull time UI test case

---

src/jobservice/api/authenticator.go
src/registryctl/auth/secret.go

(cherry-pick) Use subtle.ConstantTimeCompare instead of compare directly

---

src/controller/artifact/controller.go
src/controller/artifact/controller_test.go
src/controller/proxy/controller.go
src/controller/tag/controller.go
src/controller/tag/controller_test.go
src/testing/controller/tag/controller.go

fixes #18708
to set the pull time of tag for the first time cache the artifact.
Fixes #(issue)

set tag pull time for proxy cache

---

tests/apitests/python/library/cosign.py
tests/apitests/python/library/referrers_api.py
tests/apitests/python/test_referrers_api.py
tests/files/sbom_test.json
tests/robot-cases/Group0-BAT/API_DB.robot

[cherry-pick]Add Referrers API testcase

---

src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.scss
src/portal/src/app/shared/components/push-image/push-image.component.html
src/portal/src/app/shared/components/push-image/push-image.component.spec.ts
src/portal/src/app/shared/components/push-image/push-image.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1. Fixes #18781
Fixes #(issue)

Add Podman push command to the UI

---

src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1. Update the text for all the i18n files
Fixes #(issue)

Update the text for the oidc cli secret tooltip

---

src/jobservice/README.md

Job logger support file, db and stdout, the comment should include the type of DB as well as file and stdout.
Fixes #(issue)

jobservice: add DB to job logger config

---

ADOPTERS.md

Adding Dynatrace as adopter 
depends on:
https://github.com/goharbor/website/pull/465

Add Dynatrace as adopter and fix master to main

---

src/jobservice/README.md
src/jobservice/mgt/manager.go

To reflect the newest job interface, and the missing parts of DB job service logger.
Fixes #(issue)

jobservice: update readme

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.scss
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.html
src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.scss
src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.module.ts
src/portal/src/app/base/project/repository/artifact/artifact.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1.Fixes #18832
Remove the pull command column from the datagrid and add `COPY PULL COMMAND` dropdown at the top right of the datagrid:
Fixes #(issue)

Add new client Podman to the pull command

---

make/migrations/postgresql/0120_2.9.0_schema.up.sql
src/pkg/scan/dao/scan/model.go
src/pkg/scan/dao/scan/report.go
src/pkg/scan/postprocessors/report_converters.go
src/pkg/scan/postprocessors/report_converters_test.go
src/pkg/scan/report/manager.go
src/testing/pkg/scan/report/manager.go

For better performance when query cve information, add summary information to scan_report
Extract cve_score from vendor attribute in vulnerability_record
SQL migrate script for the update
Fixes #(issue)

Update table scan_report and extract cvss_v3_score from vendor attribute

---

src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts

1. Fixes #18870
Fixes #(issue)

Add unit test for hidden columns

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html

Correct the hidden property for clrDgHideableColumn

---

tests/resources/Harbor-Pages/Project-Webhooks.robot
tests/resources/Harbor-Pages/Project-Webhooks_Elements.robot
tests/resources/TestCaseBody.robot
tests/resources/Webhook-Util.robot
tests/robot-cases/Group1-Nightly/Webhook.robot

[cherry-pick]Add CloudEvents format webhook testcase

---

tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/OIDC.robot

[cherry-pick]Add OIDC filter group testcase

---

src/controller/gc/controller.go
src/controller/gc/controller_test.go

fixes #18881
Save workers settings into the metadata of the garbage collection schedule
Fixes #(issue)

fix gc schedule issue

---

src/core/auth/authenticator.go

Log warning message when current user is freeze

---

src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.html
src/portal/src/app/base/project/project-config/project-policy-config/project-policy-config.component.ts
src/portal/src/app/base/project/project-config/project-policy-config/project.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/sub-accessories/sub-accessories.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.service.ts
src/portal/src/app/base/project/repository/artifact/artifact.ts
src/portal/src/app/services/event-service/event.service.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Add Notation UI for deployment security

---

make/migrations/postgresql/0120_2.9.0_schema.up.sql

add index for better query performance
Fixes #(issue)

Create index in vulnerability_record table

---

.buildbaselog

Refresh base images on 2.8

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts

Update the parameter to search cosign

---

tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
tests/resources/TestCaseBody.robot
tests/robot-cases/Group1-Nightly/Common_GC.robot
tests/robot-cases/Group1-Nightly/Replication.robot
tests/robot-cases/Group1-Nightly/Webhook.robot

Sync test case updates because of changes to webhook and replication
1. #18923
2. #18906
Fixes #(issue)

Update webhook and replication testcase

---

make/photon/db/Dockerfile.base

Fix build harbor-db-base error

---

make/migrations/postgresql/0120_2.9.0_schema.up.sql

Skip to run migrate script when data available

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/golang/Dockerfile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

remove build_golang in ci script
Fixes #(issue)

bump golang1.20.6 on release-2.8.0& build golang based on photon

---

src/jobservice/job/impl/gc/garbage_collection.go
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.html
src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

fixes #19040
Gives the make details for the dry-run
Fixes #(issue)

add details for gc dry-run

---

src/jobservice/job/impl/gc/garbage_collection.go

Give the mock time for dry run, otherwise, it will be zero.
Fixes #(issue)

fix dry run creation time

---

src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts

Add validator for duration of banner message

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.20.6 on main

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.ts

1.Merge cosign check and notaion check into one API call, related issue #19077
Fixes #(issue)

Merge cosign check and notation check

---

src/portal/src/app/base/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts

Cherry-pick #19080
Fixes #(issue)

[Cherry-pick]Convert the string "0" to number 0

---

src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.scss
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.html
src/portal/src/app/base/left-side-nav/config/system/system-settings.component.ts

1. Fixes #19031
2. Fixes #19049
Fixes #(issue)

Update ui for gc history and banner message

---

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Update cron ui for add replicatipn rule page

---

src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.scss

1. Fixes #19098
Fixes #(issue)

Update style for add-replication-rule page

---

api/v2.0/swagger.yaml

fixes #18262
Add Schedule as a valid enum values of ScheduleObj.type
Fixes #(issue)

fix ScheduleObj.type in swagger

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.20.7 on main

---

.buildbaselog

Refresh base images on 2.9.0

---

.github/workflows/publish_release.yml

Bump up setup-gcloud to 430.0.0
Fixes #(issue)

[cherry-pick]Bump up setup-gcloud to 430.0.0

---

.github/workflows/publish_release.yml

Bump up setup-gcloud to 430.0.0
Fixes #(issue)

Bump up setup-gcloud to 430.0.0

---

make/harbor.yml.tmpl
make/photon/prepare/migrations/version_2_4_0/harbor.yml.jinja
make/photon/prepare/migrations/version_2_5_0/harbor.yml.jinja
make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja
make/photon/prepare/migrations/version_2_7_0/harbor.yml.jinja
make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
make/photon/prepare/models.py

Update the incorrect otel timeout sample value in the harbor YAML configuration template.
Fixes https://github.com/goharbor/harbor/issues/19084

[cherry-pick] chore: fix incorrect otel timeout in harbor yaml template

---

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html

ignore spaces for vulnerability filters

---

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html

1. Cherry-pick #19180
Fixes #(issue)

[Cherry-pick]ignore spaces for vulnerability filters

---

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-filter/vulnerability-filter.component.ts

1.Cherry-pick #19194
Fixes #(issue)

[Cherry-pick]Update the max length for the filters

---

src/pkg/securityhub/dao/security.go

Filter artifact without CVE from top 5 dangerous artifacts

---

src/pkg/securityhub/dao/security.go

(cherry-pick) Filter artifact without CVE from top 5 dangerous artifacts

---

src/pkg/securityhub/dao/security.go

(cherry-pick) Wrong artifact scanned count

---

src/jobservice/job/impl/gc/garbage_collection.go

In the dry run mode, the accessories should be considered when try to simulate delete the subject manifest.
Fixes #(issue)

fix gc dry run issue

---

src/portal/src/app/route-reuse-strategy/harbor-route-reuse-strategy.ts

Add new uri path to ShouldNotReuseRoute array

---

src/portal/src/app/route-reuse-strategy/harbor-route-reuse-strategy.ts

Cherry-pick #19217
Fixes #(issue)

[Cherry-pick]Add new uri path to ShouldNotReuseRoute array

---

src/pkg/securityhub/dao/security.go
src/pkg/securityhub/dao/security_test.go

Refine total artifact and scanned artifact

---

src/pkg/securityhub/dao/security.go
src/pkg/securityhub/dao/security_test.go

(cherry-pick) Refine total artifact and scanned artifact

---

src/portal/src/i18n/lang/zh-cn-lang.json

i18n: fix typo for CONFIRM_SECRET

---

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.scss
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1. This tooltip explains the artifacts total count
2. Cherry-pick #19231
Fixes #(issue)

[Cherry-pick]Add a tooltip for the page title of security hub

---

.buildbaselog

Refresh base images on release-2.9.0

---

src/portal/package-lock.json
src/portal/package.json
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.ts
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
src/portal/src/app/shared/shared.module.ts

Cherry-pick #19262
Fixes #(issue)

[Cherry-pick]Switch to a new chart library

---

.github/workflows/nightly-trivy-scan.yml

Update the image version for trivy scan for release-2.9.0 branch
Fixes #(issue)

Update the image version for trivy scan

---

src/portal/package-lock.json
src/portal/package.json
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/single-bar/single-bar.component.ts
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html
src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.ts
src/portal/src/app/shared/shared.module.ts

Switch to a new chart library

---

make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja

Fixes https://github.com/goharbor/harbor/issues/19320

(cherry-pick)fix storage.redirect.disable migrate template error release-2.8.0

---

make/photon/prepare/migrations/version_2_8_0/harbor.yml.jinja
make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja

update boolean to lowercase
Fixes https://github.com/goharbor/harbor/issues/19320

(cherry-pick) fix storage.redirect.disable migrate template error release-2.9.0

---

tests/apitests/python/library/base.py
tests/apitests/python/library/repository.py
tests/apitests/python/library/securityhub.py
tests/apitests/python/test_security_hub.py
tests/robot-cases/Group0-BAT/API_DB.robot

Add security hub API test case

---

tests/apitests/python/library/base.py
tests/apitests/python/library/repository.py
tests/apitests/python/library/securityhub.py
tests/apitests/python/test_security_hub.py
tests/robot-cases/Group0-BAT/API_DB.robot

[cherry-pick]Add security hub API test case

---

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html

1.Related issue #19391
Fixes #(issue)

[Cherry-pick]Hide version property if the value is undefined

---

src/portal/src/app/base/left-side-nav/interrogation-services/vulnerability-database/vulnerability-summary/vulnerability-summary.component.html

1.Related issue #19391
Fixes #(issue)

Hide version property if the value is undefined

---

src/pkg/securityhub/dao/security.go

(cherry-pick) Change fixed_version to package_version

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang to 1.20.10

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

[cherry-pick]bump golang to 1.20.10

---

src/server/middleware/subject/subject.go
src/server/middleware/subject/subject_test.go

Needs to set the repo when to handle the accessory before subject manifest.
Fixes #(issue)

fix issue 19392

---

src/portal/src/app/shared/components/operation/operation.component.css

Update the style for operation-component

---

tests/apitests/python/test_garbage_collection.py

Add GC accessory API test case

---

tests/apitests/python/test_garbage_collection.py
tests/resources/Cosign_Util.robot
tests/resources/Harbor-Pages/GC.robot
tests/resources/Harbor-Pages/Project-Artifact-Elements.robot
tests/resources/Harbor-Pages/Project-Artifact.robot
tests/resources/TestCaseBody.robot
tests/robot-cases/Group1-Nightly/Common_GC.robot

[cherry-pick]Add GC accessory UI test case

---

tests/apitests/python/library/gc.py
tests/apitests/python/test_garbage_collection.py

[cherry-pick]Add GC details and GC workers API test case

---

tests/apitests/python/library/gc.py
tests/apitests/python/test_garbage_collection.py

Add GC details and GC workers API test case

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
src/go.mod
src/server/middleware/quota/util_test.go
tests/ci/distro_installer.sh

bump golang to 1.21.3 on release-2.9.0

---

src/server/middleware/quota/util_test.go

update ut mock anything

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
src/go.mod
src/server/middleware/quota/util_test.go
tests/ci/distro_installer.sh

bump golang to 1.21.3

---

tests/apitests/python/library/base.py
tests/apitests/python/library/notation.py
tests/apitests/python/test_cosign_sign_artifact.py
tests/apitests/python/test_notation_sign_artifact.py
tests/robot-cases/Group0-BAT/API_DB.robot

Add notation sign artifact  API test case

---

tests/apitests/python/test_permission.py

usage example:
HARBOR_BASE_URL=https://{ip_or_domain}/api/v2.0 RESOURCE=preheat-instance  USER_NAME={username} PASSWORD={password}  python tests/apitests/python/test_permission.py
Fixes #(issue)

Add API permission testcase

---

src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.html
src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.ts

Add quota sorting to the project quotas list

---

tests/apitests/python/test_permission.py

Add audit-log,project,registry,replication API permission testcase
Fixes #(issue)

Add API(audit-log,project,registry,replication) permission testcase

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang to 1.21.4

---

src/common/rbac/const.go
src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.ts
tests/apitests/python/test_robot_account.py

1. Update the permission scope
2. Sort the resources and actions by unicode
Fixes #(issue)

Update the permission scope

---

tests/apitests/python/test_project_permission.py

1. Add API test cases to cover all the project level permissions
Fixes #(issue)

Add test cases for the project level permissions

---

tests/resources/Harbor-Pages/Project.robot
tests/resources/Notation_Util.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common.robot
tests/robot-cases/Group1-Nightly/Replication.robot

Add notation accessory copy test case

---

tests/resources/Harbor-Pages/Project.robot
tests/resources/Notation_Util.robot
tests/resources/Util.robot
tests/robot-cases/Group1-Nightly/Common.robot
tests/robot-cases/Group1-Nightly/Replication.robot

[cherry-pick]Add notation accessory copy test case

---

tests/resources/Harbor-Pages/Project-Config.robot
tests/robot-cases/Group1-Nightly/Common.robot

Add notation pull policy test case

---

tests/robot-cases/Group1-Nightly/Common.robot

[cherry-pick]Add jump to CNAB Bundle index artifact list test case

---

tests/apitests/python/test_project_permission.py

Update the test script for the project permissions

---

tests/apitests/python/library/user.py
tests/apitests/python/test_user_crud.py
tests/robot-cases/Group0-BAT/API_DB.robot

[cherry-pick]Add user API test case

---

.buildbaselog

Refresh base images on release-2.7.0

---

make/photon/prepare/migrations/version_2_10_0/harbor.yml.jinja

https://github.com/goharbor/harbor/issues/19654

fix 2.10 prepare migration version

---

src/portal/src/app/base/left-side-nav/project-quotas/project-quotas/project-quotas.component.scss
src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.html
src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-accounts.component.scss
src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.html
src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.scss
src/portal/src/app/shared/components/robot-permissions-panel/robot-permissions-panel.component.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

1. Fixes #19614
2. Fixes #19617
Fixes #(issue)

Update the style for the robot acccount ui

---

src/portal/src/app/base/left-side-nav/system-robot-accounts/list-all-projects/list-all-projects.component.html
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Update the wording text for the system robot account  according to the comments from UX
Fixes #(issue)

Update the wording text for the system robot account

---

tests/apitests/python/test_project_permission.py
tests/apitests/python/test_system_permission.py
tests/resources/Harbor-Pages/Project_Robot_Account.robot
tests/resources/Harbor-Pages/Project_Robot_Account_Elements.robot
tests/resources/Harbor-Pages/Robot_Account.robot
tests/resources/Harbor-Pages/Robot_Account_Elements.robot
tests/robot-cases/Group1-Nightly/Common.robot
tests/robot-cases/Group1-Nightly/Replication.robot

Update project and system robot account testcase
Update system robot account do replication testcase
Fixes #(issue)

Update Robot Account Test Case

---

tests/apitests/python/test_project_permission.py
tests/apitests/python/test_system_permission.py
tests/resources/Harbor-Pages/Project_Robot_Account.robot
tests/resources/Harbor-Pages/Project_Robot_Account_Elements.robot
tests/resources/Harbor-Pages/Robot_Account.robot
tests/resources/Harbor-Pages/Robot_Account_Elements.robot
tests/robot-cases/Group1-Nightly/Common.robot
tests/robot-cases/Group1-Nightly/Replication.robot

Update project and system robot account testcase
Update system robot account do replication testcase
Fixes #(issue)

[cherry-pick]Update Robot Account Test Case

---

.buildbaselog

Refresh base images on release-2.10.0

---

ADOPTERS.md

following https://github.com/goharbor/website/pull/520

add DE-CIX as adopters

---

tests/robot-cases/Group1-Nightly/Replication.robot

[cherry-pick]Add notation replication test case

---

tests/robot-cases/Group1-Nightly/Replication.robot

[cherry-pick]Add multi-tier accessory replication test cases

---

tests/robot-cases/Group1-Nightly/Replication.robot

Add notation replication test case

---

tests/robot-cases/Group1-Nightly/Replication.robot

Add multi-tier accessory replication test cases

---

.github/workflows/nightly-trivy-scan.yml

Update tag in nightly trivy scan

---

make/harbor.yml.tmpl

fix invalid links in harbor.yml.tmpl

---

src/common/rbac/const.go
src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Add quota permissions to robot account

---

src/common/rbac/const.go
src/portal/src/app/base/left-side-nav/system-robot-accounts/system-robot-util.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

[cherry-pick]Add quota permissions to robot account

---

src/common/rbac/const.go

[cherry-pick]Remove robot account update quota permission

---

src/common/rbac/const.go

Remove robot account update quota permission

---

tests/apitests/python/test_system_permission.py
tests/resources/Harbor-Pages/Project_Robot_Account.robot
tests/robot-cases/Group1-Nightly/Common.robot

[cherry-pick]Add quota permissions testcase

---

Makefile

remove the unused the part from makefile
Fixes #(issue)

deprecate gosec in makefile

---

src/controller/proxy/controller.go
src/controller/proxy/controller_test.go
src/controller/proxy/manifestcache.go

[cherry-pick] Cache image list with digest key

---

src/lib/config/userconfig.go

fixes #19795, remove the noise in the log
Fixes #(issue)

remove the log for ScannerSkipUpdatePullTime

---

src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json

Removing double "an" in the About UI

Fixing typo for About UI

---

src/lib/config/userconfig.go

fixes #19795, remove the noise in the log
Fixes #(issue)

[cherry-pick]remove the log for ScannerSkipUpdatePullTime

---

src/server/v2.0/handler/robot.go

Update isValidDuration function

---

tests/resources/Harbor-Pages/Replication_Elements.robot

Update replication rule filter label xpath

---

tests/resources/Harbor-Pages/Replication_Elements.robot

[cherry-pick]Update replication rule filter label xpath

---

make/photon/prepare/templates/nginx/nginx.https.conf.jinja
make/photon/prepare/templates/portal/nginx.conf.jinja

[cherry-pick]add v6 port for nginx ad portal config

---

make/photon/prepare/templates/nginx/nginx.https.conf.jinja
make/photon/prepare/templates/portal/nginx.conf.jinja

Fixes https://github.com/goharbor/harbor/issues/19865

add v6 port for nginx and portal config

---

tests/resources/Harbor-Pages/Replication_Elements.robot

[Cherry-Pick] Update replication rule filter label xpath (#19895)

---

tests/resources/Harbor-Pages/Project.robot
tests/resources/Harbor-Pages/SecurityHub.robot
tests/resources/Harbor-Pages/SecurityHub_Elements.robot

fix: cve export label filter xpath

---

make/harbor.yml.tmpl
make/photon/prepare/migrations/version_2_10_0/harbor.yml.jinja
make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
make/photon/prepare/templates/nginx/nginx.https.conf.jinja
make/photon/prepare/templates/portal/nginx.conf.jinja
make/photon/prepare/utils/configs.py
make/photon/prepare/utils/nginx.py
make/photon/prepare/utils/portal.py

https://github.com/goharbor/harbor/issues/19932

add ip_family config in harbor.yml on release-2.10

---

make/harbor.yml.tmpl
make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja
make/photon/prepare/templates/nginx/nginx.https.conf.jinja
make/photon/prepare/templates/portal/nginx.conf.jinja
make/photon/prepare/utils/configs.py
make/photon/prepare/utils/nginx.py
make/photon/prepare/utils/portal.py

https://github.com/goharbor/harbor/issues/19932#issuecomment-1926639534

reverse ip_family config for release-2.9

---

make/photon/prepare/migrations/version_2_10_0/harbor.yml.jinja
make/photon/prepare/migrations/version_2_9_0/harbor.yml.jinja

https://github.com/goharbor/harbor/issues/19932#issuecomment-1926639534

remove ipfamily config migrate jinja in 2.9 and 2.10

---

tests/apitests/python/test_scan_data_export.py

update retry of get_scan_data_export_execution from 5 to 15

---

package-lock.json

Remove redundant file package-lock.json under src folder. This file was introduced by #19733.
Fixes #(issue)

Remove redundant file package-lock.json under src folder

---

src/core/controllers/oidc.go

Limit url to local site

---

src/common/utils/utils.go
src/common/utils/utils_test.go
src/core/controllers/oidc.go

[cherry-pick] limit url to local site

---

make/photon/db/Dockerfile.base
src/common/utils/utils.go
src/common/utils/utils_test.go
src/core/controllers/oidc.go

[cherry-pick]Limit URL to local site

---

make/photon/prepare/templates/nginx/nginx.https.conf.jinja
make/photon/prepare/templates/portal/nginx.conf.jinja
make/photon/prepare/utils/configs.py
make/photon/prepare/utils/nginx.py
make/photon/prepare/utils/portal.py

Move strong_ssl_ciphers to top level in harbor.yml

---

src/pkg/project/models/pro_meta.go
src/pkg/project/models/project.go
src/server/v2.0/handler/project_metadata.go

Add a new switcher for sbom generation, by default is false.
Fixes #(issue)

add sbom settings for project

---

src/controller/artifact/controller.go
src/server/registry/manifest.go

- https://github.com/goharbor/harbor/issues/20072

Update deletion for index type of accessory

---

src/server/v2.0/handler/project_metadata.go

fix: assign metas to key and value

---

src/controller/replication/execution.go
src/controller/replication/execution_test.go
src/controller/retention/controller.go
src/controller/systemartifact/execution.go
src/controller/systemartifact/execution_test.go
src/pkg/task/dao/task.go
src/pkg/task/dao/task_test.go
src/pkg/task/execution.go
src/testing/pkg/task/execution_manager.go

panic due to mark retention task error 

---

src/pkg/joblog/manager.go
src/server/v2.0/handler/model/webhook_policy.go

chore: fix function names

---

src/controller/replication/execution.go
src/controller/replication/execution_test.go
src/controller/retention/controller.go
src/controller/systemartifact/execution.go
src/controller/systemartifact/execution_test.go
src/pkg/task/dao/task.go
src/pkg/task/dao/task_test.go
src/pkg/task/execution.go
src/testing/pkg/task/execution_manager.go

[cherry-pick] panic due to mark retention task error

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang to 1.21.8 on release-2.10.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.21.8 on release-2.9.0

---

src/pkg/scan/export/digest_calculator.go

fix: close file

---

src/pkg/scan/util.go
src/pkg/scan/util_test.go

Update GenAccessoryArt API to generate valid accessory for SBOM

---

api/v2.0/swagger.yaml
src/controller/scan/options.go
src/server/v2.0/handler/scan.go

Add SBOM scan REST API

---

tests/apitests/python/library/quota_sorting.py
tests/apitests/python/test_quota_sorting.py
tests/robot-cases/Group0-BAT/API_DB.robot

feat: add api test case for quota sorting

---

src/common/utils/utils.go
src/common/utils/utils_test.go

[cherry-pick] Allow empty path in redirect_url

---

api/v2.0/swagger.yaml
tests/apitests/python/test_project_permission.py

fix: test robot account permission

---

api/v2.0/swagger.yaml

fix: add 400 response code for /scan/{report_id}/log

---

make/migrations/postgresql/0140_2.11.0_schema.up.sql

update artifact_type column alteration

---

src/server/middleware/cosign/cosign.go
src/server/middleware/subject/subject.go

adopt cosign with oci-spec 1.1

---

src/controller/artifact/processor/chart/chart.go
src/controller/artifact/processor/sbom/sbom.go
src/controller/artifact/processor/sbom/sbom_test.go

complete task #20066
Fixes #(issue)

Update swagger API to display SBOM content in addition API

---

src/controller/scan/base_controller.go
src/controller/scan/base_controller_test.go
src/pkg/scan/rest/v1/models.go
src/pkg/scan/rest/v1/models_test.go
src/pkg/scan/rest/v1/spec.go
src/server/v2.0/handler/artifact.go
src/server/v2.0/handler/assembler/report.go
src/server/v2.0/handler/assembler/report_test.go
src/server/v2.0/handler/model/artifact.go
src/server/v2.0/handler/model/option.go
src/server/v2.0/handler/model/option_test.go

Support list artifact with_sbom_overview option

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
tests/ci/distro_installer.sh

bump golang 1.21.9 on release-2.9.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/codeql-analysis.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
src/go.mod
tests/ci/distro_installer.sh
tests/ci/ut_install.sh

bump golang to 1.22.2

---

.buildbaselog

Refresh bash image

---

Makefile

fix: update TRIVYVERSION=v0.50.1 && TRIVYADAPTERVERSION=v0.31.0

---

tests/robot-cases/Group1-Nightly/OIDC.robot

feat: add test case for customizing OIDC provider name

---

api/v2.0/swagger.yaml
src/controller/scan/base_controller.go
src/server/v2.0/handler/scan.go

Rename scan request type

---

src/controller/scanner/controller.go

refactor: update controller.go

---

src/controller/scan/base_controller.go

Add enableCapabilities to extraAttrs for stop

---

api/v2.0/swagger.yaml
src/controller/scan/base_controller.go
src/pkg/scan/sbom/sbom.go

change log level with no content message
fix time in sbom accessory
fixes #20342 #20332 #20328
Fixes #(issue)

Add 422 in the swagger.yaml

---

src/controller/event/topic.go

fix: update image reference to "@" in audit log when pushing & deleting images

---

src/controller/event/handler/internal/artifact.go
src/pkg/scan/dao/scan/report.go
src/pkg/scan/dao/scan/report_test.go
src/pkg/scan/report/manager.go
src/testing/pkg/scan/report/manager.go

Delete scan_report when accessory is removed

---

src/server/v2.0/handler/assembler/report.go
src/server/v2.0/handler/assembler/report_test.go

Display status in sbom_overview for image index

---

src/controller/artifact/model.go
src/server/v2.0/handler/assembler/report.go
src/server/v2.0/handler/assembler/report_test.go

artifact object's addition_links has sboms item when it support to generate sbom
fixes #20346
Fixes #(issue)

Add additional link for sboms

---

.buildbaselog

fresh base image

---

Makefile

Bump up trivy version to v0.51.2, trivyadapter to v0.31.2

---

Makefile

bump up trivy and trivy-adapter version

---

src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-sbom/artifact-sbom.component.ts
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts

fix sbom status and download issue
Fixes #20469

Fix - 20469 sbom status and download issue

---

.buildbaselog

Bump up base image

---

src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html

[cherry-pick] Fix tooltip issue related to SBOM.Details

---

src/pkg/scan/sbom/sbom.go
src/pkg/scan/sbom/sbom_test.go

Fix multiple SBOM

---

src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html

Fix tooltip issue related to SBOM.Details

---

src/pkg/scan/util.go

Make it supports the tls configuration for the client for pushing sbom object
Fixes #(issue)

tls support for pushing sbom

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.ts
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.ts
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.html
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.scss
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.spec.ts
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-tip-histogram/sbom-tip-histogram.component.ts
src/portal/src/app/base/project/repository/artifact/sbom-scanning/scanning.scss
src/portal/src/app/base/project/tag-feature-integration/immutable-tag/immutable-tag.component.ts
src/portal/src/app/shared/units/utils.ts
src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/ko-kr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Fix UI bugs - Pagination is missing on tag immutability rules

---

src/pkg/scan/util.go

[cherry-pick] fix http client to push sbom accessory

---

src/pkg/scan/sbom/sbom.go
src/pkg/scan/sbom/sbom_test.go
src/pkg/task/mock_task_manager_test.go
src/pkg/task/task.go
src/testing/pkg/task/manager.go

[cherry-pick] Response an error message when there is incomplete sbom generate job

---

src/pkg/scan/util.go

fix http client to push sbom accessory

---

src/server/v2.0/handler/assembler/report.go
src/server/v2.0/handler/assembler/report_test.go

[cherry-pick] No sbom_overview when sbom is deleted

---

src/portal/src/app/base/project/repository/artifact/artifact-additions/artifact-additions.component.ts
src/portal/src/app/base/project/repository/artifact/sbom-scanning/sbom-scan.component.spec.ts

 Fixes-20537 SBOM tab should not exist when the artifact is helm package 

---

RELEASES.md

doc: update minor release support matrix with v2.11.x

---

.github/workflows/nightly-trivy-scan.yml

fix: update image tag for nightly-trivy-scan

---

src/portal/src/app/shared/entities/shared.const.ts

Add menu item for ko_KR local

---

tests/resources/Harbor-Pages/Job_Service_Dashboard.robot

fix: update the cron of execution sweep in test 

---

src/portal/src/app/shared/entities/shared.const.ts

[cherry-pick] Add menu item for ko_KR local

---

tests/robot-cases/Group3-Upgrade/data.json

fix: change coporate harbor to registry.goharbor.io

---

tests/robot-cases/Group3-Upgrade/data.json

fix: update migrate tc

---

.github/workflows/publish_release.yml

fix: add quote to dockerhub cred

---

.github/workflows/publish_release.yml

[cherry-pick] fix: add quote to dockerhub cred

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html

can't remove artifact labels
Fixes #20799

Fixes-20799 can't remove artifact labels

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html

Can't remove artifact labels
Fixes #20799

cherry-pick: Fixes-20799 can't remove artifact labels

---

src/pkg/task/sweep_manager.go

cherry-pick #20603

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
src/go.mod
tests/ci/distro_installer.sh

fix: bump up golang to v1.22.6

---

api/v2.0/swagger.yaml

Fix typo in the Swagger API docs.

Fix typo in Swagger API docs

---

src/controller/event/handler/auditlog/auditlog.go
src/controller/event/handler/init.go
src/controller/event/metadata/robot.go
src/controller/event/metadata/robot_test.go
src/controller/event/topic.go
src/controller/robot/controller.go
src/controller/robot/controller_test.go

1, add creation audit log for robot account
2, add deletion audit log for robot account
Fixes #(issue)

enable audit log for robot

---

.buildbaselog
Makefile

and bump up base image
Fixes #(issue)

fix: bump trivy-adapter version to v0.31.4 and trivy version to v0.54.1;

---

src/controller/artifact/controller.go

[cherry-pick] Check create when fire the artifact event

---

tests/apitests/python/library/artifact.py
tests/apitests/python/library/scan.py
tests/apitests/python/library/scan_stop.py
tests/apitests/python/test_project_permission.py
tests/apitests/python/test_sbom_generation_of_image_artifact.py
tests/apitests/python/test_stop_sbom_generation_of_image_artifact.py
tests/resources/Harbor-Pages/Project-Repository.robot
tests/resources/Harbor-Pages/Project-Repository_Elements.robot
tests/resources/Harbor-Pages/Vulnerability.robot
tests/resources/TestCaseBody.robot
tests/robot-cases/Group0-BAT/API_DB.robot
tests/robot-cases/Group1-Nightly/Trivy.robot

[Cherrypick to v2.11]add Test Case for SBOM feature (#20797)

---

src/portal/src/app/base/left-side-nav/projects/create-project/create-project.component.html
src/portal/src/app/base/left-side-nav/replication/replication/create-edit-rule/create-edit-rule.component.html
src/portal/src/app/base/left-side-nav/system-robot-accounts/new-robot/new-robot.component.html
src/portal/src/app/base/project/robot-account/add-robot/add-robot.component.html

Escape the - with \- when it is a char of itself

---

.buildbaselog

- [C] Well Written Title and Summary of the PR

Update ".buildbaselog" to trigger refresh of base image

---

.github/workflows/build-package.yml

update the version of docker-compose to be installed in "build-package"

---

Makefile
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh

update the version and point to the URL of new repository under goharbor
Fixes #(issue)

Bump up trivy adapter

---

src/pkg/reg/adapter/harbor/v2/adapter.go
src/pkg/reg/adapter/harbor/v2/client.go

fixes #20430, set the pagesize to 100 when to list artifact on replication
Fixes #(issue)

add pagesize for replicaiton

---

.github/workflows/build-package.yml

fix build package issue

---

.buildbaselog

refresh base for v2.12

---

Makefile

Bump up trivy adapter to v0.32.0-rc.2

---

.buildbaselog

refresh base

---

RELEASES.md

Update support matrix for 2.12.x

---

.buildbaselog

refersh base release-2.11.0

---

.github/workflows/CI.yml
.github/workflows/build-package.yml
.github/workflows/conformance_test.yml
CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
src/go.mod
tests/ci/distro_installer.sh

bump golang to 1.22.9 on release-2.11

---

.github/workflows/nightly-trivy-scan.yml

Update image tag for nightly-trivy-scan

---

tests/apitests/python/test_proxy_cache.py
tests/robot-cases/Group1-Nightly/Common.robot
tests/robot-cases/Group1-Nightly/LDAP.robot
tests/robot-cases/Group1-Nightly/OIDC.robot
tests/robot-cases/Group1-Nightly/Replication.robot
tests/robot-cases/Group1-Nightly/Schedule.robot

replace cicd to registry.goharbor.io on release-2.11.0

---

.github/workflows/build-package.yml

disable gpg sign for release-2.11.0

---

.github/workflows/build-package.yml

fix gpg sign build package release-2.11.0

---

Makefile

Bump up to trivy adapter v0.32.0

---

Makefile
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh

Bump up Trivy Adapter for v2.11.x

---

.github/workflows/build-package.yml

remove slack notification release-2.12.0

---

.github/workflows/build-package.yml

remove slack notification

---

.github/workflows/build-package.yml

remove slack notification release-2.11.0

---

tools/release/release_utils.sh

remove asc files handling

---

tests/apitests/python/library/cnab.py
tests/apitests/python/test_push_cnab_bundle.py
tests/apitests/python/test_system_permission.py
tests/resources/Docker-Util.robot
tests/resources/TestCaseBody.robot
tests/robot-cases/Group1-Nightly/Replication.robot
tests/robot-cases/Group1-Nightly/Webhook.robot

Change dockhub to registry.goharbor.io
Change the testcase for webhook
Fixes #(issue)

Update testcase for test env change, especially for webhook config

---

src/controller/artifact/controller.go

revert change of artifact event

---

Makefile

Bump up trivy to v0.57.1 and trivy-adapter to v0.32.1-rc.1

---

CONTRIBUTING.md
Makefile
make/photon/registry/Dockerfile.binary
make/photon/trivy-adapter/Dockerfile.binary
make/photon/trivy-adapter/builder.sh
src/go.mod
tests/ci/distro_installer.sh

bump go version

---

src/server/v2.0/handler/robot.go
src/server/v2.0/handler/robot_test.go

fix robot account creation issue

---

Makefile

Bump up to use trivy adapter v0.32.1 (GAed version)

---

Makefile

Bump up trivy adapter to fix a CVE

---

Makefile

Pin to trivy adapter v0.32.2 GAed version.

Pin trivy adapter v0.32.2

---

src/go.mod
src/go.sum

bump go dep

---

src/common/const.go
src/lib/config/metadata/metadatalist.go
src/lib/config/userconfig.go

Add configure item audit_log_disable
Fixes #(issue)

Add configure item for audit_log_disable

---

make/harbor.yml.tmpl
make/photon/prepare/templates/jobservice/config.yml.jinja
make/photon/prepare/templates/jobservice/env.jinja
make/photon/prepare/utils/configs.py
make/photon/prepare/utils/jobservice.py

Add config max_job_duration_hours for jobservice

---

tests/apitests/python/test_system_permission.py

Update the ping registry endpoint to harbor in check permission script

---

make/photon/prepare/utils/configs.py

Update prepare to avoid error when max_job_duration_hours not configured

---

src/controller/event/metadata/commonevent/model.go
src/core/middlewares/middlewares.go
src/server/middleware/log/log.go

Add middleware for audit log

---

tests/apitests/python/test_system_permission.py

Remove id field from payload when update purge audit or gc schedule

---

.buildbaselog

bump base images

---

Makefile

Bump up trivy to v0.58.2, trivy adapter to v0.32.3

---

src/portal/src/app/base/left-side-nav/replication/replication/replication-tasks/replication-tasks.component.scss

- Fixes overflow of text in Turkish and German languages.
Fixes #21059 
- increase width from `100px` to `150px` to support two words.

Fix Overlay Issue in Replication Page UI

---

.github/workflows/build-package.yml
tests/integration.sh

disable gpg sign for 1.10

---

Makefile

Bump up trivy to v0.58.2, trivy adapter to v0.32.3 (#21417)

---

src/portal/src/app/base/left-side-nav/replication/replication/list-replication-rule/list-replication-rule.component.html

- fix incorrect data display in replications table
Fixes #(issue)

[cherry-pick] Fix Incorrect Data Display in Replications Table (#21461)

---

src/controller/event/handler/webhook/artifact/replication.go
src/controller/event/model/event.go

Add execution_id and task_id to the replication webhook payload.
Fixes https://github.com/goharbor/harbor/issues/20182

feat: add execution_id and task_id to the replication webhook payload

---

src/core/controllers/oidc.go
src/pkg/auditext/event/login/login.go

Add OIDC login event

---

src/controller/systeminfo/controller.go
src/controller/systeminfo/controller_test.go
src/server/v2.0/handler/systeminfo.go

[21152](https://github.com/goharbor/harbor/issues/21152)

remove version info for anonymous users

---

Makefile

consume the downstream distribution

---

src/portal/src/app/base/preference-settings/preference-settings.component.scss
src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.html
src/portal/src/app/base/project/repository/artifact/artifact-tag/artifact-tag.component.scss

Fix: Copy Pull Button Overlap with Tag Immutable Label

---

src/core/controllers/oidc.go

If redirect to the root page, harbor UI will redirect to the OIDC login page automaticlly.
Fixes #(issue)

redirect to the sign-in page

---

src/core/controllers/oidc.go

For the default redirection, to the sign page.
Fixes #(issue)

fix logout redirect

---

src/portal/package.json

Update UI Version to 2.12.0 in package.json

---

src/portal/src/i18n/lang/de-de-lang.json
src/portal/src/i18n/lang/en-us-lang.json
src/portal/src/i18n/lang/es-es-lang.json
src/portal/src/i18n/lang/fr-fr-lang.json
src/portal/src/i18n/lang/ko-kr-lang.json
src/portal/src/i18n/lang/pt-br-lang.json
src/portal/src/i18n/lang/tr-tr-lang.json
src/portal/src/i18n/lang/zh-cn-lang.json
src/portal/src/i18n/lang/zh-tw-lang.json

Add tips for "Other events"

---

.gitignore
src/controller/event/topic.go

Add operation description for delete tag event

---

src/common/models/oidc_user.go
src/lib/orm/metadata.go
src/lib/orm/metadata_test.go
src/lib/orm/query.go
src/pkg/reg/dao/model.go
src/pkg/robot/model/model.go
src/pkg/user/dao/user.go

the orm Filterable function always return true even set the tag of the field as false
Fixes #(issue)

fix orm filterable issue

---

src/portal/src/app/base/project/repository/artifact/artifact-common-properties/artifact-common-properties.component.scss

- Simple CSS change to fix overflow.
Fixes #21776 
Also fixes #21784 

Fix: Modelfs overflow in UI.

---

src/pkg/audit/forward.go
src/pkg/auditext/manager.go

skip to log error message when log endpoint is emtpy
Fixes #(issue)

Add operation_descrtion when forward audit log

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts
src/portal/src/app/base/project/repository/artifact/artifact.ts

- Remove top copy pull command button
Fixes #21781 

Remove top copy pull cmd button

---

Makefile

Bump up trivy and trivy-adapter to fix CVE

---

src/pkg/auditext/event/login/login.go
src/pkg/auditext/event/login/logout.go
src/pkg/auditext/event/login/logout_test.go
src/pkg/auditext/event/login/oidclogout.go

Rule out the duplicate login event and false logout event for oidc

---

.buildbaselog

build base images for v2.13

---

.github/workflows/publish_release.yml

Test the flow for signing the offline installer

---

.github/workflows/publish_release.yml

Release sign package

---

src/portal/app-swagger-ui/package-lock.json
src/portal/app-swagger-ui/package.json
src/portal/package-lock.json

[cherry-pick] Update dependencies in Harbor UI

---

.buildbaselog

build base for v2.13

---

make/photon/prepare/templates/jobservice/env.jinja

[cherry-pick]fix jobservice container loglevel consistent with job_log

---

make/photon/prepare/templates/jobservice/env.jinja

Fixes https://github.com/goharbor/harbor-helm/issues/2166

fix jobservice container loglevel consistent with job_log

---

.buildbaselog

build base for v2.12.3

---

src/server/v2.0/handler/repository.go

update artifact info

---

src/server/v2.0/handler/repository.go

[cherry-pick] Update artifact info

---

Makefile

Decouple the lint from the api generation step in the makefile.
Fixes #(issue)

revise make file for lint api

---

tests/e2e_setup/README.md

Add missing step in e2e pipeline setup

---

src/server/v2.0/handler/scanexport.go

Remove the error check never happen

---

.github/workflows/nightly-trivy-scan.yml

update trivy scan branch

---

src/lib/orm/query.go

the query parameter cannot contains orm.ExerSep which is key characters that used by orm. the pull request enhances the validation for query parameters.
Fixes #(issue)

enhance the query judgement

---

src/pkg/scan/postprocessors/report_converters.go

Update the severity, fixed version and cvss_score_v3

---

.buildbaselog

build base for patch release

---

Makefile

Decouple the lint from the api generation step in the makefile.
Fixes #(issue)

[cherry-pick]revise make file for lint api

---

.buildbaselog
Makefile

bump up the base image for v2.12.3

---

Makefile

change python ./setup.py install to pip install . because deprecated

---

Makefile

Pin trivy adapter to v0.32.4

---

src/portal/src/app/base/left-side-nav/clearing-job/gc-page/gc/gc-history/gc-history.component.ts

Display gc progress information in running state

---

.buildbaselog

build base images for v2.13.1

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts

Fix: Helm Chart Copy Button in UI

---

src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.html
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.spec.ts
src/portal/src/app/base/project/repository/artifact/artifact-list-page/artifact-list/artifact-list-tab/pull-command/pull-command.component.ts

[cherry-pick] Fix: Helm Chart Copy Button in UI

---

Makefile

Bump up Trivy adapter for v2.13.x

---

Makefile

Pin trivy adapter to the GA version v0.33.1

---

.buildbaselog

build base images for v2.13.0

---

src/go.mod
src/go.sum

downgrade gorilla go mod version

---

.github/workflows/CI.yml

This pull request includes a minor update to the `.github/workflows/CI.yml` file to fix a configuration issue with the Codecov action. The change updates the `file` parameter to the correct `files` parameter in two places, ensuring compatibility with the Codecov action's expected input.
CI workflow configuration updates:
* [`.github/workflows/CI.yml`](diffhunk://#diff-3ab46ee209a127470fce3c2cf106b1a1dbadbb929a4b5b13656a4bc4ce19c0b8L94-R94): Changed `file` to `files` in the Codecov configuration for the backend coverage report (`profile.cov`) to align with the expected parameter name.
* [`.github/workflows/CI.yml`](diffhunk://#diff-3ab46ee209a127470fce3c2cf106b1a1dbadbb929a4b5b13656a4bc4ce19c0b8L336-R336): Changed `file` to `files` in the Codecov configuration for the UI coverage report …

chore: fix the arguments for codecov v5

---

tests/resources/Harbor-Util.robot

Update robot case for get harbor version with credential.(behavior changed since https://github.com/goharbor/harbor/pull/21672)

update robot case for get harbor version

---

CHANGELOG.md
RELEASES.md
ROADMAP.md

This PR fixes minor errors and grammatical mistakes in CHANGELOG.md , RELEASES.md and ROADMAP.md. This enhances readability and avoids confusion.

Update CHANGELOG.md, RELEASES.md and ROADMAP.md

---

api/v2.0/swagger.yaml

Some useful code response is lacked and now add it to make it more convenient to distinguish the error type.
Fixes #(issue)

Add 400 code response in swagger.yaml for updateRegistry updateReplicationPolicy and headProject

---

src/pkg/scan/postprocessors/report_converters.go

Set Fix and CVE3Score in VulnerabilityRecord from VulnerabilityItem.
Follow-up of https://github.com/goharbor/harbor/pull/21915
Fixes https://github.com/goharbor/harbor/issues/21463

Update FixVersion and ScoreV3

---

.buildbaselog
CONTRIBUTING.md
Makefile
src/go.mod
tests/ci/distro_installer.sh

update go and base image

---

tests/ci/build_util.sh

Display download url for BUILD_PACKAGE action

---

tests/ci/build_util.sh

[cherry-pick] Display download url for BUILD_PACKAGE action

---

src/lib/orm/query.go

to extend the enhancement from https://github.com/goharbor/harbor/pull/21924 to fuzzy and range match. After the enhance, the orm.ExerSep is not supported in any sort of query keywords.
Fixes #(issue)

update the orm filter func

---

CONTRIBUTING.md
Makefile
src/go.mod
tests/ci/distro_installer.sh

to the latest golang version v1.24.5 from v1.24.3
Fixes #(issue)

bump golang version

---

api/v2.0/swagger.yaml

Add HTTP 409 error when creating robot account

---

src/controller/artifact/processor/cnai/parser/base.go
src/controller/artifact/processor/cnai/parser/base_test.go
src/controller/artifact/processor/cnai/parser/license.go
src/controller/artifact/processor/cnai/parser/license_test.go
src/controller/artifact/processor/cnai/parser/readme.go
src/controller/artifact/processor/cnai/parser/readme_test.go
src/go.mod
src/go.sum

This pull request introduces enhancements to the artifact parsing logic, adds support for new media types, and updates dependencies. The most significant changes include the addition of a new `decodeContent` function for handling multiple file formats, updates to license and README parsers to support raw media types, and modifications to the test cases to validate these updates.
* Added `decodeContent` function in `src/controller/artifact/processor/cnai/parser/base.go` to handle multiple file formats (`.tar` and `.raw`) based on the media type. Updated the `Parse` method to use this new function.
* Defined constants for file formats (`formatTar` and `formatRaw`) to improve readability and maintainability.
* Updated `license` and `readme` parsers to support `MediaTypeModelDocRaw` in …

feat: support raw format for CNAI model

---

src/server/v2.0/handler/auditlog.go
src/server/v2.0/handler/base.go
src/server/v2.0/handler/project.go

The tag retention job failed with 403 error message

---

.buildbaselog

bump base images for v2.14.0

---

tests/robot-cases/Group1-Nightly/Replication.robot

Remove gitlab replication

---

tests/robot-cases/Group1-Nightly/Replication.robot

Remove GCR replication because GCR account is removed

---

Makefile

Bump up trivy to 0.66.0 and pin trivy-adapter to 0.34.0

---

.buildbaselog

bump base images for v2.14.0-rc2

---

tests/robot-cases/Group1-Nightly/P2P_Preheat.robot

Remove p2p preheat by event testcase
