goharbor/harbor

- Deploy/config/nginx/nginx.https.conf
- Deploy/docker-compose.yml
- docs/configure_https.md
add cert directory and nginx.https.conf file to Deploy/config/nginx/
> Configure Harbor with HTTPS Access

- service/utils/registryutils.go
Listing repository tags will fail if the repository name contains string
'service'
Fixed in registryutils.go. Use regrexp instead of splitting strings by
'service'.
> Fix bug: Failed to get repository tags

- Deploy/harbor.cfg
- Deploy/prepare
- Deploy/templates/ui/app.conf
- docs/installation_guide.md
- utils/mail.go
Some mail service providers use ssl connection to send/receive emails.
Had test with tencent's enterprise mail success: **smtp.exmail.qq.com:465**
> add ssl support for send email

- static/resources/js/project.js
Fixes the issue with the "undefined" fields in admin tab:
before:
after:
> Fixed issue with undefined values in admin tab

- docs/swagger.yaml
1 op_time definition: string <- time
2 no useful definitions 'repository'
no error on online check now
> fix swagger.yml online check issue

- docs/swagger.yaml
The "name" field of Project's properties in swagger.yaml,
but "POST" Project API use parameter "project_name".
> Fixed Project describe "name" field  error in swagger.yaml

- Deploy/templates/ui/env
- utils/registry/auth/tokenauthorizer.go
1. record the local time when token is issued to avoid the mismatch of time for client and registry 2.recover the env variable
> Expire time of cached token

- make/common/templates/ui/app.conf
- make/harbor.cfg
- make/prepare
- src/common/utils/mail.go
The identity field parameter passed to smtp.SendMail is now
configurable instead of being hardcoded to 'Mail Config'.
This fixes issue #900
> Make mail identity configurable

- src/ui/service/token/authutils.go
This commit solves the issue related on #1012 
Basically, instead of verifying if there is a '/' character on the a.Name variable, it's applied a split function on this string with the '/' character, then verifying the size of array.
Being bigger than 1, it verifies if the array is bigger than 3 (like privaterepo.com/rpkatz/debian) and getting only the 2nd item from array (rpkatz), otherwise (as being smaller than 3, and bigger than 1, like rpkatz/debian) it gets the first item of the array.
> Improves namespace validation for Docker Notary integration

- src/common/utils/registry/repository.go
To fix the frequent timeout issue during recent testing.
Will revisit the transport initialization code to tune the different timeouts.
> remove timeout for replicating large image

- make/photon/log/Dockerfile
This change mitigate problems with container restarts (stop, start) or automatic restart after host machine restart. Rsyslogd strictly checks existence of its pid file and won't start if such one exists.
> remove rsyslogd.pid before start to allow container restarts

- make/common/templates/nginx/nginx.http.conf
- make/common/templates/nginx/nginx.https.conf
- src/ui/api/repository.go
1. Fix issue: deleting repo action will fall in deadlock between two Harbor if they are configured to sync to each other #1222 
2. Filter notification request in nginx
> Fix sync deadlock and filter notification

- src/ui/api/project.go
name rule:
https://github.com/docker/distribution/blob/master/docs/spec/api.md#overview
...
The rules for a repository name are as follows:
1. A repository name is broken up into path components. A component of a repository name must be at least one lowercase, alpha-numeric characters, optionally separated by periods, dashes or underscores. More strictly, it must match the regular expression [a-z0-9]+(?:[._-][a-z0-9]+)*.
2. If a repository name has two or more path components, they must be separated by a forward slash ("/").
3. The total length of a repository name, including slashes, must be less than 256 characters.
...
> fix project name length and follow docker project name rule

- docs/installation_guide.md
This solved the "[ERROR] [password.go:83]: Send email failed: 555 5.5.2 Syntax error. b192sm9510409pga.30 - gsmtp" error.
> Added escape for angle brackets in email_from

- make/docker-compose.tpl
The background is, I'll use "extends" to extend the harbor template to harbor+notary template, and add different group of containers in different networks. 
So I add the default network so I can append other networks to container like harbor-ui and nginx.
> Add a default network in docker compose template.

- make/common/templates/nginx/nginx.https.conf
- make/common/templates/notary/server-config.json
- src/ui/service/token/creator.go
- src/ui/service/token/token_test.go
User will have to set the env var like this:
DOCKER_CONTENT_TRUST_SERVER=https://10.117.4.142/notary
> fix the 'v2' URL conflict issue, and remove the workaround

- make/docker-compose.tpl
allow Harbor to run when dockerd is running with --selinux-enabled
example AVC denials:
type=AVC msg=audit(1488384855.681:154671): avc:  denied  { read } for  pid=454 comm="registry" name="config.yml" dev="dm-8" ino=12583048 scontext=system_u:system_r:svirt_lxc_net_t:s0:c298,c958 tcontext=system_u:object_r:default_t:s0 tclass=file
type=AVC msg=audit(1488384855.681:154671): avc:  denied  { open } for  pid=454 comm="registry" path="/etc/registry/config.yml" dev="dm-8" ino=12583048 scontext=system_u:system_r:svirt_lxc_net_t:s0:c298,c958 tcontext=system_u:object_r:default_t:s0 tclass=file
type=AVC msg=audit(1488384855.687:154672): avc:  denied  { append } for  pid=350 comm=72733A6D61696E20513A526567 name="registry.log" dev="dm-5" ino=4315920 …
> label volumes for SELinux

- .gitignore
- src/ui_ng/src/app/config/auth/config-auth.component.html
- src/ui_ng/src/app/config/config.component.ts
remove ‘required’ flag from 'searchDN and search password' of ldap
> remove ‘required’ flag from 'searchDN and search password' of ldap

- src/common/utils/email/mail_test.go
test is broken due to security process change in gmail.
> bypass some email test

- make/common/templates/nginx/nginx.http.conf
- make/common/templates/nginx/nginx.https.conf
- src/ui/controllers/controllers_test.go
- src/ui/controllers/proxy.go
- src/ui/main.go
- src/ui/proxy/proxy.go
- src/ui/router.go
A reverse proxy is added as a controller on harbor ui.  Interceptors will be added to the proxy handler to block unsigned and vulnerable images according to project policies.
> create reverse proxy

- tests/generateCerts.sh
The web server's cn name should be different with the CA's common name
other wise we cannot view the harbor UI if we use this script to create
certificate.
> Fix common name issue.

- make/docker-compose.clair.yml
When run clair full scan it will take more than 60% percent of CPU if no limit
this change to limit clair to use at most 1.5cpu
We can this it to cpus when we move to docker compose3.0
> Limit clair resource

- src/ui/filter/security.go
- src/ui/filter/security_test.go
1. only apply security filter to /api/ and /service/ 
2. support basic auth for deleting repository and tag in integration mode
> Apply security filter to certain patterns and enable basic auth for deleting repo

- contrib/sdk/harbor-py/README.md
- contrib/sdk/harbor-py/setup.py
harbor-py requires the requests package, but because it's not specified in `setup.py`, pip doesn't know about it and won't install it as a dependency. This fixes that.
While we're here, let's update the URLs in `setup.py` and `README.md` to point to harbor-py's new location in the main harbor git repo.
> Correct harbor-py dependencies & URLs

- make/pushimage.sh
Just a quick fix for the pushimage.sh file.
The $REGISTRY variable was created but not used in the `docker login` instruction.
> use $REGISTRY instead of $4

- make/common/templates/nginx/nginx.http.conf
- make/common/templates/nginx/nginx.https.conf
When host in low disk status, enable the buffer will cause upload error.
> disable nginx buffer

- docs/user_guide.md
In user_guide.md, Content trust paragraph does't  has enough  information of pushing images.
In this commit, I added the description of notary's ''Passphrase``.
> Add the discription of notary in User Guide

- contrib/Configure_mirror.md
P.S. I update only the last link, but GitHub editor saved others lines also, which I thought is fine though.
> fix docker docs link

- contrib/sdk/harbor-py/harborclient/harborclient.py
Per python logging best practices, modules shouldn't set the global logging level and should log with a named logger matching the module. This allows the application to control the logging.
> Fix harborclient module logging

- make/common/mariadb/Dockerfile
- make/common/nginx/Dockerfile
- make/common/postgresql/Dockerfile
- make/photon/adminserver/Dockerfile
- make/photon/jobservice/Dockerfile
- make/photon/log/Dockerfile
- tools/migration/Dockerfile
Refine the Dockerfile to remove temporary workarounds.
Also fixes #3587, to make sure the configuration files of rsyslog can be
read by uid 10000.
> Refine the Dockerfile

- make/photon/clair/docker-entrypoint.sh
Clair will call bzr, without -H in sudo it will use root user's
Home envrionment.
> Fix clair permission issue

- src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.html.ts
- src/ui_ng/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
- src/ui_ng/lib/src/service/endpoint.service.ts
- src/ui_ng/lib/src/service/interface.ts
- src/ui_ng/package.json
Fix issue about test connection with wrong password in endpoint
Fix bug about inline alert undisappear
> Fix issue about endpoint test connection #3661

- tests/apitests/api-testing/client/harbor_api_client.go
- tests/apitests/api-testing/envs/environment.go
If the 'http_proxy' or 'HTTP_PROXY' env variable is set when protocol is 'http', the testing API client will use that url as proxy settings.
If the 'https_proxy' or 'HTTPS_PROXY' env variable is set when protocol is 'https', the testing API client will use that url as proxy settings.
> [SKIP CI] add proxy settings to the API client for the api-testing part

- make/common/templates/adminserver/env
- make/harbor.cfg
- make/prepare
- src/adminserver/systemcfg/systemcfg.go
- src/common/const.go
- src/common/models/uaa.go
- src/common/utils/test/adminserver.go
- src/ui/auth/uaa/uaa.go
- src/ui/config/config.go
- src/ui/config/config_test.go
- tests/coverage4gotest.sh
Remove the attribute "uaa_ca_root" from harbor.cfg and introduce
"uaa_verify_cert".  Similar to LDAP settings, this allow user to
explicitly turn off the cert verification against UAA server, such that
the code will work with self-signed certificate.
> Refactor the configuraiton of UAA

- make/docker-compose.tpl
- make/harbor.cfg
- make/prepare
- src/common/utils/uaa/client.go
- src/common/utils/uaa/client_test.go
- src/ui/auth/uaa/uaa.go
Enable configuring the path of root cert of UAA in harbor.cfg.  It only
takes effects if the verify_cert is set to "true" If the file does not
exist, the configuration is skipped.
The intention for this commit is to support integration with nested UAA
in PAS or PKS, we don't expect user to manually configure this value,
though he can do it if he wants.
> Enable configuring the CA Certificate for UAA

- src/common/const.go
- src/common/dao/dao_test.go
- src/common/dao/user.go
- src/ui/api/internal.go
- src/ui/auth/authenticator.go
- src/ui/controllers/controllers_test.go
- src/ui/router.go
This is to provide a workaround for very corner case that in user's
authentication backend (LDAP, UAA) has a user called "admin" and because
Harbor's super user is hard coded to "admin" it's not possible to login
the "admin" with credentials in LDAP or UAA.
To minimize the impact, we'll provide an internal API for user to update
the super user's username from "admin" to "admin@harbor.local", this API
can be called by "admin" only, and is not reversible.
> Provide API to rename admin

- make/docker-compose.tpl
As this is for tile deployment only, so add a shortcut for tile/bosh
script to add entry in /etc/hosts inside the container.
Due to effort consideration I don't think we want to render
docker-compose in `prepare` script.
> Add place holder for injecting UAA host

- src/ui/auth/auth_test.go
- src/ui/auth/authenticator.go
- src/ui/auth/db/db.go
- src/ui/auth/ldap/ldap.go
- src/ui/auth/ldap/ldap_test.go
- src/ui/auth/uaa/uaa.go
There has been inconsistency in terms of the error returned by
authenticator.
This commit introduces an error ErrAuth to explicitly flag an
authentication failure, which should be treated as user error such
as "invalid credentials", and other errors will be treated as system error.
> WIP: Refine error returned by Authenticator

- .drone.yml
- CONTRIBUTING.md
This is a temporary workaround for external PR builds.
> Add ability to skip check membership on CI

- make/common/templates/jobservice/app.conf
- make/common/templates/jobservice/config.yml
- make/common/templates/jobservice/env
- make/docker-compose.tpl
- make/photon/jobservice/Dockerfile
- make/photon/jobservice/start.sh
- make/prepare
This commit doesn't integrate redis.  No change to makefile b/c it
should work once the temporary jobservice_v2 folder is renamed to jobservice.
> Integrate new jobservice into docker-compose template

- contrib/helm/harbor/templates/registry/registry-ss.yaml
Error: YAML parse error on harbor/templates/registry/registry-ss.yaml: error converting YAML to JSON: yaml: line 63: did not find expected key
> fix to yaml parse error causing Helm check failure

- make/photon/db/registry.sql
- make/photon/db/registry_sqlite.sql
- tools/migration/db/changelog.md
We have to add the uuid/id mapping as new job service will only store uuid.
Further work is in feature branch for now, commit this change to
accelerate migration work.
> Update SQL script to add uuid to job tables.

- src/ui_ng/lib/src/tag/tag.component.ts
When an image has a size greater than1GB, rendering shows the correct size in GB but with a MB suffix.
> fix size suffix label for >1GB images

- src/ui/filter/readonly.go
- src/ui/proxy/interceptor_test.go
- src/ui/proxy/interceptors.go
The output is,
The push refers to a repository [myregistry/library/busybox]
123abc123abc: Preparing 
denied: Upload/Delete is prohibited in read only mode.
> Bypass docker client retry on push in readonly mode

- src/ui/filter/readonly.go
The pull request is to fix "Error unhandled" issue got by gas code scan, log the error and let the response body empty but with 503 in header.
The code scan results list in #vmware#4612
> Log error when to write response body in readonly filter

- make/common/templates/adminserver/env
- make/common/templates/ui/env
To set the release default log level of adminserver and ui to info instead of debug, this will help to reduce log size and the redundant message.
> Update harbor default log level to info

- contrib/helm/harbor/Chart.yaml
- contrib/helm/harbor/README.md
- contrib/helm/harbor/templates/ingress/secret.yaml
- contrib/helm/harbor/values.yaml
fix for https://github.com/vmware/harbor/issues/4644
default behavior is the same as before ie: auto-generated
> Helm chart: added tls certificate generation toggle

- src/common/security/admiral/authcontext/authcontext.go
Fix bug: the user can push images although he have no permisson by checking empty value before assign permissions.
> Fix bug #4688

- src/jobservice/job/impl/logger/job_logger.go
An interface value is nil only if the inner value and type are both unset, (nil, nil). In particular, a nil interface will always hold a nil type. If we store a nil pointer of type *int inside an interface value, the inner type will be *int regardless of the value of the pointer: (*int, nil). Such an interface value will therefore be non-nil even when the pointer inside is nil.
> Return the logger.Interface instead of the pointer of logger to avoid nil checking issue

- make/common/templates/notary/server-config.json
- make/docker-compose.clair.tpl
- make/docker-compose.notary.tpl
- make/photon/clair/docker-entrypoint.sh
- make/photon/jobservice/start.sh
- make/photon/notary/server-start.sh
- make/photon/notary/signer-start.sh
- make/photon/registry/entrypoint.sh
- make/photon/ui/start.sh
- make/prepare
- src/common/utils/notary/helper.go
- src/ui/config/config.go
- src/ui/config/config_test.go
- src/ui/service/token/authutils.go
- tests/testprepare.sh
This commit fixes a recently discovered issue on Kubernetes #4496
It make necessary to avoid calling `chown` to config files during the
bootstrap of the containers.
> Do not call `chown` to config files

- contrib/helm/harbor/README.md
- contrib/helm/harbor/templates/NOTES.txt
- contrib/helm/harbor/templates/_helpers.tpl
- contrib/helm/harbor/templates/adminserver/adminserver-cm.yaml
- contrib/helm/harbor/templates/ingress/ingress.yaml
- contrib/helm/harbor/templates/ingress/secret.yaml
- contrib/helm/harbor/templates/notary/notary-cm.yaml
- contrib/helm/harbor/templates/notary/notary-db.yaml
- contrib/helm/harbor/templates/notary/notary-server.yaml
- contrib/helm/harbor/templates/notary/notary-signer.yaml
- contrib/helm/harbor/templates/notary/notary-svc.yaml
- contrib/helm/harbor/values.yaml
Assuming Harbor FQDN is specified as harbor.my.domain by the user,
the Notary server FQDN will be set to notary-harbor.my.domain.
So the user must point both Harbor FQDN and Notary FQDN to the K8s
ingress controller IP in the DNS server.
Fix issue https://github.com/vmware/harbor/issues/4394
> [Chart] Add support for deploying Notary

- src/common/models/pro_meta.go
- src/common/utils/clair/utils.go
- src/common/utils/clair/utils_test.go
Currently "Critical" vulnerablity is treated as "Unknown" in Harbor.
This commit provides a quickfix that it will be interpret as "High".  In
future, we should consider introduce "Critical" and enable UI to handle
it to be more consistent with CVSS spec.
> Cherry-pick: Fix mis-interpretation of severity in Clair

- src/common/models/pro_meta.go
- src/common/utils/clair/utils.go
- src/common/utils/clair/utils_test.go
This partially fix the issue #4776 
Currently "Critical" vulnerablity is treated as "Unknown" in Harbor.
This commit provides a quickfix that it will be interpret as "High".  In
future, we should consider introduce "Critical" and enable UI to handle
it to be more consistent with CVSS spec.
> Fix mis-interpretation of severity in Clair

- src/ui_ng/src/app/shared/list-repository-ro/list-repository-ro.component.ts
Fix issue #3852, After global search result returned if you research another item, the content will not refresh.
> Fix bug on search result ui

- docs/swagger.yaml
- src/ui/api/projectmember.go
- src/ui/api/projectmember_test.go
- src/ui/auth/authenticator.go
When adding a project member, if the user/group is not found in database or LDAP, it should return 404 instead of 500 so that the UI can display error message
> Return 404 if user is not found

- make/photon/db/registry.sql
- make/photon/db/registry_sqlite.sql
- src/common/dao/label_test.go
- tools/migration/db/db_meta.py
Add unique constraint to column name, scope and project_id  of table harbor_label to make creating same name labels under different projects valid
> Modify unique constraint of table harbor_label

- make/photon/db/postgresql/registry.sql
Add unique constraint to column name, scope and project_id of table harbor_label to make creating same name labels under different projects valid
> Modify unique constraint of table harbor_label in pgsql

- src/ui/api/replication_policy.go
When checking the jobs of the rule which are going to be deleted, only get the transfer and delete jobs.
> Fix bug #4819: the scheduled rule can not be removed

- src/ui/api/replication_policy.go
When checking the jobs of the rule which are going to be deleted, only get the transfer and delete jobs.
> Cherry pick: Fix bug #4819: the scheduled rule can not be removed

- make/docker-compose.tpl
- make/photon/redis/redis.conf
Previously the log file was set to a hard coded file, but given this
redis should run in container, the update is made to have the process
output log messages to standard output, and redirect it to syslog in
docker-compose template.
> Collect log of redis

- make/docker-compose.tpl
- make/photon/redis/redis.conf
Previously the log file was set to a hard coded file, but given this
redis should run in container, the update is made to have the process
output log messages to standard output, and redirect it to syslog in
docker-compose template.
> Collect log of redis - cherrypick to 1.5 branch

- tools/migration/cfg/migrator_1_5_0/__init__.py
as the default value of redis_url in the harbor.cfg has changed, so we need to leverage the value into the migrator
> Add default value for redis_url in v1.5.0 migrator

- tools/migration/cfg/migrator_1_5_0/__init__.py
The value of these attributes should be overwritten due to change in jobservice implementation.
> Overwrite values of 'redis_url' and 'max_job_workers'

- contrib/helm/harbor/templates/registry/registry-cm.yaml
- contrib/helm/harbor/values.yaml
Just a simple add on to allow using redis for blob caching in the registry.
Currently this would be an existing redis...
> Add redis cache support for registry pod

- tests/resources/Nightly-Util.robot
Remove the notary-db and clair-db logs files, and change the mysql.log to postgresql.log. There changes are align with the Harbor DB migration, otherwise, the nightly will fail by collecting logs in the tear down phase.
> Modify harbor log files name to align with latest change

- tests/resources/Harbor-Util.robot
To investigate the failure on LDAP test case in drone CI, it needs to log the output of shutting down Harbor, then to analyse the root cause.
> Dump log of shutting down harbor in CI

- docs/swagger.yaml
Parameters include:
ldap_group_attribute_name
ldap_group_base_dn
ldap_group_search_filter
ldap_group_search_scope
**Test**
1.Prepare swagger env by https://github.com/vmware/harbor/blob/10199c10efe5dff3479ddc174e287b34cb39b306/docs/configure_swagger.md
2.Testing the ldap_group related configuration update/reset with payload
{
"ldap_group_attribute_name":"uid",
"ldap_group_base_dn":"ou=group,dc=example,dc=com",
"ldap_group_search_filter":"objectclass=groupOfNames",
"ldap_group_search_scope":1
}
3. Check the get API can get the updated value.
4. Check the reset API can reset it to the default value.
> Update swagger.yaml to add ldap group config parameters

- src/common/dao/dao_test.go
- src/common/dao/group/usergroup.go
- src/common/dao/group/usergroup_test.go
- src/common/dao/project.go
- src/common/dao/project/projectmember.go
- src/common/dao/project/projectmember_test.go
- src/common/dao/project_test.go
- src/common/dao/testutils.go
- src/common/models/project.go
- src/common/models/user.go
- src/common/security/admiral/context_test.go
- src/common/security/context.go
- src/common/security/local/context.go
- src/common/security/local/context_test.go
- src/ui/api/project.go
- src/ui/auth/ldap/ldap.go
- src/ui/auth/ldap/ldap_test.go
- src/ui/promgr/pmsdriver/local/local.go
- tests/testprepare.sh
The project list will contain all public projects, user is a member of this project, or user is in the group which is a member of this projects.
Change the behaviour of user roles, if the user is not a member of this project, then return the user's groups role of current project
>  Update security context for assign role to project group member

- make/prepare
The job logs directory's permission is not changed by prepare script
because the everything is moved from /data to /storage/data on VIC
appliance.  This commit will make sure both cases the directory is
readable by user 10000:10000.
This PR also makes sure the config json of notary signer has 0644
permission.
> Fix permission issue on VIC appliance

- src/ui/auth/uaa/uaa.go
- src/ui/auth/uaa/uaa_test.go
This is a fix to #4895.
Currently the user data will not be populated correctly after a user in
UAA is logged in.  This problem is fixed in this commit.
> Sync user info after UAA user is logged in

- src/jobservice/job/impl/context.go
- src/jobservice/main.go
- src/jobservice/runtime/bootstrap.go
Return none zero code when job service exit with an error
Add retry when getting configs from admin server failed
> Improve the error handling capabilities of job service

- src/ui/auth/uaa/uaa.go
- src/ui/auth/uaa/uaa_test.go
This is a fix to #4895.
Currently the user data will not be populated correctly after a user in
UAA is logged in.  This problem is fixed in this commit.
> Sync user info after UAA user is logged in - cherry pick to 1.5 branch

- contrib/helm/harbor/templates/notary/notary-cm.yaml
- contrib/helm/harbor/templates/notary/notary-server.yaml
K8s 1.10 throws error when mounting a file into the directory which
is also mounted from a ConfigMap.
Fix issue https://github.com/vmware/harbor/issues/4886
> [Chart] Fix a ConfigMap mount issue in K8s 1.10

- src/ui/api/ldap.go
Some user requires return json format message in 404 when importing not exist LDAP users
> Fix issue of import LDAP user 404 message

- make/photon/adminserver/start.sh
Narrow down the scope of `chown` in adminserver because the
/etc/adminserver/config/ is the location to store the config.json file.
And /etc/adminserver/key should be readonly.
> chown only to the folder to store the config.json

- src/ui_ng/lib/package.json
- src/ui_ng/lib/src/endpoint/endpoint.component.ts
- src/ui_ng/lib/src/list-replication-rule/list-replication-rule.component.ts
- src/ui_ng/lib/src/replication/replication.component.ts
- src/ui_ng/lib/src/repository-gridview/repository-gridview.component.ts
- src/ui_ng/lib/src/service/project.service.ts
- src/ui_ng/lib/src/tag/tag.component.ts
- src/ui_ng/lib/src/vulnerability-scanning/result-bar-chart.component.ts
- src/ui_ng/package.json
Because new version of rxjs you need import each function manually, update code to avoid related errors.
Issues #4923 #4904 are caused by this problem.
> Fix 'xxx' is not a function err

- docs/swagger.yaml
- src/replication/models/filter.go
- src/replication/models/filter_test.go
- src/replication/policy/manager.go
- src/ui/api/models/replication_policy.go
- src/ui/api/replication_policy.go
- src/ui/api/replication_policy_test.go
The label filter can be used to filter images when do the replication, this commit provides the filter in replication policy
> Add label filter in replication policy API

- src/common/utils/registry/repository.go
- src/common/utils/registry/repository_test.go
The location header returned by the remote registry contains no scheme and host parts if "relativeurls" is enabled,
this commit fix it by adding them at the beginning of location.
> Fix replication issue when the remote registry enables relativeurls

- docs/swagger.yaml
- make/photon/db/registry.sql
- src/common/dao/label.go
- src/common/dao/label_test.go
- src/common/models/label.go
- src/ui/api/label.go
- src/ui/api/replication_policy.go
- src/ui/api/replication_policy_test.go
- tools/migration/db/changelog.md
Modify the deletion of label to soft deletion, in this way the names of deleted labels referenced by replication rules can be shown to users
> Soft delete label

- make/prepare
The secretkey file will be loaded by adminserver which is run by non-root
user (uid:10000) previously the entrypoint script will run `chown` to a
lot files, and there's a breakage in upgrade when we skip running
`chown` inside container.
This commit will fix the issue during upgrade by changing the owner of
the secretkey file.
> Change owner of the file secretkey in prepare.

- tools/migration/db/run.sh
- tools/migration/db/util/mysql_pgsql_1_5_0.sh
- tools/migration/db/util/pgsql.sh
this commit to fix issue https://github.com/vmware/harbor/issues/5097, add the clair data migration.
[Usage]:
docker run -it -e DB_USR=root -e DB_PWD=${pwd} -v /data/database/:/var/lib/postgresql/data -v /data/clair-db/:/clair-db vmware/harbor-migrator:dev --db up
[Limitation]
For clair migration, there is a necessary precondition that you should not launch harbor before doing it, otherwise the migrator will give a waring message and stop the process.
> Add clair data migration in DB migrator

- src/common/dao/label.go
- src/common/dao/label_test.go
- src/common/models/label.go
- src/ui/api/label.go
- src/ui/api/label_test.go
This commit provides the support of fuzzy matching for label name when listing labels
> Fix #4742: fuzzy match label name

- src/ui/api/usergroup.go
Not to create the LDAP user group again or update the user group name.
> If group already exist return 409 when adding a LDAP user group

- make/prepare
This commit fixes #5053.
It removes the usage of `string.strip` which will fail in python3.
> Fix failure of running prepare with python3

- contrib/helm/harbor/templates/_helpers.tpl
- contrib/helm/harbor/templates/notary/notary-cm.yaml
- contrib/helm/harbor/templates/registry/registry-cm.yaml
- contrib/helm/harbor/templates/registry/registry-ss.yaml
- contrib/helm/harbor/values.yaml
Provide more flexibility for ingress controller setting.  When the
ingress controller is not exposing 80/443 port, user can set `externalPort` to expose the endpoint of Harbor.
> Add externalPort in values.yaml

- src/ui/api/replication_job.go
- src/ui/api/scan_job.go
Parse the error got from jobservice, and return the corresponding HTTP code if it's a HTTP error to caller
> Parse the error got from jobservice, fix #5047

- contrib/helm/harbor/templates/ui/ui-dpl.yaml
This commit fixes #5138.  A volume references the secret will be mounted
to the UI pod, so the user can download the CA cert from UI.
> Enable CA cert download on Chart deployment

- contrib/helm/harbor/README.md
- contrib/helm/harbor/templates/ingress/ingress.yaml
- contrib/helm/harbor/values.yaml
If you are on other kubernetes distros like Openshift, you shouldn't use Ingress.
> Helm: Options to disable ingress objects

- make/common/templates/adminserver/env
- make/harbor.cfg
- make/prepare
- src/adminserver/systemcfg/systemcfg.go
- src/adminserver/systemcfg/systemcfg_test.go
- src/common/const.go
- tests/common
If customized settings are matched by skip_reload_pattern in harbor.cfg, then these values are kept in the config store will be unchange after reload_config. This feature is used by harbor tile to reconfigure tile.
> Fix issue that harbor tile can not save customized settings 

- contrib/helm/harbor/templates/ui/ui-dpl.yaml
Its an follow up form: https://github.com/vmware/harbor/pull/5180
Due a rebase https://github.com/vmware/harbor/pull/5185 was new that I didn't see it instantly.
> Helm: Do not mount secret if ingress is disabled

- make/docker-compose.clair.tpl
Fixes #5072
Due to an issue in bzr, Clair container may consume a lot of CPU
resource while updating the vuln data.  This commit mitigates the impact
by setting the cpu_quota of clair container. (default value of
cpu_period is 100000 in v2 docker-compose template)
> Restrict the CPU usage of Clair

- make/common/templates/nginx/nginx.http.conf
- make/common/templates/nginx/nginx.https.conf
this removes the registry upstream in nginx configuration (it is unused since 785298e6b).
> remove unused upstream

- tests/integration.sh
- tests/resources/Util.robot
This commit is to fix the bug introduced by PR https://github.com/vmware/harbor/pull/5207/, which adds the json library but doesn't install it in the E2E engine. The bug will cause an runtime error when to exsecute robot framework. Disable it temporary as the upgrade script havn't added into the nightly test. 
And also make the CI pipeline script to throw error on packing/uploading offline installer, otherwise the latest installer will not be updated by the lastest code change.
> Fix CI pipeline bug on packaging offline installer

- make/prepare
This is a simple replacement to fix the #2920 `install.sh Fail to generate key file` `openssl` issue on recent linux distributions (Debian 9). The solution was first mentioned by @teknologist but apparently nobody did a PR to avoid having to apply manually the workaround.
> Change empty_subj to fix #2920 openssl issue

- make/common/templates/registry/config.yml
- make/common/templates/registry/config_ha.yml
- make/prepare
It gives Harbor the capability to controll the cache of docker
registry, and the workaround for cache invalidation bug caused
by garbage collection, that is clean cache in GC job.
For more details, see Harbor issue #5078.
> Update docker registry cache from inmemory to redis.

- make/photon/redis/Dockerfile
This commit changes the ownership of directory that Redis uses to user redis when starting up
> Fix permission deny issue when Redis starting

- src/chartserver/base_test.go
- src/chartserver/manipulation_handler.go
- src/ui/api/chart_repository.go
- src/ui/router.go
**Add API routes of chart repo services in harbor API router**
- add chart repo API controller
- update GetChartVersion to extract repo name from the request
- update the corresponding UI cases
- update the chart controller initialization process
> Add API routes of chart repo services in harbor API router

- docs/migration_guide.md
Fix the typo of image's name of migrator v 1.2
> Fix images name typo on migration doc

- make/photon/adminserver/Dockerfile
- make/photon/ui/Dockerfile
- src/adminserver/systemcfg/systemcfg.go
- src/common/dao/base.go
- src/ui/main.go
This commit make update to remove the code from ui container to init the
DB schema.  As UI has dependency on admin server, so it's safe to assume
adminserver has to be ready first.  Regardless the setting of the config
store of admin server, it will try to access and intialize the schema of
database.
> Let adminserver initialise the DB schema.

- make/photon/adminserver/Dockerfile
- make/photon/clair/Dockerfile
- make/photon/db/Dockerfile
- make/photon/jobservice/Dockerfile
- make/photon/log/Dockerfile
- make/photon/nginx/Dockerfile
- make/photon/notary/server.Dockerfile
- make/photon/notary/signer.Dockerfile
- make/photon/redis/Dockerfile
- make/photon/registry/Dockerfile
- make/photon/registryctl/Dockerfile
- make/photon/ui/Dockerfile
- tools/migration/Dockerfile
This commit update the base photon image from vmware/photon:1.0 to
photon:1.0, per suggestion by photon team.
> Update photon base images

- contrib/helm/harbor/templates/database/database-ss.yaml
Postgres was complaning about a `lost+found` folder in the data folder. This happens because the volume is directly mounted into the directory `/var/lib/postgresql/data`. This pull request will remove the folder if it exists before the container starts.
Another solution could be to create a subfolder and set the `PGDATA` env to this subfolder, but this will break current deployments.
> Remove lost+found folder in database volume on initial start

- src/chartserver/chart_operator.go
- src/chartserver/client.go
- src/chartserver/manipulation_handler.go
- src/chartserver/repo_handler.go
- src/chartserver/utils.go
- src/ui/api/chart_repository.go
**Fix the multipart form data content missing issue by refill the content again before passing to the backend server**
- refill the multipart form data at harbor API layer
- export write error functions from the chartserver package
- refactor the error format to be compatiable with push plugin
> Fix the multipart form data content missing issue by refill the content again before passing to the backend server

- src/ui_ng/src/app/global-message/message.component.scss
Issue description:
Notification will hide some content when it popup.
According to ux requirement, we should make it not extend to the whole widh of UI, and should not hide the content.
Fix:
Modify the position from 'absolute' to 'relative', so that it will not hide the content.
> Notification should not hide content according to ux

- contrib/helm/harbor/templates/registry/registry-cm.yaml
- contrib/helm/harbor/templates/registry/registry-secret.yaml
- contrib/helm/harbor/templates/registry/registry-ss.yaml
- contrib/helm/harbor/values.yaml
This commit adds the registry storage configuration to the values.yaml. By this way, users can cusomize the storage they use.
> Support the configuration of registry storage in helm chart

- make/harbor.cfg
When proxy is set for Clair, there may be issue when Clair pulls image
from the registryif the `no_proxy` attribute is not updated.  This
commit adds `registry` to the default setting.
> Add registry to default no_proxy hosts for Clair

- make/common/templates/clair/config.yaml
- make/harbor.cfg
- make/prepare
To mitigate the impact we saw in the updater issues in clair, this
commit enable configuring the interval, include disabling the updaters
of clair.
> Enable configuring the interval of clair updaters

- tools/migration/cfg/migrator_1_6_0/__init__.py
- tools/migration/cfg/migrator_1_6_0/harbor.cfg.tpl
In 1.6, there will be only one DB process in the default deployment.
The migrator will try to handle the setting by "guessing" whether Harbor
was pointed to external DB.
Verified 1.5->1.6 and 1.4->1.6 migration.
> Enable cfg migrator to 1.6.0

- make/migrations/postgresql/0001_initial_schema.up.sql
- tools/migration/db/schema/registry_create_tables.pgsql
Root cause: Use default 'now'::timestamp will not generate timestamp for each transaction,
PG will convert now to a timestamp as soon as the constant is parsed. To fix it, update it
to defult CURRENT_TIMESTAMP, thie setting is the same as default now(), which returns the
start time of current transaction because ther are fuction calls, hey will give the desired
behavior of defaulting to the time of row insertion.
Reference: https://www.postgresql.org/docs/9.6/static/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT
PG version: 9.6.9
> Fix pgsql creation column bug

- src/ui_ng/lib/src/_mixin.scss
- src/ui_ng/lib/src/repository-gridview/repository-gridview.component.html
- src/ui_ng/lib/src/repository-gridview/repository-gridview.component.scss
Problem Description:
In the card view of repositories, if the title is long, it can not show all the text.
Fix:
Add css
overflow: hidden;
text-overflow: ellipsis;
word-wrap:break-word;
white-space: nowrap
in mixin files, and tooltip to show all the text.
> Fix Repositories card view title displayed wrong

- contrib/helm/harbor/Chart.yaml
This commit updates the URL of the icon used in Harbor helm chart
> Update the icon used in Harbor chart

- src/common/models/label.go
- src/common/models/pro_meta.go
- src/common/models/project.go
- src/common/models/user.go
- src/common/models/watch_item.go
This commit set the default value of creation_time and update_time to
data objects by adding `orm:add_now` annotations.
> Set default creation_time and update_time at model

- tests/robot-cases/Group11-Nightly/UAA.robot
This commit adds basic test cases to perform when Harbor is configured as
uaa_auth.  It has dependency on an internal UAA server.
> Add UAA e2e test cases

- src/replication/replicator/replicator.go
Set the status of replication job to "error" when the submitting to jobservice fails
> Update job status when failed to submit it

- src/ui_ng/src/app/project/list-project/list-project.component.ts
- src/ui_ng/src/app/shared/shared.utils.ts
Issue description:
In project list page. User click sort according access level, it does not work.
Fix:
Remodify the compare method.
> Fix access level can not sort

- .travis.yml
We used to trigger make install and try to access Harbor in travis.
This is unnecessary as it's run in Drone.  So this commit removes that
chunk from .travis.yml
> Remove BAT from travis.yml

- src/chartserver/chart_operator.go
- src/ui/api/chart_repository.go
**Add 'Deprecated' info for the chart**
- info returned by getting /charts include 'Deprecated' field
- amend error message in the access checking logic
> Add 'Deprecated' info for the chart

- src/ui_ng/lib/src/helm-chart/versions/helm-chart-version.component.ts
- src/ui_ng/src/app/shared/shared.utils.ts
add back getImageLink function
fix issue:upload helm chart can not show backend message.
> Fix helm chart getImageLink was deleted by accident

- make/photon/registryctl/Dockerfile
- tools/migration/Dockerfile
The "|| echo" is the workaround to handle the tdnf install error, it's used for debug only.
> Remove the tdnf error eater in docker files

- Makefile
- tests/integration.sh
This commit is to enable go secure scan in the CI pipeline, it happens at the phase of merging code. The results will be uploaded to /harbor-builds for master and /harbor-release for release-* named as harbor-gosec-results-latest.json
> Add secure go result into CI pipeline

- .drone.yml
- tests/integration.sh
Currently, check-org-membership results in a bash syntax error, which seems to be preventing CI from running.
An incomplete update to the integration testing logic to replace some instances of vmware/harbor with goharbor/harbor to get CI working.
---
For examples of failures this addresses, see:
* https://ci-vic.vmware.com/goharbor/harbor/3/3
* https://ci-vic.vmware.com/goharbor/harbor/7/4
> Fix continuous integration pipeline following move to goharbor org

- tools/migration/cfg/migrator_1_6_0/__init__.py
- tools/migration/cfg/migrator_1_6_0/harbor.cfg.tpl
There's a limitation in the new harbor.cfg file the redis url will be
hard coded to the internal redis instance.  We expect user to manually
edit the .cfg file if he's using a customized redis, this would be a
very rare case.  We'll mention it in the release note of 1.6
> Update CFG migrator to match the new redis setting

- .drone.yml
As for move to goharbor, the CI should not align with any other products. This commit is to remove the step to trigger downstream project vic in Drone CI pipeline, which is a designed step in vmware/harbor repo.
> Remove step to trigger downstream product in CI pipeline

- Makefile
- make/docker-compose.tpl
- make/photon/Makefile
- src/ui/router.go
This is my commit message
Signed-off-by: wangyan <wangyan@vmware.com>
1, remove the API to call registry ctl
2, remove the registryctl image from docker-compose
3, do not package registryctl into offline installer
4, do not compile registryctl binary
> Remove registry controller from release-1.6.0

- Makefile
- make/common/templates/ui/env
- make/prepare
- src/jobservice/job/impl/gc/job.go
- src/ui/api/models/reg_gc.go
- src/ui/api/reg_gc.go
Signed-off-by: wangyan <wangyan@vmware.com>
To workaround the issue: https://github.com/docker/distribution/issues/2094. GC needs to clean cache before to call the docker reigstry api to delete blobs. Otherwise, the following docker push will not be performed as docker registry does not clean cache in GC, it thinks the image is still there, and the new blobs will be uploaded.
> Add clean registry cache to gc job

- src/ui/api/user.go
If current user is in the group defined ldap_group_admin_dn, it doesn't have the harbor admin role.
The current solution only fix the /api/users/currentuser, but for /api/users/:id it can display the real information. see issue #5620 
> Fix issue ldap_group_admin_dn doesn't take effect(master)

- src/jobservice/api/handler.go
- src/jobservice/api/handler_test.go
Add validation to job ID in the API to get job log in job service, to
prevent file path traversal attack.
> Validate job ID when getting job log （cherry-pick to 1.6.0)

- tests/apitests/python/library/Harbor.py
Reload the python path to fix the module not found error in API E2E test
> Fix module not found error in API test

- contrib/helm/harbor/README.md
Fix the losting "|" in the readme of Harbor chart
> Update the readme of Harbor chart

- src/ui/main.go
This commits fixes the "gob: name not registered for interface" error when restarting Harbor by registering models.User
> Fix "gob: name not registered for interface" error

- .gitignore
- make/harbor.cfg
- make/photon/registry/entrypoint.sh
- make/prepare
- tools/migration/cfg/migrator_1_6_0/harbor.cfg.tpl
In some user's environment, there's local object storage hosted with
self-signed certificate.
Because registry process runs in a photon container, it has to trust
the certificate in the photon level such that the registry can access
the storage service.
This commit updates the registry image to append custom cert to the root
bundle when the container is started.  And make the customer cert
configurable in `harbor.cfg`
> Update registry image to enable inject root cert (1.6 cherry pick)

- .gitignore
- make/harbor.cfg
- make/photon/registry/entrypoint.sh
- make/prepare
- tools/migration/cfg/migrator_1_6_0/harbor.cfg.tpl
In some user's environment, there's local object storage hosted with
self-signed certificate.
Because registry process runs in a photon container, it has to trust
the certificate in the photon level such that the registry can access
the storage service.
This commit updates the registry image to append custom cert to the root
bundle when the container is started.  And make the customer cert
configurable in `harbor.cfg`
> Update registry image to enable inject root cert

- src/ui/main.go
This commits fixes the "gob: name not registered for interface" error when restarting Harbor by registering models.User
> [Cherry-pick]Fix "gob: name not registered for interface" error

- make/photon/chartserver/Dockerfile
The VOLUME definition in Dockerfile of chart museum will mount a volume automatically by docker if no specific volume is provided.
> Add VOLUME definition in Dockerfile of chart museum

- make/photon/chartserver/Dockerfile
The VOLUME definition in Dockerfile of chart museum will mount a volume automatically by docker if no specific volume is provided.
> [Cherry-pick]Add VOLUME definition in Dockerfile of chart museum

- src/chartserver/utils.go
- src/chartserver/utils_test.go
**Fix the issue of parsing redis connection address in chart API**
- update logic in func parseRedisConfig
> Fix the issue of parsing redis connection address in chart API

- src/chartserver/utils.go
- src/chartserver/utils_test.go
**Fix the issue of parsing redis connection address in chart API**
- update logic in func parseRedisConfig
- Add UT case for redis addr parsing func
> [cherry-pick] Fix the issue of parsing redis connection address in chart API

- make/harbor.cfg
Set the updater interval to "0" to mitigate the impact of Apline URL
change that cause clair keep polling vuln data.
> Temporarily disable updaters of clair

- make/harbor.cfg
Set the updater interval to "0" to mitigate the impact of Apline URL
change that cause clair keep polling vuln data.
> Temporarily disable updaters of clair -- cherry-pick 1.6

- src/adminserver/systeminfo/imagestorage/driver.go
- src/adminserver/systeminfo/imagestorage/filesystem/driver.go
When run Harbor in MacOS, volume capacity is incorrect due to the use of `statfs`.
Refer to: https://github.com/docker/for-mac/issues/2136
This PR fix: https://github.com/goharbor/harbor/issues/5694
> Fix volume capacity when run in MacOS

- docs/swagger.yaml
- src/common/dao/repository.go
- src/common/models/project.go
- src/common/models/repo.go
- src/ui/api/repository.go
Support repo list sorting.
Add parameter `sort` to API `/api/repositories`. Support sorting based on:
- name
- creation_time
- update_time
Default to name ascending ordering.
Related to issue: https://github.com/goharbor/harbor/issues/5481
> Support repo list sorting

- src/chartserver/chart_operator.go
- src/chartserver/chart_operator_test.go
**Append latest version of the chart when returning the chart list**
- append `LatestVersion` to the `ChartInfo` model
- update the UT case to check the `LatestVersion`
> Append latest version of the chart when returning the chart list

- src/jobservice/models/models.go
- src/jobservice/opm/redis_job_stats_mgr.go
- src/jobservice/opm/redis_job_stats_mgr_test.go
**Return more data of the job when reporting status info via webhook**
- update the status report func `RedisJobStatsManager.reportStatus`
- update the UT case for the above change
tracked by issue https://github.com/goharbor/harbor/issues/5353
> Return more data of the job when reporting status info via webhook

- src/common/utils/registry/auth/tokenauthorizer.go
- src/common/utils/registry/auth/tokenauthorizer_test.go
Add `pull` scope to POST/PUT/patch method.
This fix issue: https://github.com/goharbor/harbor/issues/5777
> Add pull scope to post/put/patch method

- tools/migration/db/util/mysql_pgsql_data_converter.py
This commit is to fix bug reported by community to upgrade v1.6.0, for the details
just refer to #5788, the fix is to add the encoding for the converter when to convert
the mysql data to pqsql data. Already passed on test with Chinese.
> Add the encoding to the data converter script

- tools/migration/db/util/mysql_pgsql_data_converter.py
This commit is to fix bug reported by community to upgrade v1.6.0, for the details
just refer to #5788. The fix is to add the encoding(utf-8) for the converter when to convert
the mysql data to pqsql data. Already passed on test with Chinese/Japanese.
update
> [Cherry-pick]Add the encoding to the data converter script

- src/adminserver/systemcfg/systemcfg.go
- src/common/dao/base.go
- src/common/utils/utils.go
This commit moves the database schema upgrading after database initialization. The init will test TCP connection.
> Test TCP connection before upgrading database schema

- src/common/dao/config.go
- src/common/dao/group/usergroup.go
- src/common/dao/group/usergroup_test.go
- src/common/utils/utils.go
- src/common/utils/utils_test.go
- src/ui/auth/ldap/ldap.go
Fix the issue mentioned in #5776, LDAP server is case insensitive.
Convert all LDAP group DN to lowercase before save. 
> LDAP group DN should be case insensitively

- src/common/dao/config.go
- src/common/dao/group/usergroup.go
- src/common/dao/group/usergroup_test.go
- src/common/utils/utils.go
- src/common/utils/utils_test.go
- src/ui/auth/ldap/ldap.go
Fix issue #5776, LDAP servers are case insensitive. because only LDAP
group DN is used to compare/equal operation, lowercase all LDAP group DN
when retrieves it from LDAP server, and lowercase them before save it in DB
> LDAP group DN should be case insensitive

- src/chartserver/repo_handler.go
**Fix the potential issue of causing deadlock problem**
avoid deadlock may occurred in the 1 len queue
```
if len(errorChan) == 0 {
//One error is enough, it will be an exit signal to the worker loop
errorChan <- err
}
```
> Fix the potential issue of causing deadlock problem

- src/common/utils/utils.go
Currently, the `TestTCPConn` is a helper to test connection issue between harbor and database, and it may cause an uncontrolled goroutine issue while do `TestTCPConn` without break out the whole loop. The break inside dial goroutine would ONLY break out the select-case statement, rather than the whole for loop.
See the [golang specification](https://golang.org/ref/spec#Break_statements), `A "break" statement terminates execution of the innermost "for", "switch" or "select" statement.`
BTW, the test case wasn't broken, due to the go test is the main routine, while it returned, the other goroutine would also exit.
Thanks.
> Fix `TestTCPConn` break issue.

- .github/stale.yml
"wontfix" is used to mark the issues that were decided will not be fixed
after triage, so let's use a different label to mark stale issues.
> Let stale bot use the label "staled"

- src/chartserver/utility_handler.go
- src/chartserver/utility_handler_test.go
- src/common/const.go
- src/ui/api/base.go
- src/ui/api/chart_label.go
- src/ui/api/chart_label_test.go
- src/ui/api/harborapi_test.go
- src/ui/api/label_resource.go
- src/ui/api/project_test.go
- src/ui/api/repository_label.go
- src/ui/label/errors.go
- src/ui/label/errors_test.go
- src/ui/label/manager.go
- src/ui/router.go
- src/ui/utils/error.go
- src/ui/utils/error_test.go
**Add API to support marking labels to charts**
- add related chart label API entries
- extract label related functionalities to a separate manager interface
- add a base controller for label related actions
- add related UT cases
> Add API to support marking labels to charts

- src/portal/src/app/project/create-project/create-project.component.html
- src/portal/src/app/project/create-project/create-project.scss
fixed #5885 
Tooltip is truncated in "New Project" dialog ,so modify the tooltip to the right and raise the modal-body to make the tooltip display full.
Signed-off-by: Cheng Fangyuan<1309173081@qq.com>
> Modify the tooltip to increase and display the full content

- CONTRIBUTING.md
This PR is removing the CLA text and updating the links to the community resources for the project.
This is part of #5879.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>
> Remove CLA and update community links

- Makefile
- tests/e2e-image/dockerd-entrypoint.sh
Fix the Makefile for MacOS to run harbor locally for dev:
```bash
$ sudo -i
$ make install CLARITYIMAGE=goharbor/harbor-clarity-ui-builder:1.6.0 CLAIRFLAG=true NOTARYFLAG=true
```
Changes made are:
- fix `sed -i` in MacOS, BSD sed and Linux sed are different, use `sed -i -e` instead
- set file mode to 644 in MacOS, instead of 600
- change target name from `version` to `ui_version`
- fix `cleandockercomposefile` target to clean all generated docker-compose files
> Fix Makefile to run harbor locally in  MacOS for dev

- docs/swagger.yaml
- src/chartserver/handler_interface.go
- src/chartserver/handler_utility.go
- src/chartserver/handler_utility_test.go
- src/common/models/project.go
- src/core/api/project.go
- src/core/api/project_test.go
- src/testing/chart_utility.go
**Return the total count of charts under the project in project API**
- add new interface method to get the total count of charts under namespaces by calling get index
- add new field 'chart_count' in the project model
- append chart count to the project model in project API
> Return the total count of charts under the project in project API

- .gitignore
- src/common/dao/group/usergroup.go
Fixes #5895 
This is because a user's group DNs are always lowercased, and comparisons are done in a case-sensitive fashion. 
https://github.com/goharbor/harbor/blob/9dca49ba6e4978a6ed22e471e105533322b68e5d/src/ui/auth/ldap/ldap.go#L95-L97
Following the practice in the same file to lowercase the LDAP group DN before persisting into the DB:
https://github.com/goharbor/harbor/blob/dcb518bcdda4fcede33823417273c10c98eee73f/src/common/dao/group/usergroup.go#L37
> Normalize (make lowercase) ldap_group_dn during onboarding

- src/replication/replicator/replicator.go
Revoke the change made to replicator to reset the insecure flag to true
when accessing source registry.  The reason is that the replicator will
use external URL to access source registry, setting it to false will
break replication when Harbor is hosting with self-signed certificate.
> Revoke the change in replicator

- make/photon/db/initial-registry.sql
The migrate tool will try to create table schema_migration upon opening
the connection to DB.  This will cause error when there are multiple
instance of adminserver trying to access the migrator upon start.
This commit move the creation of the table during the initialization of
the DB container.
> Create shcema migration table in DB container

- tests/robot-cases/Group1-Nightly/Common.robot
Currently, the case "Project Level Image Serverity Policy" uses the project library as the target project, but the project library has been set to scan image automatically when images are pushing, this will cause case failure. This commit creates a new project in the case to aviod the failure.
> Update automation test case "Project Level Image Serverity Policy"

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
fixed #5130 
when removing a user from a project,The dialog information is changed from 'Confirm project deletion' to 'Confirm removal of project members'.
> Modify the dialog information when removing a member of project

- make/docker-compose.chartmuseum.tpl
- make/docker-compose.clair.tpl
- make/docker-compose.notary.tpl
- make/docker-compose.tpl
This commit is to set dns search to null in the harbor containers,
that means the dns search domains of docker host doesn't impact
the network IO in the containers.
If do not set this, Harbor notary-server and notary-signer are resolving
the "mysql" alias to the resolv.conf search path instead of to "mysql."
for the notary-db bridge IP, see #6031.
> Limit dns search in harbor containers

- make/photon/notary/binary.Dockerfile
- make/photon/notary/builder
This commit is to upgrade the golang version to 1.9.4, it because a
bug of golang 17.3 could introduce one dns resolver issue for harbor
mentioned by #6031.
The bug of golang is https://github.com/golang/go/issues/15419, it makes
harbor containers to lookup 'endpoint.' firstly which may cause network
issue.
> Upgrade notary compile golang version to 1.9.4

- src/portal/lib/src/config/system/system-settings.component.ts
- src/portal/lib/src/repository-gridview/repository-gridview.component.html
- src/portal/lib/src/repository-gridview/repository-gridview.component.scss
- src/portal/lib/src/repository-gridview/repository-gridview.component.ts
- src/portal/lib/src/service.config.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
fixes #3117 
Adding links enables developers and project administrators to download registry certificates from UI.
> Allow developers and project admins  administrators to downloadthe harbor certs  from UI.

- make/common/templates/adminserver/env
- make/common/templates/core/env
- make/common/templates/jobservice/env
- make/docker-compose.chartmuseum.tpl
- make/docker-compose.clair.tpl
- make/docker-compose.notary.tpl
- make/docker-compose.tpl
- tests/docker-compose.test.yml
According docker official document, use 'dns_search= .' in the docker
compose file if you don't wish to set the search domain.
https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/
> Use docker official way to unset dns search

- src/portal/src/app/user/user.component.html
fixed #5301 
1, add the header separator line in the action drop-down menu of user options.
2. Modify the text in the drop-down menu as initial letter.
> Add a header separator line to the action drop-down menu.

- src/common/dao/base.go
- src/common/dao/config.go
- src/common/dao/dao_test.go
This commit mitigates the situation when more then one adminserver is
deployed and there may be duplication error when they try to initialize
the configuration to DB.
> Ignore duplication error when inserting config

- src/portal/lib/src/config/vulnerability/vulnerability-config.component.html
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
- tests/resources/Harbor-Pages/Vulnerability.robot
fixed： #6080 
Modify the vulnerability scan page to cancel the edit button so that the page is displayed as the initial data after clicking
Signed-off-by: Cheng Fangyuan <fangyuanc@vmware.com>
> Vulnerability scan cancel editing to make UI into orginal status

- src/portal/lib/src/repository-gridview/repository-gridview.component.html
- src/portal/lib/src/repository-gridview/repository-gridview.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
Descrition info not present based on locale info before, translate it before showing on page.
> Fix: Show image description info based on locale setting

- make/photon/log/Dockerfile
- make/photon/log/rsyslog.conf
This commit fixes the permission issues introduced after migration to photon:2.0 base image.
> Fix permission issue in rsyslog container.

- docs/configure_swagger.md
Typo in configure_swagger.md when mentioning SERVER_IP for prepare-swagger.sh
> Fix typo in configure_swagger.md

- make/install.sh
Update the `grep` filter to anchor at the start of the line
and allow for whitespace characters, in order to correctly
determine the hostname being set if the default is merely
commented out and the custom one added, instead of overridden.
Fixes #6117
Signed-off-by: Christian Witts <cwitts@gmail.com>
> Fix install issue with default hostname commented

- README.md
This commit is to add the nightly result badge into goharbor repo,
1,the badge could index the status of full ci which is running internally.
2,the badge is clickable, and all of the logs can be downloaded.
> Add nightly badge into goharbor repo

- make/common/templates/nginx/nginx.https.conf
Modify nginx configuration to use 308 instead of 301 on the http to
https redirect.
Fix problems with some clients on POST requests that are transformed to
GET on 301 redirect (per HTTP 1.1 standard).
See [RFC7538](https://tools.ietf.org/html/rfc7538).
> Send 308 status on redirect from http to https

- tests/robot-cases/Group1-Nightly/Common.robot
Add "Wait Until xxx" to wait the expected page appear before the next step to avoid the case failure
> Update automation test case "Delete Multi Project"

- docs/user_guide.md
Picture can not be displayed in GitHub to modify the picture path.
> Modify the  image path of download the harbor certs in the user guide.

- src/replication/models/policy.go
Adding header to replication/models/policy.go file as it was previously missing.
Signed-off-by: clouderati <35942204+clouderati@users.noreply.github.com>
> Adding copyright header

- tests/robot-cases/Group1-Nightly/Common.robot
As the changes on scan all, the default schedule was removed from source code,
hence the gc job should be the first admin job, to change to job id to 1.
> Fix failure on GC test case

- src/jobservice/job/impl/gc/job.go
- src/registryctl/api/registry.go
This commit is to fix two problems in the gc job,
1, in order to support redis cluseter, gc job should delete the keys only
for docker reigstry instead of all keys. It because that in the redis cluster,
only db 0 is supported.
2, to restore the real status of read only not just to set it to false.
> Fix gc jobs issues

- src/jobservice/opm/job_stats_mgr.go
- src/jobservice/opm/redis_job_stats_mgr.go
- src/jobservice/opm/redis_job_stats_mgr_test.go
- src/jobservice/period/enqueuer.go
- src/jobservice/pool/redis_pool.go
As before all the running job instances of one periodic job is referred by the ID. Now, each job instance has its own ID and then the stopping logic is outdated and causes issues. In this PR, the stop job method is refined.
> Fix the issue of stopping periodic job

- src/jobservice/runtime/bootstrap.go
An issue `use of closed network connection` of redis message server is reported. To avoid that case, add `TestOnBorrow` check func to the redis pool to verify the connections in the pool are usable.
> Add TestOnBorrow check func of redis pool to verify the getting conn

- src/portal/lib/src/config/system/system-settings.component.ts
- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/app/config/config.component.ts
- src/portal/src/app/config/email/config-email.component.ts
Because currently, each page only have changes on its own page, we don't need this confirmation box to force user to save changes in the tab.
> remove switch tab confirmation

- src/ui/api/replication.go
Signed-off-by: 陈德 <chende@caicloud.io>
When trigger a replication policy, Harbor will check whether the policy has related jobs that are pending or running. But there is some mistake in the check.
```
count, err := dao.GetTotalCountOfRepJobs(&models.RepJobQuery{
PolicyID: replication.PolicyID,
Statuses: []string{models.RepOpTransfer, models.RepOpDelete},
})
```
> [1.6.0] Fix statuses condition when trigger replication

- src/portal/lib/src/tag/tag.component.scss
Increase the height of the retag to make the tooltip display complete
> Let the retag error prompt show complete

- src/replication/replicator/replicator.go
Currently, we pass the external URL as the source registry and set insecure as true in replication, this causes security issue. This commit replaces the URL with the internal one and set insecure to false. Fixes #6109.
> Pass internal core URL as source in replication

- make/photon/clair/docker-entrypoint.sh
Update the entrypoint to allow the image accept other parms,
to help debug in the future.
If replace "$*" with "$@" only one parm will be passed to dumbinit
> Clair image should accept parms

- make/photon/clair/Dockerfile.binary
- make/photon/clair/builder
This commit is to add the clair_version into the harbor images, then clair
will use it in the user-agent, and helpful for the debugging.
> Build clair version into clair image

- make/prepare
Some configuration files and env files contain sensitive information,
they should not be readable by any user by default.
This commit updates the `prepare` script to update the mask of the
rendered files.
> Make rendered files less visible

- src/core/api/user.go
- src/portal/src/app/shared/new-user-form/new-user-form.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Signed-off-by: peimingming
the fix(commit 571384cdb290be980616aeb86f5e7d34b6f13492) for this issue has some problem.
and limit length of user name to 80 in UI is reasonable, for it will look strange from UI if length is too long.
and user name length to 255 when creating by API. https://github.com/goharbor/harbor/issues/6086
> Support longer UserName

- src/core/service/notifications/registry/handler.go
- src/core/utils/job.go
- src/core/utils/utils.go
There's an issue in registry 2.6.x, that when the webhook is sent the
manifest of the image may not be written.
For details: https://github.com/docker/distribution/issues/2625
This will cause issue in "scan on push" or replication.
This commit mitigates the issue by adding retries in notification
handler.
> Wait for manifest in notification handler

- src/jobservice/README.md
- src/jobservice/main.go
Uncomment the harbor configuration injection code block and also fix a typo in the jobservice README doc.
> Uncomment the harbor configuration injection code block 

- make/harbor.cfg
As we split UI into two components: portal and core, the value of no_proxy needs to be updated
> Replace ui with core for no_proxy in harbor.cfg

- tests/apitests/python/library/repository.py
Recover repository.py to initial version for calling the wrong API function.
> Recover repository.py to initial version

- tests/resources/Harbor-Pages/Project-Helmcharts.robot
Sometimes the time span of back to helm chart list is longer then 2 seconds.
> Fix: Nightly test fail from time to time

- make/docker-compose.chartmuseum.tpl
- make/docker-compose.clair.tpl
- make/docker-compose.notary.tpl
- make/docker-compose.tpl
Drop all capabilities when starting containers by modifying docker-compose files to avoid security issue
> Drop unnecessary capabilities when starting containers

- src/chartserver/chart_operator.go
Call API: /chartrepo/{repo}/charts GET
Expected response data format is:
```"[
{
"name": "mariadb",
"total_versions": 1,
"latest_version": "4.3.1",
"created": "2018-11-26T06:25:05.966719842Z",
"updated": "0001-01-01T00:00:00Z",
"icon": "https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png",
"home": "https://mariadb.org",
"deprecated": false
}
]" 
```
Actual behavior is:
```"[
{
"Name": "mariadb",
"total_versions": 1,
"latest_version": "4.3.1",
"Created": "2018-11-26T06:25:05.966719842Z",
"Updated": "0001-01-01T00:00:00Z",
"Icon": "https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png",
"Home": "https://mariadb.org",
"Deprecated": false
}
]"```
> Fix the malformat json data of chart list API

- src/chartserver/cache.go
Add retry with backoff when creating redis cache for chart server
> Add retry with backoff when creating redis cache for chart server

- src/core/api/repository.go
Signed-off-by: 陈德 <chende@caicloud.io>
Fix issue: [Retag kicks user back to login when the user doesn't have sufficient permission](https://github.com/goharbor/harbor/issues/6327])
Use status code `403` when permission not allowed, instead of `401`.
> Fix status code for permission check in retag, use 403

- make/photon/portal/Dockerfile
- tools/migration/Dockerfile
Corrected issues found during build on Photon 2.0. 
harbor\make\photon\portal\Dockerfile -> Set alias for first stage of build due to error when using COPY --from=0
harbor\tools\migration\Dockerfile -> correct syntax in bash command which was preventing package installation.
> Corrected errors in photon build

- make/migrations/postgresql/0002_1.7.0_schema.up.sql
- src/common/dao/dao_test.go
- src/core/api/replication_policy.go
- src/core/api/replication_policy_test.go
- tests/apitests/python/library/label.py
- tests/apitests/python/library/registry.py
- tests/apitests/python/library/replication.py
- tests/apitests/python/test_add_replication_rule.py
This commits fix #5102 by checking the existence of name when creating/editing replication rule
> Check the existence of name when creating replication rule

- docs/swagger.yaml
- make/migrations/postgresql/0003_add_replication_op_uuid.up.sql
- src/common/dao/replication_job.go
- src/common/models/replication_job.go
- src/core/api/models/replication.go
- src/core/api/replication.go
- src/core/api/replication_job.go
- src/core/api/replication_policy.go
- src/replication/core/controller.go
- src/replication/core/controller_test.go
- src/replication/replicator/replicator.go
Add uuid to track all jobs triggered by one replication execution.
Related issue: https://github.com/goharbor/harbor/issues/3876
> Add op uuid to image replication

- src/jobservice/config.yml
- src/jobservice/pool/de_duplicator.go
- src/jobservice/pool/de_duplicator_test.go
- src/jobservice/pool/redis_job_wrapper.go
- src/jobservice/pool/redis_job_wrapper_test.go
- src/jobservice/pool/redis_pool.go
Currently, the uniqueness checking only covers the job queue. The running job is not taken into consideration.
In this PR, the unique scope is expanded to job queue and running jobs. That means if the job is declared to be unique, there will be only one job running at the same time.
> Support unique job constraints (both unique queue and running jobs)

- docs/user_guide.md
The anchor tag for Online GC isn't correct in the user guide. This PR fixes that.
> Fix link to Online GC in user guide

- src/common/utils/timemarker.go
- src/common/utils/timemarker_test.go
- src/core/api/repository.go
- src/core/api/systeminfo.go
Previously there was a in-memory marker to prevent user from frequently
calling the "scan all" API.  This has become problematic in HA
deployment, and is no longer needed after enhancement in jobservice.
This commit removes the marker for "scan all" api, however, we need to
review the mechanism and rework to make it stateless.
> Remove the Scan all in-memory marker

- docs/migration_guide.md
Update the migration guide to reflect the change in data migration
process after v1.6.0
For simplification, removed the various steps to migrate from previous
versions to latest.  User will need to refer to guide in previous
releases.
> Update the data migration guide

- docs/swagger.yaml
- src/core/api/systeminfo.go
- src/core/api/systeminfo_test.go
The Harbor root cert can be downloaded by all users now, so the permission checking is not needed anymore
> Remove the permission checking for getcert API

- docs/migration_guide.md
Fixes #6449
1. Simplify the steps for backing up database.
2. Add the missing command to pull migrator image.
> Refine migration guide for 1.7

- docs/swagger.yaml
- src/core/api/repository.go
Fixes #6418, that when multiple "scan all" jobs are
triggered, the API should not return 500.
> Return 409 when there is a scan all job running

- src/portal/src/app/shared/shared.utils.ts
fix #6422 
When the response is a string, add judgement to return error directly
> Modify the error message when adding members

- src/core/filter/readonly.go
- src/core/filter/readonly_test.go
Block retag requests in read-only mode.
Related issue: https://github.com/goharbor/harbor/issues/6455
/assign @wy65701436
> Block retag requests in read-only mode

- tests/travis/api_common_install.sh
As pip will always install the latest version, to avoid any break change,
just fix the framework to 3.0.4
> [Cherry-pick]Fix robot framework version to 3.0.4

- src/portal/lib/src/tag/tag.component.html
- src/portal/lib/src/tag/tag.component.ts
The default label is displayed when filtering images by label, and the page is not friendly, so set the label to be hidden by default.
> cherry-pick:Remove the border of default label when filtering images by label

- tools/migration/db/schema/notaryserver_alter_tables.pgsql
- tools/migration/db/schema/notaryserver_create_tables.pgsql
- tools/migration/db/schema/notarysigner_alter_tables.pgsql
- tools/migration/db/schema/notarysigner_create_tables.pgsql
- tools/migration/db/util/mysql_pgsql_1_5_0.sh
- tools/migration/db/util/mysql_pgsql_data_converter.py
This commit is to fix the issue on notary migrations from mysql to pgsql.
1, alter sequence for the primary key of changeseed, this is missed in v1.6.0 migrator.
2, alter table owners from postgres to notarysigner and notaryserver.
Issue:
#6465
Workaround:
#6465 (comment)
Impacted upgrade path:
1, Upgrade from version older then v1.6.0 with migrator:v1.6.0, and migrates the notarty DB.
No impacted upgrade path:
1, Upgrade from version older than v1.6.0 with migrator:v1.6.0, but without migrates the notarty DB.
Notes：
After merge this fix, we need to provide an new migrator with an new tag, like v1.6.1, and
deprecated the v1.6.0. For those who was impacted by migrator v1.6.0, will open an new PR to build
the workaround into the migrator and expose an specical command for hot-fix. …
> [Cherry-pick]Fix unable to use Notary after updating to v1.6.0 

- docs/migration_guide.md
The migrator v1.6.3 includes a fix for issue #6465, this issue blocks user to
sign image after updates with goharbor/harbor-migrator:v1.6.0/1/2.
> Update migrator version to v1.6.3

- src/portal/src/app/app-config.ts
- src/portal/src/app/shared/about-dialog/about-dialog.component.ts
About dialog returns unknow instead of 1.2.0 when harbor version is not available
> Return unknow when about dialog cannot get harbor version

- src/jobservice/job/impl/context.go
This commit adds the ssl mode as a param when establishing the connection with database
> Read ssl mode param from the adminserver to init the connection with database

- src/jobservice/job/impl/context.go
This commit adds the ssl mode as a param when establishing the connection with database
> [Cherry-pick]Read ssl mode param from the adminserver to init the connection with database

- CONTRIBUTING.md
Add DCO related description to CONTRIBUTING.md, to guide contributors to sign-off in their commits.
> Add DCO description to CONTRIBUTING.md

- tests/apitests/python/library/repository.py
- tests/apitests/python/test_scan_image.py
Change a small docker image to pull and make timeout value longer.
> Pull a more smaller size of docker image and also make timeout value longer

- src/common/http/client.go
- src/common/utils/registry/registry.go
- src/common/utils/uaa/client.go
- src/core/config/config.go
Adds support for the transport https/http proxy.
To use the proxy one can set http_proxy and https_proxy enviroment variables. Eq. in jobservice to enable proxy set your proxy and also set no_proxy for harbor services, eq. adminserver, registry, core. 
Improvement on helm chart should be made to enable more seamless no_proxy integration.
Fixes #5864 
Signed-off-by: Niklas Wik <niklas.wik@nokia.com>
> Add support for http proxy in transport

- tests/resources/Harbor-Pages/Project-Retag_Elements.robot
- tests/robot-cases/Group1-Nightly/Common.robot
After  clicks the retag confirmation button, the request will be sent, so that the retag dialog cannot disappear immediately. The existence of the modal-backdrop cause the project button can not be clicked, so add the judgment. When the modal popup disappears, click the project button.
> fix nightly test of retag

- src/portal/lib/src/repository-gridview/repository-gridview.component.html
- src/portal/lib/src/repository-gridview/repository-gridview.component.ts
- src/portal/src/app/repository/repository-page.component.html
- src/portal/src/app/repository/repository-page.component.ts
fixed #6591 
Download certificate link is not displayed when  harbor is deployed in http mode 
> When harbor is deployed in http mode, the registry certificate download button is not displayed in the project page.

- src/portal/src/app/config/config.component.html
fix #6361 
Use clarity to refactor the configuration page
> Config component nav tabs to use clarity component

- src/portal/lib/src/repository-gridview/repository-gridview.component.html
- src/portal/lib/src/repository-gridview/repository-gridview.component.ts
- src/portal/src/app/repository/repository-page.component.html
- src/portal/src/app/repository/repository-page.component.ts
fix #6626 
1、After the integration of harbor and vic, admiral could not download the registry certificate.
2、When harbor is deployed in http mode, the registry certificate download button is not displayed in the project page.
Signed-off-by: FangyuanCheng fangyuanc@vmware.com
> [Cherry-pick] Fix download certificate relate bug

- make/prepare
600 is no enough for nginx config file
> The nginx conf file mode should be 644

- make/migrations/postgresql/0002_1.7.0_schema.up.sql
Rename the "name" colume in table "replication_policy" and "replication_target" before adding the "UNIQUE" constraint to avoid the upgrade failure
> [Cherry-pick]Update the upgrade sql to rename the duplicate records

- src/core/service/notifications/registry/handler.go
> Remove user agent check for docker notifications

- src/portal/lib/package.json
- src/portal/lib/src/tag/tag.component.html
- src/portal/package.json
retag api is hard coded in harbor frontend, this lead to wrong admiral api cal if harbor is a component integrated with admiral. For the requirement of vic release. We need to toggle of this feature if integrate with admiral.
> disable retag function if integrate with admiral

- tests/resources/Harbor-Pages/HomePage.robot
- tests/resources/Harbor-Pages/HomePage_Elements.robot
- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/LDAP.robot
- tests/robot-cases/Group1-Nightly/Nightly.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
Robot scripts refactor for keyword sign-in-harbor and other few keywords, mainly on replacing 'sleep' to 'wait until', and also add a checkpoint in "Go Into Project" keyword to verify the result of loading a project page.
fixed  #6684 ##6563
> Robot script refactor for keyword sign-in-harbor

- src/common/ram/namespace.go
- src/common/ram/namespace_test.go
- src/common/ram/parser.go
- src/common/ram/parser_test.go
- src/common/ram/project/const.go
- src/common/ram/project/util.go
- src/common/ram/project/visitor.go
- src/common/ram/project/visitor_role.go
- src/common/ram/project/visitor_role_test.go
- src/common/ram/project/visitor_test.go
- src/common/ram/ram.go
- src/common/ram/ram_test.go
- src/common/security/admiral/context.go
- src/common/security/local/context.go
- src/common/security/secret/context.go
Implement current security interfaces using ram, which keep security interface the same as before.
If this pr merged, the next step is to add HasPermission method to `security.Context`
> Implement current security interfaces using ram

- src/portal/package-lock.json
- src/portal/src/app/harbor-routing.module.ts
Just add a reload option on router module. This feature is introduced in angular5, we can solve this issue easily.
> Fix: data not reload when global serach navigate to same location

- tests/resources/APITest-Util.robot
- tests/resources/Util.robot
Before running robot test cases, make swagger client is requested, but it fails occasionally, so we add retry to avoid this impact.
Fixed: #6385
> add retry for making swagger client

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Harbor-Pages/ToolKit.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/LDAP.robot
- tests/robot-cases/Group1-Nightly/Nightly.robot
The former way to verify project creation is by API calling, but it's not a GUI operation, which is not a goal for operator, so I replace it with GUI verification
Fixed: #6814 #6817 #6826
> Add keyword <Go Into Project> into <Create An New Project> for result verification

- src/common/const.go
- src/core/auth/authenticator.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/auth/authproxy/test/server.go
- src/core/auth/uaa/uaa.go
- src/core/main.go
An HTTP authenticator verifies the credentials by sending a POST request
to an HTTP endpoint.  After successful authentication he will be
onboarded to Harbor's local DB and assigned a role in a project.
This commit provides the initial implementation.
Currently one limitation is that we don't have clear definition about
how we would "search" a user via this HTTP authenticator, so a user has
to login first before he can be assigned a role in Harbor.
> Provide HTTP authenticator

- make/photon/Makefile
- tools/migration/Dockerfile
This commit is to add a flag judging when to build image of migator, which is not necessary.
> Add a flag judging on building migrator

- src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts
Change the Name to name and the Token to token when getting the object returned by the backend
> Fix bug where name and token cannot be displayed due to api changes

- make/migrations/postgresql/0004_add_robot_account.up.sql
- src/common/dao/robot_test.go
- src/common/models/robot.go
This commit is to remove the token attribute as harbor doesn't store the token in DB.
> Remove the token attribute from robot table

- Makefile
- make/photon/Makefile
bump the version of chartmuseum to 0.8.1
> Enhhance: bump chartmuseum version to 0.8.1

- src/common/dao/dao_test.go
- src/common/dao/replication_job.go
- src/common/dao/replication_job_test.go
- src/replication/policy/manager.go
This commit fixes the issue #6698: cannot create a same name replication policy after deleting it
> Fix #6698: cannot create a same name replication policy after deleting it

- src/common/dao/dao_test.go
- src/common/dao/replication_job.go
- src/common/dao/replication_job_test.go
- src/replication/policy/manager.go
This commit fixes the issue #6698: cannot create a same name replication policy after deleting it
> [Cherry-pick]Fix #6698

- make/common/templates/registry/config.yml
Disable validation for registry to fix Docker registry not working with Windows layers.
See [docker/distribution#2795](https://github.com/docker/distribution/issues/2795) for more details.
> Disable validation for registry

- docs/swagger.yaml
- make/migrations/postgresql/0004_add_robot_account.up.sql
- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/robot.go
- src/common/token/claims.go
- src/common/token/htoken.go
- src/common/token/htoken_test.go
- src/common/token/options.go
- src/common/token/options_test.go
- src/core/api/robot.go
- src/core/config/config.go
- src/core/config/config_test.go
This commit is to make the expiration of robot account configurable
1, The expiration could be set by system admin in the configuation page or
by /api/config with robot_token_expiration=60, the default value is 30 days.
2, The expiration could be shown in the robot account infor both on UI and API.
> add expiration of robot account

- src/replication/ng/execution/execution.go
- src/replication/ng/flow/controller.go
- src/replication/ng/operation/controller.go
- src/replication/ng/operation/controller_test.go
- src/replication/ng/replication.go
- src/replication/ng/replication_test.go
This commit implements the operation controller. The operation controller wraps the flow controller and execution manager to provide capabilities for the upper level
> Implement the operation controller

- tools/migration/Dockerfile
The psycopg2 installed by pip has very old `.so` files.
This commit will mitigate such issue by using `tdnf` to install this package.
> Install psycopg2 via photon's repo - Cherry pick to 1.7 branch

- tools/migration/Dockerfile
The psycopg2 installed by pip very old .so files.
This commit will mitigate such issue by using `tdnf` to install this package.
> Install psycopg2 via photon's repo

- src/replication/ng/dao/dao_test.go
- src/replication/ng/dao/example.go
- src/replication/ng/dao/example_test.go
This commit creates a new folder called dao under replication to hold dao codes
> Create dao folder in replication

- src/jobservice/job/impl/replication/transfer.go
This PR will skip transfer blob for foreign layers when do replicate which will fix #6992
> Skip transfer blob for foreign layers

- src/portal/src/app/project/member/add-member/add-member.component.ts
fix 6950 about the default option is not displayed When we click the add-member button, the default option is not displayed.
> fix 6950 about the default option is not displayed When we click the add-member button, the default option is not displayed.

- src/portal/src/app/project/list-project/list-project.component.html
- src/portal/src/app/project/list-project/list-project.component.ts
Should not display the counts of chart if it's not enabled
> Fix: Should not display helm chart counts if it's not enabled

- src/core/api/search.go
- src/core/api/search_test.go
- src/portal/src/app/base/global-search/search-result.component.html
Global search result data does not contain the chart info when chart is empty
> Fix: global search not work when chart enabled

- src/portal/lib/src/config/config.ts
- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
add http auth proxy selection in system configuration:
Under System Configuration Authentication AuthMode module selection, Add option'http auth', which is read-only. Under this option, there are modifiable parts such as Server Endpoint, Authentication Verify Cert, Always Onboard, etc.
> add http auth proxy selection in system configuration

- OWNERS.md
Removal of James Zabala as core maintainer for Harbor based on his request to step down, found here:
https://github.com/goharbor/community/pull/61
Signed-off-by: <jrosland@vmware.com>
> Update OWNERS based on clouderati's request

- src/jobservice/job/impl/replication/transfer.go
This PR will skip transfer blob for foreign layers when do replicate which will fix #6992
> [Cherry-Pick]Skip transfer blob for foreign layers

- src/registryctl/api/registry.go
As registry v2.7.1 has introduced the possibility to clean untagged manifests,
enable it in the registryctl api.
> Enable docker registry to clean untagged revisions

- make/install.sh
> Fix: "install.sh" failure if "$host" env is set

- make/photon/prepare/Pipfile
- make/photon/prepare/Pipfile.lock
Because previous version has security issue
> Fix: upgrade pyyaml version to 4.2b1

- make/photon/portal/Dockerfile
To fix the issue https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html,
it needs to upgrade node to 10.15, which has pitched the fix.
> Upgrade node version to 10.15

- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html
- src/portal/lib/src/list-replication-rule/list-replication-rule.component.ts
- src/portal/lib/src/service/replication.service.ts
1、fix cannot get adapters
2、fix cannot execute replication operation ,execute replication api is changed from 'api/replication' to 'api/replication/execution'
> Fix cannot get adapters

- src/portal/e2e/app.e2e-spec.ts
- src/portal/lib/src/config/config.ts
- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/app/config/auth/config-auth.component.scss
- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/app/config/config.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
OIDC step1---- configration
#7251 
In the configration auth mode section, we add an option, OIDC.
When the user logs in using OIDC mode, the system defaults to auth mode to select OIDC, where the user can modify the name, endpoint, scope, clientId, clientSecret and skipCertVerify of the OIDC. After the modification, the user clicks the Save button to save the changes.
#
Clicking this button will open https://openid.net/connect./
> Oidc step1

- src/replication/ng/adapter/harbor/adapter.go
- src/replication/ng/adapter/image_registry.go
- src/replication/ng/config/config.go
- src/replication/ng/event/handler.go
- src/replication/ng/model/registry.go
- src/replication/ng/operation/controller.go
- src/replication/ng/operation/flow/controller.go
- src/replication/ng/operation/flow/controller_test.go
- src/replication/ng/operation/flow/copy.go
- src/replication/ng/operation/flow/copy_test.go
- src/replication/ng/operation/flow/deletion.go
- src/replication/ng/operation/flow/deletion_test.go
- src/replication/ng/operation/flow/stage.go
- src/replication/ng/operation/flow/stage_test.go
- src/replication/ng/replication.go
- src/replication/ng/transfer/repository/transfer.go
1. Use the secret to do the auth between the components when replicating
2. Handle internal core URL and token service URl when the instance is local Harbor
> Use the secret to auth the replication for local Harbor

- src/common/utils/registry/auth/credential.go
Only add the authentication info when the username is provided to support pulling public images from docker hub without login
> Update the registry client to support pulling public images from docker hub without login

- src/common/const.go
- src/common/utils/oidc/helper.go
- src/common/utils/oidc/helper_test.go
- src/core/config/config_test.go
- src/core/controllers/oidc.go
- src/core/router.go
This commit add callback controller to handler the redirection from
successful OIDC authentication.
For E2E case this requires callback controller to kick off onboard
process, which will be covered in subsequent commits.
> Add callback controller for OIDC

- src/core/api/repository.go
- src/replication/ng/adapter/harbor/image_registry.go
- src/replication/ng/adapter/image_registry.go
- src/replication/ng/adapter/image_registry_test.go
- src/replication/ng/transfer/repository/transfer.go
Call Harbor API to delete the images in Harbor adapter to avoid the inconsistent between the different versions of Harbor
> Call Harbor API to delete the images in Harbor adapter

- src/portal/src/app/app.module.ts
- src/portal/src/app/harbor-routing.module.ts
- src/portal/src/app/oidc-onboard/oidc-onboard.component.html
- src/portal/src/app/oidc-onboard/oidc-onboard.component.scss
- src/portal/src/app/oidc-onboard/oidc-onboard.component.spec.ts
- src/portal/src/app/oidc-onboard/oidc-onboard.component.ts
- src/portal/src/app/oidc-onboard/oidc-onboard.module.ts
- src/portal/src/app/oidc-onboard/oidc-onboard.service.spec.ts
- src/portal/src/app/oidc-onboard/oidc-onboard.service.ts
- src/portal/src/app/shared/route/oidc-guard-active.service.ts
- src/portal/src/app/shared/shared.module.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
When a user logs in to Harbor for the first time through OIDC, the user will enter an onboard page, prompting the user to add the user name of Harbor. After the user name is entered, click save, and the user successfully logs in to Harbor through OIDC.
> Add the OIDC onboard page

- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Fix issue of oidc configuration save button is always disabled and incorrect character.
when we login Harbor width OIDC ,we cannot click the save  button of oidc config page
> Fix issue of oidc configuration save button is always disabled.

- src/core/api/registry.go
- src/core/main.go
- src/replication/ng/dao/policy.go
- src/replication/ng/dao/policy_test.go
- src/replication/ng/model/policy.go
- src/replication/ng/policy/manager/manager.go
Use policy controller to get policies when delete registry.
And also refactor the GetPolicies method.
> Use policy controller in registry deletion

- src/core/api/registry_test.go
- src/core/main.go
- src/replication/ng/registry/healthcheck.go
- src/replication/ng/replication.go
- src/replication/ng/replication_test.go
Set a longer interval for regular health check for registries.
And also wait some random time before checking.
> Wait randomly before registry health checking

- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Util.robot
Add a checkpoint in the end of key word <Add Guest Member To Project>, to make sure that the confirm button was click successfully, to see if this confirm button was dissappered after clicked.
> Add a checkpoint in the end of key word <Add Guest Member To Project>

- make/photon/prepare/utils/docker_compose.py
Fix problem for `make prepare` error:
```
preparing...
host make path is set to /Users/xfoolish/Work/src/github.com/goharbor/harbor/make
cp: /data/cert/server.crt: No such file or directory
cp: /data/cert/server.key: No such file or directory
...
loaded secret from file: /secret/keys/secretkey
Traceback (most recent call last):
File "main.py", line 70, in <module>
main()
File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.6/site-packages/click/core.py", …
```
> Fix make prepare problem

- tests/resources/Harbor-Pages/Public_Elements.robot
- tests/resources/Harbor-Pages/ToolKit.robot
- tests/resources/Util.robot
Many keywords in ToolKit.robot miss wait or retry when operating elements, and it has cause test case failure one time, so I modify all keywords in ToolKit.robot.
> Add wait and retry in keywords of ToolKit.robot

- src/portal/src/app/account/account-settings/account-settings-modal.component.html
- src/portal/src/app/account/account-settings/account-settings-modal.component.scss
- src/portal/src/app/account/account-settings/account-settings-modal.component.ts
- src/portal/src/app/shared/session-user.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
user could copy the CLI secret when login through oidc, and using this cli secret as password when using docker/helm cli to access Harbor.
> Add Cli secret in Harbor user profile

- src/portal/lib/src/config/config.ts
- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
adding token review endpoint to the configuration page allows users to edit token review endpoint when logging in through http auth.
> Add Token Review Endpoint in configuration page

- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
1、Fix when clicking the edit policy, the source registry isn’t shown
2、Fix save button enable when not input rule name or source/destination namespaces
3、When editing the pull mode policy, generate filter and trigger according to the selected source registry.
> Fix replication ui relate issues

- src/replication/adapter/image_registry.go
When client not exist , will deadlock.
> fix deadlock when client not exist.

- src/replication/adapter/adapter.go
- src/replication/adapter/dockerhub/adapter.go
- src/replication/adapter/harbor/adapter.go
- src/replication/adapter/harbor/adapter_test.go
- src/replication/adapter/huawei/huawei_adapter.go
- src/replication/adapter/huawei/huawei_adapter_test.go
- src/replication/adapter/native/adapter.go
- src/replication/operation/controller_test.go
- src/replication/operation/flow/stage.go
- src/replication/operation/flow/stage_test.go
Update the PrepareForPush method to avoid the useless API callings to create namespaces
> Update the PrepareForPush method

- src/portal/lib/src/cron-schedule/cron-schedule.component.html
- src/portal/lib/src/cron-schedule/cron-schedule.component.scss
When select custom, input will automatically go to the second line.
The modified page is
> Fix cron input box and select box not in one line

- make/install.sh
> Fix: grep https not work

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
fix #7431 
1、Hide vulnrability if clair is not installed
2、Hide gc if is not has adminRole
3、If there is no gc and vulneravility at the same time, hide the task
> Hide vulnrability if clair is not installed

- src/common/utils/oidc/helper.go
- src/common/utils/oidc/secret.go
- src/common/utils/oidc/testutils.go
- src/core/filter/security.go
- src/core/filter/security_test.go
Ths commmit ensures that when user's token is invalidated OIDC provider, he
cannot access protected resource in Harbor with the user info in his session.
We share the code path with secret verification b/c the refresh token
can be used only once, so it has to be stored in one place.
> Handle OIDC user invalidation from OIDC provider.

- src/core/filter/security.go
If a user does not have OIDC meta data in DB, it means he's not
onboarded via OIDC authn, hence, we should not check the token.
> Skip verifying OIDC token for local user

- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Replication_Elements.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
Due to replication NG feature already in master branch, old replication UI test cases have been moved out of Jenkins pipeline, and here test case Pro-Replication-Rules-Add has been finished and ready for duty.
> Add UI test case Pro-Replication-Rules-Add

- tests/resources/Harbor-Pages/Project-Repository.robot
Add retry and wait for keyword <View Repo Scan Details>, Jenkins chart CI failed at 1 test case in rare occasion, the reason is lacking of wait and retry to wait.
> Add retry and wait for keyword <View Repo Scan Details>

- src/portal/src/app/account/account-settings/account-settings-modal-service.service.spec.ts
- src/portal/src/app/account/account-settings/account-settings-modal-service.service.ts
- src/portal/src/app/account/account-settings/account-settings-modal.component.html
- src/portal/src/app/account/account-settings/account-settings-modal.component.scss
- src/portal/src/app/account/account-settings/account-settings-modal.component.ts
- src/portal/src/app/account/account.module.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
add cli secret button in user profile page, OIDC users can click this button to regenerate a cli secret, if the user does so, then the past cli secret will be abandoned.
> Add generate cli secret in user profile page

- src/chartserver/client.go
- src/chartserver/utils.go
- src/core/api/chart_repository.go
Chart client eats the http error if not status ok, after refactor, the
real http response will be catched in core api.
> refine chart clint http response

- tests/resources/Harbor-Pages/Replication.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
Due to replication NG feature already in master branch, old replication UI test cases have been moved out of Jenkins pipeline, and here is that test case endpoint add/edit/delete  have been finished and ready for duty.
> Add UI test case endpoint add/edit/delete

- src/portal/lib/package.json
- src/portal/lib/src/config/gc/gc.api.repository.ts
- src/portal/lib/src/config/gc/gc.component.html
- src/portal/lib/src/config/gc/gc.component.ts
- src/portal/lib/src/config/gc/gc.service.ts
Before just hardcoded the log url in the gc html. That caused admiral will get log fail because different endpoint. 
Therefore, we need to make gc log endpoint also use api config in config files.
> use endpoint in api config to load gc logs

- src/portal/lib/package.json
- src/portal/lib/src/config/gc/gc-history/gc-history.component.html
- src/portal/lib/src/config/gc/gc-history/gc-history.component.ts
- src/portal/lib/src/config/gc/gc.api.repository.ts
- src/portal/lib/src/config/gc/gc.service.ts
Before just hardcoded the log url in the gc html. That caused admiral will get log fail because different endpoint.
Therefore, we need to make gc log endpoint also use api config in config files.
> use endpoint for gc log

- src/portal/lib/src/tag/tag.component.html
- src/portal/lib/src/vulnerability-scanning/result-bar-chart.component.ts
- src/portal/lib/src/vulnerability-scanning/result-grid.component.html
fix #7402 
If set to automatically scan images on push,Entering the tag page image will always scan,So need to keep getting the status until the end
> Fix scan task never ends in UI

- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
This commit ensures that the TLS config of the HTTP client for auth
proxy is updated when the configuration is changed.
> Update Transport of HTTP cient in auth proxy client

- src/common/utils/oidc/helper.go
- src/common/utils/oidc/secret.go
- src/core/controllers/oidc.go
This commit make sure the token is persist to DB after every time after
a user logs in via OIDC provider, to make sure the secret is usable for
the OIDC providers that don't provide refresh token.
It also updates the authorize URL for google to make sure the refresh
token will be returned.
Also some misc refinement included, including add comment to the
OIDC onboarded user, preset the username in onboard dialog.
> Persist the new token in DB after login

- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html
- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
- src/portal/lib/src/replication/replication.component.scss
- src/portal/lib/src/replication/replication.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
fix #7539 #7557 #7578 
1、Add loading if the fileter is not loaded when creating the replication rule
2、Hide the both option if there is only one option in the resource
3、Disable url when adapter is dockerHub
> Add loading if the fileter is not loaded when creating the replication rule

- src/common/api/base.go
- src/core/controllers/oidc.go
This commit update the response off OIDC callback when there's error in exchange token.
Additionally add comments to clarify that by default 500 error will not
contain any details.
> Return more details for error in exchange token

- src/replication/operation/controller.go
- src/replication/operation/controller_test.go
When fetching resources is slow, the starting replication request may timeout, this commit returns immediately after creating the execution record when starting the replication
> Return immediately after creating the execution record when starting the replication

- make/photon/prepare/utils/configs.py
Fix that when loading external db config wrong varible used
> Fix cannot load external configs of database

- src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html
- src/portal/lib/src/replication/replication-tasks/replication-tasks.component.ts
- src/portal/lib/src/replication/replication.component.ts
fix #7551 
1、If the task is in progress, the api should not return end_time. The frontend check that if there is no end_time field, it will display ‘-’ by default.
2、Refresh the list if the search field is empty
> Display '-' if the end_time does not exist

- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/test_robot_account.py
- tests/apitests/python/testutils.py
- tests/robot-cases/Group0-BAT/API_DB.robot
This API test script was blocked by a swagger error, now this error was fixed, so robot account script can be finished now. In swagger.yaml, robot account can be updated in "disabled" status, it's added into script.
> Update API test script - "Robot Account"

- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
- src/portal/lib/src/replication/replication.component.ts
Steps in issue
1、Create a new replication rule
2、Click pull mode
3、Choose a source repository
4、Quickly click on the push mode before the filter does not get the data.
5、Dialog display
solution：
Disable replication mode before the filter is loaded.
> Fix failed to get filter data when switching replication mode

- tests/apitests/python/library/system.py
In API test, there is a dead loop in checking GC status, it's fixed in this PR.
> Fix dead loop in checking GC status.

- src/portal/lib/src/config/gc/gc.component.html
- src/portal/lib/src/config/gc/gc.component.ts
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.html
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
- src/portal/lib/src/cron-schedule/cron-schedule.component.html
- src/portal/lib/src/cron-schedule/cron-schedule.component.scss
- src/portal/lib/src/cron-schedule/cron-schedule.component.ts
- src/portal/lib/src/utils.ts
1、The front end only verifies that cron has entered illegal special characters, does not verify the specific format of cron, is completed by the backend, and throws an error.
2、If the background check fails, the page is still in edit state
> Remove the frontend check of cron

- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/app/config/auth/config-auth.component.ts
for 7622: click the icon of auth mode when value is database in configuration page will go to a wrong pagee
> Modify auth mode icon to jump to a new page only in OIDC mode

- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
fix #7662 
Switch from push mode to pull mode. If the source registry has been selected, it will not get filter and trigger according to the id of the selected registry, resulting in incorrect page data.
solution:
Switch from push to pull. If the source registry is selected, re-acquire the filter and trigger according to the selected id.
> Fix will not get filter and trigger when switching from push to pull

- src/replication/adapter/native/adapter.go
- src/replication/adapter/native/adapter_test.go
- src/replication/adapter/native/image_registry_test.go
- src/replication/model/registry.go
Rename the adapter name of docker registry to "docker-registry"
> Rename the adapter name of docker registry

- src/portal/src/app/account/account-settings/account-settings-modal.component.html
remove required  from filed "First and last name" on the OIDC user profile page.
> Remove required  from filed "First and last name" on the OIDC user profile page

- src/common/utils/oidc/helper.go
Some OIDC providers will not return error when refreshing the token
Fixes #7695
> Make sure panic is not thrown when refresh token

- src/portal/lib/src/cron-schedule/cron-schedule.component.ts
fix #7668
Should only verify that the invalid cron is entered under the custom, can not be saved
> Fix unable to save after entering invalid cron and then switching back to other schedules

- src/jobservice/api/handler.go
- src/jobservice/api/handler_test.go
- src/jobservice/api/router.go
- src/jobservice/common/query/q.go
- src/jobservice/common/query/q_test.go
- src/jobservice/common/rds/keys.go
- src/jobservice/core/controller.go
- src/jobservice/core/controller_test.go
- src/jobservice/core/interface.go
- src/jobservice/errs/errors.go
- src/jobservice/job/tracker.go
- src/jobservice/job/tracker_test.go
- src/jobservice/main.go
- src/jobservice/mgt/manager.go
- src/jobservice/mgt/manager_test.go
- src/jobservice/runtime/bootstrap.go
- src/jobservice/worker/cworker/c_worker.go
- src/jobservice/worker/cworker/c_worker_test.go
- src/jobservice/worker/interface.go
- tests/robot-cases/Group0-BAT/API_DB.robot
Support API  **GET** `/api/v1/jobs` to get job list
Following query parameters supported:
* `kind=Scheduled` : only query the jobs which are in the scheduled queue (not executed yet)
* `page_number` : only valid for `kind=Scheduled` case
* `page_size`:  for `kind=Scheduled` case, this is fixed to 20; for other cases, this is used to set the query scope (not the real page_size, so the items in the returned list are not guaranteed to be totally equal with `page_size`. Check [documemt](https://redis.io/commands/scan) to learn more details)
* for case without param `kind`, param `cursor` is used to query the 'next page'
For the response header,
* For `kind=Scheduled`, header `Total-Count` is returned, which includes the total number of the …
> add get jobs API to provide powerful job stats management

- src/portal/lib/src/config/gc/gc.component.spec.ts
- src/portal/lib/src/config/registry-config.component.spec.ts
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.spec.ts
- src/portal/lib/src/cron-schedule/cron-schedule.component.html
- src/portal/lib/src/cron-schedule/cron-schedule.component.scss
- src/portal/lib/src/cron-schedule/cron-tooltip/cron-tooltip.component.html
- src/portal/lib/src/cron-schedule/cron-tooltip/cron-tooltip.component.scss
- src/portal/lib/src/cron-schedule/cron-tooltip/cron-tooltip.component.ts
- src/portal/lib/src/cron-schedule/index.ts
- src/portal/lib/src/replication/replication.component.html
- src/portal/lib/src/replication/replication.component.spec.ts
Using the table tag directly as the content of the tooltip, compatibility issues will appear in the Firefox browser, resulting in incomplete tooltip display.
solution:
Add a layer of div outside as tooltip content
> Fix the cron tooltip in replication is not fully displayed in Firefox.

- src/common/const.go
- src/core/controllers/base.go
- src/core/controllers/controllers_test.go
- src/core/router.go
When the auth mode is OIDC, when a user login via Harbor's login form.
If the user does not exist or the user is onboarded via OIDC, he will be
redirected to the OIDC login page.
> Redirect regular user to OIDC login page

- src/replication/adapter/harbor/adapter.go
- src/replication/adapter/harbor/chart_registry.go
- src/replication/adapter/harbor/image_registry.go
- src/replication/transfer/image/transfer.go
Fix issue https://github.com/goharbor/harbor-helm/issues/222: replication cannot work when Harbor is deployed on Kubernetes whose hairpin mode is disabled
> Fix issue: replication cannot work when Harbor is deployed on Kubernetes whose hairpin mode is disabled

- tests/testprepare.sh
Read the content of env instead of config_env as the config_env has been removed
> Fix travis failure: read the content of env instead of config_env as the config_env has been removed

- src/replication/adapter/huawei/huawei_adapter.go
- src/replication/model/registry.go
Rename the adapter name of huawei to huawei-SWR. Fixes #7732
> Rename the adapter name of huawei to huawei-SWR

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Change the images in ‘Delete remote images when locally deleted’ to resources
> Modify the prompt for deleting resources when creating a replication rule.

- docs/swagger.yaml
- src/core/api/label.go
- src/core/api/label_test.go
- src/core/api/projectmember.go
- src/core/api/projectmember_test.go
- src/core/api/replication_policy.go
- src/core/api/replication_policy_test.go
- src/core/api/usergroup.go
Return 400 status code for validation failed which fix #6880 and this match the responses of `/api/labels` in swagger.yaml 
> Return 400 status code for validation failed

- src/replication/adapter/harbor/chart_registry.go
- src/replication/adapter/harbor/image_registry.go
Use internal service name rather than 127.0.0.1 when calling APIs of core in jobservice jobs
> Fixes bug in replication

- src/core/controllers/oidc.go
- src/core/filter/security.go
- src/core/filter/security_test.go
This commit allows request with a valid ID token to access the API.
> Add filter to handle request with ID token

- src/core/controllers/base.go
As the UI cannot handle 302, update the login controller to return 403
and put the redirection URL in a json response body.
> Update login controller to return 403 for redirection

- src/core/controllers/base.go
As the UI cannot handle 302, update the login controller to return 403
and put the redirection URL in a json response body.
> Update login controller to return 403 for redirection - cherrypick to 1.8 branch

- make/photon/log/rsyslog.conf
Add "MaxMessageSize" to the config of rsyslogd to avoid the mess of log file when the size of one log line > 8k
> Add "MaxMessageSize" to the config of rsyslogd

- make/photon/prepare/utils/chart.py
Signed-off-by: liqiang-fit2cloud <liqiang@fit2cloud.com>
Fix https://github.com/goharbor/harbor/issues/7288
The issue occurs when using Alibaba OSS for both docker registry and helm chart repository, the endpoint must be specified in the registry_storage_provider_config of harbor.cfg file as the endpoint is mandatory for helm chart, although it's optional for docker registry .
For docker registry the endpoint must contain the bucket name like bucket-name.oss-cn-qingdao-internal.aliyuncs.com, But for helm chart the endpoint must be in the format oss-cn-qingdao-internal.aliyuncs.com which should not contains bucket name.
So if set the endpoint with bucket name docker registry works well but helm chart is not working, if set the endpoint without bucket name docker registry is not working but …
> Fix issue: harbor 1.7.4 aliyun oss chartmuseum 500

- make/photon/prepare/utils/chart.py
Signed-off-by: liqiang-fit2cloud <liqiang@fit2cloud.com>
> Fix issue: https://github.com/goharbor/harbor/issues/7288

- tests/resources/Harbor-Pages/Project.robot
Nightly test case user-view-logs failed several times, after debugging, the reason is checking too fast although the operation has not finsished, so I add a checking for end of the operation.
> Add positive result check for delete a repo

- src/core/auth/authproxy/auth.go
This issue is regresssion that introduced by https://github.com/goharbor/harbor/commit/f92bc8076dda5b62f3afac8e179268626f899ae1#diff-42381e6df5f17ebd3d9165a325d5d8f4, the a.ensure() was removed from SearchUser(), which leads to the alwaysonboard cannot be updated.
> Add ensure settings when to search user in auth proxy

- src/portal/lib/package.json
- src/portal/package-lock.json
- src/portal/package.json
- src/portal/src/app/app.module.ts
- src/portal/src/app/base/navigator/navigator.component.scss
fix bug when we use language with pt-br;
change the harbor version from 1.7.x to 1.8;
edit style fix #7807
> Fix bug when we use language with pt-br; change the harbor version from 1.7.x to 1.8

- tests/resources/Docker-Util.robot
- tests/robot-cases/Group3-Upgrade/data.json
- tests/robot-cases/Group3-Upgrade/prepare.py
Jenkin job cd_daily_master failed due to sign image failure, but there're other failure for replicaiton NG, so API for replication NG need to be updated.
> Update API in prepary.py for Jenkin job cd_daily_master

- tests/robot-cases/Group3-Upgrade/prepare_v17.py
Population data tool - prepare.py has been adapted for the latest version due to API changing, but the old version still was needed in other place, so it should be add it back and give it a new name.
> Add a new prepare file for old version of APIs

- docs/swagger.yaml
It looks like the Swagger for `ChartVersions` and `ChartVersionDetails`
were missing fields to properly generate a client.
This fixes the problem by adding the correct `refs` so that the client
produces an output when making an API call.
In Go, this generates something like:
```Go
/*GetChartrepoRepoChartsNameVersionOK handles this case with default header values.
Successfully retrieved the chart version
*/
type GetChartrepoRepoChartsNameVersionOK struct {
Payload *models.ChartVersionDetails
}
...
/*GetChartrepoRepoChartsNameOK handles this case with default header values.
Retrieved all versions of the specified chart
*/
type GetChartrepoRepoChartsNameOK struct {
Payload models.ChartVersions
}
```
Signed-off-by: Dan Norris <dan.norris@netapp.com>
> Fix Swagger client generation for a few chartrepo endpoints

- tests/resources/Harbor-Pages/Project.robot
In robot-framework, Element Clicked returns OK, but the element was not click functionally
> Element Clicked returns OK, but the element was not click functionally

- tests/resources/Util.robot
Modify robot-framework keyword <Retry Double Keywords When Error>, when the second action is success, should quit keyword.
> Modify robot-framework keyword <Retry Double Keywords When Error>

- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
- src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss
fix bug: Save button not enabled when all the required fields are filled on Safari, Edge , Internet Explorer
fix issue   https://github.com/goharbor/harbor/issues/7829
> fix bug: Save button not enabled when all the required fields are filled on Safari, Edge , Internet Explorer

- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/resources/Harbor-Pages/Vulnerability_Elements.robot
- tests/resources/Util.robot
In nightly test, case Disable-Scan-Schedule always failed at action of edit button click, so we should add a confirmation to make sure that this button will be disappeared after click action.
> Add button click confirmation in test case Disable-Scan-Schedule 

- src/portal/src/styles.css
> fix  filter ui bug : half filter is covered when there is one or two records in a datagrid

- src/core/api/health.go
The health check for the registry was using "/v2" which returned an
unauthorized response and put additional errors in the logs. Switch
to using "/" which returns an OK response with reduced logging.
Signed-off-by: Mark Peek <markpeek@vmware.com>
> Switch registry health check to a 200 response url

- src/common/dao/scan_job.go
- src/common/models/cve_whitelist.go
- src/common/models/cve_whitelist_test.go
- src/common/models/scan_job.go
- src/common/models/sev.go
- src/core/api/repository.go
- src/core/api/utils.go
- src/core/proxy/interceptors.go
- src/core/proxy/proxy.go
- src/pkg/scan/vuln.go
- src/pkg/scan/vuln_test.go
Interceptor will filter the vulnerability in whitelist while calculating
the serverity of an image and determine whether or not to block client
form pulling it.
It will use the system level whitelist in this commit, another commit
will switch to project level whitelist based on setting in a project.
> Apply CVE white list in interceptor

- src/core/filter/security.go
Fixes #8130
Enable OIDC filter to handle requests to /api/chartrepo/*
> Handle helm push in OIDC filter - cherrypick to 1.8

- src/jobservice/common/rds/keys.go
> use separate key for the last periodic enqueue data

- src/core/filter/security.go
Fixes #8130
Enable OIDC filter to handle requests to /api/chartrepo/*
> Handle helm push in OIDC filter

- src/replication/transfer/image/transfer.go
Support v1 signed media type when do the replicatio
> Support v1 signed media type when do the replication

- tests/resources/Harbor-Pages/ToolKit.robot
In nightly test case <Delete Multi Member>, 'action' was clicked, but the dropdown list was't not shown up, so we should add a comfirmation to make sure the expected element show up.
> Add confirmation for  nightly test case <Delete Multi Member>

- tests/ldap_test.ldif
Add user027 and user028 to ldap service, it was added in ldap_test.ldif for nightly test.
> Add user027 and user028 to ldap service

- docs/swagger.yaml
- src/common/models/pro_meta.go
- src/common/models/project.go
- src/core/api/project.go
- src/core/api/sys_cve_whitelist.go
- src/core/api/sys_cve_whitelist_test.go
- src/core/promgr/promgr.go
- src/core/proxy/interceptor_test.go
- src/core/proxy/interceptors.go
- src/pkg/scan/whitelist/manager.go
- src/pkg/scan/whitelist/validator.go
- src/pkg/scan/whitelist/validator_test.go
This commit update the project API to support "reuse_sys_cve_whitelist"
setting in project metadata and "cve_whitelist" in project request.
Also modify the interceptor to support project level CVE whitelist if
the reuse flag is false.
> Enable project level CVE whitelist

- src/pkg/retention/policy/alg/index.go
- src/pkg/retention/policy/alg/or/processor.go
- src/pkg/retention/policy/alg/or/processor_test.go
- src/pkg/retention/policy/alg/processor.go
- src/pkg/retention/policy/builder.go
Roll back the Processor interface and add an index for processors.
```go
// Processor processing the whole policy targeting a repository.
// Methods are defined to reflect the standard structure of the policy:
// list of rules with corresponding selectors plus an action performer.
type Processor interface {
// Process the artifact candidates
//
//  Arguments:
//    artifacts []*res.Candidate : process the retention candidates
//
//  Returns:
//    []*res.Result : the processed results
//    error         : common error object if any errors occurred
Process(artifacts []*res.Candidate) ([]*res.Result, error)
}
```
> refactor the processor interface

- src/common/utils/oidc/helper.go
- src/common/utils/oidc/helper_test.go
This commit make sure the OIDC is more actively recreated, to mitigate
the problem in #8177
> Reload OIDC provider older than 3 seconds -- cherrypick

- src/pkg/retention/policy/rule/latestk/evaluator.go
- src/pkg/retention/policy/rule/latestk/evaluator_test.go
This ports my WIP implementation to match the updated proposal.
Fixes #6660
> Retention: Implement Filter: Keep Latest K

- tests/resources/Harbor-Pages/Project-Helmcharts.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Common.robot
In nightly test case 'list helm chart', there is no verification for delete chart, so add confirmation for chart files deletion.
> In nightly test case 'list helm chart', there is no verification for delete chart. 

- src/pkg/retention/policy/rule/lastpulled/evaluator.go
- src/pkg/retention/policy/rule/lastpulled/evaluator_test.go
Implement the `Keep N Most Recently Pulled/Accessed Artifacts` evaluator.
Fixes #6659 
Signed-off-by: Nathan Lowe public@nlowe.me
> Retention: Implement Evaluator: Keep N Most Recently Pulled

- src/pkg/retention/policy/rule/latest/evaluator.go
- src/pkg/retention/policy/rule/latest/evaluator_test.go
Implementation for the "Retain the latest K most recently active images", where "active" is defined as the pull or push time, whichever is more recent.
Fixes #6657
> Retention: Implement Evaluator: Retain Latest K 'Active'

- src/core/api/base.go
- src/core/api/repository_label_test.go
- src/pkg/project/manager.go
- src/pkg/repository/manager.go
- src/pkg/retention/launcher.go
- src/pkg/retention/launcher_test.go
Move the pkg manager/controller declaration to the api package to avoid the dependency cycle
> Move the pkg manager/controller declaration to the api package

- src/jobservice/hook/hook_client.go
jobservice reads the proxy environment variables, but do not consider the no_proxy variable.
Modified the code to leverage the go proxy handling function that reads the env variables including no_proxy. The same function is used in all the other containers.
> Make jobservice use the proxy env variables (including no_proxy)

- src/pkg/retention/policy/action/index_test.go
- src/pkg/retention/policy/builder_test.go
- src/pkg/retention/policy/rule/index_test.go
- add UT cases for the index of action
- add UT cases for the index of processor
- add UT cases for the index of the rule selector
- add UT cases for the policy builder
> add missing UT cases for index and builder components

- docs/swagger.yaml
- src/common/utils/oidc/helper.go
- src/common/utils/oidc/helper_test.go
- src/core/api/harborapi_test.go
- src/core/api/oidc.go
- src/core/api/oidc_test.go
- src/core/router.go
This commit adds an API to help admin verify the OIDC endpoint is a
valid one.
> Add API to ping OIDC endpoint

- src/jobservice/runtime/bootstrap.go
- src/pkg/retention/job.go
add two checkpoints for `stop` in the retention job
> support stop in the retention job and register it

- src/jobservice/config/config.go
- src/jobservice/config/config_test.go
- src/jobservice/main.go
- src/pkg/retention/boot.go
- src/pkg/retention/dep/client.go
- src/pkg/retention/dep/client_test.go
- src/pkg/retention/job.go
- src/pkg/retention/job_test.go
- src/pkg/retention/launcher.go
- src/pkg/retention/launcher_test.go
As the retention client is only used in job which running in jobservice, the configurations that needed to init the client should be read from jobservice
> Create retention client with the configurations got from jobservice config

- tests/resources/Docker-Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
In nighly test case <Project Level Image Serverity Policy>, scan result of haproxy image is nolonger high but medium, it should be a bug of clair, so we replace haproxy by postgres, and also we pull postgres with sha256 to make sure the image under test is alway the specific one.
> Replace image from haproxy to postgres for vulnerability scanning

- src/common/dao/group/usergroup_test.go
- src/common/dao/project.go
This commit fixes #8432
When querying the role of group ID, all matched roles should be returned
instead of the minimal role ID.
> Update GetRolesByGroupID  -- cherrypick 1.8

- src/jobservice/job/known_jobs.go
- src/jobservice/runtime/bootstrap.go
- src/pkg/retention/dep/client.go
- src/pkg/retention/job.go
- src/pkg/retention/job_del_repo.go
- src/pkg/retention/job_del_repo_test.go
- src/pkg/retention/job_test.go
- src/pkg/retention/policy/action/index/index.go
- src/pkg/retention/policy/action/index/index_test.go
- src/pkg/retention/policy/action/performer_test.go
- src/pkg/retention/policy/alg/index/index.go
- src/pkg/retention/policy/alg/or/processor_test.go
- src/pkg/retention/policy/builder_test.go
- src/pkg/retention/policy/lwp/models.go
- add a new job to delete the whole repository which is not matched by the retain rules
- register the above new job to job service
- fix some `gofmt` in the package importing paths of some files
> add retention job for deleting repository

- make/photon/prepare/templates/core/env.jinja
- make/photon/prepare/utils/configs.py
- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/core/api/repository.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/core/middlewares/config.go
- src/core/middlewares/inlet.go
- src/core/middlewares/util/util.go
- src/core/utils/retag.go
- src/core/utils/utils.go
this is for internal registry api call, the request should be intercepted by quota middlerwares, like retag and delete.
Note: The api developer has to know that if the internal registry call in your api, please consider to use
NewRepositoryClientForLocal() to init the repository client, which can handle quota change.
> add internal reg request handler chain

- docs/user_guide.md
The --cert-file and --key-file options for Helm CLI are used to identify HTTPS client, i.e. the helm CLI.
It's not mandantory and usually not needed. Most of the users don't know how to get these two files.
> Remove unneccessary certificate options for Helm CLI

- src/pkg/retention/job_del_repo.go
dry run is missing when deleting ropo
> fix bug: dry run is missing when deleting ropo

- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/ToolKit.robot
- tests/robot-cases/Group1-Nightly/Chartmuseum.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Common_GC.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
Currently, nightly test pipeline was only in one level category of auth_mode and upgrade, now we like to add a level base on the original level which is harbor deployment parameters.
> add test execution dimention of harbor deployment parameters

- src/jobservice/migration/manager_test.go
- src/jobservice/migration/migrator_v180.go
- src/jobservice/runtime/bootstrap.go
The cause is the Redis connection pool used in the job service for the data migration is run out. That is caused by a bug in the migration process, the connection should be returned to the pool instantly, not with `defer` way.
We’ll build a patch soon and check if we resolve this issue.
> fix bug #8499: redis connection pool is run out

- src/common/utils/log/logger.go
If harbor is built (or `go test`'d) in a different folder than the repo
root, the call to `common/utils/log/line(...)` will panic with an index
out of range runtime error because the `strings.SplitN(...)` can't find `harbor/src`
in the path.
Since `SplitN` always returns at least one element for `n != 0`, the check should probably have originally been `if len(l) > 1` anyways.
I found this while writing #8357, not sure how I didn't hit this with previous PRs, perhaps the integration branch was missing 411876908807c966e627402ba87187c40981386a before now.
> Fix logger line() call if built outside of the repo root

- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Util.robot
Adding retry for wait element visibility, in nightly test case Developer-Operate-Labels, project didn't show up when checking its visiblity, so add some wait for this check.
> Adding retry for wait element visibility in nightly test case Developer-Operate-Labels

- src/jobservice/worker/cworker/c_worker.go
As the arguments of a job may contain sensitive information, ignore them when logging the job detail. Fixes #8404
> Ignore the arguments when logging the job detail

- .dockerignore
Add dockerignore file to prevent local node_modules to be copied into the portal image.
Otherwise the portal linux image could contain node_modules built for darwin when the image is built on a Mac, which makes the angular build fail.
> Add dockerignore file to prevent local node_modules to be copied into the portal image

- src/replication/operation/flow/stage.go
Fixes #8281, only show one tag in the task list to decrease the length of string to avoid exceeding the limit in database
> Fixes #8281, only show one tag in the task list to decrease the length of string

- src/replication/adapter/harbor/adapter.go
- src/replication/adapter/harbor/adapter_test.go
This commit filters the metadata when creating project in replication to avoid replicate unnecessary properties, such as retention policy
> Only replicate "public" metadata when creating project in Harbor

- docs/swagger.yaml
- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/core/api/project.go
- src/core/config/config.go
- src/core/middlewares/chart/builder.go
- src/core/middlewares/countquota/builder.go
- src/core/middlewares/countquota/handler_test.go
- src/core/middlewares/interceptor/quota/options.go
- src/core/middlewares/interceptor/quota/quota.go
- src/core/middlewares/sizequota/builder.go
- src/core/middlewares/sizequota/handler_test.go
1. add quota_per_project_enable  config item
2. quota interceptor reserve resources only enforce resources set for the interceptor
3. quota for project creation and summary have effect only quota_per_project_enable is true
> feat(quota,middleware): enable or disable quota per project by config

- docs/swagger.yaml
This commit update the swagger doc to document how to trigger an "admin
job" such as "GC" to make it execute right away.
> Update the swagger doc for GC API

- src/common/dao/project.go
Fix issue #8570, sort projects when there is no user group related info
> Sort project by name

- docs/swagger.yaml
This commit add `reuse_sys_cve_whitelist` to project metadata, and fixes
a few issues in APIs related webhook.
> Fix issue in API swagger doc

- src/core/views/404.tpl
The error template is missing a closing <a> tag in the link to the harbor portal.
Signed-off-by: Pedro Laguna <44469313+vmlaguna@users.noreply.github.com>
> Close <a> tag in error template

- src/replication/adapter/native/adapter.go
Use the stardard token authentication work flow even though the credentail isn't provided
> Fix bug in native replication adapter

- src/core/api/retention.go
- src/pkg/retention/policy/rule/dayspl/evaluator.go
- src/pkg/retention/policy/rule/dayspl/evaluator_test.go
- src/pkg/retention/policy/rule/daysps/evaluator.go
- src/pkg/retention/policy/rule/daysps/evaluator_test.go
- src/pkg/retention/policy/rule/lastx/evaluator.go
- src/pkg/retention/policy/rule/lastx/evaluator_test.go
- src/pkg/retention/policy/rule/latestk/evaluator.go
- src/pkg/retention/policy/rule/latestk/evaluator_test.go
- src/pkg/retention/policy/rule/latestpl/evaluator.go
- src/pkg/retention/policy/rule/latestpl/evaluator_test.go
- src/pkg/retention/policy/rule/latestps/evaluator.go
- src/pkg/retention/policy/rule/latestps/evaluator_test.go
json decode int as float64, which cause type conversion failed
Change-Id: I16d7284b17508885e136f2d9ea5651978ba4a6d8
> fix retention rule compute error

- docs/swagger.yaml
- src/core/api/repository.go
- src/portal/lib/src/service/tag.service.ts
Enable the `detail` parameter when list tags. In some cases, only tag name is cared, no need to spend long time to fetch detail, vulnerability scanning result, notary sign results.
Related issues: https://github.com/goharbor/harbor/issues/6876
> List simple tags when detail set to false

- docs/swagger.yaml
- tests/apitests/python/library/project.py
- tests/apitests/python/test_project_level_cve_whitelist.py
This commit update test case to cover project level CVE whitelist.
It also fixes the swagger doc to add missing attributes
> API test for project level CVE whitelist

- make/migrations/postgresql/0001_initial_schema.up.sql
- src/common/dao/user.go
- src/common/dao/user_test.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/auth/ldap/ldap.go
- src/core/auth/ldap/ldap_test.go
- src/core/auth/uaa/uaa.go
- src/core/auth/uaa/uaa_test.go
- src/core/controllers/oidc.go
Fix issue #7848, If email address is empty, set null instead of xxx@placeholder.com to avoid any security concern.
> Set default email to null if not provided

- make/photon/prepare/utils/registry.py
when log level is warning, the actual value of registry should be warn
> Fix: registry log level rendering issue

- src/common/utils/ldap/ldap.go
- src/common/utils/ldap/ldap_test.go
Fix #7710   Normalize LDAP filter for user and group filter to make a common schema for filter
> Normalize LDAP filter for user filter and group filter

- make/migrations/postgresql/0010_1.9.0_schema.up.sql
- src/core/service/notifications/jobs/handler.go
- src/pkg/retention/dao/models/retention.go
- src/pkg/retention/dao/retention.go
- src/pkg/retention/dao/retention_test.go
- src/pkg/retention/launcher_test.go
- src/pkg/retention/manager.go
- src/pkg/retention/manager_test.go
- src/pkg/retention/models.go
Compare the status code when updating retention task status to avoid the concurrent issue
> Handle the retention task status updating in concurrency

- docs/swagger.yaml
This PR fixes all the errors in the swagger API definition. It does not remove all the warnings though.
Before: (using the [`go-swagger`](https://github.com/go-swagger/go-swagger/) tool)
```
> swagger validate docs/swagger.yaml
2019/08/11 23:14:13
The swagger spec at "docs/swagger.yaml" showed up some valid but possibly unwanted constructs.
2019/08/11 23:14:13 See warnings below:
2019/08/11 23:14:13 - WARNING: definition "#/definitions/ChartInfoList" is not used anywhere
2019/08/11 23:14:13 - WARNING: definition "#/definitions/InternalChartAPIError" is not used anywhere
2019/08/11 23:14:13 - WARNING: definition "#/definitions/PingRegistry" is not used anywhere
2019/08/11 23:14:13 - WARNING: definition "#/definitions/Role" is not used anywhere
2019/08/11 23:14:13 - WARNING: definition …
```
> Fix the swagger API definition

- src/common/quota/manager.go
- src/common/quota/util.go
- src/common/quota/util_test.go
- src/core/middlewares/interceptor/quota/quota.go
1. Skip overflow error when subtract resources
2. Take up resources before handle request and put it back when handle
failed for add action in quota interceptor
3. Free resources only after handle success for subtract action in quota
interceptor
Closes #8681
> refactor(quota,middleware): skip overflow error when subtract resources

- src/portal/src/app/shared/route/member-guard-activate.service.ts
revert the pr 8494; because of the backend Api is not ready.
https://github.com/goharbor/harbor/pull/8494
> Revert "Fix redirect login page when enter harbor through global search"

- make/photon/prepare/templates/jobservice/config.yml.jinja
- src/jobservice/config/config.go
- src/jobservice/runtime/bootstrap.go
When Redis is served under HAProxy, job service keeps restarting without configure idle timeout for redis pool
Fix: https://github.com/goharbor/harbor/issues/7871
> Config idle timeout for redis pool to avoid jobservice restarting

- docs/swagger.yaml
- src/core/controllers/oidc.go
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
Signed-off-by: sakura longfei.shang@daocloud.io
Typo fix "an user" -> "a user"
> fixt typo "an user" to "a user"

- src/common/dao/project_blob.go
- src/common/dao/project_blob_test.go
the project id is missing in the method, that makes GC to clean all of items,
and if quota will not compute twice for the existing manifest.
> fix sql in remove blob from project

- src/common/const.go
- src/common/dao/project_blob.go
- src/common/dao/project_blob_test.go
- src/core/api/quota/registry/registry.go
The foreign layer won't be counted into project quota
NOTE: the foreign layer will be dumped from the registry in the migration
> fix(quota/sync) #8886

- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
- make/photon/prepare/utils/configs.py
- make/photon/prepare/utils/docker_compose.py
- make/photon/prepare/utils/jinja.py
If depend on external redis or pg. local db and redis should not start. Therefore can save some resources.
> Disable redis and db containers if external db enabled

- src/portal/src/i18n/lang/en-us-lang.json
Typo fix in en-us-lang.json "Creat" -> "Create"
> Typo fix in en-us-lang.json

- tests/robot-cases/Group1-Nightly/Clair.robot
Clair scan result is not accurate that when I script this case, only 6 high CVE-ID, but in today nightly result, one more CVE-ID popuped, so I have to add it.
> Fix nightly case to handle new vuln found by Clair.

- src/core/controllers/oidc.go
Same PR as https://github.com/goharbor/harbor/pull/8820 but rebased on **master** (although would be nice to merge also PR 8820 into 1.8.x).
If wrong OIDC scopes are defined, or there are some configuration errors, the OIDC callback query string might contain "error=..." with an error message. Intercept this case and show an error to the user instead of trying to exchange the token with a missing "code" parameter.
> Handle error on OIDC callback

- src/core/api/user.go
- src/core/api/user_test.go
This commit enhance the `POST /api/users` API to block request from non-admin to create
admin user.
> Disallow creating an admin user when registration

- src/common/dao/blob.go
- src/common/dao/blob_test.go
- src/common/models/blob.go
- src/core/api/quota/registry/registry.go
- src/core/middlewares/sizequota/builder.go
- src/core/middlewares/sizequota/handler_test.go
- src/core/middlewares/sizequota/util.go
- src/core/middlewares/util/util.go
1. Sync blobs from manifest for image with foreign layers.
2. Ignore size of foreign layers when compute size quota.
3. Fix repo info of artifact when upgrade from 1.8 version.
> fix(quota): correct size quota for image with foreign layers

- make/photon/portal/nginx.conf
shouldn't cache index.html for access fresh page after upgrade.
> Add no-cache to index.html

- tests/robot-cases/Group1-Nightly/Clair.robot
Replace image from httpd to haproxy:1.5 to make sure severity is stable for test.
> Replace image from httpd to haproxy:1.5 for CVE whitelist test

- src/pkg/scan/whitelist/manager.go
This commit make sure that the "items" in response of project level
CVE_whitelist is not null, even when it's null in the DB the API will
return an empty list
> The default item list should be empty list,not null

- src/core/api/user.go
- src/core/api/user_test.go
This commit enhance the `POST /api/users` API to block request from non-admin to create
admin user.
> Disallow creating an admin user when registration -- cherry pick to 1.8

- src/core/controllers/oidc.go
If wrong OIDC scopes are defined, or there are some configuration errors, the OIDC callback query string might contain "error=..." with an error message. Intercept this case and show an error to the user instead of trying to exchange the token with a missing "code" parameter.
Signed-off-by: Iradier, AlvaroJose <AlvaroJose.Iradier@adidas.com>
Change error variable name
Signed-off-by: Iradier, AlvaroJose <AlvaroJose.Iradier@adidas.com>
> Handle error on OIDC callback -- cherry-pick to 1.8 branch

- src/pkg/scan/whitelist/manager.go
This commit make sure that the "items" in response of project level
CVE_whitelist is not null, even when it's null in the DB the API will
return an empty list
> The default item list should be empty list,not null - cherrypick to 1.9 branch

- tests/robot-cases/Group0-BAT/API_DB.robot
Add CVE whitelist project level API test into travis tests.
> Add CVE whitelist project level API test into travis tests.

- tests/robot-cases/Group1-Nightly/Replication.robot
Replace image from tomcat to alpine for small size, then it will not take a long time for replication.
> Replace image from tomcat to alpine for small size

- make/photon/prepare/main.py
- make/photon/prepare/utils/configs.py
Do not read unrelated configs of the database if external db enabled.
> Add logic to read clair and notary config

- tests/resources/Harbor-Pages/Configuration.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
Replace CVE sample image from other to redis in union, redis is stable in relative, so test result will be stable relatively
> Replace CVE sample image from other to redis in union

- src/core/api/user.go
- src/core/api/user_test.go
This commit enhance the `POST /api/users` API to block request from non-admin to create
admin user.
> Disallow creating an admin user when registration -- cherry pick to 1.7

- src/common/const.go
We changed the listenning port of portal from 80 to 8080 to run the process as non-root user, but the change didn't update the default URL of portal in source code, this causes the health check API fail.
> Add the port 8080 to the default URL of portal to avoid the health check API failure

- src/common/const.go
We changed the listenning port of portal from 80 to 8080 to run the process as non-root user, but the change didn't update the default URL of portal in source code, this causes the health check API fail.
> [Cherry-pick]Add the port 8080 to the default URL of portal to avoid the health check API failure

- .travis.yml
- tests/travis/ui_ut_run.sh
- tests/travis/ut_install.sh
- tests/travis/ut_run.sh
The previous version of travis vm. the node js version is 8.9. It will fail when angular upgrade to 8. This pr focus on upgrade the node js version in CI and also split the frontend unit test in a separate job.
> Run frontend unit test in separate job in travis. Also upgrade the node js version in CI

- tests/resources/Harbor-Pages/Configuration.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
Replace CVE sample image from other to redis in union, redis is stable in relative, so test result will be stable relatively
> [cherry-pick to 1.9 ] Replace CVE sample image from other to redis

- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/core/filter/security_test.go
This commit add the new setting "oidc_groups_claim" to Harbor's
configurations.
And add "group_claim" to OIDCSetting struct.
> Add groups claim to OIDC configuration

- docs/installation_guide.md
Cherry-picking the syslog and DB updates from https://github.com/goharbor/harbor/pull/9005 into the 1.9 branch.
@reasonerjt and @xaleeks can you please approve?
* Documented how to configure Syslog connection in harbor.yml
* Documenting DB connection pool
* Removed extraneous character
* Comments from Qian.
* Comment from Weiwei
* Another comment from Weiwei
* Added max_open_conns and max_idle_conns to the external DB
* Corrected defaults for max_open_conns and max_idle_conns
> Cherry pick syslog doc updates into 1.9 branch

- tests/resources/Docker-Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
In nighly test case <Project Level Image Serverity Policy>, scan result of haproxy image is nolonger high but medium, it should be a bug of clair, so we replace haproxy by postgres, and also we pull postgres with sha256 to make sure the image under test is alway the specific one.
> [cherry-pick to release-1.8.0] Replace nightly test case sample image from haproxy to postgres

- src/core/controllers/base.go
It's introduced by https://github.com/goharbor/harbor/pull/8976
> remove filter redeclared as imported package name in base.go

- src/core/api/base.go
- src/core/controllers/base.go
- src/core/controllers/oidc.go
This commit mitigates the Session Fixation issue by making sure a new
session ID is generated each time user logs in to Harbor
> Generate new session ID after login -- 1.9 cherrypick

- tests/resources/Harbor-Pages/Verify.robot
After angular upgraded, all migrate pipelines failed at system setting project creation verification. Keyword of Page Should Contain is not working anymore in new UI, so I chosen a new more precise way of checking the select element value of 'everyone'
> Modify way of Project creation verifycation in migrate pipeline

- tests/resources/Harbor-Pages/Project.robot
In nightly test, keyword <Create An New Project> failed after angular upgrade, the OK button in create new project page was clicked, but it's not effective, so I add a retry for OK button click, if the button was not disappeared, script will be clicked again.
> Add retry in keyword <Create An New Project> to make sure OK button was clicked successfully

- make/photon/prepare/templates/nginx/nginx.https.conf.jinja
This commit modifies nginx configuration file to make sure the secure
flag is added to "Set-Cookie" header when Harbor is serving https
> Add Secure flag to cookie  -- cherrypick to 1.9

- src/pkg/retention/policy/rule/dayspl/evaluator_test.go
- src/pkg/retention/policy/rule/daysps/evaluator_test.go
- tests/apitests/python/test_retention.py
adjust wait job timeout for tag retention, as currently get job service log may fail if not wait enough time
> adjust wait job timeout in test case

- tests/resources/Harbor-Pages/Verify.robot
In this PR right now, I commented 2 lines to remove a verification, it's because that Vulnerability data is not consistent when migrate harbor from 1.7 to 1.9, I've filed an issue to follow it, once it's fixed, these 2 commented lines will be come back.
> commented 2 lines to remove Vulnerability scan all data verification

- src/portal/lib/src/config/system/system-settings.component.html
- tests/resources/Harbor-Pages/Configuration_Elements.robot
Add id for system configuration repo-readonly-checkbox in UI code, and add element locator in robot case.
> Add id for system configuration repo-readonly-checkbox in UI code

- tests/resources/Harbor-Pages/HomePage.robot
After angular upgrade, in DB.robot, 4 test cases failed at create-a-new-user, the reason is that no sleep between input or click action, some blank was not inputed, so I add retry keyword for those actions.
> Refect nightly test case keyword create-a-new-user

- src/core/api/oidc.go
Returning a common error when failed to test the oidc provider and printing the detail in the log
> Return a common error message when testing the oidc provider 

- src/core/api/oidc.go
Returning a common error when failed to test the oidc provider and printing the detail in the log
> [Cherry-pick]Return a common error message when testing the oidc provider 

- src/core/api/notification_policy.go
This commit returns a common error message when testing the webhook endpoint and prints the detail in the log for debug
> Return the common error message when testing the webhook endpoint 

- src/core/api/notification_policy.go
This commit returns a common error message when testing the webhook endpoint and prints the detail in the log for debug
> [Cherry-pick]Return the common error message when testing the webhook endpoint 

- docs/swagger.yaml
- src/core/api/user.go
Make the username required when searching user and remove the support for query email
> Make the username required when searching user

- src/core/middlewares/sizequota/builder.go
- src/core/middlewares/sizequota/util.go
- src/core/middlewares/sizequota/util_test.go
1. fix `parseUploadedBlobSize` function when range header not found in response
2. skip to save blob size when quota disabled
> Patch blob upload improvement

- src/core/middlewares/sizequota/builder.go
- src/core/middlewares/sizequota/util.go
- src/core/middlewares/sizequota/util_test.go
1. fix `parseUploadedBlobSize` function when range header not found in response
2. skip to save blob size when quota disabled
> [Cherry pick]Patch blob upload improvement

- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
In nightly helm pipeline, test case 'Project Quotas Control Under GC' failed, it should be timing issue that the valuse in UI is not ready, so I add a keyword 'Retry Keyword When Return Value Mismatch' to retry value getting action.
> Add a keyword 'Retry Keyword When Return Value Mismatch'

- tests/robot-cases/Group1-Nightly/Clair.robot
In nightly CVE whitelist tests, there be a new CVE occured  in image redis, so add this for test verifcation.
> Add a new CVE ID  for image redis in nightly CVE system and project level whitelist tests

- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Common.robot
1. Nightly test case failed due to more vulnerability CVE IDs in image redis, so add 2 new CVE IDs in CVE Whitelist test cases. 2. A Keyword parameter error was fixed in this PR.
> Fixed CVE whitelist test case of more CVE ID in image redis

- Makefile
- make/photon/Makefile
- make/photon/portal/Dockerfile
1. Introduce NPM_REGISTRY in Makefile to support npm registry
configuration when build portal image.
2. Install npm pkgs before copy portal src so that build cache works for
npm install in portal image.
> build(portal): npm registry configurable and build cache support

- src/core/main.go
This commit is to fix the issue for the following scenario:
1, user success migrate harbor to v1.9.0 from a previous version
2, add a project, push images into the project.
3, delete images and then to delete the project.
4, re-launch harbor.
After that, it still execute the quota migration as the condition doesn't consider the deleted projects usage.
And in this case, the harbor core crashes with a duplicate sql err, and unable to launch.
[Workaroud]
Clean table of project_blob with: TRUNCATE TABLE project_blob, and re-launch harbor, wait for quota sync success.
> fix quota migration still execute on launch even data sync success

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/robot-cases/Group3-Upgrade/data.json
- tests/robot-cases/Group3-Upgrade/prepare.py
- tests/robot-cases/Group3-Upgrade/prepare_v17.py
In nightly migrate pipeline, after migration, should check all the data which were populated, for now, project meta data were populated, but were not been verified, so I add these verification in this PR.
It shoud fixed issues #8918 and #9366.
> Add project meta data verifcation In nightly migrate pipeline

- src/core/main.go
This commit is to fix the issue for the following scenario:
1, user success migrate harbor to v1.9.0 from a previous version
2, add a project, push images into the project.
3, delete images and then to delete the project.
4, re-launch harbor.
After that, it still execute the quota migration as the condition doesn't consider the deleted projects usage.
And in this case, the harbor core crashes with a duplicate sql err, and unable to launch.
[Workaroud]
Clean table of project_blob with: TRUNCATE TABLE project_blob, and re-launch harbor, wait for quota sync success.
> [cherry-pick]fix quota migration still execute on launch even data sync success

- src/core/middlewares/util/util.go
- src/core/middlewares/util/util_test.go
Fixes #8234, check the existence of project to avoid the panic
> Check the existence of project before the next action

- src/common/utils/ldap/ldap.go
This PR escape the user dn in the ldap search filter for nested groups.
In our company, the dn contains the username surrounded by brackets. The login failed with the message 'Error occurred in UserLogin: LDAP Result Code 201 "": ldap: finished compiling filter with extra at end: OU=user,dc=example,dc=net))'
> Escape user dn in ldap group search filter

- tests/robot-cases/Group3-Upgrade/prepare_v17.py
Fix an error in prepary.py in Jenkins upgrade pipeline, which is a 'if' position error in project metadata population.
> Fix a 'if' position error in project metadata population

- src/portal/src/app/project/helm-chart/helm-chart-detail/chart-detail/chart-detail.component.ts
If we have https reverse proxy in a front of harbor, we can set external_url and harbor will use it but not on chart details page within Add Repo command (it will be http://) if you have https -> http proxy setup.
> Use external_url if exists on Add Repo Command chart details page

- make/photon/prepare/templates/nginx/nginx.https.conf.jinja
According to [linked article](https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html) from comment, TLSv1.1 is not recommended anymore and should be disabled. 
And for example, [GitLab 12 has TLSv1.1 disabled by default](https://docs.gitlab.com/omnibus/update/gitlab_11_changes.html#tls-v11-deprecation).
> nginx: Remove TLSv1.1 support

- src/common/dao/project_blob.go
- src/common/dao/project_blob_test.go
1. Use fake id of blobs to reduce the time for preparing the blobs
2. Increment the batch size form 10 to 100 in `AddBlobsToProject` fn
These reduce the test running time of `common/dao` package from 400s to 18s and `UTTEST` job from 33m to 24m.
> perf(test): speed up TestAddBlobsToProject test in dao pkg

- Makefile
- make/photon/Makefile
- make/photon/portal/Dockerfile
1. Introduce NPM_REGISTRY in Makefile to support npm registry configuration when build portal image.
2. Install npm pkgs before copy portal src so that build cache works for npm install in portal image.
> [Cherry pick]build(portal): npm registry configurable and build cache support

- tests/robot-cases/Group1-Nightly/Common.robot
Project quotas counting result is growing a little bit for unknow reason, images redis size was caculating from 25.8 to 25.9, so error message should be updated.
> Fix nightly test case failure by project quota error message changed

- src/common/utils/oidc/helper.go
- src/common/utils/oidc/secret.go
- src/core/filter/security.go
1) Disassociate id token from user session
2) Some OIDC providers do not return id_token in the response of refresh
request:
https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse
When validating the CLI secret it will not validate the id token,
instead it will check the expiration of the access token, and try to
refresh it.
> Update OIDC token refresh process

- src/common/utils/oidc/helper.go
- src/common/utils/oidc/secret.go
- src/core/filter/security.go
1) Disassociate id token from user session
2) Some OIDC providers do not return id_token in the response of refresh
request:
https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse
When validating the CLI secret it will not validate the id token,
instead it will check the expiration of the access token, and try to
refresh it.
> Update OIDC token refresh process  -- Cherrypick 1.9

- src/common/rbac/const.go
- src/common/rbac/project/visitor_role.go
- src/core/api/project.go
- src/portal/lib/src/cache/index.ts
- src/portal/lib/src/index.ts
- src/portal/lib/src/service/permission-static.ts
- src/portal/lib/src/service/permission.service.ts
- src/portal/src/app/project/summary/summary.component.html
- src/portal/src/app/project/summary/summary.component.spec.ts
- src/portal/src/app/project/summary/summary.component.ts
- src/portal/src/app/shared/message-handler/message-handler.service.ts
- src/portal/src/app/shared/route/sign-in-guard-activate.service.ts
- src/portal/src/app/shared/session.service.ts
1. Only show project member info when has member list permission.
2. Only show quota info when has quota read permission.
3. Add quota read permission for all roles of project.
4. Refactor permission service in portal.
5. Clear cache when clear session.
Closes #8697
> fix(permissions): permissions checking for member and quota info

- src/core/api/sys_cve_whitelist_test.go
- src/pkg/scan/whitelist/validator.go
- src/pkg/scan/whitelist/validator_test.go
To contain various vulnerabilities in the CVE whitelist, this commit
removes the validation.
Fixes #9242
> Remove validation for item in CVE whitelist -- Cherrypick to 1.9

- make/photon/notary/builder
This commit modify the log message from upstream notary DB migrator, to
make sure the DB URL is not displayed.
Fixes #7510
> Hide DB URL from notary migrator script

- src/common/config/metadata/type.go
- src/common/config/metadata/type_test.go
Support scientific notation format string for int64 and quota types in configuration.
`RESTDriver` load number in `JSON` as `float64` which will be formatted as string with scientific notation, `Int64Type` and `QuotaType` not support scientific notation that will cause issue #9308 .
Closes #9308
> fix(configuration): E notation support for int64 and quota types

- src/common/config/metadata/type.go
- src/common/config/metadata/type_test.go
Support scientific notation format string for int64 and quota types in configuration.
`RESTDriver` load number in `JSON` as `float64` which will be formatted as string with scientific notation, `Int64Type` and `QuotaType` not support scientific notation that will cause issue #9308 .
Closes #9308
> [Cherry pick]fix(configuration): E notation support for int64 and quota types

- src/core/api/chart_repository.go
- src/core/service/notifications/registry/handler.go
Fixes #9455. Populate the public metadata into the event when doing the replication based on event
> Populate public metadata into the event

- src/core/api/chart_repository.go
- src/core/service/notifications/registry/handler.go
Fixes #9455. Populate the public metadata into the event when doing the replication based on event
> [Cherry-pick]Populate public metadata into the event

- .dockerignore
- Makefile
- make/photon/Makefile
- make/photon/portal/Dockerfile
1. Introduce NPM_REGISTRY in Makefile to support npm registry configuration when build portal image.
> build(portal): npm registry configurable

- src/common/const.go
- src/core/api/health.go
- src/core/config/config.go
As we introduce the pluggable scanner, users can add the external scanners, so we remove the Clair from the health check API
> Remove the health checker for Clair in health check API

- tests/resources/Harbor-Pages/ToolKit_Elements.robot
In nightly test case of project members, xpath locator of remove a member is not strong enough for location, it used index of element, so it should be update by the meaning of this button.
> strenth xpath locator of project member remove button

- src/core/api/internal.go
- src/core/api/quota/migrator.go
- src/core/api/quota/registry/registry.go
1, eat the unknown manifest error, and log it. The migration process will not crashed on it.
2, enable to persist DB of sync quota API.
3, add empty project support.
append empty project
> Fix quota sync crash on getting the unknown mainfest

- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/DB.robot
Before user keyword Enable Self Reg, explore should be opened and navigate to harbor login page.
> fixed bug of enable self reg, explore should be opened and navigate to harbor log in page

- src/core/api/internal.go
- src/core/api/quota/migrator.go
- src/core/api/quota/registry/registry.go
1, eat the unknown manifest error, and log it. The migration process will not crashed on it.
2, enable to persist DB of sync quota API.
3, add empty project support.
> [cherry-pick] Fix quota sync crash on getting the unknown mainfest

- src/common/dao/project_blob.go
- src/common/dao/project_blob_test.go
1. Use fake id of blobs to reduce the time for preparing the blobs
2. Increment the batch size form 10 to 100 in AddBlobsToProject fn
These reduce the test running time of common/dao package from 400s to 18s and UTTEST job from 33m to 24m.
> [Cherry pick]perf(test): speed up TestAddBlobsToProject test in dao pkg

- make/photon/prepare/templates/clair-adapter/env.jinja
1. Set log level for clair adapter to make it match the setting in `harbor.yml`
> chore(log): log level support for clair adapter

- src/core/service/notifications/jobs/handler.go
- src/pkg/scan/dao/scan/report.go
- src/pkg/scan/dao/scan/report_test.go
- bug details: #9629
- root cause: the preconditions for updating may not be matched
> fix the bug of returning errors when nothing is updated

- src/common/dao/quota.go
- src/common/dao/quota_test.go
- src/common/dao/quota_usage.go
- src/common/dao/quota_usage_test.go
- src/pkg/types/resources.go
1. Limit `ListQuotas` and `ListQuotaUsages` sort only on support resources.
> fix(quota): order by quotas only on support resources

- src/common/dao/quota.go
- src/common/dao/quota_test.go
- src/common/dao/quota_usage.go
- src/common/dao/quota_usage_test.go
- src/pkg/types/resources.go
1. Limit `ListQuotas` and `ListQuotaUsages` sort only on support resources.
> [Cherry pick]fix(quota): order by quotas only on support resources

- src/core/api/chart_repository.go
- src/core/service/notifications/registry/handler.go
Fixes #9455. Populate the public metadata into the event when doing the replication based on event
> [Cherry-pick-1.8]Populate public metadata into the event

- make/photon/prepare/templates/core/env.jinja
- src/core/main.go
As the quota sync is default called by harbor-core on every launch, and it will break the launch process if any failure throwed.
1, The commit is to provide an switcher for the system admin to bypass the quota sync.
2, In case Harbor goes into the restarting cycle.
Harbor already provides an internal API to sync quota data, in the failure case,
system admin can launch harbor and call the /api/internal/syncquota to sync quota.
> [cherry-pick]add a switcher for quota sync on core launch

- src/common/models/pro_meta.go
- src/core/api/metadata.go
- src/core/middlewares/util/util.go
- src/core/middlewares/util/util_test.go
The severity saved in db is lowercase but the severities in vuln pkg
begin with upper letter, this fix use func to transform project severity
value from db to vuln.Severity.
> fix(policy-checker): add func to transform project severity to vuln.Severity

- tests/resources/Harbor-Pages/Replication.robot
Replication rule element is modified from selector to input, so nightly test case should be updated.
> Modify nightly test case due to replication rule element is modified from selector to input

- make/harbor.yml
- make/install.sh
- make/photon/prepare/main.py
- make/photon/prepare/utils/configs.py
- tests/hostcfg.sh
1. Umcomment https related configs
2. Remove the https prepare related thing in ci
> Enable https by default

- src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
> Fix a bug that when someone edits a rule with same name ,it displays the name is already in use

- src/common/rbac/project/visitor_role.go
- src/core/api/repository_test.go
- src/core/api/scan_test.go
- the developer role should not have permission to trigger scan action
> revoke scan permission from the developer role

- src/portal/src/app/account/password-setting/password-setting.component.html
- src/portal/src/app/account/password-setting/reset-password/reset-password.component.html
- src/portal/src/app/shared/new-user-form/new-user-form.component.html
- src/portal/src/app/user/change-password/change-password.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Addresses: #234 
Extends the password length to unlimited characters.
This should be possible since:
* In [`src/common/dao/user.go`](https://github.com/goharbor/harbor/blob/master/src/common/dao/user.go#L159) the Salt never exceeds 32 characters since the [`utils.GenerateRandomString()`](https://github.com/goharbor/harbor/tree/master/src/common/utils/utils.go#L67) always return 32.
* [`utils.Encrypt(u.Password, u.Salt)`](https://github.com/goharbor/harbor/blob/master/src/common/utils/encrypt.go#L42) also always returns 32. that can be test here:
https://play.golang.org/p/NeBuv9eHm91
The database table for the password and the salt both have a `character varying(40)` type.
I updated the translations as best as I could, I trusted Google translate for most of them.
> feat: Expand password length to unlimited

- tools/migration/cfg/migrator_1_9_0/harbor.yml.jinja
Possible fix for: https://github.com/goharbor/harbor/issues/9174
As far as I'm aware chart is only available if the stack was started with `./install.sh --with-chartmuseum` so I guess it's fair to add a check if the property is available.
> #9174 config migration fails with python error: jinja2.exceptions.UndefinedError: 'chart' is undefined

- src/core/middlewares/contenttrust/handler.go
- src/core/middlewares/regtoken/handler.go
- src/core/middlewares/util/util.go
- src/core/middlewares/vulnerable/handler.go
This commit is to fix https://github.com/goharbor/harbor/issues/9780.
To align with OCI spec, when a docker pull request without bearer token in header comes in, Harbor should not intecepte it(return a 412 if check fail)
when the policy check is enabled. As the 401 is expected by the docker/caller, and then to ask token service which url is in the 401 header.
> Disable policy check when pull without bearer token

- src/pkg/scan/report/summary.go
- src/pkg/scan/report/summary_test.go
- src/pkg/scan/vuln/summary.go
> add scan by info in the scan report summary

- API/harbor/swagger.yaml
- src/common/models/project.go
- src/core/api/project.go
- src/core/api/project_test.go
- src/core/api/search.go
This commit fixes #9771
It compares the roles to return the one with highest permission in the
response of `GET /api/projects`.
In addition to that, it adds the role list to the response, because a
user can have multiple roles in a project.
It also removes the togglable attribute as it's not used anywhere.
> Add role list in project response

- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/api/config.go
- src/core/api/harborapi_test.go
- src/core/api/user.go
- src/core/api/user_test.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/core/filter/security_test.go
- src/testing/apitests/apilib/user_profile.go
This commit make case sensitivity configurable when the authentication
backend is auth proxy.
When the "http_authproxy_case_sensitive" is set to false, the name of
user/group will be converted to lower-case when onboarded to Harbor, so
as long as the authentication is successful there's no difference regardless
upper or lower case is used.  It will be mapped to one entry in Harbor's
User/Group table.
> Add configuration "case sensitive" to HTTP auth proxy

- API/harbor/swagger.yaml
- src/common/models/pro_meta.go
- src/core/api/metadata.go
- src/core/api/project.go
- src/core/middlewares/util/util.go
- src/pkg/scan/vuln/severity.go
- src/pkg/scan/vuln/severity_test.go
- src/portal/lib/src/project-policy-config/project-policy-config.component.ts
BREAKING CHANGE: the value negligible of severity in project metadata will change to none in the responses of project APIs
> feat(vuln-severity): map negligible to none to match CVSS v3 ratings

- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
As the background of Clair updated was disabled, and we populate clair db right after harbor deployed with existing data, so all Clair relevant test cases should be update as the data of this clair population.
> update clair nightly test cases since clair data has been solid for testing

- make/migrations/postgresql/0015_1.10.0_schema.up.sql
- src/core/api/immutabletagrule.go
- src/core/api/immutabletagrule_test.go
- src/pkg/immutabletag/controller_test.go
- src/pkg/immutabletag/dao/immutable_test.go
Fix #9681, add check before insert rules
> Avoid to create duplicated immutable tag rules in the same project

- src/core/main.go
- src/pkg/scan/dao/scanner/registration.go
- src/pkg/scan/init.go
- src/pkg/scan/init_test.go
- src/pkg/types/error.go
1. Fix name conflict when install internal clair adapter.
2. Remove all internal adapters when reinstall harbor without --with-clair flag
Closes #9767 
> fix(scanner): process scenario reinstall without clair flag

- .drone.yml
There is a new commit in harbor-e2e-engine:1.42, which is upgrade docker to the latest version, so drone.yml should be update to the new one.
> Update drone.yml for harbor-e2e-engine upgrade

- src/common/utils/oidc/helper.go
- src/common/utils/oidc/helper_test.go
- src/common/utils/oidc/secret.go
- src/common/utils/oidc/secret_test.go
- src/common/utils/oidc/testutils.go
- src/core/controllers/oidc.go
- src/core/filter/security.go
This commit refactors the flow to populate user info and verify CLI
secret in OIDC authentication.
It will call the `userinfo` backend of OIDC backend and fallback to
using the ID token if userinfo is not supported by the backend.
> Populate user groups during OIDC CLI secret verification

- src/core/api/project.go
- src/portal/src/app/project/summary/summary.component.html
The issue of limited guest info missing in summary page was cuased by PR #9490
> fix(limited-guest): fix limited guest info missing in summary page

- make/harbor.yml
All communication between internal components should bypass the proxy
Add chartmuseum, notary-server,clair-adapter to the no_proxy list in harbor.yml
> Failed to start harbor when proxy is set

- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Util.robot
The criteria of keyword Go Into Project is not strong for verify if it's in project repository page, so fix this issue by way of adding keyword 'Retry Double Keywords When Error'.
> Fix keyword of Go Into Project

- src/portal/src/app/sign-in/sign-in.component.html
- src/portal/src/app/sign-in/sign-in.component.ts
Currently when you click on the `About` link in the top right on the sign in page, the modal is not opened. This PR fixes this.
> Fix broken about dialog on sign in page

- tests/robot-cases/Group1-Nightly/Clair.robot
Clair DB has already been populated by existing data right after harbor deployed in nightly test, so Clair test case modify some CVE IDs for this Clair DB data.
> [Cherry-Pick 1.9.0] Modify CVE whitelist nightly test cases regarding to the solid Clair DB

- tests/robot-cases/Group1-Nightly/Common.robot
It's a temporary solution for quotas case, after internal registry in service, image size will not change any longer.
> Modify redis image size for verification as a temporary solution

- src/core/auth/authproxy/auth.go
- src/core/filter/security.go
- src/pkg/authproxy/http.go
- src/pkg/authproxy/http_test.go
This commit fixes #9869
It has some refactor to make sure the group is populated when user is
authenticated via tokenreview workflow.
> populate group list when doing token review

- tests/resources/Harbor-Pages/Replication.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
Add a replication scope keyword for waiting the completion of replication result. All replication test case must use this keyword to verify if image was pulled.
> [Nightly Test]Add a replication scope keyword for waiting the completion of replication result

- src/portal/src/app/project/tag-retention/tag-retention.component.ts
Fix tag-retention ui bug:   should refresh project info in ngOnInit methord
> Fix tag-retention ui bug

- tests/robot-cases/Group1-Nightly/Common.robot
As we like to use a local registry for nightly quotas test, so that the sample image will not be update without noticed, so modify quotas test case to use local image for pulling.
> Modify image source in quotas test case for local registry

- make/photon/prepare/utils/configs.py
CA bundle name start with '/' will break the os path join
> Fix ca bundle path join issue

- src/core/auth/authproxy/auth.go
- src/core/filter/security.go
- src/pkg/authproxy/http.go
- src/pkg/authproxy/http_test.go
This commit fixes #9869
It has some refactor to make sure the group is populated when user is
authenticated via tokenreview workflow.
> populate group list when doing token review - cherrypick to 1.10

- src/core/auth/authproxy/auth.go
- src/core/filter/security.go
- src/pkg/authproxy/http.go
- src/pkg/authproxy/http_test.go
This commit fixes #9869
It has some refactor to make sure the group is populated when user is
authenticated via tokenreview workflow.
> populate group list when doing token review - cherry pick to 1.9

- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Harbor-Pages/Project_Robot_Account.robot
- tests/resources/Harbor-Pages/Project_Robot_Account_Elements.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
1. Add nightly test case of Robot-Account; 2. In Go Into Repo keyword, filter element should not be clicked since list in loading state, so add some sleep and waiting for the cirlce icon is gone; 3. Move read-only test case in the end of common.robot.
> Add nightly test case of Robot-Account and fixed 2 issues

- make/migrations/postgresql/0012_1.9.4_schema.up.sql
- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/api/config_test.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/pkg/authproxy/http.go
- src/pkg/authproxy/http_test.go
This commit add an attribute to configurations, whose value is the
certificate of authproxy server.  When this attribute is set Harbor will
pin to this cert when connecting authproxy.
This value will also be part of the response of systemInfo API.
This commit will be cherrypicked to 1.10 and 1.9 branch.
> Support pinning to authproxy server's cert

- make/migrations/postgresql/0012_1.9.4_schema.up.sql
- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/api/config_test.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/pkg/authproxy/http.go
- src/pkg/authproxy/http_test.go
This commit add an attribute to configurations, whose value is the
certificate of authproxy server.  When this attribute is set Harbor will
pin to this cert when connecting authproxy.
This value will also be part of the response of systemInfo API.
This commit will be cherrypicked to 1.10 and 1.9 branch.
> Support pinning to authproxy server's cert - Cherrypick to 1.9

- make/migrations/postgresql/0012_1.9.4_schema.up.sql
- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/api/config_test.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/pkg/authproxy/http.go
- src/pkg/authproxy/http_test.go
This commit add an attribute to configurations, whose value is the
certificate of authproxy server.  When this attribute is set Harbor will
pin to this cert when connecting authproxy.
This value will also be part of the response of systemInfo API.
This commit will be cherrypicked to 1.10 and 1.9 branch.
> Support pinning to authproxy server's cert - Cherrypick to 1.10

- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/api/config.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/auth/authproxy/test/server.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/core/filter/security_test.go
- src/pkg/authproxy/http_test.go
This commit removes the attribute to control case-sensitivity from
authproxy setting.
The result in token review status will be used as the single source of
truth, regardless the case of the letters in group names and user names.
> Get rid of case-sensitivity in authproxy setting

- tests/robot-cases/Group1-Nightly/Common.robot
As we like to use a local registry for nightly quotas test, so that the sample image will not be update without noticed, so modify quotas test case to use local image for pulling.
> [Cherry-Pick-To-1.10] Add local registry for nightly quotas test

- src/portal/src/lib/_animations/slide-in-out.animation.ts
- src/portal/src/lib/components/operation/operation.component.css
- src/portal/src/lib/components/operation/operation.component.html
- src/portal/src/lib/components/operation/operation.component.ts
Fix #9176 ,fix #9175 
1.New one(temporary env: https://10.161.67.1:8082)
When a new event occurs, the event panel won't be opened automatically, but will show a badges.
The opened panel will be closed in 5 seconds automatically after your mouse leaves the panel.
> Modify event panel

- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/api/config.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/auth/authproxy/test/server.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/core/filter/security_test.go
- src/pkg/authproxy/http_test.go
This commit removes the attribute to control case-sensitivity from
authproxy setting.
The result in token review status will be used as the single source of
truth, regardless the case of the letters in group names and user names.
> Get rid of case-sensitivity in authproxy setting -- Cherrypick to v1.9

- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/api/config.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/auth/authproxy/test/server.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/core/filter/security_test.go
- src/pkg/authproxy/http_test.go
This commit removes the attribute to control case-sensitivity from
authproxy setting.
The result in token review status will be used as the single source of
truth, regardless the case of the letters in group names and user names.
> Get rid of case-sensitivity in authproxy setting -- Cherrypick to v1.10

- Makefile
- api/harbor/README
- docs/configure_swagger.md
- make/photon/portal/Dockerfile
- tests/swaggerchecker.sh
- update swagger yaml file reference in `Makefile`
- update swagger yaml file reference in `README`
- update swagger yaml file reference in `docs/configure_swagger.md`
- update swagger yaml file reference in `make/photon/portal/Dockerfile`
- update swagger yaml file reference in `tests/swaggerchecker.sh`
> chore[api]:rename API folder to api

- src/pkg/scan/rest/v1/client.go
- add the missing resolver calls to the v1 client
fix #10108
> fix[scan]:missing header in v1 client

- make/migrations/postgresql/0030_1.11.0_schema.up.sql
- src/go.mod
- src/pkg/artifact/controller.go
- src/pkg/artifact/manager/dao/model.go
- src/pkg/artifact/manager/manager.go
- src/pkg/artifact/model/model.go
- src/pkg/artifact/model/model_test.go
This commits does some basic init work for supporting OCI:
1. Create the artifact and tag model
2. Create database tables
> Create the models for OCI supporting

- src/core/api/statistic.go
statistic API use security Context to list project rather than calling
projectmanager directly, such that the group membership will be taken
into account.
fixes #10230
It should be cherry picked to 1.9.x and 1.10.x branches
> Stastics API should handle group members

- src/core/api/statistic.go
statistic API use security Context to list project rather than calling
projectmanager directly, such that the group membership will be taken
into account.
fixes #10230
It should be cherry picked to 1.9.x and 1.10.x branches
> Stastics API should handle group members - cherrypick to 1.10

- src/core/api/statistic.go
statistic API use security Context to list project rather than calling
projectmanager directly, such that the group membership will be taken
into account.
fixes #10230
It should be cherry picked to 1.9.x and 1.10.x branches
> Stastics API should handle group members -cherrypick 1.9

- api/harbor/swagger.yaml
- src/common/dao/dao_test.go
- src/common/dao/register.go
- src/common/dao/role.go
- src/common/dao/user.go
- src/common/models/user.go
- src/common/security/local/context.go
- src/common/security/local/context_test.go
- src/core/api/harborapi_test.go
- src/core/api/user.go
- src/core/auth/ldap/ldap.go
- src/core/auth/ldap/ldap_test.go
- src/core/auth/uaa/uaa.go
- src/core/filter/security_test.go
- src/testing/apitests/apilib/user.go
- tests/apitests/python/library/user.py
- tests/apitests/python/test_ldap_admin_role.py
- tests/robot-cases/Group3-Upgrade/prepare.py
- tests/robot-cases/Group3-Upgrade/prepare_v17.py
Separate the HasAdminRole(In DB) with the privileges from external auth, and use user.HasAdminPrivilege to check if the current user has admin privilege.
Fix issue: #10012
> Fix admin permission not revoked when removed from LDAP admin group(Do Not Merge)

- src/common/api/base.go
- src/common/dao/base.go
- src/common/dao/config.go
- src/common/dao/dao_test.go
- src/core/api/base.go
- src/core/api/immutabletagrule.go
- src/core/middlewares/immutable/handler.go
- src/core/middlewares/util/error/immutable.go
- src/internal/error/errors.go
- src/pkg/immutabletag/dao/immutable.go
1, Leverage go v1.13 new error feature
2, Define genernal error OCI format, so that /v2 API could return a OCI compatible error
> add OCI error format support

- src/core/service/token/token.go
This commit disables XSRF check for "service/token" so that when
containerd sends `POST` it will not return 403 and containerd can
fallback to `GET` to complete the workflow.
Fixes #10305
> Disable XSRF check for /service/token

- src/core/filter/security.go
- src/core/filter/security_test.go
This commit will make the "tokenreview" security filter onboard
user if the request carries a valid token.  If the "skipsearch" flag in
http_auth setting is set to false the onboard will fail.
> Onboard user when doing token review

- src/core/filter/security.go
- src/core/filter/security_test.go
This commit will make the "tokenreview" security filter onboard
user if the request carries a valid token.  If the "skipsearch" flag in
http_auth setting is set to false the onboard will fail.
> Onboard user when doing token review - 1.9 cherrypick

- src/core/filter/security.go
- src/core/filter/security_test.go
This commit will make the "tokenreview" security filter onboard
user if the request carries a valid token.  If the "skipsearch" flag in
http_auth setting is set to false the onboard will fail.
> Onboard user when doing token review - cherrypick to 1.10

- src/core/service/token/token.go
This commit disables XSRF check for "service/token" so that when
containerd sends `POST` it will not return 403 and containerd can
fallback to `GET` to complete the workflow.
Fixes #10305
> Disable XSRF check for /service/token - cherry pick to 1.10

- src/core/service/token/token.go
This commit disables XSRF check for "service/token" so that when
containerd sends `POST` it will not return 403 and containerd can
fallback to `GET` to complete the workflow.
Fixes #10305
> Disable XSRF check for /service/token - cherry pick to 1.9

- make/harbor.yml.tmpl
- make/photon/prepare/Dockerfile.base
- make/photon/prepare/main.py
- make/photon/prepare/templates/core/env.jinja
- make/photon/prepare/templates/registry/config.yml.jinja
- make/photon/prepare/utils/cert.py
- make/photon/prepare/utils/configs.py
- make/photon/prepare/utils/misc.py
- make/photon/prepare/utils/registry.py
- src/core/config/config.go
This commit updates `prepare` and templates to populate the credential
for registry for basic authentication.
A temporary flag `registry_use_basic_auth` was added to avoid breakage.
It MUST be removed before the release.
> Populate basic auth information for registry

- src/replication/transfer/image/transfer.go
Remove the workaround for blocking manifest list in replication
> Remove the workaround for blocking manifest list in replication

- src/core/filter/orm.go
- src/core/main.go
- src/internal/orm/orm.go
- src/internal/orm/orm_test.go
- src/internal/orm/tx.go
1. Get and set orm from context.
2. Add WithTransaction decorator make func run in transaction.
3. Support nested transaction by Savepoint.
> feat(orm): add orm support with context

- src/pkg/scan/dao/scanner/registration.go
Use new created ormer for transaction in SetDefaultRegistration
Closes #10284
> fix(scanner): use new created ormer for transaction

- api/harbor/swagger.yaml
- src/core/api/robot_test.go
- src/pkg/robot/controller.go
- src/pkg/robot/controller_test.go
- src/pkg/robot/model/robot.go
- tests/apitests/python/library/project.py
- tests/apitests/python/test_robot_account.py
Update API of creating robot accout, user can specify expiration time per account.
> add expiration data time when to create a robot account

- src/pkg/scan/dao/scanner/registration.go
Use new created ormer for transaction in SetDefaultRegistration
Closes #10284
> [Cherry pick]fix(scanner): use new created ormer for transaction

- src/replication/adapter/awsecr/adapter.go
fix #10264 
aws ecr didn't implement standard oci delete manifest api, that we have to call its sdk
> fix(replication): aws ecr delete image

- .github/workflows/CI.yml
- tests/travis/api_run.sh
Sometimes github action test case will fail
1. UTTEST jobservice/period, 10 minutes timeout panic
2. docker push mysql with api, 30s timeout fail
These seems relative with the latest golang 1.13.6, so use the same sdk golang 1.13.4 as src build
> fix(cicd) Use fixed golang version 1.13.4 and fail early

- Makefile
The http://central.maven.org is not available now so change the download
link of swagger-codegen-cli to https://repo1.maven.org
> build(swagger): change download link of swagger-codegen-cli

- Makefile
The http://central.maven.org is not available now so change the download
link of swagger-codegen-cli to https://repo1.maven.org
> [Cherry pick]build(swagger): change download link of swagger-codegen-cli

- tests/resources/Docker-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group0-Util/notary-push-image.sh
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
In nightly test, images for tests were pulled from docker-hub, and sometime in an rare occasion, client will fail to contact docker-hub like timeout error, so we like to pull image from an internal harbor registry with no network issue invovled.
> Switch registry from docker-hub ot internal harbor registry

- src/server/middleware/manifestinfo/manifest_info.go
- src/server/middleware/manifestinfo/manifest_info_test.go
- src/server/middleware/util.go
To add a new middleware to resolve the manifest information from request path, then pass
it into the request context for later use.
> add get manifest information middleware in new v2 hanlder

- src/server/middleware/regtoken/regtoken.go
- src/server/middleware/regtoken/regtoken_test.go
- src/server/middleware/util.go
- src/server/registry/handler.go
To move the regtoken middlware to new v2 handler framework, it parses the docker pull bearer token and check whether it's a scanner pull.
> add regtoken middleware in new v2 handler

- tests/apitests/python/library/docker_api.py
Sometimes test case test_robot_account.py may failed with docker push read timeout in github action CI.
Try increase the docker client timeout.
> Fix githubactions testcase timeout

- src/jobservice/common/list/list.go
- src/jobservice/common/list/list_test.go
- src/jobservice/common/rds/keys.go
- src/jobservice/common/rds/scripts.go
- src/jobservice/common/rds/utils.go
- src/jobservice/hook/hook_agent.go
- src/jobservice/hook/hook_agent_test.go
- src/jobservice/hook/hook_client_test.go
- src/jobservice/job/impl/context_test.go
- src/jobservice/job/impl/sample/job.go
- src/jobservice/job/models.go
- src/jobservice/job/tracker.go
- src/jobservice/job/tracker_test.go
- src/jobservice/lcm/controller.go
- src/jobservice/lcm/controller_test.go
- src/jobservice/mgt/manager.go
- src/jobservice/mgt/manager_test.go
- src/jobservice/period/basic_scheduler.go
- src/jobservice/period/basic_scheduler_test.go
- src/jobservice/period/enqueuer.go
- src/jobservice/period/enqueuer_test.go
- src/jobservice/period/policy_store.go
- src/jobservice/period/policy_store_test.go
- src/jobservice/period/scheduler.go
- src/jobservice/runner/redis.go
- src/jobservice/runner/redis_test.go
- src/jobservice/runtime/bootstrap.go
- src/jobservice/worker/cworker/c_worker.go
- src/jobservice/worker/cworker/reaper.go
- src/jobservice/worker/cworker/reaper_test.go
- improve the status hook sending/resending approach
- improve the status compare and set approach
- simplify the relevant flow
- add reaper to fix the out of sync jobs
- fix #10244 , fix #9963
> fix[jobservice]:job status is hung after restart

- src/api/artifact/abstractor/abstractor.go
- src/api/artifact/abstractor/abstractor_test.go
- src/api/artifact/abstractor/resolver/resolver.go
- src/api/artifact/abstractor/resolver/resolver_test.go
Try to parse the type of the artifact based on the media type when no resolver found, if parse failed, set it's type to unknown. This won't block the pushing for artifacts that has no resolver registered in Harbor
> Try to parse the type of the artifact based on the media type when no resolver found

- src/common/config/context.go
- src/jobservice/job/impl/context.go
- src/pkg/robot/controller.go
- src/pkg/robot/model/robot.go
- src/pkg/scan/api/scan/base_controller.go
- src/pkg/scan/api/scan/base_controller_test.go
- src/pkg/scan/job.go
- src/pkg/scan/job_test.go
- src/pkg/scan/rest/v1/models.go
Before submit scan job the authorization computed and send to the scan
job and then scan job may in pending state for a long time before it
begins to run.
When the pending more than 30 min which is the default bearer token
expiration time, the authorization had been expired when execute scan
job.
This PR changes the time of computing authorization from before
submitting the scan job to executing the job.
Closes #10325
> fix(scan-job): fetch bearer token for scanner adapter in scan job

- src/core/main.go
- src/core/middlewares/middlewares.go
- src/core/middlewares/middlewares_test.go
- src/internal/response_buffer.go
- src/server/middleware/middleware.go
- src/server/middleware/skipper.go
- src/server/middleware/skipper_test.go
- src/server/middleware/transaction/transaction.go
- src/server/middleware/transaction/transaction_test.go
Add transaction middleware for v2 and v2.0 APIs.
> feat(middleware): add transaction middleware for v2 and v2.0 APIs

- src/core/middlewares/contenttrust/handler.go
- src/core/middlewares/contenttrust/handler_test.go
- src/core/middlewares/regtoken/handler.go
- src/core/middlewares/url/handler.go
- src/core/middlewares/url/handler_test.go
- src/core/middlewares/util/util.go
- src/core/middlewares/vulnerable/handler.go
- src/server/middleware/artifactinfo/artifact_info.go
- src/server/middleware/artifactinfo/artifact_info_test.go
- src/server/middleware/util.go
- src/server/middleware/v2authz/authz.go
- src/server/middleware/v2authz/authz_test.go
- src/server/registry/error/error.go
- tests/apitests/python/test_project_quota.py
When the registry shifts from token auth to basic auth, we'll use the middleware to check permission.
This commit add middlewares for populate the artifact info and check
permission based on request to /v2/* api via security context
The change in `/src/core/xxx` can be disregarded because in the end all middlewares will be moved to `/src/server/middleware`
> Add middlewares for permission checking for v2 API

- make/harbor.yml.tmpl
- make/photon/prepare/templates/registry/config.yml.jinja
- make/photon/prepare/utils/configs.py
- make/photon/prepare/utils/registry.py
- src/api/artifact/abstractor/blob/fetcher.go
- src/common/utils/registry/auth/basicauthorizer.go
- src/common/utils/registry/auth/basicauthorizer_test.go
- src/core/api/utils.go
- src/core/utils/utils.go
- src/jobservice/job/impl/utils/utils.go
- src/server/middleware/util.go
- src/server/middleware/v2auth/auth.go
- src/server/middleware/v2auth/auth_test.go
- src/server/registry/handler.go
- src/server/registry/handler_test.go
- src/server/registry/route.go
- tests/apitests/python/library/docker_api.py
- tests/apitests/python/test_robot_account.py
- tests/robot-cases/Group0-BAT/API_DB.robot
1. Add basic authorizer for registry which modify the request
to add basic authorization header to request based on configuration.
2. Set basic auth header for proxy when accessing registry
3. Switche the registry to use basic auth by default and use the basic
authorizer to access Harbor.
4. Make necessary change to test cases, particularly
"test_robot_account.py" and "docker_api.py", because the error is
changed after siwtched to basic auth from token auth.  #10604 is opened
to track the follow up work.
> Switch to basic authentication for registry

- .github/codecov-ut-config/codecov.yml
- .github/workflows/CI.yml
Fix #10405 
Add ut coverage reports provided by codecov for every PR(see below report from a robot account)
The coverage is the sum of ui-ut coverage and backend-ut coverage(can not be provided individually so far). We can see individual reports on detail page
> Add ut coverage report

- src/common/security/context.go
- src/common/security/local/context.go
- src/common/security/robot/context.go
- src/common/security/secret/context.go
- src/core/api/base.go
- src/core/api/config.go
- src/core/filter/security.go
- src/core/filter/security_test.go
- src/core/middlewares/inlet.go
- src/core/service/token/creator.go
- src/core/service/token/token_test.go
- src/server/middleware/v2auth/auth.go
- src/server/middleware/v2auth/auth_test.go
1. Add `NewContext` and `FromContext` funcs in security pkg.
2. Add `Name` func in `security.Context` interface to make the checking
for the `/api/internal/configurations` API clear.
3. Get the security from the context to prepare change the security
filter to middleware.
4. Remove `GetSecurityContext` in filter pkg.
> refactor(security): add `NewContext` and `FromContext` to security pkg

- api/v2.0/swagger.yaml
- src/api/artifact/model.go
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/pkg/artifact/model.go
As we only provide the API to get artifact information via project name, repository name and digest, the digest of child artifact must be returned
> Add child artifact digest in reference model

- Makefile
fail early for gen apis if build swagger img failed
> build(gen-apis): fail early for gen apis if build swagger img fail

- tests/apitests/python/test_project_quota.py
- tests/apitests/python/test_robot_account.py
- tests/resources/Helm-Util.robot
- tests/resources/TestCaseBody.robot
Fix description issue of test in robot account API test and issue of Helm3 test
1. Fix issue that test step descriton was mismatch with test step;
2. Wrong helm command was used in Helm3 test, replace helm with helm3;
3. In API test, images were pulled from docker-hub registry, images size changed sometime, so we like to use internal registry.
> [Cherry-Pick To 1.10] Fix description issue of test in robot account and quotas API test

- src/jobservice/common/list/list.go
- src/jobservice/common/list/list_test.go
- src/jobservice/common/rds/keys.go
- src/jobservice/common/rds/scripts.go
- src/jobservice/common/rds/utils.go
- src/jobservice/hook/hook_agent.go
- src/jobservice/hook/hook_agent_test.go
- src/jobservice/hook/hook_client_test.go
- src/jobservice/job/impl/context_test.go
- src/jobservice/job/impl/sample/job.go
- src/jobservice/job/models.go
- src/jobservice/job/tracker.go
- src/jobservice/job/tracker_test.go
- src/jobservice/lcm/controller.go
- src/jobservice/lcm/controller_test.go
- src/jobservice/mgt/manager.go
- src/jobservice/mgt/manager_test.go
- src/jobservice/period/basic_scheduler.go
- src/jobservice/period/basic_scheduler_test.go
- src/jobservice/period/enqueuer.go
- src/jobservice/period/enqueuer_test.go
- src/jobservice/period/policy_store.go
- src/jobservice/period/policy_store_test.go
- src/jobservice/period/scheduler.go
- src/jobservice/runner/redis.go
- src/jobservice/runner/redis_test.go
- src/jobservice/runtime/bootstrap.go
- src/jobservice/worker/cworker/c_worker.go
- src/jobservice/worker/cworker/reaper.go
- src/jobservice/worker/cworker/reaper_test.go
- improve the status hook sending/resending approach
- improve the status compare and set approach
- simplify the relevant flow
- add reaper to fix the out of sync jobs
- fix #10244 , fix #9963
> [CHERRY-PICK] fix[jobservice]:job status is hung after restart

- tests/apitests/python/test_project_quota.py
- tests/resources/Harbor-Pages/Project.robot
In project quotas API test, pull images from goharbor namespace instead of library.
> Fix project quotas API test issue

- api/v2.0/swagger.yaml
- src/api/artifact/abstractor/abstractor.go
- src/api/artifact/abstractor/abstractor_test.go
- src/api/artifact/abstractor/resolver/chart/chart.go
- src/api/artifact/abstractor/resolver/chart/chart_test.go
- src/api/artifact/abstractor/resolver/image/index.go
- src/api/artifact/abstractor/resolver/image/index_test.go
- src/api/artifact/abstractor/resolver/image/manifest_v1.go
- src/api/artifact/abstractor/resolver/image/manifest_v1_test.go
- src/api/artifact/abstractor/resolver/image/manifest_v2.go
- src/api/artifact/abstractor/resolver/image/manifest_v2_test.go
- src/api/artifact/abstractor/resolver/resolver.go
- src/api/artifact/abstractor/resolver/resolver_test.go
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/artifact/descriptor/descriptor.go
- src/api/artifact/model.go
- src/common/rbac/const.go
- src/common/rbac/project/util.go
- src/common/rbac/project/visitor_role.go
- src/internal/context.go
- src/internal/context_test.go
- src/server/middleware/apiversion/api_version.go
- src/server/middleware/apiversion/api_version_test.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/repository.go
- src/server/v2.0/route/route.go
- src/testing/api/artifact/abstractor/resolver/resolver.go
- src/testing/api/artifact/controller.go
This commit implements the API to get build history of image with manifest version 2 and populates the addition links when listing/getting the artifact
> Implement get addition API for image

- src/core/middlewares/middlewares.go
- src/core/middlewares/middlewares_test.go
- src/server/middleware/skipper.go
1. Escape and clean request path for `legacyAPISkipper`.
2. Escape and clean request path for `MethodAndPathSkipper`.
> fix(middleware): escape and clean path for the skipper

- src/portal/src/app/app.module.ts
- src/portal/src/app/base-href-intercept.service.spec.ts
- src/portal/src/app/base-href-intercept.service.ts
> Switch APIs to v2.0

- src/api/artifact/abstractor/resolver/image/index.go
- src/api/artifact/abstractor/resolver/image/index_test.go
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/go.mod
- src/pkg/artifact/dao/dao.go
- src/pkg/artifact/dao/dao_test.go
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/server/error/error.go
- src/server/error/error_test.go
- src/server/middleware/util.go
- src/server/middleware/v2auth/auth.go
- src/server/registry/proxy.go
- src/testing/pkg/artifact/manager.go
1. As "List" method of artifact DAO doesn't return the artifacts that referenced by other and without tag, so we introduce a new method "GetByDigest" to check the existence of artifact
2. The "Www-Authenticate" header is needed to be returned when the request is unauthorized. This is required in the OCI distribution spec and is needed when pushing CNAB
> Fix bugs when pushing image(with index) and CNAB

- api/v2.0/swagger.yaml
- src/api/artifact/abstractor/resolver/image/manifest_v2.go
- src/api/artifact/abstractor/resolver/image/manifest_v2_test.go
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/artifact/model.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/model/artifact.go
Move the scan overview populating logic to API handler to avoid importing cycle
> Move the scan overview populating logic to API handler

- make/migrations/postgresql/0030_1.11.0_schema.up.sql
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/pkg/artifact/dao/dao.go
- src/pkg/artifactrash/dao/dao.go
- src/pkg/artifactrash/dao/dao_test.go
- src/pkg/artifactrash/manager.go
- src/pkg/artifactrash/manager_test.go
- src/pkg/artifactrash/model/model.go
- src/registryctl/api/registry.go
- src/testing/pkg/artifactrash/manager.go
1, move the deleted artifact into trash
2, disable GC to delete the untagged manifest
> add artifact trash manager

- README.md
This PR fixes the broken Swagger API link in the README.
> Update Swagger link

- api/v2.0/legacy_swagger.yaml
- make/migrations/postgresql/0030_2.0.0_schema.up.sql
- src/common/dao/admin_job.go
- src/common/dao/admin_job_test.go
- src/common/models/adminjob.go
- src/core/api/admin_job.go
- src/core/api/models/admin_job.go
- src/core/api/models/admin_job_test.go
- src/core/api/reg_gc.go
- src/core/api/reg_gc_test.go
- src/jobservice/job/impl/default_context.go
- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/gc/garbage_collection_test.go
- src/jobservice/job/impl/gc/util.go
- src/jobservice/runner/redis_test.go
- src/jobservice/worker/cworker/c_worker_test.go
- src/pkg/artifactrash/dao/dao.go
- src/pkg/artifactrash/dao/dao_test.go
- src/pkg/artifactrash/manager.go
- src/pkg/artifactrash/manager_test.go
- src/testing/apitests/apilib/admin_job_req.go
- src/testing/pkg/artifactrash/manager.go
1, set harbor to readonly
2, select the candidate artifacts from Harbor DB.
3, call registry API(--delete-untagged=false) to delete manifest bases on the results of #2
4, clean keys of redis DB of registry, clean artifact trash and untagged from DB.
5, roll back readonly.
> Revise the GC job flow

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
- src/api/artifact/abstractor/abstractor.go
- src/api/artifact/abstractor/abstractor_test.go
- src/api/artifact/abstractor/resolver/chart/chart.go
- src/api/artifact/abstractor/resolver/chart/chart_test.go
- src/api/artifact/abstractor/resolver/cnab/cnab.go
- src/api/artifact/abstractor/resolver/cnab/cnab_test.go
- src/api/artifact/abstractor/resolver/image/index.go
- src/api/artifact/abstractor/resolver/image/manifest_v2.go
- src/api/artifact/abstractor/resolver/image/manifest_v2_test.go
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/pkg/artifact/dao/dao.go
- src/pkg/artifact/dao/dao_test.go
- src/pkg/artifact/dao/model.go
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/pkg/artifact/model.go
- src/pkg/blob/dao/dao_test.go
- src/pkg/blob/manager_test.go
- src/server/middleware/immutable/pushmf_test.go
- src/server/registry/manifest.go
- src/server/v2.0/handler/artifact.go
- src/testing/api/artifact/controller.go
- src/testing/pkg/artifact/manager.go
As we store the repository name in the artifact table, we can use it direclty in the code to reduce the database query
> Use the repository name of artifact model

- RELEASES.md
> Update the support matrix

- src/server/middleware/v2auth/auth.go
This is needed for "docker manifest" commands: https://github.com/docker/cli/issues/989
> Add "Docker-Distribution-Api-Version" header for the 401 response of registry API

- src/core/filter/security.go
As we swtich to basic auth for /v2/* API
The CLI secret should handle /v2/* API so that OIDC user can use the
secret to do push/pull
This commit makes such change.
> CLI Secret should handle /v2/* API

- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/artifact/model.go
- src/api/tag/controller.go
- src/api/tag/controller_test.go
- src/api/tag/model.go
- src/pkg/retention/dep/client_test.go
- src/server/middleware/immutable/deletemf.go
- src/server/middleware/immutable/pushmf.go
- src/server/registry/tag.go
- src/server/registry/tag_test.go
- src/server/v2.0/handler/artifact.go
- src/testing/api/artifact/controller.go
- src/testing/api/tag/controller.go
- tests/apitests/python/test_sign_image.py
use the tag controller to handle CRUD of tags, especially the delete scenario, it could validate
the immutable and signature. And move the code of tag handling from artifact controller to tag controller
> add tag controller

- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/pkg/artifact/model.go
- src/pkg/artifact/model_test.go
- src/testing/api/artifact/controller.go
Add Walk method to artifact controller which walks the artifact tree rooted at root, calling walkFn for each artifact in the tree, including root.
> feat(artifact): add Walk method to artifact controller

- api/v2.0/swagger.yaml
- make/migrations/postgresql/0030_2.0.0_schema.up.sql
- src/pkg/audit/dao/dao.go
- src/pkg/audit/dao/dao_test.go
- src/pkg/audit/manager.go
- src/pkg/audit/manager_test.go
- src/pkg/audit/model/model.go
- src/server/v2.0/handler/auditlog.go
- src/server/v2.0/handler/auditlog_test.go
- src/server/v2.0/handler/handler.go
1, add API entry for get audit logs
2. add audit log manager to hanlder CRUD
Use the new format of audit log to cover differernt resource, artifact/tag/repostory/project
> add audit logs API

- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/repository.go
Use project controller rather than the manager in API handlers
> Use project controller rather than the manager in API handlers

- src/core/middlewares/middlewares.go
Admin must have a way to switch off the readonly by call configuration api,
either internal or external.
> skip configuration update in readonly mode

- src/jobservice/runner/redis.go
- src/jobservice/runner/redis_test.go
- src/jobservice/runtime/bootstrap.go
- src/jobservice/worker/cworker/c_worker_test.go
- refactor default context creation to avoid data race
- refactor the timer interval in c_worker UT cases to avoid receiving signals at the same time
> fix[js]:fix ut case faulure

- src/internal/error/errors.go
- src/server/error/error.go
- src/server/middleware/immutable/pushmf.go
- src/server/registry/catalog.go
- src/server/registry/manifest.go
- src/server/registry/manifest_test.go
- src/server/registry/tag.go
- src/server/router/router.go
- src/server/router/router_test.go
1, Return DIGEST_INVALID error in delete manifest instead of NOT_FOUND
2, Disable return 500 in immutable middleware
3, Return empty array in catalog and tags API instead of null
> fix Conformance testing failure

- src/pkg/robot/controller.go
- src/pkg/robot/controller_test.go
- src/pkg/robot/model/robot.go
"-1" means the robot account is a permanent account, no expiration time set.
The ExpiresAt claim is optional, so if it's not set, it will still be considered a valid claim
> add no expriation limited robot account

- src/server/error/error.go
- src/server/error/error_test.go
- src/server/middleware/v2auth/auth.go
If "Www-Authenticate" header is set for Harbor management API, the browser will show a basic auth dialog when get 401 error, this commit moves the header to the registry APIs
> Only set "Www-Authenticate" header for registry API

- docs/1.10/working-with-projects/create-projects/_index.md
This PR fixes image links broken due to misnaming a Markdown file.
> Fix image links

- src/server/middleware/path/path.go
- src/server/middleware/path/path_test.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/handler.go
- src/server/v2.0/handler/repository.go
- src/server/v2.0/handler/util.go
- src/server/v2.0/handler/util_test.go
fix(api): escape path paramters before APIs and unescape them in the Prepare of operations
1. Escape the path paramters before the APIs.
2. Unescape the path paramters in the Prepare stage of the swagger
operations.
Closes #10860
> fix(api): escape path paramters before APIs and unescape them in the Prepare of operations

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
- src/api/artifact/abstractor/resolver/cnab/cnab.go
- src/api/artifact/abstractor/resolver/image/index.go
- src/pkg/artifact/dao/model.go
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/pkg/artifact/model.go
Persistent the URLs and annotations of artifact references in database
> Persistent the URLs and annotations of artifact references in database

- api/v2.0/swagger.yaml
- make/migrations/postgresql/0030_2.0.0_schema.up.sql
- src/core/api/notification_policy.go
- src/server/v2.0/route/legacy.go
Add API for query supported event types and notify types; 
Return policy name in last trigger info; 
Remove project_id unique constraint in table notification_policy
> Add API for query supported event types and notify types

- api/v2.0/swagger.yaml
- src/api/artifact/model.go
- src/api/tag/model.go
- src/common/models/label.go
- src/pkg/artifact/model.go
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/model/artifact.go
Using "x-go-type" may cause the inconsistence between the swagger definition and the real data model
> Remove the "x-go-type" for artifact definition in swagger

- Makefile
- src/go.sum
enhance govet check performance by remote -L1 param, which will make the check cost from about 3 minutes to 10 seconds
> feat(ci) enhance govet check performance

- src/replication/adapter/adapter.go
- src/replication/adapter/adapter_test.go
fix #10322 
The replication adapters should have a fixed order shown on UI
> feat(replication) sort the adapters shown on UI

- src/core/api/registry.go
fix #10077 
update healthy status immediately after added or update, as it has already done check when request api.
> enhance(replication) update healthy status immediately

- docs/compile_guide.md
- docs/configure_https.md
- docs/configure_swagger.md
- docs/configure_user_settings.md
- docs/customize_look&feel_guide.md
- docs/customize_token_service.md
- docs/demo_server.md
- docs/developer_guide_i18n.md
- docs/harbor_compatibility_list.md
- docs/import_vulnerability_data.md
- docs/installation_guide.md
- docs/kubernetes_deployment.md
- docs/manage_role_by_ldap_group.md
- docs/migration_guide.md
- docs/permissions.md
- docs/registry_landscape.md
- docs/ui_contribution_get_started.md
- docs/upgradetest.md
- docs/use_make.md
- docs/use_notary.md
- docs/user_guide.md
All of the old stub pages should now point to the new docs site.
@michmike @jonasrosland @lucperkins is this OK? Thanks!
> Updating the redirects in the old page stubs to point to new site.

- src/internal/selector/selector.go
- src/internal/selector/selectors/doublestar/selector.go
- src/internal/selector/selectors/doublestar/selector_test.go
- src/internal/selector/selectors/index/index.go
- src/internal/selector/selectors/label/selector.go
- src/pkg/immutabletag/match/rule/match.go
- src/pkg/retention/launcher.go
- src/pkg/retention/policy/alg/or/processor_test.go
- src/pkg/retention/policy/builder.go
- src/pkg/retention/policy/rule/models.go
- src/portal/src/app/project/project-detail/project-detail.component.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.html
- src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.scss
- src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/retention.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.html
- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
We will add a checkbox for user to decide whether to keep the untagged images
1.     UI change, add a checkbox after Tags line .
2.     Protocol change, add a new optional field “extras”, which is a map
cid:image002.png@01D5F0B0.D7AAE830
The default value for “untagged” is False if this “extras”field not exist
3.     Code logic
a)      tags matching **, untagged : all images will be retained
b)      tags matching ** : only tagged images will be retained
c)      tags excluding ** : only untagged images will be retained
d)      tags excluding **, untagged : no images will be retained
e)      tags matching latest, untagged : images with tag latest and all untagged images will be retained
4.     upgrade logic
old policy not changed, when deal with retention job, behavior is as untagged …
> [OCI] add checkbox for user to control whether remove untagged image

- src/server/middleware/transaction/transaction.go
- src/server/middleware/transaction/transaction_test.go
Type assertion not work when the ctx in the request changed in the next
handler, so change to use value in the ctx to decide whether to commit
tx.
> fix(transaction): change to use value in the ctx to decide whether commit tx

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
- src/migration/migration.go
As the count quota is against artifact rather than tag in 2.0, the count usage should be recalculated
> Repair the count usage during the upgrading 

- src/core/middlewares/middlewares.go
- src/pkg/notification/notification.go
- src/server/middleware/notification/notification.go
- src/server/middleware/notification/notification_test.go
the notification is for send out the event after DB transaction complete.
It's safe to send hook as this middleware is after transaction in the response path.
> add notification middleware

- .github/workflows/CI.yml
This will remove the docs folder from triggering CI runs.
Signed-off-by: jonasrosland <jrosland@vmware.com>
> Remove docs folder from CI runs

- src/api/scan/base_controller.go
- src/api/scan/base_controller_test.go
The v2auth middleware will check whether the requestor  has the pull or
push permissions for the repository, and forbid the request when the
requestor does not have the permission.  We need to assign repository
pulling permission to the robot account for the scanner, otherwise
scanner will be failed to pull the artifact.
> fix(scan): assign repository pull access policy to robot account when scan artifact

- src/pkg/q/builder.go
- src/pkg/q/builder_test.go
- src/server/v2.0/handler/base.go
- src/server/v2.0/handler/base_test.go
Escapse the repository name in the link header returned in response
> Escapse the repository name in the link header returned in response

- src/pkg/registry/client.go
- src/server/registry/manifest.go
Filter the pulling manifest request from replication service so that the audit log will not record the pulling action
> Filter the pulling manifest request from replication service

- src/core/api/base.go
- src/core/api/retention.go
- src/core/filter/security.go
- src/core/filter/security_test.go
- src/core/service/token/creator.go
Remove the project manager introduced when integrated with Admiral from the context
> Remove the project manager from context

- make/photon/prepare/utils/configs.py
When iinternal_tls is empty, prepare should works as usual
> Fix: return error when internal_tls_not_provided

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
Fixes #10786 by increaseing the length of src_resource and dst_resource to 256
> Increase the length the columns (src_resource, dst_resource)of replication_task

- api/v2.0/legacy_swagger.yaml
- api/v2.0/swagger.yaml
The API definition is put on the wrong swagger file introduced by PR #11029 by mistake
> Move the webhook event API definition to legacy_swagger.yaml

- src/pkg/q/builder.go
- src/pkg/q/builder_test.go
- src/server/v2.0/handler/base_test.go
The query string is encoded by UI, and we have to unescape the "=" in "q=tag=nil",
otherwise, the query doesn't work, and returns 400
> Unescape tags query when to list artifact

- src/api/repository/controller.go
- src/api/repository/controller_test.go
Fixes #10997 by looping the artifact candidates until all of them are deleted
> Fix bug when deleting the repository

- api/v2.0/swagger.yaml
- src/server/middleware/path/path.go
- src/server/middleware/path/path_test.go
Add "_self" suffix for repository API to avoid conflict
> Add "_self" suffix for repository API to avoid conflict

- src/internal/orm/query.go
For the Andlist, the query setter should ignore it
> Fix orm query setter issue

- docs/1.10/administration/configuring-replication/create-replication-endpoints.md
- docs/1.10/administration/configuring-replication/create-replication-rules.md
- docs/1.10/working-with-projects/project-configuration/_index.md
- docs/1.10/working-with-projects/project-configuration/create-robot-accounts.md
- docs/1.10/working-with-projects/using-api-explorer/_index.md
A few docs pages still had wrong links for images, and some wonky formatting.
We should run a Markdown linter on the docs in the near future to make sure everything looks proper.
Signed-off-by: jonasrosland <jrosland@vmware.com>
> Update a few docs with correct images and formatting

- src/server/middleware/security/auth_proxy.go
- src/server/middleware/security/auth_proxy_test.go
As we don't support bearer token in Harbor 2.0, the URL checking logic in auth proxy security generator should be updated
> Update the URL checking logic of auth proxy security generator

- src/lib/orm/query.go
Fixes #11267
When caller parse an empty orlist to orm lib, it will parse the empty vaule to beego orm.
But beego will panic if the query string is empty.
> Handle empty orlist in orm query

- src/common/api/base.go
- src/core/api/registry.go
- src/jobservice/job/impl/replication/scheduler.go
- src/replication/policy/scheduler/scheduler.go
1. In Harbor 2.0, the replication isn't supported between instances with different versions, this commit returns the 404 error when trying to get the registry info whose version is different with the current one
2. Bump up the version of API used in replicatoin scheduler job
3. Check the error message to determine whether the job exists or not in jobservice when unschedule a job
> Fix bugs of replication

- src/common/security/robot/robot.go
- src/common/security/robot/robot_test.go
- tests/apitests/python/library/artifact.py
Fixes #11225
As registry changes to basic auth, the push action lost the pull permission.
Add it in the robot security context.
> append pull permission for push policy

- src/replication/adapter/harbor/image_registry.go
- src/server/v2.0/handler/base.go
Fixes #11315
When specify no pagination in listing artifact request, the go-swagger will set the default value for them, so we need to iterate the link header to get all of artifacts
> Iterate the link header when listing artifact

- src/pkg/registry/client.go
- src/replication/transfer/image/transfer.go
Fixes #11272, support replicate images with media type application/vnd.docker.distribution.manifest.v1+json
> Support replicate images with media type application/vnd.docker.distribution.manifest.v1+json

- tests/apitests/python/library/docker_api.py
- tests/apitests/python/test_registry_api.py
Adding a test for listing repositories
Adding a test for list image tags for specified repo.
Testing done: 
- run Python tests/apitests/python/test_registry_api.py, paased.
Fixes #11283, fixes #11282
> Adding tests for native docker registry APIs exposed by Harbor

- src/pkg/artifact/dao/dao.go
- src/pkg/repository/dao/dao.go
- src/pkg/tag/dao/dao.go
- tests/apitests/python/test_create_delete_tag.py
Add "order by" clause to avoid the duplicat rows: https://www.postgresql.org/docs/9.6/queries-limit.html
> Add "order by" clause to avoid the duplicat rows

- src/server/middleware/v2auth/auth.go
- src/server/middleware/v2auth/auth_test.go
That was added to support core process sending request to `/v2/xxx`.
It's no longer needed after reworking the flow.
This commit removes this.
Fixes #10602, as it's not a case we need to support for now.
> Not checking for registry credentials in v2auth

- src/server/middleware/contenttrust/contenttrust.go
- src/server/middleware/contenttrust/contenttrust_test.go
- src/server/middleware/util.go
Fixes #11206
1, fix middleware doesn't work for docker pull without auth
2, fix middleware doesn't bypass scanner pull
> fix content trust middleware bypass scanner pull

- src/controller/scan/base_controller.go
- src/controller/scan/base_controller_test.go
Scanner name and uuid splited by `-` not `:` because of `:` is the separator of the basic auth.
Closes #11198
> fix(scan): add scanner name as prefix for name of the robot when submit scan job

- src/controller/artifact/controller.go
- src/controller/artifact/controller_test.go
Fixes #11222, update the existence checking logic when copying artifact
> Update the existence checking logic when copying artifact

- src/lib/log/context_test.go
- src/lib/log/logger.go
- src/lib/log/logger_test.go
1. When use the helper functions of log pkg, the depth is 4 to get the
correct file and line.
2. Whe use the default logger of log pkg, the depth is 3 to get the
correct file and line.
Closes #11391
> fix(log): correct file and line when use logger

- make/photon/prepare/utils/configs.py
Item in yaml without value will be as None in python, which will make
the password of redis as `None` in `get_redis_configs`. This fix will
not accept items of `false value` in `external_redis` configurations.
Closes #11367
> fix(prepare): not accpet items of false value in external_redis configurations

- make/photon/prepare/utils/configs.py
Item in yaml without value will be as None in python, which will make
the password of redis as `None` in `get_redis_configs`. This fix will
not accept items of `false value` in `external_redis` configurations.
Closes #11367
> fix(prepare): not accpet items of false value in external_redis

- src/controller/scan/base_controller.go
- src/controller/scan/base_controller_test.go
- src/pkg/scan/vuln/summary.go
- src/pkg/scan/vuln/summary_test.go
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
1. Fix ScanStatus when merge NativeReportSummary
-  Running and success status is high priority when merge ScanStatus of
NativeReportSummary, otherwise chose the bigger status.
-  Merge scan logs of referenced artifacts when get the scan logs of
image index.
2. Fix the annotation for the scan completed percent in scan overview
> Fix merge scan summary

- src/pkg/scan/vuln/summary.go
- src/server/middleware/vulnerable/vulnerable.go
- src/server/middleware/vulnerable/vulnerable_test.go
1. Prevent the pull action when scan report status is not successfuly.
2. Bypass the checking when no vulnerabilities not found.
3. Improve the returned message when prevented the pull action.
Closes #11202
> fix(vulnerable,middleware): improve vulnerable middleware

- src/pkg/artifact/dao/dao_test.go
The updated column should be PullTime instead of PushTime
> fix artifact dao UT issue

- src/lib/errors/const.go
- src/lib/errors/errors.go
- src/lib/errors/errors_test.go
- src/lib/errors/stack.go
- src/lib/errors/stack_test.go
- src/lib/log/logger.go
- src/server/error/error.go
- src/server/error/error_test.go
Fixes #10839
Add a StackTrace func in to Error, and log it when Harbor gets a internal
> Add trace information into internal error

- api/v2.0/swagger.yaml
Remove `text/plain` from produces to make `application/json` as default response.
> fix(swagger): make json as default response

- src/common/security/v2token/context.go
- src/common/security/v2token/context_test.go
- src/core/service/token/authutils.go
- src/server/middleware/contenttrust/contenttrust.go
- src/server/middleware/security/idtoken.go
- src/server/middleware/security/security.go
- src/server/middleware/security/utils.go
- src/server/middleware/security/utils_test.go
- src/server/middleware/security/v2_token.go
- src/server/middleware/security/v2_token_test.go
- src/server/middleware/v2auth/access.go
- src/server/middleware/v2auth/access_test.go
- src/server/middleware/v2auth/auth.go
- src/server/middleware/v2auth/auth_test.go
- src/server/middleware/vulnerable/vulnerable.go
- tests/apitests/python/test_robot_account.py
Docker CLI fails if it's not logged in upon seeing "basic" realm challenging while pinging the "/v2" endpoint. (#11266)
Some CLI will send HEAD to artifact endpoint before pushing (#11188)(#11271)
To fix such problems, this commit re-introduce the token auth flow to the CLIs.
For a request to "/v2/xxx" with no "Authoirzation" header, the v2_auth middleware populates the
"Www-Authenticate" header to redirect it to token endpoint with proper
requested scope.
It also adds security context to based on the content of the JWT which has the claims of the registry.
So a request from CLI carrying a token signed by the "/service/token" will have proper permissions.
> Reenable token auth for cli

- src/controller/scan/base_controller.go
- src/pkg/scan/report/report.go
- src/pkg/scan/report/summary.go
- src/pkg/scan/report/supported_mimes.go
- src/pkg/scan/vuln/report.go
- src/pkg/scan/vuln/report_test.go
- src/pkg/scan/vuln/summary.go
- src/pkg/scan/vuln/summary_test.go
- src/pkg/scan/vuln/util.go
- src/pkg/scan/vuln/util_test.go
- src/server/v2.0/handler/util.go
- src/server/v2.0/handler/util_test.go
1. Merge the scanning reports of referenced artifacts for image index.
2. Add artifact info for report.
> feat(scan): merge reports for image index

- api/v2.0/swagger.yaml
- src/controller/artifact/controller.go
1. Copy artifact will not return 409 anymore.
2. Make sure the tags of source artifact exist in the target artifact
> Update the logic of copy artifact

- src/server/middleware/contenttrust/contenttrust.go
- src/server/middleware/patterns.go
This commit removes the EnsureArtifactDigest as its implementation is
problematic: the artifactinfo in context is immutable.
When the content trust middleware needs the digest it will retrieve it
via artifact controller.
> Get digest in content trust middleware

- src/controller/quota/controller_test.go
- src/server/middleware/quota/quota.go
- src/server/middleware/quota/quota_test.go
- src/server/middleware/quota/refresh_project.go
1. Ignore limitation when refresh quota for project.
2. Return 403 when quota errors occurred.
3. Add test for Refresh method of quota controller.
Closes #11512
> feat(quota): ignore limitation support for quota RefreshMiddleware

- src/common/security/v2token/context.go
- src/common/security/v2token/context_test.go
Fixes #11563, add "delete" into the action map if the action in token is "*"
> Add "delete" into the action map if the action in token is "*"

- src/replication/adapter/harbor/base/adapter.go
Use insecure transport when creating the adapter for local instance in replication
> Use insecure transport when creating the adapter for local instance in replication

- src/jobservice/job/impl/gc/garbage_collection.go
- src/pkg/artifactrash/dao/dao.go
- src/pkg/artifactrash/dao/dao_test.go
fixes #11533
GC jobs will use the filter results to call registry API to delete manifest.
In the current imple, the filter function in some case does not return the deleted artifact as it's using digest as the filter condition.
Like: If one artifact is deleted, but there is another project/repo has a image with same digest with the deleted one, filter func will
not mark the deleted artifact as candidate. It results in, GC job does not call API to remove the manifest.
To fix it, update the filter to use both digest and repository name to filter candidate.
> fix artifact trash filter issue

- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/notification/webhook_job.go
- src/jobservice/job/impl/replication/replication.go
- src/jobservice/job/impl/replication/scheduler.go
- src/jobservice/job/impl/sample/job.go
- src/jobservice/job/interface.go
- src/jobservice/runner/redis_test.go
- src/jobservice/worker/cworker/c_worker.go
- src/jobservice/worker/cworker/c_worker_test.go
- src/pkg/retention/job.go
- src/pkg/scan/all/job.go
- src/pkg/scan/job.go
- src/pkg/scheduler/periodic_job.go
- update Job interface to introdcue MaxCurrency method for declaring the max currency of the specified job
- change the downstream jobs to implement the new interface method
- GC and sample jobs are set to 1
- other jobs are set to 0 that means unlimited
- add max currency option when doing job registration
- resolve issue #11586
- probably resolve issue #11281
- resolve issue #11570
> fix(job currency):introduce max corrency of job

- src/jobservice/job/priority.go
- src/jobservice/job/priority_test.go
- src/jobservice/worker/cworker/c_worker.go
- priority option is supported when doing job registration
- the priority is defined by a unique priority sampler
- the default priority is 1000 (max is 10000)
Fix issue #11607 
> feat(job):enable priority option

- make/photon/registry/Dockerfile
- make/photon/registry/entrypoint.sh
- make/photon/registryctl/Dockerfile
- src/registryctl/api/registry.go
Fixes #11606
As we DO NOT want to user to execute GC in the container, rename it and append the warning message.
> add warning to registry binary name

- src/lib/errors/errors.go
- src/lib/errors/errors_test.go
- src/server/error/error_test.go
Customize the json output with message with err.Error(). Otherwise, the wrappged message will be lost
in the final errors object.
> add MarshalJSON func for lib errs

- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
Trivy can't access harbor from external if https enabled so inject cert to trivy container trust
> Fix cert issue of trivy

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
Fixes #11624
All of the existing policies created v1.10 has no name, it fails the upgrade process.
When to set the unique constraint for policy name, the empty can be seen as duplicated key.
ERROR:  could not create unique index "notification_policy_name_key"
DETAIL:  Key (name)=() is duplicated.
> fix notification policy ugrade issue

- make/photon/log/Dockerfile
For harbor-log container,
```
root [ / ]# chage -l root
Last password change					: Apr 15, 2020
Password expires					: Jul 14, 2020
Password inactive					: never
Account expires						: never
Minimum number of days between password change		: 0
Maximum number of days between password change		: 90
Number of days of warning before password expires	: 7
```
When run ```sudo -u \#10000 -E  'rsyslogd' '-n'```, after 90 days you build image, it requires password change.
Fix: https://github.com/goharbor/harbor/issues/11633
> fix: set root password never expire

- src/core/controllers/base.go
The commit fix a regression introduced by #11672 which impacts admin
adding new users.
When admin is creating new users, /c/UserExists is called by UI. We must
allow it called by admin when self-registration is turned off.
> Allow sys admin to call /c/UserExists --  cherry pick to 2.0

- src/core/controllers/base.go
The commit fix a regression introduced by #11672 which impacts admin
adding new users.
When admin is creating new users, /c/UserExists is called by UI. We must
allow it called by admin when self-registration is turned off.
> Allow sys admin to call /c/UserExists

- src/pkg/retention/job.go
fix #11690 
When artifact never been pulled, the time is nil in db, and the value is int64(-62135596800) that shown as "0001/01/01 00:00:00", so just ignore time<=0 can work
> fix(retention) fix empty pull time log

- src/pkg/retention/job.go
fix #11702
do not retry retention job, as it's usually not necessary, and user can't manually retry easily
> fix(retention) not retry retention job

- src/controller/event/handler/webhook/artifact/artifact.go
In the delete repository scenario, the repository has already been removed from the DB, the repository cannot be retrived.
Just let the creation time as empty.
> Fix delete repository event issue

- src/controller/event/handler/webhook/artifact/artifact.go
In the delete repository scenario, the repository has already been removed from the DB, the repository cannot be retrived.
Just let the creation time as empty.
> [cherry-pick]Fix delete repository event issue

- src/lib/context.go
- src/server/middleware/contenttrust/contenttrust.go
- src/server/middleware/contenttrust/contenttrust_test.go
- src/server/middleware/immutable/pushmf.go
- src/server/middleware/vulnerable/vulnerable.go
- src/server/middleware/vulnerable/vulnerable_test.go
It's found by conformance test, it should be 404 instead of 500 when to get the non exist manifest
> fix return code on getting non exist manifest

- src/lib/context.go
- src/server/middleware/contenttrust/contenttrust.go
- src/server/middleware/contenttrust/contenttrust_test.go
- src/server/middleware/immutable/pushmf.go
- src/server/middleware/vulnerable/vulnerable.go
- src/server/middleware/vulnerable/vulnerable_test.go
It's found by conformance test, it should be 404 instead of 500 when to get a non exist manifest
> [cherry-pick]fix return code on getting non exist manifest

- src/server/middleware/v2auth/auth.go
- src/server/middleware/v2auth/auth_test.go
When scanner like trivy handles the auth flow to pull image, it pings
the /v2 and access the token service url in response body, by default it
will be external endpoint of Harbor.
There will be problem when Harbor is deployed on a single node with hairpinning not
supported.
This commit makes sure the address of token service in the challenge is
internal url of core component when the request is from internal.
> v2 auth middleware handles the ping request from internal

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
It's a workaround for issue https://github.com/goharbor/harbor/issues/11754
The phenomenon is the repository data is gone, but artifacts belong to the repository are still there.
To resolve it, just set the repository_id to a negative, and cannot duplicate.
> Fix the database upgrade issue

- Makefile
- api/v2.0/swagger.yaml
- tests/apitests/python/library/base.py
1. Enable `security` in the swagger.yaml.
2. Include `basic` auth in `security` to make the generated python
client by `swagger-codegen-cli` work with basic authorization.
3. Include `anonymous` auth in `security` to make APIs of v2.0 generated
by `goswagger` work with `security` middleware.
Closes #11771
> fix(swagger): enable security in swagger.yaml

- Makefile
- api/v2.0/swagger.yaml
- tests/apitests/python/library/base.py
1. Enable `security` in the swagger.yaml.
2. Include `basic` auth in `security` to make the generated python
client by `swagger-codegen-cli` work with basic authorization.
3. Include `anonymous` auth in `security` to make APIs of v2.0 generated
by `goswagger` work with `security` middleware.
Closes #11771
> [Cherry pick]fix(swagger): enable security in swagger.yaml

- src/pkg/retention/dep/client.go
- src/pkg/retention/job.go
fix #11690
When artifact never been pulled, the time is nil in db, and the value is int64(-62135596800) that shown as "0001/01/01 00:00:00", so just ignore time<=0 can work
> [cherry-pick]fix(retention) fix empty pull time log 2.0.0

- tests/apitests/python/library/cnab.py
- tests/apitests/python/library/containerd.py
- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/library/retention.py
- tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
- tests/apitests/python/test_push_cnab_bundle.py
- tests/apitests/python/test_push_image_with_special_name.py
- tests/apitests/python/test_push_index_by_docker_manifest.py
- tests/apitests/python/test_retention.py
- tests/resources/Harbor-Pages/Administration-Users.robot
- tests/resources/Harbor-Pages/Project-Repository.robot
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
1. Manifest list can be pulled by ctr;
2. ui-test missing key checkpoint, fix it by add checking scan detail result;
3. add tag retension untag image test;
> Cherry-pick to 2.0 - Add ctr command for pulling oci

- Makefile
- tests/integration.sh
1. add a label that mark the build time of base image
something as below
2. remove the useless push on dockerhub
> feat(cicd) add build date for base images

- src/lib/errors/const.go
- src/server/error/error.go
- src/server/middleware/quota/put_manifest.go
- src/server/middleware/quota/put_manifest_test.go
fixes #11945
When client calls PUT with an invalid digtest, Harbor has to give a 400 instead of 500.
> fix conformance test ErrorsCodes failure

- src/lib/errors/const.go
- src/server/error/error.go
- src/server/registry/manifest.go
- src/server/registry/manifest_test.go
fixes #11949
When to call delete manifest API with a tag as the reference, Harbor should give a unsupported error code.
Reference: Note that a manifest can only be deleted by digest. https://github.com/opencontainers/distribution-spec/blob/master/spec.md#delete-manifest
> fix conformance issue on deleting manifest

- src/controller/scanner/base_controller.go
- src/controller/scanner/base_controller_test.go
The function GetRegistrationByProject should not return err when Ping
return err.  The return value 'registration' has 'Health' field which
shows the scanner health status.
Resolves: #11051
See also: #9788, #9807
Signed-off-by: qinshaoxuan <qinshaoxuan@baidu.com>
> Fix bug when scanner is unhealthy

- src/core/api/base.go
- src/core/api/metadata.go
- src/core/api/metadata_test.go
- src/core/api/project.go
- src/core/api/repository.go
- src/core/api/repository_test.go
- src/core/api/scan.go
Update to repositories API so it will not differentiate if a project
does not exist or the user doesn't have permission to access it.
> Change to repositories api

- src/core/api/chart_repository.go
Response code should consistent whether namespace is existed or not
> Fix: chart repo response code inconsistent

- src/jobservice/common/rds/scripts.go
- src/jobservice/job/tracker.go
- src/jobservice/job/tracker_test.go
- src/jobservice/period/basic_scheduler.go
- never expire the jobs that are not entering the final status (Error, Success or Stopped)
- set different expiration time to the jobs with different status
- never store the `check_in` data in the Redis DB to save space
> fix(jobservice):fix issues of jobservice

- make/photon/db/docker-healthcheck.sh
This patch remove the trailing space of the hostname introduced by
`hostname -i`.
The trailing space will cause resolution error after this patch is
applied to glibc in photon:
https://github.com/vmware/photon/blob/2.0/SPECS/glibc/glibc-fix-CVE-2019-10739.patch
> Update health check script for harbor-db

- make/photon/db/docker-healthcheck.sh
This patch remove the trailing space of the hostname introduced by
`hostname -i`.
The trailing space will cause resolution error after this patch is
applied to glibc in photon:
https://github.com/vmware/photon/blob/2.0/SPECS/glibc/glibc-fix-CVE-2019-10739.patch
> Update health check script for harbor-db (#12103) - cherrypick to 2.0

- make/photon/db/docker-healthcheck.sh
This patch remove the trailing space of the hostname introduced by
`hostname -i`.
The trailing space will cause resolution error after this patch is
applied to glibc in photon:
https://github.com/vmware/photon/blob/2.0/SPECS/glibc/glibc-fix-CVE-2019-10739.patch
> Update health check script for harbor-db (#12103) - Cherrypick to 1.10

- src/jobservice/hook/hook_agent_test.go
- src/jobservice/period/basic_scheduler.go
- src/jobservice/worker/cworker/c_worker.go
- returnning nil instead of error when trying to stop a job that has been in the final status(Error/Success/Stopped)
- do enhancements to the periodic job unschedule func
- fix a UT nil ptr issue
fix #11894
fix #11083 
> fix(jobservice):mismatch status issue when stopping job

- src/core/api/base.go
- src/core/api/metadata.go
- src/core/api/metadata_test.go
- src/core/api/project.go
Update to projects API so it will not differentiate if a project
does not exist or the user doesn't have permission to access it.
> Change status code for projects API -- cherrypick to 2.0

- src/core/api/base.go
- src/core/api/metadata.go
- src/core/api/metadata_test.go
- src/core/api/project.go
Update to projects API so it will not differentiate if a project
does not exist or the user doesn't have permission to access it.
> Change status code for projects API

- src/common/api/base.go
- src/lib/http/error.go
- src/lib/http/error_test.go
- src/registryctl/api/base.go
- src/server/middleware/artifactinfo/artifact_info.go
- src/server/middleware/csrf/csrf.go
- src/server/middleware/immutable/pushmf.go
- src/server/middleware/middleware.go
- src/server/middleware/quota/quota.go
- src/server/middleware/readonly/readonly.go
- src/server/middleware/transaction/transaction.go
- src/server/middleware/v2auth/auth.go
- src/server/registry/catalog.go
- src/server/registry/manifest.go
- src/server/registry/tag.go
- src/server/v2.0/handler/base.go
- src/server/v2.0/handler/handler.go
- src/server/version.go
Move the sendError into library in case the cycle dependency as regsitry and core are now the consumers.
> move send error to source lib

- Makefile
- make/photon/Makefile
Fix #12259
Signed-off-by: Max Rosin <git@hackrid.de>
> Fix DOCKERIMASES and SWAAGER_IMAGE_BUILD_CMD typos in Makefiles

- src/controller/p2p/preheat/enforcer.go
- src/lib/selector/candidate.go
- src/lib/selector/selector.go
- src/lib/selector/selectors/doublestar/selector.go
- src/lib/selector/selectors/label/selector.go
- src/lib/selector/selectors/severity/selector.go
- src/lib/selector/selectors/severity/selector_test.go
- src/lib/selector/selectors/signature/selector.go
- src/lib/selector/selectors/signature/selector_test.go
- src/pkg/p2p/preheat/models/policy/policy.go
- src/pkg/p2p/preheat/policy/filter.go
- src/pkg/p2p/preheat/policy/filter_test.go
- add new selector based on vulnerability severity criteria
- add new selector based on signature(signed) criteria
- do change to the select factory method definition
- do changes to selector.Candidate model
- add preheat policy filter interface and default implementation
- add UT cases to cover new code
> feat(preheat):add artifact filters for preheat policy

- codecov.yml
- ignore all md files
- ignore all yaml files
- ignore non source code folders: docs,api,make,contrib,tests,tools
- ignore source code vendor folder: src/vendor
- ignore folders for auto-generated code: "src/server/v2.0/models" and "src/server/v2.0/restapi"
> fix(codecov):add ignore configuration

- make/photon/prepare/templates/chartserver/env.jinja
The Chartmuseum S3 client need set an Env variable
Ref: https://github.com/helm/chartmuseum/issues/280
> Fix Amazon S3 storage not work

- src/registryctl/handlers/router.go
The repository name contains blackslash, the mux router has to use the * to match the blackslash. Otherwise the caller(gc job) will get a 404.
> fix delete manifest route issue

- src/registryctl/api/base.go
- src/registryctl/api/base_test.go
When to delete an non exist blob/manifest, the API has to return a 404 instead of 500
> fix return value for blob & manifest not found

- src/pkg/blob/dao/dao.go
- src/pkg/blob/dao/dao_test.go
- src/pkg/blob/manager_test.go
- src/pkg/blob/models/blob.go
Add support list blob with update time.
As introduces the time window in GC, it wants to list the blobs less than specific time.
> support list blobs by update time

- api/v2.0/legacy_swagger.yaml
- make/migrations/postgresql/0040_2.1.0_schema.up.sql
- src/common/const.go
- src/common/dao/project.go
- src/common/dao/project/projectmember_test.go
- src/common/models/project.go
- src/common/rbac/project_rbac_role.go
- src/core/api/project.go
- src/core/api/project_test.go
- src/core/api/projectmember.go
- src/core/api/projectmember_test.go
- src/testing/apitests/apilib/project.go
This commit rename the var name, text appearance, and swagger of "master" role
to "maintainer" role.
It only covers backend code.
> Rename master role to maintainer

- src/common/quota/driver/project/driver.go
- src/core/api/project.go
1. Clear cache for projects loader in quota driver of project which will
ensure that load project will raise error after project deleted.
2. Delete quota of the project before the deletion of the project.
Closes #12292
> fix(quota): fix internal server error when delete project

- src/common/dao/pgsql.go
- src/common/dao/pgsql_test.go
- src/common/dao/testutils.go
Due to the issues of beego v1.12.1 and v1.12.2, we set the max open conns
ourselves.
Closes #12403
> fix(db): set max open conns of sql.DB manually

- src/common/dao/pgsql.go
- src/common/dao/pgsql_test.go
- src/common/dao/testutils.go
Due to the issues of beego v1.12.1 and v1.12.2, we set the max open conns
ourselves.
Closes #12403
> [Cherry pick]fix(db): set max open conns of sql.DB manually

- make/migrations/postgresql/0040_2.1.0_schema.up.sql
Rename "reuse_sys_cve_whitelist" to "reuse_sys_cve_allowlist" in project metadata
> Rename "reuse_sys_cve_whitelist" to "reuse_sys_cve_allowlist"

- src/controller/proxy/controller.go
- src/controller/proxy/controller_test.go
- src/controller/proxy/inflight.go
- src/controller/proxy/inflight_test.go
- src/controller/proxy/local.go
- src/controller/proxy/local_test.go
- src/controller/proxy/remote.go
- src/server/middleware/repoproxy/proxy.go
- src/server/registry/route.go
Update route to add proxy related middleware
Add proxy controller
> Add proxy cache feature

- src/controller/p2p/preheat/enforcer.go
- src/controller/p2p/preheat/enforcer_test.go
Read security settings from the project configurations and override the preheat policy settings if necessary.
Check the project security settings and override the related settings in the policy if necessary.
NOTES: if the security settings (relevant with signature and vulnerability) are set at the project configuration,
they will have the highest priority and override the related settings of the preheat policy.
e.g (use signature as an example, similar case to vulnerability severity part):
if policy.signature = false and project.config.signature = true; then policy.signature = true
if policy.signature = true and project.config.signature = true; then policy.signature = true
if policy.signature = true and project.config.signature = false; then policy.signature = true
if policy.signature = …
> feat(p2p):enhance policy enforcer

- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/gc/garbage_collection_test.go
- src/jobservice/job/impl/gc/util.go
- src/pkg/artifactrash/dao/dao.go
- src/pkg/blob/models/blob.go
- tests/apitests/python/library/system.py
two phases:
1, mark, select the gc candidates bases on the DB and mark them as status delete.
2, sweep, select the candidate and mark it as status deleting and remove it from backend and database.
> revise gc job to align non blocking gc

- src/server/middleware/repoproxy/proxy.go
When to call,
~~~ REQUEST ~~~
GET  /v2/conformance/testrepo/manifests/.INVALID_MANIFEST_NAME
Per OCI distribution spec, it has to return 404, instead of 400 (project name required)
> fix get manifest return code

- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/common/utils/oidc/helper.go
- src/common/utils/oidc/helper_test.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/core/controllers/oidc.go
- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/lib/components/config/config.ts
In our company, as well as #8422 and #9995, we need to skip the onboarding screen. Also, OIDC is integrated with ADFS (Active Directory Federation Services) and we need to get the username from a different claim name (sAMAccountName) instead of "name" claim. This PR addresses these 2 issues, allowing to select "Automatic onboarding" from the OIDC configuration and use a custom claim name for the username. 
- Add an option in the UI to enable or disable the automatic user onboarding
- Add an option to specify the claim name where the username is retrieved from.
Signed-off-by: Iradier, AlvaroJose <AlvaroJose.Iradier@adidas.com>
> Add options for automatic onboarding and username claim

- src/core/api/registry.go
Don't return the error detail back to the client when adding registry to avoid security issue
> Don't return the error detail back to the client when adding registry

- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/app/shared/list-repository-ro/list-repository-ro.component.ts
- src/portal/src/lib/components/replication/replication.component.html
Fixes #12500
1.[replication] sccess rate should be displayed as 0 when status is inprogress
2.[repository] fix get repo name error when the repo contains the project name field
> [cherry-pick][fix] [replication] Success rate should be displayed as 0 when status is inprogress

- src/core/middlewares/middlewares.go
- src/core/middlewares/middlewares_test.go
- src/pkg/distribution/distribution.go
- src/server/middleware/blob/put_blob_upload.go
1. Skip database transaction middleware for GET Blob and PATCH Blob Upload APIs for there are no database writing operations in them.
2. Skip database transaction middleware for PUT Blob Upload API  and execute database transaction manually in the middlewares in it so that use some short time executions than one long time database transaction execution. Replication use PUT Blob Upload API to upload the whole blob which may spend a long time (minutes level or even more) taking up a database connection if only one database transaction execution in this API.
> perf(db): skip tx for get blob, patch/put blob upload apis

- src/pkg/proxy/secret/manager.go
- src/pkg/proxy/secret/manager_test.go
This commit provides the secret manager for proxy cache.
The secret is used for pushing blobs to local when it's proxied from
remote registry.
Each secret can be used only once and has a relatively short expiration
time.
> Provide secret manager for proxy cache project

- src/common/const.go
- src/core/api/reg_gc.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/jobservice/job/impl/gc/garbage_collection.go
- src/pkg/blob/dao/dao.go
- src/server/middleware/blob/head_blob.go
- src/server/middleware/blob/util.go
- tests/apitests/python/library/system.py
- tests/ci/api_common_install.sh
For debugging, the tester/users wants to run GC to delete the removed artifact immediately instead of waitting for two hours, add the env(_GC_BLOB_TIME_WINDOW) to meet this.
> add debugging env for GC time window

- src/controller/quota/controller.go
- src/controller/quota/driver/project/project.go
- src/controller/quota/options.go
- src/core/api/quota.go
- src/pkg/quota/dao/dao.go
- src/pkg/quota/models/quota.go
- src/testing/controller/quota/controller.go
- src/testing/pkg/blob/manager.go
Make to load the ref object of the quota optional and also move it from dao to controller.
`Get` and `GetByRef` also support to load the ref object of the quota.
> refactor(quota): align Get and List methods of quota controller
