goharbor/harbor

make/docker-compose.chartmuseum.tpl, make/docker-compose.clair.tpl, make/docker-compose.tpl, make/photon/Makefile, make/photon/chartserver/Dockerfile, make/photon/chartserver/docker-entrypoint.sh, make/photon/clair/Dockerfile, make/photon/clair/docker-entrypoint.sh, make/photon/common/install_cert.sh, make/photon/registry/Dockerfile, make/photon/registry/entrypoint.sh, make/prepare
=> Install custom cert for clair, registry, chartmuseum(1.6.0)

src/portal/src/app/project/list-project/list-project.component.html, src/portal/src/app/project/list-project/list-project.component.ts, src/portal/src/app/project/project.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Project API return the helm chart count now, so put it to UI.
=> Enhance: Add helm chart count number in the project list

tests/apitests/python/library/configurations.py, tests/apitests/python/library/project.py, tests/apitests/python/test_edit_project_creation.py, tests/robot-cases/Group0-BAT/API_DB.robot
Add API test script edit-project_creation to verify Harbor system configuration setting for project creation.
=> add test case for edit project creation

tests/resources/Harbor-Pages/Project-Helmcharts.robot
Fix delete helm chart testcase
=> Fix testcase of helm chart delete

tests/apitests/python/library/repository.py, tests/apitests/python/test_scan_image.py, tests/robot-cases/Group0-BAT/API_DB.robot
Add test case to verify scan image feature, scan a not-scanned image. 
=> add test case scan a not scanned image

tests/resources/Harbor-Pages/Project-Retag.robot, tests/resources/Harbor-Pages/Project-Retag_Elements.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot
fixed #6270 
Add test case for retag
=> Add E2E test for retag

tests/travis/api_run.sh
Travis didn't catch error in api_run.sh, so add some debug info. 
=> Debug for exit-code didn't work for travis

tests/apitests/python/library/docker_api.py, tests/apitests/python/library/repository.py, tests/apitests/python/test_project_level_policy_content_trust.py, tests/robot-cases/Group0-BAT/API_DB.robot
Add test case project level policy content trust
=> add test case project level policy content trust

CONTRIBUTING.md
=> added dependency install steps to linting

docs/swagger.yaml, tests/apitests/python/library/repository.py, tests/apitests/python/library/system.py, tests/apitests/python/test_garbage_collection.py, tests/robot-cases/Group0-BAT/API_DB.robot
Add API test case for garbage collection
=> Add API test case for garbage collection

make/migrations/postgresql/0002_1.7.0_schema.up.sql, src/common/dao/joblog.go, src/common/dao/joblog_test.go, src/common/models/base.go, src/common/models/joblog.go, src/jobservice/job/impl/context.go, src/jobservice/logger/backend/db_logger.go, src/jobservice/logger/backend/db_logger_test.go, src/jobservice/logger/entry.go, src/jobservice/logger/factory.go, src/jobservice/logger/getter/db_getter.go, src/jobservice/logger/getter_factory.go, src/jobservice/logger/known_loggers.go, src/jobservice/logger/known_loggers_test.go, src/jobservice/logger/sweeper/db_sweeper.go, src/jobservice/logger/sweeper_factory.go, src/jobservice/pool/redis_job_wrapper.go
test cases:
1. Start a image scan job. Job successful. after job finished, check data in table Job_log in DB.
2. Start a image scan job. Job failed. after job finished, check data in table Job_log in DB.
3. Check the Job log produced in step 1 and 2, Log from step 2 checked from UI and 1 from OpenAPI.
4. Confing using sweeper，use default Duration(1 day)，Start JobService，the expired logs will be clean immediately.
5. Confing using sweeper，use default Duration(1 day)，Start JobService，the expired logs will be clean after one day.
6. delete DB data, and startup harbor again,  DB will be created and table job_log will be created too.
7. Case for limit of length of Job content. when size of log proceeds 4k retrieving log normally. No limit for log size.
8. all Unit Test cases run successfully。
=> 6144 js logger in db

docs/installation_guide.md
=> update installation guide doc

src/core/main.go
change session cookie name to sid and this fix #6355
=> change session cookie name to sid

src/portal/lib/src/service/helm-chart.service.ts, src/portal/lib/src/service/interface.ts
=> Fix: helmchart api change caused problems

src/portal/src/app/base/global-search/search-result.component.html, tests/resources/Harbor-Pages/Project-Members.robot
Global search bug fix introduced test case failure, fix it by edit xpath
=> Fix xpath in go to project robot case

src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Fix i18n issues that may confuse people
=> Fix: i18n issues of deleting project failure info

docs/swagger.yaml, tests/apitests/python/library/chart.py, tests/apitests/python/library/docker_api.py, tests/apitests/python/library/repository.py, tests/apitests/python/test_list_helm_charts.py, tests/apitests/python/test_scan_all_images.py, tests/apitests/python/test_scan_image.py, tests/robot-cases/Group0-BAT/API_DB.robot, tests/travis/api_common_install.sh, tests/travis/api_run.sh
Add API test case scan all images.
=> Add API test case scan all images

src/jobservice/logger/entry_test.go, src/jobservice/logger/factory.go, src/jobservice/logger/factory_test.go, src/jobservice/logger/getter/db_getter_test.go, src/jobservice/logger/getter_factory_test.go, src/jobservice/logger/known_loggers_test.go, src/jobservice/logger/sweeper/db_sweeper.go, src/jobservice/logger/sweeper/db_sweeper_test.go, src/jobservice/logger/sweeper_factory_test.go
add unit test for JobService Logger.
=> Add unit test for JobService Logger

tests/resources/Harbor-Pages/Project-Helmcharts.robot
Fix testcase because of wrong keyword
=> Fix: Rebotcase failure in upload chart

tools/migration/cfg/migrator_1_7_0/__init__.py, tools/migration/cfg/migrator_1_7_0/harbor.cfg.tpl, tools/migration/cfg/run.py, tools/migration/cfg/utils.py
Add script to upgrade harbor.cfg
=> Feat: Upgrade harbor.cfg from 1.6.0 to 1.7.0

src/portal/lib/src/filter/filter.component.ts, src/portal/lib/src/log/recent-log.component.spec.ts, src/portal/lib/src/log/recent-log.component.ts
Fix the javascript error, when trying to invoke trim() by undefined.
=> fix #6421 javascript error when user input nothing in the filter logs

tools/migration/cfg/migrator_1_7_0/__init__.py
=> Update no_proxy from 'portal' to 'core' in cfg migrator

src/portal/lib/src/config/vulnerability/vulnerability-config.component.html, src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
=> Don't get the next available time while scan now

src/portal/lib/src/config/vulnerability/vulnerability-config.component.html
fixed #6426 
Formatting time using 24-hour format followed by AM
=> Time display using 24-hour system

src/common/api/base.go, src/core/api/repository.go
Related issue: https://github.com/goharbor/harbor/issues/6453
=> Give meaningful error messages when retag is forbidden

src/portal/lib/src/helm-chart/versions/helm-chart-version.component.html, src/portal/lib/src/helm-chart/versions/helm-chart-version.component.ts, src/portal/lib/src/service/label.service.ts
issue description:
in helm chart page, user only can add labels in project level, no global label shows. 
fix:
Need to show global labels in helm chart add label popup.
=> fix helm chart did not get global label

tests/resources/Harbor-Pages/Project-Repository.robot
currently, scan log popup in a new window to keep consistent with other logs. 
So this is a quick fix for the currently nightly test. 
ideally, we should test the new window content should popup correctly. However, I did not very good approach for now. So let me do a quick fix for ci and then refactor the nightly to test popup window.
=> quick fix for scan log

src/portal/lib/src/tag/tag.component.html, src/portal/lib/src/tag/tag.component.ts
Fix the problem that project guest can't use retag function.
Related issue: https://github.com/goharbor/harbor/issues/6473
=> Enable retag button to project guest

src/portal/lib/src/tag/tag.component.html, src/portal/lib/src/tag/tag.component.ts
=> [Cherry-Pick] Enable retag button for project guest

src/common/config/encrypt/encrypt.go, src/common/config/encrypt/encrypt_test.go, src/common/config/encrypt/keyprovider.go, src/common/config/encrypt/keyprovider_test.go, src/common/config/metadata/metadata.go, src/common/config/metadata/metadata_test.go, src/common/config/metadata/metadatalist.go, src/common/config/metadata/type.go, src/common/config/metadata/type_test.go, src/common/config/metadata/value.go, src/common/config/metadata/value_test.go
Only include config manager and data structure to access config.
Remote config store is not implemented.
=> Refactor config setting module

tests/apitests/python/library/repository.py, tests/apitests/python/test_project_level_policy_content_trust.py
=> Remove redundant functions

src/registryctl/auth/secret.go, src/registryctl/auth/secret_test.go
Added tests for registryctl authentication to improve coverage levels.
=> Registryctl auth unit tests

docs/compile_guide.md
Update required docker as multi build with FROM as used which is introduced in Docker 17.05
Signed-off-by: Niklas Wik <niklas.wik@nokia.com>
=> Compile doc update

docs/swagger.yaml
=> Modify the developer center version number to 1.7.0

docs/swagger.yaml
=> [Cherry-Pick] Modify the developer center version number to 1.7.0

src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Add `helmchart` item in `project_detail` entry
=> Update i18n files of project_detail

src/portal/src/i18n/lang/en-us-lang.json
This issue is caused by error formated json file
=> Fix i18n switch issue

src/core/api/repository.go, src/portal/lib/src/repository/repository.component.spec.ts, src/portal/lib/src/service/interface.ts, src/portal/lib/src/tag/tag-detail.component.html, src/portal/lib/src/tag/tag-detail.component.spec.ts, src/portal/lib/src/tag/tag-detail.component.ts, src/portal/lib/src/tag/tag.component.spec.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Include os version in image tag detail page

src/common/config/manager.go, src/common/config/manager_test.go, src/common/config/metadata/value.go, src/common/config/metadata/value_test.go, src/common/config/store/driver/db.go, src/common/config/store/driver/db_test.go, src/common/config/store/driver/driver.go, src/common/config/store/driver/rest.go, src/common/config/store/driver/rest_test.go, src/common/config/store/store.go, src/common/config/store/store_test.go
Add config store, driver implementation
=> Refactor config settings stage2

src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Add `helmchart` item in `project_detail` entry
=> [Cherry-pick]Update i18n files of project_detail

src/portal/src/app/dev-center/dev-center.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Modify swagger page title to "Harbor Swagger"
=> add harbor swagger title for api explorer

make/common/templates/nginx/nginx.http.conf, make/common/templates/nginx/nginx.https.conf, make/prepare
This is a solution for product that using harbor as proxy to add customized location
=> Add customized config file for proxy

src/portal/src/i18n/lang/en-us-lang.json
=> Fix i18n switch issue (#6579)

src/common/models/retag.go, src/common/utils/validate.go, src/common/utils/validate_test.go, src/core/api/repository.go, src/core/api/repository_test.go
Related to issue: https://github.com/goharbor/harbor/issues/6540
=> Validate repo and tag names in retag

src/common/models/retag.go, src/common/utils/validate.go, src/common/utils/validate_test.go, src/core/api/repository.go, src/core/api/repository_test.go
=> [Cherry-Pick] Validate repo and tag names in retag

tests/resources/Harbor-Pages/Project_Elements.robot
A layer of div is added to the left navigation bar.
=> fix xpath of project and log

src/portal/lib/package.json, src/portal/lib/src/tag/tag.component.html, src/portal/package.json
cherry pick disable retag function from 1.7.0 release branch to master. To make them consistent.
=> disable retag function if with admiral

tests/robot-cases/Group3-Upgrade/prepare.py
=> modify a code error by copy mistake

tests/resources/Harbor-Pages/Project.robot, tests/resources/Harbor-Pages/ToolKit.robot, tests/resources/Harbor-Pages/Vulnerability.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot, tests/robot-cases/Group1-Nightly/Nightly.robot
=> Add wait until in <Multi-delete Object> and <Project Should Display>

src/common/dao/robot.go, src/common/dao/robot_test.go, src/common/models/robot.go
=> Add dao of robot account

docs/swagger.yaml, src/common/const.go, src/core/api/base.go, src/core/api/harborapi_test.go, src/core/api/health.go, src/core/api/health_test.go, src/core/config/config.go, src/core/router.go
The commit implements an unified health check API for all Harbor services
=> Implement the unified health check API

src/common/dao/base.go, src/common/dao/robot.go, src/common/models/robot.go, src/common/models/token.go, src/core/api/api_test.go, src/core/api/harborapi_test.go, src/core/api/robot.go, src/core/api/robot_test.go, src/core/router.go
Add API implementation of robot account
1. POST /api/project/pid/robots
2, GET /api/project/pid/robots/id?
3, PUT /api/project/pid/robots/id
4, DELETE /api/project/pid/robots/id
=> Add API implementation of robot account

src/common/security/context.go, src/core/api/chart_repository_test.go, src/core/service/token/token_test.go
=> Add Can method to securty.Context interface

docs/swagger.yaml, make/migrations/postgresql/0005_add_master_role.up.sql, src/common/const.go, src/common/dao/project.go, src/common/security/local/context.go, src/core/api/projectmember.go, src/core/api/projectmember_test.go
=> Support master role for project member create and update apis

tests/resources/Harbor-Pages/Project.robot
=> add space adaptor for regexp when create a new project

src/portal/lib/src/helm-chart/helm-chart.component.scss, src/portal/lib/src/label/label.component.scss, src/portal/lib/src/list-replication-rule/list-replication-rule.component.html, src/portal/lib/src/replication/replication.component.scss, src/portal/lib/src/tag/tag.component.scss, src/portal/src/app/log/audit-log.component.html, src/portal/src/app/log/audit-log.component.ts, src/portal/src/app/project/member/add-group/add-group.component.scss
Signed-off-by: Yogi_Wang <wang1084@126.com>
=> style_change

src/portal/lib/src/tag/tag.component.html, src/portal/lib/src/tag/tag.component.scss
fixed #6825 
Clr-dg-column has a minimum width of 80px, set the maximum width and set overflow concealment, but the full tag name can be displayed when the mouse hovers.
=> The tag column sets the Maximum  width

src/common/security/robot/context.go, src/common/security/robot/context_test.go
=> Fix action and resouce of RBAC change

src/portal/lib/src/_mixin.scss, src/portal/lib/src/helm-chart/helm-chart.component.scss, src/portal/lib/src/helm-chart/versions/helm-chart-version.component.scss, src/portal/lib/src/repository-gridview/repository-gridview.component.scss, src/portal/lib/src/shared/shared.const.ts, src/portal/src/app/config/config.module.ts, src/portal/src/app/harbor-routing.module.ts, src/portal/src/app/project/project-detail/project-detail.component.html, src/portal/src/app/project/project.module.ts, src/portal/src/app/project/robot-account/add-robot/add-robot.component.html, src/portal/src/app/project/robot-account/add-robot/add-robot.component.scss, src/portal/src/app/project/robot-account/add-robot/add-robot.component.spec.ts, src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts, src/portal/src/app/project/robot-account/robot-account.component.html, src/portal/src/app/project/robot-account/robot-account.component.scss, src/portal/src/app/project/robot-account/robot-account.component.spec.ts, src/portal/src/app/project/robot-account/robot-account.component.ts, src/portal/src/app/project/robot-account/robot-account.service.ts, src/portal/src/app/project/robot-account/robot.api.repository.ts, src/portal/src/app/project/robot-account/robot.ts, src/portal/src/app/shared/confirmation-dialog/confirmation-dialog.component.scss, src/portal/src/app/shared/shared.const.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json, src/portal/src/styles.css
1, Project admin can add a robot account with name, description and a pull/push permission.
2, Project admin can disable/enable any of them.
3, Project admin can delete any of them.
4, Project admin can search any of them.
=> Support Robot account in Harbor

src/jobservice/job/impl/replication/ng/replication.go, src/jobservice/job/impl/replication/ng/replication_test.go, src/replication/ng/model/execution.go, src/replication/ng/model/namespace.go, src/replication/ng/model/policy.go, src/replication/ng/model/registry.go, src/replication/ng/model/resource.go, src/replication/ng/transfer/chart/transfer.go, src/replication/ng/transfer/repository/transfer.go, src/replication/ng/transfer/transfer.go, src/replication/ng/transfer/transfer_test.go
1. Refine the replication job
2. Define the Transfer interface
3. Define the common models
=> Refine the replication job

tests/resources/Docker-Util.robot, tests/resources/Harbor-Pages/Project-Members.robot, tests/resources/Harbor-Pages/Project_Elements.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot
=> Add retry keyword for docker pull and push image command.

tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot
=> remove some sleep and add retry common keyword

src/portal/lib/src/list-replication-rule/list-replication-rule.component.ts, src/portal/lib/src/project-policy-config/project-policy-config.component.spec.ts, src/portal/lib/src/repository-gridview/repository-gridview.component.html, src/portal/lib/src/service/permission.service.ts, src/portal/lib/src/tag/tag-detail.component.html, src/portal/lib/src/tag/tag.component.spec.ts, src/portal/lib/src/tag/tag.component.ts, src/portal/lib/src/vulnerability-scanning/result-grid.component.spec.ts, src/portal/lib/src/vulnerability-scanning/result-grid.component.ts
Signed-off-by: Yogi_Wang <wang1084@126.com>
1.fix permissionRole no change when switching project  ;
2.fix scan image permission not effectiv;
3. resolve list-replication-rule error;
=> PermissionMasterRoleWithIsue

src/adminserver/api/base_test.go
Added new API unit tests to increase coverage for admin server core APIs
=> Additional unit tests for base.go

docs/import_vulnerability_data.md
Updated documentation for importing vulnerability data into the clair DB. 
Reference issue: #6714 
=> Updated clair db import for Harbor 1.6+

make/photon/Makefile
=> Fix format of makefile

docs/swagger.yaml, src/common/models/robot.go
=> Add post response for robot account API

tests/resources/Util.robot
=> add Capture Page Screenshot in retry keyword

tools/migration/Dockerfile
=> Upgrade migrator base os to photon 2.0

src/portal/lib/src/config/system/system-settings.component.ts, src/portal/lib/src/repository-gridview/repository-gridview.component.ts, src/portal/lib/src/service.config.ts, src/portal/src/app/repository/repository-page.component.html, src/portal/src/app/repository/repository-page.component.ts
fixed ##6850
Show download certificate link when integrating with admiral
=> Download the certificate link by default on ui

src/portal/lib/src/repository/repository.component.spec.ts
=> fixed_ciIssue

src/replication/ng/adapter/adapter.go, src/replication/ng/adapter/adapter_test.go, src/replication/ng/execution/execution.go, src/replication/ng/flow/controller.go, src/replication/ng/flow/controller_test.go, src/replication/ng/flow/flow.go, src/replication/ng/model/execution.go, src/replication/ng/model/policy.go, src/replication/ng/model/registry.go, src/replication/ng/model/resource.go, src/replication/ng/policy/manager.go, src/replication/ng/registry/manager.go, src/replication/ng/scheduler/scheduler.go, src/replication/ng/transfer/transfer.go
1. Implement the replication flow controller
2. Implement the registry adapter management
3. Define the interface for PolicyManager, RegistryManager, ExecutionManager, TaskManager and Scheduler
=> Implement the replication flow controller

src/portal/lib/src/helm-chart/helm-chart.component.scss, src/portal/lib/src/helm-chart/versions/helm-chart-version.component.html, src/portal/lib/src/helm-chart/versions/helm-chart-version.component.scss, src/portal/lib/src/log/recent-log.component.ts, src/portal/lib/src/repository-gridview/repository-gridview.component.ts
1. style change about  card margin ；
2. when leave page ,refresh interface execute once more；
3. change card deletion privileges do not require records with selected rows.
=> change_style and datagrid refresh interface change

src/portal/src/app/project/list-project/list-project.component.html, src/portal/src/app/project/list-project/list-project.component.ts
=> fix issue 2923

src/portal/lib/src/config/gc/gc.component.spec.ts, src/portal/lib/src/tag/tag.component.spec.ts
1.fix 2 skipped tests,
2.add mock data in gc-component
=> Skipped tests fix

docs/swagger.yaml, tests/apitests/python/library/docker_api.py, tests/apitests/python/library/project.py, tests/apitests/python/library/repository.py, tests/apitests/python/test_robot_account.py
=> add API test case for robot account function

make/photon/log/Dockerfile, make/photon/log/logrotate
This commit fixes issue #6895 by running logrotate with user 10000
=> Run logrotate as user 10000 to avoid issue #6895

src/portal/lib/src/log/recent-log.component.spec.ts, src/portal/lib/src/repository-gridview/repository-gridview.component.spec.ts, src/portal/lib/src/repository-gridview/repository-gridview.component.ts, src/portal/lib/src/repository/repository.component.spec.ts
=> fix_skipped_tests

docs/permissions.md
Doc for permissions of project member.
=> Add doc for permissions

make/photon/log/Dockerfile, make/photon/log/logrotate
This commit fixes issue #6895 by running logrotate with user 10000
=> [Cherry-pick]Run logrotate as user 10000 to avoid issue #6895

src/portal/lib/src/config/system/system-settings.component.ts, src/portal/lib/src/repository-gridview/repository-gridview.component.ts, src/portal/lib/src/service.config.ts, src/portal/src/app/repository/repository-page.component.html, src/portal/src/app/repository/repository-page.component.ts
Show download certificate link when integrating with admiral
=> [Cherry-pick] Download the certificate link by default on ui

src/replication/ng/execution/execution.go, src/replication/ng/flow/controller.go, src/replication/ng/flow/controller_test.go, src/replication/ng/flow/flow.go, src/replication/ng/model/execution.go, src/replication/ng/scheduler/scheduler.go
This commit refactors the Scheduler interface and does the corresponding changes to the flow controller
=> Refactor the Scheduler interface

tools/migration/Dockerfile
=> [Cherry-pick]Upgrade migrator base os to photon 2.0

tests/resources/APITest-Util.robot, tests/resources/Harbor-Pages/Project-Helmcharts.robot, tests/resources/Harbor-Pages/Project-Members.robot, tests/resources/Harbor-Pages/Project.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot
Add GUI test script for new feature of master-role, without adding a new case for master-role, I add new test steps in old test case named Manage-Project-Members, because master-role is a sub function in project members.
In this PR, I also modify a public action keyword to make it suitble for indefinite numbers of parameters.
Fixed: #6955
=> add master role in case manage project member of nightly test script

src/common/utils/clair/utils_test.go, src/common/utils/ldap/ldap.go, src/core/promgr/pmsdriver/admiral/admiral_test.go, src/core/service/notifications/clair/handler.go, src/jobservice/runtime/bootstrap.go, src/replication/trigger/cache.go
Some variable name, function name is colliding with builtin function.
File changed:
- src/common/utils/clair/utils_test.go
- src/common/utils/ldap/ldap.go
- src/core/promgr/pmsdriver/admiral/admiral_test.go
- src/core/service/notifications/clair/handler.go
- src/jobservice/runtime/bootstrap.go
- src/replication/trigger/cache.go
=> Fix colliding with builtin function

tests/resources/Harbor-Pages/Project.robot
=> debug-keyword-delete-repo-failed-occasionally

src/portal/lib/src/project-policy-config/project-policy-config.component.spec.ts
"mockPorjectPolicies" to "mockProjectPolicies".
=> Fix some misspells in code

src/common/dao/pgsql.go
This commit deletes the replication policies and jobs which are marked as "deleted" to fix #6698: cannot recreate the same name replication policy after it is deleted
=> [1.7.4]Run upgrade SQL to fix #6698

open_source_license
=> Update the OSL for v1.7.4

src/portal/src/app/project/member/add-member/add-member.component.ts, src/portal/src/app/user/user.service.ts
fix get users list about permission issue
about all user lists cannot be accessed when the user is authorized
=> fix get users list about permission issue

src/core/api/search.go, src/portal/src/app/base/global-search/search-result.component.ts, src/portal/src/app/base/global-search/search-results.ts
Fix issue that global search doesn't work
related issues:
#6753
#6435
#6740
#6738
=> Fix global search issue

.github/stale.yml
=> Add items to exemptlabels in stale.yml

src/core/api/projectmember.go, src/core/auth/ldap/ldap_test.go
=> Search local DB first when adding a project member with username

src/common/config/metadata/metadatalist.go, src/common/const.go, src/common/models/ldap.go, src/common/utils/ldap/ldap.go, src/core/config/config.go
The PR#6161 is pending on update too long, create another PR to merge it
=> Add new parameter ldap_group_membership_attribute (PR#6161)

docs/swagger.yaml, src/core/api/harborapi_test.go, src/core/api/user.go, src/core/api/user_test.go, src/core/router.go, tests/apitests/apilib/user.go
Add /users/search API for autocomplete input when create project member by projectAdmin.
=> Add users search API

docs/swagger.yaml, src/core/api/harborapi_test.go, src/core/api/replication_adapter.go, src/core/api/replication_adapter_test.go, src/core/router.go, src/replication/ng/adapter/adapter.go, src/replication/ng/adapter/adapter_test.go, src/replication/ng/flow/controller_test.go, src/replication/ng/model/registry.go
This commit implements the replication adapter API
=> Implement replication adapter API

README.md
Mailing lists updated + minor tweaks to the Slack links.
=> Harbor project contact information updated

docs/swagger.yaml, src/common/rbac/const.go, src/common/rbac/project/util.go, src/core/api/harborapi_test.go, src/core/api/replication_execution.go, src/core/api/replication_execution_test.go, src/core/router.go, src/replication/ng/operation/controller.go, src/replication/ng/replication.go
This commit implements the replication operation related APIs
=> Implement replication operation API

src/replication/ng/adapter/adapter.go, src/replication/ng/adapter/chart_registry.go, src/replication/ng/adapter/image_registry.go, src/replication/ng/flow/controller_test.go, src/replication/ng/flow/flow.go, src/replication/ng/model/policy.go, src/replication/ng/transfer/repository/registry.go, src/replication/ng/transfer/repository/transfer.go, src/replication/ng/transfer/repository/transfer_test.go
This commit refactors the Adapter interface and adjust the code in the flow controller and repository handler
=> Refactor the adapter interface

tools/notary-migration-fix.sh
The script is to fix the issue #7091, notary upgrade failure from mysql to pqsl.
=> add script to fix migration issue on notary

src/common/models/base.go, src/replication/ng/dao/models/policy.go, src/replication/ng/dao/policy.go, src/replication/ng/policy/manager.go
1. Define ng persist replication policy model.
2. Add ng replication policy CURD methods.
3. Implement ng policy manger.
Signed-off-by: Frank Kung <kfanjian@gmail.com>
=> Ng policy manager

.gitignore, src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/adapter/image_registry.go, src/replication/ng/replication.go
This commit provides a null implementation for Harbor adapter to fill data for the listing adapter API
=> Provide a null implementation for Harbor adapter

docs/swagger.yaml, src/core/api/harborapi_test.go, src/core/api/replication_execution_test.go, src/core/api/replication_policy_ng.go, src/core/api/replication_policy_ng_test.go, src/core/router.go, src/replication/ng/dao/policy.go, src/replication/ng/dao/policy_test.go, src/replication/ng/dao/registry.go, src/replication/ng/model/policy.go, src/replication/ng/model/registry.go, src/replication/ng/policy/manager.go, src/replication/ng/policy/manager_test.go, src/replication/ng/registry/manager.go, src/replication/ng/replication.go
This commit implements the replication policy management API
=> Implement replication policy management API

src/portal/lib/src/config/gc/gc.component.html, src/portal/lib/src/config/gc/gc.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
fix #7107 
1、If the current type is none, a post request should be sent to other types, otherwise it is a put request.
2、Modify the tooltip description of houly daily weekly
=> Fix returning internal error when setting cron for gc

src/replication/ng/flow/flow.go, src/replication/ng/scheduler/scheduler.go
Update the job ID for the task if it is scheduled successfully
=> Update the job ID in flow controller

docs/kubernetes_deployment.md, docs/swagger.yaml, tests/apitests/python/test_scan_image.py
fix some typos
Signed-off-by: yeya24 <ben.ye@daocloud.io>
=> fix some typos

src/common/utils/registry/auth/tokenauthorizer.go, src/core/api/replication_adapter_test.go, src/core/api/replication_execution.go, src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/execution/execution.go, src/replication/ng/execution/execution_test.go, src/replication/ng/flow/controller_test.go, src/replication/ng/flow/flow.go, src/replication/ng/replication.go
Implement the replication adapter for Harbor registry
=> Add Harbor adapter for replication

docs/swagger.yaml, src/common/models/robot.go, src/portal/src/app/project/robot-account/robot-account.component.html, src/portal/src/app/project/robot-account/robot.ts
=> update robot account return attribute

make/photon/db/Dockerfile
=> Fix hostname command not found

src/common/job/const.go, src/core/api/replication_execution.go, src/jobservice/job/impl/replication/ng/replication.go, src/jobservice/runtime/bootstrap.go, src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/flow/controller.go, src/replication/ng/flow/flow.go, src/replication/ng/replication.go, src/replication/ng/scheduler/scheduler.go, src/replication/ng/scheduler/scheduler_test.go
This commit fixes bugs found in the implement of replciation NG
=> Fix bug in replication

src/common/config/manager.go, src/common/config/manager_test.go
=> ldap_url and ldap_base_dn not exist in user config rest api when not configured

src/core/api/repository.go, src/portal/lib/src/repository/repository.component.spec.ts, src/portal/lib/src/service/interface.ts, src/portal/lib/src/tag/tag-detail.component.html, src/portal/lib/src/tag/tag-detail.component.spec.ts, src/portal/lib/src/tag/tag-detail.component.ts, src/portal/lib/src/tag/tag.component.spec.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> [Cherry-Pick]Include os version in image tag detail page

src/core/api/systeminfo.go
=> Expose HTTP auth proxy infor in systeminfo API

src/replication/ng/dao/execution.go, src/replication/ng/dao/execution_test.go, src/replication/ng/dao/models/execution.go, src/replication/ng/execution/execution_test.go
=> Execution updateStatus logic upgrade

tests/resources/Harbor-Util.robot
=> parse url for helm chart notary function

src/common/http/client.go, src/replication/ng/adapter/chart_registry.go, src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/adapter/harbor/chart_registry.go, src/replication/ng/adapter/harbor/image_registry.go, src/replication/ng/flow/controller_test.go, src/replication/ng/flow/flow.go, src/replication/ng/transfer/chart/transfer.go, src/replication/ng/transfer/repository/transfer_test.go
This commit provides the capability for Harbor to replicate helm charts
=> Replicate helm charts

docs/swagger.yaml, src/core/api/replication_adapter.go, src/core/api/replication_adapter_test.go, src/replication/ng/adapter/adapter.go, src/replication/ng/adapter/adapter_test.go, src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/flow/controller_test.go, src/replication/ng/model/policy.go, src/replication/ng/transfer/chart/transfer_test.go
This commit updates the listing/getting replication adapter API
=> Update listing/getting replication adapter API

src/portal/lib/src/config/config.ts, src/portal/package-lock.json, src/portal/src/app/config/auth/config-auth.component.html, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Add a item ldap_membership to LDAP config
=> Add membership item in LDAP config

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
add tooltip for src namespace.
=> add validation message

src/common/dao/dao_test.go, src/common/dao/user.go
Fix pagination for /users and /users/search APIs.
=> Fix pagination for users and users search apis

src/portal/lib/src/service/endpoint.service.ts
Remove the promise and change it to observable
=> Fix bugs that adapters can't display

src/core/api/search.go, src/core/api/search_test.go, src/portal/src/app/base/global-search/search-result.component.html, src/portal/src/app/base/global-search/search-result.component.ts, src/portal/src/app/base/global-search/search-results.ts, src/portal/src/app/project/list-project/list-project.component.html, src/portal/src/app/project/list-project/list-project.component.ts
cherry-pick fix global search issues
=> Cherry-pick global search fix to Release 1.7.0

src/core/service/notifications/registry/handler.go
Fixes #5729
Signed-off-by: Jan-Otto Kröpke <mail@jkroepke.de>
=> Remove user agent check for docker notifications -- Cherry pick to 1.7

src/replication/ng/adapter/image_registry.go, src/replication/ng/flow/stage_test.go, src/replication/ng/operation/controller.go, src/replication/ng/transfer/chart/transfer.go, src/replication/ng/transfer/repository/transfer.go, src/replication/ng/transfer/repository/transfer_test.go
This commit implements the delete function for image transfer
=> Implement deletion for image transter

src/core/service/notifications/jobs/handler.go, src/replication/ng/hook/task.go, src/replication/ng/hook/task_test.go
This commits converts job status to task status
=> Convert job status to replication task status

src/common/config/metadata/metadatalist.go, src/common/const.go, src/common/models/config.go, src/core/config/config.go, src/core/config/config_test.go
=> Settings for OIDC provider

docs/swagger.yaml, src/core/api/harborapi_test.go, src/core/api/registry.go, src/core/api/replication_adapter.go, src/core/api/replication_adapter_test.go, src/core/router.go, src/replication/ng/adapter/adapter.go, src/replication/ng/adapter/adapter_test.go, src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/flow/copy.go, src/replication/ng/flow/stage.go, src/replication/ng/flow/stage_test.go, src/replication/ng/model/policy.go, src/replication/ng/model/registry.go, src/replication/ng/operation/controller.go
This commit adds the Info() method to the registry adapter interface
=> Update the registry adapter interface

src/portal/src/app/app.module.ts, src/portal/src/app/project/helm-chart/list-chart-versions/helm-chart-versions-detail/helm-chart-version.component.ts, src/portal/src/app/project/helm-chart/list-charts-detail/helm-chart.component.ts, src/portal/src/app/shared/confirmation-dialog/confirmation-dialog.component.ts
=> moveHelmChartIssue

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss, src/portal/lib/src/create-edit-rule/create-edit-rule.component.spec.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts, src/portal/lib/src/replication/replication.component.html, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Add filter support in frontend. 
=> add filter logic

src/portal/lib/src/service/retag.service.ts
Should use baseURL from Config in frontend.
Issue: https://github.com/goharbor/harbor/issues/6712
=> Use baseURL from config

make/photon/prepare/utils/notary.py
Copy notary.upstream.conf to nginx config file
=> Fix: copy upstream file to nginx config file

src/portal/lib/src/cron-schedule/cron-schedule.component.html, src/portal/lib/src/cron-schedule/cron-schedule.component.ts, src/portal/lib/src/utils.ts
=> Add cron regular expression

CONTRIBUTING.md
update to the current version for the dependencies. 
=> add new version info for contributing guide

docs/swagger.yaml, src/core/api/harborapi_test.go, src/core/api/replication_execution.go, src/core/api/replication_execution_test.go, src/core/api/replication_policy_ng.go, src/core/api/replication_policy_ng_test.go, src/core/router.go, src/replication/ng/event/handler.go, src/replication/ng/event/handler_test.go, src/replication/ng/model/policy.go, src/replication/ng/model/policy_test.go, src/replication/ng/operation/controller.go, src/replication/ng/operation/controller_test.go, src/replication/ng/operation/flow/copy.go, src/replication/ng/operation/flow/copy_test.go, src/replication/ng/operation/flow/deletion.go, src/replication/ng/operation/flow/deletion_test.go, src/replication/ng/operation/flow/stage.go, src/replication/ng/operation/flow/stage_test.go, src/replication/ng/policy/manager/manager.go, src/replication/ng/policy/manager/manager_test.go, src/replication/ng/replication.go
1. Add getting execution by ID API
2. Return registry detail info in listing policies API
=> Update the replication API

src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html, src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.spec.ts, src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.spec.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts, src/portal/lib/src/endpoint/endpoint.component.spec.ts, src/portal/lib/src/list-replication-rule/list-replication-rule.component.html, src/portal/lib/src/list-replication-rule/list-replication-rule.component.spec.ts, src/portal/lib/src/list-replication-rule/list-replication-rule.component.ts, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.ts, src/portal/lib/src/replication/replication.component.spec.ts, src/portal/lib/src/service/endpoint.service.ts, src/portal/lib/src/service/interface.ts, src/portal/lib/src/service/replication.service.ts
1、Get registry detail  from listing policies API
2、Update the replicationJobItem  interface
3、Get the specified execution by id.
=> Get registry detail  from listing policies API

src/replication/ng/dao/execution.go, src/replication/ng/dao/execution_test.go
=> Fix execution end time bug

src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/adapter/image_registry.go, src/replication/ng/operation/scheduler/scheduler.go, src/replication/ng/registry/manager.go, src/replication/ng/util/util.go, src/replication/ng/util/util_test.go
1. Provide a util function to return a shared HTTP transport
2. Read secretkey from the configuration of replication
=> Provide a util function to return a common HTTP transport

docs/README.md
Signed-off-by: Xiang Dai <764524258@qq.com>
=> docs/README.md: update old url

make/photon/prepare/utils/configs.py
This is quick fix, further fixs will in the config refactor PR
=> Fix: clair env file should using empty string is not exist

make/migrations/postgresql/0004_1.8.0_schema.up.sql, src/core/api/registry.go, src/core/api/replication_execution.go, src/core/api/replication_execution_test.go, src/core/router.go, src/replication/ng/dao/models/execution.go, src/replication/ng/event/handler.go, src/replication/ng/event/handler_test.go, src/replication/ng/operation/controller.go, src/replication/ng/operation/controller_test.go, src/replication/ng/operation/flow/stage.go, src/replication/ng/operation/hook/task_test.go, src/replication/ng/policy/scheduler/scheduler.go
1. Add operation property for tasks
2. Add trigger property for executions
3. Update the getting registry info API to allow passing 0 as ID to get the info of local Harbor registry
=> Fix replication related issues

src/portal/src/app/account/sign-in/sign-in.component.html, src/portal/src/app/account/sign-in/sign-in.component.scss, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
In the login page ,we add button to jump to OIDC login page.
=> Add links to OIDC login

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss, src/portal/lib/src/create-edit-rule/create-edit-rule.component.spec.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts, src/portal/lib/src/harbor-library.module.ts, src/portal/lib/src/service.config.ts, src/portal/lib/src/service/replication.service.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1 Since backend api changed. source registry and destination registry need pass the whole object instead of id. frontend need to do corresponding change. 
2 Add translation for trigger and filter.
=> modify frontend replication UI to apply api changes. use dest registry as object

src/common/utils/utils.go, src/core/api/project.go, src/core/api/user.go, src/core/controllers/oidc.go
=> Add controller to onboard oidc user

docs/swagger.yaml, src/core/api/models/registry.go, src/core/api/registry.go
Allow update registry description.
Related issue: https://github.com/goharbor/harbor/issues/7128
=> Allow edit registry description

src/core/api/registry.go, src/replication/ng/registry/manager.go
Related issue: https://github.com/goharbor/harbor/issues/7128
=> Handle registry with empty credential

src/portal/src/app/account/sign-in/sign-in.component.html, src/portal/src/app/project/project-detail/project-detail.component.ts, tests/resources/Harbor-Pages/HomePage_Elements.robot
Solve the problem that when we login  the harbor page, the automation test will click on an incorrect button, which results in the test page unable to log in.
=> Fix nightly test case failed when login harbor. 

src/replication/ng/operation/controller.go, src/replication/ng/operation/controller_test.go, src/replication/ng/policy/manager/manager.go
Implement the function to support to stop the replication execution
=> Stop a replication execution

src/core/service/notifications/registry/handler.go, src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/adapter/image_registry.go
Filter the events triggerred by replication pull
=> Filter the events triggerred by replication

make/migrations/postgresql/0004_1.8.0_schema.up.sql, src/common/dao/dao_test.go, src/replication/ng/dao/models/policy.go, src/replication/ng/policy/manager/manager.go
Upgrade the registry and replication tables in database
=> Upgrade the registry and replication policy tables

docs/swagger.yaml, src/common/utils/registry/registry.go, src/core/api/harborapi_test.go, src/core/api/registry.go, src/core/api/registry_test.go, src/core/router.go, src/replication/ng/adapter/adapter.go, src/replication/ng/adapter/image_registry.go, src/replication/ng/model/registry.go, src/replication/ng/operation/controller_test.go, src/replication/ng/operation/flow/stage_test.go, src/replication/ng/registry/manager.go
=> Add registry ping API

make/migrations/postgresql/0004_1.8.0_schema.up.sql, src/common/dao/dao_test.go, src/replication/ng/dao/dao_test.go, src/replication/ng/dao/execution.go
This commit migrates the replication_job table, add one execution record and one task record for each job
=> Upgrade the replication_job table

src/portal/src/app/account/sign-in/sign-in.component.html, src/portal/src/app/account/sign-in/sign-in.component.scss, src/portal/src/app/account/sign-in/sign-in.component.ts, src/portal/src/app/base/navigator/navigator.component.ts, src/portal/src/app/oidc-onboard/oidc-onboard.component.ts
Add OIDC onboard page redirect to Harbor url when we login from OIDC and  add redirect page address when we login again after logout
1.when we are the first time we login harbor page when we login from OIDC  ,we add the url in onboard-add-username  page.
2.fix the part of issue that we cannot redirect to de origin page when we login
=> Add OIDC onboard page redirect to Harbor url when we login from OIDC 

src/common/config/store/driver/db.go
=> Remove error message of saving system setting to db

CHANGELOG.md
=> Update CHANGELOG.md to make it up to date

src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/adapter/harbor/adapter_test.go, src/replication/ng/adapter/harbor/chart_registry_test.go, src/replication/ng/adapter/harbor/image_registry_test.go, src/replication/ng/model/registry.go
Add unit test cases for Harbor adapter
=> Add unit test cases for Harbor adapter

src/core/api/replication_execution.go, src/core/api/replication_execution_test.go, src/replication/ng/dao/models/execution.go, src/replication/ng/event/handler_test.go, src/replication/ng/model/policy.go, src/replication/ng/operation/controller.go, src/replication/ng/operation/hook/task_test.go, src/replication/ng/policy/manager/manager.go, src/replication/ng/policy/manager/manager_test.go
Handle the policy from previous versions
=> Handle the policy from previous versions

src/replication/ng/dao/registry.go, src/replication/ng/registry/manager.go
Update only specified props in registry updating, especially when update health status.
=> Update only specific props in registry update

src/portal/lib/src/create-edit-rule/create-edit-rule.component.spec.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
1 fix the console error in edit policy. 
2 fix the filter edit in pull mode.
=> modify some issues of create replication policy 

make/photon/prepare/utils/docker_compose.py
=> [Cherry-Pick] Fix make prepare problem

tests/apitests/python/library/project.py, tests/apitests/python/library/repository.py, tests/apitests/python/test_retag.py, tests/robot-cases/Group0-BAT/API_DB.robot
Add API test case for retag, create a user and 2 projects by this new user, push image to 1st project, and retag this image to 2nd project.
=> Add API test case for retag

src/portal/src/app/account/account.module.ts, src/portal/src/app/app.module.ts, src/portal/src/app/base/base.module.ts, src/portal/src/app/harbor-routing.module.ts, src/portal/src/app/shared/route/auth-user-activate.service.ts, src/portal/src/app/sign-in/sign-in.component.html, src/portal/src/app/sign-in/sign-in.component.scss, src/portal/src/app/sign-in/sign-in.component.ts, src/portal/src/app/sign-in/sign-in.module.ts, src/portal/src/app/sign-in/sign-in.service.ts
change the login module to fix the issue that the nav is being in page when we login harbor again,
and change harbor router .
=> Change the login module

docs/swagger.yaml, src/core/api/harborapi_test.go, src/core/api/registry.go, src/core/api/registry_test.go
Fix bug in ping registry API: accept both ID and other properties
=> Fix bug in ping registry API

docs/swagger.yaml, src/core/api/registry.go, src/core/router.go, src/replication/ng/adapter/harbor/adapter.go, src/replication/ng/adapter/harbor/adapter_test.go
To query the namespace of the registry according to its ID.
=> Add api to get namespaces of registry

src/replication/ng/adapter/huawei/huawei_adapter.go, src/replication/ng/adapter/huawei/huawei_adapter_test.go, src/replication/ng/adapter/huawei/image_registry.go, src/replication/ng/adapter/huawei/image_registry_test.go
Signed-off-by: Yuan Lei <yuanlei9@huawei.com>
=> huawei cloud registry adapter for replication

src/replication/ng/adapter/harbor/chart_registry.go, src/replication/ng/adapter/harbor/filter.go, src/replication/ng/adapter/harbor/filter_test.go, src/replication/ng/adapter/harbor/image_registry.go, src/replication/ng/transfer/repository/transfer.go
Add filter support when fetching resources for Harbor adapter
=> Add filter support when fetching resources for Harbor adapter

tests/resources/Harbor-Pages/HomePage_Elements.robot
In UI, sign-in element xpath has changed, so it need to be modified to the new one.
=> Modify xpath of sign-in element

.travis.yml, src/replication/ng/replication.go, tests/robot-cases/Group0-BAT/API_DB.robot
Remove the E2E test cases for replication
=> Remove the E2E test cases for replication

src/core/api/registry.go, src/core/api/registry_test.go
Check health status when add registry, so that invalid registry won't be added.
=> Check health status when add registry

src/jobservice/job/impl/replication/ng/replication.go, src/replication/ng/adapter/image_registry.go, src/replication/ng/adapter/native/adapter.go, src/replication/ng/adapter/native/image_registry.go, src/replication/ng/replication.go
=> Implement native docker registry.

src/core/api/replication_policy_ng.go, src/replication/ng/operation/controller.go, src/replication/ng/operation/flow/stage.go
=> Correct some typos and do some small adjustments

src/core/api/replication_policy_test.go, src/replication/adapter/harbor/adapter.go, src/replication/adapter/harbor/image_registry.go, src/replication/adapter/harbor/image_registry_test.go, src/replication/model/policy.go, src/replication/model/policy_test.go
Support replication all projects in Harbor
=> Support replication all projects in Harbor

src/replication/adapter/image_registry.go, src/replication/adapter/native/adapter.go, src/replication/adapter/native/image_registry.go
Check the existence of repository if the name filter contains no * and ?
=> Fix buf in native docker registry adapter

src/replication/adapter/dockerhub/adapter.go, src/replication/adapter/dockerhub/client.go, src/replication/adapter/image_registry.go
Fix: https://github.com/goharbor/harbor/issues/7371
=> Support anonymous access to dockerhub

src/core/api/registry.go, src/core/api/replication_execution_test.go, src/core/api/replication_policy.go, src/core/api/replication_policy_test.go, src/replication/adapter/harbor/adapter.go, src/replication/dao/registry.go, src/replication/event/handler.go, src/replication/event/handler_test.go, src/replication/model/policy.go, src/replication/model/policy_test.go, src/replication/model/registry.go, src/replication/registry/manager.go
The "LocalHarbor" is the type of registry where the replication service is running on
=> Add new registry type: LocalHarbor

make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
rendering 443 when https enabled
rendering 4443 when notary enabled
=> Fix bug when rendering port in proxy

src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/create-edit-rule/create-edit-rule.component.spec.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts, src/portal/lib/src/endpoint/endpoint.component.ts, src/portal/lib/src/list-replication-rule/list-replication-rule.component.html, src/portal/lib/src/list-replication-rule/list-replication-rule.component.scss, src/portal/lib/src/list-replication-rule/list-replication-rule.component.spec.ts, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.scss, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.ts, src/portal/lib/src/replication/replication.component.html, src/portal/lib/src/replication/replication.component.spec.ts, src/portal/lib/src/service/interface.ts, src/portal/lib/src/shared/shared.utils.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
fix #7372 #6808 
1、Fix wrong error message is shown to users when creating registries
2、Add an override field when creating a policy
3、Execution lists and details pages show total and stopped information
=> Fix replication frontend issues

docs/swagger.yaml
=> Fix swagger typo for updating robot account status

src/portal/src/app/harbor-routing.module.ts, src/portal/src/app/project/project-detail/project-detail.component.html, src/portal/src/app/project/project-detail/project-detail.component.ts
fix #7405 
Remove the Replication tab under project view
=> Remove the Replication tab under project view

src/portal/lib/src/repository-gridview/repository-gridview.component.spec.ts
recovery a test case about 'should filter data by keyword'  in the test file named  repository-gridview.component.spec.ts
=> Recovery a test case about 'should filter data by keyword' in the test file named repository-gridview.component.spec.ts

make/photon/prepare/templates/registry/config.yml.jinja
Add compatibility config in registry.yml
=> Add compatibility config

src/replication/adapter/native/image_registry.go, src/replication/adapter/native/image_registry_test.go
=> Optimizing native adapter

src/common/api/base.go
=> Disable throw internal error to UI

src/replication/adapter/dockerhub/adapter.go, src/replication/adapter/dockerhub/client.go
=> Fix create ns failure in DockerHub

src/replication/adapter/dockerhub/adapter.go, src/replication/adapter/dockerhub/consts.go
Issue: https://github.com/goharbor/harbor/issues/7369
=> Dockerhub delete image

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/list-replication-rule/list-replication-rule.component.ts, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.scss, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.ts
fix #7437 
1、Fix replication tasks page cannot pagination
2、Fix can also check the checkbox without clicking on the label.
=> Fix replication tasks page cannot pagination

src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html, src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.scss, src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts, src/portal/lib/src/replication/replication.component.ts
fix #7429 
If adapter select dockerhub, url hardcode "https://registry-1.docker.io"
=> Fix failed executions does not show duration

make/harbor.yml, tests/hostcfg.sh
Default mode to https
The cert file value is set to previous version style
=> Set default mode to https

make/photon/prepare/Pipfile, make/photon/prepare/Pipfile.lock
=> Upgrade the version of jinja2

docs/swagger.yaml, make/migrations/postgresql/0004_1.8.0_schema.up.sql, src/common/dao/oidc_user.go, src/common/dao/oidc_user_test.go, src/core/api/user.go, src/core/router.go
This commit provide an API to allow a user that is onboarded via OIDC
authn update his CLI secret.
=> Provide API to generate CLI secret

src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html, src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/list-replication-rule/list-replication-rule.component.html, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/portal/lib/src/replication/replication.component.html, src/portal/lib/src/replication/replication.component.scss, src/portal/lib/src/service/endpoint.service.ts, src/portal/lib/src/service/interface.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1、Test ping API does not support accepting credential in object form, So modify the parameter to access_key and access_secret
2、Do not disable url when editing registries
3、Do not disable url when type is dockerhub
=> Modify some issues of test ping registry and edit registry

src/replication/adapter/native/adapter_test.go, src/replication/adapter/native/image_registry.go, src/replication/adapter/native/image_registry_test.go, src/replication/util/util.go, src/replication/util/util_test.go
1. Add IsSpecificRepositoryName util method.
2. Add IsSpecificRepositoryName unit test case.
3. Add Copyright header comment.
Signed-off-by: 慕薇疯魔 <kfanjian@gmail.com>
=> IsSpecificRepositoryName

tests/resources/Harbor-Pages/Replication.robot, tests/resources/Harbor-Pages/Replication_Elements.robot, tests/robot-cases/Group1-Nightly/Replication.robot
Due to replication NG feature already in master branch, old replication UI test cases have been moved out of Jenkins pipeline, and here test case add-replication-test-case-Endpoint-Verification has been finished and ready for duty.
=> Add replication test case add-replication-test-case-Endpoint-Verification 

src/core/api/ldap.go
=> fix error message when auth_mod is not ldap 

src/chartserver/chart_operator.go, src/chartserver/reverse_proxy.go, src/common/const.go, src/core/api/chart_repository.go
Use chart API to load the uploaded chart file to get the name and version
=> Fix chart upload issue on event based

src/replication/registry/manager.go
Fix bug: cannot update the registry that has no credential when creating it
=> Fix bug: cannot update the registry

src/portal/lib/src/label/label.component.html, src/portal/lib/src/label/label.component.scss, src/portal/lib/src/repository-gridview/repository-gridview.component.html, src/portal/lib/src/repository-gridview/repository-gridview.component.scss, src/portal/src/app/project/helm-chart/list-charts-detail/helm-chart.component.scss, src/portal/src/app/project/member/member.component.scss, src/portal/src/app/project/robot-account/robot-account.component.scss
Adjust the margin top the label tab page  to match the other tab pages 
=> Align all tab spacing between project and configuration pages

src/portal/lib/src/tag/tag-detail.component.html, src/portal/lib/src/tag/tag.component.html
=> Fix history display

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
fix #7428
Add tooltips for creating replication rule
=> Add tooltips for creating replication rule

src/portal/src/app/base/navigator/navigator.component.ts
remove the ability  to change passwords when user login harbor through OIDC.
=> Remove OIDC's ability to change passwords

src/replication/adapter/dockerhub/adapter.go, src/replication/operation/controller.go, src/replication/operation/controller_test.go, src/replication/operation/flow/copy.go, src/replication/operation/flow/deletion.go, src/replication/operation/flow/deletion_test.go, src/replication/operation/flow/stage.go, src/replication/operation/flow/stage_test.go
Call filterResources direclty if resource isn't null in copy flow
=> Fix bug found in replication

src/common/secret/store.go, src/common/utils/ldap/ldap_test.go, src/core/api/models/admin_job_test.go, src/core/auth/db/db_test.go
=> Remove adminserver in sourcecode

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/endpoint/endpoint.component.ts, src/portal/lib/src/list-replication-rule/list-replication-rule.component.ts, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/portal/lib/src/replication/replication.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Get delete or copy failure information directly and display
=> Get delete or replicate failure information directly and display

src/core/api/user.go
=> Check whether user is nil in Prepare() of users API

src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.ts
Get the number of execution status every 10s and refresh the task list
=> Get the number of execution status every 10s and refresh the task list

src/portal/lib/src/list-replication-rule/list-replication-rule.component.html, src/portal/lib/src/tag/tag.component.html
Add label in project page will cause a javascript error in console. that is because define a value of undefined. Need to check the value if undefined. 
=> fix replication add label console error

src/core/api/reg_gc.go
=> Add gc parameters when to update gc schedule

src/replication/adapter/harbor/chart_registry.go
=> Remove the workaround for checking chart existence

src/replication/adapter/harbor/adapter.go, src/replication/adapter/image_registry.go, src/replication/config/config.go, src/replication/dao/execution.go, src/replication/dao/execution_test.go, src/replication/dao/models/execution.go, src/replication/event/handler.go, src/replication/model/registry.go, src/replication/operation/execution/execution_test.go, src/replication/operation/flow/stage.go, src/replication/operation/flow/stage_test.go, src/replication/replication.go, src/replication/transfer/image/transfer.go
Don't fail the process when one tag replication failed
=> Don't fail the process when one tag replication failed

docs/swagger.yaml, src/core/api/systeminfo.go
=> Add Ext URL to response of systeminfo API

src/common/rbac/const.go, src/common/rbac/project/util.go, src/common/rbac/project/visitor_role.go, src/common/security/local/context_test.go, src/common/security/robot/context_test.go, src/common/security/secret/context_test.go
Remove push+pull action from rbac pkg which fix #6881
=> Remove push+pull action

docs/kubernetes_deployment.md, docs/swagger.yaml, src/portal/lib/src/service/project.service.ts, tests/apitests/python/test_scan_image.py
"infomation" to "information".
"fimiliar" to "familiar".
=> Fix some misspells in file

src/common/job/client.go, src/core/api/admin_job.go
Use the latest error or success execution as the periodic job log
=> Fix get log issue of Periodic job

make/harbor.yml
=> Fix typo in harbor.yml

src/core/api/replication_policy.go
Check the task status of execution whose status is running when deleting the policy
=> Check the task status of execution whose status is running when deleting the policy

src/portal/lib/src/operation/operate.ts, src/portal/lib/src/repository-gridview/repository-gridview.component.ts, src/portal/lib/src/service/interface.ts, src/portal/src/app/config/auth/config-auth.component.html, src/portal/src/app/config/auth/config-auth.component.scss, src/portal/src/app/config/auth/config-auth.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1. add OIDC Redirect url on configration.
2. fix delete repository bug.
3. fix operation refresh bug when user Appears when the refresh button is clicked on replicate.
=> Add OIDC Redirect url and fix delete repository bug and fix operation refresh bug

src/core/api/systeminfo.go
=> Disable CA download when hosted via HTTP

src/portal/lib/src/config/gc/gc.component.ts, src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts, src/portal/lib/src/endpoint/endpoint.component.ts, src/portal/lib/src/label/label.component.ts, src/portal/lib/src/list-replication-rule/list-replication-rule.component.ts, src/portal/lib/src/replication/replication.component.ts, src/portal/lib/src/repository-gridview/repository-gridview.component.ts, src/portal/lib/src/shared/shared.utils.ts, src/portal/lib/src/tag/tag.component.ts, src/portal/src/app/group/group.component.ts, src/portal/src/app/project/helm-chart/list-chart-versions/helm-chart-versions-detail/helm-chart-version.component.ts, src/portal/src/app/project/helm-chart/list-charts-detail/helm-chart.component.ts, src/portal/src/app/project/list-project/list-project.component.ts, src/portal/src/app/project/member/add-group/add-group.component.ts, src/portal/src/app/project/member/member.component.ts, src/portal/src/app/project/robot-account/robot-account.component.ts, src/portal/src/app/shared/shared.utils.ts, src/portal/src/app/user/user.component.ts
change request mode specified as API acquisition.
=> Change request mode specified as API acquisition

src/core/filter/security.go
=> Fix condition for OIDC security filter

src/core/config/config.go
=> fix issue7637: /api/systeminfo cannot return 500 when DB is down

make/migrations/postgresql/0004_1.8.0_schema.up.sql, src/core/api/replication_policy.go, src/replication/adapter/harbor/adapter.go, src/replication/adapter/harbor/adapter_test.go, src/replication/adapter/harbor/chart_registry.go, src/replication/adapter/harbor/image_registry.go, src/replication/dao/execution.go, src/replication/model/policy.go
1. handle the public/private property when creating the projects
2. extend the length of access_secret
3. update the task status by using orm functions
=> Fix a few bugs of replication

src/replication/transfer/image/transfer.go
Replicate just one image if the media type is manifest list
=> Replicate just one image if the media type is manifest list

make/harbor.yml, make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja, make/photon/prepare/utils/configs.py, make/photon/prepare/utils/docker_compose.py
=> Alow user to set CA cert for UAA in harbor.yml

src/common/http/client.go, src/replication/adapter/harbor/adapter.go, src/replication/adapter/harbor/image_registry.go
Iterate all paginations when listing projects and repositories
=> Iterate all paginations when listing projects and repositories

src/portal/lib/src/inline-alert/inline-alert.component.ts, src/portal/src/app/global-message/message.ts, src/portal/src/app/project/create-project/create-project.component.ts, src/portal/src/app/shared/inline-alert/inline-alert.component.ts
fix create project error show in modal;resolve the different color of notification in UI.
=> Fix create project error show in modal;resolve the different color of notification in UI.

make/photon/prepare/templates/jobservice/config.yml.jinja
=> Clean admin server related config

src/portal/src/app/config/auth/config-auth.component.html, src/portal/src/app/config/auth/config-auth.component.scss, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Move redirectUrl tip,fix pattern with endpoint,fix incorrect tip message for invalid input of OIDC scope
=> Move redirectUrl tip,fix pattern with endpoint,fix incorrect tip message for invalid input of OIDC scope

src/portal/src/app/sign-in/sign-in.component.ts, src/portal/src/app/user/user.component.ts
fix “Delete” and "Reset Password" should be hidden in user management page;forget Password should be hidden when oidc mode;
=> Fix “Delete” and "Reset Password" should be hidden in user management page;forget Password should be hidden when oidc mode;

src/core/proxy/interceptor_test.go, src/core/proxy/interceptors.go, src/core/proxy/proxy.go, src/core/service/notifications/registry/handler.go
1, Add a interceptor to block request to upload manifest list
2, Discard notiification without tag.
=> add multiple manifest intercepetor handler

src/core/api/user.go
=> Don't display password when calling api/users API.

src/replication/adapter/dockerhub/adapter_test.go, src/replication/adapter/dockerhub/client.go
Add more unit test cases for docker hub adapter
=> Add more unit test cases for docker hub adapter

src/common/utils/log/logger.go
This would help as we have more and more source files having duplicated
names.
Fixes #7202
=> print more sectors of file path in logger

src/replication/operation/controller.go, src/replication/operation/flow/copy.go, src/replication/operation/flow/stage.go, src/replication/operation/flow/stage_test.go
Fix #7579: cannot stop the execution during the initialization stage
=> Fix #7579: cannot stop the execution during the initialization stage

make/migrations/postgresql/0004_1.8.0_schema.up.sql, src/common/models/adminjob.go, src/common/utils/utils.go, src/core/api/admin_job.go, src/core/api/models/admin_job.go, src/core/api/models/admin_job_test.go
=> add scan all and gc schedule migration

src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
fix #7701 
New replication rule dialog will always show filter loading when call API failed，
Add error handling, loading disappears and displays error message when call API failed
=> Fix filter will always show loading when call API failed

README.md, docs/installation_guide.md
=> Update required docker and docker-compose version

README.md, docs/installation_guide.md
=> bump up required docker compose version to 1.18

src/core/api/admin_job.go
1, Throw the error of job service to UI when to create job schedule.
2, Return 200 when to save none without schedule.
Fixed #7675
=> Return 200 when to post an none schedule

make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja, make/photon/prepare/utils/chart.py, make/photon/prepare/utils/docker_compose.py
Add volumn binding on docker-compose.yml
=> Fix chart storage keyfile issue in gcs

src/portal/lib/src/config/gc/gc-history/gc-history.component.scss, src/portal/lib/src/config/gc/gc-history/gc-history.component.ts, src/portal/lib/src/config/gc/gc.component.ts
Automatically refresh the list when the status of gc history is pending or running
=> Automatically refresh the list when the status of gc history is pending or running

src/portal/src/app/config/auth/config-auth.component.ts, src/portal/src/app/config/config.component.html, src/portal/src/app/config/config.component.ts, src/portal/src/app/config/email/config-email.component.ts
Fix question of `Cancel` of OIDC configuration does not work;
fix #7678
=> Fix question of `Cancel` of OIDC configuration does not work

make/migrations/postgresql/0004_1.8.0_schema.up.sql, src/replication/policy/manager/manager.go, src/replication/policy/manager/manager_test.go
Fixes #7693, the filters of replication policy is lost after upgrade
=> Fixes #7693, the filters of replication policy is lost after upgrade

make/kubernetes/adminserver/adminserver.deploy.yaml, make/kubernetes/templates/adminserver.cm.yaml, make/photon/prepare/templates/core/env.jinja, src/common/config/metadata/metadata_test.go, src/common/config/metadata/metadatalist.go, src/common/const.go, src/common/utils/ldap/ldap_test.go, src/common/utils/notary/helper_test.go, src/common/utils/test/config.go, src/common/utils/test/test.go, src/core/auth/db/db_test.go, src/core/auth/ldap/ldap_test.go, src/core/controllers/controllers_test.go, src/core/proxy/interceptor_test.go, src/portal/lib/src/config/config.ts
=> Remove unused configure item cfg_expiration

tools/migration/cfg/run.py, tools/migration/migrator.py
Fixes #7680 
I'll open another PR to update the document
=> Require output path for harbor.cfg->harbor.yml migration

src/portal/src/app/config/auth/config-auth.component.html, src/portal/src/app/config/auth/config-auth.component.scss, src/portal/src/app/config/auth/config-auth.component.ts
Add Oidc more info link in configration
=> Add Oidc more info link in configration

make/install.sh
=> Update the version check in install.sh

docs/migration_guide.md
Make necessary updates to reflect the new command to migrate
configuration file from harbor.cfg to harbor.yml
Fixes #7054 
=> Update migration guide for v1.8.0

tools/migration/cfg/run.py, tools/migration/cfg/utils.py, tools/migration/migrator.py
=> Enable cfg migration from v1.8.0

src/jobservice/worker/cworker/c_worker_test.go
=> Fix UT case failure

docs/configure_user_settings.md, docs/installation_guide.md
=> Add document for config user settings

make/harbor.yml
=> Update default value of external_database

tests/resources/Harbor-Pages/Replication.robot
Missing modification in keyword <Create A New Endpoint>, due to changing of docker-hub select item, it must be modified.
=> Modify keyword <Create A New Endpoint>

make/photon/prepare/utils/registry.py
jinja2 render None to empty string
=> Fix None rendered in jinja2

make/install.sh
=> Fix a bug of checking docker version in install.sh

make/photon/prepare/utils/configs.py
if https port is 443 or http port is 80, then only showing url
=> Fix public url shoud not display port is it's default value

make/migrations/postgresql/0004_1.8.0_schema.up.sql
In v1.7.0, it creates an record for scan all but without cron string, just update the record with the cron in properties.
=> Fix migrator scan all schedule from v1.7.0

docs/installation_guide.md, make/harbor.yml
Document how to use the external database in installation guide. Fixes #7189
=> Document how to use the external database in installation guide

tests/resources/Harbor-Util.robot
=> Enable migrator in offline installer

src/portal/lib/src/config/gc/gc.component.ts, src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts, src/portal/lib/src/cron-schedule/cron-schedule.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Fix_cron schedule bug when call api ' get/schedule '   error

make/photon/prepare/templates/notary/signer-config.postgres.json.jinja
=> Fix issue caused by notary default_alias

src/portal/src/app/sign-in/sign-in.component.ts
add a way to login to OIDC by clicking login button through response status 403
=> Add a way to login to OIDC by clicking login button

src/portal/lib/src/config/gc/gc.component.ts, src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts, src/portal/lib/src/cron-schedule/cron-schedule.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Fix_cron schedule bug when call api ' get/schedule ' error
=> Fix_cron schedule bug when call api ' get/schedule ' error

make/photon/prepare/templates/registry/config.yml.jinja
it should be disable not disabled
=> Typo in registry config - cherrypick to 1.8

make/photon/prepare/templates/registry/config.yml.jinja
it should be disable not disabled
=> Typo in registry config

src/core/controllers/oidc.go
=> Set the real name of OIDC user when onboarding

src/core/api/ldap.go
=> fix issue7793: ping ldap server is always success

src/core/api/ldap.go
Signed-off-by: stonezdj stonezdj@gmail.com
=> cherry-pick fix issue7793: ping ldap server is always success

src/core/controllers/oidc.go
=> Set the real name of OIDC user when onboarding -cherrypick to 1.8 branch

make/harbor.yml, make/photon/prepare/templates/jobservice/config.yml.jinja, make/photon/prepare/utils/configs.py, make/photon/prepare/utils/jobservice.py
log level in job server can be controlled by harbor.yml
=> Made logs in jobservice configurable

src/portal/src/app/project/create-project/create-project.component.ts, src/portal/src/app/project/robot-account/add-robot/add-robot.component.html, src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts
clear inlineAlert when reopen create project;change add robot error handle
fix #7804
=> Clear inlineAlert when reopen create project;change add robot error handle

src/common/models/robot.go, src/core/api/robot.go, src/core/api/robot_test.go
=> add validation for robot account registration

make/photon/prepare/utils/chart.py
=> Fix typo in azure config

docs/installation_guide.md, make/harbor.yml, make/photon/prepare/utils/configs.py
=> Update doc caused by refactor prepare

tests/resources/Cert-Util.robot, tests/resources/Docker-Util.robot, tests/resources/Harbor-Pages/OIDC_Auth.robot, tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot, tests/resources/Nightly-Util.robot, tests/resources/TestCaseBody.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot, tests/robot-cases/Group1-Nightly/LDAP.robot, tests/robot-cases/Group1-Nightly/OIDC.robot, tests/robot-cases/Group3-Upgrade/verify.robot
OIDC authentication is a new feature in version 1.8.0, so add nightly GUI test cases for OIDC authentication scenario.
=> Add nightly GUI test cases for OIDC authentication scenario

src/core/auth/authproxy/auth.go
=> Add ensure settings when to search user in auth proxy

tests/resources/Harbor-Pages/OIDC_Auth.robot, tests/resources/Harbor-Pages/Project-Members.robot, tests/resources/Harbor-Pages/Project.robot, tests/resources/TestCaseBody.robot, tests/robot-cases/Group1-Nightly/Common.robot, tests/robot-cases/Group1-Nightly/OIDC.robot
Add test case for oidc auth mode
=> Add test case for oidc auth mode

src/portal/src/app/vulnerability-page/vulnerability-page.component.html, src/portal/src/app/vulnerability-page/vulnerability-page.component.scss, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
edit the words width vulnerability and robot;
=> Edit the words width vulnerability and robot;

tests/resources/Harbor-Pages/Project-Members.robot, tests/resources/TestCaseBody.robot, tests/robot-cases/Group1-Nightly/Common.robot
Fix bug for manage-project-member, due to keywords changed for oidc-auth-mode, test case  manage-project-member should be debug at the same time.
=> Fix parameters bug for manage-project-member

docs/installation_guide.md
I update the name of two parameters for log according to harbor.yml.
And delete some red tails. 
Signed-off-by: zhihui wu <wu.zhihui1@zte.com.cn>
=> [Docs] Update the name of two parameters for log

tests/resources/Docker-Util.robot, tests/resources/Harbor-Pages/OIDC_Auth.robot, tests/resources/Harbor-Pages/OIDC_Auth_Elements.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/OIDC.robot
Add test case secret-verify for oidc-auth-mode feature by adding some keywords and one test cases.
=> Add test case secret-verify for oidc-auth-mode feature

src/common/models/robot.go, src/core/api/robot.go
=> Return account id when to issue a robot

src/common/models/robot.go, src/core/api/robot.go
=> remove the id in the post body when to create a robot account

src/portal/lib/package.json, src/portal/package-lock.json, src/portal/package.json, src/portal/src/app/app.module.ts, src/portal/src/app/base/navigator/navigator.component.scss
fix bug when we use language with pt-br;
change the harbor version from 1.7.x to 1.8
=> Fix bug when we use language with pt-br; change the harbor version from 1.7.x to 1.8

docs/swagger.yaml
Fixes https://github.com/goharbor/harbor/issues/7861
=> Update version in swagger yaml - cherry pick to 1.8 branch

docs/swagger.yaml
=> Update version in swagger yaml

src/portal/src/app/account/account-settings/account-settings-modal.component.html
=> Add id for element in html

src/core/api/repository.go, src/replication/transfer/image/transfer.go
=> Fix replication bug

tests/resources/Harbor-Util.robot
=> Remove the compile golang image tag setting when to build offline

src/jobservice/config.yml, src/jobservice/migration/manager.go, src/jobservice/migration/manager_test.go, src/jobservice/migration/migrator.go, src/jobservice/migration/migrator_v180.go, src/jobservice/migration/version.go, src/jobservice/runtime/bootstrap.go, src/jobservice/runtime/bootstrap_test.go
fix issue #7988
fix issue #7868 
=> add migration process for rdb as well as UT cases

make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
=> Change the mount target of gcs.key file(master)

make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
=> Change the mount target of gcs.key file(1.8.1)

tests/resources/Harbor-Util.robot
=> Fix issue on building package offline and online installer

src/portal/lib/src/shared/shared.utils.ts, src/portal/src/app/log/audit-log.component.ts, src/portal/src/app/project/member/member.component.ts
Fix issue  click members and logs tab in project detail page portal will redirect to projects list page when call API failed; #7696
=> Fix issue  click members and logs tab in project detail page portal will redirect to projects list page when call API failed

src/jobservice/worker/cworker/c_worker_test.go
increase the waiting time of the test case
=> fix failure UT case of job service

README.md, docs/configure_https.md, docs/installation_guide.md
=> Update doc for configure https

tests/integration.sh
=> Enable push dev images on release branch

tests/resources/Harbor-Util.robot
=> Fix issues on packaging offline installer

src/core/api/repository.go
=> Set Event.Type value to event.EventTypeImageDelete instead of event.EventTypeImagePush when deleting

docs/swagger.yaml, make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/common/dao/cve_whitelist.go, src/common/dao/cve_whitelist_test.go, src/common/models/base.go, src/common/models/cve_whitelist.go, src/core/api/harborapi_test.go, src/core/api/sys_cve_whitelist.go, src/core/api/sys_cve_whitelist_test.go, src/core/router.go, src/replication/dao/dao_test.go
=> API for system level vulnerability whitelist

src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html, src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.scss, src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
ui enhance for gcr replication,
depend on https://github.com/goharbor/harbor/pull/7946
=> ui change: gcr/ecr driver for replication

src/replication/dao/dao_test.go, src/replication/operation/execution/execution_test.go
Clean up the dao test for replication
=> Clean up the dao test for replication

src/jobservice/job/impl/replication/replication.go, src/replication/adapter/azurecr/adapter.go, src/replication/adapter/azurecr/adapter_test.go, src/replication/adapter/image_registry.go, src/replication/adapter/native/adapter.go, src/replication/adapter/native/adapter_test.go, src/replication/adapter/native/image_registry.go, src/replication/adapter/native/image_registry_test.go, src/replication/model/registry.go, src/replication/replication.go
Implement Azure ACR adapter to replicate images between Harbor and Azure ACR
Issue: https://github.com/goharbor/harbor/issues/7978
=> Implement azure acr adapter

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/create-edit-rule/create-edit-rule.component.scss, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts, src/portal/lib/src/service/interface.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Add label filter in replication Ng

src/portal/lib/src/vulnerability-scanning/result-tip.componnent.html
=> Fix the different width on vulnerability

docs/manage_role_by_ldap_group.md
=> Update LDAP group documents

src/common/rbac/project/util.go, src/common/rbac/project/visitor_role.go, src/core/api/projectmember_test.go
Fix the missing for read permission of project member read API
=> Fix read permission of project member read api

docs/compile_guide.md, docs/use_make.md
Signed-off-by: Mark Peek <markpeek@vmware.com>
=> Reflect change to golang:1.12.5 in the docs

Makefile
Signed-off-by: Mark Peek <markpeek@vmware.com>
=> Fix a couple of error message typos in the Makefile

src/replication/filter/filter.go, src/replication/filter/filter_test.go, src/replication/model/policy.go, src/replication/model/policy_test.go, src/replication/policy/manager/manager.go
Support specify multiple labels in one label filter
=> Update replication label filter

src/jobservice/common/rds/keys.go
=> [Cherry-pick]use separate key for the last periodic enqueue data

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/common/dao/quota.go, src/common/dao/quota_test.go, src/common/dao/quota_usage.go, src/common/dao/quota_usage_test.go, src/common/models/base.go, src/common/models/quota.go, src/common/models/quota_usage.go
=> Add dao for quota

src/common/utils/oidc/helper.go, src/common/utils/oidc/helper_test.go
This commit make sure the OIDC is more actively recreated, to mitigate
the problem in #8177
=> Reload OIDC provider older than 3 seconds

src/common/rbac/project/util.go, src/common/rbac/project/visitor_role.go, src/core/api/projectmember_test.go
Fix the missing for read permission of project member read API
=> [Cherry pick]Fix read permission of project member read api

src/common/dao/group/usergroup.go, src/common/dao/group/usergroup_test.go, src/common/dao/project.go, src/common/dao/project/projectmember.go, src/common/dao/project/projectmember_test.go, src/common/dao/project_test.go, src/common/dao/utils.go, src/common/dao/utils_test.go, src/common/models/project.go, src/common/models/user.go, src/common/security/local/context.go, src/common/security/local/context_test.go, src/core/auth/ldap/ldap.go, src/core/promgr/pmsdriver/local/local.go
=> Refactor LDAP usergroup

src/common/dao/base.go, src/common/dao/dao_test.go, src/common/models/quota.go, src/common/models/quota_usage.go, src/common/quota/manager.go, src/common/quota/manager_test.go, src/common/quota/resources.go, src/common/quota/resources_test.go, src/common/quota/util.go, src/common/quota/util_test.go
=> Add manager for quota

src/pkg/retention/client.go, src/pkg/retention/job.go, src/pkg/retention/policy/builder.go, src/pkg/retention/policy/models.go, src/pkg/retention/res/candidate.go, src/pkg/retention/res/result.go
=> implement retention job

src/portal/lib/src/service/interface.ts, src/portal/lib/src/shared/shared.const.ts, src/portal/src/app/app-config.service.ts, src/portal/src/app/base/harbor-shell/harbor-shell.component.html, src/portal/src/app/base/harbor-shell/harbor-shell.component.ts, src/portal/src/app/group/add-group-modal/add-group-modal.component.html, src/portal/src/app/group/add-group-modal/add-group-modal.component.ts, src/portal/src/app/group/group.component.html, src/portal/src/app/group/group.component.ts, src/portal/src/app/group/group.ts, src/portal/src/app/project/member/add-group/add-group.component.ts, src/portal/src/app/project/member/add-http-auth-group/add-http-auth-group.component.html, src/portal/src/app/project/member/add-http-auth-group/add-http-auth-group.component.scss, src/portal/src/app/project/member/add-http-auth-group/add-http-auth-group.component.spec.ts, src/portal/src/app/project/member/add-http-auth-group/add-http-auth-group.component.ts, src/portal/src/app/project/member/member.component.html, src/portal/src/app/project/member/member.component.ts, src/portal/src/app/project/project.module.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
add the pages  in project and system
=> Add user group when http auth mode

src/pkg/retention/policy/rule/latest/evaluator.go, src/pkg/retention/policy/rule/latestpull/evaluator.go, src/pkg/retention/res/candidate.go
* Retain the most recent active # images
* Retain the most recently pulled # images
=> add more rule evaluators

src/core/api/chart_repository.go, src/pkg/project/manager.go, src/pkg/repository/manager.go, src/pkg/retention/client.go, src/pkg/retention/launcher.go, src/pkg/retention/launcher_test.go, src/pkg/retention/models.go, src/pkg/retention/policy/models.go, src/pkg/retention/policy/rule/models.go, src/pkg/retention/res/candidate.go
The commit implements the launcher for tag retention
=> Implement the launcher

make/prepare
=> Add SELinux label to all volumes inside prepare script

tests/resources/Harbor-Pages/Project-Helmcharts.robot, tests/resources/Helm-Util.robot, tests/resources/TestCaseBody.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot, tests/robot-cases/Group1-Nightly/OIDC.robot
Add a nightly test case helm CLI, in this case, we verify help repo add and helm push.
=> Add a nightly test case "helm CLI"

src/portal/lib/src/config/registry-config.component.spec.ts, src/portal/lib/src/project-policy-config/project-policy-config.component.spec.ts
#8294 
Signed-off-by: Shijun Sun (c) <sshijun@vmware.com>
=> modify UT for cve-whitelist UI

src/pkg/retention/policy/rule/lastx/evaluator.go, src/pkg/retention/policy/rule/lastx/evaluator_test.go
This ports my WIP implementation to match the updated proposal.
Fixes #6661 
=> Retention: Implement Evaluator: Retain if created less than x days ago

src/replication/adapter/dockerhub/client.go
fix replication dockerhub skip tls
=> fix replication dockerhub skip tls

make/harbor.yml, make/photon/log/rsyslog_docker.conf, make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja, make/photon/prepare/templates/log/rsyslog_docker.conf.jinja, make/photon/prepare/utils/configs.py, make/photon/prepare/utils/docker_compose.py, make/photon/prepare/utils/log.py
Add config item in harbor.yml
Make fowarding rule configurable
=> Add supoort for external endpoint

src/core/api/harborapi_test.go, src/core/api/repository.go, src/core/api/repository_test.go, src/jobservice/job/known_jobs.go, src/pkg/clients/core/chart.go, src/pkg/clients/core/client.go, src/pkg/clients/core/image.go, src/pkg/retention/client.go, src/pkg/retention/client_test.go, src/pkg/retention/launcher.go, src/pkg/retention/launcher_test.go, src/pkg/retention/manager.go, src/pkg/retention/models.go, src/pkg/retention/policy/models.go, src/testing/clients/dumb_core_client.go
Implement the retention client
=> Implement the retention client

tests/travis/ut_install.sh
build prepare container before running ut case
=> Travis ci build prepare container in local

src/portal/lib/src/config/system/system-settings.component.html, src/portal/lib/src/config/system/system-settings.component.scss, src/portal/lib/src/config/system/system-settings.component.ts, src/portal/lib/src/project-policy-config/project-policy-config.component.html, src/portal/lib/src/project-policy-config/project-policy-config.component.scss, src/portal/lib/src/project-policy-config/project-policy-config.component.ts
=> The item in CVE whiltelist should be a click-able link

src/common/dao/group/usergroup.go, src/common/dao/group/usergroup_test.go, src/core/auth/authproxy/auth.go, src/core/auth/authproxy/auth_test.go, src/core/auth/ldap/ldap.go
Fix issue when adding a HTTP user group to a project member, returns HTTP 500 error.
=> Fix OnBoardGroup issue

src/portal/lib/src/config/system/system-settings.component.html, src/portal/lib/src/config/vulnerability/vulnerability-config.component.html, src/portal/lib/src/project-policy-config/project-policy-config.component.html
=> fix issue : time shown for scheduled scanning is incorrect

src/common/models/repo.go, src/common/utils/notary/helper.go, src/common/utils/notary/helper_test.go, src/common/utils/notary/model/model.go, src/core/api/harborapi_test.go, src/core/api/repository.go, src/core/api/repository_test.go, src/pkg/clients/core/client.go, src/pkg/clients/core/image.go, src/pkg/retention/client_test.go, src/testing/clients/dumb_core_client.go
Fix package import cycle issue
=> Fix package import cycle issue

src/portal/src/app/project/robot-account/add-robot/add-robot.component.html, src/portal/src/app/project/robot-account/add-robot/add-robot.component.scss, src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> UI Modification: When New Robot

src/pkg/retention/policy/rule/always/evaluator.go, src/pkg/retention/policy/rule/always/evaluator_test.go
Fixes #6658 
This should be the last of the rules to implement.
=> Retention: Implement Rule: Always Keep

src/chartserver/client.go, src/chartserver/handler_manipulation.go, src/common/api/base.go, src/core/api/base.go, src/core/api/project.go
Signed-off-by: Qian Deng <dengqian0826@gmail.com>
=> Fix: Internal server error with messy code when chartmuseum not work

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/common/job/client.go, src/core/api/base.go, src/core/main.go, src/core/router.go, src/core/service/notifications/scheduler/handler.go, src/jobservice/runtime/bootstrap.go, src/pkg/scheduler/dao/schedule.go, src/pkg/scheduler/dao/schedule_test.go, src/pkg/scheduler/hook/handler.go, src/pkg/scheduler/hook/handler_test.go, src/pkg/scheduler/manager.go, src/pkg/scheduler/manager_test.go, src/pkg/scheduler/model/schedule.go, src/pkg/scheduler/periodic_job.go, src/pkg/scheduler/scheduler.go, src/pkg/scheduler/scheduler_test.go, src/testing/job/mock_client.go, src/testing/scheduler.go
Implement a common scheduler that can be used globally
=> Implement a common scheduler

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/pkg/retention/controllers/retention.go, src/pkg/retention/dao/models/retention.go, src/pkg/retention/dao/retention.go, src/pkg/retention/dao/retention_test.go, src/pkg/retention/launcher_test.go, src/pkg/retention/manager.go, src/pkg/retention/q/query.go
Implement the task management in retention manager
=> Implement the task management in retention manager

src/core/router.go, src/core/service/notifications/jobs/handler.go
Implement the webhook handler for retention task
=> Implement the webhook handler for retention task

src/portal/lib/src/log/recent-log.component.spec.ts
=> Fix UT issue about it should support pagination

src/replication/adapter/helmhub/adapter.go, src/replication/adapter/helmhub/adapter_test.go, src/replication/adapter/helmhub/chart.go, src/replication/adapter/helmhub/chart_registry.go, src/replication/adapter/helmhub/chart_registry_test.go, src/replication/adapter/helmhub/client.go, src/replication/adapter/helmhub/consts.go, src/replication/model/registry.go
it will invoke getChartDetail 3-5 times to make it compatible with the chart interface.
so this will degrade some performance.
@ywk253100 @steven-zou @cd1989 @kofj
=> Support helm chart replication from helmhub

src/core/api/project.go
=> fix(api,project): fix repo, chart count missing in project summary

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/core/service/notifications/jobs/handler.go, src/pkg/retention/controller.go, src/pkg/retention/dao/models/retention.go, src/pkg/retention/job.go, src/pkg/retention/launcher.go, src/pkg/retention/launcher_test.go, src/pkg/retention/manager.go, src/pkg/retention/models.go
Support to stop one execution of retention
=> Support to stop one execution of retention

src/core/main.go
=> Update log level for init proxy

src/portal/lib/src/shared/shared.const.ts, src/portal/src/app/config/auth/config-auth.component.html, src/portal/src/app/config/auth/config-auth.component.ts, src/portal/src/app/config/config.service.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Add test button in configration width oidc mode

tests/resources/Harbor-Pages/Project-Members_Elements.robot
=> modify xpath of project member due to summary tab was added in project.

src/pkg/retention/dao/retention.go, src/pkg/retention/dao/retention_test.go, src/pkg/retention/launcher_test.go, src/pkg/retention/manager.go, src/pkg/retention/manager_test.go
Implement getting the retention task log
=> Implement getting the retention task log

src/core/api/base.go, src/core/api/harborapi_test.go, src/core/api/retention.go, src/core/api/retention_test.go, src/pkg/retention/controller.go, src/pkg/retention/controller_test.go, src/pkg/retention/dao/retention_test.go, src/pkg/retention/manager.go, src/pkg/retention/manager_test.go, src/pkg/retention/policy/models.go
Change-Id: I6d9412126e03b697d93ac512b75b5007223aa926
=> add ut for tag retention controller

src/pkg/retention/job.go, src/pkg/retention/job_test.go, src/pkg/retention/launcher.go, src/pkg/retention/policy/lwp/models.go, src/pkg/retention/res/candidate.go, src/pkg/retention/res/selectors/doublestar/selector.go, src/pkg/retention/res/selectors/index.go
Fix bugs found in running the retention workflow
=> Fix bugs found in running the retention workflow

src/pkg/retention/launcher.go, src/pkg/retention/launcher_test.go
Only listing chart repositories when chart server is enabled
=> Only listing chart repositories when chart server is enabled

src/replication/adapter/awsecr/adapter.go, src/replication/adapter/awsecr/adapter_test.go
Signed-off-by: 疯魔慕薇 <kfanjian@gmail.com>
Benchmark:
=> Improve awsecr parseRegion method.

src/common/dao/artifact.go, src/common/dao/artifact_test.go, src/common/utils/utils.go, src/common/utils/utils_test.go, src/core/middlewares/contenttrust/handler.go, src/core/middlewares/contenttrust/handler_test.go, src/core/service/notifications/registry/handler.go
=> Update pull time in artifact table for docker image pull

src/core/middlewares/countquota/putmanifest.go, src/core/middlewares/sizequota/handler.go
=> Fix logic error in quota middlewware on handling failure response

src/pkg/retention/res/selectors/label/selector.go
=> enhance the label selector

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/core/api/retention.go, src/pkg/retention/controller.go, src/pkg/retention/dao/models/retention.go, src/pkg/retention/dao/retention.go, src/pkg/retention/manager.go, src/pkg/retention/manager_test.go
Change-Id: I0be88c728194b815be3e8fcd24b4c2457bb64ade
=> get execution status on the fly

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/pkg/retention/dao/models/retention.go, src/pkg/retention/launcher.go, src/pkg/retention/manager.go, src/pkg/retention/models.go
Add property "repository" to retention task
=> Add property "repository" to retention task

src/pkg/retention/job.go, src/pkg/retention/policy/alg/or/processor.go, src/pkg/retention/policy/alg/or/processor_test.go, src/pkg/retention/policy/builder_test.go
=> fix the OR processor failure issue

src/core/main.go, src/jobservice/runtime/bootstrap.go, src/pkg/retention/launcher.go
1. Register the scheduler job
2. Fix retention bugs
=> Register the scheduler job and fix bugs

src/pkg/retention/dao/models/retention.go, src/pkg/retention/dao/retention.go, src/pkg/retention/dao/retention_test.go
Change-Id: I2c295090de34d133671c01422a6812fa426e9be7
=> fix tag retention api bug

src/common/models/token.go, src/common/utils/registry/auth/tokenauthorizer.go, src/common/utils/registry/auth/util.go, src/replication/adapter/azurecr/adapter.go, src/replication/adapter/azurecr/adapter_test.go, src/replication/adapter/dockerhub/adapter.go, src/replication/adapter/dockerhub/adapter_test.go, src/replication/adapter/googlegcr/adapter.go
Fix #8319, got error when replicating image with Azure container registry
=> Fix #8319, got error when replicating image with Azure container registry

src/portal/lib/src/project-policy-config/project-policy-config.component.spec.ts
#8306 
Signed-off-by: Shijun Sun (c) <sshijun@vmware.com>
=> modify spec.ts file for project-policy-config.component.ts

src/jobservice/job/impl/replication/replication.go, src/replication/replication.go
Register the replication adapter for Helm Hub
=> Register the replication adapter for Helm Hub

src/pkg/clients/core/chart.go, src/pkg/clients/core/client.go, src/pkg/clients/core/image.go, src/pkg/retention/controller_test.go, src/pkg/retention/dep/client.go, src/pkg/retention/launcher.go, src/pkg/retention/launcher_test.go, src/testing/clients/dumb_core_client.go
=> Refactor retention launcher

src/pkg/retention/controller.go, src/pkg/retention/dao/retention.go, src/pkg/retention/launcher_test.go, src/pkg/retention/manager.go, src/pkg/retention/manager_test.go
Change-Id: Ia1a618597aa9a0f721b9516f341ef5f6556e5246
=> fix tag_retention bug

src/portal/lib/src/cron-schedule/index.ts, src/portal/lib/src/index.ts, src/portal/src/app/project/tag-retention/retention.ts, src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.scss, src/portal/src/app/project/tag-retention/tag-retention.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
#8462
Signed-off-by: Shijun Sun (c) <sshijun@vmware.com>
=> Optimization for tag-retention UI

src/portal/lib/src/filter/filter.component.html, src/portal/lib/src/label-piece/label-piece.component.scss, src/portal/src/app/project/helm-chart/label-filter/label-filter.component.html, src/portal/src/app/project/helm-chart/label-filter/label-filter.component.scss, src/portal/src/app/project/helm-chart/label-marker/label-marker.component.html, src/portal/src/styles.css
1.filter input auto focus   #8278
2.filter is covered by datagrid
3.modify elements of click action in label
（2）
Before modification
after modification
(3)
Before modification
after modification
=> Fix many issue  for harbor for ui

src/portal/src/app/project/tag-retention/add-rule/add-rule.component.ts
change "num" type from string to int
=> fix bug for tag-retention

src/pkg/retention/launcher.go
Fix retention bug that passing the wrong rules to retention job
=> Fix retention bug

make/migrations/postgresql/0005_1.8.2_schema.up.sql
=> Delete the none scan all schedule in migration

src/portal/src/app/project/robot-account/add-robot/add-robot.component.html, src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Add download button that it can download the message of robot to local file when click it

make/migrations/postgresql/0005_1.8.2_schema.up.sql
=> [Cherry-pick]Delete the none scan all schedule in migration

src/portal/lib/ng-package.json, src/portal/lib/ng-package.prod.json, src/portal/src/app/project/summary/summary.component.html
=> Fix the part of warnings when ng build

src/jobservice/migration/manager_test.go, src/jobservice/migration/migrator_v180.go, src/jobservice/runtime/bootstrap.go
=> fix bug #8499: redis connection pool is run out

src/core/api/retention.go, src/pkg/retention/controller.go, src/pkg/retention/dao/retention.go, src/pkg/retention/launcher_test.go, src/pkg/retention/manager.go
Change-Id: I58a250dbb643f6949c1e34aa3a84a01dc3e0b285
=> add total page num for tag retention

src/portal/src/app/user/user.component.html, src/portal/src/app/user/user.component.ts, src/portal/src/app/user/user.service.ts
Change userList paging from "by frontend" to "by backend"
#8173
=> Change userList paging from "by frontend" to "by backend"

src/portal/lib/src/config/registry-config.component.ts, src/portal/src/app/project/tag-retention/add-rule/add-rule.component.html, src/portal/src/app/project/tag-retention/retention.ts, src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.ts, src/portal/src/app/project/tag-retention/tag-retention.service.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1. add disable/enable to retention rule.
2. add server paging
3. modify UI of add-rule component
#8521 
=> Modify tag-retention UI

docs/manage_role_by_ldap_group.md, src/common/security/local/context.go, src/common/security/local/context_test.go, src/common/utils/test/test.go
Fix issue #8432
If a user in the project member list and also this user's group is also in the project member. merge these privileges.
=> Merge user roles and group roles

docs/manage_role_by_ldap_group.md, src/common/security/local/context.go, src/common/security/local/context_test.go, src/common/utils/test/test.go
Fix issue #8432
If a user in the project member list and also this user's group is also in the project member. merge these privileges.
=> Merge user roles and group roles -- 1.8 cherry pick

src/core/api/retention.go, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1. remove rule always
2. update i18n
Change-Id: I0e2394f0a6b283d0efef7a44ed2d4afb9745eabd
=> remove rule always

src/pkg/retention/controller_test.go, src/pkg/retention/launcher.go, src/pkg/retention/launcher_test.go, src/pkg/retention/policy/rule/models.go
Change-Id: Ic82b41c2ed14c47c51b9be8a46376bdfc7567376
=> add disable rule feature for tag retention

src/core/api/retention.go, src/pkg/retention/policy/rule/index/index.go, src/pkg/retention/policy/rule/index/index_test.go, src/pkg/retention/policy/rule/nothing/evaluator.go, src/pkg/retention/policy/rule/nothing/evaluator_test.go
Change-Id: I4e7a4ecb40fe39b80e41a6d9bf8b5fb3968a41af
=> retain nothing rule

src/core/api/retention.go, src/pkg/retention/policy/rule/daysps/evaluator.go, src/pkg/retention/policy/rule/daysps/evaluator_test.go, src/pkg/retention/policy/rule/index/index.go, src/pkg/retention/policy/rule/index/index_test.go
=> Retention: New Evaluator: Retain Images pushed within N days

src/pkg/retention/dep/client.go, src/pkg/retention/dep/client_test.go, src/pkg/retention/launcher.go, src/pkg/retention/launcher_test.go
As we don't provide the capability for chart rerention currently, this commit comments related code
=> Comment the related code for chart retention

src/core/api/retention.go, src/pkg/retention/policy/rule/dayspl/evaluator.go, src/pkg/retention/policy/rule/dayspl/evaluator_test.go, src/pkg/retention/policy/rule/index/index.go, src/pkg/retention/policy/rule/index/index_test.go
=> Retention: New Evaluator: Pulled within the last N Days

src/common/config/store/driver/db.go
Change to debug level to avoid too much noise in log file
=> Change trace level of missing configure metadata

src/common/dao/artifact.go, src/common/dao/artifact_test.go, src/common/models/repo.go, src/core/api/repository.go, src/pkg/retention/dep/client.go
Populate pull/push time properties to the returning data when listing tags
=> Populate pull/push time properties to the returning data when listing tags

docs/migration_guide.md
fix some log typos in migration_guide.md
=> fix some log typos in migration_guide.md

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
=> Removal of leading white space

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/core/service/notifications/jobs/handler.go, src/pkg/retention/dao/models/retention.go, src/pkg/retention/job.go, src/pkg/retention/manager.go, src/pkg/retention/models.go, src/portal/package-lock.json
Change-Id: Ic3696a924118b8ea0e3897ca4aafeba30fcc82c7
=> add task retain num

src/common/utils/passports.go, src/replication/adapter/adapter.go, src/replication/adapter/aliacr/adapter.go, src/replication/adapter/dockerhub/adapter.go, src/replication/adapter/harbor/image_registry.go, src/replication/adapter/native/adapter.go
Improve FetchImages performance for registry adapters
Issue: https://github.com/goharbor/harbor/issues/7982
=> Replication performance

src/portal/src/app/project/tag-retention/add-rule/add-rule.component.html, src/portal/src/app/project/tag-retention/add-rule/add-rule.component.ts, src/portal/src/app/project/tag-retention/tag-retention.service.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> fix issue and add new templats for tag-retention

src/core/api/retention.go, src/core/api/retention_test.go, src/portal/package-lock.json
Change-Id: I8af648f22aa3fe76024240d322a7fdae560e3fbd
=> check rule conflict

src/portal/lib/src/tag/tag.component.html, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Add pull-time and push time in repositories image

src/portal/lib/src/config/config.ts, src/portal/lib/src/config/system/system-settings.component.html, src/portal/lib/src/config/system/system-settings.component.ts, src/portal/lib/src/confirmation-dialog/confirmation-dialog.component.html, src/portal/lib/src/service/permission-static.ts, src/portal/lib/src/shared/shared.const.ts, src/portal/src/app/harbor-routing.module.ts, src/portal/src/app/project/project-detail/project-detail.component.html, src/portal/src/app/project/project-detail/project-detail.component.ts, src/portal/src/app/project/project.module.ts, src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html, src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.scss, src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.ts, src/portal/src/app/project/webhook/add-webhook/add-webhook.component.html, src/portal/src/app/project/webhook/add-webhook/add-webhook.component.ts, src/portal/src/app/project/webhook/webhook.component.html, src/portal/src/app/project/webhook/webhook.component.scss, src/portal/src/app/project/webhook/webhook.component.ts, src/portal/src/app/project/webhook/webhook.service.ts, src/portal/src/app/project/webhook/webhook.ts, src/portal/src/app/shared/confirmation-dialog/confirmation-dialog.component.html, src/portal/src/app/shared/shared.const.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Add webhook UI

make/photon/portal/Dockerfile, src/portal/src/app/app.module.ts, src/portal/src/app/harbor-routing.module.ts, src/portal/src/app/license/license.component.html, src/portal/src/app/license/license.component.scss, src/portal/src/app/license/license.component.spec.ts, src/portal/src/app/license/license.component.ts, src/portal/src/app/license/license.module.ts, src/portal/src/app/shared/about-dialog/about-dialog.component.html
=> Fix issue width Link to license in the about dialog should not be hardcoded to master

src/replication/adapter/harbor/chart_registry.go, src/replication/adapter/harbor/chart_registry_test.go, src/replication/adapter/helmhub/chart_registry.go
Fix bug in Helm Hub and Harbor adapter for replicating chart
=> Fix bug in Helm Hub and Harbor adapter for replicating chart

src/portal/src/app/config/auth/config-auth.component.html, src/portal/src/app/config/auth/config-auth.component.scss, src/portal/src/app/config/config.component.scss
=> The part of Authentication

src/common/dao/base.go, src/common/dao/pro_meta.go, src/common/dao/project.go, src/common/dao/quota.go, src/common/dao/quota_usage.go, src/common/dao/repository.go, src/core/service/notifications/jobs/handler.go, src/replication/dao/execution.go, src/replication/operation/controller.go, src/replication/operation/controller_test.go, src/replication/operation/execution/execution.go, src/replication/operation/hook/task.go
Fix replication tasks stuck in "InProgress" issue
=> Fix replication tasks stuck in "InProgress" issue

src/common/dao/blob.go, src/common/dao/project_blob.go, tests/travis/ut_run.sh
=> temporary disable coverall service in travis ci

tests/robot-cases/Group0-BAT/API_DB.robot
=> add replication testcase in api_db.robot file

src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.html, src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.scss, src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.ts, src/portal/lib/src/config/project-quotas/project-quotas.component.html, src/portal/lib/src/config/project-quotas/project-quotas.component.ts, src/portal/lib/src/shared/shared.const.ts, src/portal/src/app/project/summary/summary.component.html, src/portal/src/app/project/summary/summary.component.ts
=> Add the warning color in quota when used/hard >0.7

src/portal/lib/src/config/gc/gc-history/gc-history.component.ts, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/portal/lib/src/replication/replication-tasks/replication-tasks.component.ts, src/portal/lib/src/replication/replication.component.ts, src/portal/lib/src/service/replication.service.ts, src/portal/lib/src/shared/shared.const.ts
=> Add paging from backend in replication task ui

src/common/dao/project_blob.go, src/common/dao/project_blob_test.go, src/common/quota/manager.go, src/common/quota/manager_test.go, src/core/api/harborapi_test.go, src/core/api/internal.go, src/core/api/internal_test.go, src/core/router.go
=> Enable usage sync when switch quota setting

make/photon/prepare/g.py, make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja, make/photon/prepare/utils/nginx.py, make/prepare
*  mount root of host
* copy file to data dir and change ownership and permission
=> Fix permission of nginx cert

src/core/middlewares/sizequota/handler.go
=> Add log in quota size handler

tests/apitests/python/library/system.py, tests/apitests/python/library/user.py, tests/apitests/python/test_assign_sys_admin.py, tests/apitests/python/test_sys_cve_whitelists.py
=> API test for system level CVE whitelist

src/core/service/notifications/registry/handler.go, src/core/utils/utils.go
Signed-off-by: mmpei <peimingming@corp.netease.com>
[issue8162](https://github.com/goharbor/harbor/issues/8162)
=> Optimize fetch manifest loop when handling notification

src/common/dao/project_blob.go, src/core/api/internal.go, src/core/api/internal_test.go
=> Fix quota switch fail to get project size

src/common/utils/registry/repository.go
Set content length when pushing blobs
=> Set content length when pushing blobs

src/portal/lib/src/log/recent-log.component.spec.ts, src/portal/lib/src/log/recent-log.component.ts, src/portal/lib/src/service/interface.ts, src/portal/lib/src/tag/tag.component.html, src/portal/lib/src/tag/tag.component.ts, src/portal/lib/src/vulnerability-scanning/result-bar-chart.component.ts
1、fix scan is repeatedly triggered 
2. fix refresh Logs failed
3. fix the init push time  not  available
fix #8630 #8619 #8657
=> Fix scan is repeatedly triggered and refresh Logs failed

src/core/api/retention.go
Change-Id: Ide98d58f64596e8110fbb9eb0d73df6ccbd99c80
=> remove tag retention rule always

src/core/api/retention.go
Because user may just want protect special image
Change-Id: I34bac3b73e693b89e0b9debb28617352656ed1d9
=> add always rule again

docs/swagger.yaml, make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/common/dao/artifact.go, src/core/api/harborapi_test.go, src/core/api/health.go, src/core/api/health_test.go, src/core/api/internal.go, src/core/api/internal_test.go, src/core/api/quota/chart/chart.go, src/core/api/quota/migrator.go, src/core/api/quota/registry/registry.go, src/core/api/utils.go, src/core/main.go, src/core/router.go
=> Add quota sync api to sync quota data with backend storage

src/common/utils/ldap/ldap.go
More details here: https://ldapwiki.com/wiki/1.2.840.113556.1.4.1941
Implementation of https://github.com/goharbor/harbor/issues/8122
It works but if someone want to use it as a starting plate, go for it!
=> Search for LDAP_MATCHING_RULE_IN_CHAIN groups

src/common/dao/cve_whitelist.go, src/common/dao/cve_whitelist_test.go, src/core/promgr/promgr.go, src/pkg/scan/whitelist/manager.go, src/pkg/scan/whitelist/manager_test.go
Fixes #8702
Also enforce the code to mitigate the potential risk.
=> Avoid overwriting system CVE whitelist by mistake

src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.scss, src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.ts, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts, src/portal/lib/src/shared/shared.const.ts, src/portal/lib/src/utils.ts, src/portal/src/app/project/create-project/create-project.component.html, src/portal/src/app/project/create-project/create-project.component.ts, src/portal/src/app/project/summary/summary.component.scss, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1.modify the quota message.
2.fix replication ng bug when no filter.
3.fix summary ui style.
4.fix quota-edit page validation when input a large number
=> Fix bug for harbor 1.9.0

src/pkg/retention/controller.go
Change-Id: I04cad9d4c520db751bfa413bb139317563716501
=> fix tag retention schedule none error

src/portal/lib/src/config/system/system-settings.component.scss, src/portal/lib/src/project-policy-config/project-policy-config.component.html, src/portal/lib/src/project-policy-config/project-policy-config.component.scss, src/portal/lib/src/project-policy-config/project-policy-config.component.ts
=> fix cve-whitelist bugs

src/portal/src/app/project/webhook/webhook.component.html, src/portal/src/app/project/webhook/webhook.component.scss, src/portal/src/app/project/webhook/webhook.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json
=> fix UI bugs for Webhooks

src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.html, src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.scss, src/portal/lib/src/config/system/system-settings.component.html, src/portal/lib/src/config/system/system-settings.component.scss, src/portal/lib/src/create-edit-label/create-edit-label.component.html, src/portal/lib/src/create-edit-label/create-edit-label.component.scss, src/portal/src/app/config/auth/config-auth.component.html, src/portal/src/app/config/auth/config-auth.component.scss, src/portal/src/app/config/email/config-email.component.html
=> Add the part of configration

src/common/quota/errors.go, src/common/quota/manager.go, src/common/quota/manager_test.go, src/common/quota/util.go, src/common/quota/util_test.go, src/pkg/types/format.go, src/pkg/types/format_test.go, src/pkg/types/resources.go, src/pkg/types/resources_test.go
More info message when quota usage overflow the hard limit, and this will fix #8693
=> refactor(quota): new error types for quota checking

src/portal/src/app/shared/route/member-guard-activate.service.ts
=> Fix redirect login page when enter harbor through global search

src/core/middlewares/chart/builder.go, src/core/middlewares/chart/handler_test.go, src/core/middlewares/interceptor/quota/quota.go, src/testing/suite.go
=> fix(quota): fix computeResources method of qutoa interceptor

src/portal/lib/src/config/system/system-settings.component.html, src/portal/lib/src/project-policy-config/project-policy-config.component.html, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json
1.add ids to key elements of CVE-whitelist UI for easy test  …
2.change decrible in UI #8740
=> add ids to key elements of CVE-whitelist UI for easy test

src/core/api/project_test.go
so many typos hurts word statistics, so let's fix it.
=> project_test.go: many typos "respose" fixup

src/core/api/base.go, src/core/service/notifications/scheduler/handler.go, src/pkg/scheduler/scheduler.go
The scheduler hook handler doesn't parse the job status struct when handling the hook. This commit fixes it.
=> Fix bug found in scheduler

src/core/api/repository.go
=> Fix bug of listing tags filtered by label

src/core/api/retention.go
Change-Id: I379f3c29cee742d346fb57ade397be64fd76f59d
=> fix rule conflict, id error

src/jobservice/job/impl/sample/job.go, src/jobservice/job/models.go, src/jobservice/job/tracker.go, src/jobservice/runner/redis.go, src/jobservice/worker/cworker/c_worker.go
The retry process is broken by the status comparison check.
=> fix #8745: job retry issue

src/portal/lib/src/image-name-input/image-name-input.component.ts, src/portal/lib/src/vulnerability-scanning/result-grid.component.ts, src/portal/src/app/user/user.component.html
=> Fix error in Harbor

src/jobservice/job/impl/sample/job.go, src/jobservice/job/models.go, src/jobservice/job/tracker.go, src/jobservice/runner/redis.go, src/jobservice/worker/cworker/c_worker.go
=> [Cherry-pick] fix #8745: job retry issue

src/common/dao/user.go, src/common/models/user.go, src/common/quota/driver/project/driver.go, src/common/quota/driver/project/driver_test.go
=> fix(quota-driver): owner name of project quota reference object

src/core/main.go
Signed-off-by: ethan <guangming.wang@daocloud.io>
=> core/main.go: logging message correction

src/common/dao/project_blob.go, src/common/dao/project_blob_test.go, src/common/quota/manager.go, src/common/quota/manager_test.go, src/jobservice/job/impl/gc/job.go
=> fix quota size usage in gc job

src/portal/src/app/project/tag-retention/add-rule/add-rule.component.html, src/portal/src/app/project/tag-retention/retention.ts, src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.scss, src/portal/src/app/project/webhook/webhook.component.scss
=> ui adjustment for tag-retention and webhook

src/jobservice/period/enqueuer.go, src/jobservice/runner/redis.go, src/jobservice/worker/cworker/c_worker.go
fix #8525: periodic job retry issue: job stats are not found
=> fix #8525: periodic job retry issue: job stats are not found

src/core/api/retention.go, src/pkg/retention/controller_test.go, src/pkg/retention/dao/retention.go, src/pkg/retention/job_test.go, src/pkg/retention/manager_test.go, src/pkg/retention/policy/models.go, src/pkg/retention/policy/rule/index/index.go, src/pkg/retention/policy/rule/index/index_test.go, src/pkg/retention/policy/rule/models.go, src/pkg/retention/res/selectors/index/index.go
1, remove rule none
2, change rule orders
Change-Id: Idc18a27cb0267f5f5c80a04b381e4a5dc6998508
=> remove rule none and change rule order

src/portal/src/app/project/tag-retention/add-rule/add-rule.component.html
=> modify metadate of tag-retention

make/photon/core/Dockerfile, make/photon/jobservice/Dockerfile
=> fix(build): install tzdata pkg for core and jobservice images

src/jobservice/period/enqueuer.go, src/jobservice/runner/redis.go, src/jobservice/worker/cworker/c_worker.go
Cherry-pick fix commit to 1.8.0 branch to fix #8525
=> [CHERRY-PICK] fix #8525: periodic job retry issue: job stats is not found

docs/swagger.yaml
=> Remove 401 error for HEAD /projects

src/pkg/types/resources_test.go
=> test: fix TestIsNegative

src/core/api/quota/registry/registry.go
=> fix deleted project error when to migrate quota

src/common/rbac/namespace.go, src/common/rbac/namespace_test.go, src/common/rbac/parser.go, src/common/rbac/parser_test.go, src/common/rbac/project/visitor_test.go, src/common/security/admiral/context.go, src/common/security/local/context.go, src/common/security/local/context_test.go, src/common/security/robot/context.go, src/common/security/robot/context_test.go, src/common/security/robot/robot_test.go, src/core/api/base.go, src/core/api/chart_label.go, src/core/api/chart_repository.go, src/core/api/label.go, src/core/api/metadata.go, src/core/api/notification_job.go, src/core/api/notification_policy.go, src/core/api/project.go, src/core/api/projectmember.go, src/core/api/repository.go, src/core/api/repository_label.go, src/core/api/retention.go, src/core/api/robot.go, src/core/api/scan_job.go, src/core/api/user_test.go, src/core/service/token/creator.go
=> fix(rbac): NewProjectNamespace in rbac only accept projectID

src/common/dao/base.go, src/common/dao/pro_meta.go, src/common/dao/project.go, src/common/dao/repository.go, src/core/service/notifications/jobs/handler.go, src/replication/dao/execution.go, src/replication/operation/controller.go, src/replication/operation/controller_test.go, src/replication/operation/execution/execution.go, src/replication/operation/hook/task.go
Fix replication tasks stuck in "InProgress" issue
=> [Cherry-pick]Fix replication tasks stuck in "InProgress" issue

src/portal/src/app/project/robot-account/robot-account.service.ts
PR #8777 make the resource of project in rbac only accept project id, so change the resource with project id for robot account in portal
=> fix(robot): make resource with projectId for robot in portal

tools/migration/cfg/migrator_1_9_0/__init__.py, tools/migration/cfg/migrator_1_9_0/harbor.yml.jinja, tools/migration/cfg/run.py
Add config template
Add upgrade script
Update latest version
=> Feat: Add migration script for 1.9

src/jobservice/job/tracker.go, src/jobservice/worker/cworker/c_worker.go
reduce the expire time of job stats in redis DB
Fix issue #8537
=> reduce the expire time of job stats in redis DB

src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html, src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
Signed-off-by: 方彬 <fang_bingo@163.com>
=> fix UI bug for Webhooks

src/jobservice/job/tracker.go, src/jobservice/worker/cworker/c_worker.go
Fix #8537  and cherry-pick to 1.8.0
=> [CHERRY-PICK] reduce the expire time of job stats in redis DB

src/common/dao/blob.go, src/common/dao/blob_test.go, src/core/middlewares/countquota/builder.go, src/core/middlewares/sizequota/builder.go, src/core/middlewares/sizequota/handler_test.go, src/core/middlewares/sizequota/util.go, src/core/middlewares/util/util.go, src/core/middlewares/util/util_test.go
=> fix quota count size for same manifest in different repo

src/core/api/retention_test.go, src/pkg/retention/dao/retention_test.go, src/pkg/retention/policy/models.go, src/pkg/retention/policy/models_test.go, src/pkg/retention/policy/rule/models.go
Change-Id: If882b65a4a05aeb5590edb33fb3bb0b3d1f29e30
=> add tag retention model test

src/pkg/retention/policy/rule/models.go
Change-Id: Ifb237bbed4c6d7272ace62da7603e027c1481aef
=> fix tag retention model verify

src/pkg/retention/policy/rule/latestps/evaluator.go
=> fix rule logic bug described in #8817

src/common/dao/project_blob.go, src/common/dao/project_blob_test.go, src/jobservice/job/impl/gc/job.go
=> fix #8815 :add remove untagged blob record in table project_blob

src/portal/lib/src/channel/channel.service.ts, src/portal/lib/src/tag/tag-detail.component.ts, src/portal/lib/src/vulnerability-scanning/result-bar-chart.component.ts, src/portal/lib/src/vulnerability-scanning/result-grid.component.ts
we do not change the existing logic.
fix #8731
=> Show the result about vulnerabilities number and vunerability list when click scan button

src/portal/src/app/project/tag-retention/add-rule/add-rule.component.html, src/portal/src/app/project/tag-retention/add-rule/add-rule.component.scss, src/portal/src/app/project/tag-retention/add-rule/add-rule.component.ts, src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
#8816 
#8811 
#8805 
#8804 
#8803
Signed-off-by: Shijun Sun (c) <sshijun@vmware.com>
=> Improvement for rule validator of tag-retention

src/portal/lib/src/project-policy-config/project-policy-config.component.html, src/portal/lib/src/project-policy-config/project-policy-config.component.scss
=> Modify cve list css

src/portal/lib/src/config/project-quotas/project-quotas.component.scss
=> Modify style

docs/swagger.yaml, src/common/quota/errors.go, src/core/api/repository.go, src/core/middlewares/chart/handler.go, src/core/middlewares/countquota/handler.go, src/core/middlewares/sizequota/handler.go
1, fix #8802, update the error formet
2, fix #8807, raise the real retag error to UI
3, fix #8832, raise the real chart error to chart client & ut
=> Revise quota errors to make it more readable

make/migrations/postgresql/0010_1.9.0_schema.up.sql
=> fix #8839: update bolb size type to bigint

src/core/api/registry_test.go, src/core/main.go, src/replication/registry/healthcheck.go, src/replication/replication.go, src/replication/replication_test.go
Issue: https://github.com/goharbor/harbor/issues/8599
=> Fix core hung when stop problem

src/common/utils/registry/repository.go
Set content length when pushing blobs
=> [Cherry-pick]Set content length when pushing blobs

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/core/api/replication_execution_test.go, src/core/api/replication_policy.go, src/core/service/notifications/jobs/handler.go, src/replication/dao/execution.go, src/replication/dao/execution_test.go, src/replication/dao/models/execution.go, src/replication/event/handler_test.go, src/replication/operation/controller.go, src/replication/operation/controller_test.go, src/replication/operation/execution/execution.go, src/replication/operation/execution/execution_test.go, src/replication/operation/flow/stage.go, src/replication/operation/flow/stage_test.go, src/replication/operation/hook/task.go, src/replication/operation/hook/task_test.go
Add status revision to handle retrying in replication task
=> Add status revision to handle retrying in replication task

docs/migration_guide.md
in version 1.9, the input file should be yaml format
=> Update migration doc

src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html, src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
=> Add placeholder in registry page when select helm-hub

src/common/utils/utils.go, src/core/api/retention_test.go, src/pkg/retention/controller_test.go, src/pkg/retention/dao/retention_test.go, src/pkg/retention/manager_test.go, src/pkg/retention/policy/models.go, src/pkg/retention/policy/models_test.go, src/pkg/retention/policy/rule/dayspl/evaluator.go, src/pkg/retention/policy/rule/dayspl/evaluator_test.go, src/pkg/retention/policy/rule/daysps/evaluator.go, src/pkg/retention/policy/rule/daysps/evaluator_test.go, src/pkg/retention/policy/rule/evaluator.go, src/pkg/retention/policy/rule/index/index.go, src/pkg/retention/policy/rule/lastx/evaluator.go, src/pkg/retention/policy/rule/latestk/evaluator.go, src/pkg/retention/policy/rule/latestpl/evaluator.go, src/pkg/retention/policy/rule/latestpl/evaluator_test.go, src/pkg/retention/policy/rule/latestps/evaluator.go, src/pkg/retention/policy/rule/latestps/evaluator_test.go
Change-Id: I82215a0cf1ec32a253c8db9bfafe7e25b26c9ad9
=> add valid for rule

src/common/dao/pgsql.go
=> fix(database): generate db url by url.URL for schema upgrade

src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts, src/portal/src/app/project/tag-retention/add-rule/add-rule.component.ts
=> remove whitespaces when add tag-retention rule

src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html
=> Add  id in endpoint url

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/common/dao/pro_meta.go
=> Hard delete project metadata

src/portal/src/app/project/helm-chart/list-charts-detail/helm-chart.component.html, src/portal/src/app/project/member/member.component.html, tests/resources/Harbor-Pages/Configuration.robot, tests/resources/Harbor-Pages/Project-Helmcharts_Elements.robot, tests/resources/Harbor-Pages/Project.robot, tests/resources/Harbor-Pages/Project_Elements.robot, tests/resources/Harbor-Pages/Replication.robot, tests/resources/Harbor-Pages/ToolKit.robot
=> fix part of robot

src/pkg/retention/job.go
Change-Id: I5acc13714dbb1dc1d8bf3f1c6c620a7d54f86910
=> show empty if time is 0

src/common/dao/project_blob.go, src/common/dao/project_blob_test.go, src/core/api/quota/chart/chart.go, src/core/api/quota/migrator.go, src/core/api/quota/registry/registry.go
1, fix #8858, add retry to ping backend service
2, fix #8859, split the blobs data when larger then 65535
=> fix quota sync issues

make/harbor.yml, make/photon/prepare/utils/configs.py, tools/migration/cfg/migrator_1_9_0/harbor.yml.jinja
=> fix(build): max idle and open conn settings for external db

src/pkg/retention/dao/retention_test.go, src/pkg/retention/job.go, src/pkg/retention/launcher.go
enhance tag retention log
Change-Id: Id5946c2dd53868fdd5f5abbcca45e453bc9ba4fd
=> enhance tag retention log

src/pkg/retention/controller.go, src/pkg/retention/manager.go
Change-Id: I7f93dd4c1b93b8d7e6b2c2a14fd4ccf128945def
=> tag retention fix duration and show trigger

src/common/models/robot.go, src/core/api/robot.go
=> [Cherry pick]Return account id when to issue a robot

src/portal/lib/src/config/project-quotas/project-quotas.component.html, src/portal/lib/src/config/project-quotas/project-quotas.component.scss, src/portal/src/app/project/tag-retention/add-rule/add-rule.component.ts, src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.ts, src/portal/src/app/project/tag-retention/tag-retention.service.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> fix UI bug for tag-retention and project-quota

make/photon/prepare/utils/docker_compose.py
non-root user can see the content
=> Fix docker-compose file permmission

src/core/middlewares/chart/builder.go, src/core/middlewares/chart/handler_test.go
=> fix(chart,quota): fix path regexp of chart creation and deletion

make/photon/prepare/g.py, make/photon/prepare/utils/cert.py, make/photon/prepare/utils/chart.py, make/photon/prepare/utils/core.py, make/photon/prepare/utils/db.py, make/photon/prepare/utils/misc.py, make/photon/prepare/utils/registry.py
1. recursivele change ownership for all prepare dir
2. database file permission fix
=> Fix: prepare permission issue

src/common/quota/manager.go, src/common/quota/manager_test.go
=> fix int out of range when to set usage in GC job

src/portal/src/app/project/member/add-member/add-member.component.ts
=> fix add-member nightly case failure

src/common/rbac/namespace.go, src/common/rbac/namespace_test.go, src/common/rbac/parser.go, src/common/rbac/parser_test.go, src/common/rbac/project/visitor_test.go, src/common/security/admiral/context.go, src/common/security/local/context.go, src/common/security/local/context_test.go, src/common/security/robot/context.go, src/common/security/robot/context_test.go, src/common/security/robot/robot_test.go, src/core/api/base.go, src/core/api/chart_label.go, src/core/api/chart_repository.go, src/core/api/label.go, src/core/api/metadata.go, src/core/api/project.go, src/core/api/projectmember.go, src/core/api/repository.go, src/core/api/repository_label.go, src/core/api/robot.go, src/core/api/scan_job.go, src/core/api/user_test.go, src/core/service/token/creator.go
=> [Cherry pick]fix(rbac): NewProjectNamespace in rbac only accept projectID

tests/resources/Harbor-Pages/Replication.robot, tests/resources/Harbor-Pages/Replication_Elements.robot, tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Replication.robot
Add AWS-ECR and Google-GCR replication test into nighly tests.
=> Add AWS-ECR and Google-GCR replication test into nighly tests.

src/portal/lib/src/project-policy-config/project-policy-config.component.html, src/portal/src/app/user/user.component.html, tests/resources/Harbor-Pages/ToolKit.robot
=> Modify robot

CONTRIBUTING.md, docs/installation_guide.md
=> add harbor components version and gosec checking in drone ci

src/core/api/internal.go
=> add read only for quota switcher

tests/resources/Harbor-Pages/Verify.robot, tests/robot-cases/Group0-BAT/API_DB.robot, tests/robot-cases/Group1-Nightly/Clair.robot, tests/robot-cases/Group1-Nightly/OIDC.robot, tests/robot-cases/Group1-Nightly/Replication.robot
1.Add CVE white list API test into API_DB.robot;2.Random data for project name should use lower case %m%s;3.Replace from harbor to self.
=> Add CVE white list API test into API_DB.robot and some other modification

docs/swagger.yaml
=> docs(swagger): add Products tag for quota APIs

docs/user_guide.md
=> Xaleeks master role to user guide

docs/user_guide.md
Signed-off-by: xaleeks <xalex@vmware.com>
=> changed user_guide.md

tests/robot-cases/Group0-BAT/API_DB.robot, tests/robot-cases/Group1-Nightly/Clair.robot, tests/robot-cases/Group1-Nightly/OIDC.robot, tests/robot-cases/Group1-Nightly/Replication.robot
1.Add CVE white list API test into API_DB.robot;2.Random data for prjoect name should use lower case %m%s;3.Replace from harbor to self.
=> Add CVE white list API test into API_DB.robot and Modified datetime format and some naming issues

src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.scss, src/portal/src/app/project/webhook/webhook.component.html, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> modify css for tag-retention and webhook

docs/user_guide.md
Fixes https://github.com/goharbor/harbor/issues/7809.
=> Minor doc fixes

docs/user_guide.md
Fixes https://github.com/goharbor/harbor/issues/7809 in the 1.8 docs and also mentions that password cannot begin with `#`.
=> Minor doc fixes for the 1.8 docs

src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/replication/dao/execution.go, src/replication/dao/execution_test.go, src/replication/dao/models/execution.go, src/replication/operation/execution/execution_test.go, src/replication/operation/flow/stage.go
Related issue: https://github.com/goharbor/harbor/issues/8962
=> Not use time pointer in model fields

docs/swagger.yaml, src/core/api/retention.go, src/pkg/retention/controller_test.go, src/pkg/retention/manager.go, src/pkg/retention/manager_test.go, src/pkg/retention/models.go, src/pkg/retention/policy/models.go, src/pkg/retention/policy/rule/models.go, src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.ts, tests/apitests/python/library/base.py, tests/apitests/python/library/docker_api.py, tests/apitests/python/library/repository.py, tests/apitests/python/library/retention.py, tests/apitests/python/test_retention.py, tests/apitests/python/testutils.py, tests/robot-cases/Group0-BAT/API_DB.robot
1. add swagger for tag retention
2. enhance some validation
3. add e2e lib for tag retention
=> add swagger for tag retention

make/photon/log/rsyslog.conf
=> disable syslog DNS name resolution

src/portal/src/app/harbor-routing.module.ts, src/portal/src/app/project/project-detail/project-detail.component.ts, src/portal/src/app/shared/route/member-permission-guard-activate.service.ts, src/portal/src/app/shared/shared.module.ts
=> Add page routing permission to prevent refresh from entering the error page

make/photon/prepare/main.py, make/photon/prepare/utils/configs.py
* Add logic to read clair and notary config
=> Cherry-pick parse config to 1.9.0

src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html, src/replication/dao/execution.go, src/replication/dao/execution_test.go, src/replication/dao/models/execution.go, src/replication/operation/execution/execution_test.go, src/replication/operation/flow/stage.go
Related issue: https://github.com/goharbor/harbor/issues/8962
Cherry pick from: https://github.com/goharbor/harbor/pull/8963
=> [Cherry-Pick] Replication jobs timezone

src/common/job/client.go, src/common/job/client_test.go, src/core/api/admin_job.go, src/replication/operation/controller.go, src/replication/operation/controller_test.go
Check the status behind error when trying to update the scan schedule
=> Check the status behind error when trying to update the scan schedule

docs/swagger.yaml, src/core/api/retention.go, src/pkg/retention/controller_test.go, src/pkg/retention/manager.go, src/pkg/retention/manager_test.go, src/pkg/retention/models.go, src/pkg/retention/policy/models.go, src/pkg/retention/policy/rule/models.go, src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.ts, tests/apitests/python/library/base.py, tests/apitests/python/library/docker_api.py, tests/apitests/python/library/repository.py, tests/apitests/python/library/retention.py, tests/apitests/python/test_retention.py, tests/apitests/python/testutils.py, tests/robot-cases/Group0-BAT/API_DB.robot
add swagger for tag retention
enhance some validation
add e2e lib for tag retention
=> [Cherry-Pick]add swagger for tag retention

src/common/job/client.go, src/common/job/client_test.go, src/core/api/admin_job.go, src/replication/operation/controller.go, src/replication/operation/controller_test.go
Check the status behind error when trying to update the scan schedule
=> [Cherry-pick 1.8.3]Check the status behind error when trying to update the scan schedule

src/common/job/client.go, src/common/job/client_test.go, src/core/api/admin_job.go, src/replication/operation/controller.go, src/replication/operation/controller_test.go
Check the status behind error when trying to update the scan schedule
=> [Cherry-pick 1.9]Check the status behind error when trying to update the scan schedule

src/portal/lib/src/project-policy-config/project-policy-config.component.html, src/portal/lib/src/project-policy-config/project-policy-config.component.scss, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
change button text from "ADD SYSTEM" to "COPY FROM SYSTEM" in project config page(cherry-pick #9038)
=> change button text from "ADD SYSTEM" to "COPY FROM SYSTEM" 

make/migrations/postgresql/0010_1.9.0_schema.up.sql, src/common/dao/dao_test.go, src/common/dao/register.go, src/common/dao/user.go, src/common/models/user.go, src/common/utils/encrypt.go, src/common/utils/test/database.go, src/common/utils/utils_test.go, src/core/api/user.go, src/core/controllers/base.go
Use sha256 for newer encryption but the previous sha1 will still be used for the old password
=> Upgrade hash alg for pswd

docs/migration_guide.md
@reasonerjt can you please review and add more reviewers as appropriate? Thanks!
=> Updated upgrade and migration guide for 1.9

docs/swagger.yaml, tests/apitests/python/library/docker_api.py, tests/apitests/python/library/system.py, tests/apitests/python/test_project_quota.py, tests/robot-cases/Group0-BAT/API_DB.robot
* add e2e test case for project quota
=> Quota e2e case

docs/installation_guide.md
@reasonerjt and @xaleeks does this cover it?
=> Documented how to configure Syslog and DB connection pool in harbor.yml

docs/migration_guide.md
Cherry-picking the updates from https://github.com/goharbor/harbor/pull/9045 into the `release-1.9.0` branch.
@reasonerjt and @xaleeks can you please approve?
=> Cherry pick upgrade doc updates into 1.9 branch

src/core/api/project.go, src/core/api/project_test.go, src/core/controllers/base.go
Project head only allow authenticated user to call.
=> Fix: Add authenticate to projects head

docs/permissions.md
Signed-off-by: xaleeks <xalex@vmware.com>
=> added permissions for 1.9 features

src/portal/lib/src/project-policy-config/project-policy-config.component.html, src/portal/src/app/project/member/add-member/add-member.component.html, src/portal/src/global.scss
Modify css for add-memeber page and project-config page
Format global.scss file
=> Modify css for add-memeber page and project-config page

src/portal/src/app/group/add-group-modal/add-group-modal.component.html, src/portal/src/app/group/add-group-modal/add-group-modal.component.scss, src/portal/src/app/group/add-group-modal/add-group-modal.component.ts, src/portal/src/app/project/member/add-group/add-group.component.ts
=> Supplement group ui

src/portal/lib/src/repository/repository.component.html
=> Add id in repo info button

src/portal/src/app/project/create-project/create-project.component.html, src/portal/src/app/project/create-project/create-project.component.ts
Improve project name validator when adding new project .
It will fix #9144
=> Improve project name validator when adding new project

docs/SECURITY.md
Signed-off-by: xaleeks <xalex@vmware.com>
=> security disclosure process

src/core/api/base.go, src/core/controllers/base.go, src/core/controllers/oidc.go
This commit mitigates the Session Fixation issue by making sure a new
session ID is generated each time user logs in to Harbor
=> Generate new session ID after login

src/portal/lib/src/config/config.ts, src/portal/lib/src/config/vulnerability/vulnerability-config.component.scss, src/portal/lib/src/shared/shared.const.ts, src/portal/src/app/app-config.service.ts, src/portal/src/app/base/harbor-shell/harbor-shell.component.html, src/portal/src/app/base/harbor-shell/harbor-shell.component.ts, src/portal/src/app/config/auth/config-auth.component.html, src/portal/src/app/config/auth/config-auth.component.scss, src/portal/src/app/group/add-group-modal/add-group-modal.component.html, src/portal/src/app/group/add-group-modal/add-group-modal.component.ts, src/portal/src/app/group/group.component.ts, src/portal/src/app/project/member/add-http-auth-group/add-http-auth-group.component.ts, src/portal/src/app/project/member/member.component.html, src/portal/src/app/project/member/member.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1. add oidc group claim in configration page
2. add oidc group-page in user page,you can go to it through clicking add-group button;
3. add oidc list page in administrator ,admin can go to this page
fix #9024 ;
fix #9026 ;
=> Add oidc group claim in config-auth、member、administrator

src/common/api/base.go, src/core/api/robot.go
related with https://github.com/goharbor/harbor/issues/8197.
Every redirection request behind of apis has this problem. This pr can be general solution.
=> All redirect operations should have content-type as json

make/photon/prepare/templates/nginx/nginx.https.conf.jinja
This commit modifies nginx configuration file to make sure the secure
flag is added to "Set-Cookie" header when Harbor is serving https
=> Add Secure flag to cookie

src/portal/src/app/account/sign-up/sign-up.component.html, tests/resources/Harbor-Pages/HomePage_Elements.robot
Modify sign-up button xpath from relative HTML path to id, and modify script.
=> Modify sign-up button xpath from relative html path to id

make/migrations/postgresql/0015_1.10.0_schema.up.sql, src/common/dao/immutable.go, src/common/dao/immutable_test.go, src/common/models/base.go, src/common/models/immutable.go
Add CRUD operation on immutable tag rules
=> Add DAO for immutable tags

docs/migration_guide.md
add the migration method after 1.8.x
=> Update the doc of migration

src/portal/karma.conf.js, src/portal/lib/karma.conf.js, src/portal/src/app/account/account-settings/account-settings-modal-service.service.spec.ts, src/portal/src/app/app.module.ts, src/portal/src/app/dev-center/dev-center.component.spec.ts, src/portal/src/app/gc-page/gc-page.component.spec.ts, src/portal/src/app/group/add-group-modal/add-group-modal.component.spec.ts, src/portal/src/app/group/group.component.spec.ts, src/portal/src/app/group/group.service.spec.ts, src/portal/src/app/license/license.component.spec.ts, src/portal/src/app/oidc-onboard/oidc-onboard.component.spec.ts, src/portal/src/app/oidc-onboard/oidc-onboard.service.spec.ts, src/portal/src/app/project/helm-chart/helm-chart-detail/chart-detail.component.spec.ts, src/portal/src/app/project/helm-chart/list-chart-versions/list-chart-versions.component.spec.ts, src/portal/src/app/project/helm-chart/list-charts.component.spec.ts, src/portal/src/app/project/member/add-group/add-group.component.spec.ts, src/portal/src/app/project/member/add-http-auth-group/add-http-auth-group.component.spec.ts, src/portal/src/app/project/member/add-http-auth-group/add-http-auth-group.component.ts, src/portal/src/app/project/project-config/project-config.component.spec.ts, src/portal/src/app/project/robot-account/add-robot/add-robot.component.spec.ts, src/portal/src/app/project/robot-account/robot-account.component.spec.ts, src/portal/src/app/project/summary/summary.component.spec.ts, src/portal/src/app/replication/replication-tasks-page/replication-tasks-page.component.spec.ts, src/portal/src/app/vulnerability-page/vulnerability-page.component.spec.ts
1Fix harbor portal unit test to make sure all the test will run in CI. 
2 set threshold in karma config 
portal global coverage threshold:
global: {
statements: 47,
branches: 18,
functions: 27,
lines: 47
},
lib global coverage threshold: 
global: {
statements: 37,
branches: 20,
functions: 28,
lines: 36
},
=> fix harbor portal unit test and set thresholds

src/jobservice/api/authenticator.go
Update the erro log format in jobservice
=> Update the error log format

src/jobservice/api/authenticator.go
Update the erro log format in jobservice
=> [Cherry-pick]Update the error log format

docs/swagger.yaml
=> [cherry-pick]Add quota switcher swagger doc

src/portal/karma.conf.js, src/portal/lib/karma.conf.js, src/portal/lib/src/config/gc/gc-history/gc-history.component.spec.ts, src/portal/src/app/user/change-password/change-password.component.spec.ts, src/portal/src/app/user/change-password/change-password.component.ts, src/portal/src/app/user/new-user-modal.component.spec.ts, src/portal/src/app/user/user.component.spec.ts, src/portal/src/app/user/user.service.spec.ts
1 Add more unit test
2 Set coverage break to warning to avoid ci break.
=> add more unit test

make/migrations/postgresql/0010_1.9.0_schema.up.sql, make/migrations/postgresql/0011_1.9.1_schema.up.sql, src/common/dao/dao_test.go, src/common/dao/register.go, src/common/dao/user.go, src/common/models/user.go, src/common/utils/encrypt.go, src/common/utils/test/database.go, src/common/utils/utils_test.go, src/core/api/user.go, src/core/controllers/base.go
Update alg for pswd
The old one still be used for the old pswd
=> Cherry pick 19 upgrade hash alg for pswd

src/jobservice/core/controller.go, src/jobservice/logger/base_test.go, src/jobservice/logger/getter/file_getter.go, src/jobservice/logger/getter/file_getter_test.go
the logid content need check before use
=> Add checking for logid

src/jobservice/logger/backend/file_logger.go
Log file permission from 644 to 600
=> change the permission of job log file

make/photon/prepare/templates/nginx/nginx.http.conf.jinja, make/photon/prepare/templates/nginx/nginx.https.conf.jinja
extra headered added in https and http config
=> Add headers in nginx config file

src/core/api/project.go, src/core/api/project_test.go, src/core/controllers/base.go
Add more check for head request for projects
=> Fix: Add more check for projects head

docs/user_guide.md
@xaleeks do we want to add the workaround from https://github.com/goharbor/harbor/issues/8717#issuecomment-528235134?
=> Documenting tag retention issue

docs/swagger.yaml, src/common/dao/immutable.go, src/common/rbac/const.go, src/common/rbac/project/util.go, src/common/rbac/project/visitor_role.go, src/core/api/api_test.go, src/core/api/harborapi_test.go, src/core/api/immutabletagrule.go, src/core/api/immutabletagrule_test.go, src/core/router.go, src/pkg/immutabletag/rulemanager.go
=> Immutable tag api

docs/user_guide.md
Cherry-picking PR #9215 from `release-1.9.0` into the `master` branch. 
@ywk253100 and @ninjadq can you please approve? Thanks!
=> Documenting tag retention issue (#9215)

src/portal/src/app/base/harbor-shell/harbor-shell.component.html, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> fix language expression issue for tag retention

src/common/rbac/rbac.go, src/common/security/robot/robot.go, src/common/security/robot/robot_test.go, src/core/api/robot.go, src/core/api/robot_test.go, tests/apitests/python/library/project.py
=> [Cherry pick]fix(robot): robot account improvement

src/common/rbac/rbac.go, src/common/security/robot/robot.go, src/common/security/robot/robot_test.go, src/core/api/robot.go, src/core/api/robot_test.go, tests/apitests/python/library/project.py
=> fix(robot): robot account improvement

docs/customize_look&feel_guide.md, src/portal/src/app/base/global-search/global-search.component.ts, src/portal/src/app/base/navigator/navigator.component.html, src/portal/src/app/base/navigator/navigator.component.ts, src/portal/src/app/shared/about-dialog/about-dialog.component.html, src/portal/src/app/sign-in/sign-in.component.html, src/portal/src/app/skinable-config.service.ts, src/portal/src/setting.json
=> Fix setting.json bug

src/portal/lib/src/service/interface.ts, src/portal/lib/src/tag/tag-detail.component.html, src/portal/lib/src/tag/tag-detail.component.scss, src/portal/lib/src/tag/tag-detail.component.ts, src/portal/lib/src/vulnerability-scanning/histogram-chart/histogram-chart.component.scss, src/portal/lib/src/vulnerability-scanning/histogram-chart/histogram-chart.component.ts, src/portal/lib/src/vulnerability-scanning/result-bar-chart.component.ts, src/portal/lib/src/vulnerability-scanning/result-grid.component.html, src/portal/lib/src/vulnerability-scanning/result-grid.component.ts, src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.html, src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.scss, src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.ts, src/portal/lib/src/vulnerability-scanning/scanning.scss, src/portal/src/app/project/scanner/scanner.component.html
=> Fix scanner UI bugs

Makefile, make/checkenv.sh, make/common.sh, make/install.sh
This commit fixes #8622 by extract shared func into common.sh to avoid
inconsistency in future.
=> Extract shared func for checkenv and install scripts

tests/resources/Util.robot, tests/robot-cases/Group1-Nightly/Common.robot
Add nightly test case of 'Retag should be forbidden when read only mode is set'.
It should fix issue #7432.
=> Add nightly test case of 'Retag should be forbidden when read only mode is set'

docs/swagger.yaml, src/core/api/user.go, src/core/api/user_test.go, src/core/router.go
This commit replace the API to generate CLI secret with a new API to
update the secret
=> API for user to set the CLI secret

docs/user_guide.md
=> Fixed typo

src/common/utils/registry/auth/apikey.go, src/common/utils/registry/auth/apikey_test.go, src/jobservice/job/impl/replication/replication.go, src/replication/adapter/quayio/adapter.go, src/replication/adapter/quayio/adapter_test.go, src/replication/adapter/quayio/types.go, src/replication/model/registry.go, src/replication/replication.go
https://github.com/goharbor/harbor/issues/8410
=> Feat/image replication adapter for quay.io

src/core/api/quota/registry/registry.go
=> ignore the duplicate error when to insert project_blobs on quota syncing

src/core/api/robot.go, src/pkg/robot/dao/robot.go
=> fix list robot account API return an internal error

src/core/api/quota/registry/registry.go
=> [cherry-pick]ignore the duplicate error when to insert project_blobs on quota syncing

src/core/api/immutabletagrule.go, src/pkg/immutabletag/controller.go, src/pkg/immutabletag/match/matcher.go, src/pkg/immutabletag/match/rule/match.go, src/pkg/immutabletag/match/rule/match_test.go
=> add immutable match

src/core/api/chart_label.go, src/core/api/chart_repository.go, src/core/api/label.go, src/core/api/quota/migrator.go, src/core/api/repository.go, src/core/api/systeminfo.go, src/core/notifier/notification_handler.go, src/core/promgr/metamgr/metamgr.go, src/core/promgr/promgr.go, src/core/service/notifications/admin/handler.go, src/core/service/notifications/jobs/handler.go, src/core/service/token/token.go, src/core/utils/utils.go
=> Fix typos in core package

src/common/config/metadata/metadatalist.go
Disable self_registration by default 
=> Update default self_registration=false

src/portal/src/app/config/auth/config-auth.component.html
=> Remove validation about oidc claim group

src/portal/lib/src/push-image/copy-input.coponent.html
=> Fix copy button not working

src/portal/src/app/account/account-settings/account-settings-modal-service.service.ts, src/portal/src/app/account/account-settings/account-settings-modal.component.html, src/portal/src/app/account/account-settings/account-settings-modal.component.scss, src/portal/src/app/account/account-settings/account-settings-modal.component.ts, src/portal/src/app/account/account-settings/account.ts, src/portal/src/app/shared/shared.utils.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Add new cli secret ui in profile

tests/integration.sh, tests/resources/Harbor-Util.robot
=> add npm registry when to build offline package in drone CI

src/core/middlewares/chain.go, src/core/middlewares/config.go, src/core/middlewares/immutable/handler.go, src/core/middlewares/immutable/handler_test.go, src/pkg/immutabletag/match/rule/match_test.go
=> add immutable tag middleware

src/portal/lib/src/config/system/system-settings.component.ts, src/portal/lib/src/project-policy-config/project-policy-config.component.ts
=> Remove CVE ID check

src/portal/lib/src/config/system/system-settings.component.ts, src/portal/lib/src/project-policy-config/project-policy-config.component.ts, src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.ts, src/portal/src/app/project/tag-retention/tag-retention.service.ts
1.Remove CVE ID check  #9242
2.Add server paging to tag-retention sub task list #9337
=> Remove CVE ID check(cherry pick #9440)

src/portal/src/app/project/tag-retention/tag-retention.component.html, src/portal/src/app/project/tag-retention/tag-retention.component.ts, src/portal/src/app/project/tag-retention/tag-retention.service.ts
=> Add server paging to tag-retention sub task list

tests/integration.sh, tests/resources/Harbor-Util.robot
=> [cherry-pick]add npm registry when to build offline package in drone CI

.drone.yml
=> [cherry-pick]add npm registry into drone yml

.drone.yml, tests/integration.sh, tests/resources/Harbor-Util.robot
=> debug drone ci error

RELEASES.md, SECURITY.md
Document the versioning and release process.
Signed-off-by: Steven Ren <stevenr@stevenr-a01.vmware.com>
=> Document the versioning and release process

make/install.sh
=> disable noglob after import common

docs/permissions.md, make/migrations/postgresql/0015_1.10.0_schema.up.sql, src/common/const.go, src/common/dao/project.go, src/common/models/project.go, src/common/rbac/project/util.go, src/common/rbac/project/visitor_role.go, src/common/rbac/project/visitor_role_test.go, src/common/security/local/context.go, src/core/api/project.go, src/core/api/projectmember.go, src/core/api/projectmember_test.go, src/portal/lib/src/shared/shared.const.ts, src/portal/src/app/project/member/add-member/add-member.component.html, src/portal/src/app/project/member/member.component.html, src/portal/src/app/project/summary/summary.component.html, src/portal/src/app/shared/route/member-guard-activate.service.ts, src/portal/src/app/shared/shared.const.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1. Introduce a limited guest role, see issue #8632 
2. Change all policies of project from static table to compute from all roles' policies
3. Change the role validation from comparing with number range to comparing with all roles
=> feat(role): introduce a limited guest role

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts, src/portal/src/app/project/member/member.component.ts, src/portal/src/app/project/robot-account/add-robot/add-robot.component.html, src/portal/src/app/project/robot-account/add-robot/add-robot.component.spec.ts, src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts, src/portal/src/app/shared/shared.utils.ts
fix #9271 
fix #9207 
fix #9178 
=> Fix bug in harbor UI

src/core/api/sys_cve_whitelist_test.go, src/pkg/scan/whitelist/validator.go, src/pkg/scan/whitelist/validator_test.go
To contain various vulnerabilities in the CVE whitelist, this commit
removes the validation.
Fixes #9242
=> Remove validation for item in CVE whitelist

src/portal/lib/src/config/registry-config.component.html, src/portal/lib/src/config/registry-config.component.scss, src/portal/lib/src/config/system/system-settings.component.html, src/portal/lib/src/project-policy-config/project-policy-config.component.html, src/portal/lib/src/repository/repository.component.html, src/portal/lib/src/tag/tag.component.html, src/portal/lib/src/tag/tag.component.ts, src/portal/src/app/base/harbor-shell/harbor-shell.component.html, src/portal/src/app/config/scanner/config-scanner.component.html, src/portal/src/app/config/scanner/config-scanner.component.scss, src/portal/src/app/config/scanner/config-scanner.component.ts, src/portal/src/app/config/scanner/new-scanner-form/new-scanner-form.component.html, src/portal/src/app/config/scanner/new-scanner-form/new-scanner-form.component.scss, src/portal/src/app/config/scanner/new-scanner-form/new-scanner-form.component.ts, src/portal/src/app/project/scanner/scanner.component.html, src/portal/src/app/project/scanner/scanner.component.scss, src/portal/src/app/repository/tag-detail/tag-detail-page.component.html, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
1. Remove all *ngIf ="withClair" flags as scanners are pluggable now.
2. Modify css
=> Improve scanner UI

src/portal/lib/src/service/interface.ts, src/portal/lib/src/tag/tag.component.html, src/portal/src/app/account/account-settings/account-settings-modal.component.scss, src/portal/src/app/account/account-settings/account-settings-modal.component.ts, src/portal/src/i18n/lang/en-us-lang.json, src/portal/src/i18n/lang/es-es-lang.json, src/portal/src/i18n/lang/fr-fr-lang.json, src/portal/src/i18n/lang/pt-br-lang.json, src/portal/src/i18n/lang/tr-tr-lang.json, src/portal/src/i18n/lang/zh-cn-lang.json
=> Improve immutable,fix oidc nightly error

src/portal/lib/src/create-edit-rule/create-edit-rule.component.html, src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
=> Add enable rule when Edit replication

docs/registry_landscape.md
Updated registry landscape with more features and added GitLab as a column.
Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>
=> Update the Registry Landscape

src/common/utils/ldap/ldap.go
Remove the code change in #8378, because the previous code change caused issues: #9092, #9110, #9326
=> Remove the nested group search -- cherrypick 1.9
