- src/common/config/metadata/metadatalist.go
Update default self_registration=false
> Disable self registration by default (cherry-pick)

- docs/swagger.yaml
- src/common/models/repo.go
- src/core/api/repository.go
- src/core/middlewares/config.go
- src/core/middlewares/immutable/builder.go
- src/core/middlewares/immutable/handler.go
- src/core/middlewares/interceptor/immutable/deletemf.go
- src/core/middlewares/interceptor/immutable/pushmf.go
- src/core/middlewares/util/error/immutable.go
> add immutable match in the repository/tag delete api

- src/core/middlewares/interceptor/immutable/deletemf.go
- tests/apitests/python/test_project_quota.py
> update query in the immutable delete manifest middleware

- tests/resources/Harbor-Pages/OIDC_Auth.robot
> Modify the words of setting cli secret

- src/portal/lib/src/create-edit-rule/create-edit-rule.component.ts
- src/portal/lib/src/replication/replication.component.html
- src/portal/lib/src/replication/replication.component.scss
- src/portal/lib/src/repository/repository.component.spec.ts
- src/portal/lib/src/tag/tag.component.spec.ts
- src/portal/lib/src/tag/tag.component.ts
> Modify the permission when add Limited Guest

- src/jobservice/job/impl/gc/job.go
> fix(gc,quota): clean blob size cache in redis when gc

- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
> Cherry-pick  the way of replication show label

- .drone.yml
- tests/integration.sh
Change-Id: I58369eb059243e0a059c8be86cd980c2cb42f0bc
> add gpg sign

- src/portal/lib/src/create-edit-rule/create-edit-rule.component.html
> Modiy the way of replication show label filter

- src/replication/dao/execution.go
> code simplify

- src/jobservice/job/impl/context.go
> fix fatal error

- make/migrations/postgresql/0015_1.10.0_schema.up.sql
- src/core/api/immutabletagrule.go
- src/core/middlewares/immutable/handler.go
- src/core/middlewares/interceptor/immutable/deletemf.go
- src/core/middlewares/interceptor/immutable/pushmf.go
- src/core/middlewares/util/error/immutable.go
- src/pkg/immutabletag/controller.go
- src/pkg/immutabletag/controller_test.go
- src/pkg/immutabletag/dao/immutable.go
- src/pkg/immutabletag/dao/immutable_test.go
- src/pkg/immutabletag/dao/model/rule.go
- src/pkg/immutabletag/manager.go
- src/pkg/immutabletag/manager_test.go
- src/pkg/immutabletag/match/rule/match_test.go
1, unify disable and enable
2, fix update rule error
> update immutable rule API

- src/portal/lib/src/confirmation-dialog/confirmation-dialog.component.html
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/app/project/webhook/webhook.component.html
- src/portal/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
- tests/resources/Harbor-Pages/Project-Webhooks.robot
- tests/resources/Harbor-Pages/Project-Webhooks_Elements.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add webhook nightly case

- src/common/dao/group/usergroup.go
User Group Query SQL error in some cases
> Fix User Group Search SQL error

- src/common/dao/group/usergroup.go
User Group Query SQL error in some cases
> Fix User Group Search SQL error (cherry-pick)

- src/common/rbac/const.go
- src/common/rbac/project/util.go
- src/common/rbac/project/visitor_role.go
- src/core/api/harborapi_test.go
- src/core/api/pro_scanner.go
- src/core/api/pro_scanner_test.go
- src/core/router.go
- src/pkg/scan/api/scanner/base_controller.go
- src/pkg/scan/dao/scanner/model.go
- add new endpoint for getting scanner candidates of specified project
- adjust the permission granting functions
- fix #9608
> permission grant for scanner related actions are not correctly

- src/common/dao/user.go
> remove useless code

- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html
- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.scss
- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.spec.ts
- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.ts
- src/portal/lib/src/endpoint/endpoint.component.spec.ts
1. change adapterInfo from "by hardcode" to "by getting from back-end API" for registries UI
2. add server paging to tasks list for tag-retantion
> change adapterInfo from by hardcode to by getting from backend API

- src/portal/lib/src/repository-gridview/repository-gridview.component.ts
- src/portal/lib/src/shared/shared.utils.ts
> Fix the error when delete some images

- src/jobservice/job/impl/scan/all.go
- src/pkg/scan/event/init.go
> fix bug found in the pluggable scanner

- src/portal/src/app/project/immutable-tag/immutable-tag.component.html
- src/portal/src/app/project/immutable-tag/immutable-tag.component.scss
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
> Improve immutable ui style

- src/portal/lib/src/tag/tag.component.scss
> Fix page style confusion caused by error margin-top

- tools/migration/cfg/migrator_1_10_0/__init__.py
- tools/migration/cfg/migrator_1_10_0/harbor.yml.jinja
- tools/migration/cfg/run.py
Add migrator for harbor 1.10.0
> Upgrade script 190 to 110

- tests/resources/Docker-Util.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/DB.robot
fixed bug of enable self reg, explore should be opened and navigate to harbor log in page
> fixed bug of enable self registration

- tests/robot-cases/Group1-Nightly/Common.robot
Image postgres severity has changed from high to low, so nightly script should be updated
> Fix nightly script issue due to image postgres severity has changed from high to low

- src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.html
- src/portal/src/app/project/immutable-tag/immutable-tag.component.spec.ts
> Fix a warning that appears when running the test

- docs/configure_https.md
- docs/installation_guide.md
@reasonerjt @xaleeks can you please review and approve? Thanks!
> Clarified that HTTP is still the default in 1.9.x

- docs/user_guide.md
This PR replaces https://github.com/goharbor/harbor/pull/7631
> Fixed typo per pr 7631

- Makefile
- make/photon/core/Dockerfile
- src/core/api/systeminfo.go
- src/core/main.go
- src/pkg/version/version.go
- tests/integration.sh
- tests/resources/Harbor-Util.robot
> add ldflags for harbor compiler and linker

- make/photon/prepare/templates/core/env.jinja
- src/core/main.go
> add a switcher for quota sync on core launch

- make/photon/prepare/templates/core/app.conf.jinja
- make/photon/prepare/utils/core.py
- src/core/api/base.go
- src/core/api/harborapi_test.go
- src/core/api/user.go
- src/core/api/user_test.go
- src/core/config/config.go
- src/core/controllers/controllers_test.go
- src/core/controllers/proxy.go
- src/core/filter/sessionchecker.go
- src/core/filter/sessionchecker_test.go
- src/core/main.go
- src/core/service/notifications/admin/handler.go
- src/core/service/notifications/jobs/handler.go
- src/core/service/notifications/registry/handler.go
- src/portal/lib/src/service/http-xsrf-token-extractor.service.spec.ts
- src/portal/lib/src/service/http-xsrf-token-extractor.service.ts
- src/portal/lib/src/shared/shared.module.ts
- src/portal/src/app/dev-center/dev-center.component.ts
> Refine request handle process

- make/photon/prepare/utils/misc.py
Secrets is included in python 3.6, so just import and use it
> Replance python ran lib to secrets

- src/portal/src/app/config/config.component.html
> [cherry-pick-1.9.0]change element id in config page

- src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.html
- src/portal/lib/src/config/project-quotas/edit-project-quotas/edit-project-quotas.component.scss
- src/portal/lib/src/config/project-quotas/project-quotas.component.html
- src/portal/lib/src/config/project-quotas/project-quotas.component.scss
- src/portal/src/app/project/summary/summary.component.html
- src/portal/src/app/project/summary/summary.component.scss
UI design: https://www.figma.com/file/0bSkyzvchcOCrwSWROIivtIb/Harbor-v1.9?node-id=235%3A531
> Improve the style of quota ui

- make/photon/common/install_cert.sh
Every file in specific dir `/harbor_cust_cert` will be appended to the end of the system ca_bundle
> All certs in /harbor_cust_certs will appended to ca_bundle

- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
> Modify the tootip words of verify remote cert.

- src/portal/lib/src/tag/tag.component.ts
- src/portal/src/app/base/navigator/navigator.component.scss
1.One of the request is cancelled when trying to do the multiple deletion for tags(fix #9720  #9714 )
after modify:
2.when using other languages, switch languages, English button has default border
after modify:
> Fix bug of UI;

- tests/apitests/python/test_health_check.py
- tests/robot-cases/Group0-BAT/API_DB.robot
Add e2e test case for health check API
> Add e2e test case for health check API

- make/photon/chartserver/Dockerfile
- make/photon/chartserver/docker-entrypoint.sh
- make/photon/clair/Dockerfile
- make/photon/clair/docker-entrypoint.sh
- make/photon/prepare/utils/configs.py
- make/photon/registry/Dockerfile
- make/photon/registry/entrypoint.sh
- make/photon/registryctl/Dockerfile
- make/photon/registryctl/start.sh
- tests/docker-compose.test.yml
- tests/pushimage.sh
- tests/reg_config.yml
- tests/travis/ut_install.sh
* Registry user to non-root
* Registryctl user to non-root
* Clair user to non-root
* Chartmuseum user to non-root
> Inject certs to non root

- docs/migration_guide.md
Add instructions for migration using offline installer.
Requested by Wang Yan in Issue 7831
> Document offline migration

- API/harbor/swagger.yaml
- tests/apitests/python/test_scan_image.py
- add scanners mgmt related API
- add scan related API
- trigger scan
- get report
- get log text stream
- update the scan_overview in the tag getting API
- fix #9606
> update API swagger file

- make/install.sh
> Fix install script

- API/harbor/swagger.yaml
Issue: https://github.com/goharbor/harbor/issues/9624
> fix: add spec of oidc settings in swagger.yaml

- src/portal/lib/src/confirmation-dialog/confirmation-dialog.component.html
- src/portal/lib/src/repository/repository.component.html
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/app/project/webhook/webhook.component.html
- src/portal/src/app/shared/confirmation-dialog/confirmation-dialog.component.html
- tests/resources/Harbor-Pages/Project-Webhooks.robot
- tests/resources/Harbor-Pages/Project-Webhooks_Elements.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> [cherry-pick 1.9.0]Add webhook nightly case

- src/core/api/admin_job.go
- src/core/api/scan_all.go
- src/pkg/scan/all/stats.go
> add status data in the scan all metrics

- src/portal/lib/src/tag/tag.component.html
- src/portal/lib/src/tag/tag.component.ts
> Fix the bug of cannot soft by pull time

- src/pkg/immutabletag/manager.go
> Fix immutable rule sequence to list API

- src/portal/lib/src/tag/tag.component.html
- src/portal/lib/src/tag/tag.component.scss
- src/portal/lib/src/utils.ts
- src/portal/lib/src/vulnerability-scanning/result-bar-chart-component.html
- src/portal/lib/src/vulnerability-scanning/result-grid.component.html
- src/portal/lib/src/vulnerability-scanning/result-grid.component.ts
- src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.html
- src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.scss
- src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.ts
- src/portal/lib/src/vulnerability-scanning/scanning.scss
- src/portal/src/app/config/scanner/config-scanner.component.ts
- src/portal/src/app/config/scanner/new-scanner-form/new-scanner-form.component.html
- src/portal/src/app/config/scanner/new-scanner-form/new-scanner-form.component.scss
- src/portal/src/app/config/scanner/new-scanner-modal/new-scanner-modal.component.ts
- src/portal/src/app/project/immutable-tag/add-rule/add-rule.component.ts
- src/portal/src/app/project/tag-retention/add-rule/add-rule.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Fix UI bugs:
#9723 
#9721 
#9709 
#9708 
#9707 
#9706 
#9699
> Fix bugs for scanner UI testing round 1

- src/portal/lib/src/config/config.ts
- src/portal/lib/src/config/registry-config.component.html
- src/portal/lib/src/config/registry-config.component.ts
- src/portal/lib/src/config/vulnerability/scanAll.service.ts
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.html
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.scss
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.spec.ts
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
- src/portal/lib/src/log/recent-log.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Fix  #9744 and #9736
1.New UI
2. UI design: https://www.figma.com/proto/0bSkyzvchcOCrwSWROIivtIb/Harbor-v1.9?node-id=1251%3A1888&viewport=639%2C1697%2C0.5&scaling=min-zoom
3. Temporary available env. : https://10.160.194.191
> Refactor scan all page UI

- src/common/dao/user.go
> promote code quality

- make/photon/prepare/templates/registry/config.yml.jinja
Add these mediatypes to reduce the amount of registry event
> Add ignore mediatypes for registry

- tools/migration/cfg/migrator_1_9_0/harbor.yml.jinja
Signed-off-by: Peter Philipp <peter.philipp@cando-image.com>
> Possible fix for: https://github.com/goharbor/harbor/issues/9174

- src/portal/src/app/config/scanner/config-scanner.service.ts
- src/portal/src/app/config/scanner/new-scanner-form/new-scanner-form.component.html
- src/portal/src/app/config/scanner/new-scanner-form/new-scanner-form.component.scss
- src/portal/src/app/config/scanner/new-scanner-form/new-scanner-form.component.ts
- src/portal/src/app/project/scanner/scanner.component.html
- src/portal/src/app/project/scanner/scanner.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
> Fix bugs for scanner UI testing round 2

- .drone.yml
- tests/integration.sh
Change-Id: I32d13be2f5b5f383113582a4b1ad5f74bdc7546b
> [cherry-pick] add gpg sign

- src/portal/lib/src/shared/shared.const.ts
- src/portal/src/app/project/helm-chart/list-charts-detail/helm-chart.component.html
- src/portal/src/app/project/helm-chart/list-charts-detail/helm-chart.component.scss
- src/portal/src/app/project/project.component.ts
- src/portal/src/app/sign-in/sign-in.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
> Fix bug by ui test

- src/portal/src/app/project/tag-retention/add-rule/add-rule.component.html
- src/portal/src/app/project/tag-retention/tag-retention.component.html
- tests/resources/Harbor-Pages/Project-Tag-Retention.robot
- tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Test-Example/Test.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add nightly case for tag-retention

- src/portal/src/app/config/scanner/config-scanner.component.spec.ts
- src/portal/src/app/project/scanner/scanner.component.html
- src/portal/src/app/project/scanner/scanner.component.spec.ts
> Add more UT for scanner

- src/common/dao/group/usergroup.go
- src/common/dao/group/usergroup_test.go
- src/common/models/usergroup.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/auth/ldap/ldap.go
- src/core/auth/ldap/ldap_test.go
- src/core/controllers/oidc.go
- src/core/filter/security.go
Change include LDAP auth, OIDC auth, HTTP auth
> Populate group from auth provider to Harbor when user login

- src/core/api/harborapi_test.go
- src/core/api/user.go
- src/core/api/user_test.go
- tests/apitests/apilib/user_profile.go
Update the test cases of user API
> Update the test cases of user API

- src/portal/src/app/project/scanner/scanner.component.spec.ts
> Fix UT bug for scanner component

- src/replication/adapter/helmhub/adapter.go
Add adapter pattern for helm hub adapter
> Add adapter pattern for helm hub adapter

- src/portal/lib/src/tag/tag.component.html
- src/portal/lib/src/tag/tag.component.ts
- src/portal/lib/src/vulnerability-scanning/result-bar-chart.component.ts
- src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.html
- src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.scss
- src/portal/lib/src/vulnerability-scanning/scanning.scss
> Fix tag select bug in tag component

- src/core/middlewares/util/error/immutable.go
> update immutable tag error message format

- src/portal/lib/src/shared/shared.const.ts
- src/portal/src/app/sign-in/sign-in.component.ts
>  Cherry-pick 1.9 Hidden "Forgot Password" when the auth mode is  http_auth

- src/portal/lib/src/service/project.service.ts
- src/portal/src/app/project/list-project/list-project.component.html
- src/portal/src/app/project/list-project/list-project.component.spec.ts
- src/portal/src/app/project/list-project/list-project.component.ts
- src/portal/src/i18n/lang/zh-cn-lang.json
1. remove toggle public project code;
2. modify the way to show role in public project list;
3. Change the way the change detection is default and remove actively refreshed code;
environment：
https://10.192.162.161/
> Solve the problem that the style cannot be neat because the page is not refreshed

- src/core/api/replication_execution.go
- src/core/api/replication_execution_test.go
Remove the duplicated code in replication execution API
> Refine the implementation of replication execution API

- src/portal/lib/src/config/vulnerability/vulnerability-config.component.html
- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/resources/Harbor-Pages/Vulnerability_Elements.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Nightly.robot
> Modify scan now nightly case

- src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
- src/portal/lib/src/tag/tag.component.ts
- src/portal/lib/src/vulnerability-scanning/result-bar-chart.component.ts
> Modify the way to handle 409 error

- src/core/api/immutabletagrule.go
- src/core/api/immutabletagrule_test.go
- src/pkg/immutabletag/controller.go
- src/pkg/immutabletag/controller_test.go
- src/pkg/immutabletag/manager.go
- src/pkg/immutabletag/manager_test.go
Change implementation
Fix some nil pointer issue
> Refactor immutable tag rule

- src/common/dao/group/usergroup.go
- src/common/dao/group/usergroup_test.go
- src/common/models/usergroup.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/auth/ldap/ldap.go
- src/core/auth/ldap/ldap_test.go
- src/core/filter/security.go
Fix #9749, change include LDAP auth, OIDC auth, HTTP auth
> Populate group from auth provider to Harbor DB when user login (cherry-pick for 1.9.0)

- src/common/dao/group/usergroup.go
- src/common/models/usergroup.go
- src/core/auth/ldap/ldap.go
> Fix review comments on PR9749

- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/common/models/config.go
- src/core/api/config.go
- src/core/api/harborapi_test.go
- src/core/api/user.go
- src/core/api/user_test.go
- src/core/auth/authproxy/auth.go
- src/core/auth/authproxy/auth_test.go
- src/core/config/config.go
- src/core/config/config_test.go
- src/core/filter/security_test.go
- src/testing/apitests/apilib/user_profile.go
rework of https://github.com/goharbor/harbor/pull/9746 on `master` branch
> Authproxy case sensitive master

- src/common/dao/group/usergroup.go
- src/common/models/usergroup.go
- src/core/auth/ldap/ldap.go
> Fix review comments on PR9749 (cherry-pick)

- src/core/middlewares/contenttrust/handler.go
- src/core/middlewares/regtoken/handler.go
- src/core/middlewares/util/util.go
- src/core/middlewares/vulnerable/handler.go
> enable policy checker in response handler

- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.ts
- src/portal/src/app/project/webhook/add-webhook/add-webhook.component.ts
> Fix webhook testing-error bug

- src/common/config/manager.go
> Change log level to avoid tedious error in log

- src/portal/lib/src/config/vulnerability/scanAll.service.ts
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.html
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.scss
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.spec.ts
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
- src/portal/lib/src/service/interface.ts
- src/portal/lib/src/tag/tag.component.html
- src/portal/lib/src/utils.ts
- src/portal/lib/src/vulnerability-scanning/result-bar-chart-component.html
- src/portal/lib/src/vulnerability-scanning/result-bar-chart.component.ts
- src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.html
- src/portal/lib/src/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.ts
- src/portal/src/app/config/scanner/scanner-metadata/scanner-metadata.component.ts
- src/portal/src/app/config/scanner/scanner-metadata/scanner-metadata.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
1.Add scanner name
2. Add vulnerability database update time
> Add vulnerability database update time and scanner name

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
> fix(i18n): fix missing i18n for limited guest in group

- src/portal/lib/src/label/label.component.scss
- src/portal/lib/src/replication/replication.component.html
- src/portal/lib/src/replication/replication.component.scss
- src/portal/lib/src/tag/tag.component.html
- src/portal/lib/src/tag/tag.component.scss
- src/portal/src/app/config/scanner/config-scanner.component.html
- src/portal/src/app/config/scanner/config-scanner.component.scss
- src/portal/src/app/project/helm-chart/list-charts-detail/helm-chart.component.scss
- src/portal/src/app/project/scanner/scanner.component.html
- src/portal/src/app/project/scanner/scanner.component.scss
- src/portal/src/app/project/tag-retention/tag-retention.component.scss
- src/portal/src/global.scss
Solve the problem of overlapping the line due to newly created inline characters.
environment ： https://10.192.162.161
> Fix datagrid text overflow issue

- src/pkg/immutabletag/dao/immutable.go
- src/pkg/immutabletag/manager.go
> add empter result to list immutable rules

- tests/integration.sh
- tests/resources/Harbor-Util.robot
1, upload online installer and signature
2, inject npm registry server when to build offline
> upload online installer with drone

- src/portal/src/app/harbor-routing.module.ts
- src/portal/src/app/shared/about-dialog/about-dialog.component.html
- src/portal/src/app/shared/about-dialog/about-dialog.component.scss
> Fix version info in about dialog can not select and copy

- tests/integration.sh
- tests/resources/Harbor-Util.robot
> cherry pick upload online installer

- src/portal/lib/src/tag/tag.component.ts
- src/portal/src/global.scss
> FIx the tag list is not refreshed when the target refills the current repository when the retag is operated.

- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.html
- src/portal/lib/src/create-edit-endpoint/create-edit-endpoint.component.scss
- src/portal/lib/src/tag/tag.component.html
- src/portal/lib/src/tag/tag.component.scss
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.ts
1.modify input size
2. list tag . text align
3.modify webhook test 
10.192.162.161
> Fix ui issue about the third round test

- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Common.robot
Modify 2 points, 1st is add wait time right after scan all; 2nd is add name length for project name to avoid naming repeatly.
> Fix scan all test case

- tests/resources/Harbor-Util.robot
> enable build migrator in master

- src/portal/lib/src/endpoint/endpoint.component.html
- src/portal/lib/src/label/label.component.html
1.Fix #9936 
2.Temporary available env.: https://10.193.32.139:8081
> Fix filter bug for registries and labels datagrid

- CONTRIBUTING.md
> add coding style documentation

- make/photon/prepare/utils/configs.py
> fix(prepaire,clair): disable clair updaters when its interval is 0

- tests/integration.sh
- tests/resources/Harbor-Util.robot
> udpate base image to 1.10.0

- tests/resources/Harbor-Pages/Project-Members.robot
Add a big loop for keyword Go Into Project to make sure if project was not found, search it again
> Add a big loop for keyword Go Into Project

- src/portal/src/app/sign-in/sign-in.component.html
- src/portal/src/app/sign-in/sign-in.component.ts
Signed-off-by: Bastian Hofmann <bashofmann@gmail.com>
> Fix broken about dialog on sign in page

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/navigator/navigator.component.html
- src/portal/src/app/base/navigator/navigator.component.scss
- src/portal/src/app/base/navigator/navigator.component.ts
- src/portal/src/app/sign-in/sign-in.component.html
> Modify the style of language and modify variable name

- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
Make big loop effective by stop assert in keyword Retry Double Keywords When Error; 
> Modify keyword Go Into Project and Quota case

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/navigator/navigator.component.html
- src/portal/src/app/base/navigator/navigator.component.scss
- src/portal/src/app/base/navigator/navigator.component.ts
- src/portal/src/app/sign-in/sign-in.component.html
> [Cherry-pick#9971]Modify the style of language and modify variable name (9971)

- src/portal/src/app/app.module.ts
- src/portal/src/app/intercept-http.service.spec.ts
- src/portal/src/app/intercept-http.service.ts
> Resolve token expiration issues

- src/portal/src/app/app.module.ts
- src/portal/src/app/intercept-http.service.spec.ts
- src/portal/src/app/intercept-http.service.ts
> [Cherry-pick1.10]Reslove the token expired

- src/portal/src/app/app.module.ts
- src/portal/src/app/intercept-http.service.spec.ts
- src/portal/src/app/intercept-http.service.ts
> cherry1.9.4 Reslove the token expired

- src/portal/lib/src/config/vulnerability/vulnerability-config.component.html
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.spec.ts
- src/portal/lib/src/config/vulnerability/vulnerability-config.component.ts
- src/portal/src/app/project/tag-retention/tag-retention.component.ts
Fix #9891 
Env: https://10.161.67.1:8085
> Disable scan now button if no default scanner(cherry-pick #10032) 

- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.html
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.spec.ts
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.ts
Fix #9891
Env: https://10.161.67.1:8085
> Disable scan now button if no default scanner

- src/portal/src/app/project/tag-retention/tag-retention.component.ts
> Fix tag-retention ui bug(cherry-pick #10036)

- make/photon/prepare/utils/configs.py
> [Cherry pick]fix(prepaire,clair): disable clair updaters when its interval is 0

- src/portal/lib/src/replication/replication-tasks/replication-tasks.component.html
- src/replication/dao/execution.go
- src/replication/dao/execution_test.go
- src/replication/dao/models/execution.go
- src/replication/operation/execution/execution_test.go
- src/replication/operation/flow/stage.go
Cherry-pick the fix https://github.com/goharbor/harbor/pull/8981 into 1.9
> Use struct instead of pointer for the time to fix the timezone issue

- make/harbor.yml
- make/photon/prepare/g.py
- make/photon/prepare/utils/configs.py
- tools/migration/cfg/migrator_1_9_0/harbor.yml.jinja
All internal service and known internal hostname shuold add to no_proxy by default
> Add default domainname for no_proxy

- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Common.robot
Clair db is pre-populated, some clair test case need to updated.
> Remove clair cases

- API/harbor/swagger.yaml
- src/common/dao/repository.go
- src/portal/src/lib/components/repository-gridview/repository-gridview.component.html
- src/portal/src/lib/components/repository-gridview/repository-gridview.component.ts
1.Delete sort by number of tags ；
（The backend does not currently support this sorting method. Currently, the front-end sorting is used, but it is not accurate. You need to wait until the oci function is completed to complete this function.）
2.Modify the name sorting and filtering method to be back-end dominant；
3. Modify the pull_count sorting  method to be back-end dominant；
4.clear front-end dominant code about  sorting and filtering;
environment： https://10.161.148.123
fix #10080
> Modify the repository list sort and filter

- src/portal/lib/src/tag/tag-detail.component.ts
Fix bug: the package count will increase after clicking scan button
Env: https://10.161.67.1:8086
> Fix a bug in tag-detail page

- src/portal/src/app/account/account-settings/account-settings-modal.component.html
- src/portal/src/app/account/account-settings/account-settings-modal.component.spec.ts
> Test: add more ut in front end

- src/core/config/config.go
Fix bug when trying to get the external URL
> Fix bug when trying to get the external URL

- src/portal/src/lib/components/config/replication/replication-config.component.spec.ts
- src/portal/src/lib/components/config/system/system-settings.component.html
- src/portal/src/lib/components/config/system/system-settings.component.spec.ts
Here are the coverage reports for the new added spec files:
> Add more UI UT

- src/core/middlewares/vulnerable/handler.go
To make the message more friendly and readable for the end-user
> improve pulling vulnerable images warning message

- src/core/api/repository.go
Sort the tag before returning the list when calling API list tag API
> Sort the tag before returning the list when calling API

- make/photon/portal/Dockerfile
> fix(build): npm install with special endpoint

- src/core/middlewares/vulnerable/handler.go
To make the message more friendly and readable for the end-user
> [cherry-pick] improve pulling vulnerable images warning message

- src/portal/lib/src/project-policy-config/project-policy-config.component.html
> Improve ui for  project config page

- src/jobservice/job/impl/context.go
Closes #9300
Signed-off-by: liuxu <liuxu623@gmail.com>
> [Cherry pick]fix fatal error

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
- src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
- src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
- src/portal/src/app/config/scanner/config-scanner.component.html
- src/portal/src/app/config/scanner/config-scanner.component.scss
- src/portal/src/app/config/scanner/config-scanner.component.ts
- src/portal/src/app/config/scanner/config-scanner.service.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
New added parts:
UX:https://www.figma.com/file/0bSkyzvchcOCrwSWROIivtIb/Harbor-v1.9?node-id=1426%3A43663
Env.:https://10.161.67.1:8090
> Add links to view doc for scanners ui

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
- src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
- src/portal/src/app/base/harbor-shell/harbor-shell.component.ts
- src/portal/src/app/config/scanner/config-scanner.component.html
- src/portal/src/app/config/scanner/config-scanner.component.scss
- src/portal/src/app/config/scanner/config-scanner.component.ts
- src/portal/src/app/config/scanner/config-scanner.service.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/project-policy-config/project-policy-config.component.html
> Add links to view doc for scanners ui(cherry-pick #10220)

- tests/e2e-image/Dockerfile
- tests/e2e-image/dockerd-entrypoint.sh
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Helm-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Chartmuseum.robot
E2E image Dockerfile has lost control for several updates, so o add modifications back to the Dockerfile. 1. update  and docker-compose; 
2. Install helm and helm3.
3. dockerd-entrypoint.sh has been modify by commit image manually, so it should be updated.
> Maintain E2E image Dockerfile

- docs/migration_guide.md
Migration guild is a lit bit confusion
Add copy after migrate config file
> [doc] Update doc for migration

- tests/resources/Util.robot
> Modify robot keyword from press key to press keys

- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.html
- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.scss
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.html
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.scss
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.ts
- src/portal/src/lib/components/filter/filter.component.html
- src/portal/src/lib/components/filter/filter.component.ts
- src/portal/src/lib/components/image-name-input/image-name-input.component.html
- src/portal/src/lib/components/image-name-input/image-name-input.component.scss
- src/portal/src/lib/components/image-name-input/image-name-input.component.ts
- src/portal/src/lib/components/replication/replication.component.html
- src/portal/src/lib/components/replication/replication.component.ts
- src/portal/src/lib/components/tag/tag.component.html
- src/portal/src/lib/components/tag/tag.component.scss
1.Improve search function : The old search function did not work perfectly and would cause nightly  case failure sometime.
2. Improve css for cron-component , filter-component and image-name-input.component.
Env: https://10.161.79.96:8092
> Improve search function for replication and tags

- src/portal/src/app/account/sign-up/sign-up.component.html
- src/portal/src/app/account/sign-up/sign-up.component.spec.ts
> Remove duplicate ids

- api/harbor/swagger.yaml
> Fix syntax error in swagger.yaml

- .github/workflows/CI.yml
- make/common.sh
- make/photon/registry/Dockerfile
- src/core/api/api_test.go
- src/core/api/utils.go
- tests/coverage4gotest.sh
- tests/docker-compose.test.yml
- tests/pushimage.sh
- tests/travis/api_common_install.sh
- tests/travis/api_run.sh
- tests/travis/ui_ut_run.sh
- tests/travis/ut_install.sh
- tests/travis/ut_run.sh
In order to replace travis.
Implement 5 CI jobs
- UTTEST
- APITEST_DB
- APITEST_LDAP
- OFFLINE
- UI_UT
> enhance[cicd] introduce github action for CICD

- tests/e2e-image/Dockerfile
- tests/resources/Harbor-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group0-Util/notary-push-image.sh
- tests/robot-cases/Group0-Util/notary-remove-image-signature.expect
- tests/robot-cases/Group1-Nightly/Notary.robot
1. Update E2E image Dockerfile for adding notary CLI;
2. Add test case of remove notary signature.
> Add notary remove signature test case in nightly

- tests/resources/Harbor-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group0-Util/notary-push-image.sh
- tests/robot-cases/Group0-Util/notary-remove-image-signature.expect
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
> Change parameter image to optional

- src/portal/src/lib/components/repository-gridview/repository-gridview.component.html
- src/portal/src/lib/components/repository-gridview/repository-gridview.component.spec.ts
- src/portal/src/lib/components/repository-gridview/repository-gridview.component.ts
Env: https://10.161.79.96:8083
> Improve repo datagrid search function

- src/server/middleware/middleware.go
- src/server/v2.0/registry/catalog/catalog.go
- src/server/v2.0/registry/handler.go
- src/server/v2.0/registry/manifest/manifest.go
- src/server/v2.0/registry/tag/tag.go
This commit adds several handlers to handle registry requests, some of the handlers aren't implemented yet, will be done later
> Add the registry handlers without the implementation detail

- tests/resources/Harbor-Pages/Project.robot
> Refect keyword of Go Into Reop

- src/portal/src/app/shared/session-user.ts
- src/portal/src/app/shared/session.service.ts
- src/portal/src/app/shared/session.viewmodel.factory.spec.ts
- src/portal/src/app/shared/session.viewmodel.factory.ts
- src/portal/src/app/user/user.component.ts
- src/portal/src/app/user/user.ts
> Modify system admin role from has_admin_role to admin_role_in_auth and sysadmin_flag

- src/portal/lib/src/repository-gridview/repository-gridview.component.html
- src/portal/lib/src/repository-gridview/repository-gridview.component.spec.ts
- src/portal/lib/src/repository-gridview/repository-gridview.component.ts
- src/portal/src/app/base/global-search/global-search.component.ts
- src/portal/src/app/base/global-search/search-result.component.html
- src/portal/src/app/base/global-search/search-result.component.ts
> Improve global search and repo datagrid search function(cherry-pick #10292 and #10143)

- tests/robot-cases/Group3-Upgrade/verify.robot
> Remove whitelist verifcation since it's not ready

- tests/resources/Harbor-Pages/Project.robot
> [Cherry-pick to 1.9.0] Refect keyword of Go Into Reop

- tests/resources/Harbor-Pages/Project.robot
> [Cherry-pick to 1.10.0] Refect keyword of Go Into Reop

- tests/resources/Harbor-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group0-Util/notary-push-image.sh
- tests/robot-cases/Group0-Util/notary-remove-image-signature.expect
- tests/robot-cases/Group1-Nightly/Common.robot
> Notary test failed in Helm Pipeline

- tests/resources/Harbor-Pages/Administration-Users.robot
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/HomePage.robot
- tests/resources/Harbor-Pages/LDAP-Mode.robot
- tests/resources/Harbor-Pages/Project-Config.robot
- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Harbor-Pages/Project-Repository_Elements.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/UserProfile.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/LDAP.robot
- tests/robot-cases/Group1-Nightly/Nightly.robot
- tests/robot-cases/Group1-Nightly/UAA.robot
> Replace keyword without waiting to one which had waiting

- tests/resources/Harbor-Pages/Configuration.robot
> Refresh project quotas list at regular time

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/lib/components/config/project-quotas/edit-project-quotas/edit-project-quotas.component.html
- src/portal/src/lib/components/config/project-quotas/edit-project-quotas/edit-project-quotas.component.spec.ts
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.html
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.spec.ts
Coverage Report:
Total:
Respective:
> Add more UT for project-quota-component

- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Util.robot
- tests/resources/TestCaseBody.robot
- tests/resources/Util.robot
- tests/robot-cases/Group0-BAT/BAT.robot
> Repull image when error

- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Harbor-Pages/Project-Webhooks.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Robot_Account.robot
> add checkpoint and retry for click add member button

- tests/resources/Harbor-Pages/Project-Tag-Retention.robot
- tests/resources/Harbor-Pages/Project-Tag-Retention_Elements.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add nightly test case for tag immutability

- src/portal/src/lib/components/confirmation-dialog/confirmation-dialog.component.spec.ts
- src/portal/src/lib/components/operation/operation.component.spec.ts
- src/portal/src/lib/components/operation/operation.component.ts
- src/portal/src/lib/components/operation/operation.service.spec.ts
> Add more UT

- tests/resources/Harbor-Pages/Replication.robot
> Add retry when fail to find replication

- src/api/artifact/abstractor/abstractor.go
- src/api/artifact/abstractor/abstractor_test.go
- src/api/artifact/abstractor/blob/cache.go
- src/api/artifact/abstractor/blob/fetcher.go
- src/api/artifact/abstractor/resolver/chart/chart.go
- src/api/artifact/abstractor/resolver/image/index.go
- src/api/artifact/abstractor/resolver/image/manifest_v1.go
- src/api/artifact/abstractor/resolver/image/manifest_v2.go
- src/api/artifact/abstractor/resolver/image/manifest_v2_test.go
- src/api/artifact/abstractor/resolver/resolver.go
- src/api/artifact/abstractor/resolver/resolver_test.go
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/testing/api/artifact/abstractor/blob/fetcher.go
1. Define the interface for artifact abstractor and resolver
2. Implement the artifact abstractor
3. Implement the resolver for image with manifest v2
> Implement the artifact abstractor and resolver

- src/replication/adapter/awsecr/adapter.go
fix #10264 for 1.10.x
aws ecr didn't implement standard oci delete manifest api, that we have to call its sdk
> (cherry-pick): aws ecr delete image 1.10.x

- src/replication/adapter/awsecr/adapter.go
fix #10264 for master
aws ecr didn't implement standard oci delete manifest api, that we have to call its sdk
> (cherry-pick)Ecr delete image master

- tests/resources/Harbor-Pages/ToolKit.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add retry for prject list display

- src/portal/src/app/project/project.component.html
- src/portal/src/app/project/project.component.spec.ts
- src/portal/src/app/project/project.component.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/tag-retention.component.ts
- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
- src/portal/src/i18n/lang/zh-cn-lang.json
Env.:https://10.161.79.96:8081
> Improve tag-retention and project search function

- src/portal/package-lock.json
- src/portal/package.json
- src/portal/server/README.md
- src/portal/server/controllers/index.ts
- src/portal/server/controllers/scanners.ts
- src/portal/server/src/mock-api.ts
- src/portal/server/tsconfig.json
1. Add express module , so we can quickly set up a Api-server from which we can get mocked data
> Add express module

- src/server/middleware/middleware.go
- src/server/middleware/middleware_test.go
Provide a util function to apply middlewares to handler
> Provide a util function to apply middlewares to handler

- .gitignore
- src/portal/package-lock.json
- src/portal/package.json
- src/portal/scripts/convert-yaml-to-json.js
- src/portal/scripts/delete-swagger-json.js
To automatically generate models and services with swagger.yaml
> Add ng-swagger-gen to automatically generate models and services with swagger.yaml

- src/api/artifact/abstractor/resolver/image/manifest_v1.go
- src/api/artifact/abstractor/resolver/image/manifest_v1_test.go
- src/api/artifact/abstractor/resolver/image/manifest_v2.go
The manifest v1 image resolver populates the architecture info into the artifact
> Implement the manifest v1 image resolver

- src/internal/error/errors.go
- src/server/middleware/readonly.go
- src/server/middleware/readonly_test.go
- src/server/registry/blob/blob.go
- src/server/registry/blob/blob_test.go
- src/server/registry/handler.go
> move readonly middleware to new v2 handler

- tests/e2e-image/Dockerfile
- tests/resources/Harbor-Util.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group0-Util/notary-push-image.sh
- tests/robot-cases/Group0-Util/notary-remove-image-signature.expect
- tests/robot-cases/Group1-Nightly/Notary.robot
Add notary remove signature test case in nightly
1. Update E2E image Dockerfile for adding notary CLI;
2. Add test case of remove notary signature.
> [Cherry-pick 1.10.0]Add notary remove signature test case in nightly

- src/api/artifact/abstractor/resolver/image/index.go
- src/api/artifact/abstractor/resolver/image/index_test.go
The index/manifest list image resolver populates the references of the artifact
> Implement the index/manifest list image resolver

- .github/workflows/CI.yml
- tests/apitests/python/test_robot_account.py
- tests/apitests/python/test_scan_all_images.py
sometimes ut failed in github action check with docker push timeout, it seems only 30s limit, so try use a smaller image
and fix the git fetch depth problem, that if two pr merged at almost same time
Change-Id: Ie8f365e7271bfda24ae965aaca0e55d1099c1d68
> feat(cicd) use a smaller docker image for test

- src/core/filter/orm.go
- src/core/filter/sessionchecker.go
- src/internal/orm/orm.go
- src/internal/orm/orm_test.go
- src/internal/orm/query.go
- src/pkg/artifact/dao/dao.go
- src/pkg/artifact/dao/dao_test.go
- src/pkg/repository/dao/dao.go
- src/pkg/repository/dao/dao_test.go
- src/pkg/retention/launcher.go
- src/pkg/tag/dao/dao.go
- src/pkg/tag/dao/dao_test.go
This commit updates the dao methods with the ormer got from context
> Get the ormer from context instead of creating a new one

- src/replication/adapter/huawei/huawei_adapter.go
- src/replication/adapter/huawei/image_registry.go
Issue: https://github.com/goharbor/harbor/issues/9874
> fix(replication): huawei adapter multi authorization

- .github/workflows/CI.yml
- tests/travis/ut_run.sh
stop using travis, instead by github action
> feat(cicd):stop use travis

- tests/robot-cases/Group0-Util/notary-remove-image-signature.expect
> Add expect file from linux OS

- src/server/registry/catalog/catalog.go
- src/server/registry/catalog/catalog_test.go
- src/server/registry/handler.go
- src/server/registry/tag/tag.go
- src/server/registry/tag/tag_test.go
- src/server/registry/util/util.go
- src/server/registry/util/util_test.go
> add code for catalog and list tag API

- src/internal/error/errors.go
- src/internal/error/errors_test.go
- src/server/error/error.go
implement SendError for BaseAPI handler
> feat(swagger): implement SendError for BaseAPI handler

- src/server/middleware/immutable/deletemf.go
- src/server/middleware/immutable/deletemf_test.go
- src/server/middleware/immutable/error.go
- src/server/middleware/immutable/pushmf.go
- src/server/middleware/immutable/pushmf_test.go
- src/server/registry/handler.go
> add immutable tag middleware into new v2 handler

- src/api/artifact/abstractor/abstractor_test.go
- src/api/artifact/abstractor/resolver/chart/chart.go
- src/api/artifact/abstractor/resolver/chart/chart_test.go
- src/api/artifact/abstractor/resolver/image/index.go
- src/api/artifact/abstractor/resolver/image/index_test.go
- src/api/artifact/abstractor/resolver/image/manifest_v1.go
- src/api/artifact/abstractor/resolver/image/manifest_v1_test.go
- src/api/artifact/abstractor/resolver/image/manifest_v2.go
- src/api/artifact/abstractor/resolver/image/manifest_v2_test.go
- src/api/artifact/abstractor/resolver/resolver_test.go
- src/api/artifact/controller.go
Implement the resolver for helm chart
> Implement the resolver for helm chart

- src/core/api/api_test.go
- src/core/api/log.go
- src/core/api/log_test.go
> Remove project logs access for Limited Guest role

- api/v2.0/swagger.yaml
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/artifact/model.go
- src/pkg/artifact/model.go
- src/pkg/repository/manager.go
- src/pkg/repository/manager_test.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/base.go
- src/server/v2.0/handler/handler.go
- src/testing/artifact_manager.go
- src/testing/repository_manager.go
- src/testing/tag_manager.go
Implement the listing artifact API
> Implement the listing artifact API

- src/core/main.go
- src/server/registry/handler.go
- src/server/registry/manifest/manifest.go
- src/server/registry/route.go
- src/server/router/router.go
- src/server/router/router_test.go
- src/server/server.go
- src/server/v1.0/route/route.go
- src/server/v2.0/route/route.go
Wrap the beego router and provide a unified view for users to register routes
> Wrap the beego router and provide a unified view for users to register routes

- src/api/artifact/abstractor/blob/fetcher.go
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/repository/controller.go
- src/api/repository/controller_test.go
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/server/registry/error/error.go
- src/server/registry/handler.go
- src/server/registry/manifest/manifest.go
- src/server/registry/route.go
- src/testing/project_manager.go
Implement the get/delete handler for registry API
> Implement the get/delete handler for registry API

- make/photon/portal/Dockerfile
- src/portal/scripts/convert-yaml-to-json.js
> Fix postinstall script in Docker

- src/server/v2.0/handler/base.go
Add `HasPermission` and `HasProjectPermission` in `BaseAPI`
> feat(api,permission): add HasPermission, HasProjectPermission in BaseAPI

- api/v2.0/swagger.yaml
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/go.mod
- src/server/v2.0/handler/artifact.go
Implement APIs:
1. Get artifact
2. Delete artifact
3. Create tag
4. Delete tag
> Implement artifact/tag related API

- src/server/registry/tag.go
- src/testing/api/artifact/controller.go
Use ListTags instead in the registry tag listing handler
> Update the method called by registry handler

- tests/apitests/python/test_project_quota.py
- tests/apitests/python/test_robot_account.py
- tests/resources/Helm-Util.robot
- tests/resources/TestCaseBody.robot
> Fix description of test in robot account API test

- src/pkg/robot/controller_test.go
- src/pkg/robot/dao/robot.go
Update the query FuzzyMatch when to list robot accounts per project
> fix issue on listing robot accounts

- api/v2.0/swagger.yaml
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/artifact/model.go
- src/core/api/repository.go
- src/core/middlewares/interceptor/immutable/deletemf.go
- src/core/middlewares/interceptor/immutable/pushmf.go
- src/pkg/immutabletag/match/matcher.go
- src/pkg/immutabletag/match/rule/match.go
- src/pkg/immutabletag/match/rule/match_test.go
- src/pkg/retention/policy/action/performer.go
- src/server/middleware/immutable/deletemf.go
- src/server/middleware/immutable/pushmf.go
- src/testing/pkg/immutabletag/matcher.go
> set the immutable status on getting/listting tag

- src/pkg/robot/controller_test.go
- src/pkg/robot/dao/robot.go
Update the query FuzzyMatch when to list robot accounts per project
> [cherry-pick]fix issue on listing robot accounts

- api/v2.0/swagger.yaml
- src/common/rbac/const.go
- src/common/rbac/project/util.go
- src/common/rbac/project/visitor_role.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/base.go
Add permission check for artifact related APIs
> Add permission check for artifact related APIs

- api/v2.0/swagger.yaml
- src/api/artifact/controller.go
- src/api/repository/controller.go
- src/api/repository/controller_test.go
- src/server/v2.0/handler/handler.go
- src/server/v2.0/handler/repository.go
- src/testing/api/repository/controller.go
Implement repository deletion API based on the new design
> Implement repository deletion API

- src/server/middleware/immutable/deletemf.go
- src/server/middleware/immutable/pushmf.go
- src/server/middleware/util.go
> Use controller rather than manager in the API handler and middleware

- api/v2.0/swagger.yaml
- src/pkg/artifact/dao/dao.go
- src/pkg/artifact/dao/dao_test.go
- src/pkg/q/query.go
- src/pkg/q/query_test.go
- src/server/v2.0/handler/artifact.go
Specify the query string "tags=NOT_NULL" to the listing artifact API to only return the tagged artifacts
> Add query string to listing artifact API to support specify only show the tagged artifacts

- src/core/api/api_test.go
- src/core/api/log.go
- src/core/api/log_test.go
Signed-off-by: Mark Huang <mhuang@pivotal.io>
> [Cherry pick]Hide projects in global logs where user has limited guest role

- src/server/registry/catalog.go
- src/server/registry/catalog_test.go
- src/server/registry/tag.go
- src/server/registry/tag_test.go
> fix catalog pagination issue

- src/server/middleware/v2auth/auth.go
- src/server/middleware/v2auth/auth_test.go
> Fix nilpointer issue in v2 auth middleware

- src/portal/scripts/convert-yaml-to-json.js
> UI should use relative path for back-end APIs

- src/common/utils/registry/auth/authorizer.go
- src/common/utils/registry/auth/nullauthorizer.go
- src/replication/adapter/native/adapter.go
- tests/robot-cases/Group0-BAT/API_DB.robot
This commit introduces a new wrapper authorizer which can authorize the request according to the auth scheme automatically
> Do enhancement for the registry authorizer

- docs/1.10/administration/configure-project-quotas.md
- docs/1.10/administration/garbage-collection.md
- docs/1.10/administration/general-settings.md
@jonasrosland @michmike can you please approve?
> Fixed image links

- Makefile
- make/prepare
fix #10569 
The VERSIONTAG in prepare script is not set in install.sh, so revert to old code, fix this when package the installer
> fix(feat) fix prepare version in installer

- api/v2.0/swagger.yaml
> Improve swagger.yaml

- api/v2.0/swagger.yaml
- make/migrations/postgresql/0030_1.11.0_schema.up.sql
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/artifact/model.go
- src/common/rbac/const.go
- src/common/rbac/project/visitor_role.go
- src/pkg/artifact/dao/dao.go
- src/pkg/label/dao.go
- src/pkg/label/dao_test.go
- src/pkg/label/manager.go
- src/pkg/label/manager_test.go
- src/pkg/label/model.go
- src/pkg/tag/dao/dao.go
- src/server/v2.0/handler/artifact.go
- src/testing/api/artifact/controller.go
- src/testing/pkg/label/manager.go
This commit add supporting for adding/removing label to/from artifacts and populates labels when listing artifacts
> Support add/remove label to/from artifact

- .github/codecov-ut-config/codecov.yml
- .github/workflows/CI.yml
> Fix UT coverage report uploading

- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/artifact/model.go
- src/pkg/artifact/dao/dao.go
- src/pkg/artifact/dao/dao_test.go
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/pkg/artifact/model.go
- src/pkg/tag/dao/dao.go
- src/pkg/tag/dao/dao_test.go
- src/pkg/tag/manager.go
- src/pkg/tag/manager_test.go
- src/pkg/tag/model/tag/model.go
- src/testing/pkg/artifact/manager.go
- src/testing/pkg/tag/manager.go
Delete the child artifacts along with the parent when deleting an artifact
> Refactor the logic of deleting artifact

- api/v2.0/swagger.yaml
> update the enum value for chart on api get the addition

- docs/1.10/install-config/harbor-ha-helm.md
This PR removes a line left over from a prior merge operation.
> Remove errant merge line

- api/v2.0/swagger.yaml
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/repository/controller.go
- src/api/repository/controller_test.go
- src/api/scan/all_handler.go
- src/common/models/repo.go
- src/go.mod
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/pkg/repository/manager.go
- src/pkg/repository/manager_test.go
- src/pkg/retention/launcher.go
- src/pkg/retention/launcher_test.go
- src/pkg/tag/manager.go
- src/pkg/tag/manager_test.go
- src/server/registry/catalog.go
- src/server/registry/catalog_test.go
- src/server/registry/tag.go
- src/server/registry/tag_test.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/repository.go
- src/testing/api/artifact/controller.go
- src/testing/api/repository/controller.go
- src/testing/pkg/artifact/manager.go
- src/testing/pkg/repository/manager.go
- src/testing/pkg/tag/manager.go
Implement delete/update repository API
> Implement delete/update repository API

- api/v2.0/swagger.yaml
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/common/rbac/project/visitor_role.go
- src/pkg/registry/client.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/artifact_test.go
- src/testing/api/artifact/controller.go
- src/testing/pkg/registry/client.go
Copy artifact into the repository from the specified artifact
> Implement copy artifact API

- Makefile
- tests/apitests/python/library/artifact.py
- tests/apitests/python/library/base.py
> Build python swagger client for V2.0

- src/api/scan/base_controller.go
Harbor v2.0 has changed to use basic auth to pull image so remove bearer
token support for scan job
> refactor(scan,auth): remove bearer token auth support for scan job

- docs/1.10/working-with-projects/using-api-explorer/_index.html.md
- docs/1.10/working-with-projects/working-with-images/_index.html.md
Hopefully this will allow sub-subtopics to show up in the Working in Projects section.
> Adjusted weightings for Working with Projects

- src/api/artifact/abstractor/abstractor.go
- src/api/artifact/abstractor/abstractor_test.go
- src/api/artifact/abstractor/resolver/cnab/cnab.go
- src/api/artifact/abstractor/resolver/cnab/cnab_test.go
- src/api/artifact/controller.go
- src/api/artifact/descriptor/descriptor.go
- src/api/artifact/descriptor/descriptor_test.go
- src/pkg/distribution/distribution.go
- src/server/router/router.go
- src/vendor/github.com/docker/distribution/manifest/ocischema/builder.go
- src/vendor/github.com/docker/distribution/manifest/ocischema/manifest.go
- src/vendor/modules.txt
This commit introduces a new resolver to resolver metadata for CNAB
> Implement the resolver for CNAB

- Makefile
- tests/apitests/python/library/artifact.py
- tests/apitests/python/library/base.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/test_add_sys_label_to_tag.py
- tests/apitests/python/test_copy_artifact_outside_project.py
- tests/apitests/python/test_del_repo.py
- tests/apitests/python/test_garbage_collection.py
- tests/apitests/python/test_manage_project_member.py
- tests/apitests/python/test_project_level_policy_content_trust.py
- tests/apitests/python/test_retention.py
- tests/apitests/python/test_robot_account.py
- tests/apitests/python/test_sign_image.py
- tests/robot-cases/Group0-BAT/API_DB.robot
> Upgrade repository API tests to V2.0

- .github/workflows/CI.yml
- Makefile
- make/photon/prepare/Dockerfile.base
- make/photon/redis/Dockerfile.base
- tests/travis/ut_run.sh
- remove CI checkout depth, make sure github action checkout successful every time
- fix pipenv install problem
- add pull_base_docker task in Makefile
- remove useless coverall
> feat(cicd) fix some build problem

- make/photon/core/Dockerfile
- make/photon/prepare/templates/registry/config.yml.jinja
Update config.yaml.jinja to remove notification
Update core/Dockerfile to change the health check url.
> Remove registry notification and change core health check url

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/repository.go
Implement the API to get the specified repository
> Implement the API to get the specified repository

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/artifact.go
> feat(scan): add scan API in v2.0

- src/core/middlewares/middlewares.go
- src/core/middlewares/middlewares_test.go
- src/server/middleware/readonly/readonly.go
- src/server/registry/route.go
> add readonly to beego middleware

- api/v2.0/swagger.yaml
Fix bug of swagger for repository API
> Fix bug of swagger for repository API

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact/artifact-common-properties/artifact-common-properties.component.html
- src/portal/src/app/project/repository/artifact/artifact-summary.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
> Improve artifact

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/additions.service.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-additions.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-additions.component.scss
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-additions.component.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.scss
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.spec.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/dependencies/dependencies.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/dependencies/dependencies.component.spec.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/dependencies/dependencies.component.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/models.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/summary/summary.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/summary/summary.component.scss
- src/portal/src/app/project/repository/artifact/artifact-additions/summary/summary.component.spec.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/summary/summary.component.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/values/values.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/values/values.component.scss
- src/portal/src/app/project/repository/artifact/artifact-additions/values/values.component.spec.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/values/values.component.ts
- src/portal/src/app/project/repository/artifact/artifact-summary.component.html
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/app/project/repository/vulnerability-scanning/result-bar-chart.component.spec.ts
- src/portal/src/app/project/repository/vulnerability-scanning/result-bar-chart.component.ts
- src/portal/src/lib/services/scanning.service.ts
Env.: https://10.161.79.96:8081
> Fix scanning function

- src/chartserver/handler_manipulation.go
- src/chartserver/handler_proxy_traffic_test.go
- src/chartserver/reverse_proxy.go
- src/chartserver/reverse_proxy_test.go
- src/common/api/base.go
- src/core/api/chart_label_test.go
- src/core/api/chart_repository.go
- src/core/api/chart_repository_test.go
- src/core/api/harborapi_test.go
- src/core/filter/security.go
- src/core/middlewares/chart/builder.go
- src/core/middlewares/chart/handler_test.go
- src/pkg/clients/core/chart.go
- src/replication/adapter/harbor/adapter.go
- src/replication/adapter/harbor/chart_registry.go
- src/replication/adapter/harbor/chart_registry_test.go
> Fix URL issue introduced by api version

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/base.go
- src/server/v2.0/handler/base_test.go
- src/server/v2.0/handler/repository.go
Set the "Link" and "location" header
> Set the "Link" and "location" header

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/common/dao/base.go
- src/common/dao/pgsql.go
- src/common/dao/project.go
- src/common/utils/test/database.go
- src/core/main.go
- src/migration/artifact.go
- src/migration/migration.go
- src/pkg/artifact/manager.go
- src/pkg/artifact/manager_test.go
- src/testing/pkg/artifact/manager.go
Abstract extra attributes and annotations for artifacts stored in database
> Migrate artifact data in 2.0

- .github/workflows/CI.yml
- Makefile
upgrade github action checkout@v2
enhance go_check order to make it fail earlier
> upgrade github action checkout@v2

- tests/apitests/python/library/base.py
- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/test_push_index_by_docker_manifest.py
- tests/apitests/python/update_docker_cfg.sh
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/robot-cases/Group0-BAT/API_LDAP.robot
> Add API test case of pushing index by docker manifest

- src/portal/src/app/intercept-http.service.spec.ts
- src/portal/src/app/intercept-http.service.ts
> Fix xsrf error status bug when after beego update

- src/pkg/notification/model/const.go
- src/pkg/notification/notification.go
- src/pkg/notifier/handler/notification/slack_handler.go
- src/pkg/notifier/handler/notification/slack_handler_test.go
- src/pkg/notifier/model/topic.go
- src/pkg/notifier/topic/topics.go
> add support slack in webhook

- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/repository/controller.go
- src/api/repository/controller_test.go
- src/api/tag/controller.go
- src/api/tag/controller_test.go
- src/testing/lib/orm/orm.go
More detail: // https://www.postgresql.org/message-id/002e01c04da9%24a8f95c20%2425efe6c1%40lasting.ro
> Fix transaction issue

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list.component.html
- src/portal/src/app/project/repository/artifact/artifact.ts
- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/image-name-input/image-name-input.component.ts
- src/portal/src/lib/utils/shared/shared.utils.ts
> Filter artifact by type/tag  and change error setting

- src/portal/src/app/intercept-http.service.spec.ts
- src/portal/src/app/intercept-http.service.ts
> Fix xsrf error status bug when after beego update 1.10

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
> Improve scan funciton

- make/photon/portal/Dockerfile
- src/portal/src/app/dev-center/dev-center.component.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/values/values.component.ts
- src/portal/src/app/project/repository/artifact/artifact-common-properties/artifact-common-properties.component.ts
- src/portal/src/app/project/repository/vulnerability-scanning/result-bar-chart.component.ts
- src/portal/src/lib/utils/utils.ts
Fix #10634 
Env.:https://10.161.79.96:8083
> Fix Api cennter

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Env: https://10.161.79.96:8085
> Add new status "scan unsupported" for artifact list

- .github/workflows/CI.yml
- tests/apitests/python/library/helm.py
- tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
- tests/robot-cases/Group0-BAT/API_DB.robot
Please reference issue: #10935 
Fixed issue: #10762,#10763
> Add API test python script - Push chart by Helm3 registry/chart CLI

- api/v2.0/swagger.yaml
- src/internal/orm/query.go
- src/internal/orm/query_test.go
- src/pkg/blob/dao/dao.go
- src/pkg/blob/dao/dao_test.go
- src/pkg/blob/manager.go
- src/pkg/q/builder.go
- src/pkg/q/builder_test.go
- src/pkg/q/query.go
- src/server/v2.0/handler/repository.go
This commit defines the API query string format and provides the builders to build query string to query model
> Implement query string builder

- make/photon/prepare/templates/jobservice/env.jinja
- src/core/api/reg_gc.go
- src/jobservice/job/impl/context.go
- src/jobservice/job/impl/context_test.go
- src/jobservice/job/impl/gc/garbage_collection.go
- src/pkg/artifactrash/dao/dao.go
- src/pkg/artifactrash/dao/dao_test.go
1, enable dao test for artifact trash
2, set default flush trash table to false
3, hanlder empty parameter in API call
4, add registry auth info into jobservice container
> Fix gc issue on clean the artifact trash

- src/api/preheat/controller.go
- src/api/preheat/controllor_test.go
- src/pkg/p2p/preheat/dao/history/storage.go
- src/pkg/p2p/preheat/dao/history/storage_redis.go
- src/pkg/p2p/preheat/dao/instance/storage.go
- src/pkg/p2p/preheat/dao/instance/storage_redis.go
- src/pkg/p2p/preheat/dao/instance/storage_redis_test.go
- src/pkg/p2p/preheat/dao/models/extension_test.go
- src/pkg/p2p/preheat/dao/models/extensions.go
- src/pkg/p2p/preheat/dao/utils/redis.go
- src/testing/pkg/p2p/preheat/dao/storage.go
Signed-off-by: dechen <xxyydream@gmail.com>
> Add unit tests to preheat controller

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
1, loop each access log, change to resource/resource_type, and insert into audit log
2, loop each first push operation, change it to create repository and insert into audit log.
> add sql for migrating access log

- src/replication/adapter/harbor/adapter.go
- src/replication/adapter/harbor/adapter_test.go
- src/replication/filter/artifact.go
- src/replication/model/policy.go
- src/replication/model/resource.go
- src/replication/operation/flow/stage.go
- src/replication/transfer/image/transfer.go
Provide the resource type filter for users to choose when replicating from harbor to other registries
> Make replication work with new artifact(phase 2)

- Makefile
- tests/resources/Harbor-Util.robot
Package trivy adapter image into offline image and ship dev to hub
> add trivy into offline/online package

- README.md
> use codecov badge in README

- api/v2.0/swagger.yaml
- src/pkg/q/builder.go
- src/pkg/q/builder_test.go
- src/server/v2.0/handler/artifact.go
- src/server/v2.0/handler/base.go
- src/server/v2.0/handler/base_test.go
- src/server/v2.0/handler/repository.go
Accept the pagination information in the separated query string
> Accept the pagination information in the separated query string

- tests/ci/api_common_install.sh
feat(ci) enable trivy in CI test
> feat(ci) enable trivy in CI test

- src/pkg/artifactselector/candidate.go
- src/pkg/retention/job.go
add webhook for deleted artifacts
> feature(tag_retention) add webhook for deleted artifacts

- api/v2.0/legacy_swagger.yaml
- tests/apitests/python/library/system.py
- tests/robot-cases/Group0-BAT/API_DB.robot
> enable garbage colloection api test case

- src/replication/adapter/aliacr/adapter.go
- src/replication/adapter/aliacr/types.go
#10331 
Signed-off-by: 慕薇疯魔 <kfanjian@gmail.com>
> FIX: AliACR Provider.

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/config/gc/gc.component.html
- src/portal/src/lib/components/config/gc/gc.component.scss
- src/portal/src/lib/components/config/gc/gc.component.ts
- src/portal/src/lib/components/config/gc/gc.const.ts
- src/portal/src/lib/components/config/gc/gc.service.ts
Fix #10919
Env.：https://10.161.79.96:8086
> Add new parameter for GC page

- src/portal/src/app/project/robot-account/add-robot/add-robot.component.html
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.scss
- src/portal/src/app/project/robot-account/add-robot/add-robot.component.ts
- src/portal/src/app/project/robot-account/robot-account.component.html
- src/portal/src/app/project/robot-account/robot-account.service.ts
- src/portal/src/app/project/robot-account/robot.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Env.:https://10.161.79.96:8081
> Improve UI for add robot page

- tests/apitests/python/test_project_quota.py
- tests/apitests/python/testutils.py
- tests/robot-cases/Group0-BAT/API_DB.robot
enable quota test case in API robot
> test(quota): enable quota test case in API robot

- .github/stale.yml
> Update stale.yml to for near future releases

- api/v2.0/swagger.yaml
- src/pkg/p2p/preheat/dao/history/storage_redis.go
- src/server/v2.0/handler/preheat.go
- tests/robot-cases/Group0-BAT/API_DB.robot
Signed-off-by: dechen <xxyydream@gmail.com>
> Implement pagination and query for preheat list apis

- src/common/api/base.go
- src/server/error/error.go
- src/server/error/error_test.go
- tests/apitests/python/test_edit_project_creation.py
United error response format for management APIs (legacy and v2.0 APIs)
> United error response format for management APIs (legacy and v2.0 APIs)

- docs/1.10/README.md
- docs/1.10/build-customize-contribute/e2e_api_python_based_scripting_guide.md
> Add doc for e2e API scripting guide

- tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
- tests/robot-cases/Group0-BAT/API_DB.robot
> Add verfication for helm API test

- src/server/middleware/csrf/csrf.go
- src/server/middleware/csrf/csrf_test.go
> make Secure flag of CSRF cookie adapt to config

- src/pkg/chart/operator.go
Fix bug when reading the readme.md of helm chart
> Fix bug when reading the readme.md of helm chart

- api/v2.0/legacy_swagger.yaml
- src/core/api/search.go
Change tag count to artifact count in search result
> Change tag count to artifact count in search result

- src/pkg/registry/auth/bearer/cache.go
- src/pkg/registry/auth/bearer/cache_test.go
Check expired or not when getting token from cache
> Check expired or not when getting token from cache

- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
> Fix: fix logrotate is dir issue

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact.ts
- src/portal/src/app/project/repository/repository-gridview.component.ts
> [OCI] Artifact filter params changes in ui

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/log/recent-log.component.html
- src/portal/src/lib/components/log/recent-log.component.spec.ts
- src/portal/src/lib/components/log/recent-log.component.ts
- src/portal/src/lib/services/permission.service.ts
1.Swith to new API for recent log page 
2.Improve usage for permission API(avoid multiple request at one time)
Env.:  https://10.161.79.96:8082
> Swith to new API for recent log page

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/handler.go
- src/server/v2.0/handler/project.go
use audit log api to get project logs
> update project logs api to v2.0

- make/harbor.yml.tmpl
- make/photon/prepare/g.py
- make/photon/prepare/templates/trivy-adapter/env.jinja
> chore(trivy): Allow configuring HTTP(S) proxy

- tests/apitests/python/library/artifact.py
- tests/apitests/python/test_create_delete_tag.py
- tests/robot-cases/Group0-BAT/API_DB.robot
Add create/delete tag API test case
> Add create/delete tag API test case

- src/api/preheat/controller.go
- src/api/preheat/controllor_test.go
- src/pkg/p2p/preheat/provider/driver.go
- src/pkg/p2p/preheat/provider/factory.go
- src/pkg/p2p/preheat/provider/known_drivers.go
- src/pkg/p2p/preheat/provider/known_drivers_test.go
- src/pkg/p2p/preheat/provider/kraken.go
tested.
kraken endpoint is 59.111.92.135:15005 .
> add support kraken preheat

- src/api/blob/controller.go
- src/api/event/handler/auditlog/auditlog_test.go
- src/api/quota/controller.go
- src/common/utils/log/context.go
- src/common/utils/log/logger.go
- src/common/utils/log/logger_test.go
- src/core/middlewares/middlewares.go
- src/server/middleware/blob/copy_artifact.go
- src/server/middleware/blob/post_initiate_blob_upload.go
- src/server/middleware/blob/put_blob_upload.go
- src/server/middleware/blob/put_manifest.go
- src/server/middleware/log/log.go
- src/server/middleware/log/log_test.go
- src/server/middleware/quota/copy_artifact.go
- src/server/middleware/quota/post_initiate_blob_upload.go
- src/server/middleware/quota/put_blob_upload.go
- src/server/middleware/quota/put_manifest.go
- src/server/middleware/quota/quota.go
Track request id in the log message.
> feat(log): track request id in the log message

- src/api/event/handler/webhook/scan/delete.go
> Fix delete scan report on deleting artifact

- .github/workflows/CI.yml
- tests/apitests/python/library/artifact.py
- tests/apitests/python/library/base.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/library/scan.py
- tests/apitests/python/test_scan_image_artifact.py
- tests/apitests/python/test_system_level_scan_all.py
- tests/ci/api_common_install.sh
- tests/robot-cases/Group0-BAT/API_DB.robot
> Modify API test for scan image since harbor v2 API presented

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/project/repository/repository-gridview.component.spec.ts
- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.html
- src/portal/src/app/shared/list-repository-ro/list-repository-ro.component.html
- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.html
1. search result show artifact count
2. replication shows changes both to all
3. fix delete bug when delete some artifact
> [OCI] changes some show words

- api/v2.0/swagger.yaml
Remove the other query string for listing repositories/artifacts and add some new TODO items
> Update the swagger

- src/api/artifact/controller.go
- src/api/artifact/controller_test.go
- src/api/event/handler/init.go
- src/api/event/handler/internal/artifact.go
- src/api/event/handler/internal/artifact_test.go
- src/api/repository/controller.go
- src/api/repository/controller_test.go
- src/pkg/repository/dao/dao.go
- src/pkg/repository/dao/dao_test.go
- src/pkg/repository/manager.go
- src/pkg/repository/manager_test.go
- src/server/registry/manifest.go
- src/testing/api/repository/controller.go
- src/testing/pkg/repository/manager.go
> Enable pull time on getting manifest

- api/v2.0/swagger.yaml
- tests/apitests/python/library/artifact.py
- tests/apitests/python/library/base.py
- tests/apitests/python/library/cnab.py
- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/library/scan.py
- tests/apitests/python/library/scanner.py
- tests/apitests/python/test_add_sys_label_to_tag.py
- tests/apitests/python/test_copy_artifact_outside_project.py
- tests/apitests/python/test_create_delete_tag.py
- tests/apitests/python/test_del_repo.py
- tests/apitests/python/test_edit_project_creation.py
- tests/apitests/python/test_garbage_collection.py
- tests/apitests/python/test_manage_project_member.py
- tests/apitests/python/test_project_level_policy_content_trust.py
- tests/apitests/python/test_project_quota.py
- tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
- tests/apitests/python/test_push_cnab_bundle.py
- tests/apitests/python/test_push_index_by_docker_manifest.py
- tests/apitests/python/test_retention.py
- tests/apitests/python/test_robot_account.py
- tests/apitests/python/test_scan_image_artifact.py
- tests/apitests/python/test_sign_image.py
- tests/apitests/python/test_system_level_scan_all.py
- tests/robot-cases/Group0-BAT/API_DB.robot
Fixed issue: #10990 #10767 #10768.
> Modify api test for test step of add addition

- src/api/event/metadata/quota.go
- src/api/event/topic.go
- src/api/quota/controller.go
- src/core/api/notification_policy.go
- src/pkg/distribution/distribution.go
- src/pkg/distribution/distribution_test.go
- src/pkg/notification/notification.go
- src/pkg/quota/errors.go
- src/pkg/quota/models/quota.go
- src/pkg/quota/models/quota_test.go
- src/server/middleware/notification/notification.go
- src/server/middleware/notification/notification_test.go
- src/server/middleware/quota/copy_artifact.go
- src/server/middleware/quota/copy_artifact_test.go
- src/server/middleware/quota/put_manifest.go
- src/server/middleware/quota/put_manifest_test.go
- src/server/middleware/quota/quota.go
- src/server/middleware/quota/quota_test.go
1. Send notification when request resources exceeded the quota limitation.
2. Send notification when quota usage exceeded 85% of the quota limitation.
> feat(quota,notification): notification for quota exceeded and warning

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
To improve the performance of loading repository page, make the query set thinner.
> simplify query string when to list artifact

- api/v2.0/legacy_swagger.yaml
Remove the useless definitions in lagacy swagger.yaml
> Remove the useless definitions in lagacy swagger.yaml

- src/internal/error/errors.go
1, New support construct with string or err
2, Add Wrap/Errorf method
> update common error

- src/server/v2.0/handler/base.go
- src/server/v2.0/handler/project.go
- tests/apitests/python/library/base.py
- tests/apitests/python/library/projectV2.py
- tests/apitests/python/test_user_view_logs.py
- tests/robot-cases/Group0-BAT/API_DB.robot
1, enable user view log api test case
2, update project logs api permission check
3, use project ctl instead in permission check base method
> Enable API logs test case

- src/jobservice/worker/cworker/c_worker_test.go
remove the status checking loop
> fix[js_ut]:update stop job case of js

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
> Modify Nightly popular Keyword Go-Into-Repo

- src/core/controllers/controllers_test.go
- src/portal/src/app/sign-in/sign-in.component.html
- src/portal/src/app/sign-in/sign-in.component.ts
- src/server/route.go
fixes #10712
The functions in CommonController are kept as a reference.
> Remove route entry to reset password

- src/api/chartmuseum/controller.go
- src/api/project/controller.go
- src/api/quota/util.go
- src/api/quota/util_test.go
- src/core/api/internal.go
- src/core/service/notifications/admin/handler.go
- src/testing/api/project/controller.go
Refresh quota usages of all the projects after GC.
> feat(gc,quota): refersh quotas for projects after gc

- src/portal/src/app/project/repository/repository-gridview.component.ts
> [fix] fix repo pagination

- tests/robot-cases/Group1-Nightly/Common_GC.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
> Analyze nightly failed cases

- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Project-Artifact-Elements.robot
- tests/resources/Harbor-Pages/Project-Artifact.robot
- tests/resources/Harbor-Pages/Project-Copy-Elements.robot
- tests/resources/Harbor-Pages/Project-Copy.robot
- tests/resources/Harbor-Pages/ToolKit.robot
- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/resources/Harbor-Util.robot
- tests/resources/TestCaseBody.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Modify elements locator in nightly tests

- make/install.sh
Signed-off-by: ren maosheng <stevenr@vmware.com>
> Fix a typo in the help message of install.sh

- Makefile
- make/photon/prepare/Dockerfile.base
- tests/integration.sh
fix build_base_docker, not exit when fail
fix build prepare image fail
> feat(cicd) fix build_base_docker and prepare image for 1.10.2

- src/pkg/audit/dao/dao.go
- src/pkg/audit/dao/dao_test.go
- src/server/v2.0/handler/auditlog.go
- src/server/v2.0/handler/base.go
add a base method to require system admin permission
> Add permission check for audit logs API

- src/api/event/handler/init.go
- src/api/event/handler/webhook/artifact/replication.go
- src/api/event/handler/webhook/artifact/replication_test.go
- src/api/event/metadata/replication.go
- src/api/event/topic.go
- src/common/dao/pgsql.go
- src/core/api/notification_policy.go
- src/core/service/notifications/jobs/handler.go
- src/pkg/notification/notification.go
- src/pkg/notifier/model/event.go
> Replication webhook support

- .github/workflows/netlify.yml
This will trigger a new build of the main website as soon as new docs are merged to master.
The required secret needs to be added to the project.
Signed-off-by: jonasrosland <jrosland@vmware.com>
> Trigger a new Netlify build when new docs are merged

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Harbor-Pages/ToolKit.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Modify nightly test case for user view logs and other

- tests/apitests/python/test_push_index_by_docker_manifest.py
> Remove some content of verification for artifact addtion

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
- src/portal/src/app/project/repository/artifact/artifact-summary.component.html
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.spec.ts
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/shared/list-repository-ro/list-repository-ro.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.html
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.scss
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Vulnerability.robot
1.edit case(less)
2.vunerbility refresh bug fix #11212
3.scan mutiple artifact
4.fix global search bug ;fix #11159
5.disable delete tag btn when remove immutable tag; fix #11200
6.cancel selectRow when add label or remove label;fix #11195; fix #11173
7.fix cron tootip;fix #11227 
8.fix #11224 ;fix #11258; fix #11259
> [Fix]   Fix issue 2.0

- src/core/api/registry.go
Use the same logic to parse the registry URL to fix #11274
> Use the same logic to parse the registry URL

- tests/docker-compose.test.yml
fix #10254 ut case is not covering redis config
> feat(cicd) fix redis container version for test

- src/controller/blob/controller.go
- src/controller/blob/controller_test.go
- src/server/middleware/quota/put_blob_upload.go
- src/server/middleware/quota/put_blob_upload_test.go
- src/server/middleware/quota/quota.go
> fix(quota): allowed to put blob which size is zero

- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/resources/Harbor-Pages/Vulnerability_Elements.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
Test Case - Trivy Is Default Scanner And It Is Immutable
Test Case - Disable Scan Schedule
Test Case - Scan A Tag In The Repo
Test Case - Scan As An Unprivileged User
Test Case - Manual Scan All
Test Case - View Scan Error
Test Case - Scan Image On Push
Test Case - View Scan Results
> [Nightly] Add case for trivy

- src/portal/src/app/project/repository/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.html
- src/portal/src/app/project/repository/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.scss
- src/portal/src/app/project/repository/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
Fix #11082
New UI for limited successful result:
> Modify UI for scanning result

- src/replication/filter/artifact.go
Fixes #11233, make sure the tag filter have the same behavior for empty value and *
> Make sure the tag filter have the same behavior for empty value and *

- docs/1.10/build-customize-contribute/e2e-api-python-based-scripting-guide.md
This PR marks an in-progress document as a draft to prevent it from being published in the production goharbor.io site.
cc @michmike @jonasrosland
> Mark incomplete doc as draft

- src/jobservice/logger/getter/file_getter.go
> fix[logger]:update log ID validation logic

- src/jobservice/period/enqueuer_test.go
- change the test cron spec
- use cretaed timer for timeout
> fix[UT]:improve the UT cases of enqueuer

- src/server/v2.0/handler/util.go
- src/server/v2.0/handler/util_test.go
> fix(log): change log level from warning to debug when unescape path params

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.scss
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
- src/portal/src/app/project/repository/vulnerability-scanning/result-grid.component.ts
- src/portal/src/app/project/repository/vulnerability-scanning/result-tip-histogram/result-tip-histogram.component.ts
- src/portal/src/app/project/webhook/webhook.component.html
- src/portal/src/app/project/webhook/webhook.component.scss
- src/portal/src/app/project/webhook/webhook.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.html
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.scss
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.spec.ts
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.ts
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.spec.ts
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.ts
Fix #11079 
Fix #11189 
Fix #11208 
Fix #11234
Fix #11210
> Fix bugs for round 1 testing

- src/jobservice/job/impl/notification/webhook_job.go
- src/jobservice/job/impl/notification/webhook_job_test.go
- src/pkg/scan/job_test.go
- src/testing/jobservice/context.go
Fixes #11280, no error return but just log.
> Does not throw err in the notification job

- src/core/api/scan_all.go
- src/core/api/scan_all_test.go
> fix(scan): ongoing is true for schedule scan all only when job is running

- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/gc/garbage_collection_test.go
- src/testing/registryctl/client.go
Fixes #11313
Fixes #11275
1, Add more details log in GC job
2, Add type assertion for the upgrading case, the delete_untagged parameter is introduced from v2.0
> fix GC jobs upgrade issue

- make/pushimage.sh
- tests/integration.sh
- tests/resources/Harbor-Util.robot
fix some cicd build base image problems
> feat(cicd) fix build base image

- src/pkg/registry/auth/authorizer.go
- src/pkg/registry/client.go
- src/replication/policy/scheduler/scheduler.go
- src/replication/transfer/image/transfer.go
1. Add timeout when transter artifacts
2. Check 404 error when unschedule the policy
3. Add line to mark the job failure in job log
> Some tiny improvement for replication

- src/portal/src/app/project/webhook/webhook.component.html
- tests/resources/Harbor-Pages/Project-Webhooks.robot
- tests/resources/Harbor-Pages/Project-Webhooks_Elements.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Fix nightly cases for webhook

- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/gc/garbage_collection_test.go
Fix#11190, delete all of non-referenced blobs of each project in GC job, thun the quota
can be released.
> add clean untagged blobs in gc job

- src/chartserver/handler_manipulation.go
- src/chartserver/handler_proxy_traffic_test.go
- src/chartserver/reverse_proxy.go
- src/chartserver/reverse_proxy_test.go
- src/core/api/chart_repository.go
- src/core/api/chart_repository_test.go
- src/core/api/harborapi_test.go
- src/pkg/clients/core/chart.go
- src/portal/src/app/shared/shared.module.ts
- src/portal/src/lib/entities/service.config.ts
- src/portal/src/lib/harbor-library.module.ts
- src/portal/src/lib/services/label.service.ts
- src/portal/src/lib/utils/utils.ts
- src/replication/adapter/harbor/chart_registry.go
- src/replication/adapter/harbor/chart_registry_test.go
- src/server/middleware/quota/upload_chart_version.go
- src/server/middleware/quota/util_test.go
- src/server/middleware/security/oidc_cli.go
- src/server/middleware/util/util.go
- src/server/route.go
- src/server/v2.0/route/legacy.go
- tests/apitests/python/test_list_helm_charts.py
- tests/apitests/python/testutils.py
1. Revert chart api to /api/chartrepo
2. Chart label still is /api/v2.0
3. Fix ui for these
> Rever chart api change

- src/jobservice/common/rds/scripts.go
- add default values for the integer vars converted by tonumber()
- fix #11361 
> fix[lua_scripts]:add default values for tonumber

- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.scss
- src/portal/src/lib/services/permission-static.ts
- tests/robot-cases/Group1-Nightly/Trivy.robot
1.add nightly case of scan emptyVul repo
2.modify css style 
3.fix bug add label
> [Nightly] add case about trivy

- docs/1.10/install-config/_index.md
Signed-off-by: xaleeks <xalex@vmware.com>
> small change

- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Project-Artifact-Elements.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Helm-Util.robot
- tests/robot-cases/Group0-Util/helm_push_chart.sh
- tests/robot-cases/Group1-Nightly/Common.robot
> Add nightly test of push helm chart

- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- tests/robot-cases/Group1-Nightly/Trivy.robot
1.add trivy case : Project Level Image Serverity Policy.
2.one translation modification
> [Nightly] Project Level Image Serverity Policy

- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.scss
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.spec.ts
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.ts
- src/portal/src/app/project/webhook/add-webhook/add-webhook.component.scss
- src/portal/src/app/project/webhook/last-trigger/last-trigger.component.html
- src/portal/src/app/project/webhook/last-trigger/last-trigger.component.spec.ts
- src/portal/src/app/project/webhook/last-trigger/last-trigger.component.ts
- src/portal/src/app/project/webhook/webhook.component.html
- src/portal/src/app/project/webhook/webhook.component.scss
- src/portal/src/app/project/webhook/webhook.component.spec.ts
- src/portal/src/app/project/webhook/webhook.component.ts
- src/portal/src/app/project/webhook/webhook.service.spec.ts
- src/portal/src/app/project/webhook/webhook.service.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
Fix #11232 
UX: https://www.figma.com/proto/cPY9Lh8LbIQawAJSGmi1KA/Harbor-v2.0?node-id=22%3A12961&viewport=758%2C611%2C0.09731162339448929&scaling=min-zoom
Env.: https://10.161.79.96:8081
> Improve webhook UI according to the UX

- src/pkg/notification/policy/manager/manager.go
> fix webhook slack test error

- tests/apitests/python/test_scan_all_images.py
- tests/resources/Harbor-Pages/HomePage.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/ToolKit.robot
- tests/resources/Util.robot
> Close scan plugin popup message to avoid interfereing logout operation

- docs/1.10/working-with-projects/project-configuration/implementing-content-trust.md
> Add notary remove part in notary_guide.md

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
https://jenkins11.svc.eng.vmware.com/job/harbor_nightly_result_publisher/7332/robot/report/log.html
> [Test Case] Add nightly case for CVE

- src/pkg/scan/vuln/report.go
> fix(scan): dump nil slice of vulnerabilities as empty slice in report

- make/photon/chartserver/Dockerfile
- make/photon/clair-adapter/Dockerfile
- make/photon/core/Dockerfile
- make/photon/jobservice/Dockerfile
- make/photon/prepare/scripts/gencert.sh
- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
- make/photon/registry/Dockerfile
- make/photon/registryctl/Dockerfile
- make/photon/trivy-adapter/Dockerfile
- Fix unhealthy status of harbor containers
- Add harbor_ca to jobservice trust store
> Fix container unhealth

- Makefile
- make/photon/Makefile
- tests/ci/distro_installer.sh
- tests/resources/Harbor-Util.robot
> Remove migrator flags in script

- tests/resources/Harbor-Util.robot
Fix typo of spaces cause failure
> Add spaces

- make/photon/trivy-adapter/entrypoint.sh
> Add missiong entrypoint file for trivy-adapter

- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.html
- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
> Improve UI for p2p_preheat

- Makefile
- make/photon/Makefile
- make/photon/chartserver/Dockerfile
- make/photon/clair-adapter/Dockerfile
- make/photon/clair/Dockerfile
- make/photon/core/Dockerfile
- make/photon/db/Dockerfile
- make/photon/jobservice/Dockerfile
- make/photon/log/Dockerfile
- make/photon/nginx/Dockerfile
- make/photon/notary-server/Dockerfile
- make/photon/notary-signer/Dockerfile
- make/photon/portal/Dockerfile
- make/photon/prepare/Dockerfile
- make/photon/redis/Dockerfile
- make/photon/registry/Dockerfile
- make/photon/registryctl/Dockerfile
- make/photon/trivy-adapter/Dockerfile
- tests/ci/ut_install.sh
In order to make harbor build more flexible, also parameterize docker base image and external url
> feat(cicd) parameterize docker base image and external url

- src/jobservice/period/enqueuer.go
- schedule the periodical jobs following the UTC timezone
- e.g: 5 10 10 * * * means run jobs at UTC time 10:10:05 everyday
- fix issue #11466
> fix[jobservice]:enqueue job with UTC

- src/pkg/p2p/preheat/provider/kraken.go
> fix kraken CheckProgress issue

- src/portal/src/app/distribution/distribution-history/distribution-history.component.ts
- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.html
- src/portal/src/app/distribution/distribution-interface.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
> P2p preheat

- docs/1.10/build-customize-contribute/e2e-api-python-based-scripting-guide.md
- docs/1.10/working-with-projects/project-configuration/implementing-content-trust.md
- tests/ci/distro_installer.sh
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/TestCaseBody.robot
- tests/resources/Util.robot
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/multi_scanners.robot
> Add Multi-Scanner test file

- src/server/middleware/vulnerable/vulnerable.go
- src/server/middleware/vulnerable/vulnerable_test.go
> fix(vulnerable): fix the wrong count of vulnerabilities in message

- api/swagger.yaml
- api/v2.0/swagger.yaml
1. Add version API to swagger
2. Update the description for query
> Add version API to swagger

- src/pkg/signature/notary/helper.go
Fixes #11510, just log the signature not found error in debug mode when deleting artifacts
> Just log the signature not found error in debug mode

- src/replication/adapter/harbor/base/adapter.go
- src/replication/adapter/harbor/base/chart_registry.go
- src/replication/adapter/harbor/base/client.go
- src/replication/adapter/harbor/v1/client.go
- src/replication/adapter/harbor/v2/client.go
Fixes #11480
Fixes #11461
Fix replication failure in kubernetes with hairpin mode disabled
> Fix replication failure in kubernetes with hairpin mode disabled

- README.md
> Update the link of CI badge

- src/jobservice/period/enqueuer_test.go
- eliminate the time of cron spec  overflow issue in the UT case
- fix issue #11492 
> fix(js UT cases):fix the cron spec bug

- src/pkg/scan/init.go
- src/pkg/scan/init_test.go
Resolves: #11310
Signed-off-by: Daniel Pacak <pacak.daniel@gmail.com>
> fix(scanner): Do not override the default scanner on init

- make/photon/jobservice/Dockerfile
- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
- make/photon/registryctl/Dockerfile
1. Fix trivy config rendering issue
2. Fix healthcheck in mTLS
> Fix internal tls issues

- tests/apitests/python/test_assign_role_to_ldap_group.py
Fixes #11094, uncomment the verification logic in the ldap group test case
> Uncomment the verification logic in the ldap group test case

- make/photon/portal/Dockerfile
- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
- src/portal/src/app/dev-center/dev-center-base.ts
- src/portal/src/app/dev-center/dev-center-other.component.spec.ts
- src/portal/src/app/dev-center/dev-center-other.component.ts
- src/portal/src/app/dev-center/dev-center.module.ts
- src/portal/src/app/harbor-routing.module.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
1. Partial helm api version number clear
2. Separate swagger to get v2.0 swagger and chart swagger
3. router add chart swagger
> Separate swagger to get v2.0 swagger and chart swagger

- tests/resources/Docker-Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Modify quota error info due to product changed

- src/common/dao/group/usergroup_test.go
- src/common/dao/project.go
> Exclude deleted projects when counting groups associated with group ID - cherrypick to 1.10

- src/common/dao/group/usergroup_test.go
- src/common/dao/project.go
> Exclude deleted groups when counting groups associated with group ID

- src/pkg/blob/dao/dao.go
- src/pkg/blob/dao/dao_test.go
> fix(blob): delete project blob with project_id

- src/common/config/context.go
- src/controller/scan/base_controller.go
- src/controller/scan/base_controller_test.go
- src/jobservice/job/impl/context.go
- src/pkg/robot/model/robot.go
- src/pkg/scan/dao/scanner/model.go
- src/pkg/scan/job.go
- src/pkg/scan/job_test.go
- src/pkg/scan/rest/v1/models.go
- src/server/middleware/contenttrust/contenttrust.go
- src/server/middleware/contenttrust/contenttrust_test.go
- src/server/middleware/util/util.go
- src/server/middleware/vulnerable/vulnerable.go
- src/server/middleware/vulnerable/vulnerable_test.go
> feat(scan): revert bearer token support for scanner

- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
- tests/resources/Harbor-Pages/Project-Artifact-Elements.robot
- tests/resources/Harbor-Pages/Project-Artifact.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add new nightly cases for tag CRUD

- src/lib/errors/const.go
- src/lib/errors/errors.go
- src/lib/errors/errors_test.go
1, remove the code from output
2, output format is same as pkg/errors, it's easy to migrate
3, add UT
> update internal error output format

- src/pkg/registry/auth/authorizer.go
Close the reponse body after reading data
> Close the reponse body after reading data

- src/portal/src/app/config/scanner/config-scanner.service.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact-common-properties/artifact-common-properties.component.ts
- src/portal/src/app/project/repository/artifact/artifact.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/push-image/push-image.component.html
- src/portal/src/lib/components/push-image/push-image.component.spec.ts
- src/portal/src/lib/components/push-image/push-image.component.ts
- src/portal/src/lib/components/push-image/push-image.scss
1.add pull/push command in repo;
2.move annotations from artifact list to artifact summary
fix #11194
fix #11556
https://jenkins11.svc.eng.vmware.com/job/harbor_nightly_result_publisher/7496/
> [feat] Add pull/push command in repo

- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/project/repository/repository-gridview.component.html
- src/portal/src/app/project/repository/repository-gridview.component.ts
> Fix repo list sorting and filtering bug

- src/portal/src/i18n/lang/en-us-lang.json
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Configuration_Elements.robot
- tests/resources/Harbor-Pages/Project-Artifact.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add new nightly case for GC untagged images

- make/photon/prepare/templates/registry/config.yml.jinja
- src/common/http/tls.go
- src/core/main.go
- src/jobservice/api/server.go
- src/registryctl/main.go
> Min version tls to 12

- src/server/error/error.go
Use level error instead to log trace
> update trace level to error

- src/jobservice/job/impl/gc/garbage_collection.go
- src/jobservice/job/impl/gc/garbage_collection_test.go
- src/testing/jobservice/context.go
Stop GC job in the init if receives the stop signal
> handle stop signal in GC job

- tests/resources/Harbor-Pages/Project-Repository_Elements.robot
> [Test] Fix view log error

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
- src/controller/scanner/base_controller.go
- src/core/api/scanners.go
- src/core/main.go
- src/pkg/scan/init.go
- src/pkg/scan/init_test.go
> feat(scanner): make Clair and Trivy as reserved name for scanners

- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/resources/Harbor-Pages/Vulnerability_Elements.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
- tests/robot-cases/Group1-Nightly/Upgrade.robot
https://jenkins11.svc.eng.vmware.com/job/harbor_nightly_result_publisher/7493/robot/report/log.html
https://jenkins11.svc.eng.vmware.com/job/harbor_nightly_result_publisher/7495/robot/report/log.html
> [test-case] add switch scanner case

- src/portal/src/lib/components/config/gc/gc.component.html
- src/portal/src/lib/components/config/gc/gc.component.ts
> Modify gc ui

- tests/robot-cases/Group1-Nightly/Trivy.robot
- tests/robot-cases/Group1-Nightly/Upgrade.robot
- tests/robot-cases/Group1-Nightly/multi_scanners.robot
> nightly move switch scanner case to mutiple-scanner file

- src/chartserver/handler_manipulation.go
- src/chartserver/reverse_proxy.go
- src/core/api/chart_repository.go
Use the new event model to fix bug for replicating chart triggered by event
> Fix bug for replicating chart triggered by event

- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.spec.ts
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
> [feat] Add pop up command when delete signed tag

- src/common/http/client.go
Create a transport the same as default except forceattempthttp2
> Fix: Default Transport HTTP2 related hang issue

- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
> [Fixed] Fix issue when delete signed tag

- tests/apitests/python/test_robot_account.py
- tests/ci/api_common_install.sh
- tests/ci/api_run.sh
- tests/robot-cases/Group0-BAT/API_DB.robot
> Clean up gitaction env and add tag for pytest

- src/jobservice/job/impl/notification/http_helper.go
- src/jobservice/job/impl/notification/http_helper_test.go
- src/jobservice/job/impl/notification/slack_job.go
- src/jobservice/job/impl/notification/slack_job_test.go
- src/jobservice/job/impl/notification/webhook_job.go
- src/jobservice/job/known_jobs.go
- src/jobservice/job/priority.go
- src/jobservice/job/priority_test.go
- src/jobservice/runtime/bootstrap.go
- src/pkg/notifier/handler/notification/slack_handler.go
https://github.com/goharbor/harbor/issues/11281
> fix slack rate limit issue

- src/core/controllers/base.go
> Enable userExists only when self-registration is turned on.

- .github/workflows/CI.yml
- Makefile
- tests/ci/api_common_install.sh
- tests/ci/api_run.sh
- tests/hostcfg.sh
> fix some cicd problems

- make/harbor.yml.tmpl
- make/photon/prepare/migrations/version_2_0_0/harbor.yml.jinja
- make/photon/prepare/utils/configs.py
- tests/hostcfg.sh
Remove to avoid replication access core from external_url issue
> Hidden veriify client cert verfiy option

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.ts
> Fix bugs for testing kick 3

- src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/webhook/webhook.component.html
- src/portal/src/app/project/webhook/webhook.component.scss
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.ts
- src/portal/src/lib/components/replication/replication.component.html
[cherry-pick][Fixed] Fix issue #11334 #11252 #11191 ；fix  #11698  ;
> [cherry-pick][Fixed] Fix issue #11334 #11252 #11191 #11698  

- src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/webhook/webhook.component.html
- src/portal/src/app/project/webhook/webhook.component.scss
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.ts
- src/portal/src/lib/components/replication/replication.component.html
fix #11334 ;
fix #11252;
fix #11191
> [Fixed] Fix issue #11334 #11252 #11191

- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.ts
> [cherry-pick]Fix bugs for testing kick 3

- api/v2.0/legacy_swagger.yaml
> fix(retention) add extras field to retention swagger

- src/controller/artifact/model.go
- src/go.mod
- src/lib/encode/repository/repository.go
- src/lib/encode/repository/repository_test.go
- src/pkg/clients/core/image.go
- src/replication/adapter/harbor/v2/client.go
fix #11701
tag retention does not handle the extra "/" in repository, need encode the slash twice
> fix(retention) fix retention repository with slash

- make/photon/prepare/utils/configs.py
if absolute url is enabled return true else set it to false
> Fix chart museum absolute url issue

- src/jobservice/job/impl/notification/slack_job.go
- src/jobservice/lcm/controller.go
- src/jobservice/runner/redis.go
> fix(jobservice):fix job stats NOT_FOUND issue

- src/pkg/retention/job.go
> [cherry-pick]fix(retention) not retry retention job

- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.html
> Destination namespace should support slash

- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.html
> [Cherry-pick]Destination namespace should support slash

- src/controller/event/handler/init.go
- src/controller/event/handler/internal/artifact.go
- src/controller/event/handler/internal/util.go
- src/controller/event/handler/internal/util_test.go
- src/lib/orm/orm.go
> feat(scan): support to scan artifact automatic after it pushed

- src/controller/event/handler/init.go
- src/controller/event/handler/internal/artifact.go
- src/controller/event/handler/internal/util.go
- src/controller/event/handler/internal/util_test.go
- src/lib/orm/orm.go
> [Cherry pick]feat(scan): support to scan artifact automatic after it pushed

- src/controller/artifact/model.go
- src/lib/encode/repository/repository.go
- src/lib/encode/repository/repository_test.go
- src/pkg/clients/core/image.go
- src/replication/adapter/harbor/v2/client.go
> [cherry-pick]Fix retention repository with slash 2.0.0

- api/v2.0/legacy_swagger.yaml
> [cherry-pick]Fix retention swagger 2.0.0

- src/jobservice/job/impl/notification/slack_job.go
- src/jobservice/lcm/controller.go
- src/jobservice/runner/redis.go
> [CHERRY-PICK]: fix(jobservice):fix job stats NOT_FOUND issue

- make/photon/prepare/commands/gencerts.py
> Enhance: output the stdout of gen cert script

- src/controller/event/handler/webhook/quota/quota.go
- src/controller/event/metadata/quota.go
- src/controller/event/metadata/quota_test.go
- src/server/middleware/quota/post_initiate_blob_upload.go
- src/server/middleware/quota/post_initiate_blob_upload_test.go
- src/server/middleware/quota/put_blob_upload.go
- src/server/middleware/quota/put_blob_upload_test.go
- src/server/middleware/quota/put_manifest.go
- src/server/middleware/quota/util.go
> feat(quota,webhook): send quota webhook for put and mount blob

- make/photon/prepare/commands/prepare.py
- make/photon/prepare/g.py
- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
- make/photon/prepare/templates/nginx/nginx.https.conf.jinja
- make/photon/prepare/utils/cert.py
- make/photon/prepare/utils/misc.py
this shared ca will mount to all harbor components
> Enhance: Create shared to store shared ca

- src/controller/event/handler/webhook/quota/quota.go
- src/controller/event/metadata/quota.go
- src/controller/event/metadata/quota_test.go
- src/server/middleware/quota/post_initiate_blob_upload.go
- src/server/middleware/quota/post_initiate_blob_upload_test.go
- src/server/middleware/quota/put_blob_upload.go
- src/server/middleware/quota/put_blob_upload_test.go
- src/server/middleware/quota/put_manifest.go
- src/server/middleware/quota/util.go
> [Cherry pick]feat(quota,webhook): send quota webhook for put and mount blob

- src/portal/src/app/user/new-user-modal.component.html
- src/portal/src/app/user/user.component.html
- tests/resources/Harbor-Pages/Administration-Users.robot
- tests/resources/Harbor-Pages/Administration-Users_Elements.robot
- tests/robot-cases/Group1-Nightly/Common.robot
Fix #11691
Result: https://jenkins11.svc.eng.vmware.com/job/harbor_nightly_result_publisher/7884/robot/report/log.html
> Add new nightly case  admin add new users

- tests/apitests/python/library/cnab.py
- tests/apitests/python/library/containerd.py
- tests/apitests/python/library/docker_api.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/library/retention.py
- tests/apitests/python/test_push_chart_by_helm3_chart_cli.py
- tests/apitests/python/test_push_cnab_bundle.py
- tests/apitests/python/test_push_image_with_special_name.py
- tests/apitests/python/test_push_index_by_docker_manifest.py
- tests/apitests/python/test_retention.py
- tests/resources/Harbor-Pages/Administration-Users.robot
- tests/resources/Harbor-Pages/Project-Repository.robot
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
Fixed issue: #11595, #11596, #11015
> Add ctr command for pulling oci

- src/pkg/retention/dep/client.go
fix #11690
fix the pulltime and pushtime for untagged that is null now.
> fix(retention) set pushtime and pulltime for untagged

- make/migrations/postgresql/0030_2.0.0_schema.up.sql
> Webhook data fix when updgrding to 2.0

- tests/robot-cases/Group1-Nightly/Common.robot
> Add tag for ui test case of add new user

- src/portal/src/app/user/new-user-modal.component.html
- src/portal/src/app/user/user.component.html
- tests/resources/Harbor-Pages/Administration-Users.robot
- tests/resources/Harbor-Pages/Administration-Users_Elements.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Cherry-pick 2.0 - Add new nightly case  admin add new users

- tests/robot-cases/Group1-Nightly/Common.robot
> Cherry-pick to 2.0 - Add tag for ui test case of add nuew user

- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
> Fix: GCS storage gc issue

- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/GC.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common_GC.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Add double confirm for clicking untag checkbox

- .github/workflows/conformance_test.yml
- README.md
- tests/ci/conformance_test.sh
1, add a specrate git action for conformance test
2, use the OCI testing code to test Harbor master code on push
> add conformance test to CI

- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/GC.robot
- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Common_GC.robot
- tests/robot-cases/Group1-Nightly/DB.robot
> Fix issue of GC untag images case

- CONTRIBUTING.md
This will update the contributing document with correct links and descriptions.
Signed-off-by: jonasrosland <jrosland@vmware.com>
> Update the contributing document with correct links

- .github/workflows/conformance_test.yml
Fix the report path issue in the action script.
> update the conformance test report path

- make/photon/portal/Dockerfile
- src/portal/package.json
- src/portal/scripts/generate-build-timestamp.js
- src/portal/src/environments/environment.prod.ts
- src/portal/src/environments/environment.ts
- src/portal/src/lib/utils/shared/shared.module.ts
> Improve i18n service

- make/photon/portal/Dockerfile
- src/portal/package.json
- src/portal/scripts/generate-build-timestamp.js
- src/portal/src/app/base/harbor-shell/harbor-shell.component.html
- src/portal/src/app/base/harbor-shell/harbor-shell.component.scss
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.html
- src/portal/src/app/project/repository/artifact/artifact-additions/artifact-vulnerabilities/artifact-vulnerabilities.component.ts
- src/portal/src/environments/environment.prod.ts
- src/portal/src/environments/environment.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/lib/components/create-edit-rule/create-edit-rule.component.scss
- src/portal/src/lib/utils/shared/shared.module.ts
Cherry-pick  PRs #11833 and #11835
> [Cherry-pick]Improve i18n service

- make/photon/log/Dockerfile
> fix: set root password never expire  -- cherry pick to 1.10 branch

- src/controller/event/handler/webhook/artifact/replication.go
> Core panic fix when triggering a webhook of docker-registry replication

- tests/apitests/python/library/retention.py
- tests/apitests/python/test_retention.py
- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Project-Repository.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
- tests/robot-cases/Group1-Nightly/Upgrade.robot
- tests/robot-cases/Group3-Upgrade/data.json
- tests/robot-cases/Group3-Upgrade/feature_map.json
- tests/robot-cases/Group3-Upgrade/prepare.py
- tests/robot-cases/Group3-Upgrade/verify.robot
Fixed issues: #11752, #11849, #11511
> Enhance verificaton for tag retention pytest

- docs/administration/vulnerability-scanning/_index.md
> doc(default scanners):how to determine the system default scanner

- docs/administration/vulnerability-scanning/_index.md
add docs for how to determine the default scanners among the default installed scanners (trivy and clair)
> [CHERRY-PICK]: doc(default scanners):how to determine the system default scanner

- docs/working-with-projects/project-configuration/create-robot-accounts.md
> update robot account document for v2.0.0

- contrib/deploying_using_docker_machine.md
- docs/administration/upgrade/_index.md
- docs/build-customize-contribute/compile-guide.md
- docs/install-config/run-installer-script.md
> feat(doc) change some doc about harbor.yml.tmpl

- docs/_index.md
> Update the version and links in index of doc -cherrypick to 2.0

- docs/_index.md
> Update the version and links in index of doc

- src/portal/src/lib/components/replication/replication-tasks/replication-tasks.component.html
- src/portal/src/lib/components/replication/replication.component.spec.ts
- src/portal/src/lib/components/replication/replication.component.ts
> [Cherry-pick]Fix duration and log bugs for replication task UI

- src/portal/src/lib/components/replication/replication-tasks/replication-tasks.component.html
- src/portal/src/lib/components/replication/replication.component.spec.ts
- src/portal/src/lib/components/replication/replication.component.ts
> Fix duration and log bugs for replication task UI

- contrib/deploying_using_docker_machine.md
- docs/administration/upgrade/_index.md
- docs/build-customize-contribute/compile-guide.md
- docs/install-config/run-installer-script.md
> [cherry-pick] change some doc about harbor.yml.tmpl

- src/controller/event/handler/webhook/artifact/replication_test.go
> Add UT for webhook when replicating with docker registry

- README.md
It needs to use the upper case when to get the badge url
> Fix conformance badge name

- docs/install-config/configure-yml-file.md
> docs(configurtions): add docs for configurations of trivy scanner

- docs/administration/vulnerability-scanning/scan-individual-artifact.md
> docs(scan): fix broken image link for limited successful status

- docs/administration/vulnerability-scanning/scan-individual-artifact.md
> [Cherry pick]docs(scan): fix broken image link for limited successful status

- tests/ci/conformance_test.sh
1, enable test of Content Discovery
2, enable test of Content Management
> enable full set of conformance test

- src/portal/src/app/project/create-project/create-project.component.html
- src/portal/src/app/project/create-project/create-project.component.spec.ts
> Add more UT for create project component

- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Vulnerability.robot
- tests/resources/Harbor-Pages/Vulnerability_Elements.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Common.robot
- tests/robot-cases/Group1-Nightly/Common_GC.robot
- tests/robot-cases/Group1-Nightly/LDAP.robot
- tests/robot-cases/Group1-Nightly/Nightly.robot
- tests/robot-cases/Group1-Nightly/Notary.robot
- tests/robot-cases/Group1-Nightly/OIDC.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
- tests/robot-cases/Group1-Nightly/Schedule.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
- tests/robot-cases/Group1-Nightly/UAA.robot
- tests/robot-cases/Group1-Nightly/multi_scanners.robot
> Add Scan schedule test in nightly

- tests/resources/Docker-Util.robot
- tests/resources/Helm-Util.robot
- tests/resources/Nightly-Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Modify nightly quotas error message verification

- src/pkg/registry/auth/authorizer.go
- src/pkg/registry/auth/bearer/authorizer.go
Fix replication bugs: fix #11974, fix #11939
> Fix replication bugs #11974, #11939

- CONTRIBUTING.md
Signed-off-by: barryz <barryzxb@gmail.com>
> doc typo: corrects the CONTRIBUTING.md

- src/cmd/migrate-patch/main.go
> struct instead of int within signal chan

- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
fixes: #10575
Signed-off-by: Tim Hobbs <timothy.hobbs@ic-consult.com>
> fix: Allow forward slash in destination namespace

- .github/workflows/CI.yml
- tests/ci/api_common_install.sh
> Move docker prune cmd outside of api common install shell script

- Makefile
- tests/integration.sh
fix build_base_docker for 1.10.x
> fix build_base_docker

- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.scss
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.spec.ts
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.ts
- src/portal/src/app/project/webhook/webhook.component.ts
- src/portal/src/lib/utils/utils.ts
> Remove test button for webhook

- Makefile
- make/photon/chartserver/builder
Upgrade chartmuseum version 0.12.0
> Enhance: Upgrade chartmuseum version

- make/photon/prepare/templates/nginx/nginx.http.conf.jinja
- make/photon/prepare/templates/nginx/nginx.https.conf.jinja
> Add timount on nginx configs

- src/pkg/scan/whitelist/manager.go
> [Cherry pick]fix(cve-whitelist): fix panic in `Get` method of whitelist manager

- src/pkg/scan/whitelist/manager.go
> fix(cve-whitelist): fix panic in `Get` method of whitelist manager

- src/replication/adapter/helmhub/adapter_test.go
- src/replication/adapter/helmhub/chart_registry_test.go
- src/replication/adapter/helmhub/client.go
fix https://github.com/goharbor/harbor/issues/11454
> Fix helmhub insecure issue when using with a proxy

- src/portal/lib/src/service/permission-static.ts
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.spec.ts
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.ts
- src/portal/src/app/project/webhook/webhook.component.html
- src/portal/src/app/project/webhook/webhook.component.spec.ts
- src/portal/src/app/project/webhook/webhook.component.ts
- src/portal/src/app/project/webhook/webhook.service.spec.ts
- src/portal/src/app/project/webhook/webhook.service.ts
Fix #12093
Temp Env for 1.10: https://10.184.70.213/
> Fix permission control for webhook

- make/photon/prepare/templates/core/env.jinja
- src/common/config/manager_test.go
- src/common/config/metadata/metadatalist.go
- src/common/const.go
- src/core/config/config.go
> refactor(configuration): cleanup unneeded CLAIR_URL configuration in core

- docs/administration/configure-authentication/_index.md
> Fix typo (ODIC -> OIDC)

- src/portal/src/app/global-message/message.component.html
- src/portal/src/app/global-message/message.component.scss
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
https://10.78.96.167
fix #12092； fix #9863
> [fix] Fix  issue in front ui 2.0.1

- src/portal/src/app/global-message/message.component.html
- src/portal/src/app/global-message/message.component.scss
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
1.fix add label issue
2.fix unauthorized user can contrl page
> [cherry-pick][fix]   issue in front ui 2.0.1

- make/photon/prepare/templates/nginx/nginx.http.conf.jinja
- make/photon/prepare/templates/nginx/nginx.https.conf.jinja
> Add timeout on nginx configs

- Makefile
- tests/apitests/python/test_user_view_logs.py
- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Project-Members.robot
- tests/resources/Harbor-Pages/Project-Tag-Retention.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group1-Nightly/Clair.robot
- tests/robot-cases/Group1-Nightly/Nightly.robot
- tests/robot-cases/Group1-Nightly/Schedule.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
> Add replication schedule test

- tests/resources/Harbor-Pages/HomePage.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> remove close scanner prompt header step

- tests/robot-cases/Group1-Nightly/Schedule.robot
- tests/robot-cases/Group1-Nightly/Trivy.robot
- tests/robot-cases/Group1-Nightly/multi_scanners.robot
> Scan result behavior changed after trivy upgrade

- src/server/v2.0/route/legacy.go
> Remove the API to test a webhook - Cherry pick to 2.0 branch

- src/server/v2.0/route/legacy.go
> Remove the API to test a webhook

- src/portal/src/app/account/account-settings/account-settings-modal.component.spec.ts
- src/portal/src/app/account/password-setting/forgot-password/forgot-password.component.spec.ts
- src/portal/src/app/account/password-setting/password-setting.component.spec.ts
- src/portal/src/app/account/password-setting/reset-password/reset-password.component.spec.ts
- src/portal/src/app/account/sign-up/sign-up.component.spec.ts
- src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
- src/portal/src/app/global-message/message.component.html
- src/portal/src/app/global-message/message.component.scss
- src/portal/src/app/global-message/message.component.ts
- src/portal/src/app/project/create-project/create-project.component.spec.ts
- src/portal/src/app/project/helm-chart/helm-chart.service.ts
- src/portal/src/app/project/member/add-member/add-member.component.spec.ts
- src/portal/src/app/project/member/add-member/add-member.component.ts
- src/portal/src/app/project/member/member.component.ts
- src/portal/src/app/project/tag-feature-integration/immutable-tag/add-rule/add-rule.component.spec.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.spec.ts
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.spec.ts
- src/portal/src/app/project/webhook/webhook.component.spec.ts
- src/portal/src/app/shared/inline-alert/inline-alert.component.spec.ts
- src/portal/src/app/shared/inline-alert/inline-alert.component.ts
- src/portal/src/app/shared/message-handler/message-handler.service.ts
- src/portal/src/lib/components/config/project-quotas/edit-project-quotas/edit-project-quotas.component.spec.ts
- src/portal/src/lib/components/inline-alert/inline-alert.component.ts
- src/portal/src/lib/components/push-image/push-image.component.spec.ts
- src/portal/src/lib/components/replication/replication.component.spec.ts
- src/portal/src/lib/utils/error-handler/error-handler.ts
1.support show relogin when unauthorized  in popup modali
2.change change member role error handle
3.change helm chart service error handle
env: 10.78.96.167
> [fix][unauthorized] Support show relogin when unauthorized  in popup modal

- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.html
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.scss
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.spec.ts
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.ts
- src/portal/src/app/project/webhook/webhook.component.ts
> [Cherry-pick]Remove test button for webhook

- .github/workflows/CI.yml
- tests/apitests/python/library/singularity.py
- tests/apitests/python/test_push_files_by_oras.py
- tests/apitests/python/test_push_sif_by_singularity.py
- tests/robot-cases/Group0-BAT/API_DB.robot
> Add singularity py-test

- src/portal/src/app/account/account-settings/account-settings-modal.component.spec.ts
- src/portal/src/app/account/password-setting/forgot-password/forgot-password.component.spec.ts
- src/portal/src/app/account/password-setting/password-setting.component.spec.ts
- src/portal/src/app/account/password-setting/reset-password/reset-password.component.spec.ts
- src/portal/src/app/account/sign-up/sign-up.component.spec.ts
- src/portal/src/app/base/harbor-shell/harbor-shell.component.spec.ts
- src/portal/src/app/global-message/message.component.html
- src/portal/src/app/global-message/message.component.scss
- src/portal/src/app/global-message/message.component.ts
- src/portal/src/app/project/create-project/create-project.component.spec.ts
- src/portal/src/app/project/helm-chart/helm-chart.service.ts
- src/portal/src/app/project/member/add-member/add-member.component.spec.ts
- src/portal/src/app/project/member/add-member/add-member.component.ts
- src/portal/src/app/project/member/member.component.ts
- src/portal/src/app/project/tag-feature-integration/immutable-tag/add-rule/add-rule.component.spec.ts
- src/portal/src/app/project/tag-feature-integration/tag-retention/add-rule/add-rule.component.spec.ts
- src/portal/src/app/project/webhook/add-webhook-form/add-webhook-form.component.spec.ts
- src/portal/src/app/project/webhook/webhook.component.spec.ts
- src/portal/src/app/shared/inline-alert/inline-alert.component.spec.ts
- src/portal/src/app/shared/inline-alert/inline-alert.component.ts
- src/portal/src/app/shared/message-handler/message-handler.service.ts
- src/portal/src/lib/components/config/project-quotas/edit-project-quotas/edit-project-quotas.component.spec.ts
- src/portal/src/lib/components/inline-alert/inline-alert.component.ts
- src/portal/src/lib/components/push-image/push-image.component.spec.ts
- src/portal/src/lib/components/replication/replication.component.spec.ts
- src/portal/src/lib/utils/error-handler/error-handler.ts
1.support show relogin when unauthorized  in popup modali
2.change change member role error handle
3.change helm chart service error handle
> [cherry-pick][fix][unauthorized] Support show relogin when unauthorized  in popup modal

- src/portal/src/app/shared/about-dialog/about-dialog.component.scss
- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
> [fix][ui] about dialog Icon cutoff in safari

- src/portal/src/app/shared/about-dialog/about-dialog.component.scss
- src/portal/src/css/common.scss
- src/portal/src/css/dark-theme.scss
- src/portal/src/css/light-theme.scss
> [cherry-pick][fix][ui] about dialog Icon cutoff in safari

- src/core/api/label.go
- src/pkg/label/manager.go
- src/pkg/label/manager_test.go
- src/testing/pkg/label/manager.go
Fixes #12112, remove the label from artifacts when deleting a label
> Remove the label from artifacts when deleting a label

- src/core/api/user.go
- src/core/api/user_test.go
> Makes api/users return 401 for request not authenticated - Cherrypick to 2.0

- src/core/api/user.go
- src/core/api/user_test.go
> Makes api/users return 401 for request not authenticated

- tests/resources/Harbor-Pages/Configuration_Elements.robot
- tests/resources/Harbor-Pages/Project-Config-Elements.robot
> Fix nightly issue caused by GC and CVE UI changed

- src/core/api/label.go
- src/pkg/label/manager.go
- src/pkg/label/manager_test.go
- src/testing/pkg/label/manager.go
Fixes #12112, remove the label from artifacts when deleting a label
> [Cherry-pick]Remove the label from artifacts when deleting a label

- api/v2.0/legacy_swagger.yaml
- make/migrations/postgresql/0040_2.1.0_schema.up.sql
- src/common/dao/project.go
- src/common/models/project.go
- src/core/api/project.go
- src/core/api/registry.go
- src/core/promgr/pmsdriver/local/local.go
Update creating project API to support proxy cache project
> Update creating project API to support proxy cache project

- make/migrations/postgresql/0040_2.1.0_schema.up.sql
- src/pkg/task/checkin.go
- src/pkg/task/checkin_test.go
- src/pkg/task/dao/model.go
- src/pkg/task/execution.go
- src/pkg/task/model.go
- src/pkg/task/task.go
Define the task manager interface and data model
> Define the task manager interface and data model

- tests/robot-cases/Group1-Nightly/Setup.robot
> Add harbor version verification case

- .github/workflows/CI.yml
- tests/apitests/python/library/helm.py
- tests/apitests/python/library/project.py
- tests/apitests/python/test_push_chart_by_helm2_helm3_with_robot_Account.py
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/robot-cases/Group1-Nightly/Setup.robot
> Add helm and helm3 CLI py-test

- src/common/secret/store.go
- src/common/security/secret/context.go
- src/common/utils/utils.go
- src/common/utils/utils_test.go
- src/core/config/config.go
- src/core/service/token/authutils.go
Move the RandString() function to utils to avoid dependency cycle
Add harbor-proxyservice secret
> Add temporary secret for harbor proxy service

- tests/apitests/python/library/helm.py
- tests/apitests/python/library/project.py
- tests/apitests/python/test_garbage_collection.py
- tests/apitests/python/test_list_helm_charts.py
- tests/apitests/python/test_push_chart_by_helm2_helm3_with_robot_Account.py
- tests/apitests/python/test_user_view_logs.py
- tests/resources/Harbor-Pages/Project-Artifact.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/robot-cases/Group0-BAT/API_DB.robot
- tests/robot-cases/Group1-Nightly/Common.robot
It fixed issue: #12256, #12087, #12310
> Add API E2E pytest of GC with untag flag enabled

- make/photon/common/install_cert.sh
> feat(certs): install internal tls ca from /etc/harbor/ssl dir

- src/pkg/p2p/preheat/models/provider/instance.go
- src/pkg/p2p/preheat/provider/auth/basic_handler.go
- src/pkg/p2p/preheat/provider/auth/cred.go
- src/pkg/p2p/preheat/provider/auth/custom_handler.go
- src/pkg/p2p/preheat/provider/auth/handler.go
- src/pkg/p2p/preheat/provider/auth/handler_test.go
- src/pkg/p2p/preheat/provider/auth/known_handlers.go
- src/pkg/p2p/preheat/provider/auth/none_handler.go
- src/pkg/p2p/preheat/provider/auth/token_handler.go
- src/pkg/p2p/preheat/provider/client/http_client.go
- src/pkg/p2p/preheat/provider/client/http_client_test.go
- src/pkg/p2p/preheat/provider/dragonfly.go
- src/pkg/p2p/preheat/provider/dragonfly_test.go
- src/pkg/p2p/preheat/provider/driver.go
- src/pkg/p2p/preheat/provider/factory.go
- src/pkg/p2p/preheat/provider/known_drivers.go
- src/pkg/p2p/preheat/provider/known_drivers_test.go
- src/pkg/p2p/preheat/provider/kraken.go
- src/pkg/p2p/preheat/provider/kraken_test.go
- define preheat driver interface
- implement dragonfly driver
- implememt kraken driver
- add related UT cases with testify framework
- fix #10870 #10871
- some code are picked up from the original P2P feat branch
> feat(preheat):add preheat drivers

- src/pkg/p2p/preheat/models/policy/policy.go
- src/pkg/p2p/preheat/models/policy/policy_test.go
> feat: add p2p preheat policy model

- make/photon/common/install_cert.sh
> [Cherry pick]feat(certs): install internal tls ca from /etc/harbor/ssl dir

- src/pkg/p2p/preheat/job.go
- src/pkg/p2p/preheat/job_test.go
- src/pkg/p2p/preheat/models/provider/instance.go
- src/pkg/p2p/preheat/provider/dragonfly_test.go
- src/pkg/p2p/preheat/provider/driver.go
- src/pkg/p2p/preheat/provider/known_drivers.go
- src/pkg/p2p/preheat/provider/kraken_test.go
- src/pkg/p2p/preheat/provider/mock.go
- src/pkg/p2p/preheat/provider/preheat_image.go
- implement the preheat job
- add relevant UT case
- fix issue #12285
> feat(preheat):add preheat job

- src/server/middleware/blob/put_blob_upload.go
- src/server/middleware/blob/put_blob_upload_test.go
After blob is uploaded success, the middleware will update the blob status accordingly.
> handle blob status chanage in put blob middlware

- make/migrations/postgresql/0040_2.1.0_schema.up.sql
- src/pkg/p2p/preheat/dao/policy/dao.go
- src/pkg/p2p/preheat/dao/policy/dao_test.go
- src/pkg/p2p/preheat/models/policy/policy.go
- src/pkg/p2p/preheat/models/policy/policy_test.go
- src/pkg/p2p/preheat/policy/manager.go
- src/pkg/p2p/preheat/policy/manager_test.go
> feat: add p2p preheat policy dao and manager(#12286)

- src/pkg/blob/dao/dao.go
- src/pkg/blob/dao/dao_test.go
- src/pkg/blob/manager.go
- src/pkg/blob/manager_test.go
- src/testing/pkg/blob/manager.go
> add get GC candidate

- .github/workflows/codeql-analysis.yml
> feat(code):enable code security scanning

- src/portal/src/app/project/create-project/create-project.component.html
- src/portal/src/app/project/create-project/create-project.component.spec.ts
- src/portal/src/app/project/create-project/create-project.component.ts
- src/portal/src/app/project/create-project/create-project.scss
- src/portal/src/app/project/helm-chart/helm-chart-detail/chart-detail/chart-detail.component.spec.ts
- src/portal/src/app/project/list-project/list-project.component.html
- src/portal/src/app/project/list-project/list-project.component.ts
- src/portal/src/app/project/project-detail/project-detail.component.html
- src/portal/src/app/project/project-detail/project-detail.component.scss
- src/portal/src/app/project/project-detail/project-detail.component.ts
- src/portal/src/app/project/project.ts
- src/portal/src/app/project/summary/summary.component.html
- src/portal/src/app/project/summary/summary.component.scss
- src/portal/src/app/project/summary/summary.component.spec.ts
- src/portal/src/app/project/summary/summary.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/services/project.service.ts
Temp Env: https://10.185.12.35
UX: https://www.figma.com/proto/cPY9Lh8LbIQawAJSGmi1KA/Harbor-v2.0?node-id=1%3A2481&scaling=min-zoom
Changed points:
> Add proxy cache ui

- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/app/shared/list-repository-ro/list-repository-ro.component.ts
- src/portal/src/lib/components/replication/replication.component.html
1.[replication] sccess rate should be displayed as 0 when status is inprogress
2.[repository] fix get repo name error when the repo contains the project name field
> [fix] [replication] Success rate should be displayed as 0 when status is inprogress

- tests/apitests/python/library/replication.py
- tests/apitests/python/library/repository.py
- tests/apitests/python/library/tag_immutability.py
- tests/apitests/python/test_replication_from_dockerhub.py
- tests/apitests/python/test_sign_image.py
- tests/robot-cases/Group0-BAT/API_DB.robot
> Verify error message when deleting signed image

- api/v2.0/legacy_swagger.yaml
- make/photon/prepare/templates/core/env.jinja
- src/controller/event/handler/webhook/artifact/replication_test.go
- src/core/api/project.go
- src/core/api/registry.go
- src/core/api/replication_policy_test.go
- src/core/config/config.go
- src/go.mod
- src/replication/dao/registry.go
- src/replication/dao/registry_test.go
- src/replication/event/handler_test.go
- src/replication/model/registry.go
- src/replication/registry/manager.go
Suport filtering registries by type in listing registry API
> Suport filtering registries by type in listing registry API

- api/v2.0/swagger.yaml
> fix: adjust p2p preheat policy swagger yaml definitions

- src/jobservice/job/impl/gc/garbage_collection.go
- src/pkg/artifactrash/dao/dao.go
- src/pkg/artifactrash/dao/dao_test.go
- src/pkg/artifactrash/manager.go
- src/pkg/artifactrash/manager_test.go
- src/testing/pkg/artifactrash/manager.go
support with time window to filter and delete item in artifact trash
> add time windows support in artifact trash

- src/portal/src/app/project/create-project/create-project.component.ts
> Add query string for getting registry

- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
> feat(preheat): add healthcheck methods for p2p preheat controller

- src/server/v2.0/handler/preheat.go
- src/server/v2.0/handler/preheat_test.go
Add logic of preheat instance methods without RBAC.
> Instance handler.

- src/controller/artifact/controller.go
- src/controller/artifact/controller_test.go
- src/controller/event/handler/init.go
- src/controller/event/handler/p2p/preheat.go
- src/controller/event/handler/p2p/preheat_test.go
- src/controller/event/metadata/label.go
- src/controller/event/topic.go
- src/controller/p2p/preheat/enforcer.go
> Add P2P trigger event and handler

- make/migrations/postgresql/0040_2.1.0_schema.up.sql
- src/pkg/p2p/preheat/dao/instance/dao.go
- src/pkg/p2p/preheat/dao/instance/dao_test.go
- src/pkg/p2p/preheat/dao/policy/dao_test.go
- src/pkg/p2p/preheat/policy/manager.go
- src/pkg/p2p/preheat/policy/manager_test.go
- src/server/v2.0/handler/preheat.go
- src/server/v2.0/handler/preheat_test.go
1. instance/policy name validation
2. create instance(name unique)/policy (name and project_id unique)
3. policy manager parse policy
> fix(preheat): validate instance/policy name and set unique name

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/preheat.go
Add preheat APIs, handlers.
1. Manual preheat.
2. Instance health check.
> Preheat and healthcheck

- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.ts
- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
> Query preheat instance by name

- src/common/rbac/const.go
- src/common/rbac/project_rbac_role.go
- src/server/v2.0/handler/preheat.go
Enable RBAC control in the preheat API
> Enable RBAC control in the preheat API

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/preheat.go
Close https://github.com/goharbor/harbor/issues/12444
> feat(preheat): add list providers under project level handler

- src/server/middleware/repoproxy/proxy.go
- src/server/middleware/repoproxy/proxy_test.go
- src/server/registry/route.go
Add middleware for blob and manifest push operation
> Add disable push for proxy project

- src/controller/event/handler/replication/replication.go
- src/controller/event/handler/webhook/artifact/artifact.go
- src/controller/event/handler/webhook/artifact/replication.go
- src/controller/event/handler/webhook/artifact/replication_test.go
- src/controller/event/handler/webhook/chart/chart.go
- src/controller/event/handler/webhook/quota/quota.go
- src/controller/event/handler/webhook/scan/scan.go
Fix webhook bug for getting proejct metadata failed.
> Fix  project metadata for webhook

- make/photon/prepare/commands/migrate.py
- make/photon/prepare/migrations/version_1_10_0/__init__.py
- make/photon/prepare/migrations/version_1_9_0/__init__.py
- make/photon/prepare/migrations/version_1_9_0/harbor.yml.jinja
- make/photon/prepare/migrations/version_2_0_0/__init__.py
- make/photon/prepare/tests/migrations/utils_test.py
- make/photon/prepare/utils/migration.py
1. Change down version to list to accept multi verstion value
2. Update search function use BFS to find migration path
2. Add test case
> Enhance: Support multi downversion in migration

- tests/apitests/python/library/project.py
- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/resources/Harbor-Pages/Replication_Elements.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Add push-based replication test in nightly

- src/pkg/registry/auth/authorizer.go
- src/pkg/registry/auth/bearer/authorizer.go
Fix replication bugs: fix #11974, fix #11939
> [Cherry-pick]Fix replication bugs #11974, #11939

- src/jobservice/core/controller.go
> fix(jobservice):add job id in log getting error

- src/core/api/registry.go
Don't return the error detail back to the client when adding registry to avoid security issue
> [Cherry-pick]Don't return the error detail back to the client when adding registry

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/artifact.go
Prevent copying artifact to a proxy cache project
> Prevent copying artifact to a proxy cache project

- src/controller/blob/controller.go
- src/controller/blob/controller_test.go
- src/pkg/blob/dao/dao.go
- src/pkg/blob/dao/dao_test.go
- src/pkg/blob/manager.go
- src/pkg/blob/manager_test.go
- src/server/middleware/blob/head_blob.go
- src/server/middleware/blob/util.go
- src/testing/controller/blob/controller.go
- src/testing/pkg/blob/manager.go
For the deleting blob which marked for more than 2 hours, it should be set to delete failed in head blob & put manifest request
> fix blob deleting status issue

- src/replication/adapter/huawei/huawei_adapter.go
fix #12466
SWR replication adapter can not do pull-based replication
> fix SWR replication adapter pull-based

- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Replication.robot
- tests/robot-cases/Group1-Nightly/Replication.robot
> Fix issues in replication tests

- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.ts
- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
- src/portal/src/app/group/group.component.ts
- src/portal/src/app/project/helm-chart/list-chart-versions/helm-chart-versions-detail/helm-chart-version.component.ts
- src/portal/src/app/project/helm-chart/list-charts-detail/helm-chart.component.ts
- src/portal/src/app/project/list-project/list-project.component.ts
- src/portal/src/app/project/member/add-group/add-group.component.ts
- src/portal/src/app/project/member/member.component.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/app/project/robot-account/robot-account.component.ts
- src/portal/src/app/user/user.component.ts
- src/portal/src/app/user/user.service.ts
- src/portal/src/lib/components/endpoint/endpoint.component.ts
- src/portal/src/lib/components/label/label.component.ts
- src/portal/src/lib/components/list-replication-rule/list-replication-rule.component.ts
- src/portal/src/lib/components/replication/replication.component.ts
fix #11268  includes the following functions:
delete group  delete chart version  delete project   delete member  add group    delete repo  delete artifact   delete tag   delete robot  delete user   delete registry   delete label  delete replication list     replication     distribution
env: 10.78.96.167
> [fix][ui] Operation unified processing session expired

- src/replication/adapter/huawei/huawei_adapter.go
fix Huawei SWR replication adapter pull-based
> [cherry-pick] fix SWR replication adapter pull-based

- api/v2.0/swagger.yaml
- make/migrations/postgresql/0040_2.1.0_schema.up.sql
- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.ts
- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
- src/server/v2.0/handler/preheat.go
Fix:
1. ping instance always ok
2. update instance not work
3. policy creation_time/update_time nil
4. policy swagger add provider name
> fix(preheat): fix preheat handler PingInstance and UpdateInstance

- src/core/api/project.go
- src/pkg/retention/policy/models.go
Remove images that are not visited in last 7 days
Add a build method in policy models.go
> Add default retention policy

- src/portal/src/app/project/summary/summary.component.html
- src/portal/src/app/project/summary/summary.component.spec.ts
- src/portal/src/app/project/summary/summary.component.ts
> Get registrry from project summary api

- src/common/utils/ldap/ldap.go
- src/core/auth/ldap/ldap.go
> Release connection after search ldap user

- src/common/utils/ldap/ldap.go
- src/core/auth/ldap/ldap.go
>  Release connection after search ldap user (cherry-pick)

- src/pkg/p2p/preheat/dao/instance/dao.go
> Fix: preheat install update transaction.

- src/controller/p2p/preheat/enforcer.go
- src/pkg/p2p/preheat/job.go
- src/pkg/p2p/preheat/policy/filter.go
- src/pkg/p2p/preheat/policy/filter_test.go
- src/pkg/p2p/preheat/policy/manager.go
- fix invalid data type of vulnerability filter param
- add more debug logs
- add more logs in the preheat job
- fix issue of getting empty list when doing querying artifacts
> fix(p2p-preheat):fix issues of triggering preheat

- src/portal/src/app/project/create-project/create-project.component.ts
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/config/project-quotas/project-quotas.component.ts
> Fix ui bugs with label target2.1.0

- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
- src/portal/src/app/project/p2p-provider/policy/policy.component.ts
- src/portal/src/app/project/p2p-provider/task-list/task-list.component.html
- src/portal/src/app/project/p2p-provider/task-list/task-list.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Fixes #12581 
Fixes #12580 
Fixes #12579
Temp Env: https://10.185.12.35:4200 
> Improve p2p-preheat ui

- src/portal/src/app/project/robot-account/robot.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.html
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.scss
- src/portal/src/lib/components/config/vulnerability/vulnerability-config.component.ts
- src/portal/src/lib/components/operation/operate.ts
- src/portal/src/lib/components/operation/operation.component.css
- src/portal/src/lib/components/operation/operation.component.ts
- src/portal/src/lib/components/operation/operation.service.spec.ts
Fixes #12157 
Fixes #12151 
Fixes #12143 
Fixes #10100
> Fix css bugs with label target 2.1.0

- make/photon/prepare/templates/core/app.conf.jinja
- make/photon/prepare/templates/core/env.jinja
- make/photon/prepare/utils/core.py
the port should be flexible depend on the internal tls
> Fix: beego app config port hardcode

- src/controller/event/handler/replication/replication.go
- src/controller/event/handler/webhook/artifact/artifact.go
- src/controller/event/handler/webhook/artifact/replication.go
- src/controller/event/handler/webhook/artifact/replication_test.go
- src/controller/event/handler/webhook/chart/chart.go
- src/controller/event/handler/webhook/quota/quota.go
- src/controller/event/handler/webhook/scan/scan.go
#	src/controller/event/handler/webhook/artifact/replication_test.go
> Fix for project metadata

- src/controller/event/handler/p2p/preheat.go
- src/controller/p2p/preheat/enforcer.go
- fix issue of missing handling error in the preheat event handler
- change preheat artifact logic to reduce health check times
- publish pushed events only for the tagged artifacts
> fix(preheat):fix issues of event-based preheat

- tests/apitests/python/library/system.py
- tests/apitests/python/test_garbage_collection.py
> Add checkpoint of no deletion for untagged image

- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
- src/core/api/base.go
- src/pkg/p2p/preheat/models/policy/policy.go
- src/pkg/retention/controller.go
- src/server/v2.0/handler/preheat.go
> Schedule preheat policy.

- api/v2.0/legacy_swagger.yaml
- src/common/models/project.go
- src/core/api/project.go
- src/core/api/replication_policy.go
- src/replication/dao/policy_test.go
- src/replication/model/policy.go
Include the registry info in the project summary API for proxy cache project
> Include the registry info in the project summary API for proxy cache project

- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
- src/pkg/p2p/preheat/policy/manager.go
- src/pkg/p2p/preheat/policy/manager_test.go
- src/pkg/p2p/preheat/provider/client/http_client.go
- fix npe issue in create/update policy
- fix issue of missing schedule job id in the preheat policy
> fix(preheat): fix npe issues

- src/jobservice/job/impl/gc/garbage_collection.go
- src/pkg/blob/dao/dao.go
- src/server/middleware/blob/head_blob.go
- src/server/middleware/blob/util.go
1, update typo in the update blob status sql, the typo will not impact the sql result.
2, correct blob status in the middleware & GC job log.
> revise the blob logs

- src/common/secret/store.go
- src/common/security/proxycachesecret/context.go
- src/common/security/proxycachesecret/context_test.go
- src/common/security/secret/context.go
- src/controller/proxy/local.go
- src/core/config/config.go
- src/core/middlewares/middlewares.go
- src/lib/patterns.go
- src/lib/patterns_test.go
- src/pkg/proxy/secret/authorizer.go
- src/pkg/proxy/secret/authorizer_test.go
- src/server/middleware/artifactinfo/artifact_info.go
- src/server/middleware/artifactinfo/artifact_info_test.go
- src/server/middleware/repoproxy/proxy.go
- src/server/middleware/repoproxy/proxy_test.go
- src/server/middleware/security/proxy_cache_secret.go
- src/server/middleware/security/proxy_cache_secret_test.go
- src/server/middleware/security/security.go
- src/server/middleware/v2auth/access.go
- src/server/registry/route.go
Limit the permission of secret used by proxy cache service, fixes #12257
> Limit the permission of secret used by proxy cache service

- src/common/job/const.go
- src/core/api/reg_gc.go
- src/jobservice/job/impl/gcreadonly/garbage_collection.go
- src/jobservice/job/impl/gcreadonly/garbage_collection_test.go
- src/jobservice/job/impl/gcreadonly/util.go
- src/jobservice/job/known_jobs.go
- src/jobservice/runtime/bootstrap.go
Add the read only job as a back up plan, user still can use it but just with API, and specify the parameter read_only:true
> add gc read only job

- make/photon/prepare/commands/migrate.py
- make/photon/prepare/migrations/__init__.py
- make/photon/prepare/migrations/version_2_1_0/__init__.py
- make/photon/prepare/migrations/version_2_1_0/harbor.yml.jinja
db_max_open_comms should be 1000 if its value between 100 and 1000
> Add migration 2.1.0

- src/replication/adapter/gitlab/adapter.go
fix #12605
replication from gitlab with more namespace is not working
> fix[replication] gitlab pull-based multi namespace

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/preheat.go
> fix(preheat): fix preheat task log display

- src/portal/src/app/project/create-project/create-project.component.html
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.html
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.scss
- src/portal/src/lib/components/cron-schedule/cron-schedule.component.ts
Fixes #12630
Fixes #12057
Temp Env: https://10.185.12.35:4202
> Improve cron component and create project component

- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.html
- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.html
- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.scss
- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.spec.ts
- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
- src/portal/src/app/project/p2p-provider/policy/policy.component.html
- src/portal/src/app/project/p2p-provider/policy/policy.component.scss
- src/portal/src/app/project/p2p-provider/policy/policy.component.spec.ts
- src/portal/src/app/project/p2p-provider/policy/policy.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Temp Env.: https://10.185.12.35:4200
Changed point:
> Improve p2p UI

- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.html
- src/portal/src/app/project/repository/artifact/artifact-tag/artifact-tag.component.ts
Fixes #11944
Temp Env: https://10.185.12.35:4201
Changed point:
> Add pull command by tag for artifact detail page

- src/replication/adapter/huawei/huawei_adapter.go
- src/replication/adapter/huawei/image_registry.go
> [CHERRY-PICK]fix(replication): huawei adapter multi authorization

- src/pkg/p2p/preheat/dao/instance/dao.go
- src/pkg/p2p/preheat/dao/instance/dao_test.go
> Fix bug of update preheat instance default.

- make/photon/chartserver/Dockerfile
- make/photon/clair-adapter/Dockerfile
- make/photon/clair/Dockerfile
- make/photon/db/Dockerfile
- make/photon/log/Dockerfile
- make/photon/nginx/Dockerfile
- make/photon/redis/Dockerfile
- make/photon/registry/Dockerfile
- make/photon/trivy-adapter/Dockerfile
The export is dynamical now because of introduce of internal TLS
> Remove expose port in dockerfiles

- src/server/v2.0/handler/preheat.go
Close https://github.com/goharbor/harbor/issues/12584
> fix(preheat): check running executions when delete policy

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/preheat.go
> fix(preheat): provider more info about p2p provider instance

- api/v2.0/swagger.yaml
- src/controller/task/controller.go
- src/controller/task/controller_test.go
- src/controller/task/execution_controller.go
- src/controller/task/execution_controller_test.go
- src/pkg/task/execution.go
- src/pkg/task/execution_test.go
- src/pkg/task/mock_task_manager_test.go
- src/pkg/task/task.go
- src/pkg/task/task_test.go
- src/server/v2.0/handler/preheat.go
- src/testing/pkg/task/execution_manager.go
- src/testing/pkg/task/manager.go
> fix(preheat): add pagination for execution and task list api

- make/common/templates/nginx/nginx.https.conf
- make/common/templates/nginx/notary.server.conf
- tests/travis/ut_install.sh
> disable tls v1.1

- make/photon/log/Dockerfile
Signed-off-by: Yiyang Huang <huangyiyang@caicloud.io>
> fix: set root password never expire

- src/common/utils/passports.go
- src/replication/adapter/aliacr/adapter.go
- src/replication/adapter/dockerhub/adapter.go
- src/replication/adapter/harbor/v1/adapter.go
- src/replication/adapter/harbor/v2/adapter.go
- src/replication/adapter/jfrog/adapter.go
- src/replication/adapter/native/adapter.go
Show the detail error message when failed to fetch the artifacts during replication
> Show the detail error message when failed to fetch the artifacts during replication

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/preheat.go
> fix(preheat): add precheck when delete instance

- src/controller/p2p/preheat/enforcer.go
- src/controller/p2p/preheat/enforcer_test.go
- use content trust settings of project configurations
- use vulnerability severity settings of project configurations
> fix(preheat):leverage project settings

- make/harbor.yml.tmpl
Resolves: #11985
Signed-off-by: Daniel Pacak <pacak.daniel@gmail.com>
> docs: Explain how to use Trivy in offline mode

- .dockerignore
> Ignore folders that not need when build docker image

- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
- src/server/v2.0/handler/preheat.go
> fix(preheat): add precheck before disable instance

- .drone.yml
- tests/integration.sh
> Modify e2e image for drone build

- .drone.yml
- tests/integration.sh
- tests/robot-cases/Group0-Distro-Harbor/package-offline-installer.robot
- tests/robot-cases/Group0-Distro-Harbor/package-online-installer.robot
> Recovery drone build script

- src/jobservice/job/impl/gc/garbage_collection.go
> fix gc foreign layer issue

- .drone.yml
- .github/workflows/CI.yml
- tests/apitests/python/library/docker_api.py
- tests/ci/api_common_install.sh
- tests/e2e-image/drone/Dockerfile
- tests/e2e-image/nightly/Dockerfile
- tests/generateCerts.sh
- tests/integration.sh
- tests/robot-cases/Group0-Distro-Harbor/package-offline-installer.robot
- tests/robot-cases/Group0-Distro-Harbor/package-online-installer.robot
> Upgrade python and robot for drone build

- src/portal/src/lib/services/endpoint.service.ts
- src/replication/adapter/quay/adapter.go
> fix(replication): fix quay adapter authorization

- src/controller/blob/controller.go
- src/controller/blob/controller_test.go
- src/jobservice/job/impl/gc/garbage_collection.go
> fix(blob): make blob size in redis expired in 24 hours

- make/photon/prepare/migrations/version_2_1_0/harbor.yml.jinja
> Fix: append trivy every time when run migrate

- .drone.yml
- tests/e2e-image/drone/Dockerfile
- tests/integration.sh
> Add git/golang/dns config in drone iamge

- make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja
To void trivy can not start issue
> Add log denpendency ti trivy

- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Verify.robot
- tests/resources/TestCaseBody.robot
- tests/robot-cases/Group3-Upgrade/data.json
- tests/robot-cases/Group3-Upgrade/prepare.py
> Fix wrong keyword issue in upgrade test

- tests/integration.sh
> test key files in CI

- api/v2.0/swagger.yaml
- src/server/v2.0/handler/preheat.go
> fix(preheat): fix the swagger definition of preheat get log api

- src/server/v2.0/handler/scan.go
- tests/apitests/python/library/base.py
- tests/apitests/python/library/scan.py
- tests/apitests/python/test_scan_image_artifact_in_public_project.py
- tests/apitests/python/testutils.py
- tests/robot-cases/Group0-BAT/API_DB.robot
> fix(scan): fix the permission checking for artifact scanning

- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
- src/pkg/p2p/preheat/policy/manager.go
> [FIX] Delete executions of the P2P policy.

- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.html
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.ts
- src/portal/src/app/project/repository/artifact/artifact-summary.component.html
- src/portal/src/app/project/repository/artifact/artifact-summary.component.spec.ts
- src/portal/src/app/project/repository/artifact/artifact-summary.component.ts
- src/portal/src/app/project/repository/artifact/artifact.service.spec.ts
- src/portal/src/app/project/repository/artifact/artifact.service.ts
- src/portal/src/app/project/repository/artifact/artifact.ts
Related backend PR #12683(need to merge first)
Fixes #12706
> get artifact icon from backend API

- src/portal/src/app/config/scanner/config-scanner.component.html
- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.html
- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.html
- src/portal/src/app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts
- src/portal/src/app/project/list-project/list-project.component.html
- src/portal/src/app/project/list-project/list-project.component.ts
- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.html
- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.scss
- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.spec.ts
- src/portal/src/app/project/p2p-provider/add-p2p-policy/add-p2p-policy.component.ts
- src/portal/src/app/project/p2p-provider/policy/policy.component.html
- src/portal/src/app/project/p2p-provider/policy/policy.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
- src/portal/src/lib/components/endpoint/endpoint.component.html
- src/portal/src/lib/services/interface.ts
Fixes #12758 
Fixes #12757 
Fixes #12746 
Fixes #12744 
Fixes #12728 
Fixes #12725 
Fixes #12718
Fixes #12716 
Fixes #12715 
Fixes #12703
> Fix UI bugs found on testing day for target 2.1

- Makefile
- tests/ci/api_common_install.sh
In git action, use the local build base images instead of pulling from docker hub.
> build base image in CI

- src/common/models/cve_allowlist.go
- src/common/models/cve_allowlist_test.go
- src/controller/p2p/preheat/enforcer.go
- src/pkg/scan/report/summary.go
- src/pkg/scan/report/summary_test.go
- src/server/middleware/vulnerable/vulnerable.go
> refactor(scan): remove duplicate CVESet types

- src/portal/src/app/project/repository/artifact-list-page/artifact-list/artifact-list-tab/artifact-list-tab.component.spec.ts
> Improve UI UT for artifact list page

- src/common/dao/label.go
- src/common/dao/notification/notification_policy.go
- src/replication/dao/policy.go
- src/replication/dao/policy_test.go
1, order label by creation time.
2, order webhook policy by creation time.
3, order replication policy by creation time.
> udpate resource list order

- src/portal/src/app/services/intercept-http.service.ts
- src/portal/src/lib/utils/shared/shared.module.ts
> Change storage of csrf token from cookie to localstorage

- src/portal/src/app/config/auth/config-auth.component.html
- src/portal/src/app/config/auth/config-auth.component.ts
- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.html
- src/portal/src/app/project/repository/repository-gridview.component.html
- src/portal/src/app/project/repository/repository-gridview.component.ts
- src/portal/src/app/sign-in/sign-in.component.html
- src/portal/src/app/sign-in/sign-in.component.spec.ts
- src/portal/src/app/sign-in/sign-in.component.ts
- src/portal/src/i18n/lang/en-us-lang.json
- src/portal/src/i18n/lang/es-es-lang.json
- src/portal/src/i18n/lang/fr-fr-lang.json
- src/portal/src/i18n/lang/pt-br-lang.json
- src/portal/src/i18n/lang/tr-tr-lang.json
- src/portal/src/i18n/lang/zh-cn-lang.json
- src/portal/src/i18n/lang/zh-tw-lang.json
Fixes #12759 
Fixes #12737
Fixes #12723 
Fixes #12711 
Fixes #12696 
> Fix issues with label target 2.1 and RC

- src/portal/src/app/services/intercept-http.service.ts
> Add more safe request methods

- src/server/v2.0/handler/scan.go
- tests/apitests/python/library/base.py
- tests/apitests/python/library/scan.py
- tests/apitests/python/test_scan_image_artifact_in_public_project.py
- tests/apitests/python/testutils.py
- tests/robot-cases/Group0-BAT/API_DB.robot
> [Cherry pick]fix(scan): fix the permission checking for artifact scanning

- make/photon/portal/Dockerfile
> Fix schema of the portal health check

- tests/resources/Docker-Util.robot
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Configuration_Elements.robot
- tests/resources/Harbor-Pages/Project.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add distribution UI test in nightly

- src/server/middleware/quota/quota.go
> fix(quota): change log to debug level when warning not found

- src/portal/src/app/distribution/distribution-instances/distribution-instances.component.html
- src/portal/src/app/project/create-project/create-project.component.html
- src/portal/src/app/project/p2p-provider/policy/policy.component.ts
> Fix UI issues found on round-2 testing day

- src/controller/p2p/preheat/controller.go
- src/controller/p2p/preheat/controllor_test.go
Closes: https://github.com/goharbor/harbor/issues/12843, https://github.com/goharbor/harbor/issues/12842
> fix(p2p): disable change provider vendor type

- src/controller/p2p/preheat/controller.go
> Fix schedule error msg.

- src/pkg/registry/client.go
- src/replication/adapter/googlegcr/adapter.go
- src/testing/pkg/registry/client.go
> fix(replication) gcr deletion and tag deletion

- src/controller/event/operator/operator.go
- src/controller/proxy/controller.go
- src/server/registry/manifest.go
> refactor(event): change default operator to username of security

- make/migrations/postgresql/0040_2.1.0_schema.up.sql
> Make the 2.1.0 migration SQL script idempotent

- .drone.yml
- tests/integration.sh
> Update drone e2e image to release 2.0.0

- src/controller/event/handler/auditlog/auditlog.go
- src/controller/event/handler/auditlog/auditlog_test.go
- src/controller/event/handler/internal/artifact.go
- src/controller/event/handler/p2p/preheat.go
- src/controller/event/handler/p2p/preheat_test.go
- src/controller/event/handler/replication/replication.go
- src/controller/event/handler/webhook/artifact/artifact.go
- src/controller/event/handler/webhook/artifact/replication.go
- src/controller/event/handler/webhook/artifact/replication_test.go
- src/controller/event/handler/webhook/artifact/retention.go
- src/controller/event/handler/webhook/chart/chart.go
- src/controller/event/handler/webhook/chart/chart_test.go
- src/controller/event/handler/webhook/quota/quota.go
- src/controller/event/handler/webhook/quota/quota_test.go
- src/controller/event/handler/webhook/scan/delete.go
- src/controller/event/handler/webhook/scan/scan.go
- src/controller/event/handler/webhook/scan/scan_test.go
- src/controller/event/topic.go
- src/pkg/notifier/handler/notification/http_handler.go
- src/pkg/notifier/handler/notification/http_handler_test.go
- src/pkg/notifier/handler/notification/slack_handler.go
- src/pkg/notifier/handler/notification/slack_handler_test.go
- src/pkg/notifier/notification_handler.go
- src/pkg/notifier/notifier.go
- src/pkg/notifier/notifier_test.go
fixes #12554
Add string method for each event, and the detail can be logged in the core.log
> fix event log issue

- tests/integration.sh
> Change pybot to robot in release 2.0.0

- make/migrations/postgresql/0040_2.1.0_schema.up.sql
- src/controller/artifact/controller.go
- src/controller/artifact/controller_test.go
- src/controller/artifact/processor/chart/chart.go
- src/controller/artifact/processor/chart/chart_test.go
- src/controller/artifact/processor/cnab/cnab.go
- src/controller/artifact/processor/cnab/cnab_test.go
- src/controller/artifact/processor/default.go
- src/controller/artifact/processor/default_test.go
- src/controller/artifact/processor/image/index.go
- src/controller/artifact/processor/image/index_test.go
- src/controller/artifact/processor/image/manifest_v1.go
- src/controller/artifact/processor/image/manifest_v1_test.go
- src/controller/artifact/processor/image/manifest_v2.go
- src/controller/artifact/processor/image/manifest_v2_test.go
- src/controller/icon/controller.go
- src/controller/icon/controller_test.go
- src/lib/icon/const.go
> Fill in the icon of known artifacts in artifact controller

- src/portal/lib/src/repository-gridview/repository-gridview.component.html
- src/portal/lib/src/repository-gridview/repository-gridview.component.spec.ts
- src/portal/lib/src/repository-gridview/repository-gridview.component.ts
> Fix repos refresh bug

- CONTRIBUTING.md
> docs: add doc for gen apis and mocks

- tests/apitests/python/test_assign_role_to_ldap_group.py
- tests/resources/Harbor-Pages/Configuration.robot
- tests/resources/Harbor-Pages/Configuration_Elements.robot
- tests/resources/Harbor-Pages/Project-P2P-Preheat-Elements.robot
- tests/resources/Harbor-Pages/Project-P2P-Preheat.robot
- tests/resources/Harbor-Pages/Project_Elements.robot
- tests/resources/Util.robot
- tests/robot-cases/Group1-Nightly/Common.robot
> Add P2P Preheat UI Test

- src/server/middleware/repoproxy/proxy.go
When the remote repo is offline or network issue or credential issue, fall back to local repo.
Fixes #12853
>  Fallback to local repo on errors when proxy to remote repo
